### ISSUE TITLE
Whitespace cleanup

### ISSUE THREAD

**Issue by wavexx** [h5py/h5py#1001]
In trying to address #973 I noticed that the sources are somewhat riddled with trailing whitespace.
It's common with both vim and (in my case) emacs for those to get stripped automatically, so they end up showing as diff. Several open PRs show useless whitespace changes for the same reason.

Would you accept a zero-change whitespace cleanup PR?

**Comment by aragilar** [comment]
@wavexx Yes, that would be useful.
