### ISSUE TITLE
h5py.File should support file-like objects

### ISSUE THREAD

**Issue by aparamon** [h5py/h5py#1006]
Currently, `h5py.File` constructor only supports files on disk via one of the built-in drivers: https://github.com/h5py/h5py/blob/3d1edda9036f073bf48d3a53b1692234de4a97b9/h5py/_hl/files.py#L273

It is however possible to implement a custom driver:
https://support.hdfgroup.org/HDF5/doc1.8/TechNotes/VFL.html

A driver wrapping Python file-like object would enable important usage scenarios, one notable example being temp HDF5 stores (via `tempfile.TemporaryFile`, `tempfile.NamedTemporaryFile`).

`pyfive.File` constructor does support "file like object which has read and seek methods which behaves like a Python file object":
https://github.com/jjhelmus/pyfive/blob/46dc0bd19b9126d33e6b4eb7153451f3820103d3/pyfive/high_level.py#L139

**Comment by aragilar** [comment]
This is a similar request to #687. The best option would be to add support to HDF5 to accept arbitrary file handles. The next best thing would be to build an external library which implemented the necessary HDF5 APIs to accept file-like objects (and would need to define what a file-like object acted like). Without either of those happening, I don't see much hope in allowing files to be used, instead of file names.

**Comment by aragilar** [comment]
Note that pyfive explicitly does not depend on HDF5, so there's not much that h5py can use from pyfive in this case.

**Comment by tacaswell** [comment]
I'm going to close this as this is not something we can to at the python level.

**Comment by aparamon** [comment]
Hmm, that was a bit premature! It *is* definitely possible to support file-like objects at Python level, as demonstrated by a script below. I have checked with file objects and `tempfile.TemporaryFile`, but the implementation should work for any object having `read`, `write`, `seek`, `tell`, `flush`, `truncate`, and `close`.

````python
import h5py
from ctypes import *
import os
import sys

hdf5 = CDLL('hdf5')
hid_t = c_int64
herr_t = c_int

class H5FD_t(Structure):
    _fields_ = [('driver_id', hid_t),
                ('cls', c_void_p),  # POINTER(H5FD_class_t)
                ('fileno', c_uint),
                ('access_flags', c_uint),
                ('feature_flags', c_uint),
                ('maxaddr', c_size_t),
                ('base_addr', c_size_t),
                ('threshold', c_size_t),
                ('alignment', c_size_t),
                ('paged_aggr', c_bool)]

class H5FD_class_t(Structure):
    _fields_ = [('name', c_char_p),
                ('maxaddr', c_size_t),
                ('fc_degree', c_int),
                ('terminate', c_void_p),
                ('sb_size', c_void_p),
                ('sb_encode', c_void_p),
                ('sb_decode', c_void_p),
                ('fapl_size', c_size_t),
                ('fapl_get', c_void_p),
                ('fapl_copy', c_void_p),
                ('fapl_free', c_void_p),
                ('dxpl_size', c_size_t),
                ('dxpl_copy', c_void_p),
                ('dxpl_free', c_void_p),
                ('open', CFUNCTYPE(c_void_p, c_char_p, c_uint, hid_t, c_size_t)),
                ('close', CFUNCTYPE(herr_t, POINTER(H5FD_t))),
                ('cmp', c_void_p),
                ('query', c_void_p),
                ('get_type_map', c_void_p),
                ('alloc', c_void_p),
                ('free', c_void_p),
                ('get_eoa', CFUNCTYPE(c_size_t, POINTER(H5FD_t), c_int)),
                ('set_eoa', CFUNCTYPE(herr_t, POINTER(H5FD_t), c_int, c_size_t)),
                ('get_eof', CFUNCTYPE(c_size_t, POINTER(H5FD_t), c_int)),
                ('get_handle', c_void_p),
                ('read', CFUNCTYPE(herr_t, POINTER(H5FD_t), c_int, hid_t, c_size_t, c_size_t, c_void_p)),
                ('write', CFUNCTYPE(herr_t, POINTER(H5FD_t), c_int, hid_t, c_size_t, c_size_t, c_void_p)),
                ('flush', CFUNCTYPE(herr_t, POINTER(H5FD_t), hid_t, c_bool)),
                ('truncate', CFUNCTYPE(herr_t, POINTER(H5FD_t), hid_t, c_bool)),
                ('lock', c_void_p),
                ('unlock', c_void_p),
                ('fl_map', c_int*7)]

class H5FD_fileobj_t(Structure):
    _fields_ = [('base', H5FD_t),
                ('fileobj', py_object),
                ('eoa', c_size_t)]

fileobj_holder = None

@CFUNCTYPE(c_void_p, c_char_p, c_uint, hid_t, c_size_t)
def H5FD_fileobj_open(name, flags, fapl, maxaddr):
    global fileobj_holder
    fileobj_holder = H5FD_fileobj_t(fileobj=cast(int(name), py_object))
    return addressof(fileobj_holder)

@CFUNCTYPE(herr_t, POINTER(H5FD_t))
def H5FD_fileobj_close(f):
    fileobj = cast(f, POINTER(H5FD_fileobj_t)).contents.fileobj
    fileobj.close()
    global fileobj_holder
    fileobj_holder = None
    return 0

@CFUNCTYPE(c_size_t, POINTER(H5FD_t), c_int)
def H5FD_fileobj_get_eoa(f, typ):
    fd = cast(f, POINTER(H5FD_fileobj_t)).contents
    return fd.eoa

@CFUNCTYPE(herr_t, POINTER(H5FD_t), c_int, c_size_t)
def H5FD_fileobj_set_eoa(f, typ, addr):
    fd = cast(f, POINTER(H5FD_fileobj_t)).contents
    fd.eoa = addr
    return 0

@CFUNCTYPE(c_size_t, POINTER(H5FD_t), c_int)
def H5FD_fileobj_get_eof(f, typ):
    fileobj = cast(f, POINTER(H5FD_fileobj_t)).contents.fileobj
    fileobj.seek(0, os.SEEK_END)
    return fileobj.tell()

@CFUNCTYPE(herr_t, POINTER(H5FD_t), c_int, hid_t, c_size_t, c_size_t, c_void_p)
def H5FD_fileobj_read(f, typ, dxpl, addr, size, buf):
    fileobj = cast(f, POINTER(H5FD_fileobj_t)).contents.fileobj
    fileobj.seek(addr)
    memmove(buf, fileobj.read(size), size)
    return 0

@CFUNCTYPE(herr_t, POINTER(H5FD_t), c_int, hid_t, c_size_t, c_size_t, c_void_p)
def H5FD_fileobj_write(f, typ, dxpl, addr, size, buf):
    fileobj = cast(f, POINTER(H5FD_fileobj_t)).contents.fileobj
    fileobj.seek(addr)
    fileobj.write(cast(buf, POINTER(c_byte*size)).contents)
    return 0

@CFUNCTYPE(herr_t, POINTER(H5FD_t), hid_t, c_bool)
def H5FD_fileobj_truncate(f, dxpl, closing):
    fd = cast(f, POINTER(H5FD_fileobj_t)).contents
    fd.fileobj.truncate(fd.eoa)
    return 0

@CFUNCTYPE(herr_t, POINTER(H5FD_t), hid_t, c_bool)
def H5FD_fileobj_flush(f, dxpl, closing):
    fileobj = cast(f, POINTER(H5FD_fileobj_t)).contents.fileobj
    fileobj.flush()
    return 0

info = H5FD_class_t(name=c_char_p(b'fileobj'),
                    maxaddr=sys.maxsize,
                    fc_degree=h5py.h5f.CLOSE_WEAK,
                    open=H5FD_fileobj_open,
                    close=H5FD_fileobj_close,
                    get_eoa=H5FD_fileobj_get_eoa,
                    set_eoa=H5FD_fileobj_set_eoa,
                    get_eof=H5FD_fileobj_get_eof,
                    read=H5FD_fileobj_read,
                    write=H5FD_fileobj_write,
                    truncate=H5FD_fileobj_truncate,
                    flush=H5FD_fileobj_flush)

hdf5.H5FDregister.restype = hid_t
fileobj_driver = hdf5.H5FDregister(pointer(info))

def set_fileobj_fapl(plist):
    hdf5.H5Pset_driver(hid_t(plist.id), hid_t(fileobj_driver), None)

h5py.register_driver('fileobj', set_fileobj_fapl)

# ---

with open('test.h5', 'wb+') as f:

    hf = h5py.File(str(id(f)), driver='fileobj')
    print(hf)
    hf.create_dataset('test', data=list(range(12)))
    hf.flush()
    print(list(hf))
    print(hf['test'][:])
    hf.close()

with open('test.h5', 'rb') as f:

    hf = h5py.File(str(id(f)), 'r', driver='fileobj')
    print(hf)
    print(list(hf))
    print(hf['test'][:])
    hf.close()
````

I did implement only a minimal subset of VFL functions, but that should be enough for initial version. Thorough error checking is also missing; adding it into driver functions should be quite straightforward, although using `set_exception` for debugging `H5Pset_driver()` calls didn't work for me, as per code below:
````python
pythonapi.PyCapsule_GetPointer.restype = c_void_p
pythonapi.PyCapsule_GetPointer.argtypes = [py_object, c_char_p]
set_exception = CFUNCTYPE(c_int)(pythonapi.PyCapsule_GetPointer(
    h5py._errors.__pyx_capi__['set_exception'], c_char_p(b'int (void)')))
````

Hopefully my sketch inspires h5py implementation (using Cython maybe?).

**Comment by leofang** [comment]
Came across this thread from google. It would be very great to see h5py support file-like objects or file descriptors. 

One of possible use cases that will be beneficial to our work is the following: we have many datasets of moderate size (about a few to tens of GB, will be larger in the future) and once a Python interpreter pre-processes one,  we would like to keep it in memory for subsequent MPI processes (spawned by mpi4py, independent of the first Python process) to access. This way we are able to avoid lots of I/O through network disk, but this only works if h5py.File could take a file descriptor so that we can then use the POSIX shared memory mechanism (through posix_ipc + mmap) to get a file descriptor pointing to that memory.

**Comment by tacaswell** [comment]
That code should probably be pushed down to a c-extension rather than using ctypes (as the only place we currently use ctypes is as part of the build process to sort out what version of hdf5 we are dealing with).

Could this live as a stand-alone package under the h5py org?

**Comment by aparamon** [comment]
@tacaswell Yes, c-extension/cython sounds reasonable, but I didn't yet have any experience with that so I started my sketch with familiar ctypes.
I want to prepare an initial pull request including tests and doc-string changes.
Is it expected that I add tests to
`h5py/tests/hl/test_file.py`
or to
`h5py/tests/old/test_file.py`
?

**Comment by tacaswell** [comment]
Can you target `h5py/tests/hl/test_file.py` please?
