### ISSUE TITLE
Parallel HDF5 Corruption Issue

### ISSUE THREAD

**Issue by dmlb2000** [h5py/h5py#1007]
To assist reproducing bugs, please include the following:
 * Operating System - CentOS 7.3
 * Python version - 2.7
 * Where Python was acquired - I use pyenv to build it.
 * h5py version - 2.7.1
 * HDF5 version - 1.10.1
 * mpi4py version - 3.0.0
 * openmpi version - 2.1.2
 * No stack trace but the file is still corrupt

Okay the example program, and maybe the example is fundamentally broken way of interfacing with HDF5 but I'm new to HDF5 in general.
```
from mpi4py import MPI
import h5py

rank = MPI.COMM_WORLD.rank
size = MPI.COMM_WORLD.size

f = h5py.File('parallel_test.hdf5', 'w', driver='mpio', comm=MPI.COMM_WORLD)
g = f.create_group('test_group')

dset = g.create_dataset('test{}'.format(rank), (1,), dtype='i')
dset[0] = rank

f.close()
```

The program seems to complete successfully but when I open it with HDFView the file is corrupted. I expect to see a single data group `test_group` and NP number of data sets `test[0-n]` with a single value in each data set being the value of the rank.

For an example run of 16 processes, I get the `test_group` but only one data set `test6` and the value in the data set is `10` not `6`.

Some background.

I've built hdf and openmpi myself, so here's the configure lines for them

```
../openmpi-2.1.2/configure --prefix=/home/dmlb2000/python-mpi-hdf/install --enable-shared --with-pmi --with-verbs --without-memkind
```
```
export PATH=$PATH:/home/dmlb2000/python-mpi-hdf/install/bin
../hdf5-1.10.1/configure --enable-parallel --enable-shared --prefix=/home/dmlb2000/python-mpi-hdf/install
```

A basic hello world example of mpi4py works, so I'm assuming my openmpi build is okay. The example program on the h5py [website](http://docs.h5py.org/en/latest/mpi.html) works. However, I'm trying to do something slightly differently and that's not working.

Any help would be appreciated.

**Comment by aragilar** [comment]
Quick check, how did you install h5py (as the wheels are currently built with 1.8 on linux)?

**Comment by dmlb2000** [comment]
I've downloaded the source and followed the build instructions (here)[http://docs.h5py.org/en/latest/mpi.html#building-against-parallel-hdf5]

**Comment by aragilar** [comment]
@dmlb2000 Cool, that rules problems with conflicting ABIs. I'll need to set up a parallel build of HDF5/MPI with your settings to test this, so it might be a bit of time before can chase this up, you may want to ask on the mailing list (h5py@googlegroups.com) to see if other people have run into issues (I don't know off the top of my head what versions of openmpi are compatible with HDF5, as that could be a potential problem).

**Comment by dmlb2000** [comment]
Reference, I'm thinking I'm not doing my code right...

https://support.hdfgroup.org/HDF5/doc/RM/CollectiveCalls.html

**Comment by dmlb2000** [comment]
Another data point, I rearranged my code to create all the data sets as a collective operation...
```
from mpi4py import MPI
import h5py

rank = MPI.COMM_WORLD.rank
size = MPI.COMM_WORLD.size

f = h5py.File('fixed.hdf5', 'w', driver='mpio', comm=MPI.COMM_WORLD)
g = f.create_group('test_group')

for i in range(size):
    g.create_dataset('test{}'.format(i), (1,), dtype='i')
dset = g['test{}'.format(rank)]
dset[0] = rank

f.close()
```

This is disappointing as the data set structure I'm creating is quite large and I was hoping to not have to serially create the data sets.

**Comment by dmlb2000** [comment]
I guess it is disappointing as well that the H5Dcreate calls were called with different arguments and it didn't freak out or break the code in anyway. I would expect some sort of stack dump if a required collective operation is called incorrectly across all the MPI ranks. That's the only thought I have now.

**Comment by sethrj** [comment]
Error-checking in parallel is very difficult if not impossible, so HDF5's mechanisms for verifying your commands are limited. Parallel error-checking (e.g. "make sure the dataset name is consistent on all domains") would require parallel communication.

What you're trying to do is an "independent" operation that's different on each domain. Every independent operation must be called with the same data (for technical reasons regarding HDF5's local metadata cache). What you want is a *collective* operation that writes to a single dataset, but each different domain will write to a different range of that dataset.

I highly recommend reading all available [documentation on parallel HDF5](https://portal.hdfgroup.org/display/knowledge/Hints+to+using+Parallel+HDF5?preview=/48809760/48809759/parallelhdf5hints.pdf) because it is not easy to do correctly and *very* difficult to do performantly.

**Comment by dmlb2000** [comment]
@sethrj Thanks for the info, I think we can close this I got enough info to know what I'm doing now.
