### ISSUE TITLE
Strange issues when using scaleoffset and NaN values

### ISSUE THREAD

**Issue by equaeghe** [h5py/h5py#1009]
I am aware that the HDF5 library currently does not correctly deal with NaN values when using the scaleoffset filter. I was investigating how exactly h5py/HDF5 behave in this situation and encountered some strange things.

```python
import numpy as np
import h5py as h5

a = np.abs(np.random.normal(scale=100, size=(100, 100, 100)))
b = a < 100
a[b] = np.nan
np.mean(b)
# 0.68250100000000002

f = h5.File('test.h5', 'w')
f.create_dataset('a', data=a, scaleoffset=0)
np.mean(np.abs(f['a'][~b] - a[~b]))
# 0.079259186906086659, substantially smaller than expected
c = np.isnan(f['a'])
np.any(c) and np.all(np.isnan(a[c]))
# True
np.all(np.isnan(f['a'][b]))
# False, this should be True
should_be_nans.min(), should_be_nans.max()
# (100.00264238895511, 100.36546279537075)
np.mean(c)
# 0.46481800000000001, should be same as for b
np.mean(f['a'][~c & ~b] == a[~c & ~b])
# 0.68225096771958338, a large number is still the same!?
```

I have the impression that applying the scaleoffset filter to data with NaNs is a hazard. Perhaps an exception should be raised when it is tried.

Version info:
```
h5py    2.7.1
HDF5    1.10.1
Python  3.5.4 (default, Jan  5 2018, 23:25:42) 
[GCC 6.4.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.10.4
```
Details: Gentoo linux, using system Python.

**Comment by aragilar** [comment]
The only way to know if there were NaNs being passed (and hence raise an exception) is for h5py to call `np.isnan`, which would be a significant overhead for users who know their data does not contain NaNs. We should document that scaleoffset does not work with NaNs though (a PR doing this would be useful).

**Comment by aragilar** [comment]
Apparently we already warn about this: http://docs.h5py.org/en/stable/high/dataset.html#scale-offset-filter.
