### ISSUE TITLE
[Question] Is the HDF5 library used for windows wheel built by you or the HDF Group?

### ISSUE THREAD

**Issue by vasole** [h5py/h5py#1017]
Hello,

Probably is a question for @cgohlke 

In order to make sure I use the proper built environment, I would like to know if when building the windows wheels, you also compile the HDF5 library or if you use the binaries supplied by the HDF Group.

Thank you.

**Comment by cgohlke** [comment]
I'm using my own builds of HDF5. The HDF Group does not seem to provide VC9, VC10, or VC14.2 binaries.

**Comment by vasole** [comment]
Thanks.
