### ISSUE TITLE
h5py python 3.6 windows wheels break with numpy 1.12

### ISSUE THREAD

**Issue by matthew-brett** [h5py/h5py#1018]
I noticed just now that the Python 3.6 h5py Windows wheels on PyPI are compiled against numpy-1.13, rather than numpy-1.12, which is the earliest version available with wheels, for Python 3.6.  I hit this because I installed numpy 1.12, then h5py, and then I got a puzzling crash when importing h5py, which eventually boiled down to the numpy ABI mismatch.

I think the wheels should be compiled against the earliest numpy reasonably compatible with the relevant Python version. Otherwise, it means it's not unlikely that someone with the earliest version of numpy installed, will get a crash like me, when they install and import h5py.

In practice, I think it's reasonable to compile against the earliest version of numpy that has wheels for that version of Python.  What do y'all think?

**Comment by tacaswell** [comment]
Is the 1.12 vs 1.13 ABI change in numpy known?

**Comment by matthew-brett** [comment]
For example - the OSX and Linux wheels for Python 3.6 compile against numpy 1.11.3, for that reason:

https://github.com/MacPython/h5py-wheels/blob/master/.travis.yml#L80

**Comment by t20100** [comment]
Independently of choosing a version of numpy to build the wheels, you can get the version of numpy in the setup.py and use it as the minimum required version in `install_requires`. Thus the generated wheels always advertise the version of numpy they were built with as a minimal requirement.

Something like:
```
from numpy.version import version
NUMPY_DEP = 'numpy>=%s' % version

```

**Comment by matthew-brett** [comment]
Yes, although that only tells you that the build used some version of numpy  >= that version - so it doesn't tell you what version of numpy you need to install in order for the package to work.  For example, h5py could specify `install_requires` of >=1.11, but then it could build with 1.12, so the user now needs 1.12 installed, otherwise h5py will break - as here.

**Comment by vasole** [comment]
@matthew-brett 

I think what t20100 is proposing avoids exactly the problem you mention.

If h5py was built with 1.12, install_requires would automatically be set to >= 1.12

**Comment by matthew-brett** [comment]
Could do - but the better solution is to build with the earliest compatible version of numpy, to reduce the number of users who are forced to upgrade numpy, by installing h5py.

**Comment by vasole** [comment]
It will not be me who will argue against that (using numpy version 1.9.1 on a Mac OS 10.7)

**Comment by t20100** [comment]
Setting a minimal runtime required version at build time is a safety net, it does not prevent you to use the earliest compatible version of numpy to make the wheels. It just avoids problems in case you don't.

**Comment by tacaswell** [comment]
attn @cgohlke

**Comment by tacaswell** [comment]
This should be fixed for the published windows wheels.
