### ISSUE TITLE
Wrong dataset order when using accentuated letters

### ISSUE THREAD

**Issue by FlorentD42** [h5py/h5py#1029]
```python
import h5py
    
h5f = h5py.File('tmp.h5', 'w')

# dataset containing accentuated letter
h5f.create_dataset('é/aaa', data=0)
h5f.create_dataset('é/bbb', data=0)
h5f.create_dataset('é/ccc', data=0)

# normal dataset
h5f.create_dataset('e/aaa', data=0)
h5f.create_dataset('e/bbb', data=0)
h5f.create_dataset('e/ccc', data=0)

# both normal, sorted outputs
print('é', list(h5f['é']))
print('e', list(h5f['e']))
```
Normal output:
```python
é ['aaa', 'bbb', 'ccc']
e ['aaa', 'bbb', 'ccc']
```
 Closing and opening again :
```python
h5f.close()
h5f = h5py.File('tmp.h5', 'r')

print('é', list(h5f['é']))
print('e', list(h5f['e']))
```
Output in wrong order:
```python
é ['bbb', 'aaa', 'ccc']
e ['aaa', 'bbb', 'ccc']
```
`h5dump` shows the dataset correctly sorted:
```
[...]
 GROUP "é" {
      DATASET "aaa" {
         DATATYPE  H5T_STD_I64LE
         DATASPACE  SCALAR
         DATA {
         (0): 0
         }
      }
      DATASET "bbb" {
         DATATYPE  H5T_STD_I64LE
         DATASPACE  SCALAR
         DATA {
         (0): 0
         }
      }
      DATASET "ccc" {
         DATATYPE  H5T_STD_I64LE
         DATASPACE  SCALAR
         DATA {
         (0): 0
         }
      }
   }
}
}
```

Summary of the h5py configuration
---------------------------------
h5py    2.8.0rc1
HDF5    1.8.18
Python  3.5.4 |Anaconda, Inc.| (default, Feb 19 2018, 10:59:04) 
[GCC 7.2.0]
sys.platform    linux (Ubuntu 16.04.3 LTS)
numpy   1.14.2

**Comment by aragilar** [comment]
Groups are mappings (and internally use dictionaries) so there is no guarantee of order. We could look at using OrderedDicts internally, but it'd be useful to know why you require a specific order (also, if you use Python 3.6 or later, the dict objects are now order maintaining, so you could use that as a workaround).

**Comment by FlorentD42** [comment]
I need a specific order because of how my data is structured and how I need to use it, basically:
```
firstname_lastname/<data_name>
firstname_lastname/<data_name>_std
firstname_lastname/<data_name>_mean
```
where `<data_name>` isn't necessarily known. I need the size of the first set of data so I use 
`data_length = fh[name + '/' + next(fh[name].__iter__())].shape[0]`
Before accents appeared in my data I had no issue with this line, I could make use of the order of the groups. 
I upgraded to Python 3.6 without difference.
My workaround for the moment is to use a (fortunately short) list of all possible values for `<data_name>`.

**Comment by aragilar** [comment]
I dug into this, in the cython level we use `H5_ITER_NATIVE`, which has the comment "No particular order, whatever is fastest". Given we seem to adjust order based on whether creation order is being tracked or not, I'm hesitant to change the current setup.
