### ISSUE TITLE
Option to fcntl.lockf a File

### ISSUE THREAD

**Issue by louisabraham** [h5py/h5py#1035]
It's incredibly hard to find how to write to the same HDF5 file from multiple processes without risk.

I found the solution here: https://github.com/ax3l/lock_file

Don't you think it could be included as an option `lock_file=False` in h5py.File?
It would be especially great to be able to use the contextlib syntax (because it would spare one indentation level).

**Comment by aragilar** [comment]
I'd recommend using MPI if you need multiple processes to write to the same file. Additionally, I'm not sure that such code in the link will work on Windows.
