### ISSUE TITLE
Cannot open HDF file created in H5Py in any other package

### ISSUE THREAD

**Issue by mhearne-usgs** [h5py/h5py#1036]
Operating System:
OSX 10.12.6

Python Version:
Python 3.5.5

Python Acquired:
Miniconda on OSX

H5Py Version:
2.7.1

HDF5 Version:
1.8.17

Stack Trace:
As noted in the title, the problem doesn't seem to be in H5Py, but rather in every other HDF5-related tool I try.  I've created a large (14M) HDF5 file using my own class hierarchy based on H5Py, which I can read/write just fine using those classes. However, when trying to open that file using either h5dump on the command line or the Java HDFView tool I get the error below.

h5dump error: unable to open file "shake_result.hdf"

I'm attaching a text file with the results of running "h5dump --enable-error-stack shake_result.hdf".
[h5dump_results.txt](https://github.com/h5py/h5py/files/2005953/h5dump_results.txt)

I've tried using my classes to create a smaller example, but none of them seemed to reproduce the error.  The file in question can be found here:

ftp://ftpint.usgs.gov/pub/cr/co/golden/hearne/shake_result.hdf

If it is helpful, I tried reading the file in Matlab as well, and the error I get in there looks like this:
Error using hdf5infoc
Call to HDF5 library failed (open_group): "Unable to open group: /__arrays__".

The HDF file is organized into groups by (sort of) data type: strings, dictionaries, lists, pandas dataframes, numpy arrays, etc. Each group is named as you see above with two leading and trailing underscores. Each thing (string, array, etc.) is stored as a dataset with its own name inside the appropriate group, with appropriate serialization techniques applied as needed.

**Comment by aragilar** [comment]
It may be that the Java app and Matlab are using older versions of HDF5, can you check what versions they are using?

**Comment by mhearne-usgs** [comment]
Sorry, that was an internal url:
ftp://ftpext.usgs.gov/pub/cr/co/golden/hearne/shake_result.hdf 
is the correct one.

The hdf library version behind the Matlab code is: 1.8.12
I conda-installed the 1.8.17 version of hdf5 in another venv, and still got the same error from h5dump.

I also tried on a Linux system, where I get the same error with h5dump, and the same success with h5py.

**Comment by aragilar** [comment]
I suspect the file is corrupted, as h5py on my system also fails to read the entire file (here's what I ran):
```python
>>> import h5py
>>> h5py.File("shake_result.hdf")
<HDF5 file "shake_result.hdf" (mode r+)>
>>> f = h5py.File("shake_result.hdf")
>>> f.visititems(lambda *x: print(*x))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    f.visititems(lambda *x: print(*x))
  File "/home/aragilar/.virtualenvs/tmp-325af999aec527f9/lib/python3.6/site-packages/h5py/_hl/group.py", line 479, in visititems
    return h5o.visit(self.id, proxy)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 355, in h5py.h5o.visit
RuntimeError: Object visitation failed (address of object past end of allocation)
```

**Comment by takluyver** [comment]
Closing as there's nothing evident to fix in h5py; feel free to reopen if you can create a minimal reproducible example.
