### ISSUE TITLE
h5py 2.8.0 not yet on pypi

### ISSUE THREAD

**Issue by Anthchirp** [h5py/h5py#1040]
I saw that the 2.8.0 release has been tagged in https://github.com/h5py/h5py/commit/dd51465b22a5e9f0195bd9af8c4ca0be4ee84f58, but the [pypi package points to 2.7.1](https://pypi.org/project/h5py/#description).

I guess the release is still underway?

**Comment by aragilar** [comment]
My understanding is we're waiting on the wheel builders to build the wheels before uploading the sdist.

**Comment by aragilar** [comment]
The sdist and wheels are now on PyPI.
