### ISSUE TITLE
create_dataset multiplies the data size by 10

### ISSUE THREAD

**Issue by louisabraham** [h5py/h5py#1041]
I use
    macOS 10.12.6
    h5py    2.7.1
    HDF5    1.8.18
    Python  3.6.4 |Anaconda, Inc.| (default, Mar 12 2018, 20:05:31) 
    [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
    sys.platform    darwin
    sys.maxsize     9223372036854775807
    numpy   1.14.2

I have to copy a dataset with a specific dtype, so I cannot use Group.copy.

My code looks like this (I iterate on the paths):

    data = fin[path]
    fout.create_dataset(data.name,
                                    shape=data.shape,
                                    dtype=data.dtype,
                                    chunks=data.chunks,
                                    data=data[()])

The resulting file is about 10x the size of the original.

**Comment by aragilar** [comment]
This is under the control of the HDF5 library, either there's a bug in it and there's lots of empty space, or the extra size is being used for something.
