### ISSUE TITLE
require_dataset casting check unexpectedly fails

### ISSUE THREAD

**Issue by NBrierley** [h5py/h5py#1043]
Win10
h5py    2.7.0
HDF5    1.8.15
Python  3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.12.1

group.py call of numpy.can_cast in require_dataset method calls "to" and "from" arguments the wrong way around, leading to failures when e.g. trying to cast unit16 to float64 ("Datatypes cannot be safely cast (existing uint16 vs new float64)"). 

See also https://docs.scipy.org/doc/numpy/reference/generated/numpy.can_cast.html

**Comment by aragilar** [comment]
I'm not sure it is the wrong way round; the dtype passed is a minimum requirement.

**Comment by NBrierley** [comment]
On further investigation I now see that what I was seeing was actually the unexpected interaction with an existing file. I stand corrected - sorry!
