### ISSUE TITLE
whatsnew for 2.8 is missing

### ISSUE THREAD

**Issue by yarikoptic** [h5py/h5py#1064]
Just discovered that in 2.8 (now in conda) the https://github.com/h5py/h5py/issues/1063 so decided to check on the "NEWS" but apparently there were none:

```shell
$> git describe
2.8.0-24-g07f3c36
$> ls docs/whatsnew 
2.0.rst  2.1.rst  2.2.rst  2.3.rst  2.4.rst  2.5.rst  2.6.rst  2.7.1.rst  2.7.rst  2.9.rst  index.rst
```

**Comment by tacaswell** [comment]
https://github.com/h5py/h5py/pull/1054 has this covered. 

https://github.com/h5py/h5py/issues/1046 / https://github.com/h5py/h5py/pull/1047 has a proposed fix for missing highlevel import, but we are still thinking about the right way to fix it (do a fancy deprecation or just put it back).

**Comment by tacaswell** [comment]
#1054 has been merged.
