### ISSUE TITLE
Unable to create file named "prn.hdf5"

### ISSUE THREAD

**Issue by hannu-s** [h5py/h5py#1070]
Following code throws exception:

```
import h5py
import numpy as np
with h5py.File("prn.hdf5", "w") as f:
    f.create_dataset("dataset", data=np.array([[1,2,3],[4,5,6]]))
```

Same outcome occurs if the file name is in uppercase and/or without the hdf5 file extension.
However, it won't reproduce if you remove the dot, e.g. "prnhdf5". Also, I haven't found any other letter combinations that cause this.

### Traceback:

> Traceback (most recent call last):
>   File "...\demo.py", line 3, in <module>
>     with h5py.File("prn.hdf5", "w") as f:
>   File "C:\Users\...\AppData\Local\conda\conda\envs\STOCK\lib\site-packages\h5py\_hl\files.py", line 312, in __init__
>     fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
>   File "C:\Users\...\AppData\Local\conda\conda\envs\STOCK\lib\site-packages\h5py\_hl\files.py", line 148, in make_fid
>     fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
>   File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py\h5f.pyx", line 98, in h5py.h5f.create
> OSError: Unable to create file (unable to open file: name = 'prn.hdf5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 302)

### System info:
```
h5py    2.8.0
HDF5    1.10.2
Python  3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.14.5

Windows 10 Pro version 1803
```

**Comment by cgohlke** [comment]
`PRN` is a reserved file name on Windows. See https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file.

**Comment by hannu-s** [comment]
Thanks!
