### ISSUE TITLE
Wrong filename in quickstart docs?

### ISSUE THREAD

**Issue by travisdickey** [h5py/h5py#1071]
It appears that the wrong file name is given in the [Groups and Hierarchical Organization](http://docs.h5py.org/en/stable/quick.html#groups-and-hierarchical-organization) section of the docs. The docs read:

![capture](https://user-images.githubusercontent.com/4392580/43045728-315df20c-8d8c-11e8-8b65-5a4d3395ae04.PNG)

But this produces an OSError. Replacing 'mydataset.hdf5' with 'mytestfile.hdf5' works.

**Comment by aragilar** [comment]
We probably want to use `'w'` rather than `'r+'` as the mode, would you be able to create a PR fixing this?
