### ISSUE TITLE
Include filename in exception output

### ISSUE THREAD

**Issue by tdegeus** [h5py/h5py#1072]
It would be great to include the filename in the exception output. For example, `h5py.File(fname, 'r')` failed because of some file corruption, but the error stream shows:

```bash
Traceback (most recent call last):
  File "/home/tdegeus/opt/bin/HDF5pp_merge", line 182, in <module>
    source = h5py.File(fname, 'r')
  File "/home/tdegeus/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/tdegeus/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 96, sblock->base_addr = 0, stored_eof = 2048)
```

which is not very useful as it tells me nothing of which value `fname` had.

**Comment by aragilar** [comment]
The exception information comes directly from HDF5, I'd suggest asking for this to be added at https://forum.hdfgroup.org/c/hdf5.

**Comment by tdegeus** [comment]
Ok. I have submitted it.

**Comment by tacaswell** [comment]
I'm going to close this to let the upstream tracking do it's job.

Thanks for doing the legwork on that @tdegeus !

**Comment by epourmal** [comment]
We are filing enhancement report. Contributions to HDF5 ARE MORE than WELCOME!

**Comment by epourmal** [comment]
For your records the issue report is HDFFV-10549.

**Comment by tdegeus** [comment]
It has been quite a while since this feature request is around, and to date it is not in HDF5. Maybe a workaround could still be considered? This is at least what I have done in the C++ wrapper around HDF5 that I use: https://github.com/BlueBrain/HighFive/pull/471

**Comment by tdegeus** [comment]
I'm still experiencing this, and I often have to write small extra bits of code to debug some issue with data. I do not have the impression that this is integrate upstream. Could this be considered in h5py?

**Comment by tacaswell** [comment]
I still think the best place to fix this in libhdf5.  If the fname is in the error message now and we are dropping that, that is definitly a bug in h5py.

We do the mapping from c error -> Python exception in https://github.com/h5py/h5py/blob/master/h5py/_errors.pyx .  It is not clear to me on a quick reading that we have access to the current filename (but I do not know the hdf5 error structures off the top of my head).  If it can be done in a generic way, I think we would merge a PR to add the file name to the message.

**Comment by tdegeus** [comment]
Thanks @tacaswell . I don't know if it is in the error stream or not. HDF5 bug/request handling is a mystery to me, so I cannot find if in the two years since this got reported it was implemented or not. @epourmal how can I track "HDFFV-10549" ?

**Comment by ajelenak** [comment]
Fyi... the HDFFV-10549 is being worked on right now.

**Comment by tdegeus** [comment]
Thanks @ajelenak ! Is there any way how we can track it?

**Comment by ajelenak** [comment]
There should be a branch eventually in libhdf5 GitHub repo.

**Comment by bmribler** [comment]
@tdegeus, you can view it at https://jira.hdfgroup.org/browse/HDFFV-10549.  It fell through the crack before.

**Comment by derobins** [comment]
Hi all. I'll have to think about how this could be implemented. Given the way that HDF5 handles errors, a generic fix might be difficult. To be very clear, though, "being worked on right now" means that it appeared on my radar for the first time, not that there is a fix for this in the works. We have limited resources for unfunded work and we have to prioritize this against other work. I'll do my best, but I can't make promises.

**Comment by tdegeus** [comment]
Thanks @derobins
