### ISSUE TITLE
KeysView is returned instead of the expected list (quickstart documentation)

### ISSUE THREAD

**Issue by arokem** [h5py/h5py#1073]
Dear h5py developers and community, 

Thanks for all your work on this project! 

I am trying to follow [this](http://docs.h5py.org/en/latest/quick.html) example, with a file that I got from the [Allen Institute's open datasets](https://github.com/AllenInstitute/AllenSDK/wiki/Use-the-Allen-Brain-Observatory-%E2%80%93-Visual-Coding-on-AWS). 

When I ran this:

```
source = h5py.File(fname, mode='r')
source.keys()
```
I expected to get a list of keys, but instead I got this object:

```
KeysView(<HDF5 file "myfile.nwb" (mode r+)>)
```
(Note: this file has an `nwb` extension, but it is an hdf5 file!)

Calling `list` on this, I get an empty list. How do I get to the data in this file?

Here are the outputs of `print(h5py.version.info)`:

```
Summary of the h5py configuration
---------------------------------

h5py    2.7.1
HDF5    1.10.1
Python  3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.13.3
```

Thanks again!

**Comment by tacaswell** [comment]
Returning a keys-view is consistent with `dict` in py3  which in the rough API we are trying to follow (but it could definitely use a better repr, which is actually already on masterhttps://github.com/h5py/h5py/pull/1049/files ).  The bug is that quick-start is very out a date...

What do you get with:

```python

In [3]: import h5py
   ...: 
   ...: with h5py.File('/tmp/test.nwb', 'w') as fout:
   ...:     fout['a'] = [1, 2, 3]
   ...:     fout['b'] = [1, 2, 3]
   ...:     fout['c/a'] = [1, 2, 3]
   ...:     fout['c/b'] = [1, 2, 3]

In [4]: source = h5py.File('/tmp/test.nwb', 'r')

In [5]: source.keys()
Out[5]: hdf_keys(['a', 'b', 'c'])

In [6]: list(source.keys())
Out[6]: ['a', 'b', 'c']

In [7]: 

```

(I am on master so hence the nicer repr).

Is this file someplace I can get at it?

**Comment by arokem** [comment]
Hi Thomas, 

Thanks for getting back to me on this!

Here's what I see: 

```
In [7]: import h5py

In [8]: with h5py.File('/tmp/test.nwb', 'w') as fout:
   ...:         fout['a'] = [1, 2, 3]
   ...:         fout['b'] = [1, 2, 3]
   ...:         fout['c/a'] = [1, 2, 3]
   ...:         fout['c/b'] = [1, 2, 3]
   ...:

In [9]: source = h5py.File('/tmp/test.nwb', 'r')

In [10]: source.keys()
Out[10]: KeysView(<HDF5 file "test.nwb" (mode r)>)

In [11]: list(source.keys())
Out[11]: ['a', 'b', 'c']
```

The file I was working with is available on AWS S3 as part of an open data-set, so I believe you should be able to get it using the following code, even without AWS credentials: 

```
import boto3
s3 = boto3.resource('s3')
b = s3.Bucket('allen-brain-observatory')
fname = '509523145.nwb'
b.download_file(op.join('visual-coding-2p/ophys_experiment_data', fname), fname)
```

**Comment by arokem** [comment]
I upgraded my version of the software to the current released version
(2.8), and I can now reproduce your second outcome (with the call to
`list`) but not your first result (still get `KeysView(<HDF5 file
"509523145.nwb" (mode r)>)`).

**Comment by tacaswell** [comment]
The `hdf_keys` is still not released (I am running the master branch), sorry for the confusion on that.

**Comment by arokem** [comment]
Aha - then all is well with the world (well, with this tiny corner of it). Closing. Thanks again!

**Comment by Xiangju** [comment]
> The `hdf_keys` is still not released (I am running the master branch), sorry for the confusion on that.

Here is the alternative way to access `hdf_keys`:

`keys = [key for key in f.keys()] `
or
`print( list(f.keys()) )`

**Comment by NYcleaner** [comment]
#if  matlab save data use  ‘-v7.3’，scipy.io.loadmat api load may lead mistake ，thus can use like：

```
import h5py
f = h5py.File('http.mat', 'r')
print(f.keys()) # <KeysViewHDF5 ['X', 'y']>  
print(f['X'][:]) 
```
