### ISSUE TITLE
ImportError: cannot import name '_errors'

### ISSUE THREAD

**Issue by Tchabo** [h5py/h5py#1074]
To assist reproducing bugs, please include the following:
 * Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 16.04.2 LTS, CentOS 7)
 * Python version (e.g. 2.7, 3.5)
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows)
 * h5py version (e.g. 2.6)
 * HDF5 version (e.g. 1.8.17)
 * The full traceback/stack trace shown (if it appears)

`h5py.version.info` contains the needed versions, which can be displayed by
```
python -c 'import h5py; print(h5py.version.info)'
```
where `python` should be substituted for the path to python used to install
`h5py` with.

**Comment by Tchabo** [comment]
I get this error

Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.10.2, library is 1.10.1
            SUMMARY OF THE HDF5 CONFIGURATION
            =================================

General Information:
-------------------
                   HDF5 Version: 1.10.1
                  Configured on: 2017-05-08
                  Configured by: Visual Studio 14 2015 Win64
                    Host system: Windows-10.0.15063
              Uname information: Windows
                       Byte sex: little-endian
             Installation point: C:/Program Files/HDF5

Compiling Options:
------------------
                     Build Mode:
              Debugging Symbols:
                        Asserts:
                      Profiling:
             Optimization Level:

Linking Options:
----------------
                      Libraries:
  Statically Linked Executables: OFF
                        LDFLAGS: /machine:x64
                     H5_LDFLAGS:
                     AM_LDFLAGS:
                Extra libraries: X:inclib-vc14-x64/zlib.lib;X:/inclib-vc14-x64/libsz.lib;X:/inclib-vc14-x64/libaec.lib
                       Archiver:
                         Ranlib:

Languages:
----------
                              C: yes
                     C Compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe 19.0.24215.1
                       CPPFLAGS:
                    H5_CPPFLAGS:
                    AM_CPPFLAGS:
                         CFLAGS: /DWIN32 /D_WINDOWS /W3
                      H5_CFLAGS:
                      AM_CFLAGS:
               Shared C Library: YES
               Static C Library: YES

                        Fortran: OFF
               Fortran Compiler:
                  Fortran Flags:
               H5 Fortran Flags:
               AM Fortran Flags:
         Shared Fortran Library: YES
         Static Fortran Library: YES

                            C++: ON
                   C++ Compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe 19.0.24215.1
                      C++ Flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
                   H5 C++ Flags:
                   AM C++ Flags:
             Shared C++ Library: YES
             Static C++ Library: YES

                            JAVA: OFF
                   JAVA Compiler:

Features:
---------
                  Parallel HDF5: OFF
             High-level library: ON
                   Threadsafety: OFF
            Default API mapping: v110
 With deprecated public symbols: ON
         I/O filters (external):  DEFLATE DECODE ENCODE
                            MPE:
                     Direct VFD:
                        dmalloc:
 Packages w/ extra debug output:
                    API Tracing: OFF
           Using memory checker: OFF
Memory allocation sanity checks: OFF
            Metadata trace file:
         Function Stack Tracing: OFF
      Strict File Format Checks: OFF
   Optimization Instrumentation:
Bye...

**Comment by aragilar** [comment]
How did you install python and h5py?

**Comment by tdegeus** [comment]
I too got something similar as at least the title of this bugs suggest:

```bash
import h5py
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-c9f0b8c65221> in <module>()
----> 1 import h5py

/usr/local/lib/python3.7/site-packages/h5py/__init__.py in <module>()
     24 # We tried working around this by using "package_dir" but that breaks Cython.
     25 try:
---> 26     from . import _errors
     27 except ImportError:
     28     import os.path as _op

ImportError: dlopen(/usr/local/lib/python3.7/site-packages/h5py/_errors.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/hdf5/lib/libhdf5.101.dylib
  Referenced from: /usr/local/lib/python3.7/site-packages/h5py/_errors.cpython-37m-darwin.so
  Reason: image not found
```

For me this was solved by

```bash
pip3 install --upgrade --force-reinstall h5py
```

**Comment by Tchabo** [comment]
Actually, I finally solved the issue by removing the h5py installation file from the location where I was running the program

**Comment by tacaswell** [comment]
Closing as the installation issue seems to have been resolved.

**Comment by Wei-TingChen777** [comment]
> Actually, I finally solved the issue by removing the h5py installation file from the location where I was running the program

what is the specific h5py installation file that was removed by you??

**Comment by Baron-Fourier** [comment]
Operating System: Windows 10
Python version: 3.6
Where: Anaconda
h5py version: 2.10.0
HDF5 version: 1.10.4
