### ISSUE TITLE
KeysView in Quick Start Guide

### ISSUE THREAD

**Issue by DerManiac** [h5py/h5py#1084]
This is an issue with the documentation. The Quick Start Guide says:

> Remember h5py.File acts like a Python dictionary, thus we can check the keys,

```
>>> f.keys()
[u'mydataset']
```

However, in reality it would be:

```
>>> f.keys()
KeysView(<HDF5 file "mytestfile.hdf5.h5" (mode r)>)
>>> list(f.keys())
[u'mydataset']
```

This was previously mentioned in issue #726 but not addressed/fixed before the issue was closed.

**Comment by aragilar** [comment]
The examples were written when Python 2 was assumed (note the `u` prefixes), and so there will be differences when using Python 3. I've opened a bug (#1086) to track the updating to Python 3, we'd welcome PRs to move the docs to Python 3.
