### ISSUE TITLE
Migrate examples in documentation to Python 3

### ISSUE THREAD

**Issue by aragilar** [h5py/h5py#1086]
Most examples in the documentation assume Python 2, which causes confusion when the output does not match what is shown in the examples (e.g. #1084 and #726). We should migrate the documentation to Python 3, and state that the examples are written for Python 3.

**Comment by saitouena** [comment]
The fix of documentation isn't reflected to the documentation.

**Comment by NumesSanguis** [comment]
There are still many `print ` statements that should be changed to `print()`. E.g.: http://docs.h5py.org/en/2.10.0/refs.html

**Comment by takluyver** [comment]
There was a sprint just after 2.10 was released, and I think all of these are fixed if you look at the docs built from master: http://docs.h5py.org/en/latest/refs.html

I'll close this issue - please open new ones if you spot examples that still need changing. Or even better, make pull requests. :-)
