### ISSUE TITLE
Reading in hangs on h5f.open()

### ISSUE THREAD

**Issue by ghartoularos** [h5py/h5py#1087]
I'm running Scanpy (a bioinformatics tool for single-cell data) that uses h5py to read and write data. I've been running this on an SGE cluster, both on interactive nodes and a compute nodes, using a Miniconda environment. I have an .h5ad file, which (as I understand it) is just Scanpy's annotated version of .h5, and it should be read in the same way. I've noticed that my command to read just hangs; it never errors, there's no traceback and I can't CTRL-C out of the process (I've waited about 20 minutes maximum).  I end up having to just close the terminal window. Through a series of print statements I've narrowed this down to the h5py package and the `make_fid` function, in particular it's `fid = h5f.open(name, flags, fapl=fapl)` call. Because this h5f function is imported from a Cython file, I kind of hit a roadblock here since I don't really understand how Cython works and how to debug it.

I found a Google groups post about a similar situation: https://groups.google.com/forum/#!topic/h5py/3LqT0b9nW2A
The author of that suggests that the file is corrupted, but it would be nice for h5py to catch this error if this is the case. The problem in my situation is that I don't think it's the case because, and here's the weird part: I've loaded the same exact file just fine on my local computer (it takes only a few seconds). I don't think the cluster OS or my Python version has anything to do with the issue, since I've confirmed other users on the cluster can run h5py without a problem. I thought I found the issue when I tried to `rm -r` all the site-packages directories and reinstall all the relevant packages: I found these `.nfs#############` files in the `h5/.libs` directory, indicating to me that the terminal windows I closed still had their processes running. I used `lsof` to figure out which process had opened these, and then used `kill -9` to kill them. Then I was able to `rm -r` the h5py dir and reinstall, and I'm _still_ getting the same hanging process. My next attempt is to completely uninstall and reinstall Miniconda, but otherwise I have no idea what's going on, and if I do figure it out, at least an error out or time out would be useful.

```
Linux version 2.6.32-696.30.1.el6.x86_64 (mockbuild@c1bl.rdu2.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) )
h5py    2.8.0
HDF5    1.10.2
Python  3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.15.1
```

**Comment by tacaswell** [comment]
> I've noticed that my command to read just hangs; it never errors, there's no traceback and I can't CTRL-C out of the process (I've waited about 20 minutes maximum).

This is frequently a sign that things are hung in the c-layer and frequently in OS calls.  That you are finding lots of `.nfs#############` around supports that this is an issues with your file system.

The open method is https://github.com/h5py/h5py/blob/2e284d395a9b5160e04cf6a7fc2ee5165a3c690d/h5py/h5f.pyx#L71-L85

which is calling out to the hdf5 c-library.

**Comment by tacaswell** [comment]
Closing as I believe that this is a local filesystem issue that should be taken up with the local sysadmins.
