### ISSUE TITLE
NameError: name 'mpi4py' is not defined when trying to use the "mpio" driver on a Linux cluster

### ISSUE THREAD

**Issue by tmaric** [h5py/h5py#1093]
I get  NameError: name 'mpi4py' is not defined when trying to use the "mpio" driver with "h5py" on a Linux cluster. I have installed "mpi4py" and "h5py" locally using 

```
pip install mpi4py --user
pip install h5py --user
```
I have tried to build both "mpi4py" as well as "h5py" (with MPI support) from source and succeeded, but then I get other MPI run-time errors. 

Is the "h5py" that is available via "pip" built with MPI support? If not, should I try to build "h5py" from source with "MPI" support and a path to a parallel HDF5 library?

 * Operating System CentOS Linux release 7.4.1708 (Core)
 * Python version Python 3.6.2
 * system Python Linux
 * h5py version 2.8.0
 * HDF5 version hdf5/parallel/1.10.2
 * The full traceback/stack trace shown

  1 --------------------------------------------------------------------------                                                                                                                
  2 A process has executed an operation involving a call to the                                                                                                                               
  3 "fork()" system call to create a child process.  Open MPI is currently                                                                                                                    
  4 operating in a condition that could result in memory corruption or                                                                                                                        
  5 other system errors; your job may hang, crash, or produce silent                                                                                                                          
  6 data corruption.  The use of fork() (or system() or other calls that                                                                                                                      
  7 create child processes) is strongly discouraged.                                                                                                                                          
  8                                                                                                                                                                                           
  9 The process that invoked fork was:                                                                                                                                                        
 10                                                                                                                                                                                           
 11   Local host:          [[24011,0],0] (PID 30576)                                                                                                                                          
 12                                                                                                                                                                                           
 13 If you are *absolutely sure* that your application will successfully                                                                                                                      
 14 and correctly survive a call to fork(), you may disable this warning                                                                                                                      
 15 by setting the mpi_warn_on_fork MCA parameter to 0.                                                                                                                                       
 16 --------------------------------------------------------------------------                                                                                                                
 17 --------------------------------------------------------------------------                                                                                                                
 18 A process has executed an operation involving a call to the                                                                                                                               
 19 "fork()" system call to create a child process.  Open MPI is currently                                                                                                                    
 20 operating in a condition that could result in memory corruption or                                                                                                                        
 21 other system errors; your job may hang, crash, or produce silent                                                                                                                          
 22 data corruption.  The use of fork() (or system() or other calls that                                                                                                                      
 23 create child processes) is strongly discouraged.                                                                                                                                          
 24                                                                                                                                                                                           
 25 The process that invoked fork was:                                                                                                                                                        
 26                                                                                                                                                                                           
 27   Local host:          [[24011,0],1] (PID 30577)                                                                                                                                          
 28                                                                                                                                                                                           
 29 If you are *absolutely sure* that your application will successfully                                                                                                                      
 30 and correctly survive a call to fork(), you may disable this warning                                                                                                                      
 31 by setting the mpi_warn_on_fork MCA parameter to 0.                                                                                                                                       
 32 -------------------------------------------------------------------------- 
Rank = 0                                                                                                                                                                                  
 34 Rank = 1                                                                                                                                                                                  
 35 Traceback (most recent call last):                                                                                                                                                        
 36   File "test-h5py.py", line 12, in <module>                                                                                                                                               
 37     rbfPolyFile = h5py.File("testFile.h5", 'w', driver="mpio", comm=comm)                                                                                                                 
 38   File "/home/user/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 311, in __init__                                                                                       
 39     fapl = make_fapl(driver, libver, **kwds)                                                                                                                                              
 40   File "/home/user/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 117, in make_fapl                                                                                      
 41     set_fapl(plist, **kwds)                                                                                                                                                               
 42   File "/home/user/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 43, in _set_fapl_mpio                                                                                  
 43     kwargs.setdefault('info', mpi4py.MPI.Info())                                                                                                                                          
 44 NameError: name 'mpi4py' is not defined                                                                                                                                                   
 45 Traceback (most recent call last):                                                                                                                                                        
 46   File "test-h5py.py", line 12, in <module>                                                                                                                                               
 47     rbfPolyFile = h5py.File("testFile.h5", 'w', driver="mpio", comm=comm)                                                                                                                 
 48   File "/home/user/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 311, in __init__                                                                                       
 49     fapl = make_fapl(driver, libver, **kwds)                                                                                                                                              
 50   File "/home/user/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 117, in make_fapl                                                                                      
 51     set_fapl(plist, **kwds)                                                                                                                                                               
 52   File "/home/user/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 43, in _set_fapl_mpio                                                                                  
 53     kwargs.setdefault('info', mpi4py.MPI.Info())                                                                                                                                          
 54 NameError: name 'mpi4py' is not defined                                                                                                                                                   
 55 srun: error: hpa0231: tasks 0-1: Exited with exit code

**Comment by tacaswell** [comment]
I am more concerned by 

```
18 A process has executed an operation involving a call to the
19 "fork()" system call to create a child process. Open MPI is currently
20 operating in a condition that could result in memory corruption or
21 other system errors; your job may hang, crash, or produce silent
22 data corruption. The use of fork() (or system() or other calls that
23 create child processes) is strongly discouraged.

```

Can you provide a runnable example and how you are invoking it?

**Comment by tmaric** [comment]
@tacaswell : this warning also appears after I have build `h5py` with MPI support from source. I have opened [another issue](https://github.com/h5py/h5py/issues/1095) for that. The program that causes is the simplest possible test:
```
#!/usr/bin/python                                                                                                                                                                             
                                                                                                                                                                                              
from mpi4py import MPI                                                                                                                                                                        
import h5py                                                                                                                                                                                   
                                                                                                                                                                                              
comm = MPI.COMM_WORLD                                                                                                                                                                         
rank = comm.rank                                                                                                                                                                              
                                                                                                                                                                                              
rbfPolyFile = h5py.File("testFile.h5", 'w', driver="mpio", comm=comm)                                                                                                                         
rbfPolyFile.close() 
```

**Comment by tacaswell** [comment]
How do you launch it? 

I don't have any MPI experience, but am willing to try to reproduce.

**Comment by tmaric** [comment]
@tacaswell : Thanks a lot for taking a look at this!  

I have also done a data consistency test, and this fails as well. I am launching the following test now: 

#!/usr/bin/python                                                                                                                                                                             
                                                                                                                                                                                              
```
from mpi4py import MPI                                                                                                                                                                        
import h5py                                                                                                                                                                                   
                                                                                                                                                                                              
comm = MPI.COMM_WORLD                                                                                                                                                                         
rank = comm.rank                                                                                                                                                                              
                                                                                                                                                                                              
rbfPolyFile = h5py.File("testFile.h5", 'w', driver="mpio", comm=comm)                                                                                                                         
                                                                                                                                                                                              
# The error persists irrespective of the MPI atomic mode.                                                                                                                                     
#rbfPolyFile.atomic = True                                                                                                                                                                    
                                                                                                                                                                                              
groupPath = "/RANK-%d" % rank                                                                                                                                                                 
print (groupPath)                                                                                                                                                                             
rbfPolyFile.create_group(groupPath)                                                                                                                                                           
rbfPolyFile.close() 
```
using this command: 

`mpiexec  -n 4 python3 test-h5py.py `

and I get the warning: 

```
A process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.

The process that invoked fork was:

  Local host:          [[15978,1],0] (PID 12642)

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
```

And what is much worse, _the groups are not written to the file_:

```
 > h5ls -lr testFile.h5 
/                        Group
/RANK-1                  Group
```

**Comment by tacaswell** [comment]
Do you get the warning if you swap

```python
from mpi4py import MPI                                                                                                                                                                        
import h5py   
```

for

```python
import h5py
from mpi4py import MPI                                                                                                                                                                        
```

?

**Comment by tmaric** [comment]
I have checked the parallel execution on my laptop, the login node on the cluster and on the compute nodes on the cluster. On my laptop and the compute nodes, I get no "fork()" warning, and on the cluster login node I get one, irrespective of the order of lines
```
from mpi4py import MPI                                                                                                                                                                        
import h5py  
```
That is weird. I think that if the "fork" warning goes away on the laptop and the compute nodes, I can work with it, as I will not run productive calculations on the cluster login node. But it is still strange.

**Comment by tacaswell** [comment]
This is something you should take to your local administrators / mpi experts...

**Comment by tmaric** [comment]
I have, thanks for the advice. I think this issue can be closed. I can re-open it if I see that the file structure is corrupt after I test everything.
