### ISSUE TITLE
h5py.special_dtype  bug

### ISSUE THREAD

**Issue by xxhwjzx** [h5py/h5py#1094]
To assist reproducing bugs, please include the following:
 * Operating System (Windows 10)
 * Python version (3.6)
 * Where Python was acquired (Anaconda on Windows)
 * h5py version (e.g. 2.8)

 * The full traceback/stack trace shown (if it appears)

When use "h5py.special_dtype"
dt = h5py.special_dtype(vlen=str)

Cannot find reference 'special_dtype' in '__init__.py' less... (Ctrl+F1) 
Inspection info: This inspection detects names that should resolve but don't. Due to dynamic dispatch and duck typing, this is possible in a limited but useful number of cases. Top-level and class-level items are supported better than instance items.

**Comment by aparamon** [comment]
Hi @xxhwjzx ! Is it reproducible if you run your code non-interactively, via python.exe?
