### ISSUE TITLE
H5PY Virtual Dataset to merge 2D 

### ISSUE THREAD

**Issue by Goon83** [h5py/h5py#1096]
//anaconda/lib/python3.5/site-packages/h5py-2.8.0.post0-py3.5-macosx-10.6-x86_64.egg/h5py

Hi,
Could anyone can help to look at the below code? Thanks in advance.  
I am trying to use the virtual data function to merge 2D data on multiple files.
Say, we have two files, f1.h5 and f2.h5. Each has a single dataset "data".  Their dimension are both [10, 21]. So, I want to merge two datasets into a [20,21], where 20=10+10.

I tried some example code like below

```
layout = h5py.VirtualLayout(shape=(10*2, 21), dtype='i2')
filenamelist=["f1.h5", "f2.h5"]
n=0
for filename in filenamelist:
    vsource = h5py.VirtualSource(filename, 'DataByChannelTime', shape=(10, 20), dtype='i2')
    layout[n*10:(n+1)*10-1, :] = vsource
    n += 1
with h5py.File("merged.h5", 'w', libver='latest') as f:
    f.create_virtual_dataset('data', layout, fillvalue=0)
```

The code above reports 

```
Traceback (most recent call last):
  File "../h5-merge.py", line 25, in <module>
    f.create_virtual_dataset('data', layout, fillvalue=0)
  File "//anaconda/lib/python3.5/site-packages/h5py-2.8.0.post0-py3.5-macosx-10.6-x86_64.egg/h5py/_hl/group.py", line 154, in create_virtual_dataset
    maxshape=layout.maxshape, fillvalue=fillvalue)
  File "//anaconda/lib/python3.5/site-packages/h5py-2.8.0.post0-py3.5-macosx-10.6-x86_64.egg/h5py/_hl/dataset.py", line 169, in make_new_virtual_dset
    dcpl.set_virtual(vspace, fpath, dset, src_dspace)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/Users/dbin/work/soft/h5py/h5py/_objects.c:2686)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/Users/dbin/work/soft/h5py/h5py/_objects.c:2644)
  File "h5py/h5p.pyx", line 824, in h5py.h5p.PropDCID.set_virtual (/Users/dbin/work/soft/h5py/h5py/h5p.c:7463)
ValueError: Invalid mapping selections (virtual and source space selections have different numbers of elements)
```

**Comment by tacaswell** [comment]
Your layout is (20, 21) but you are filling it with (10, 20) blocks (and trying to set them to a (9, 21) region).

I suspect we need better error messages on this if we can manage it!

**Comment by Goon83** [comment]
> Your layout is (20, 21) but you are filling it with (10, 20) blocks (and trying to set them to a (9, 21) region).
> 
> I suspect we need better error messages on this if we can manage it!
Sorry, it is a typo there. it intends to be 
layout = h5py.VirtualLayout(shape=(10*2, 20), dtype='i2')

The issue is that I don't know how to write this line:
    layout[n*10:(n+1)*10-1, :] = vsource

**Comment by tacaswell** [comment]
@Goon83 Can you provide a full (not) working example?  I think you just need to drop the -1 (as python uses half-open interval slicing).

**Comment by Goon83** [comment]
@tacaswell  thanks. it works by just dropping the -1.

**Comment by tacaswell** [comment]
Great, can we close this?
