### ISSUE TITLE
Support track_order for root group and for attributes

### ISSUE THREAD

**Issue by aparamon** [h5py/h5py#1097]
Currently, `Group.create_group()` supports `track_order` argument:
````
track_order
    Track dataset/group creation order under this group if True.
````
which if `True` sets `h5p.CRT_ORDER_TRACKED | h5p.CRT_ORDER_INDEXED` link creation order property.
(please note that it's unfortunately missing from the docs
http://docs.h5py.org/en/latest/high/group.html#Group.create_group
and from `Group.require_group()`).

It is proposed that additionally optional `track_order` argument is also introduced to `File.__init__()` so link creation can be set for root group.

Also, it is proposed that optional `attrs_track_order` argument is introduced for `create_group()`, `create_dataset()`, and `File.__init__()`, so HDF5 attribute creation order property can be specified too (variant: re-use `track_order` for this purpose).

It would be nice if h5py allowed to somehow specify default `track_order=True` and `attrs_track_order=True` globally.

**Comment by tacaswell** [comment]
That seems reasonable (as does updating the docs).

@aparamon Want to try taking on any of those tasks?

**Comment by aparamon** [comment]
I think I'll be able to tackle those, but probably not immediately.

In the meantime, I looked into how insertion order is used on read (`__iter__()`). Apparently, group contents iterator checks `get_link_creation_order()`, and if has `H5_CRT_ORDER_TRACKED` insertion order if used; otherwise name order. Attributes iterator always uses name order.
In all places, `H5_ITER_NATIVE` order is used, not `H5_ITER_INC`. This does sometimes lead to surprising results when items come sorted by reversed.

I think that should be unified. Given that Python `dict` iteration now [follows insertion order](https://mail.python.org/pipermail/python-dev/2017-December/151283.html) it seems that insertion order, increasing iteration of both h5py links and attributes (with the fall-back name order iteration when `h5p.CRT_ORDER_TRACKED` was not set) is "the right way", or at least a sensible default. Should we bother to provide an option to override that default iteration order? If so, a global parameter seems the only viable interface.

**Comment by maurov** [comment]
@aparamon I came to this issue while searching why `track_order` does not work with the root group. Here a complete minimal example:

```python
import h5py
import tempfile
ft = tempfile.mktemp(suffix='.hdf5')
h5 = h5py.File(ft, mode='w', track_order=True)
h5.create_group('z')
h5.create_group('a')
h5.keys()
# Out: <KeysViewHDF5 ['z', 'a']>
h5.close()
h5 = h5py.File(ft, mode='r', track_order=True)
h5.keys()
# Out: <KeysViewHDF5 ['a', 'z']>
```

I get the same behavior also if I set it globally via `h5py.get_config().track_order = True`. This happens only for the root group, while works as expected for subgroups.

PS: discussed also at https://github.com/silx-kit/silx/issues/2589

**Comment by bmaranville** [comment]
This is a bit odd, but in a pretty recent version of h5py== 3.8.0, you can get the root group in order _but only if you ask for it as a group_!

```python
import h5py
import tempfile
h5py.__version__
# Out: '3.8.0'
ft = tempfile.mktemp(suffix='.hdf5')
h5 = h5py.File(ft, mode='w', track_order=True)
h5.create_group('z')
h5.create_group('a')
h5.keys()
# Out: <KeysViewHDF5 ['z', 'a']>
h5.close()
h5 = h5py.File(ft, mode='r', track_order=True)
h5.keys()
# Out: <KeysViewHDF5 ['a', 'z']>

# But now, ask for the root group as '/':
h5['/'].keys()
# Out: <KeysViewHDF5 ['z', 'a']>
```
