### ISSUE TITLE
h5py 'fcpl' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by rimmartin** [h5py/h5py#1103]
CentOS 7
 * Python version 2.7.1
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows)
 * h5py version 2.7.1, 2.8
 * HDF5 version 1.10.1

```
        self.fcpl = h5py.h5p.create(h5py.h5p.FILE_CREATE)
        self.fcpl.set_link_creation_order(h5py.h5p.CRT_ORDER_TRACKED|h5py.h5p.CRT_ORDER_INDEXED)
        self.f = h5py.File(filePath, 'w', fcpl=self.fcpl)

```
is code that worked with 2.5.0

is there something that changed in compile or coding? the __init__ is the same from 2.5 and 2.7.1

```
Traceback (most recent call last):
  File "/home/roger/Dropbox (QuantumBio Inc.)/RogerQB/NetBeansProjects/qbpy/test/qbpy/persistence_test.py", line 183, in atomic_density_statistics_test
    p.load('./3FVA.h5')
  File "/home/roger/DropboxRogerQB/NetBeansProjects/qbpy/src/qbpy/persistence.py", line 35, in load
    self.f = h5py.File(filePath, 'r+', fcpl=self.fcpl)
  File "build/bdist.linux-x86_64/egg/h5py/_hl/files.py", line 311, in __init__
    fapl = make_fapl(driver, libver, **kwds)
  File "build/bdist.linux-x86_64/egg/h5py/_hl/files.py", line 109, in make_fapl
    raise TypeError(msg)
TypeError: 'fcpl' is an invalid keyword argument for this function

```

**Comment by takluyver** [comment]
It looks like your `fcpl` parameter was accepted but ignored in 2.5, and PR #752 added checking for the keyword arguments. If you want to use your own fcpl or fapl, you currently need to use a lower level interface.

**Comment by rimmartin** [comment]
@takluyver ah interesting.  Forget where I learned of setting fcpl before.

I see one internal to h5py.File
https://github.com/h5py/h5py/blob/master/h5py/_hl/files.py#L149

I may tinker with a PR where set_link_creation_order can be passed h5py.h5p.CRT_ORDER_TRACKED|h5py.h5p.CRT_ORDER_INDEXED somehow

**Comment by rimmartin** [comment]
https://github.com/h5py/h5py/blob/master/h5py/_hl/files.py#L369
has a place for fcpl; the fapl is stood up right before.  

What I don't know is the style the main author(s) of h5py.File would like in passing in h5py.h5p.CRT_ORDER_TRACKED|h5py.h5p.CRT_ORDER_INDEXED.  For file access property list it has been interpreted to to string such as 'r' 'w' 'r+' etc
I wonder what people would like for these settings of link order on the file creation property list

**Comment by takluyver** [comment]
Yeah, there's an `fcpl` argument for `make_fid`, but it doesn't seem to be used in the codebase, and it doesn't seem to be documented as a public API.

It's not up to me to decide, but I'd say it's clearest to stick close to the C style API except if it's something that's used so often it needs a shorter way to type it. Possibly it just needs `make_fid` to be documented, or some other way to pass a `fcpl` in.

**Comment by rimmartin** [comment]
@aparamon  you're on it! And further in the review process of it.  I'll drop my fork and almost PR and work using yours and promote getting it into the master and up coming release
