### ISSUE TITLE
The latest change to the documentation isn't reflected to the stable documentation

### ISSUE THREAD

**Issue by saitouena** [h5py/h5py#1113]
For example, https://github.com/h5py/h5py/issues/726 . This is fixed in this commit (https://github.com/h5py/h5py/commit/973a5348acd713727bfe3ae032f1413782888d68) . The lastest version documentation (http://docs.h5py.org/en/latest/quick.html) is fixed, but the stable version (http://docs.h5py.org/en/stable/quick.html#core-concepts) isn't fixed.
The project page https://www.h5py.org/ links to the stable version, so those who comes from the google search result are confused. See https://github.com/h5py/h5py/issues/726#issuecomment-418588527 and https://github.com/h5py/h5py/issues/726#issuecomment-425579967 .
To link the top page to the lastest version is better, maybe.
This is a problem of the project web site https://www.h5py.org/ , so the modification of the web site is needed.

**Comment by tacaswell** [comment]
We used to point at the 'latest' docs and that caused issues as we would have documentation for new features up on the web that users could not install!  The stable docs will be updated next time there is a release (which should be soon). 

We could maintain a `vX.Y.Z-doc' branch(s) and work out how to get read the docs to build those and use meeseeksbot to automate the backports (this is what we do on Matplotlib), however that is a fair amount of overhead to maintain.

**Comment by saitouena** [comment]
You mean the official web site was linked to the 'lastest' docs but it caused problems in the past, do you? (My understanding is ok?)
I'll wait for the next release. Thank you.

**Comment by tacaswell** [comment]
Yes, we had problems pointing to 'latest' as the canonical docs due new features being advertised but not being available in a released version.

I am going to close this issue.  It is unfortunate that we have the lag in publishing corrected docs, but I don't think we currently have the resources to manage backporting docs-only fixes and re-publishing the docs at this point.
