### ISSUE TITLE
virtual datasets: strange fillvalue=np.nan behavior

### ISSUE THREAD

**Issue by dnelson86** [h5py/h5py#1125]
Experimenting with #1060 (HDF5 1.10.4, h5py 11da4d6), I have encountered a strange issue, it seems that `fillvalue=np.nan` (also `fillvalue=np.inf`) is not being treated properly. Possibly related to #805? Not sure.

Example:

```python
    # Create source file
    with h5py.File('1.h5', 'w') as f:
        d = f.create_dataset('data', (5,), 'i4')
        d[:] = np.arange(5)

    # Assemble virtual dataset
    layout = h5py.VirtualLayout(shape=(10,), dtype='i4')

    with h5py.File('1.h5','r') as f:
        vsource = h5py.VirtualSource(f['data'])
        layout[0:5] = vsource

    # Assembly virtual dataset
    with h5py.File("VDS.h5", 'w', libver='latest') as f:
        f.create_virtual_dataset('data', layout, fillvalue=np.nan)
        print(f['data'][:])
```

output:

```
[          0           1           2           3           4 -2147483648
 -2147483648 -2147483648 -2147483648 -2147483648]
```

These values are seemingly set by the dtype (e.g. can be `-9223372036854775808` also).

**Comment by takluyver** [comment]
I see something similar when creating a regular dataset:

```
In [8]: f.create_dataset('foo', shape=(5,), dtype='i4', fillvalue=np.nan)       
Out[8]: <HDF5 dataset "foo": shape (5,), type "<i4">

In [9]: f['foo'][:]                                                             
Out[9]: 
array([-2147483648, -2147483648, -2147483648, -2147483648, -2147483648],
      dtype=int32)
```

NaN and inf are special floating-point values, and I don't think there are any integer equivalents: every possible binary pattern is interpreted as a normal integer.

I'd say the obvious thing to do in either case is to throw an error if the fill value can't be converted to the right datatype. It looks like it's getting converted to the minimum possible integer instead. Maybe there are reasons for this, or maybe it's left like that for backwards compatibility.

**Comment by vasole** [comment]
Quoting Wikipedia

_Most fixed-size integer formats do not have any way of explicitly indicating invalid data. Converting NaN to an integer type, or performing an integer operation whose floating-point equivalent would produce NaN, usually throws an exception. In Java, such operations throw instances of java.lang.ArithmeticException.[8] In C, they lead to undefined behavior._

**Comment by dnelson86** [comment]
Yes good point! Indeed this works fine for float dtypes, as expected.
