### ISSUE TITLE
converting plydata file into hdf5 file in python for PointNet

### ISSUE THREAD

**Issue by Prarthana1116** [h5py/h5py#1130]
I have a list of ply data file and I want to convert it into hdf5 file format so that I can use those files in point-net for training,
I follow the code provided in link below and converted successfully into .h5 format also.
https://github.com/IsaacGuan/PointNet-Plane-Detection/blob/master/data/write_hdf5.py
But when read those converted .h5 file I found some data format missing.

What is need is : Keys: [u'data,u'faceId,u'label,u'normal]
And What I got  using those code is: Keys:[u'data]

Can anyone help me to figure out my problem.
I have been digging my head from two weeks and still didn't get any solution.
Please help me to convert my files.

**Comment by aparamon** [comment]
Hello @Prarthana1116, and thank you for your interest in h5py!
You have posted a question in h5py issue tracker, which is intended for bug reports and new feature proposals. [Official documentation](http://docs.h5py.org) and [h5py forum](https://groups.google.com/forum/#!forum/h5py) are the places where you are more likely to find answers and friendly support.

**Comment by Prarthana1116** [comment]
@aparamon ,
Sorry and thank you for the information.

**Comment by Grungeby52** [comment]
I have same problem, could you find solved this problem?
