### ISSUE TITLE
TypeError: No conversion path for dtype: dtype('<U34')

### ISSUE THREAD

**Issue by mthiebau** [h5py/h5py#1131]
Here is my code:

import sys
import dolfyn.adp.api as apm
master = apm.read_rdi('C:\\MT\\DATA\\MASTER\\RAW\\Master_RDI_001.000',nens=10000)
master.save('C:\\MT\\DATA\\MASTER\\thymote_rz_master_clean_test')

I get the following error: _TypeError: No conversion path for dtype: dtype('<U34')_

Please advise

Thanks

**Comment by takluyver** [comment]
This looks relevant: http://docs.h5py.org/en/stable/strings.html#what-about-numpy-s-u-type

You might need to raise this with the dolfyn project.

**Comment by takluyver** [comment]
Closing as there's nothing clear to address in h5py. It's documented that h5py doesn't accept numpy unicode arrays, because HDF5 doesn't have a datatype to represent unicode codepoints as fixed width. Unicode can be stored as UTF-8, but a fixed-length unicode string is not a predictable length when encoded to UTF-8.

**Comment by wolfiex** [comment]
It's actually a python 3 issue. As it automatically gets addressed in normal python it is a strange error when first encountered.

**Comment by rahulv1999** [comment]
> It's actually a python 3 issue. As it automatically gets addressed in normal python it is a strange error when first encountered.

so then whats the sol for 
my code:
f.create_dataset('scodes/' + batch_id, (len(codes),), dtype=("S{0}".format(len(codes[0])), data=codes)
error:
TypeError: No conversion path for dtype: dtype('<U26')

**Comment by roman-bushuiev** [comment]
Converting Unicode string data type `dtype('<U26')` to a fixed-length byte string data type `dtype('S26')` using `codes = codes.astype('S26')` should solve the problem.
