### ISSUE TITLE
Error number (errno) of OSError is None

### ISSUE THREAD

**Issue by flekschas** [h5py/h5py#1133]
I am wondering if it's expected that `error.errno` in raised exception is `None` when a hdf5 file is opened in mode `w-` but already exist?

My scenario looks like this:

```python
import h5py;

try:
    with h5py.File("file-that-already-exist.hdf5", "w-") as f:
        # Do something with the file here
except OSError as error:
    print(error.errno)
    # --> None
    print(str(error))
    # --> OSError: Unable to create file (unable to open file: name = 'file-that-already-exist.hdf5', errno = 17, error message = 'File exists', flags = 15, o_flags = a02)
```

Ideally I would like to be able to do:

```python
expecting_error_no_17 = maybe_yes_maybe_no(my_magic_conditions)
try:
    with h5py.File("file-that-already-exist.hdf5", "w-") as f:
        # Do something with the file here
except OSError as error:
    if error.errno == 17 and expecting_error_no_17:
        pass
    else:
        raise
```

The above code doesn't work. I can achieve it by parsing the error message for `errno` but I am wondering why `error.errno` is `None` instead of the error number reported in the error message? Is it expected that `error.errno` is `None` or is this a bug? If it's expected is there a preferred way of getting the error number or is that up to the user?

`h5py.version.info`:
```bash
h5py    2.8.0
HDF5    1.10.3
Python  3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:55:02)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.15.3
```

I am running macOS 10.12.6.

**Comment by tacaswell** [comment]
I do not think we currently get enough information out of the hdf5 layer to provide this (see https://forum.hdfgroup.org/t/get-posix-errno-from-hdf5-errors/5003 ).

**Comment by flekschas** [comment]
Oh cool! Thanks for the link. Looks like someone had the exact same question.

**Comment by miccoli** [comment]
I was going to open another `OSError` related issue, but after reading this thread I think that it is better to wait that the problem at the hdf5 layer is solved.

I just add it here as a comment.

Currently `OSError` is raised also when one tries to open a file that is not in HDF5 format: e.g
```
>>> import h5py
>>> h5py.File("/etc/passwd", "r")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python3.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "python3.7/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```
This is obviously *not* an  `OSError` which according to the [docs](https://docs.python.org/3/library/exceptions.html#OSError) should be

> raised when a system function returns a system-related error, including I/O failures such as “file not found” or “disk full” (not for illegal argument types or other incidental errors).

If this problem is not related to this issue I can open a new one.

**Comment by takluyver** [comment]
@miccoli: It used to be IOError ("when an I/O operation... fails for an I/O-related reason"), which then got merged with OSError. I agree it's semantically wrong now (whether or not it was before), but changing exception types breaks code that expects to catch a particular error. If you feel it needs to be changed, please open a separate issue.

**Comment by scopatz** [comment]
I agre with @takluyver - I think this can be closed in favor of a separate issue.

**Comment by miccoli** [comment]
Opened issue #1226 : I understand that changing established behaviour is tricky, but this is clearly an issue that should be reported.
