### ISSUE TITLE
VDS example links not rendering

### ISSUE THREAD

**Issue by tacaswell** [h5py/h5py#1137]
See http://docs.h5py.org/en/2.9.0rc1/vds.html at the bottom.

**Comment by takluyver** [comment]
The names of the scripts? They're not links at all. We can make them links if you want, of course.

**Comment by tacaswell** [comment]
I thought they were meant to be links, if they were not intended to be we can close this.

**Comment by takluyver** [comment]
I didn't try to make them links, but it would probably make sense if they were.

**Comment by takluyver** [comment]
See #1140
