### ISSUE TITLE
Broken link in documentation page

### ISSUE THREAD

**Issue by amcnicho** [h5py/h5py#1145]
It seems the HDF Group has added a sub-domain to their documentation address for at least one file referenced in the h5py documentation. This has resulted in a broken link on [the SWMR sphinx page](http://docs.h5py.org/en/stable/swmr.html), and possibly elsewhere.

Instead of:
https://www.hdfgroup.org/HDF5/docNewFeatures/NewFeaturesSwmrDocs.html
the link should point at:
https://support.hdfgroup.org/HDF5/docNewFeatures/NewFeaturesSwmrDocs.html

**Comment by takluyver** [comment]
Thanks for spotting this. Could you make a pull request? All the source for the documentation is [in this repository](https://github.com/h5py/h5py/tree/master/docs).

It's a bit annoying that the HDF group have broken links like that, though.

**Comment by amcnicho** [comment]
There is another instance of a broken documentation link, and docs/contributing.rst has still another. These are the only ones I could find without a redirect in place. Maybe someone could get in touch with the HDF Group webmaster and convince them to set up a redirect for the https://support.hdfgroup.org/HDF5/doc/ area. It might just be more efficient to update all the links though.

**Comment by takluyver** [comment]
Good idea. You could try on the [HDF Forum](https://forum.hdfgroup.org/) - there are people from the HDF group on there, though it can be a bit hit-and-miss getting a response.

**Comment by takluyver** [comment]
#1213 should finish this off. Still no redirect, but the links in our docs should be working.

It also appears that they're pointing people to another documentation site now: https://portal.hdfgroup.org/display/HDF5/HDF5
