### ISSUE TITLE
h5py import error: image not found

### ISSUE THREAD

**Issue by scottyuecao** [h5py/h5py#1147]
* MacOS 10.13.6, Python 3.6 installed and managed using miniconda
 * h5py ver. 2.8.0 built from py36h878fce3_3
 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c9f0b8c65221> in <module>
----> 1 import h5py

~/Applications/Conda3/lib/python3.6/site-packages/h5py/__init__.py in <module>
     24 # We tried working around this by using "package_dir" but that breaks Cython.
     25 try:
---> 26     from . import _errors
     27 except ImportError:
     28     import os.path as _op

ImportError: dlopen(~/Applications/Conda3/lib/python3.6/site-packages/h5py/_errors.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libhdf5.101.dylib
  Referenced from: ~/Applications/Conda3/lib/python3.6/site-packages/h5py/_errors.cpython-36m-darwin.so
  Reason: image not found

**Comment by cnwangfeng** [comment]
Same problem.

**Comment by scottyuecao** [comment]
My problem comes from version inconsistency during the updates (if you update all packages at once). I have not determined exactly which. Uninstall and then reinstall h5py will resolve the problem.

**Comment by tacaswell** [comment]
This is a packaging problem and should be reported to the anaconda team.

Closing as there is nothing we can do on the h5py side.
