### ISSUE TITLE
Create hdf5 file where exist folder with same name

### ISSUE THREAD

**Issue by MuchkoM** [h5py/h5py#1162]
To reproduce issue:
Run test.py in lunix environment:
Output:
Unable to create file (unable to open file: name = 'test', errno = 17, error message = 'File exists', flags = 15, o_flags = c2
Run test.py in win32 environment:
Output:
Unable to create file (unable to open file: name = 'test', errno = 13, error message = 'Permission denied', flags = 15, o_flags = 502)
Result must be same

## test.py
```
import os
import h5py
try:
	os.mkdir('test')
	h5py.File('test', mode='x').close()
except OSError as err:
	print(err)
```

## Environment
win32:
h5py    2.9.0
HDF5    1.10.4
Python  3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.15.4

lunix:
h5py    2.9.0
HDF5    1.10.4
Python  3.5.3 (default, Sep 27 2018, 17:25:39)[GCC 6.3.0 20170516]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.16.0

**Comment by rmvanhees** [comment]
You ask two operating systems to handle a file creation error, and they
respond with different messages. This is therefore not a h5py problem.

Greetings, Richard

**Comment by aparamon** [comment]
I don't reproduce exactly, but `errno` is indeed different between GNU/Linux and Windows.
* Debian GNU/Linux:
`Unable to create file (unable to open file: name = 'test', errno = 22, error message = 'Invalid argument', flags = 15, o_flags = c2)`
* Windows 10:
`Unable to create file (unable to open file: name = 'test', errno = 13, error message = 'Permission denied', flags = 15, o_flags = 502)`

However it's apparently not h5py nor HDF5 problem:
````py
import os
os.mkdir('test')
try:
    open('test', 'x')
except OSError as err:
    print(err)
finally:
    os.rmdir('test')
````
* Debian GNU/Linux:
`[Errno 22] Invalid argument: 'test'`
* Windows 10:
`[Errno 13] Permission denied: 'test'`

**Comment by takluyver** [comment]
When I try the `open()` sample on Linux (Fedora), I get:

```
[Errno 17] File exists: 'test'
```

This is what I'd expect - 17 is EEXIST, which corresponds to the Python `FileExistsError`.

However, this is up to the underlying operating system, and we can't even really expose specific errors like FileExistsError until HDF5 gives us the errno (see https://forum.hdfgroup.org/t/get-posix-errno-from-hdf5-errors/5003 ). The error message that differs is coming from HDF5, and I don't think h5py should try to scrape it and rewrite it to be the same across platforms.
