### ISSUE TITLE
Illegal length 24 for complex dtype on i686

### ISSUE THREAD

**Issue by opoplawski** [h5py/h5py#1163]
To assist reproducing bugs, please include the following:
 * Fedora Rawhide
 * Python version 3.7
 * system Python
 * h5py version 2.9.0
 * HDF5 version 1.8.20
 * The full traceback/stack trace shown (if it appears)

I get this only on 32-bit x86 (not 64bit or 32-bit arm).  This also appears to be new with 2.9.0 - build works with 2.8.0.

```
+ /usr/bin/python3 setup.py test
running test
running build_py
running build_ext
Autodetected HDF5 1.8.20
********************************************************************************
                       Summary of the h5py configuration

    Path to HDF5: None
    HDF5 Version: '1.8.20'
     MPI Enabled: False
Rebuild Required: False

********************************************************************************
Executing cythonize()
...........s...........................................x.................................s......................................x....................................s/builddir/build/BUILD/h5py-2.9.0/build/lib.linux-i686-3.7/h5py/_hl/files.py:258: H5pyDeprecationWarning: File.fid has been deprecated. Use File.id instead.
  "Use File.id instead.", H5pyDeprecationWarning)
...s......ss.......................................................................................................ssssss.....................................................................x....x.........................x......x.......................................sssssssssss.................................E.....sssssssssssssssssssssssss
======================================================================
ERROR: test_float_round_tripping (h5py.tests.hl.test_datatype.TestOffsets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/h5py-2.9.0/build/lib.linux-i686-3.7/h5py/tests/hl/test_datatype.py", line 235, in test_float_round_tripping
    f.create_dataset(n, data=data)
  File "/builddir/build/BUILD/h5py-2.9.0/build/lib.linux-i686-3.7/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/builddir/build/BUILD/h5py-2.9.0/build/lib.linux-i686-3.7/h5py/_hl/dataset.py", line 118, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1630, in h5py.h5t.py_create
    cpdef TypeID py_create(object dtype_in, bint logical=0, bint aligned=0):
  File "h5py/h5t.pyx", line 1652, in h5py.h5t.py_create
    with phil:
  File "h5py/h5t.pyx", line 1670, in h5py.h5t.py_create
    return _c_complex(dt)
  File "h5py/h5t.pyx", line 1550, in h5py.h5t._c_complex
    raise TypeError("Illegal length %d for complex dtype" % length)
TypeError: Illegal length 24 for complex dtype
```

**Comment by deep-42-thought** [comment]
The same issue pops up on archlinux for i686.

**Comment by aragilar** [comment]
The test that's failing is new to h5py 2.9, which is why 2.8 doesn't fail, h5py 2.8 will fail against that test (as will all previous versions). This failure can be ignored (on 32 bit x86 systems), as it due to not supporting `numpy.clongdouble` instances that use 192 bits (2 * 96). The failure wasn't noticed as we currently don't have a CI running on a non-Windows 32-bit OS (quick google suggests travis seems to recommend using docker for this).

At some point we should duplicate the logic used for the floating types to the complex types, performing detection rather than hard coding the size (given 96 bit floats are most likely Intel's 80-bit float on x86, I doubt anyone has a pressing need for support).

**Comment by cdluminate** [comment]
Same for Debian: https://buildd.debian.org/status/fetch.php?pkg=h5py&arch=i386&ver=2.9.0-1&stamp=1549098825&raw=0

**Comment by takluyver** [comment]
Is anyone clear what needs to be done here? Do we just need to exclude one or more types from `test_float_round_tripping` on i686? I'm pushing for a 2.10 release soon, so this either needs to get resolved or postponed to a future release.

**Comment by takluyver** [comment]
@aragilar made PR #1235 to skip that test. Can anyone with a real 32-bit system test that branch and check there are no other failures?

A more specific fix would be welcome if someone has the time to put one together. Just dropping the whole test is not ideal. But it should prevent test failures!
