### ISSUE TITLE
Require Python 3?

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#1177]
Quite a lot of Python projects, including core components like numpy, are [dropping support for Python 2](https://python3statement.org/) in the near future, and some already have. Should h5py join them?

The benefits are probably familiar: development is easier when you're not having to think about compatibility, tests finish quicker because there are fewer platforms to test on, we can take advantage of new language features, and static analysis tools tend to be more informative when they don't have to make sense of compatibility layers. Cython hides some of the differences, but there's a fair bit of highlevel code written in pure Python.

h5py is in a relatively good position for this; the HDF5 file format doesn't change very fast, so if people have existing code written for h5py & Python 2, in many cases they don't need to upgrade to the latest h5py.

A number of projects have also said they will backport important fixes to a 'long term support' release series supporting Python 2 for a while. While I think the term 'support' implies a kind of guarantee that volunteer-maintained projects don't really offer, this plan is a reasonable option to develop new features on Python 3 before completely stopping work on bugs affecting Python 2 users.

**Comment by tacaswell** [comment]
:+1: I am fully on board with this.  I think we should do a major version bump when we do (same as mpl).

What is the oldest version of python to support?  We currently go all the way back to 3.4, I think we should jump to 3.6 (so we get f strings and ordered dicts). 

If we aim for late summer / early fall for a 3.0 release I don't think we have to worry too much about an LTS release (unless we find a truly show-stopping bug in h5py2.9) and just do a 2.9.x final patch release around the same time.

**Comment by takluyver** [comment]
If we're aiming for a major version bump, should we try to get #1143 into a release soon? A major version bump is probably the only chance to change the default file open mode.

If we were releasing today, my instinct is to still support 3.5. I often use Ubuntu releases as a benchmark for when it's reasonable to drop Python versions, and Ubuntu 16.04, still the default at work, has Python 3.5. But of course, we're not releasing today, and anyone using Anaconda gets new Python versions much quicker than Ubuntu defaults.

**Comment by takluyver** [comment]
Just to make that slightly cryptic comment clearer: #1143 deprecates the existing default behaviour and provides an option for people to change it. The idea is that that goes in at least one release (2.10) before the major version bump, so people have a chance to adapt code.

**Comment by aparamon** [comment]
Obsoleting Python 2 is timely; let's go for it!

As for the breaking changes for h5py 3.0, cleanup of string handling seems important. I'll try to devote some time to https://github.com/h5py/h5py/issues/379 and generally https://github.com/h5py/h5py/issues?q=is%3Aissue+is%3Aopen+label%3A%22string%2Funicode+usage%22 soon; breaking change opportunity is not to be missed there.

**Comment by takluyver** [comment]
On the other hand, let's not change things just because "now's our chance". I think part of the reason it's taken over a decade to get to this point is that Python 3 was seen as a chance to make a load of breaking changes all at the same time, which made migrating a really big job.

There may be small changes to be done to make string handling more consistent and predictable. But I think there are a few people arguing for a major change to the mapping between HDF5 types and string types, and my feeling is that that would be a mistake.

I don't think there's any possible string handling model which will neatly bridge between the available type systems. Whatever we changed it to would have its own inconsistencies and unexpected behaviours which would annoy people. Plus many people would be forced to change working code, in ways that are far more complex than adding a mode to `h5py.File()` calls.

Maybe I lack the imagination to see some golden solution to these issues. But a lot of the comments look to me like "*Obviously* this HDF5 type should map to that Python type", and if you consider the range of possible types on each side, and the desire to preserve roundtripping, I don't think anything is obvious.

**Comment by aparamon** [comment]
Btw, organizational question: currently we have a lot of `string/unicode usage` *issues*; in order to discuss a general *solution/refactoring*, what's best:
1. Comment in one of the issues, e.g. https://github.com/h5py/h5py/issues/973,
2. Create another master issue,
3. Use mail group?

**Comment by shoyer** [comment]
I'm definitely +1 for dropping Python 2 support. There are definitely some nasty string issues on Python 3 still remaining, but I don't think fixes those should block dropping support for Python 2. Nor do we need to drop Python 2 in a major release, unless there are other major changes we want to make at the same time.

> A number of projects have also said they will backport important fixes to a 'long term support' release series supporting Python 2 for a while. While I think the term 'support' implies a kind of guarantee that volunteer-maintained projects don't really offer, this plan is a reasonable option to develop new features on Python 3 before completely stopping work on bugs affecting Python 2 users.

An alternative attitude might be: bug fix PRs will be accepted on the Python 2-only branch, and bug-fix releases will be made as warranted. But I don't even know if this is necessary -- h5py on Python 2 is pretty mature software at this.

**Comment by takluyver** [comment]
This was done in #1296.
