### ISSUE TITLE
IOError: Unable to open file (truncated file: eof = 96, sblock->base_addr = 0, stored_eof = 2048)

### ISSUE THREAD

**Issue by nbro** [h5py/h5py#1179]
According to the command `du -h my_file.h5`, my `.h5` file has size 4.0K. The error apparently occurs [at line 125 of this file](https://github.com/nbro/learning-long-range-perception/blob/master/code/simulation/model.py#L125).

The full traceback/stack trace shown 

```
WARNING:tensorflow:From /home/nbro/Desktop/env/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "train.py", line 55, in <module>
    train()
  File "train.py", line 46, in train
    val_x, val_y, _ = next(generator(filename=filename, is_testset=True, testset_index=-1))
  File "/home/nbro/Desktop/learning-long-range-perception/code/simulation/model.py", line 125, in generator
    h5f = h5py.File(filename, 'r')
  File "/home/nbro/Desktop/env/local/lib/python2.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/home/nbro/Desktop/env/local/lib/python2.7/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
IOError: Unable to open file (truncated file: eof = 96, sblock->base_addr = 0, stored_eof = 2048)
```

The output of the following command

```
python -c 'import h5py; print(h5py.version.info)'
```

is

```
Summary of the h5py configuration
---------------------------------

h5py    2.9.0
HDF5    1.10.4
Python  2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0]
sys.platform    linux2
sys.maxsize     9223372036854775807
numpy   1.16.2
```

I am on a Ubuntu 18.04 VM (using VirtualBox), with a MacOS HighSierra host.

I have looked a little at the source code of `h5py`, and apparently the error occurs [here](https://github.com/h5py/h5py/blob/master/h5py/_objects.pyx#L55).

**Comment by tacaswell** [comment]
This failure is coming out of the underlying hdf5 library.  Do the command line tools (like `h5ls`) work?  I suspect that your file is corrupted.

I think `du` can only report in increments of your file system block size.

**Comment by nbro** [comment]
@tacaswell I installed `h5py` using `pip`. I don't have the command `h5ls`, but I have other apparently related commands, like `h5cc`. 

What do you mean by corrupted?

So, how can I solve this problem?

**Comment by tacaswell** [comment]
I mean the file is not a vaild hdf5 file.  To fix it you probably have to go back to the original source and get a new copy.

I am going to close this as I do not think it is a bug in h5py.

**Comment by troomtroom** [comment]
This was the issue with me as well, thank you so much!
I thought the file was too large.

**Comment by MarwanGriffin** [comment]
Hello every one @troomtroom @tacaswell 
this is my issue too for now, unless  the source of the file is me because i am training Xception model from scratch and save it as .hdf5 file when i want to make a test pridection with the trained model it says :

**OSError: Unable to open file (truncated file: eof = 754967528, sblock->base_addr = 0, stored_eof = 2770419328)**
Here's the correspandant code 
`matplotlib.matplotlib_fname()
%matplotlib inline
test_datagen = ImageDataGenerator(rescale=1./255)
val_set = test_datagen.flow_from_directory('/content/drive/My Drive/DDSM_labeled/test10/abnormal_postif/',
        target_size=(299, 299),
        batch_size=32,
        color_mode="rgb",
        shuffle=False
        #class_mode='binary',
       )

from tensorflow.keras.models import load_model
model = load_model("/content/drive/My Drive/TL_M_B_299x299_XCeption_356_.hdf5")`
**Note : the file size is 3 GO**

**Comment by troomtroom** [comment]
WHo is this?

**Comment by oraby** [comment]
What worked for me on big H5 files:
If the difference between the `stored eof` and actual file size (i.e `eof`) is small, and you don't care about the last portion of data, then you can calculate the difference in bytes: `n = stored_eof - eof` and [append the missing `n` bytes to end of the file](https://serverfault.com/questions/343705/how-do-i-append-a-specific-number-of-null-bytes-to-a-file) (but don't forget to test on a copy)
