### ISSUE TITLE
document installation on aarch64 + ubuntu

### ISSUE THREAD

**Issue by talregev** [h5py/h5py#1181]
When I install:
`pip3 install h5py`

I am using python 3.6 also happen in python 2.7 Ubuntu aarch64 / arm64.
I install:
`sudo apt install libhdf5-dev`

The include files is on `/usr/include/hdf5/serial` and the script lookin in `/usr/include`

the compiler looking for `libhdf5.so` but it is `libhdf5_serial.so`
and it looking for `libhdf5_hl.so` but it `libhdf5_serial_hl.so`

can you change that?

**Comment by tacaswell** [comment]
If you are installing the wheels they should have hdf5 bundled with it.  I am a bit unclear how you are installing h5py.

If you are installing from source, see http://docs.h5py.org/en/stable/build.html#custom-installation for how to point the installation process at where hdf5 is on your system

Can you try with h5py 2.9?

**Comment by talregev** [comment]
I install it:
pip3 install h5py
It install h5py-2.9.0
hdf5 version:
Architecture: arm64
Source: hdf5
Version: 1.10.0-patch1+docs-4
Replaces: libhdf5-serial-dev (<< 1.8.12-9~)

It download this file:


https://files.pythonhosted.org/packages/43/27/a6e7dcb8ae20a4dbf3725321058923fec262b6f7835179d78ccc8d98deec/h5py-2.9.0.tar.gz

**Comment by tacaswell** [comment]
Ah, I miss-read your first message as saying you installed h5py 2.6.

Did it work if you followed the instructions for setting your hdf5 path does it work?

**Comment by talregev** [comment]
for me that it work i do the following:
cp /usr/include/hdf5/serial/* /usr/include/
ln -s /usr/lib/aarch64-linux-gnu/libhdf5_serial.so /usr/lib/aarch64-linux-gnu/libhdf5.so
ln -s /usr/lib/aarch64-linux-gnu/libhdf5_serial_hl.so /usr/lib/aarch64-linux-gnu/libhdf5_hl.so

then it work.

errors:
```bash   
In file included from /tmp/pip-build-x7f5dh0k/h5py/h5py/defs.c:637:0:                           /tmp/pip-build-x7f5dh0k/h5py/h5py/api_compat.h:27:10: fatal error: hdf5.h: No such file or directory                                             #include "hdf5.h"                                        ^~~~~~~~                              compilation terminated.                         error: command 'aarch64-linux-gnu-gcc' failed with exit status 1                                                                                ----------------------------------------    Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-x7f5dh0k/h5py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ht4az3m4-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-x7f5dh0k/h5py/                     
```

**Comment by talregev** [comment]
errors of ld:

```bash
aarch64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -specs=/usr/share/dpkg/no-pie-link.specs -Wl,-z,relro -Wl,-Bsymbolic-functions -specs=/usr/share/dpkg/no-pie-link.specs -Wl,-z,relro -g -fdebug-prefix-map=/build/python3.6-M4RXmS/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-aarch64-3.6/tmp/pip-build-revh5vw2/h5py/h5py/defs.o -L/opt/local/lib -L/usr/local/lib -Wl,--enable-new-dtags,-R/opt/local/lib -Wl,--enable-new-dtags,-R/usr/local/lib -lhdf5 -lhdf5_hl -o build/lib.linux-aarch64-3.6/h5py/defs.cpython-36m-aarch64-linux-gnu.so                   /usr/bin/aarch64-linux-gnu-ld: cannot find -lhdf5                                               /usr/bin/aarch64-linux-gnu-ld: cannot find -lhdf5_hl                                            collect2: error: ld returned 1 exit status      error: command 'aarch64-linux-gnu-gcc' failed with exit status 1                                                                                ----------------------------------------    Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-revh5vw2/h5py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-1btz_6dx-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-revh5vw2/h5py/
```

**Comment by talregev** [comment]
I post this issue that no one after me need to deal with this errors.

**Comment by takluyver** [comment]
@tacaswell do you understand what needs to be done here? I thought this was the sort of thing that `pkgconfig` was supposed to handle.

**Comment by zrzka** [comment]
Exactly same issue here. Did apply @talregev workaround for now and will come back later to this one to investigate more.

**Comment by zrzka** [comment]
Full error output is:

```
    aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DH5_USE_16_API -I./h5py -I/tmp/pip-build-hmdd1mnj/h5py/lzf -I/opt/local/include -I/usr/local/include -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -I/usr/include/python3.6m -c /tmp/pip-build-hmdd1mnj/h5py/h5py/defs.c -o build/temp.linux-aarch64-3.6/tmp/pip-build-hmdd1mnj/h5py/h5py/defs.o
    In file included from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                     from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from /tmp/pip-build-hmdd1mnj/h5py/h5py/api_compat.h:26,
                     from /tmp/pip-build-hmdd1mnj/h5py/h5py/defs.c:642:
    /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it with " \
      ^~~~~~~
    In file included from /tmp/pip-build-hmdd1mnj/h5py/h5py/defs.c:642:0:
    /tmp/pip-build-hmdd1mnj/h5py/h5py/api_compat.h:27:10: fatal error: hdf5.h: No such file or directory
     #include "hdf5.h"
              ^~~~~~~~
    compilation terminated.
    error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
```

**Comment by zrzka** [comment]
Was following [these steps](https://docs.nvidia.com/deeplearning/frameworks/install-tf-xavier/index.html#prereqs), because I'd like to install `tensorflow-gpu` on my Jetson Nano.

**Comment by aragilar** [comment]
@zrzka @talregev Can you run `pkg-config --cflags hdf5` and `pkg-config --libs hdf5`?
The outputs should be `-I/usr/include/hdf5/serial` and `-L/usr/lib/aarch64-linux-gnu/hdf5/serial -lhdf5` respectively. If they differ, can you post them?

**Comment by zrzka** [comment]
Oh man, what a stupid mistake. You thought that you have `pkg-config` installed and then it turns out that it's not installed. Removed the workaround, tried again and it works. Sorry for the noise.

**Comment by takluyver** [comment]
So is the resolution to mention `pkg-config` in the section about [source installation on Linux](http://docs.h5py.org/en/latest/build.html#source-installation-on-linux-other-unix)? Or should it be for other platforms as well?

Would it be a good idea to require `pkg-config` to build from source, i.e. remove the fallback pathway for when it's not found? Maybe it should depend on platform, because I think pkg-config is a Unix-y tool, but we try to call it on Windows as well. This might break installing from source in some cases where it currently works, but fewer supported options for trying to build would be simpler.

**Comment by zrzka** [comment]
I think that mention of the `pkg-config` in this section won't hurt. At least for Linux & macOS. I have zero experience with other platforms like Windows.

I'd say that it should fail if the `pkg-config` is not found. But as I wrote, zero experience on other platforms and I have no idea what it can break.

**Comment by talregev** [comment]
My original issue that you have this problems when you install the library through `pip install h5py` and not from source. you should install arm64 bit linux and test your installation process. you can install this Linux on your mobile phone. I can explain how if needed.

**Comment by talregev** [comment]
please change this issue type. It not document, it a bug in linux arm64 bit installation process. Thank you.

**Comment by takluyver** [comment]
PyPI has no pre-built packages for ARM, so `pip install` on any ARM architecture is building from source.

**Comment by takluyver** [comment]
I've removed the `documentation` tag for now, but it's still not clear to me exactly what the suggested change is.

@talregev Did you have `pkg-config` installed on the system you were trying this on? Can you get the informat @aragilar asked for:

> Can you run `pkg-config --cflags hdf5` and `pkg-config --libs hdf5`?
The outputs should be `-I/usr/include/hdf5/serial` and `-L/usr/lib/aarch64-linux-gnu/hdf5/serial -lhdf5` respectively. If they differ, can you post them?

**Comment by talregev** [comment]
pkg-config not install on this system.
Installing now and try again.

**Comment by talregev** [comment]
> @talregev Can you run `pkg-config --cflags hdf5` and `pkg-config --libs hdf5`?
> The outputs should be `-I/usr/include/hdf5/serial` and `-L/usr/lib/aarch64-linux-gnu/hdf5/serial -lhdf5` respectively. If they differ, can you post them?

When I run it with `pkg-config` after I install it, it run this it show the expected flags.

**Comment by takluyver** [comment]
And once you have `pkg-config` installed, can you install h5py without needing workarounds. I.e. without copying or renaming any libraries.

I think these cases point to making `pkg-config` a firm requirement for building, at least on Linux, unless the user specifies the `hdf5` path explicitly.

**Comment by talregev** [comment]
I agree.

**Comment by talregev** [comment]
If MPI is on the system, like openMPI, it compile with MPI by default?

**Comment by takluyver** [comment]
I believe you have to specify if you want MPI support; it's not automatic:

http://docs.h5py.org/en/stable/mpi.html#building-against-parallel-hdf5

**Comment by talregev** [comment]
Thank you 👍

**Comment by takluyver** [comment]
I've filed #1231 to implement my suggestion. But I don't know how many use cases it will fix and how many it will break. :confused:

**Comment by talregev** [comment]
Thank you

**Comment by LucasKr** [comment]
Hi everyone,

I had a similar issue working with ARM devices. Try installing h5py using `apt update && apt install -y python3-h5py`.

This may help.

**Comment by h3retek** [comment]
This worked for me:

https://docs.h5py.org/en/stable/build.html#source-installation-on-linux-other-unix

`sudo apt install python-dev libhdf5-dev`
