### ISSUE TITLE
warniiing

### ISSUE THREAD

**Issue by imanusita** [h5py/h5py#1189]
what s wrong !! 
Warning (from warnings module):
  File "C:\Users\SMART-TECH 2018\AppData\Local\Programs\Python\Python37\lib\site-packages\vtk\util\numpy_support.py", line 137
    assert not numpy.issubdtype(z.dtype, complex), \
FutureWarning: Conversion of the second argument of issubdtype from `complex` to `np.complexfloating` is deprecated. In future, it will be treated as `np.complex128 == np.dtype(complex).type`.

**Comment by tacaswell** [comment]
`File "C:\Users\SMART-TECH 2018\AppData\Local\Programs\Python\Python37\lib\site-packages\vtk\util\numpy_support.py", line 137` <- this looks like it is a warning coming out of vtk not h5py.  Why do you think this is a bug in h5py?

**Comment by imanusita** [comment]
and wht s the solution ? :(

**Comment by takluyver** [comment]
Ask [VTK](https://vtk.org/).
