### ISSUE TITLE
Impossible to create empty dataset using filter not installed

### ISSUE THREAD

**Issue by vallsv** [h5py/h5py#1191]
Hi,

I would like to feed a dataset with `write_direct_chunk` and an already compressed binary data. It looks like it is not possible.

Do you think it is a h5py limitation? An HDF5 library limitation? Or a limitation of the spec?

Tested with h5py 2.9.0.

Here is with an user filter, but it is the same for a registered filter.
```
import numpy
import h5py

reference = numpy.arange(16).reshape(4, 4)
FILTER_USER = 32768
encoded_data = b'\xFF\x01\x00\x01' * 10

with h5py.File("foo.h5", "w") as h5:
    dataset = h5.create_dataset("foo",
                                shape=reference.shape,
                                maxshape=reference.shape,
                                dtype=reference.dtype,
                                chunks=reference.shape,
                                compression=FILTER_USER)
    offsets = (0,) * len(reference.shape)
    dataset.id.write_direct_chunk(offsets=offsets, data=encoded_data, filter_mask=0x0000)
```

```
ValueError                                Traceback (most recent call last)
<ipython-input-1-532c8e8524ab> in <module>()
     12                                 dtype=reference.dtype,
     13                                 chunks=reference.shape,
---> 14                                 compression=FILTER_USER)
     15     offsets = (0,) * len(reference.shape)
     16     dataset.id.write_direct_chunk(offsets=offsets, data=encoded_data, filter_mask=0x0000)

/home/valls/.local/lib/python3.5/site-packages/h5py/_hl/group.py in create_dataset(self, name, shape, dtype, data, **kwds)
    134 
    135         with phil:
--> 136             dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
    137             dset = dataset.Dataset(dsid)
    138             if name is not None:

/home/valls/.local/lib/python3.5/site-packages/h5py/_hl/dataset.py in make_new_dset(parent, shape, dtype, data, chunks, compression, shuffle, fletcher32, maxshape, compression_opts, fillvalue, scaleoffset, track_times, external, track_order, dcpl)
    138         dcpl or h5p.create(h5p.DATASET_CREATE), shape, dtype,
    139         chunks, compression, compression_opts, shuffle, fletcher32,
--> 140         maxshape, scaleoffset, external)
    141 
    142     if fillvalue is not None:

/home/valls/.local/lib/python3.5/site-packages/h5py/_hl/filters.py in fill_dcpl(plist, shape, dtype, chunks, compression, compression_opts, shuffle, fletcher32, maxshape, scaleoffset, external)
    235     elif isinstance(compression, int):
    236         if not h5z.filter_avail(compression):
--> 237             raise ValueError("Unknown compression filter number: %s" % compression)
    238 
    239         plist.set_filter(compression, h5z.FLAG_OPTIONAL, compression_opts)

ValueError: Unknown compression filter number: 32768
```

**Comment by vallsv** [comment]
I just check removing  `h5z.filter_avail`. It looks to be fine.

**Comment by vallsv** [comment]
Not so obvious. I a afraid.

**Comment by tacaswell** [comment]
This seems dangerous to allow creating even an empty data set without the requested filter installed from the high-level interface.  Even if we allowed a way to do this, it seems a bit odd that you would be able to create a dataaset that the process creating it would not be able to read back.

I suspect it can be done with the lower-level interface.

**Comment by takluyver** [comment]
I agree with @tacaswell - it seems reasonable for creating a dataset in the high-level API to fail if the specified filters are not available.

**Comment by vallsv** [comment]
I don't understand your point. If you allow to use `write_direct_chunk`, it don't is why you enforce the dataset to be already created.

**Comment by tacaswell** [comment]
That is a fair point about using `write_direct_chunk`.  In that case you are well down the road of using all the foot-cannons so our attempts to keep you safe are more annoying than actually helpful.

This is something we should talk about during the h5py code camp!

**Comment by aragilar** [comment]
I'm slightly confused what the issue is, is it the filter isn't found by installed, but you want to tag the dataset as using that filter, or isn't the filter being found or something else?

**Comment by takluyver** [comment]
Using `write_direct_chunk`, the caller would do the compression (or other filtering) themselves and then give h5py the raw data. So it's possible to make e.g. a Zstd compressed dataset even if there isn't a Zstd HDF5 filter available.

I think the check should be on by default, because in normal usage it makes sense to error if a filter is unavailable, but there should be a way to skip it if you know what you're doing. Maybe on `h5py.get_config()`, or maybe an extra parameter to `create_dataset`.

**Comment by aragilar** [comment]
Given you'd be going through the low-level interface to do `write_direct_chunk` in any case, wouldn't it be possible to create the dataset using the low-level interface, which avoids the check (I'm wary of opening a way for people to provide invalid metadata)?

**Comment by takluyver** [comment]
It's possible, but I think it's a fair bit more involved to create a dataset in the low-level interface - you need to create and manipulate a property list to do anything non-default. So I'm sympathetic to the idea that it should be possible to create a dataset in the high-level interface and then fill it with the low-level.

**Comment by aragilar** [comment]
Would a `_allow_unknown_compression_filter` keyword be acceptable (with warnings in the docs and an explicit callout that filter plugins written on top of h5py must not use this, only users of `write_direct_chunk`)?

**Comment by takluyver** [comment]
I think `allow_unknown_filter` would be OK. I don't think it should be the default, but I'm not too worried about people turning it on when it's not what they want - you'll still get an error when you try to put data into the dataset.

**Comment by vallsv** [comment]
Thanks a lot. This extra attribute sounds like a good idea.
