### ISSUE TITLE
libhdf5 required? 

### ISSUE THREAD

**Issue by CDitzel** [h5py/h5py#1193]
I just started out on a fresh Ubuntu 18.04 without libhdf5. I then did pip install h5py within a virtualenv and it works. up until now, I thought libhdf5 is a requirement?

Why isnt it?

**Comment by tacaswell** [comment]
Did you install from source or install the wheel?  If you pulled the wheel it has the pre-built binaries along with libhdf5.

**Comment by CDitzel** [comment]
pip install h5py is all I did

**Comment by tacaswell** [comment]
I am going to close this issue as you almost certainly installed the wheel which has libhdf5 bundled.

If you want to build h5py against a local / system version of libhdf5 use ` pip install h5py --no-binary :all:`  (see https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-no-binary for docs).
