### ISSUE TITLE
Documentation provides invalid SSL certificate

### ISSUE THREAD

**Issue by fuglede** [h5py/h5py#1195]
Currently, https://docs.h5py.org serves an invalid certificate (valid only for readthedocs.org), but SSL on custom domains in Read the Docs should work more or less out-of-the-box. According to [the documentation](https://docs.readthedocs.io/en/stable/custom_domains.html#custom-domain-ssl):

> By default, when you setup a custom domain to host documentation at Read the Docs, we will attempt to provision a domain validated SSL certificate for the domain. This service is generously provided by Cloudflare.

From that same page, it would seem that one needs to use readthedocs.io (io instead of org) in the CNAME record to make use of this functionality though:

> Some older setups configured a CNAME record pointing to readthedocs.org or another variation. While these continue to resolve, they do not yet allow us to acquire SSL certificates for those domains.

And this is probably the reason it fails for h5py:

```
$ dig docs.h5py.org | grep CNAME
docs.h5py.org.          471     IN      CNAME   h5py.readthedocs.org.
```

So presumably, if this functionality is something you would want to make use of (which would be nifty), it seems that all it takes is an update to the CNAME record and a bit of clicking around:

>  Point the CNAME to readthedocs.io, with no subdomain, and re-request a certificate by saving the domain in the project admin

**Comment by tacaswell** [comment]
Did this _ever_ work?

**Comment by fuglede** [comment]
@tacaswell No, probably not. This was just to say that if it's something you want to work, Read The Docs have done all the hard work, and the feature is only a bit of configuration away.

**Comment by takluyver** [comment]
The docs now work over https (thanks @andrewcollette for updating the DNS). I've opened a new issue to update references to the docs: #1346.
