### ISSUE TITLE
Performance is slowed by file closing/dataset deletion

### ISSUE THREAD

**Issue by vyasr** [h5py/h5py#1198]
Reading h5py files inside a function is very slow, and it appears to be due to the objects being deleted when they go out of scope. There appears to be some sort of caching that h5py (or the underlying C library) is doing to ameliorate this issue, but my understanding is that since the Python object is directly referencing data on the file system, such caching shouldn't really affect performance, so I'm not sure what's happening.

Here's a test script to reproduce my problem (note the `del dset` line, which can be commented out to :

```
import timeit
import numpy as np
import h5py

data = np.random.rand(100000)

fn_npy = 'data.npy'
fn_h5 = 'data.hdf5'

np.save(fn_npy, data)
f = h5py.File(fn_h5, "w")
dset = f.create_dataset("phi", data=data)
del f
del dset  # Commenting out this line of code makes all the h5py calls benchmarked below much faster.

def test_np():
    np.load(fn_npy)

def test_h5():
    f = h5py.File(fn_h5, mode='r')
    f["phi"]

def test_h5_noref():
    h5py.File(fn_h5, mode='r')["phi"]

def test_h5_context():
    with h5py.File(fn_h5, mode='r') as f:
        f["phi"]

runs = 1000

print("Start testing")
print("NumPy file without function")
print(timeit.timeit('np.load(fn_npy)', number=runs, setup="import numpy as np; from __main__ import test_np, fn_npy"))

print("NumPy file with function")
print(timeit.timeit('test_np()', number=runs, setup="import numpy as np; from __main__ import test_np"))

print("HDF5 file without deletion")
print(timeit.timeit('f = h5py.File(fn_h5); f["phi"]', number=runs, setup="import h5py; from __main__ import test_h5, fn_h5"))

print("HDF5 file with deletion")
print(timeit.timeit('f = h5py.File(fn_h5); f["phi"]; del f', number=runs, setup="import h5py; from __main__ import test_h5, fn_h5"))

print("HDF5 file in function")
print(timeit.timeit('test_h5()', number=runs, setup="import h5py; from __main__ import test_h5"))

print("HDF5 file in function, no reference")
print(timeit.timeit('test_h5_noref()', number=runs, setup="import h5py; from __main__ import test_h5_noref"))

print("HDF5 file in function, context manager")
print(timeit.timeit('test_h5_context()', number=runs, setup="import h5py; from __main__ import test_h5_context"))
```

Here are the results of the above code:
```
Generating test dataset
Start testing
NumPy file without function
1.4790044540422969
NumPy file with function
1.4621074519818649
HDF5 file without deletion
1.1844787619775161
HDF5 file with deletion
9.935849407978822
HDF5 file in function
8.201861071982421
HDF5 file in function, no reference
8.166758915991522
HDF5 file in function, context manager
8.282954779977445
```

The fact that the hdf5 file is still fast when I directly run the code, but is slowed down dramatically when I delete the file object or read it inside a function (where I assume it is being deleted as soon as it goes out scope), is why I suspect some sort of caching. Additionally when I comment out the `del dset` line above, I get the following results:

```
Start testing
NumPy file without function
1.4307067829649895
NumPy file with function
1.455536628025584
HDF5 file without deletion
1.157123142038472
HDF5 file with deletion
1.1481331510003656
HDF5 file in function
1.1576306920032948
HDF5 file in function, no reference
1.1442511550267227
HDF5 file in function, context manager
1.2170071059954353
```

Here's information about my configuration:
```
$ uname -r
5.0.2-arch1-1-ARCH
$ which python
/usr/bin/python
$ python -c "import h5py; print(h5py.version.info)"
Summary of the h5py configuration
---------------------------------

h5py    2.9.0
HDF5    1.10.5
Python  3.7.2 (default, Jan 10 2019, 23:51:51)
[GCC 8.2.1 20181127]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.16.2
```

**Comment by tacaswell** [comment]
There is some subtle machinery for making sure that the python objects (which have one life time tied to python scope) and the underlying c++ objects (which may be shared across python objects!) are both managed correctly.   The underlying c++ objects will live as long as a python object is aware of it (for example, even though you deleted the file, the dset object still needed it so the c++ file object stayed alive, but when you delete the dataset object, it is released).  By guess is that timeit is somehow holding on to at least one reference to something (when you run it not in the function), but is everything is getting torn down inside the function.

A major concern with adding a more forgiving caching to `h5py` is that we can not know when you are _actually_ done with the object.   For a one-off script this is not likely to be a problem, but for something long-running this can lead to resource exhaustion.   I think it is the responsibility of you to keep a hard-reference to the file over the lifetime you care about it.


Vaguely related to https://github.com/h5py/h5py/issues/994

**Comment by vyasr** [comment]
That's at least partially consistent with my suspicions, I'm guessing that timeit just `exec`s the statement internally in a loop and so the reference counters aren't updated until the loop ends. However, I'm not sure that caching alone explains the difference. The numpy array-based function is reloading the file from disk every time, so there's no caching. If h5py is caching the file when the reference isn't released, then wouldn't you expect a larger performance difference (h5py still takes ~80% as long as NumPy in the second set of results above). Conversely, in the slow case above, even if h5py can't cache effectively, that still means there's ~5x slowdown relative to numpy in reading the array; I wouldn't expect HDF5 files to be that much slower to read. Is there some reason it should be?

**Comment by tacaswell** [comment]
Sorry, I miss-read your tables above, timeit is not doing anything funny with reference counting (and cpython updates the reference counts immediately internally).

The latency is not necessarily from disk I/O (and the OS does it's own caching which is transparent to hdf5).  When you open an hdf5 file the c++ library has to do a fair amount of validation and such (is this an hdf5 file? what datasets are init? are the internal b-trees valid? etc).  When you are letting the File object get gc'd (and hence the c++ objects are torn down / rebuilt every time) that is when it takes ~9s (and most of that time is overhead).  Put another way, what is being cached is meta-data state (not the data).

By contrast, the npy file format is extremely simple (iirc it is just enough meta-data to say what the type and shape of the array is and then is just a stream of bytes) so there is no overhead.

You may be interested in pytables which is a higher-level abstraction on top of hdf5 files that has some sice python-side caching / batching to improve performance for the usecases it targets.

You may also be interested in chunking and compression in hdf5 (sometimes you can win via compression when the wall time of de-compression is less than walltime you save by reading fewer bits from disk).

I am going to close this as I think this is expected behavior and there is nothing we can do on the h5py side.   I suggest following up to the h5py or hdf5 mailing lists.

**Comment by vyasr** [comment]
I see. I didn't expect there to be that much overhead associated with hdf5 metadata, but I can certainly see that npy files might be an unfair comparison there given their relative simplicity. In practice, I think I can refactor my workflow to accumulate all my data into one large hdf5 file that's read in using a generator that keeps the file open until all the data has been read, so that might resolve the issue for my use-case. Otherwise npy files are perfectly acceptable for me, I just wasn't sure if this was a problem in h5py or not. Thanks for the explanation.

**Comment by tacaswell** [comment]
The target use case for hdf5 is very large files with a modest number of large multi-dimensional datasets that you want to be able to slice into efficiently.  In that context, the start up time ends up being very modest (when amortized).

Depending on how many you have, beware of having too many groups/data sets inside of an hdf5 file (as that can also run into some bad scalings).

**Comment by vyasr** [comment]
Got it. So my current use-case involves something like 1000s of arrays, each of which is of size (10, 100, 100, 100) or so, and I'm going to need to read these many times over the course of an algorithm. Would it be reasonable to consider concatenating all of those into a single (N, 10, 100, 100, 100) dataset in one HDF5 and directly indexing into that? Should I be looking into HDF5's chunking features for this purpose? Or am I just shoehorning HDF5 into a problem that it's really not optimally suited for, and leaving it as a large number of small npy files is a better option?

**Comment by tacaswell** [comment]
Yes, putting those into 1 big array or 1k individual datasets should both be ok.

Definitely look into chunking, if you get it right in relation to your access patterns you can get good performance gains.
