### ISSUE TITLE
Document behaviour when create_dataset is called multiple times

### ISSUE THREAD

**Issue by mdickinson** [h5py/h5py#1201]
Sometime between h5py 2.7.0 and h5py 2.9.0, the behaviour when `create_dataset` tries to create an already existing dataset changed from raising `RuntimeError` to raising `OSError` (see shell / Python transcripts below). This broke some of our code. That part's fine (the unit tests did their job and caught the breakage), but where I'm having difficulty is in figuring out the correct way to fix that code.

Would it be possible for the documentation to specify the expected behaviour when `create_dataset` is called with the path to an already existing dataset? Specifically, I'd like to know whether there are any guarantees on the type of the exception we get at this point (or even any guarantees on whether we get an exception). If not, I guess we should be doing a LBYL check for the dataset first ourselves and raising a suitable exception, but if we can rely on the exception type from h5py, our code becomes simpler.

Here's the old behaviour I see on macOS 10.14.4 / Python 3.6.0 from EDM / h5py 2.7.0:
```
mirzakhani:Desktop mdickinson$ edm envs create --force --version 3.6 test-oldh5py >/dev/null 2>&1
mirzakhani:Desktop mdickinson$ edm install -y -e test-oldh5py "h5py^=2.7.0" >/dev/null 2>&1
mirzakhani:Desktop mdickinson$ edm run -e test-oldh5py -- python
Enthought Deployment Manager -- https://www.enthought.com
Python 3.6.0 |Enthought, Inc. (x86_64)| (default, Mar  3 2017, 03:26:01) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py; h5py.__version__
/Users/mdickinson/.edm/envs/test-oldh5py/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
'2.7.0'
>>> f = h5py.File("testfile.hdf5", "w")
>>> f.create_dataset("default", (100,))
<HDF5 dataset "default": shape (100,), type "<f4">
>>> f.create_dataset("default", (100,))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mdickinson/.edm/envs/test-oldh5py/lib/python3.6/site-packages/h5py/_hl/group.py", line 111, in create_dataset
    self[name] = dset
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/mdickinson/.edm/envs/test-oldh5py/lib/python3.6/site-packages/h5py/_hl/group.py", line 276, in __setitem__
    h5o.link(obj.id, self.id, name, lcpl=lcpl, lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 202, in h5py.h5o.link
RuntimeError: Unable to create link (Name already exists)
```

And the new behaviour, on macOS 10.14.4 / Python 3.6.0 from EDM / h5py 2.9.0:

```
mirzakhani:Desktop mdickinson$ edm envs create --force --version 3.6 test-newh5py >/dev/null 2>&1
mirzakhani:Desktop mdickinson$ edm install -y -e test-oldh5py h5py >/dev/null 2>&1
mirzakhani:Desktop mdickinson$ edm run -e test-newh5py -- python
Enthought Deployment Manager -- https://www.enthought.com
Python 3.6.0 |Enthought, Inc. (x86_64)| (default, Mar  3 2017, 03:26:01) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py; h5py.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'h5py'
>>> ^D
mirzakhani:Desktop mdickinson$ edm envs create --force --version 3.6 test-newh5py >/dev/null 2>&1
mirzakhani:Desktop mdickinson$ edm install -y -e test-newh5py h5py >/dev/null 2>&1
mirzakhani:Desktop mdickinson$ edm run -e test-newh5py -- python
Enthought Deployment Manager -- https://www.enthought.com
Python 3.6.0 |Enthought, Inc. (x86_64)| (default, Mar  3 2017, 03:26:01) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py; h5py.__version__
'2.9.0'
>>> f = h5py.File("testfile.hdf5", "w")
>>> f.create_dataset("default", (100,))
<HDF5 dataset "default": shape (100,), type "<f4">
>>> f.create_dataset("default", (100,))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mdickinson/.edm/envs/test-newh5py/lib/python3.6/site-packages/h5py/_hl/group.py", line 139, in create_dataset
    self[name] = dset
  File "/Users/mdickinson/.edm/envs/test-newh5py/lib/python3.6/site-packages/h5py/_hl/group.py", line 371, in __setitem__
    h5o.link(obj.id, self.id, name, lcpl=lcpl, lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 202, in h5py.h5o.link
OSError: Unable to create link (name already exists)
```

**Comment by rmvanhees** [comment]
Dear Mark,

Maybe I did not get your problem.

You could check is a dataset exist:

if "default" in f:

   f.create_dataset("default", (100,))

Or you can use the function f.require_dataset("default", (100,))

Greetings, Richard

**Comment by vasole** [comment]
If you replace your create_dataset by require_dataset calls it should work. The require_dataset is supposed to create it if not existing or using it if exists. You can even make sure the existing one matches what you expect:

http://docs.h5py.org/en/stable/high/group.html#Group.require_dataset

**Comment by tacaswell** [comment]
This is due to a change in the hdf5 library.  They do not consider error codes to be part of the public API which causes us some trouble.  
See discussion around https://github.com/h5py/h5py/pull/1099, https://github.com/h5py/h5py/issues/1088 and http://docs.h5py.org/en/stable/faq.html#exceptions

**Comment by mdickinson** [comment]
@tacaswell Thank you: that doclink answers my question: h5py refuses to provide guarantees on the exception type. That's unfortunate for our purposes, but I understand where this comes from.

`require_dataset` isn't what I want or need here. We have our own library calls that end up calling `create_dataset`, and I simply want to be able to document in our own docstrings the exception raised by those library calls when attempting to (erroneously, of course) write a dataset that already exists. Given that h5py makes no guarantees here, we'll need to do an `try / except` to catch all exceptions around the `h5py` call, and then raise our own exception.

Not sure why the `bug-in-external-lib` label was added: this issue is simply about getting clarification on what guarantees h5py makes about exceptions, and that documentation link provides that clarification. Thank you.

**Comment by tacaswell** [comment]
> h5py refuses to provide guarantees

We would like to, but given that the codes can change in hdf5 bug-fix releases we can not.  The exact same h5py code built against different patch version of hdf5 will have different exceptions. 

Probably what we should do is mix an h5py specific base-class into the errors we raise from hdf5 codes so even if you can't get the exact type, you can at least filter on that rather than just `Exception`.
