### ISSUE TITLE
Unlimited dimension for one VDS dimension

### ISSUE THREAD

**Issue by mrosanes** [h5py/h5py#1202]
To assist reproducing bugs, please include the following:
 * Operating System: Debian9 
 * Python version: 3.7.3
 * Where Python was acquired: conda
 * h5py version: 2.9.0
 * HDF5 version: 1.10.4 

Hello,

According to VDS specifications, an unlimited dimension for VDS is accepted; but according to https://github.com/h5py/h5py/issues/1167, this feature is not exposed in the high-level API of h5py. At Alba synchrotron we would be really interested in such a feature.

Our use case is performing scans where each point (a source h5 file) is a single image coming from a 2D detector; all the source images would have to be mapped into a single VDS. For cases where we do not know the number of scan points in advance, an extensible VDS with an unlimited dimension would be ideal. (It could even be interesting for scans for which we know the number of points in advance, given that the scans could be stopped/aborted before finishing it).

The use case in which we are interested is described in point **8.5** of the HDF5 VDS requirements:
[Fixed dimension Full Source and Unlimited dimension Virtual Dataset Mapping](https://support.hdfgroup.org/HDF5/docNewFeatures/VDS/HDF5-VDS-requirements-use-cases-2014-12-10.pdf)

(eventually we could also be interested in point **8.3**:  Unlimited dimension Source and Unlimited dimension Virtual Dataset Mapping)

Even if recreating a VDS could be a cheap operation at the beginning, for performing long scans (with a high number of points) it could become more expensive. Having an unlimited dimension in the VDS, would avoid having to recreate the layout, mapping all the sources and recreate the VDS, each time that a new image (scan point) arrives.

**Comment by bomber8013** [comment]
I discovered a possible fix for this issue at https://github.com/h5py/h5py/pull/1686#issuecomment-703189449 . Reposting the snippet below. Example outputs can be seen in referenced comment. 
```
with h5py.File("resize", "w") as f:
    source_dset = f.create_dataset(
        "source",
        data=np.arange(20),
        shape=(10, 2),
        maxshape=(None, 2),
        chunks=(10, 1),
        fillvalue=-1
    )
    layout = h5py.VirtualLayout((10, 1), np.int, (None, 1))
    layout_source = h5py.VirtualSource(source_dset)
    layout[:, 0] = layout_source[:, 1]
    for vspace, fpath, dset, src_space in layout.sources:
        vspace.select_hyperslab((0, 0), (h5py.h5s.UNLIMITED, 1))
        src_space.select_hyperslab((0, 1), (h5py.h5s.UNLIMITED, 1))
    
    virtual_dset: h5py.Dataset = f.create_virtual_dataset("virtual", layout)
```
To try and include this in the h5py high-level library, perhaps an additional keyword to either `h5py.VirtualSource` and/or `h5py.VirtualLayout` then let the constructor in `h5py.make_new_virtual_dset` take care of the low-level calls.

**Comment by bomber8013** [comment]
@takluyver in reference to the conversation at https://github.com/h5py/h5py/pull/1686#issuecomment-703232079 I have made modifications to the `VDSmap` class to add a method for setting an axis to unlimited, so that the above snippet would turn into below:
```
with h5py.File("resize", "w") as f:
    source_dset = f.create_dataset(
        "source",
        data=np.arange(20),
        shape=(10, 2),
        maxshape=(None, 2),
        chunks=(10, 1),
        fillvalue=-1
    )
    layout = h5py.VirtualLayout((10, 1), np.int, (None, 1))
    layout_source = h5py.VirtualSource(source_dset)
    layout[:, 0] = layout_source[:, 1]
    layout.sources[0].set_unlimited(0)  # where we set unlimited
    virtual_dset: h5py.Dataset = f.create_virtual_dataset("virtual", layout)
```

**Comment by takluyver** [comment]
`VDSmap` is kind of an internal detail (not documented anywhere). I think that ideally, the interface for doing this would be with `VirtualSource` & `VirtualLayout` objects, something like:

```
layout[:h5py.h5s.UNLIMITED, 0] = layout_source[:h5py.h5s.UNLIMITED, 0]
```
