### ISSUE TITLE
OSError: Unable to open file (unable to open file: name = 'C:\Users\(name blocked)\Scripts\Neural_Network.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

### ISSUE THREAD

**Issue by Cookiedough611** [h5py/h5py#1220]
* Windows 10
 * Python version 3.7
 * Miniconda
 * h5py version: latest
I was trying to load a model with Keras and train it again. 

Here is my code:

```python
import gym
import random
import numpy as np
import tflearn
import os
import h5py
import tensorflow as tf
from tensorflow import keras
from keras.models import load_model
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.estimator import regression
from statistics import mean, median
from collections import Counter

LR = 1e-3

env = gym.make('CartPole-v0')
env.reset()

goal_steps = 300

score_requirement = 50

initial_games = 10000

def some_random_games_first():
    for episode in range (5):
        env.reset()
        for t in range(goal_steps):
            env.render()
            action = env.action_space.sample()
            observation, reward, done, info = env.step(action)
            if done:
                break

def intial_population():
	training_data = []
	scores = []
	accepted_scores = [] 
	for _ in range (initial_games):
		score = 0
		game_memory = []
		prev_observation = []
		for _ in range (goal_steps):
			action = random.randrange (0,2)
			observation, reward, done, info = env.step(action)

			if len(prev_observation) > 0:
				game_memory.append([prev_observation, action])

			prev_observation = observation
			score += reward
			if done:
				break
		if score >= score_requirement:
			accepted_scores.append(score)
			for data in game_memory:
				if data [1] == 1:
					output = [0, 1]
				elif data [1] == 0:
					output = [1, 0]

				training_data.append([data[0], output])
		env.reset()
		scores.append(score)
	training_data_save = np.array (training_data)
	np.save ("saved.npy", training_data_save)
	print ("Average accepted scores", mean(accepted_scores))
	print("Median accepted score: ", median(accepted_scores))
	print (Counter (accepted_scores))

	return training_data
intial_population()

def neural_network_model (input_size):
	network = input_data (shape=[None, input_size, 1], name="input")
	network = fully_connected(network, 128, activation="relu")
	network = dropout(network, 0.8)

	network = fully_connected(network, 256, activation="relu")
	network = dropout(network, 0.8)

	network = fully_connected(network, 512, activation="relu")
	network = dropout(network, 0.8)

	network = fully_connected(network, 256, activation="relu")
	network = dropout(network, 0.8)

	network = fully_connected(network, 128, activation="relu")
	network = dropout(network, 0.8)

	network = fully_connected(network, 2, activation="softmax")
	network = regression(network, optimizer="adam", learning_rate = LR, loss = "categorical_crossentropy", name = 'targets')
	model = tflearn.DNN (network, tensorboard_dir='log")

	return model

def train_model(training_data, model=False):
	X = np.array ([i [0] for i in training_data]).reshape(-1, len(training_data[0][0]), 1)
	y = [i [1] for i in training_data]

	if not model:
		model = neural_network_model (input_size = len(X[0]))
	model.fit({'input' :X}, {'targets' :y}, n_epoch=3, snapshot_step=500, show_metric=True,
		run_id='openaistuff')
	return model

training_data = intial_population()
model = train_model(training_data)


scores = [] 
choices = []

for each_game in range(1):
	score = 0
	game_memory= []
	prev_obs = []
	env.reset()
	for _ in range (goal_steps):
		env.render()
		if len(prev_obs) == 0:
			action = random.randrange (0,2)
		else:
			action = np.argmax(model.predict(prev_obs.reshape(-1, len(prev_obs),1)) [0])
		choices.append(action)

		new_observation, reward, done, info = env.step(action)
		prev_obs = new_observation
		game_memory.append ([new_observation, action])
		score += reward
		if done:
			break
	scores.append(score)
	model.save("C:\\Users\\William\\Scripts\\Neural_Network.h5")
Average_Score = sum(scores)/len(scores)
print("Average Score: ", Average_Score)
print("choice 1:{}  choice 0:{}".format(choices.count(1)/len(choices),choices.count(0)/len(choices)))
print(score_requirement)
if Average_Score > 299:
	print("Solved")
else:
	print("Not solved, trying again")
	new_model = load_model("C:\\Users\\William\\Scripts\\Neural_Network.h5")'
```

And when I would run the program I would get this error:

```
Traceback (most recent call last):
  File "C:\Users\William\Scripts\Cartpole.py", line 157, in <module>
    new_model = load_model('C:\\Users\\William\\Scripts\\Neural_Network.h5')
  File "C:\Users\William\Miniconda3\envs\tensorflow\lib\site-packages\keras\engine\saving.py", line 417, in load_model
    f = h5dict(filepath, 'r')
  File "C:\Users\William\Miniconda3\envs\tensorflow\lib\site-packages\keras\utils\io_utils.py", line 186, in __init__
    self.data = h5py.File(path, mode=mode)
  File "C:\Users\William\Miniconda3\envs\tensorflow\lib\site-packages\h5py\_hl\files.py", line 394, in __init__
    swmr=swmr)
  File "C:\Users\William\Miniconda3\envs\tensorflow\lib\site-packages\h5py\_hl\files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'C:\Users\William\Scripts\Neural_Network.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

I have looked at the file and it generates the files: checkpoint,(thing used for the file type 'file'), Neural_Network.h5.data-00000-of-00001, Neural_Network.h5, and Neural_Network.h5.meta.
I see the 'Neural_Network.h5' so I am not sure why it cannot load it. Any answers are appreciated!

Edit: sorry for bad code formatting I saw it and cannot seem to fix it

**Comment by takluyver** [comment]
A number of people seem to have reported similar issues to Keras:

https://github.com/keras-team/keras/issues/8661
https://github.com/keras-team/keras/issues/10592

I don't see any obvious cause, though I'd suspect something to do with Windows paths.

**Comment by vasole** [comment]
I had some issues once with windows interpreting \U as the start of an encoded string. Prepending r (to indicate raw strings) prior to the name of the file solved the problems.

If that is your problem, something like the string below would work:

r'C:\Users\William\Scripts\Neural_Network.h5'

**Comment by takluyver** [comment]
The code snippet @Cookiedough611 posted already has the slashes doubled up `"C:\\Users..."`, which should have the same effect as `r"C:\Users..."`.

**Comment by 648374hub** [comment]
I'm experiencing the same problem while running my code on Google Colab. If any of you have got the way to solve it, please do share.

**Comment by tacaswell** [comment]
Could this be a race condition between when it is saved and when it is attempted to be read back?

**Comment by mechlya** [comment]
try to replace the Backslash '\'  in your path by Forward slash ' /'.
C:\Users\William\Scripts\Neural_Network.h5
=============>
C:/Users\William/Scripts/Neural_Network.h5

**Comment by IvanEvan** [comment]
1. If you run **a.py** got the error, but you load the **model.h5** in **b.py**
2. Please cp **model.h5** to the same level directory with **a.py**
3. Edit **b.py's load('xx/model.h5')** to **load('model.h5')**

It worked for me.

**Comment by sebastiaanvbb** [comment]
for people on Google colab, add the following to your string if reading from drive:

r'/content/gdrive/My Drive/NAME_OF_FILE'

**Comment by biswajit310** [comment]
OSError                                   Traceback (most recent call last)
<ipython-input-33-ec96be8617c2> in <module>()
    101 # loss_weights define the ratio of how much I care about optimizing each one
    102 
--> 103 model.load_weights("./weights/1pred_weights.25--0.08.hdf5", by_name=True) # the by_name=True allows you to use a different architecture and bring in the weights from the matching layers
    104 
    105 model.compile(optimizer=RMSprop(lr=5e-4), 

3 frames
/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    171         if swmr and swmr_support:
    172             flags |= h5f.ACC_SWMR_READ
--> 173         fid = h5f.open(name, flags, fapl=fapl)
    174     elif mode == 'r+':
    175         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (unable to open file: name = './weights/1pred_weights.25--0.08.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)






Hi, Im facing this error. Plz help me

**Comment by Malithi-gif** [comment]
fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 108, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = './checkpoints/yolov4-416', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 302)
 Can you help me?

**Comment by theumang100** [comment]
@Malithi-gif  have you got the solution?

**Comment by Maj18** [comment]
Thanks for the help Ivan, I encountered similar problem:
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to lock file, errno = 35, error message = 'Resource temporarily unavailable')

As suggested, I moved the input file to the working folder, and didn't specify any path to it when I call it, only the file name, then it worked.

**Comment by Fahad113** [comment]
I had the same **[Error](https://github.com/h5py/h5py/issues/1220)** but now it worked.
I resolved this error by giving absolute path with double backslash ("C:\\data\\model.hdf5") 
the line of code is **model = keras.models.load_model("C:\\data\\model.hdf5")**

**Comment by JuanAlonsoCba** [comment]
# download CARS DATA from this url: https://ai.stanford.edu/~jkrause/cars/car_dataset.html

## %cd /content    <----------------------------------
## !git clone http://imagenet.stanford.edu/internal/car196/cars_train.tgz 
## !tar -xvzf cars_train.tgz

**Comment by AliSheheryar** [comment]
I had the same issue. No such h5 file found. 
" Provided the absolute path and Voila! it worked"

**Comment by callmekofi** [comment]
I had a similar issue on mac. I resolved it by changing the path name.

**Comment by yuedi-hhh** [comment]
我也遇到了这个错误，我是因为创建h5文件的path路径上的文件夹不存在，所以出现此报错。当我把路径的文件夹都创建好就没问题了

**Comment by nikunjthakkar** [comment]
> I had the same issue. No such h5 file found. " Provided the absolute path and Voila! it worked" Edit: I am using Colab.

Where did you provided the path for hdf5 file?

Thanks

**Comment by shrikantcombio** [comment]
> > I had the same issue. No such h5 file found. " Provided the absolute path and Voila! it worked" Edit: I am using Colab.
> 
> Where did you provided the path for hdf5 file?
> 
> Thanks

Provide a full PATH of your respective file to the h5py.File

import h5py
f = h5py.File('mytestfile.hdf5', 'r')

**Instead try this:**
f = h5py.File('/home/user/hdf5/mytestfile.hdf5', 'r')

**Comment by nikunjthakkar** [comment]
> > > I had the same issue. No such h5 file found. " Provided the absolute path and Voila! it worked" Edit: I am using Colab.
> > 
> > 
> > Where did you provided the path for hdf5 file?
> > Thanks
> 
> Provide a full PATH of your respective file to the h5py.File
> 
> import h5py f = h5py.File('mytestfile.hdf5', 'r')
> 
> **Instead try this:** f = h5py.File('/home/user/hdf5/mytestfile.hdf5', 'r')

it worked, thanks

**Comment by oooo111** [comment]
> The code snippet @Cookiedough611 posted already has the slashes doubled up `"C:\\Users..."`, which should have the same effect as `r"C:\Users..."`.
This is correct answer,it solve my problem

**Comment by alanlivio** [comment]
Just to registred here I was able to bypass the error by using the variable HDF5_USE_FILE_LOCKING='FALSE' from the command line.

**Comment by tacaswell** [comment]
I am going to close this as it is collecting a number of different issues none of which we can help with at the h5py level:

 - using a relative path and not being in the working directory expected (fixed on the user side by either changing the working directory, changing the relative path, or using an absolute path)
 - issues with libhdf5 file locking (see discussion in https://github.com/h5py/h5py/issues/1101
 - unicode paths on windows (which I _think_ should already be fixed in newer versions of h5py?  If we have a clean example of this please create a new issue with it)
 - Python string escaping issues (use "raw" strings `r'\not \escaped'` or put in enough slashes to escape them all)
