### ISSUE TITLE
Could we get a new minor release?

### ISSUE THREAD

**Issue by rsignell-usgs** [h5py/h5py#1227]
This PR from February https://github.com/h5py/h5py/pull/1132 fixed quite a few workflows, but the last release 2.9.0 is from December. 

It would be very useful to get a new minor release 2.9.1 if possible.

**Comment by scopatz** [comment]
I think @takluyver is working on getting 2.10 out the door.

**Comment by takluyver** [comment]
Yup, 2.10 is my goal. #1132 is new functionality, so it wouldn't be in a bugfix release anyway.

We're [getting there](https://github.com/h5py/h5py/milestone/16) on 2.10, but there's still some way to go.

**Comment by rsignell-usgs** [comment]
In case folks need the #1132 functionality, @ocefpaf built a 2.10 dev release on conda-forge:
```
conda install -c conda-forge/label/dev h5py
```
