### ISSUE TITLE
Readthedocs not updating

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#1230]
I noticed that some bits of the docs don't reflect recent changes. Sure enough, there hasn't been a [RTD build](https://readthedocs.org/projects/h5py/builds/) for 5 months. They're not failing, just not starting at all. We probably need to reconfigure the webhook - I'm not sure why, but I've had to do this for a number of projects.

@tacaswell @andrewcollette - if you want to add me (takluyver) to the project on Readthedocs, I can probably fix this in a few minutes.

**Comment by takluyver** [comment]
It looks like Github 'services', which RTD previously used for triggers, have been deprecated for some time, and delivery stopped at the end of January. That would explain why we need to do something to get further builds.

**Comment by tacaswell** [comment]
Added you as a maintainer.

**Comment by takluyver** [comment]
Thanks. It should update next time someone merges a PR.
