### ISSUE TITLE
How to resolve this issue while using facebook prophet anaconda3/lib/python3.7/site-packages/pystan/misc.py:399: FutureWarning:  Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.

### ISSUE THREAD

**Issue by drsanchikagupta** [h5py/h5py#1251]
To assist reproducing bugs, please include the following:
 * Operating System: MacOS 10.11
 * Python version ( 3.7)
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows)
 * h5py version (e.g. 2.9.0)
 * HDF5 version (e.g. 1.10.4)
Tried everything given in #961

**Comment by scopatz** [comment]
Thanks for opening this @drsanchikagupta.  My suspicion is that this is an issue with prophet, unrelated to h5py. Do you have a minimal example that demonstrates the issue?

**Comment by takluyver** [comment]
Closing as this doesn't appear to be an issue with h5py.
