### ISSUE TITLE
ImportError: cannot import name _errors

### ISSUE THREAD

**Issue by thirdlastletter** [h5py/h5py#1252]
To assist reproducing bugs, please include the following:
 * Operating System Ubuntu 16.04
 * Python version 2.7,
 *  Anaconda environment
 * h5py version (I can't find out, I keep getting error messages)

`Traceback (most recent call last):
  File "train.py", line 3, in <module>
    import h5py
  File "/usr/lib/python2.7/dist-packages/h5py/__init__.py", line 24, in <module>
    from . import _errors
ImportError: cannot import name _errors
`

I keep on getting these error messages, does anyone have experience with this?

**Comment by scopatz** [comment]
Hi @thirdlastletter - thanks for opening this up.  This seems to indicate that your h5py was not installed or compiled correctly.  Is there a minimal example you can show us?
