### ISSUE TITLE
pip download h5py fails on Python 2.7

### ISSUE THREAD

**Issue by Anthchirp** [h5py/h5py#1257]
Trying to `pip download h5py` fails on Python 2.7. This is due to `setup.py` adding a setup-time requirement for numpy. This has now become a problem because numpy 1.17.0rc1 (Python 3 only) was released yesterday.

 * Operating System: RHEL6
 * Python version: 2.7
 * Where Python was acquired: near system python
 * h5py version: 2.9
 * HDF5 version: N/A
 * The full traceback/stack trace shown (if it appears)

```
$ pip download h5py==2.9.0 --no-binary=h5py --no-cache-dir -d base_tmp/ --isolated             

Collecting h5py==2.9.0
  File was already downloaded base_tmp/h5py-2.9.0.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-download-otzrwv/h5py/setup.py", line 168, in <module>
        cmdclass = CMDCLASS,
      File "python2.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "python2.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "python2.7/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
        replace_conflicting=True,
(..)
      File "/scratch/wra62962/files/temp/python27/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-Zo5gcH/numpy-1.17.0rc1/setup.py", line 31, in <module>
    
    RuntimeError: Python version >= 3.5 required.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-download-otzrwv/h5py/
```

Code causing issue:
https://github.com/h5py/h5py/blob/b887dacf18c10d262cebec4b98d2554ca50cb4f8/setup.py#L39-L43

`pip` calls `setup.py`with parameter `egg_info`.
I would suggest to either
* add `egg_info` to the white list resulting in `use_setup_requires=False`, or (preferably imo)
* changing the logic to `use_setup_requires=False` to be the default and setting it to `True` only in those cases where you explicitly want it to be set.

**Comment by scopatz** [comment]
Pull requests welcome!

**Comment by tacaswell** [comment]
Is this also a problem with newer pips?

**Comment by Anthchirp** [comment]
This is with pip 19.1.1, setuptools 41.0.1 in a clean virtual environment.
