### ISSUE TITLE
TypeError: 'compression' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by Young-Sook** [h5py/h5py#1261]
I am now using python 3.6.8 in linux and installed h5py 2.9.0. I have a bug when I run the command below. 

f = h5py.File(rcFileName, "w", compression="gzip")

TypeError: 'compression' is an invalid keyword argument for this function

When I reinstalled h5py 2.6.0 instead of 2.9.0, I didn't get any error. I guess there is a bug  in the new 2.9.0 version?

**Comment by takluyver** [comment]
h5py 2.6 accepted any keyword arguments for `File()` and ignored the ones it didn't recognise, including `compression`. From 2.7, `File()` throws an error on unrecognised keywords (#752). This helps to catch bugs in your code where a parameter is not doing anything.

Compression is something you decide when creating a dataset - you can have different compression for different datasets in the same file.

http://docs.h5py.org/en/stable/high/dataset.html#filter-pipeline
