### ISSUE TITLE
Slicing returns copies instead of references

### ISSUE THREAD

**Issue by IgnacioJPickering** [h5py/h5py#1268]
When using h5py I encountered an unexpected behaviour, I think it is not a bug but undocumented behaviour and I believe it would be surprising to anyone familiar with numpy.

h5py slicing seems to always return copies of the sliced datasets instead of returning views, while numpy returns views.

Since I didn't find any way to return a view of a slice (i.e a reference in h5py nomenclature I suppose) I assume that this is not a feature that exists. 

The only reference to these differences I found is in [read_direct](http://docs.h5py.org/en/stable/high/dataset.html#Dataset.read_direct) which says that using the method

>  (...) can avoid making an intermediate copy as happens with slicing. (...)

Perhaps I was very naive to expect references to datasets instead of copies when slicing?

This is my h5py.version.info output:

```
Summary of the h5py configuration
---------------------------------

h5py    2.9.0
HDF5    1.10.4
Python  3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.16.4

```

**Comment by scopatz** [comment]
There isn't really a way to return a view, as the data lives on disk.

**Comment by scopatz** [comment]
Is there a more concrete example that demonstrates the issue?

**Comment by IgnacioJPickering** [comment]
Yes, I guess that makes sense. 

A concrete example: [()], for instance, in numpy returns a view for any multidimensional array but a scalar for 0-dim arrays. I'm used to writing code that assumes this overloaded functionality, but it seems that the intended use is different in h5py.

```
with h5py.file('path', 'r+') as f:
       d = f['dataset_key'][()]
```

copies the dataset into ```d```, but 

```
with h5py.file('path', 'r+') as f:
       d = f['dataset_key']
```

turns ```d``` into a hard link, whereas in numpy the behavior is to make ```d``` a view (which is analogous to a hard link in a way?)  in both cases.

Effectively, ```f['dataset_key'][()]``` behaves as ```np.copy(f['dataset_key'])```. I don't have a problem with the behavior if it is the intended behavior, its just strange that it is not explicitly documented. The behaviour is the same as numpy's behaviour for 0-dim arrays though. The same happens for all slices.

**Comment by takluyver** [comment]
Slicing reads the data from the file to return a numpy array. This is briefly documented here:
http://docs.h5py.org/en/stable/high/dataset.html#reading-writing-data

I agree it doesn't highlight the differences from numpy's behaviour. Maybe that's an area for improvement. You could in principle have a view of data on disk, but loading it into an in-memory array seems like the obvious thing to do.

There are 'region references' providing something kind of analogous to views, but the API isn't the same, and I don't think you can create one region reference from another, for instance:
http://docs.h5py.org/en/stable/refs.html#using-region-references

**Comment by IgnacioJPickering** [comment]
@scopatz, @takluyver, thank you for your comments, I should probably have used the mailing list but I wasn't sure if this behavior was intended. I'm glad region references exist, that is very useful to me, I wasn't aware of that feature.
