### ISSUE TITLE
ValueError: Dimensionality is too large

### ISSUE THREAD

**Issue by Puumanamana** [h5py/h5py#1269]
Hi,

I have been using h5py for a while, and it worked great.
I recently started working on a different server, and for some reason, I can't write arrays larger than something like 100 integers.

Here is the test I'm doing:

```
import h5py
import numpy as np

test = h5py.File('test.h5','w')
# It works
test.create_dataset('abc',np.zeros(10))

# it doesn't work
test.create_dataset('abc',np.zeros(100))
```

Here is the traceback:
```
~/.py3Env/lib/python3.7/site-packages/h5py/_hl/group.py in create_dataset(self, name, shape, dtype, data, **kwds)
    134
    135         with phil:
--> 136             dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
    137             dset = dataset.Dataset(dsid)
    138             if name is not None:

~/.py3Env/lib/python3.7/site-packages/h5py/_hl/dataset.py in make_new_dset(parent, shape, dtype, data, chunks, compression, shuffle, fletcher32, maxshape, compression_opts, fillvalue, scaleoffset, track_times, external, track_order, dcpl)
    162         sid = h5s.create(h5s.NULL)
    163     else:
--> 164         sid = h5s.create_simple(shape, maxshape)
    165
    166

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5s.pyx in h5py.h5s.create_simple()

ValueError: Dimensionality is too large (dimensionality is too large)
```

Here are my system specs:
 * Ubuntu 16.04.2
 * Python 3.7 (both with and without Anaconda)
 * h5py version: 2.9.0
 * HDF5 version: 1.8.16

SOLVED: I forgot to put `data=` in the `create_dataset()` call

**Comment by twallema** [comment]
Ran into the same issue. Could I suggest the devs to provide an input check with a more descriptive error message for this issue?

**Comment by MrCrHaM** [comment]
Had the same issue, and the commit message above inspired me.
Instead of **positional argument** `h.create_dataset(key, arr)`, use **keyword argument**
```python
h.create_dataset(key, data=arr)
```
And the reason is simply that `data` is not the second argument.
