### ISSUE TITLE
Add Release Automation

### ISSUE THREAD

**Issue by scopatz** [h5py/h5py#1270]
I think we could tighten the feedback loop on releasing h5py if we had a tool that helped us issue releases. 

I propose we add [rever](https://regro.github.io/rever-docs/) to h5py.  However, there may be other options out there (modeltee?).

**Comment by takluyver** [comment]
Modeltee is working but pretty barebones, and so far I haven't applied it to any project besides itself. I still mean to get back to it some day, but I wouldn't wait for that.

So I'm on board with adding rever. It looks pretty polished, and I imagine you have a thorough understanding of it. :-)

**Comment by scopatz** [comment]
Sounds good to me!  Do we have a list / docs anywhere about how we release h5py right now? I'l like to try to match the current release steps

**Comment by scopatz** [comment]
@tacaswell @matthew-brett @andrewcollette - Can I get push/admin access to PyPI for h5py please? You may want to add @takluyver too, while your there.

**Comment by takluyver** [comment]
Ping @tacaswell @matthew-brett @andrewcollette: could one of you add @scopatz on PyPI so he can make releases?

It would also be useful to hear (from @tacaswell?) how recent releases were made - e.g. do we use the CI setup to build any binaries?

**Comment by matthew-brett** [comment]
I think I don't have PyPI permissions to add anyone.

I _believe_ that the recent releases have been using the the https://github.com/MacPython/h5py-wheels repository, at least for the Manylinus and macOS wheels, but @tacaswell is the person who knows.

**Comment by tacaswell** [comment]
I also do not seem to have permissions to manage the project, I suspect only @andrewcollette has those rights.

@matthew-brett is correct, we use the macpython machinery to build the mac and linux wheels and 
Christoph Gohlke has built the windows wheels.

**Comment by tacaswell** [comment]
Me and @matthew-brett are now owners, what are your pypi names?

**Comment by takluyver** [comment]
I am [takowl](https://pypi.org/user/takowl/), @scopatz is [scopatz](https://pypi.org/user/scopatz/).

**Comment by scopatz** [comment]
This is great news!

**Comment by tacaswell** [comment]
Permissions granted.

**Comment by takluyver** [comment]
@scopatz do you want to do the release automation for 2.10? Or would you rather aim for one more manual release and then automate it for 2.11?

**Comment by scopatz** [comment]
Still aiming to have it for 2.10.  Sorry, I have been on vacation the last couple of weeks, but will try to get it built out this week
