### ISSUE TITLE
h5repack method

### ISSUE THREAD

**Issue by luiztauffer** [h5py/h5py#1272]
**Problem:**
I need to delete specific groups from a file, which contain large datasets. For that, I’m doing: 
```python
with h5py.File(‘file_name’, 'a') as f:
    del f['group_name']
```
This indeed removes the group, but the file size remains unchanged.

In scattered answers online, I found a possible solution would be using [h5repack](https://support.hdfgroup.org/HDF5/doc/RM/Tools.html#Tools-Repack). I can’t find, however, if this method is implemented anywhere in h5py. 
I’m opening this issue in the hope that it’s a reasonable request. 

* Operating System: Windows 10
 * Python version 3.7
 * Anaconda 3
 * h5py version 2.9.0
 * HDF5 version 1.10.4

**Comment by jangarrevoet** [comment]
h5repack is part of the h5lib so it is a stand alone executable. You should be able to just execute it from a terminal or whatever it is called on windows.

**Comment by luiztauffer** [comment]
@jangarrevoet any alternative method to that, then? I'm looking for a pythonic solution, cross-platform

**Comment by jangarrevoet** [comment]
I would simply use subprocess.

**Comment by scopatz** [comment]
Pytables has repack functionality that I think you can import. Also, PRs welcome here. Also, note that repack creates a new, smaller file. It doesn't change the size of the existing file.

**Comment by takluyver** [comment]
Pytables has a [ptrepack](https://github.com/PyTables/PyTables/blob/v3.5.2/tables/scripts/ptrepack.py) script which has some extra options to control how Pytables features are copied. It doesn't have a public Python API for that, as far as I can see.

As the `h5repack` command exists, and I don't think libhdf5 exposes a repack API, I'm inclined to say it's out of scope for h5py. Of course, there's nothing to stop someone implementing it as a separate package if you can't rely on running `h5repack` for some reason.

**Comment by aragilar** [comment]
I think what @luiztauffer wants is #1100. I would guess h5repack/ptrepack reduce file sizes by only including data that exists when copying to a new file, which could be done walking the tree of the file and copying things over in h5py. Given that would be a reimplementation of both h5repack/ptrepack, and with less features and more bugs, I don't the advantage of h5py duplicating h5repack/ptrepack.

**Comment by danschef** [comment]
> Given that would be a reimplementation of both h5repack/ptrepack, and with less features and more bugs, I don't the advantage of h5py duplicating h5repack/ptrepack.

I agree that a reimplementation does not make so much sense. But why not simply calling `h5repack `under the hood of `h5py`? This would implement the needed functionality without duplicating any code. So far as I understood, `h5repack `is installed together with `h5py `anyways.

It just took me some hours today to figure out why the file size does not get smaller even if I remove all of the large array data in my HDF5 file. I tried different modes when calling `h5py.File()` and was already thinking about a bug in the context manager or the `flush`/`close `methods..

**Comment by takluyver** [comment]
h5repack is not necessarily installed alongside h5py - if you install h5py from a wheel (with pip), the HDF5 library is bundled, but not any of the HDF5 command line tools. Even if the command line tools are installed somewhere, there's no guarantee they're on PATH - and if they are, they might be for a different version of HDF5 which doesn't support all the objects in the file. And even if we can find and run h5repack, it presumably wouldn't work while h5py has the file open for writing, because of file locking.

Given all that, I don't think we should try to wrap it in h5py. =

**Comment by danschef** [comment]
Well, in this case, it should be mentioned in the documentation ([here](https://docs.h5py.org/en/stable/high/file.html)) that the HDF5 file has to be repacked to really reduce the file size after deleting datasets from it. You could simply add a link to h5repack there and leave the installation up to the user.

I just did not know that h5py does not automatically repack the file when closing it. It would have been a matter of minutes for me to do that if this information was included somewhere in the docs.

**Comment by tacaswell** [comment]
Automatically calling `h5repack` on close is not something safe to do.  If you remove something small from the start of a very big file, you could incur a huge amount of I/O as you re-write multiple gigabytes of data to reclaim a few kb. 

@danschef I think we would happily merge a PR to the docs adding the text that would have saved you time/confusion!
