### ISSUE TITLE
Resizing an attribute is broken

### ISSUE THREAD

**Issue by hameerabbasi** [h5py/h5py#1274]
* Operating System: macOS 10.13.6
 * Python version: 3.7.3
 * Where Python was acquired: Miniconda
 * h5py version `master`
 * HDF5 version 1.10.5

```python
>>> import h5py
>>> import tempfile
>>> f = tempfile.mkstemp('.h5')
>>> f = h5py.File(f[1], 'w')
>>> f
<HDF5 file "tmp7fhvio72.h5" (mode r+)>
>>> g = f['/']
>>> g.create_dataset('a', dtype='<f8', maxshape=None, shape=(0,))
<HDF5 dataset "a": shape (0,), type "<f8">
>>> ds = g['a']
>>> ds
<HDF5 dataset "a": shape (0,), type "<f8">
>>> import numpy as np
>>> ds.attrs['b'] = np.empty((0,), dtype='<u8')
>>> ds.attrs['b'].resize((5,))
>>> ds.attrs['b'].shape
(0,)
```
May be solved by #797

**Comment by takluyver** [comment]
I think this is expected for the current API. When you do `ds.attrs['b']`, it reads and returns a regular numpy array. Naturally, resizing that doesn't affect the HDF5 attribute. You can 'resize' it by assigning a new array with a different shape.

#797 is indeed the issue requesting a high-level API to interact with attributes directly.
