### ISSUE TITLE
Unexpected behaviour when indexing multiple dimensions

### ISSUE THREAD

**Issue by ju-he** [h5py/h5py#1277]
- OS: Linux Mint 19.2
- Python: 3.6.8
- h5py: 2.9.0

In numpy indexing via array[i,j] and array[i][j] are equivalent:
```
>>> a = np.random.random(size=3)
>>> b = np.zeros(shape=(2,2,3))
>>> b[0,0] = a
>>> b[0][0]
array([0.86413749, 0.64801094, 0.90344875])
>>> b[1][1] = a
>>> b[1,1]
array([0.86413749, 0.64801094, 0.90344875])

```
This behaviour is different when using h5py
```
>>> f = h5py.File("test_file")
>>> dset = f.create_dataset("test",(2,2,3))
>>> dset[0,0] = a
>>> dset[0,0]
array([0.8641375 , 0.64801097, 0.90344876], dtype=float32)
>>> dset[1][1] = a
>>> dset[1][1]
array([0., 0., 0.], dtype=float32)
```
It is noteworthy, that there is only a difference when using the notation for storing data, not for retrieving:
```
>>> dset[0][0]
array([0.8641375 , 0.64801097, 0.90344876], dtype=float32)
```

I found this quite unexpected, especially since the dataset simply remains unchanged without telling the user that no data is saved. This might be the correct behaviour but maybe some sort of notification would be beneficial.

**Comment by takluyver** [comment]
I don't know that there's any good way around this without dramatically changing the way h5py works. `dset[1]` gives you a numpy array in memory, so `dset[1][1] = a` is the same as:

```python
arr = dset[1]
arr[1] = a
```

**Comment by tacaswell** [comment]
I think that this needs a big red warning box in the docs.

We could make the numpy arrays returned unwritable by default (ex https://stackoverflow.com/questions/5541324/immutable-numpy-array) which would break some intended uses, but would prevent this sort of bug (by failing hard and fast).

This is related to https://github.com/h5py/h5py/issues/975
