### ISSUE TITLE
H5 file  write incompletely and also  appears write nothing but save h5 file in the end

### ISSUE THREAD

**Issue by ruanjian0821** [h5py/h5py#1279]
Hi, I meet a bug in generating h5 files.

As follow:

![5555](https://user-images.githubusercontent.com/40518319/62752451-28939000-ba9a-11e9-8088-ac33362eb36a.png)

![none](https://user-images.githubusercontent.com/40518319/62752497-4f51c680-ba9a-11e9-8390-f956b1fd2bc5.png)

Have friends encountered such a problem ?

**Comment by ruanjian0821** [comment]
H5 file write incompletely and also appears write nothing but save h5 file in the end.

**Comment by takluyver** [comment]
Can you show some example code that produces the problem?

**Comment by takluyver** [comment]
Closing as there's not enough information to know what's going on.
