### ISSUE TITLE
Move/rename h5py.tests.old

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#1281]
PR #484 (in 2014) moved all the tests existing up to that point into a subpackage called `old`. I feel this naming is confusing:

- It implies that those tests are deprecated, when they still seem to test many things which aren't tested anywhere else, and I'm not aware of any plan to migrate away from them (please correct me if there is one).
- There are often two places to look for existing tests, or where to add new tests. E.g. tests for slicing datasets are in both `h5py.tests.old.test_slicing` and `h5py.tests.hl.test_dataset_getitem`.

I propose moving all the tests modules into a flat namespace in `h5py.tests`. Or if we need some more structure, organise them more descriptively (e.g. high-level vs low-level).

**Comment by aragilar** [comment]
I'd think this is a great idea! I'd suggest keeping the VDS tests in their own directory, since they're currently split out nicely anyway, but I think keeping it mostly flat should make things simpler.

**Comment by takluyver** [comment]
Done in #1283
