### ISSUE TITLE
[Conda] Install via Conda Builds its Own HDF5 Instead of Using Predefined Dev-Level Install

### ISSUE THREAD

**Issue by JPGlaser** [h5py/h5py#1286]
The title here says it all. When using conda instead of pip for the install, h5py installs its own version of hdf5 library files which are not compilable and cause errors when installing other software that depends on h5py and hdf5. However, when installing via pip, it uses the system environment's hdf5 install if present (the correct behavior).

Why is this?

Mirror Issue at:
https://github.com/conda-forge/h5py-feedstock/issues/61

 * Operating System: Latest Ubuntu 18 LTS
 * Python version: Python 2.17.16
 * Where Python was Acquired: Anaconda for Linux
 * h5py Install Info:
```
h5py    2.9.0
HDF5    1.10.4
Python  2.7.16 |Anaconda, Inc.| (default, Aug 15 2019, 23:16:23) 
[GCC 7.3.0]
sys.platform    linux2
sys.maxsize     9223372036854775807
numpy   1.16.4

```

**Comment by aragilar** [comment]
As noted in the conda-forge bug, this is an anaconda issue, you'll need to raise it with them.

**Comment by tacaswell** [comment]
> However, when installing via pip, it uses the system environment's hdf5 install if present (the correct behavior).

The wheel should include it's own version of hdf5 as well, if it does fallback to the system hdf5 that seems like a problem (as you may have an incompatible version of hdf5 at the system level).
