### ISSUE TITLE
Multithreaded version?

### ISSUE THREAD

**Issue by isaacgerg** [h5py/h5py#1287]
Are there any plans to build a wheel that can handle simultanous reads of different files from different python threads?

Re:
https://stackoverflow.com/questions/34906652/does-hdf5-support-concurrent-reads-or-writes-to-different-files

https://discuss.pytorch.org/t/hdf5-multi-threaded-alternative/6189/2

**Comment by takluyver** [comment]
AIUI, all access through h5py is protected by a single lock (called 'phil' in the code - I assume this is something like Python HDF5 Interface Lock). So it should be safe to use it in multiple threads, but it won't actually do simultaneous reads. It [looks like this also applies to HDF5](https://portal.hdfgroup.org/display/knowledge/Questions+about+thread-safety+and+concurrent+access):

> The thread-safe version of the HDF5 library effectively serializes the HDF5 library calls. It is thread-safe but not thread-efficient.

If you want to read HDF5 data in parallel, I believe you either need separate processes opening and reading independently, or to [use MPI with it](http://docs.h5py.org/en/stable/mpi.html).

I'm not aware of any plans to change how any of this works.

**Comment by takluyver** [comment]
Closing as there isn't anything to do here (as far as I understand it).

**Comment by tacaswell** [comment]
I do not think that wheels carry enough meta-data to let us safely upload a wheel built with MPI (as it may not be the _right_ MPI for your system).  conda-forge does build verisions of libhdf5 and h5py against the flavors of mpi that is supports, I suggest looking into that.
