### ISSUE TITLE
+ㅠ

### ISSUE THREAD

**Issue by eastchun** [h5py/h5py#1288]
To assist reproducing bugs, please include the following:
 * Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 16.04.2 LTS, CentOS 7)
 * Python version (e.g. 2.7, 3.5)
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows)
 * h5py version (e.g. 2.6)
 * HDF5 version (e.g. 1.8.17)
 * The full traceback/stack trace shown (if it appears)

`h5py.version.info` contains the needed versions, which can be displayed by
```
python -c 'import h5py; print(h5py.version.info)'
```
where `python` should be substituted for the path to python used to install
`h5py` with.

**Comment by tacaswell** [comment]
@eastchun This looks like it is the issue template without any edits, was this opened in error?  I'm going to close this as no-op, but if you do have an issue please update with details and ping to have this re-opened or open a new issue.

**Comment by eastchun** [comment]
Hi Thomas,

Sorry. It was generated by an error.
Apologize...

East
