### ISSUE TITLE
Iterate over keys by index

### ISSUE THREAD

**Issue by famfop** [h5py/h5py#1292]
This is not really a bug report but I couldn't find a better place to ask the question.
I've got an hdf5-file with a Group 'Outputs' where I have sub-groups 'Output1', 'Output2', ... 'Output81'. I iterate over the sub-groups via

```
g = f['Outputs']
keys = g.keys()
for i, key in list(enumerate(keys)):
    < do some stuff >
```

But here is my problem: The order of the loop is 'Output1', 'Output10', ... 'Output2', ... whereas I want the order as above (1, 2, ..., 81). 

So, my solution was to simply iterate like `for i in range(1,len(keys))`. Now I've got the problem: I cannot access keys[i], as `TypeError: 'KeysViewHDF5' object is not subscriptable`. Do you have a (alternative?) solution to this problem?

EDIT: I use Python 3.

##################

EDIT2: Please close this issue, I just found my error!

**Comment by tacaswell** [comment]
I am glad you got sorted @famfop .  Could you leave a comment explaining how you fixed it for a future reader?

**Comment by famfop** [comment]
Sure, my solution is simple: I just iterate via `for i in range(len(g.keys()))` and for each iteration I define an `element = g["Output{}".format(i+1)]` from which I can easily access datasets/attributes. The `i+1` is due to the outputs starting with 1.

**Comment by nanonand** [comment]
Hi I am having the same issue, I want to sort my keys according to the ascending value of the number and not alphanumerically. And I also want to index the keys, I tried your methods I couldn't seem to make it work. Can I ask for further guidance?
