### ISSUE TITLE
Release notes for 2.10 went missing

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#1295]
@scopatz: Commit 1156f5ac1ca38db85dcd906cf19a7aba90d0b39a seems to have deleted the release notes. I assume it was meant to move it to `docs/whatsnew`. I'll fix this manually, but presumably it means there's something wrong with the rever setup?

**Comment by takluyver** [comment]
Fixed the immediate problem in 6e685d41767306b8f7b4a1d22eecf3edbca7dc43.

**Comment by scopatz** [comment]
Yes this was supposed to move it there.  I'lll dig into what happened.

**Comment by scopatz** [comment]
This has been fixed by https://github.com/regro/rever/pull/200

**Comment by takluyver** [comment]
Thanks!
