### ISSUE TITLE
Generated AUTHORS file fails EOF check

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#1297]
The generated AUTHORS file has a couple of blank lines at the end. This fails a check in the CI that files should end with a single newline.

cc @scopatz

**Comment by takluyver** [comment]
(Again, it's obviously easy to fix the immediate issue, but presumably we want to fix how it's generated, so it doesn't recur after each release)

**Comment by scopatz** [comment]
Yep, I have fixed this in upstream rever.  Rever v0.4.1 has the fix for this.  Shouldn't happen again.
