### ISSUE TITLE
Custom installation fails on OS X 10.14.6 (Mojave) && Python 3.7.4

### ISSUE THREAD

**Issue by sr-murthy** [h5py/h5py#1298]
OS: OS X 10.14.16 (Mojave)
Python: Python 3.7.4 (installed in `/Library/Frameworks/Python.framework/Versions/3.7`)
h5py version: 2.10.0
HDF5 version: 1.10.5 (installed via `brew install hdf5`

I am trying to install the H5py (`h5py`) Python wrapper for the HDF5 library (https://pypi.org/project/h5py/) in a virtual env. on my MacBook Air (mid 2019) running OS X 10.14.6 (Mojave). The Python version is 3.7.4. 

For reference, I used the H5py build instructions page https://h5py.readthedocs.io/en/stable/build.html.

As `h5py` requires MPICH (http://www.mpich.org) and the HDF5 (https://www.hdfgroup.org/solutions/hdf5/) system libraries, I installed these via Brew, and then installed `h5py` using a fork of the Git repository (https://github.com/h5py/h5py).

These are the steps I followed in the given order.

    1. brew install mpich && pip install mpi4py

    2. brew install hdf5

    3. git clone https://github.com/mygit/h5py

    4. cd h5py && python setup.py configure --mpi

    5. python setup.py configure --hdf5=/usr/local/Cellar/hdf5

    6. python setup.py install

Everything seemed to be fine with the last step (`h5py` install).

    ...
    Using /path/to/venv/lib/python3.7/site-packages
    Finished processing dependencies for h5py==2.10.0

    $ pip freeze | grep h5py
    h5py==2.10.0

But I am unable to import `h5py` in Python 3.

    In [1]: import h5py                                                                                                               
    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-1-c9f0b8c65221> in <module>
    ----> 1 import h5py

    /path/to/venv/lib/python3.7/site-packages/h5py-2.10.0-py3.7-macosx-10.9-x86_64.egg/h5py/__init__.py in <module>
         32         raise
         33 
    ---> 34 from . import version
         35 
         36 if version.hdf5_version_tuple != version.hdf5_built_version_tuple:

    /path/to/venv/lib/python3.7/site-packages/h5py-2.10.0-py3.7-macosx-10.9-x86_64.egg/h5py/version.py in <module>
         15 
         16 from collections import namedtuple
    ---> 17 from . import h5 as _h5
         18 import sys
         19 import numpy

    h5py/h5.pyx in init h5py.h5()

    ImportError: dlopen(/path/to/venv/lib/python3.7/site-packages/h5py-2.10.0-py3.7-macosx-10.9-x86_64.egg/h5py/defs.cpython-37m-darwin.so, 2): Symbol not found: _H5Fget_mpi_atomicity
      Referenced from: /path/to/venv/lib/python3.7/site-packages/h5py-2.10.0-py3.7-macosx-10.9-x86_64.egg/h5py/defs.cpython-37m-darwin.so
      Expected in: flat namespace
     in /path/to/venv/lib/python3.7/site-packages/h5py-2.10.0-py3.7-macosx-10.9-x86_64.egg/h5py/defs.cpython-37m-darwin.so

Can someone please explain what the problem is here?

**Comment by takluyver** [comment]
Educated guesswork: you've built h5py with MPI support, but hdf5 itself without MPI support?

http://docs.h5py.org/en/stable/mpi.html#building-against-parallel-hdf5
https://support.hdfgroup.org/HDF5/faq/parallel.html

**Comment by sr-murthy** [comment]
If so then perhaps the `brew` HDF5 installation (Step 2) installed the serial, not parallel, version of HDF5. In that case I guess I could try building HDF5 from source with the parallel configuration step.

    ./configure --enable-parallel

**Comment by takluyver** [comment]
I'd guess so. I'm not a Mac user, but I think a normal build of HDF5 does not include MPI integration.

**Comment by sr-murthy** [comment]
Tried to build HDF5 parallel from source but failed at the parallel configure step

    ...
    checking whether a simple MPI-IO C program can be linked... no
    configure: error: unable to link a simple MPI-IO C program

I'm not sure it's worth continuing as the h5py 2.9.0 does install without any problems. As the standard non-parallel HDF5 installation (via Brew) was fine, I was wondering why it h5py requires the parallel version.

**Comment by takluyver** [comment]
> I was wondering why it h5py requires the parallel version.

If you want to build h5py with MPI support, you need HDF5 with MPI support, as far as I know. If you don't need MPI support, then you can use the standard build of both. I'm not sure why this would be different from 2.9 to 2.10, but we did make some changes to the configure & build scripts.

**Comment by tacaswell** [comment]
You explicitly asked to build the mpi version of h5py here

> 4. cd h5py && python setup.py configure --mpi

**Comment by sr-murthy** [comment]
OK thanks, will try this.

**Comment by sr-murthy** [comment]
I tried this and was able to build 2.10.0 (`python setup.py configure --mpi && python setup.py install`), but I still get the same error. Before this, I had uninstalled the brew installed HDF5 and reinstalled it, using the standard option (without any parallel configuration).

**Comment by sr-murthy** [comment]
Note: I have tried both options now - building HDF5 and then h5py without and with MPI support, the import of h5py still fails.

**Comment by takluyver** [comment]
Do you *want* MPI support? Unless you're planning to write code using MPI, focus on installing both libraries without MPI support, because that's the 'normal' way.

**Comment by sr-murthy** [comment]
No, I don't want MPI support. I installed the standard version of HDF5 via brew, and then tried to install `h5py` 2.10.0 via pip, which has not worked.

**Comment by takluyver** [comment]
OK, then don't use the `--mpi` flag to configure. If you've got a copy of the source tree where you've already done that, you might need to clear some state before rebuilding it, because I think it stores the configuration.

What went wrong when trying to install it with pip? You've only described installing with `setup.py` until now.

**Comment by sr-murthy** [comment]
I'm pleased to say that I've tried this again with a fresh install of h5py and the import has worked.

THe problem wasn't the installation, it was the import error in iPython, which is gone now. Thanks again for your help.
