### ISSUE TITLE
expose VDS prefix property - feature request

### ISSUE THREAD

**Issue by jangarrevoet** [h5py/h5py#1305]
Hi,

proposing a new feature to expose the search path for VDS files. I copied the white paper documentation below.
Currently when moving data around the VDS file has a high chance of not working anymore since it can not find the files. I would like to make it a bit more robust for my users by implementing some more standard search paths than the standard "".

thanks,

Jan

Choose the Path to Search for Locating Source Datasets or Files
Virtual datasets can rely on source datasets whose containing files may not be located in the same directory as the virtual dataset. A path to locate files for source datasets may be specified in one of two ways: an environment variable (“HDF5_VDS_SOURCE_PATH”) or with the following property set on a dataset access property list:
status = H5Pset_virtual_source_path(dapl_id, source_path);
Parameters:
dapl_id source_path
- The identifier for the dataset access property list for the VDS.
- This parameter is a string containing a colon-separated list of paths to search for files containing source datasets. The default value is the null string (“”). The paths specified by the “HDF5_VDS_SOURCE_PATH” environment variable are searched before the paths specified by this property.
Returns: negative on error, and positive on success.

**Comment by tacaswell** [comment]
It looks like this feature was proposed, but not implemented (see https://forum.hdfgroup.org/t/h5pset-virtual-source-path/3820 ) 

This feature request should go to the hdf5 group first, once it is in libhdf5 h5py will definitely support it.  I am going to close this as I don't think there is anything actionable at the moment.

**Comment by jangarrevoet** [comment]
It seems that it was implemented since then: https://www.hdfgroup.org/2018/04/why-should-i-care-about-the-hdf5-1-10-2-release/ (section: Locations of the VDS source files)

**Comment by tacaswell** [comment]
Fair enough.  Do we have to do anything to make the ENV setting work?

We will need to expose those two additional methods.

**Comment by tacaswell** [comment]
https://portal.hdfgroup.org/display/HDF5/H5P_GET_VIRTUAL_PREFIX
https://portal.hdfgroup.org/display/HDF5/H5P_SET_VIRTUAL_PRE

the API docs.

**Comment by jangarrevoet** [comment]
> Fair enough. Do we have to do anything to make the ENV setting work?

I will test that tomorrow and will get back to you.

**Comment by takluyver** [comment]
Note that what got implemented is a simple prefix, not a search path. I've modified the issue title and opened #1320 with it.
