### ISSUE TITLE
Add CI job for development version of hdf5

### ISSUE THREAD

**Issue by tacaswell** [h5py/h5py#1311]
With hdf5 1.12 coming later this year, it will good to start testing for regressions and to start to expose new features.

**Comment by pierlauro** [comment]
You can find following a Dockerfile to be used in CI.

It provides 3 optional arguments configurable at container build time:
- `HDF5_BRANCH` (default `develop`)
- `H5PY_BRANCH`(default `master`)
- `HDF5_MPI` (default `OFF`)

It performs the following actions:
- Install HDF5 dependencies
- Clone hdf5 from the official repository and checkout `HDF5_BRANCH`
- Compile and install hdf5
- Install h5py dependencies
- Clone h5py and checkout `H5PY_BRANCH`
- Run install h5py and run tests with the specified `HDF5_MPI` option

```dockerfile
ARG HDF5_BRANCH="develop"
ARG H5PY_BRANCH="master"
ARG HDF5_MPI="OFF"

FROM debian:10

RUN apt-get update

RUN apt-get install -y git mpich

RUN apt-get install -y gcc autoconf libtool-bin make g++ zlib1g-dev pkg-config

RUN mkdir /repos

WORKDIR /repos

### HDF5
RUN git clone https://bitbucket.hdfgroup.org/scm/hdffv/hdf5.git hdf5
WORKDIR hdf5
ARG HDF5_BRANCH
RUN git checkout $HDF5_BRANCH

RUN ./autogen.sh

RUN ./configure --prefix=/usr --enable-parallel

RUN make -j `nproc` && make install

### H5PY
RUN apt-get install -y python3.7-dev python3-pip tox
RUN python3.7 -m pip install mpi4py

WORKDIR /repos

RUN git clone https://github.com/h5py/h5py h5py
WORKDIR h5py
ARG H5PY_BRANCH
RUN git checkout $H5PY_BRANCH

ARG HDF5_MPI
RUN CC=mpicc HDF5_MPI=$HDF5_MPI tox -re py37-test-deps
```

**Comment by takluyver** [comment]
Oops, I duplicated this accidentally as #1604. I'm going to close this one, because I think the new issue better describes what needs to be done. But I've linked back to here and referred to @pierlauro's Docker file.
