### ISSUE TITLE
[feature request] Add public API to get the path / library that h5py is using

### ISSUE THREAD

**Issue by tacaswell** [h5py/h5py#1315]
This will make writing plugin wheels easier. attn @vasole

**Comment by kif** [comment]
The place to store that is in h5py.h5 ...

**Comment by takluyver** [comment]
Another option we discussed was to expose pointers to the C functions from libhdf5 so plugins can use those.

@vasole - can you list the HDF5 functions you need for the compression side, so we can judge the feasibility of different ways to get them?

**Comment by vasole** [comment]
Yes, the idea is that the actual HDF5 library functions could be replaced by proxys configurable via a pointer to the actual HDF5 functions. That way the decompression could be guaranteed without having to patch the original code of the plugins while compression could still be enabled.

For the bitshuffle+LZ4 filter the functions are

1. H5Zregister
2. H5Epush1
3. H5Pget_filter_by_id2

For Blosc they seem to be (untested)

1. H5Zregister
2. H5Epush
3. H5Pget_filter_by_id
4. H5Tget_size
5. H5Tget_super
6. H5Tclose
7. H5Pmodify_filter

**Comment by t20100** [comment]
For getting pointers to the C function API, using `dlopen`/`dlsym` on a Python extension of h5py (e.g., `h5z`) seems to give access to the HDF5 library symbols, e.g., from Python:

```
import _ctypes, os
h = _ctypes.dlopen(h5py.h5z.__file__, os.RTLD_LOCAL)
_ctypes.dlsym(h, 'H5Epush1')
```

**Comment by t20100** [comment]
We've refactored the `hdf5plugin` project (https://github.com/silx-kit/hdf5plugin) without the need from `h5py` to provide access to C pointers.
For Linux and macOS, using `dlopen` on a `h5py` module (e.g. `h5py.h5z`) gives access to the symbol of the HDF5 library, while on Windows the symbols of the HDF5 library are available for linking once the HDF5 library is loaded.

As this issue was opened as part of discussing `hdf5plugin`, I think it can be closed.

**Comment by vasole** [comment]
We intend to make a new release, but some feedback using the wheels available via the link below (or trying to build from source) would be appreciated.

https://silx.gitlab-pages.esrf.fr/bob/hdf5plugin/

**Comment by takluyver** [comment]
Thanks all, nice work on figuring out how to handle that.

Slightly off-topic for this issue, but I got an idea looking at your readme. Would you be interested if h5py 3.0 could allow you to get rid of the `**kwargs` thing?

```python
f.create_dataset('blosc_byte_shuffle_blosclz', data=numpy.arange(100),
    compression=hdf5plugin.Blosc(level=9, shuffle='byte'))

# Instead of
f.create_dataset('blosc_byte_shuffle_blosclz', data=numpy.arange(100),
    **hdf5plugin.blosc_options(level=9, shuffle='byte', compression='blosclz'))
```

**Comment by takluyver** [comment]
I've created #1389 for further discussion of that idea - I'll close this issue now.
