### ISSUE TITLE
String conversions for h5py 3.0

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#1338]
@tacaswell, @aragilar and myself sat down yesterday to discuss how various string-like types should be mapped between Python and HDF5. We have decided we do want to make some changes for h5py 3.0. This will inevitably break some code using h5py, but we think it will create a more consistent API, which is also a better fit with Python 3's separation of bytes & str.

We have divided the rules into three kinds of conversion:

```python
# 1. Writing to an existing dataset
f['data'][:10] = obj
# Also applies to creating datasets with data and a specified dtype
f.create_dataset('data', dtype=x, data=obj)

# 2. Creating a new dataset without a specified dtype
f['data'] = obj
f.create_dataset('data', data=obj)

# 3. Reading data
obj = f['data'][:]
```

We aim to ensure that `f['data2'] = f['data1'][:]` will always create the new dataset with the same data type as the copied one. We believe the rules below preserve this - please comment if you notice a case we've missed.

## 1. Writing to existing datasets

Everything rejects numpy U dtypes (UTF-32 fixed width), as in h5py 2.x, because there is no equivalent HDF5 type.

### fixed-width ascii

- accept bytes
- accept str and encode to ascii, error on invalid ascii
  - If you need to write non-ascii data, encode it first and pass bytes
- check that it will fit in width, raise if not
 
### fixed width utf-8
 - accept bytes, just check length
 - accept str, encode to utf-8

### variable width ascii
 - accept any bytes (except NULL)
 - accept str, encode to ascii, error on non-ascii
 
### variable length utf-8
- accept any bytes (except NULL)
- accept str, encode to utf-8

### Opaque
- accept bytes, np.void()
- reject str

## 2. Creating datasets

- numpy object/string array with 'tagged' dtype -> follow the tag
  - tagged means a dtype with string metadata created by h5py to indicate
    string charset & width
- numpy string array not tagged -> fixed width ascii
- numpy object array of bytes not tagged -> void opaque **(see discussion in comments)**
  - List of bytes -> opaque
- numpy object array of str not tagged -> variable length utf-8
  - list of str -> variable length utf-8
- numpy void array -> opaque
- numpy array of U type -> raise

## 3. Reading data

- ASCII Fixed -> numpy 'S' (tagged with ASCII encoding)
- UTF-8 Fixed -> numpy 'S' (tagged with UTF-8 encoding)
- ASCII Variable -> numpy 'O' of bytes (tagged with ASCII encoding via dtype)
- UTF-8 Variable -> numpy 'O' of bytes (tagged with UTF-8 encoding via dtype)
- Opaque with no tag -> numpy 'V'
- Opaque with h5py dtype tag -> follow tag

## Attributes

Attributes follow the same rules as for datasets, with a couple of exceptions:

- An attribute created from a single str/bytes object will be a scalar
  vlen string with UTF-8 charset (str) or ASCII (bytes).
- An attribute with a scalar vlen string type will be returned as a single
  str/bytes object depending on its charset, to preserve roundtripping.
- Section 1 does not apply, as h5py does not expose a high-level API to modify
  an attribute.

**Comment by takluyver** [comment]
@tacaswell @aragilar I forget what we said about assigning a single str/bytes object to a dataset:

```python
f['data'] = 'foo'
f['data'] = b'foo'
```

Currently these work, creating a scalar dataset of vlen string (UTF-8 or ASCII depending on the type). I think we mentioned them, but I don't remember what we concluded.

**Comment by takluyver** [comment]
Yes, I believe that's the idea.

**Comment by takluyver** [comment]
@t20100 brought to my attention with #1420 that currently h5py allows writing *any* object to a vlen string dataset, as if you did `str(obj).encode()`. I propose that we remove that for h5py 3.0, and only allow string types to be written (str, bytes, numpy string arrays and object arrays of str/bytes).

We would be making a potentially breaking change without a deprecation period, but I think it's a clear enough benefit to be worth it. Silently converting things to strings is not helpful. People who want to store the `str()` of objects can code that explicitly.

**Comment by chrisjbillington** [comment]
Since arbitrary bytes are allowed in UTF8 datasets (by HDF5 regardless of what h5py does), could you use the [`surrogateescape` error handler](https://www.python.org/dev/peps/pep-0383/) when encoding and decoding so that these round-trip? You are probably familiar with it, but if not, this is what Python stdlib functions use to decode bytes that are supposed to be a particular encoding, but are not guaranteed to be, like filenames in unix.

**Comment by takluyver** [comment]
I started trying to work on section 2 (picking a datatype for new datasets), but quickly ran into issues with the idea of turning bytes objects into *opaque* data:

There are two kinds of variable-length data types in HDF5: a string with size H5T_VARIABLE, or a vlen wrapping another datatype. We can't make an opaque datatype with variable size, as I think we assumed when we were planning this.

So, if someone does `f['a'] = [b'a', b'bc']`, we can create a dataset of:

1. strings, variable length - doesn't allow null bytes
2. opaque data, length 2 bytes - fixes a length based on the longest object there
3. strings, length 2 bytes - status quo, but has all the drawbacks of 1 & 2
4. vlen arrays of uint8 - will come back as numpy arrays of ints rather than bytes objects
5. vlen arrays of opaque data, length 1 byte - technically capable, but it feels pretty awkward. Even h5py would need some tricky conversion code to retrieve these as bytes.
6. or throw an error and try to point the user to how they can use other options

I think I favour options 1 or 6 from that list. 1 because the proposal above already has a lot of places where we convert between Python bytes & HDF5 strings, and it's probably not a big change for existing code - fixed length to variable length strings. Or 6 because HDF5 is not really designed for storing arbitrary blobs of data, so it feels like asking 'what do you mean?'

**Comment by takluyver** [comment]
I'm also planning a `dset.asstr()` accessor for reading HDF5 string datasets as Python str objects rather than bytes. It would take similar options to `bytes.decode()`:

```python
dset[0]  # bytes (vlen) or numpy string array (fixed size)
dset.asstr()[0]  # str, decoded with ASCII or UTF-8 following the dataset metadata
dset.asstr('latin1')[0]  # str, decoded with the specified encoding
dset.asstr(errors='replace')[0]  # Specify how to handle decoding errors
```

Questions:

1. Naming: `asstr` parallels the existing `astype`. Or we could call it `decode` or `decoded` as a closer parallel to `bytes.decode`.
2. Should it also allow writing? I think not: we're already planning to allow automatic encoding of strings with the encoding specified by the datatype (ASCII or UTF-8), and if you really need to store text encoded in some other way, you can just encode it first and give h5py bytes. Using another encoding is kind of abusing HDF5, so I don't want to make it too easy.
3. Should it allow specifying a different encoding on reading? My argument in Q2 suggests not, but I quite like the parallel with `.decode()`, and facilitating the creation of bad files feels worse than acknowledging that you might have to read them.
4. What should the default error handling be? I think `surrogateescape`, as @chrisjbillington [suggested](https://github.com/h5py/h5py/issues/1338#issuecomment-563369866), because it allows lossless roundtripping even if you don't reliably know the encoding.

**Comment by kif** [comment]
Hi Thomas,
I would prefer the `decode` for 1. For 2 it would not allow writing as encoding should be done on the str object. For 3. allowing to specify an "alternative" encoding is a good idea. For 4. if this is the way Python does things, it looks reasonable.

**Comment by takluyver** [comment]
For 1: My hesitation with `.decode()` is that calling the method wouldn't actually do the decoding. Like `.astype()`, it would make an accessor object which you index to read data. But maybe that distinction doesn't matter.

For 4: Python defaults to *strict* error-handling for functions like `bytes.decode()` - i.e. if the bytes given aren't valid for that encoding, raise `UnicodeDecodeError`. `surrogateescape` is used by functions that return filesystem paths, like `os.getcwd()` or `os.listdir()` (on Unix, anyway).

The argument against h5py defaulting to strict is that this API can effectively decode many small pieces of data together, so an error in one would stop you reading all the others. And we're pretty sure that the encoding metadata stored in HDF5 is not always accurate. The case for it is obviously following Python's precedent - which is more compelling if we also call the method `.decode()`.

I think strict and surrogateescape are the only sensible choices for the default. All the other [error handlers](https://docs.python.org/3/library/codecs.html#error-handlers) would silently break a bytes -> str -> bytes roundtrip.

**Comment by takluyver** [comment]
I've just gone through the list of specified details for datasets above, and I think we're nearly there. These are the places I found where master differs from the plan:

- [ ] Writing to fixed length string datasets silently truncates longer data rather than erroring.
- [ ] Writing to UTF-8 fixed length string datasets doesn't accept non-ascii characters in strings
- [ ] Creating a dataset from a list of str is OK, but a list of list of str fails
- [ ] Similarly, creating a dataset from a list of bytes uses a vlen string datatype, but a list of list of bytes becomes fixed length.

**Comment by takluyver** [comment]
I believe this is all in place in master now.
