### ISSUE TITLE
Document writing release notes for contributors

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#1341]
It would be good to get PR authors to write release notes alongside their changes. However, if everyone edits the same file, you get lots of merge conflicts.

Tools like [towncrier](https://github.com/hawkowl/towncrier) and [reno](https://docs.openstack.org/reno/latest/) exist to handle this. We should:

- [x] pick one
- [x] set the project up to use it
- [ ] mention what PR authors need to do in the [contribution guide](http://docs.h5py.org/en/stable/contributing.html#how-to-get-your-code-into-h5py)
- [ ] add a PR template reminding contributors about it?

**Comment by takluyver** [comment]
It appears this is a feature of rever, which we're already using, so we just need to document that people should do this:

https://regro.github.io/rever-docs/news.html

**Comment by scopatz** [comment]
Yep, we just need to document it.  Any suggestions for that?

**Comment by scopatz** [comment]
I guess the contribution guide and release template?

**Comment by takluyver** [comment]
Yup, contribution guide & PR template.

**Comment by takluyver** [comment]
This is probably obvious, but is there a neat way to assemble the release notes as a separate step before doing a release? Is this `rever changelog`? We'll probably want to do some manual adjustment of the gathered release notes before they go into a release.
