### ISSUE TITLE
Set up automatic building of low-level API docs

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#1343]
The docs at http://api.h5py.org/ are outdated, and not accessible over HTTPS. They're currently hosted where Andrew manually set them up some time ago. We should remedy this.

Our usual go-to service for hosting docs is readthedocs.org, but it's probably not a good answer here. The API docs need h5py to be importable, which which means getting libhdf5 installed with development headers and compiling h5py. RTD is not really designed for this kind of thing, as far as I know - but if someone 

- [x] Pick somewhere to host these docs (github pages?)
- [x] Pick a CI service to build them (Azure? See #1324)
- [x] Set up building and publishing the docs automatically when h5py master changes
- [x] Get the DNS updated to point to the new location
- [ ] ~~Stretch goal: automatically generate a separate URL for each tag, 'stable' referencing the latest tag, and master (like RTD does)~~

**Comment by scopatz** [comment]
My recomendation for this is doctr (https://drdoctr.github.io/), which lets you build and manage github pages on travis.  It is precisely for the extension module use case.

**Comment by takluyver** [comment]
Yes! Someone mentioned that during the code camp, but I had forgotten the name.

**Comment by takluyver** [comment]
Before we ask Andrew to change the DNS for this, a question. I've set up doctr to publish versioned docs, e.g. `/master/h5p.html` or `/v3.0.0/h5p.html`. This would break existing links to the unversioned URLs (`http://api.h5py.org/h5p.html`).

Do we:

1. Stick to unversioned docs built from master, and use Sphinx versionadded/versionchanged directives to document changes between versions.
2. "Redirect" the unversioned URLs to `/master/x` or `/stable/x`. We can't do proper HTTP redirects on Github pages (as far as I know), so this would be some combination of html meta-refresh, rel=canonical links and Javascript.

Versioned docs feel like a step forwards. But on the other hand, I suspect most people use the default docs they land on anyway, and the versionadded/versionchanged directives are still useful, so maybe it's not worth the trouble. Versioned docs can also be problematic if an old version ranks highly in search results, and people don't realise it's outdated.

I think I've now talked myself into preferring option 1. But I'd like to get other opinions before I change it.

**Comment by takluyver** [comment]
Ping @tacaswell @aragilar @scopatz - opinions on this? I'm leaning towards sticking with a single, unversioned set of docs built from master, to avoid breaking URLs.

**Comment by aragilar** [comment]
I'm happy to go with the single version docs, given it's simpler, and to avoid having to set up (and update and maintain) redirects.

**Comment by takluyver** [comment]
OK, I've opened PR #1413 to configure it for unversioned URLs.

**Comment by takluyver** [comment]
Andrew updated the DNS for us, so the docs are now working. And Github has automatically enabled HTTPS: https://api.h5py.org/
