### ISSUE TITLE
Local imports in tests

### ISSUE THREAD

**Issue by kif** [h5py/h5py#1344]
Hi,

While hacking in PR#1332 at the Cython level , I had to run the tests in gdb which was a bit tricky. I found surprising that tests import h5py everywhere instead of importing locally the library. I have seen many interference resulting from those absolute imports (with numpy, ...) and believe the development process from h5py and its debugging could be made more reliable by using relative imports as requested by Python3.

Any comments on this ?

Cheers,

Jerome

**Comment by takluyver** [comment]
I'm puzzled what interference you see. As far as I know, when modules within a package import their parent package, it doesn't make any difference whether they do it absolutely or remotely. How were you running them?

**Comment by kif** [comment]
On Tue, 24 Sep 2019 02:11:58 -0700
Thomas Kluyver <notifications@github.com> wrote:

> I'm puzzled what interference you see. As far as I know, when modules within a package import their parent package, it doesn't make any difference whether they do it absolutely or remotely. How were you running them?

That's in theory.

In practice, pytest is another process with potentially a different
interpreter (shouldn't), a different environment and we found out it
was grabbing the python2.7 version of the lib.

**Comment by takluyver** [comment]
How were you launching the tests?

If they're being imported as part of the package, then the parent package should already be loaded, so `import h5py` just gets the reference already in `sys.modules`. If they're being imported without the parent package, then relative imports aren't allowed anyway.

**Comment by kif** [comment]
On Tue, 24 Sep 2019 02:40:35 -0700
Thomas Kluyver <notifications@github.com> wrote:

> How were you launching the tests?

python setup.py test is the only way I managed to get the tests running.

Unfortunately this forks another process for pytest  in
h5py/test/__init__.py which makes the usage of gdb more complicated.

**Comment by takluyver** [comment]
I install h5py into an environment and then run `pytest --pyargs h5py`. I believe that the idiomatic way to run the tests is through tox, e.g. `tox -e py37-test-deps`, and it will set up a test environment for you (though this seems to build h5py fresh each time, so it's slower if you want to make changes and rerun tests).

**Comment by takluyver** [comment]
Closing as this is old now, and I still don't think the imports can be a problem.
