### ISSUE TITLE
Update links to docs to use https

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#1346]
The docs are now available over HTTPS: https://docs.h5py.org/en/stable/

We should update links to point to HTTPS where that's easy. E.g. in the  README, but I'm sure there are other places.

**Comment by Silas-Asamoah** [comment]
Okay I would like to work on this

**Comment by takluyver** [comment]
I see one more reference in `docs_api/index.rst` to be updated before we close this.

**Comment by Silas-Asamoah** [comment]
Yes please I will check it ASAP

**Comment by Silas-Asamoah** [comment]
I just sent a pull request effecting the change mentioned

**Comment by takluyver** [comment]
All done now, thanks @Silas-Asamoah !

**Comment by Silas-Asamoah** [comment]
Glad I could help!
