### ISSUE TITLE
Azure not uploading to codecov

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#1358]
Not high priority yet, but if we're going to drop some jobs on Travis & Appveyor in favour of Azure, we should make sure it's uploading coverage information properly. Currently it gives:

```
Error: Missing repository upload token
```

The token itself probably can't be secret if we want it to work for pull requests, but that shouldn't be a big problem:
https://community.codecov.io/t/security-issues-regarding-upload-token/429/6

**Comment by tacaswell** [comment]
It looks like codecov added support for this 3 days ago: https://blog.codecov.io/2019/01/24/new-in-codecov-4-4-3/ (at least for linux)

**Comment by takluyver** [comment]
I think I've got this working for the Linux builds in #1356. The Windows & Mac builds say `Error: No coverage report found`.
