### ISSUE TITLE
Create a dataset if it does not already exist

### ISSUE THREAD

**Issue by nbro** [h5py/h5py#1359]
I am trying to create a dataset if it does not exist with the following statement

```
a=file.get("ds", file.create_dataset("ds", shape=(0, 1), maxshape=(None, 1), data=None,chunks=True))
```

But I am getting the error `RuntimeError: Unable to create link (name already exists)` when the dataset `ds` already exists, which probably means that `file.create_dataset("ds", shape=(0, 1), maxshape=(None, 1), data=None,chunks=True)` is called when the dataset already exists, even though it should not be called. A workaround would be to 

```
a=file.get("ds")
if a is None:
    a=file.create_dataset("ds", shape=(0, 1), maxshape=(None, 1), data=None,chunks=True)
```

However, it seems like `file.get` should handle this situation.

Here are my specifications

* Operating System: Mac OS Mojave (10.14.6)
 * Python version: 2.7.15+
 * Where Python was acquired: system Python
 * h5py version: 2.7.1 (`h5py.__version__`)
 * hdf5 version: 1.10.0
 * The full traceback/stack trace shown (if it appears)

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/group.py", line 109, in create_dataset
    self[name] = dset
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/group.py", line 277, in __setitem__
    h5o.link(obj.id, self.id, name, lcpl=lcpl, lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/build/h5py-qzs83i/h5py-2.7.1/h5py/_objects.c:2847)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/build/h5py-qzs83i/h5py-2.7.1/h5py/_objects.c:2805)
  File "h5py/h5o.pyx", line 202, in h5py.h5o.link (/build/h5py-qzs83i/h5py-2.7.1/h5py/h5o.c:3899)
RuntimeError: Unable to create link (name already exists)
```

**Comment by takluyver** [comment]
It sounds like [require_dataset()](http://docs.h5py.org/en/stable/high/group.html#Group.require_dataset) is what you want.

The `f.get("ds", f.create_dataset(...))` call can't work, because Python always evaluates arguments eagerly - it will call `f.create_dataset()` before it tries to call `f.get()`. You could do something similar using `or`, which doesn't evaluate the second term if the first is true:

```python
ds = f.get('ds') or f.create_dataset(...)
```

But require_dataset() is more convenient.

**Comment by nbro** [comment]
@takluyver Can you provide a concrete example equivalent to mine above but that uses `require_dataset`?

**Comment by takluyver** [comment]
It takes the same arguments as `create_dataset()`, plus the `exact` option described in the docs.

**Comment by nbro** [comment]
@takluyver Ok, so can you provide a concrete example?

**Comment by takluyver** [comment]
My previous comment was meant to be a polite way of saying: please work it out yourself.

**Comment by nbro** [comment]
@takluyver And my previous comment was meant to be a way of encouraging you to write a reference answer, so that, in the future, people with the same problem can just look it up.

**Comment by AbdulKaderJaleel** [comment]
@takluyver you should have taken his advice. 2 years down the line, I'm here looking for the same xD

**Comment by AbdulKaderJaleel** [comment]
here is the sample code:

with h5py.File('filtered.h5', 'a') as f:
    # Create a group called data
        print(f.keys())
        if f.keys()== None:
            g = f.create_group('data')
            g.create_dataset(filename, data=norm_image)
        else:
            g = f.require_group('data')
            g.create_dataset(filename, data=norm_image)
