### ISSUE TITLE
Is there an easy way of knowing whether an HDF5 file is opened or closed?

### ISSUE THREAD

**Issue by nbro** [h5py/h5py#1363]
Is there a way of knowing whether an HDF5 file is opened or closed?

Here are my specifications

* Operating System: Mac OS Mojave (10.14.6)
 * Python version: 2.7.15+
 * Where Python was acquired: system Python
 * h5py version: 2.7.1 (`h5py.__version__`)
 * hdf5 version: 1.10.0
 * The full traceback/stack trace shown (if it appears)

**Comment by takluyver** [comment]
This is not well documented, but yes:

```python
f = h5py.File(...)
f.close()

if f:
    print("File is open")
else:
    print("File is closed")

if f.id.valid:
    print("File is open")
else:
    print("File is closed")
```

I'll leave this issue open to improve the docs.

**Comment by cydanil** [comment]
I'd like to work on this.
To me, it seems like there are two good place to put this in: either within the [Quickstart](https://docs.h5py.org/en/latest/quick.html), or the [File Object](https://docs.h5py.org/en/latest/high/file.html).

Would you have a recommendations?

**Comment by kif** [comment]
I believe in the FileObject it would be better.
Note this "boolean" behavior" is the same for groups and datasets.

**Comment by takluyver** [comment]
I agree - this is probably too minor for the quickstart page.

I'd be tempted to add `__bool__()` to the reference docs for the different types, and clarify there that that's called when you do `if f:`. That's discoverable for people who know about `__bool__`, and I can't think of any way that will make it discoverable for people who don't - the likely search terms are too generic and too varied.
