### ISSUE TITLE
Does h5py.File keep a reference to the data structures used to create the dataset until it is closed?

### ISSUE THREAD

**Issue by nbro** [h5py/h5py#1365]
I am attempting to read a large file (~900MB, so maybe not very large) into chunks, with a function like described here https://stackoverflow.com/a/8991553/3924118.

```
def grouper(n, iterable):
    it = iter(iterable)
    while True:
       chunk = tuple(itertools.islice(it, n))
       if not chunk:
           return
       yield chunk
```

This function allows me to iterate the file `n` lines at once. So, in my code, I have a for loop like this

```
file = h5py.File("path_to_file", "w")

n = 1000

with open(file_path) as f:
    generator = grouper(n, f.readlines())
    for iterable in generator:

        # Convert long strings representing long numpy arrays to actual numpy arrays, etc, 
        # so here the memory increase

        df = generate_data_frame(iterable) # Generates a data frame from n lines

        new_df = process_data_frame(df) 
        

        # Here I create a dataset for each column of df (about 5 columns),
        # I only create the dataset if it does not already exist.
        # If it already exists, I resize it to accommodate the data in the df
        write_data_frame_to_hdf5_file(new_df)

file.close()
```

As you can see, I only close `file` when I have processed all the big file with path `file_path`. I've specifically developed the code above so that to limit the memory usage, given that, in theory, I will be loading only `n` lines of the file at once. However, in practice, when I execute my script that is based on similar logic to the snippet above, the memory keeps increasing, until the script is killed. Given that I still have this memory problem, I thought that maybe the resources are not being freed after each iteration of `for iterable in generator`, so I thought that, until I close the `h5py.File`, all data frames created during each iteration are kept in memory, because maybe the `h5py.File` keeps a reference to them? So, does `h5py.File` keep a reference to the data structures used to create the dataset until it is closed, thus preventing memory from being freed?

The function `write_data_frame_to_hdf5_file` looks like

        
```
for col in df.columns.values:
    shape = df[col].iloc[0].shape
    dataset_name = "set/a/name"
    dataset = file.get(dataset_name)
    if dataset is None:
        dataset = file.create_dataset(dataset_name, shape=(0,) + shape, maxshape=(None,) + shape, dtype=np.float, data=None, chunks=True)
    dataset.resize(dataset.len() + len(df), axis=0)
    dataset[-len(df):] = np.stack(df[col].values)
```

Here are my specifications

* Operating System: Ubuntu 18.04.03 VM [which is a guest OS in the host Mac OS Mojave (10.14.6)]
 * Python version: 2.7.15+ (Ubuntu)
 * Where Python was acquired: system Python (Ubuntu)
 * h5py version: 2.7.1 (`h5py.__version__`) (Ubuntu)
 * hdf5 version: 1.10.0 (Ubuntu)

**Comment by takluyver** [comment]
As far as I know, it shouldn't. A few things you could try:

- Check the chunk shape it has chosen (`dataset.chunks`) - it's possible the automatic chunk shape doesn't match how you're writing, so it has to modify many chunks for each write.
- Try with newer versions of hdf5 & h5py, e.g. in an [Anaconda](https://www.anaconda.com/distribution/) environment. The versions in Ubuntu 18.04 are quite old now, and there may be bugs that have since been fixed.
- Close and reopen the file between each write. This will probably be slower, but if it fixes the memory issue, then it's a pretty good sign that it is a problem to do with h5py or hdf5.

**Comment by nbro** [comment]
@takluyver Regarding the first point, `dataset.chunks` is `dataset.chunks = (128, 8, 10, 1)` in my case and `np.stack(df[col].values).shape = (1000, 64, 80, 3)`. Could this be the problem?

Note that I use `chunks=True` when creating the dataset, even though I am not sure what this parameter actually does.  What exactly does `dataset.chunks` do?

**Comment by takluyver** [comment]
Chunks defines the shape of blocks of data which will be written (or read) together. So with your first dataset, each block of `(128, 8, 10, 1)` will be written together in HDF5. This might not be optimal, but it probably isn't a big problem.

If you use `chunks=True`, h5py tries to guess a chunk shape automatically. You can also pass in a chunk shape explicitly as a tuple. For more information,  see http://docs.h5py.org/en/stable/high/dataset.html#chunked-storage

**Comment by nbro** [comment]
@takluyver I've tried to flush the file at the end of `write_data_frame_to_hdf5_file`, but this does not free any memory, according to 

```
import psutil
process = psutil.Process(os.getpid())
print "Memory used (GB) =", process.memory_info()[0] / 1000000000.0
```

The memory keeps increasing at every successive call to `write_data_frame_to_hdf5_file`.

**Comment by nbro** [comment]
The memory issues I am facing are probably not due to `h5py`. In fact, I've removed all code related to it, so I've left only the code that reads the files from memory chunk by chunk and that processes those chunks, but my script is still killed (`Process finished with exit code 137 (interrupted by signal 9: SIGKILL)`).

**Comment by vasole** [comment]
As far as I know the readlines method does not return an iterator. In fact you could just close your original input file after having stored all your input into a variable.

Something on the lines of the (untested) code below should help.

```
with open(file_path) as f:
    lines = f.readlines()
nlines = len(lines)
n = 1000
start = 0
while start < nlines:
    step = min(start + n, nlines)
    chunk = lines(start:start+step)
    ... # do whatever
    start += step
```

**Comment by vasole** [comment]
Sorry, I had to edit the code.

**Comment by takluyver** [comment]
OK, I'm going to close this as it sounds like it's not an issue with h5py. Feel free to keep using the comments to work out what is going on, and we can always reopen it if it turns out there is a problem with h5py.

**Comment by nbro** [comment]
@vasole I don't get what you want to say with your comment. If you load all the contents of a file into a variable, then you will need RAM to allocate such a variable.

**Comment by nbro** [comment]
I found the problem. I was using `zip` rather than `itertools.izip`, which lazily evaluates its parameters. In Python 2.7, `zip` eagerly evaluates its contents. More specifically, in my case, I was using something like `zip(*generators)`, where `generators` is a list of generators that can be used to iterate over a file. In this case,`zip(*generators)` needs to evaluate all the contents of the file to return a list of tuples.

**Comment by vasole** [comment]
My comment was to tell you that you had already allocated all the file in memory in your f.readlines() call and if by chance you where having troubles with your fancy way of taking chunks of data (as you indeed had) you might be adding n times the size of the file instead of just one as in the solution I proposed.

Thanks for posting your solution.
