### ISSUE TITLE
Clean up cimport of numpy

### ISSUE THREAD

**Issue by kif** [h5py/h5py#1367]
Numpy exposes (for already some times now) a cython C-API based on PXD files which can be c-imported in the cython code.
The numpy.pxd file present in h5py is a "duplicate" but some definition differs. It would be useful to reduce the maintenance burden to rely directly on the one provided by numpy

**Comment by takluyver** [comment]
Thanks @kif :-)

**Comment by kif** [comment]
So I started to hack into it. There is no PR but I could open it soon, as usual, depending on the local BW available.
I found PyArray_Scalar was defined and exposed in h5py but commented out in the cython/numpy export with the given explantation:
```
    # Functions taking dtype and returning object/ndarray are disabled
    # for now as they steal dtype references. I'm conservative and disable
    # more than is probably needed until it can be checked further.
```
Removing it breaks h5py :(

**Comment by takluyver** [comment]
That's strange, because `PyArray_Scalar` doesn't seem to be used anywhere in h5py. Can you identify how h5py is broken without it?

If we do need it, we can obviously open an issue on numpy to ask that it be added to the Cython interface. But we should check first whether we do we need it.

**Comment by kif** [comment]
On Wed, 02 Oct 2019 07:26:38 -0700
Thomas Kluyver <notifications@github.com> wrote:

> That's strange, because `PyArray_Scalar` doesn't seem to be used anywhere in h5py. Can you identify how h5py is broken without it?

Maybe it is smth else ...
 
> If we do need it, we can obviously open an issue on numpy to ask that it be added to the Cython interface. But we should check first whether we do we need it.

I found some definitions in the numpy.pxd provided by cython differs
from the one in h5py: the import_array function at least which returns
an int in cython and nothing in h5py.

It shouldn't be an issue but this change causes many problems. Still investigating

**Comment by kif** [comment]
I found something else  ...
The definition of ndarray and dtypes differ from h5py and cython when it comes to the name of the cdef-attributes. 
For example h5py defines `dtype.elsize` while cython defines `dtype.itemsize`, the same for ndarray.nd or ndarray.ndim and ndarray.shape vs ndarray.dimensions. 

This brings again quite a bit of changes... The cython code didn't change neither in the 7 last years. Maybe it is the time to synchronize with them?

**Comment by takluyver** [comment]
+1 to making those names match up. Is it practical to do it one by one as a series of smaller pull requests (e.g. change `dt.elsize` to `dt.itemsize` in one PR)? Then hopefully when they're all done,  we might be able to get rid of our `numpy.pxd` file.

**Comment by kif** [comment]
OK I'll revert the last changes I have done and submit a PR.

**Comment by takluyver** [comment]
@kif: You removed `numpy.pxd` in #1406 - can this issue be closed now, or is there still more you want to do?

**Comment by kif** [comment]
I thought it was closed automatically ...
