### ISSUE TITLE
Drop some test jobs on Travis & Appveyor

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#1372]
We're getting to a point with Azure where it can handle a lot of our testing. We've already reached the point where it completes quicker than Travis or Appveyor: a typical run now takes ~12 minutes on Azure, and 20-25 minutes on both Travis and Appveyor.

A lot of the testing on the other services is (or should be) redundant. So what can we drop.

Things I'm aware of that Azure does not (yet) cover:

- Publishing low-level API docs: doctr appears to be closely integrated with Travis CI
- ppc64le tests running on Travis
- Windows 32-bit Python tests on Appveyor
- Windows tests with HDF5 1.8 on Appveyor

**Comment by aragilar** [comment]
Currently we lack CI on 32-bit intel systems for linux (there's known bugs on it around floating point types - #1337 and #1163). It's probably also worth looking out for arm CIs.

The things that need to stay on travis from what I can see are doctr and ppc64le, and azure doesn't seem to have 32-bit support. The MPI stuff can go.

**Comment by aragilar** [comment]
The other thing azure doesn't allow is easy "allow_failure" (https://github.com/microsoft/azure-pipelines-tasks/issues/9302), which we'd want for nightlies (of python and HDF5). We could hack something on azure, but it's probably fine to leave the "allow_failure" cases on travis for now.

**Comment by takluyver** [comment]
- 32-bit Intel CI: manylinux uses the `linux32` command to pretend that an x86_64 build environment is i686 ([Docker file](https://github.com/pypa/manylinux/blob/manylinux1/docker/Dockerfile-i686)). Then you can easily install and run 32-bit binaries, which I guess is mostly what we want to test. This should work on various CI services.
- ARM CI: In [another context](https://github.com/pypa/manylinux/issues/84), someone mentioned that [Shippable supports ARM builds](http://docs.shippable.com/platform/tutorial/workflow/run-ci-builds-on-arm/#running-jobs-on-arm-machines). I've never used this myself, but it appears to have a free tier for open source projects.

**Comment by takluyver** [comment]
I think we're OK on this for now - it's usually some of the Azure builds which are the last to finish.
