### ISSUE TITLE
Caching seems to have no effect on read times

### ISSUE THREAD

**Issue by ivirshup** [h5py/h5py#1391]
I can't seem to get any changes in performance for slicing into a 1d dataset axis by modifying caching arguments, even though reads are contiguous. In contrast, reading chunks exactly gives much better performance. Here's an example:

```python
# Setup
import h5py
import numpy as np

x = np.random.randint(0, 1000, int(1e7))
indices = np.sort(np.random.choice(int(1e7), int(1e4), replace=False))

with h5py.File("test.h5", "w") as f:
    f.create_dataset("x", data=x, chunks=True)
```

Now I'll try and read in the array in way that should mostly be hitting the cache. I'll show you the general schema of the benchmark, followed by just how the file was opened and timings for brevity

```python
f = h5py.File("test.h5", "r")
dset = f["x"]

# In it's own cell:
%%timeit
for i in range(len(indices) - 1):
    s = slice(indices[i], indices[i+1])
    dset[s]
# Timing results:
# 1.21 s ± 6.71 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

f.close()
```

With a large cache:

```python
f = h5py.File("test.h5", "r", rdcc_nbytes=100 * (1024 ** 2), rdcc_nslots=50000)
# Timing results:
# 1.17 s ± 25.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

With no cache:

```python
f = h5py.File("test.h5", "r", rdcc_nbytes=0)
# Timing results
# 1.14 s ± 12 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Setting `rdcc_w0` to something, while using a large cache:

```python
f = h5py.File("test.h5", "r", rdcc_nbytes=100 * (1024 ** 2), rdcc_nslots=50000, rdcc_w0=.5)
# Timing results
# 1.16 s ± 37.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

These timings all fluctuate a bit, but are all pretty similar. By contrast, I'll just read in entire chunks:

```python
%%timeit
cs = dset.chunks[0]
ts = dset.shape[0]
slice_gen = (slice(i*cs, min((i+1)*cs, ts)) for i in range(ts // cs + 1))
for s in slice_gen:
    dset[s]
# Timing results:
# 136 ms ± 955 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

Any idea what's up with this? This was [mentioned before](https://groups.google.com/forum/#!searchin/h5py/cache|sort:date/h5py/nd9ag52_AVA/7wdsbZDuAgAJ) on the mailing list, but there didn't seem to be much resolution.

## Version info

```
h5py    2.10.0
HDF5    1.10.4
Python  3.7.4 (default, Sep  7 2019, 18:27:02) 
[Clang 10.0.1 (clang-1001.0.46.4)]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.17.2
```

**Comment by takluyver** [comment]
I've played around with this a bit. I see a speed difference with the cache only when I use compression on the data.

I guess that when you don't use compression, the chunk is in the OS disk cache anyway, so whether HDF5 caches it again makes little difference. When you do use compression, the OS cache only stores the compressed data, so HDF5's caching avoids having to do the decompression repeatedly.

**Comment by ivirshup** [comment]
Any chance you know a command for clearing the OS's disk cache so we can test if that's the case?

**Comment by takluyver** [comment]
I do, though I don't know how it behaves with processes that are still running - I've used it to test cold-starting programs.

```
sync ; echo 3 | sudo tee /proc/sys/vm/drop_caches
```

From [this OpenOffice wiki page](https://wiki.openoffice.org/wiki/Cold-start-simulator).

**Comment by ivirshup** [comment]
Gave resetting the disk cache a shot. I think you were right about the OS cache masking some of the effects of the hdf5 cache. Here's a [gist](https://gist.github.com/ivirshup/247ea6fabd3935e12d41551b7252a2f8) with the full session I ran to time this, which I'll post a couple excerpts of. This used the same `test.h5` file I generated before.

The main result I see is that clearing the disk cache has an effect on total read time ([example](https://gist.github.com/ivirshup/247ea6fabd3935e12d41551b7252a2f8#file-ipython_session-py-L32-L57)). This doesn't seem to have near as much effect as reading more times, even when those reads should hit the cache. I guess this is the real thing I'm wondering about. Shouldn't cache hits be fast?

Just to make sure I wasn't expecting to much, I've implemented a simple (definitely non-optimal) cache in python to compare with. Even with a large hdf5 cache, the python cache is still faster.

<details>
<summary> Setup and cache definition </summary>

```python
import zict
import numpy as np
import h5py

def get_dset_chunk(dset, chunk_size, chunk_num):
    start = chunk_size * chunk_num
    end = start + chunk_size
    return dset[start:end]

def slice_len(s, total_len):
    return len(range(*s.indices(total_len)))

class Cache(object):
    def __init__(self, dset, chunk_size, cache_size):
        self.dset = dset
        self.chunk_size = chunk_size
        self.cache = zict.LRU(cache_size, {})
    
    def get_slice(self, s: slice):
        # We're going to assume our reads span at most two chunks for simplicity
        start_chunk, start_rem = np.divmod(s.start, self.chunk_size)
        end_chunk, end_rem = np.divmod(s.stop, self.chunk_size)
        if start_chunk == end_chunk: # Fast path
            if start_chunk in self.cache:
                chunk = self.cache[start_chunk]
            else:
                chunk = get_dset_chunk(self.dset, self.chunk_size, start_chunk)
                self.cache[start_chunk] = chunk
            return chunk[start_rem:end_rem]
        chunk1 = self.cache.get(start_chunk, None)
        chunk2 = self.cache.get(end_chunk, None)
        if chunk1 is None:
            chunk1 = get_dset_chunk(self.dset, self.chunk_size, start_chunk)
            self.cache[start_chunk] = chunk1
        if chunk2 is None:
            chunk2 = get_dset_chunk(self.dset, self.chunk_size, end_chunk)
            self.cache[end_chunk] = chunk2
        chunk1_v = chunk1[start_rem:]
        chunk2_v = chunk2[:end_rem]
        return np.concatenate([chunk1_v, chunk2_v])
```

</details>

In this case I used smaller reads since I've only implemented the case where at most two contiguous chunks are read from at once.

<details>
<summary> Setting up variables, test for correctness </summary>

```python
f = h5py.File("test.h5", "r", rdcc_nbytes=1024 ** 3)  # Using a large cache anyways
dset = f["x"]

indices = np.sort(np.random.choice(int(1e7), int(2e4), replace=False))
assert np.diff(indices).max() < dset.chunks[0], "Indices may read more than 2 chunks at a time"

cache = Cache(dset, dset.chunks[0], 5)
```

```python
# Test for correctness
tmp_cache = Cache(dset, dset.chunks[0], 5)
for i in range(len(indices) - 1):
    s = slice(indices[i], indices[i+1])
    a1 = tmp_cache.get_slice(s)
    a2 = dset[s]
    assert np.all(a1 == a2)
```

</details>

Timings:

```python
%%timeit
for i in range(len(indices) - 1):
    s = slice(indices[i], indices[i+1])
    cache.get_slice(s)
# 676 ms ± 20.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

%%timeit
for i in range(len(indices) - 1):
    s = slice(indices[i], indices[i+1])
    dset[s]
# 2.22 s ± 23.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

From my reading of the caching docs, my python cache should be fairly similar to the hdf5 one. Why would mine be faster?

**Comment by takluyver** [comment]
I have a vague impression that h5py incurs significant overhead on each call into HDF5. I've never got round to digging in to examine this, but your results appear to fit with it.

If so, I don't know if this is something h5py can avoid by doing something differently, or if it's an inherent problem with HDF5 itself.

**Comment by ivirshup** [comment]
I investigated that a bit, and it definitely seems true. I've gone ahead and drafted a faster alternative, through it could probably benefit from some cython-ization (which I haven't used before) and testing against the current code. I'm aiming to open a PR with this, so I've included my current thoughts on that and the draft implementation below (sorry about the length!).

This doesn't exactly address my initial need though. I would like it if there was a way to just iterate over the chunks of a dataset as quickly as possible. Do you think that could be in scope for this library?

<details>
<summary> setup for benchmarks </summary>

```python
import numpy as np
import h5py

x = np.random.randint(0, 1000, int(1e7)) 
indices = np.sort(np.random.choice(int(1e7), int(1e4), replace=False)) 

with h5py.File("test_w_inds.h5", "w") as f:
    f.create_dataset("x", data=x, chunks=True)
    f.create_dataset("indices", data=indices)

f = h5py.File("test_w_inds.h5", "r")
dset = f["x"]
```

</details>

## Current code

I used snakeviz to take a look at this code:

```python
%%snakeviz
for i in range(len(indices) - 1):
    s = slice(indices[i], indices[i+1])
    dset[s]
```

It shows:

* %20 of the runtime is `dataset.shape` (which is called many times, though I don't think it would be possible for another thread to modify the shape due to `with_phil`?)
* %20 of the runtime is spent handling the hyperslab in python
* %15 of the runtime is spent in figuring out if there's a zero in `dataset.shape`

This code takes about 2.3 seconds to run with the input data I used

## HDF5.jl

Just to get an idea of what the time could be, I read the same data using hdf5.jl to minimize overhead:

```julia
using HDF5
using BenchmarkTools

f = h5open("test_w_inds.h5")
x = f["x"]
indices = f["indices"][:]

function read_indices(dset, indices)
    for i in 1:(length(indices) - 1)
        dset[indices[i]:indices[i+1]]
    end
end

read_indices(x, indices)
@btime read_indices($x, $indices)
```

This takes about .33 seconds. Iterating through the chunks takes about .084 seconds (about a 4x ratio), though there are about 20x more operations reading by indices (chunk size is ~10000). This suggests either the OS cache or the hdf5 cache is being used very effectively here.

<details>
<summary> Reading by chunks in julia </summary>


```julia
function read_by_chunks(dset)
    chunk_size = get_chunk(dset)[1]
    total = length(dset)
    n_chunks = div(total, chunk_size)
    start = 1
    stop = chunk_size
    for i in 1:n_chunks
        dset[start:stop]::Vector{Int64}
        start += chunk_size
        stop = min(stop + chunk_size, total)
    end
    remaining = stop - start
    if remaining != chunk_size
        dset[start:stop]::Vector{Int64}
    end
end
```

</details>

## Revised h5py

Taking a look at the code for hdf5.jl, I noticed it was a much shorter code path to get to hdf5 library calls. I've translated this code into python, and took some timings.

### Code

```python
def hyperslab(dset: h5py.Dataset, indices: "List[Slice, Int]"):
    dset_space = dset.id.get_space()
    dims = dset_space.get_simple_extent_dims()  # Should do a bounds check, but could also avoid this call
    ndims = len(dims)
    dsel_id = dset_space.copy()
    
    dsel_start = [0 for i in range(ndims)]
    dsel_stride = dsel_start.copy() # [0 for i in range(ndims)]
    dsel_count = dsel_start.copy()  # [0 for i in range(ndims)]
    
    for k, index in enumerate(indices):
        if isinstance(index, (int, np.integer)):
            dsel_start[k] = index
            dsel_stride[k] = 1
            dsel_count[k] = 1
        elif isinstance(index, slice):
            start, stop, step = index.indices(dims[k])
            count = (stop - start) // step
            dsel_start[k] = start
            dsel_stride[k] = step
            dsel_count[k] = count
        else:
            raise ValueError()
            
    dsel_start, dsel_stride, dsel_count = tuple(dsel_start), tuple(dsel_stride), tuple(dsel_count)
    dsel_id.select_hyperslab(dsel_start, dsel_count, dsel_stride)
    dset_space.close()
    
    return dsel_id, dsel_count

def getindex(dset, indices):
    dsel_id, mem_shape = hyperslab(dset, indices)
    msel_id = h5py.h5s.create_simple(mem_shape)
    out = np.empty(mem_shape, dset.dtype)

    dset.id.read(msel_id, dsel_id, out)

    msel_id.close()
    dsel_id.close()

    return out
```

### Benchmarks

Using the following snippet:

```python
for i in range(len(indices) - 1):
    idx = (slice(indices[i], indices[i+1]),)
    getindex(dset, idx)
```

This takes about .75 seconds to read all indices. If the julia code is optimal, this would be about a quarter of the original overhead. If I'm reading the snakeviz output right, at least 90% of this is hdf5 or cython code.

Using line profiler, there are some hints as to where performance could be improved:

<details>
<summary> Wrapper function for using line profiler </summary>

```python
def readall():
    for i in range(len(indices) - 1):
        idx = (slice(indices[i], indices[i+1]),)
        getindex(dset, idx)
```

</details> 

```python
%lprun -f hyperslab readall()
```

<details>
<summary> hyperslab line-by-line </summary>

```python
Timer unit: 1e-06 s

Total time: 0.599102 s
File: <ipython-input-165-e5d9f0a95f5e>
Function: hyperslab at line 1

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
     1                                           def hyperslab(dset: h5py.Dataset, indices: "List[Slice, Int]"):
     2     19999      81258.0      4.1     13.6      dset_space = dset.id.get_space()
     3     19999      68471.0      3.4     11.4      dims = dset_space.get_simple_extent_dims()  # Should do a bounds check, but could also avoid this call
     4     19999      17111.0      0.9      2.9      ndims = len(dims)
     5     19999      46182.0      2.3      7.7      dsel_id = dset_space.copy()
     6                                               
     7     19999      47526.0      2.4      7.9      dsel_start = [0 for i in range(ndims)]
     8     19999      16413.0      0.8      2.7      dsel_stride = dsel_start.copy() # [0 for i in range(ndims)]
     9     19999      13944.0      0.7      2.3      dsel_count = dsel_start.copy()  # [0 for i in range(ndims)]
    10                                               
    11     39998      37432.0      0.9      6.2      for k, index in enumerate(indices):
    12     19999      27910.0      1.4      4.7          if isinstance(index, (int, np.integer)):
    13                                                       dsel_start[k] = index
    14                                                       dsel_stride[k] = 1
    15                                                       dsel_count[k] = 1
    16     19999      15731.0      0.8      2.6          elif isinstance(index, slice):
    17     19999      27938.0      1.4      4.7              start, stop, step = index.indices(dims[k])
    18     19999      16614.0      0.8      2.8              count = (stop - start) // step
    19     19999      15063.0      0.8      2.5              dsel_start[k] = start
    20     19999      13422.0      0.7      2.2              dsel_stride[k] = step
    21     19999      13097.0      0.7      2.2              dsel_count[k] = count
    22                                                   else:
    23                                                       raise ValueError()
    24                                                       
    25     19999      24586.0      1.2      4.1      dsel_start, dsel_stride, dsel_count = tuple(dsel_start), tuple(dsel_stride), tuple(dsel_count)
    26     19999      60437.0      3.0     10.1      dsel_id.select_hyperslab(dsel_start, dsel_count, dsel_stride)
    27     19999      42244.0      2.1      7.1      dset_space.close()
    28                                               
    29     19999      13723.0      0.7      2.3      return dsel_id, dsel_count
```

</details>

```python
%lprun -f getindex readall()
```

<details>
<summary> getindex line-by-line </summary>

```python
Timer unit: 1e-06 s

Total time: 0.977149 s
File: <ipython-input-126-174d0c1c471a>
Function: getindex at line 1

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
     1                                           def getindex(dset, indices):
     2     19999     461202.0     23.1     47.2      dsel_id, mem_shape = hyperslab(dset, indices)
     3     19999      52935.0      2.6      5.4      msel_id = h5py.h5s.create_simple(mem_shape)
     4     19999      66783.0      3.3      6.8      out = np.empty(mem_shape, dset.dtype)
     5                                           
     6     19999     322197.0     16.1     33.0      dset.id.read(msel_id, dsel_id, out)
     7                                           
     8     19999      37345.0      1.9      3.8      msel_id.close()
     9     19999      28092.0      1.4      2.9      dsel_id.close()
    10                                           
    11     19999       8595.0      0.4      0.9      return out
```

</details>

### Notes

* At the moment this only supports indexing with slices (with positive step) and positive integers
* This doesn't remove dimensions like numpy does, though I think numpy could efficiently handle that afterwards, instead of converting shapes back and forth as is currently done.
* Similarly, dimensions which had negative slices could be reversed after being extracted from the file.
* There is significant overhead to getting the shape of a dataset. This can be avoided by passing it as a tuple. I'm not sure if this is inherent to the hdf5 library, or if it has to do with the cython layer.

**Comment by takluyver** [comment]
I also played around with some profiling yesterday. :-) I'm thinking about implementing some caching at the Python layer, e.g. for `ds.shape`, so it doesn't need to get it every time. But I'm still trying to understand why it seems to take as long as it does.

**Comment by takluyver** [comment]
>  I would like it if there was a way to just iterate over the chunks of a dataset as quickly as possible. Do you think that could be in scope for this library?

Yep, it's being worked on in #1333.

**Comment by takluyver** [comment]
I've been using a simpler test case (fixed length small reads) to experiment with this, looking at the difference between

<details>
<summary>the obvious approach with the high-level API (1.1 - 1.3 seconds on my system)</summary>

```python
for i in range(10_000):
    offset = i * 10
    a = ds[offset:offset + 10]
```
</details>

<details>
<summary>The slightly lower-level `read_direct` function (0.75 - 1.0 s)</summary>

```python
for i in range(10_000):
    offset = i * 10
    ds.read_direct(a2, slice(offset, offset+10))
```
</details>

<details>
<summary>the low-level API, avoiding as much work in the loop as I can (0.2 - 0.25 s)</summary>

```python
dest_sel = SimpleSelection(a3.shape)
sel = SimpleSelection(ds.shape)


for i in range(10_000):
    offset = i * 10
    sl = slice(offset, offset+10)
    sel[sl]  # This modifies sel in place
    ds.id.read(dest_sel.id, sel.id, a3, dxpl=ds._dxpl)
```
</details>

This roughly fits with your results - we can potentially save 2/3 to 3/4 of the time for this kind of access with changes in the Python layer, before we get into what's happening in the Cython code. The interesting challenge, IMO, is how much of that speedup we can bring to normal usage, rather than adding another separate method for faster reading.

I also made C code to do the same kind of access - it can do it in about 0.01 seconds, so even my fastest Python code is still an order of magnitude slower. Some of that is probably unavoidable, but I bet there's more room for speedups.

**Comment by ivirshup** [comment]
I think hdf5 may already cache some of these things in the metadata cache, but I'm not sure if h5py accesses those. That should come with some methods for checking if the cache has been invalidated.

> The interesting challenge, IMO, is how much of that speedup we can bring to normal usage, rather than adding another separate method for faster reading.

Yeah, if the goal is to improve general reads and writes it's good to have this done through the main interface. The `getindex` method I showed above allows this, since I'm fairly certain it covers most non-fancy numpy style indexing. My thinking was it could replace most usage of the `h5py._tl.selection` module within `dataset.__getindex__`.

> But I'm still trying to understand why it seems to take as long as it does.

It seems pretty ubiquitous. And the code still seems kinda slow at the cython level. Do you think it could be the `with_phil` lock? That would explain why most calls to the hdf5 api (since they're wrapped with this) are taking a while.

**Comment by takluyver** [comment]
I've opened #1402, which gets about a 50% speedup on the high-level cases with some caching. I also found that `numpy.product()` is pretty slow for a handful of numbers, and it's easy to do much better with a bit of custom Python code.

> It seems pretty ubiquitous. And the code still seems kinda slow at the cython level. Do you think it could be the with_phil lock?

My intuition is that that's not it - I know the `phil` lock is designed to be lightweight when there's only one thread using it, and a couple of quick timeit tests indicate that it is. Maybe I'm missing something about how it behaves in the context of the rest of the codebase, though.

**Comment by takluyver** [comment]
I spent a bit longer profiling into the Cython code ([Cython docs on profiling](http://docs.cython.org/en/latest/src/tutorial/profiling_tutorial.html)). There's some stuff in the `h5py._hl.selections` module that's slower than I'd expect (`_handle_simple` and `_expand_ellipsis`), but no smoking gun that would get another 50% speedup.

I'm starting to wonder if it's death by 1000 cuts: if all the little things the h5py code does to bridge the gap between HDF5 and idiomatic Python add up to a big slowdown. E.g. taking out some error handling calls, as #1353 tries to do, makes it a few % faster.

**Comment by ivirshup** [comment]
> My intuition is that that's not it - I know the phil lock is designed to be lightweight when there's only one thread using it, and a couple of quick timeit tests indicate that it is. 

Gave this a shot, and I think you're right here. Just setting the flag to false didn't seem to do much. I guess I could try just removing all the decorators as well.

> I'm starting to wonder if it's death by 1000 cuts

I think there's value in just trying to reimplement the very basics from scratch to see if we can get close to the C efficiency. Then we could figure out if there is some fundamental limitation in communicating between python and C, or if it can be overcome.

>>I would like it if there was a way to just iterate over the chunks of a dataset as quickly as possible. Do you think that could be in scope for this library?

>Yep, it's being worked on in #1333. 

Just took a look at that PR, and it's not quite what I had in mind. What I was looking for was iterating over the actual chunks of an array from a file – not just indices. Is that something that would be in scope here? I think I've got something kinda working for this.

**Comment by ivirshup** [comment]
One last idea on possible performance issues, there are a lot of conversions between tuples and arrays in the cython code. In particular, I'd look at `select_hyperslab`, which requires tuples to be passed, but then will just convert them to arrays. I'm not sure on the typing, but it looks like these might even be python tuples containing python objects that would need to be unboxed.

**Comment by takluyver** [comment]
It is converting from a Python tuple with Python objects - that's automatically created when you do slicing like `d[0, 0:10]`. In theory I think we could avoid a tuple for 1D slicing, but retrieving a single item from a tuple should be quick anyway, and having a separate code path for 1D slicing would mean more complexity.

**Comment by ivirshup** [comment]
The tuples aren't being passed directly from the user input though, they're being constructed in `h5py._hl.selections._handle_simple` where lists are being constructed (via `.append`) then converted to python tuples. If numpy arrays were created in `_handle_simple`, I think it could be possible to just pass a reference and not even have to re-allocate or do much unboxing. I think it would largely look like this on the python side (though I think this could be done in numba soon, or translated to cython):

<details>
<summary> Translate indices to h5py hyperslab input </summary>

```python
def nhits(diff, step):
    q, r = np.divmod(diff, step)
    if r:
        q += 1
    return q

def zip_indices(indices, dims):
    """
    Given an indexer (basic, not advanced) and dimensions of an array, returns
    a three tuple of arrays for offsets, strides, and lengths.
    """
    ndims = len(dims)
    
    out_start = np.zeros(ndims, dtype=np.int_)  # Is np.int_ equivalent to hsize_t?
    out_stride = np.zeros(ndims, dtype=np.int_)
    out_count = np.zeros(ndims, dtype=np.int_)

    dim_idx = 0
    for index in indices:
        if isinstance(index, (int, np.integer)):
            out_start[dim_idx] = index
            out_stride[dim_idx] = 1
            out_count[dim_idx] = 1
        elif isinstance(index, slice):
            start, stop, step = index.indices(dims[dim_idx])
            count = nhits(stop - start, step)
            out_start[dim_idx] = start
            out_stride[dim_idx] = step
            out_count[dim_idx] = count
        elif index == Ellipsis:
            nmissing = ndims - len(indices) + 1
            for i in range(nmissing):
                out_start[dim_idx] = 0
                out_stride[dim_idx] = 1
                out_count[dim_idx] = dims[dim_idx]
                dim_idx += 1
            continue
        else:
            raise ValueError()
        dim_idx += 1

    return out_start, out_stride, out_count
```

</details>

**Comment by takluyver** [comment]
Oh yes, it makes some new tuples. You might be right that assembling them in arrays would be faster.

`_handle_simple` isn't a public API, so we can change that. `select_hyperslab` is, so it would need to continue accepting tuples. But it could take either tuples or arrays, or possibly we could add a new private method that only took arrays.

**Comment by takluyver** [comment]
I'm still playing around with performance, trying to speed up selecting the data. I've got some gains by reorganising the Python code (I hope to have a PR soon). But my attempts to speed up `select_hyperslab` by using arrays instead of tuples aren't going so well.

numpy arrays have relatively high creation overhead for tiny amounts of data like this. So I've tried with the [array module](https://docs.python.org/3/library/array.html) instead. But my best effort to use it for selecting a hyperslab in Cython is still slower than the version that checks and converts from tuples.

<details>
<summary>Cython method (SpaceID._select_hyperslab_arr)</summary>

```python
def _select_hyperslab_arr(self,
                              const hsize_t[:] start,
                              const hsize_t[:] count,
                              const hsize_t[:] stride=None,
                              const hsize_t[:] block=None,
                              int op=H5S_SELECT_SET,
                              ):
        cdef int rank
        cdef hsize_t* stride_ptr = NULL
        cdef hsize_t* block_ptr = NULL
        rank = H5Sget_simple_extent_ndims(self.id)

        if len(start) != rank:
            PyErr_SetString(ValueError, "Wrong number of dimensions")

        if stride is not None:
            stride_ptr = &stride[0]
        if block is not None:
            block_ptr = &block[0]

        H5Sselect_hyperslab(self.id, <H5S_seloper_t>op,
                            &start[0], stride_ptr, &count[0], block_ptr)
```
</details>

<details>
<summary>Timings in IPython</summary>

```
# shape == (100_000,)
In [6]: dspace = ds.id.get_space()                                                   

In [7]: start_t, count_t, stride_t = (0,), (10,), (1,)                               

In [8]: start_a, count_a, stride_a = [array('Q', tup) for tup in (start_t, count_t, s
   ...: tride_t)]                                                                    

In [9]: %timeit dspace.select_hyperslab(start_t, count_t, stride_t)                  
1.35 µs ± 50.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [10]: %timeit dspace._select_hyperslab_arr(start_a, count_a, stride_a)            
1.57 µs ± 13.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [11]: %timeit dspace.select_hyperslab(start_t, count_t, stride_t)                 
1.31 µs ± 12.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [12]: %timeit dspace._select_hyperslab_arr(start_a, count_a, stride_a)            
1.58 µs ± 39.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [13]: %timeit dspace.select_hyperslab(start_t, count_t, stride_t)                 
1.32 µs ± 12.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [14]: %timeit dspace._select_hyperslab_arr(start_a, count_a, stride_a)            
1.56 µs ± 6.56 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

# array version with with_phil decorator
In [15]: %timeit dspace._select_hyperslab_arr_phil(start_a, count_a, stride_a)       
1.75 µs ± 23.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [16]: %timeit dspace._select_hyperslab_arr_phil(start_a, count_a, stride_a)       
1.75 µs ± 16.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```
</details>

I can get it slightly faster (~1.15 µs) by commenting out the length check. But I think you could get segfaults if the `hsize_t*` pointers point to smaller buffers than HDF5 expects, so I'd rather not remove that check, even in a private method.

**Comment by kif** [comment]
> numpy arrays have relatively high creation overhead for tiny amounts of data like this. So I've tried with the [array module](https://docs.python.org/3/library/array.html) instead. But my best effort to use it for selecting a hyperslab in Cython is still slower than the version that checks and converts from tuples.

Hi ThomasK,

The limitation you are describing are well known in cython. One
shouldn't use numpy arrays for small object storage.

Cython memory views a a bit lighter but far from perfect. Pure python
objects turn out to be very efficient for creation/destruction (which
is counter-intuitive).

**Comment by ivirshup** [comment]
Just trying out the new release candidate, and performance is great now! Now reading slices from a flat dataset is ~2x faster than using a python based cache of the chunks.

Using the `Cache` benchmark from my previous comment (https://github.com/h5py/h5py/issues/1391#issuecomment-541516716):

```python
In [34]: %%timeit
    ...: for i in range(len(indices) - 1):
    ...:     s = slice(indices[i], indices[i+1])
    ...:     cache.get_slice(s)
    ...: 
301 ms ± 29.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [35]: %%timeit
    ...: for i in range(len(indices) - 1):
    ...:     s = slice(indices[i], indices[i+1])
    ...:     dset[s]
    ...: 
153 ms ± 4.77 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

A little surprisingly, I'm only seeing small changes in read speeds from setting `rdcc_nbytes=0` (though I am seeing some effect). My guess is that this might have to do with hitting the OS cache instead of the hdf5 one. I'd note that I have tried this timing multiple times on different datasets varying the size of the slices and see a consistent 33% slowdown with `rdcc_nbytes=0`.

```python
In [58]: f = h5py.File("test.h5", "r", rdcc_nbytes=100 * (1024 ** 2), rdcc_nslots=50000)
    ...: dset = f["x"]

In [59]: %%timeit
    ...: for i in range(len(indices) - 1):
    ...:     s = slice(indices[i], indices[i+1])
    ...:     dset[s]
    ...: 
142 ms ± 5.31 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [60]: f.close()
    ...: f = h5py.File("test.h5", "r", rdcc_nbytes=0)
    ...: dset = f["x"]

In [61]: %%timeit
    ...: for i in range(len(indices) - 1):
    ...:     s = slice(indices[i], indices[i+1])
    ...:     dset[s]
    ...: 
193 ms ± 7.59 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Additionally, now `h5py` beats the `julia` code in the example I used.

This improvement is fantastic! Thanks for all the work that went into this!

**Comment by takluyver** [comment]
Thanks @ivirshup !

> A little surprisingly, I'm only seeing small changes in read speeds from setting rdcc_nbytes=0 (though I am seeing some effect). My guess is that this might have to do with hitting the OS cache instead of the hdf5 one.

I think this is right, as your data is not compressed - once it's in the OS disk cache, reading it is just one extra memory copy. I found at some point that the HDF5 cache is much more important with compressed data - which makes sense, because the HDF5 cache can store the decompressed data, whereas the disk cache has it compressed.

**Comment by takluyver** [comment]
I think I'm satisifed that there's nothing specific to tackle here. 3.0 made some performance improvements, and while there may be more room to improve, I don't think it's worth turning this issue into a generic 'better performance' one. I believe we understand why the HDF5 chunk cache doesn't seem to make much difference when data isn't compressed (because the OS is also caching data read from file).

So I'll close this. If someone strenuously disagrees, we can reopen it. Or if you identify a specific performance problem, please open a new issue.
