### ISSUE TITLE
Where is the CHANGELOG?

### ISSUE THREAD

**Issue by MartinThoma** [h5py/h5py#1392]
The note for [release 2.10.0](https://github.com/h5py/h5py/releases) is "Updated CHANGELOG for 2.10.0", but I can't find a CHANGELOG.

**Comment by takluyver** [comment]
There was a bug with the release tool we've just adopted that made the release notes go missing. They're restored in master, and you can read them here: http://docs.h5py.org/en/latest/whatsnew/2.10.html

**Comment by NumesSanguis** [comment]
2.10.0 was released on Sep 7, 2019 and therefore stable? But it doesn't show up in the stable documentation (only latest): http://docs.h5py.org/en/stable/whatsnew/

**Comment by takluyver** [comment]
The stable docs are built from the release tag, which corresponds to the package that went on PyPI. The bug meant that the release notes for 2.10 were not there when the tag was made.

**Comment by NumesSanguis** [comment]
Sorry, since this issue was closed, I thought we should see the release notes now.
So, if I understand correctly, with the next release, the fixed release tool will be included and stable will have both 2.10 and 2.11 or 3.0?

**Comment by takluyver** [comment]
Yup, exactly. It should be a one-off hiccup for 2.10, after we started using rever to make the release.
