### ISSUE TITLE
Feature request: regionrefs selecting only one element

### ISSUE THREAD

**Issue by mitar** [h5py/h5py#1404]
I am using h5py==2.10.0. It looks like regionrefs cannot select only one element. See:

```python
import h5py
import numpy as np

file = h5py.File('output.h5', 'w', libver='latest')

test_dataset = file.create_dataset('test', data=np.arange(10))
print(test_dataset[0])
print(test_dataset[test_dataset.regionref[0]])
```

Output:

```
0
[0]
```

I would expect that the second `print` also outputs `0`.

**Comment by takluyver** [comment]
HDF5 itself doesn't have a distinction between getting a single element and a slice containing one element, so that information can't be stored in a region ref.

If all the regions you want to store are single elements, then you may prefer to store indices. If you need a mixture, you'd have to store the region refs alongside a boolean array indicating whether to get the item out as a scalar.

**Comment by mitar** [comment]
But with indices I then have to manually de-reference them?

Also, there is no way to select a row by value of a column? So like making a column a primary key? Because if I am to store the indices, I could be instead storing the primary key values. Like in regular relational data.

**Comment by takluyver** [comment]
Dereferencing an index (`ds[idx]`) is no more manual than dereferencing a regionref (`ds[rref]`), really. :)

> Also, there is no way to select a row by value of a column? So like making a column a primary key?

If you're looking to use it like a database, look at pytables, e.g. its [Table.where() method](http://www.pytables.org/usersguide/libref/structured_storage.html#tables.Table.where). h5py mostly tries to expose HDF5's own functionality, without adding stuff on top.

HDF5 has a notion of annotating axes with dimension scales ([dimension scales in h5py docs](http://docs.h5py.org/en/stable/high/dims.html)), but I don't think they have any shortcuts for looking up data - you'd have to read the appropriate scale, find the index of the value you want, and then use the index to get the relevant data.

**Comment by mitar** [comment]
> Dereferencing an index (ds[idx]) is no more manual than dereferencing a regionref (ds[rref]), really. :)

Hm, you are right. References seem to not contain information from which dataset they are, so they do not provide more metadata to allow for automatic dereferencing.

**Comment by takluyver** [comment]
They do also contain a reference to their dataset, but we currently don't have any way to dereference both paths at once, so you have to do something like `file[rref][rref]` - once to get the dataset, once to get the data from a region of it.

**Comment by mitar** [comment]
Oh, nice. But then there is big difference between a reference and an index.

So you could not find some way to store a bit saying if it should return one element or multiple elements?

**Comment by takluyver** [comment]
I'd leave that up to the application - region references are an HDF5 feature which h5py is exposing, and they don't have a way to store that. If we invent our own regionref-plus thing, it won't work smoothly with other software reading/writing HDF5 files.

**Comment by mitar** [comment]
[Here](https://support.hdfgroup.org/HDF5/doc/RM/RM_H5S.html#Dataspace-SelectHyperslab) I see:

>  The block array determines the size of the element block selected from the dataspace. If the block parameter is set to NULL, the block size defaults to a single element in each dimension (as if each value in the block array were set to 1). 

Could we overload this by making NULL work differently than 1? This would still be compatible with other applications, but in Python we could return a scalar if it is NULL.

**Comment by takluyver** [comment]
I think that's only for the input to the function, and it will still result in 1 stored in the file.

**Comment by takluyver** [comment]
Closing as I don't think there's anything for h5py to do: HDF5 regionrefs do not have a way to record that you want to drop dimensions (as HDF5 in general has no notion of this), and I don't think h5py should come up with its own incompatible thing to do that. If an application needs this capability, it can store regionrefs alongside extra data it knows about.
