### ISSUE TITLE
unable to configure: AttributeError: module 'pkgconfig' has no attribute 'exists'

### ISSUE THREAD

**Issue by MxmRenaud** [h5py/h5py#1408]
Hi all,
I'm a complete newcomer to both python and the hdf5 format, so it's probably a very basic problem. But.

When running `python3 setup.py configure` it basically crashes immediately, with the following output:

>running configure
Traceback (most recent call last):
  File "setup.py", line 162, in <module>
    cmdclass = CMDCLASS,
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/mrenaud1/fair_install/h5py/setup_configure.py", line 160, in run
    self.hdf5_version = autodetect_version(self.hdf5)
  File "/home/mrenaud1/fair_install/h5py/setup_configure.py", line 211, in autodetect_version
    if pkgconfig.exists("hdf5"):
AttributeError: module 'pkgconfig' has no attribute 'exists'

As mentioned below their are a few parallel installs of python on this machine, so I tried changing the version used both by changing `python/3/3.6 setup.py configure`and by changing the first line in setup.py: `#!/usr/bin/env python/3/3.6`. The exact error varies, but it always ends on the one reported above. As far as I can tell 'pkgconfig' is installed in so far that I get a lot of output if I `locate pkgconfig`.

 * Operating System: Ubuntu 16.04.5 LTS x86_64
 * Python version : three parallel installs (may be source of the problem ?): python -> 2.7.12; python3 -> 3.5.2; python3.6 -> 3.6.8
 * Where Python was acquired : 2.7 was system, 3.5 unknown (not sole user of the machine), 3.6 manual upgrade
 * h5py version: latest Master branch version
 * HDF5 version: 1.8.16

Sorry if it's very obvious. Thanks !

**Comment by takluyver** [comment]
In the same folder where you ran that, can you launch Python and do:

```python
import pkgconfig
print(pkgconfig)
```

It seems to be importing an incorrect `pkgconfig` module from somewhere. What it's expecting is available as the [pkgconfig package on PyPI](https://pypi.org/project/pkgconfig/).

**Comment by MxmRenaud** [comment]
So I started by getting 
`>>> print(pkgconfig)`
`<module 'pkgconfig' (namespace)>` 
for every python version, so I (re- ?)installed pkgconfig through pip.

Now I get for python 2.7
`>>> print(pkgconfig)`
`<module 'pkgconfig' from '/home/mrenaud1/.local/lib/python2.7/site-packages/pkgconfig/__init__.pyc'>`

But I still have the same `<module 'pkgconfig' (namespace)>` for python 3.6, which I assume I need to fix ?

**Comment by takluyver** [comment]
Yes, I think so. Is `$PYTHONPATH` set? If so, try unsetting it.

**Comment by MxmRenaud** [comment]
It is set, (`/home/mrenaud1/fair_install/ATTPCROOTv2/python:/home/mrenaud1/fair_install/FairSoft-install/lib:/home/mrenaud1/fair_install/FairSoft-install/lib/root:/home/mrenaud1/fair_install/FairSoft-install/lib/Geant4:/home/mrenaud1/fair_install/FairSoft-install/lib/g4py`). None of the listed folders are for the python installs I use.

When you suggest I "unset" it, do you mean to nothing ? And then re-install pkgconfig ?

**Comment by takluyver** [comment]
PYTHONPATH shouldn't make a difference to how modules get installed, but it does change how they're looked up for import. I'm a bit puzzled, though, because normally finding a namespace package accidentally only happens when it can't find the regular module at all.

In a terminal, try this:

```
unset PYTHONPATH
python3 setup.py configure
```

If that still doesn't work, try installing `pkgconfig` again.

**Comment by MxmRenaud** [comment]
Hi,

So, unsetting PYTHONPATH did not actually change anything, so I re-installed pkgconfig. I only managed to force it onto python3.5, not 3.6, but at least that got me through the `configure` phase, so I can start massaging the build now. 
If I get stuck again, I'll open another ticket.

Thanks for the help !
