### ISSUE TITLE
Linux/ macOS wheels for python 3.8

### ISSUE THREAD

**Issue by clbarnes** [h5py/h5py#1410]

**Comment by tacaswell** [comment]
We need numpy to have wheels first and for py38 to be available to travis for https://github.com/MacPython/h5py-wheels to work.

Any help getting the build machinery updated would be appreciated.

**Comment by clbarnes** [comment]
3.8 is already on Travis; for Linux at least (spent some of this afternoon updating my repos and it's basically only h5py dependents which are failing at the moment). Numpy wheels are obviously a blocker, but it's good to have a tracking issue.

**Comment by larsoner** [comment]
> We need numpy to have wheels first

1.17.3 is out with 3.8 wheels: https://pypi.org/project/numpy/#files

> and for py38 to be available to travis

SciPy has been testing 3.8-dev for a while, if that's good enough maybe you can adapt its config:

https://github.com/scipy/scipy/blob/master/.travis.yml#L67

**Comment by ngoldbaum** [comment]
It looks like multibuild support is there now: https://github.com/matthew-brett/multibuild/issues/261

I think all that remains for h5py is someone turning the crank in this repository to update things and generate the wheel.

**Comment by ngoldbaum** [comment]
Ah I see Tom actually did that already and the wheels are up at wheels.scipy.org, so I guess someone just needs to upload the wheel files to pypi.

**Comment by tacaswell** [comment]
I made some progress over the weekend, it looks like it worked for 2.10 (https://travis-ci.org/MacPython/h5py-wheels/builds/602613674) 2.9 seems to have had some issues on mac.

**Comment by tacaswell** [comment]
The issue on mac seems to be something about 32 vs 64 bit changes in OSX....


```
  ImportError: dlopen(/Users/travis/build/MacPython/h5py-wheels/venv/lib/python3.8/site-packages/Cython/Compiler/Scanning.cpython-38-darwin.so, 2): no suitable image found.  Did find:
2442  	/Users/travis/build/MacPython/h5py-wheels/venv/lib/python3.8/site-packages/Cython/Compiler/Scanning.cpython-38-darwin.so: mach-o, but wrong architecture
2443  	/Users/travis/build/MacPython/h5py-wheels/venv/lib/python3.8/site-packages/Cython/Compiler/Scanning.cpython-38-darwin.so: mach-o, but wrong architecture
```

**Comment by tacaswell** [comment]
Tried restarting the build to see if cython fixed its self over the weekend.  We also need to email Christoph about windows builds.

**Comment by clbarnes** [comment]
I think I recall hearing that macOS Catalina was going to have no 32-bit support whatsoever, but I'd be surprised if CI rigs were using that already.

**Comment by kif** [comment]
I'll try to do the build tomorrow.

**Comment by tacaswell** [comment]
We should invoke @matthew-brett for the osx + cython issues as well....

@kif Does it make sense to try to build powerpc wheels?  Is there a standard way to make manylunix wheels on powerpc?

**Comment by clbarnes** [comment]
Seems like the wheels are generate-able, as they're on wheels.scipy.org, and there's interest in uploading them, as windows already has 2.10 wheels on PyPI. I'm not familiar with the publishing process in h5py - is there a particular issue blocking this right now?

**Comment by jackexu** [comment]
I don't know why they don't update it yet...but here is the manual way to solve it in case any Python 3.8 user wants to install Keras and etc.
`pip install h5py-2.10.0-cp38-cp38-macosx_10_9_x86_64.whl` 
the file could be download at [](http://wheels.scipy.org)

**Comment by amorison** [comment]
Any news on this? Availability of h5py wheels is crucial for several packages, especially as Python 3.8 starts being released on common Linux distributions.

**Comment by effigies** [comment]
They're up on http://wheels.scipy.org/ (https link: https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com/). Adding `--find-links=$URL` to your `pip` command will find them.

**Comment by amorison** [comment]
Yeah sure, but personally I can't expect all the end-users of my packages to do this by themselves. And instead of documenting it + changing deployment scripts only for one package, I just don't support Python 3.8 for now. Making all these changes would be cumbersome when the only thing missing is uploading the wheel on PyPI. This is not in any case a critic towards the maintainers of h5py, I know how time consuming maintaining packages can be. It's merely a reminder that uploading the existing wheels on PyPI would save a lot of time for a lot of people.

**Comment by clbarnes** [comment]
Agreed, downstream developers can already fix their builds by introducing h5py-specific configuration (installing libhdf5). The point is we're trying to avoid it.

**Comment by matthew-brett** [comment]
Any reason not to upload the wheels to PyPI?

**Comment by ngoldbaum** [comment]
> Any reason not to upload the wheels to PyPI?

It was originally blocked on the lack of availability of wheels for some architectures. If those are up now then I think it's blocked on someone with upload access to pypi actually doing the upload. Maybe @tacaswell can confirm?

**Comment by matthew-brett** [comment]
But - perhaps this is historical now - but is there a reason not to
release wheels for the architectures that have them?    At least those
architectures would get a faster and more reliable install ...

**Comment by tacaswell** [comment]
My instinct to push stuff up in batches is due to @matthew-brett 's request to not push the sdist files up before the wheels are ready, but on the slightest further consideration that makes no sense in this context.

I'm working on publishing the wheels now.

**Comment by tacaswell** [comment]
I'm going to close this as the wheels are now up (see https://pypi.org/project/h5py/#files).

**Comment by clbarnes** [comment]
Thank you so much! A big help to everyone downstream.

**Comment by matthew-brett** [comment]
Thanks a lot from me too...

**Comment by tacaswell** [comment]
Thanks of the machinery to build them @matthew-brett !

**Comment by vasole** [comment]
@tacaswell 

Concerning your questions:

```
Does it make sense to try to build powerpc wheels? Is there a standard way to make manylunix wheels on powerpc?
``` 
Situation has evolved at our side since the answer from @kif.

I do not know what to say concerning the first question, but the answer to the second question seems to be yes. @t20100 can confirm or deny and provide you with more details. He has set up automatic building of manylinux2014 wheels for ppc64le. The wheels are at https://www.silx.org/pub/wheelhouse/

**Comment by t20100** [comment]
There is now a Power9 docker image for manylinux on Power9 (quay.io/pypa/manylinux2014_ppc64le), but you also need a Power9 machine...

I have a small gitlab internal project to build Power9 wheels uploaded to https://www.silx.org/pub/wheelhouse/ for a few projects including h5py (which for now takes the short-cut of using a pre-built hdf5 library). If it might be of interest for you, I can share it.

**Comment by tacaswell** [comment]
I am provisionally in favor of publishing the wheels built at ESRF to pypi.
