### ISSUE TITLE
Feature request: Handle unit metadata

### ISSUE THREAD

**Issue by DBerke** [h5py/h5py#1418]
I'm looking into using h5py to store some astrophysical data, with which I'm using the Unyt package (https://unyt.readthedocs.io/en/latest/) to store information on units so I don't have to keep track of it manually. Currently, storing a `unyt.unyt_array` (which is a subclass of a NumPy `ndarray`) in HDF5 causes it to lose the unit metadata attached.

I can, of course, simply re-apply the units whenever I extract the data from HDF5, but it's easy to make mistakes when working with complicated or multiple types of units, and this is exactly the problem that Unyt was intended to solve. I don't know how difficult this would be to add; perhaps there could be metadata attached to a dataset to keep track of the units, and they could be automatically applied when loading from a file? (Actually, I may try experimenting with that myself.)

**Comment by scopatz** [comment]
This might be doable realtively robustly with the new opaque dtype capability

**Comment by takluyver** [comment]
I would do this by attaching [attributes](http://docs.h5py.org/en/stable/high/attr.html) describing the units. That way the data is still readable and comprehensible whether or not a tool knows how to reconstruct the units.

Beyond exposing the attributes mechanism, I think storing units is out of scope for h5py until/unless HDF5 gains some standard way to represent units (which I'm [pushing for](https://forum.hdfgroup.org/t/machine-readable-units-format/5480), but I don't think it's going anywhere soon).

Someone could of course build a layer on top of h5py which automatically stores and reconstructs units. Or you could look at something like the netCDF4 format, which I think includes ways to record units.

**Comment by takluyver** [comment]
I don't think this would work with the opaque dtype features in #1339. But if it was, it would be exactly the sort of convenient shortcut I'm concern about enabling: throwing away standard, interoperable formats for convenient access from a single tool. Storing units in attributes has graceful degradation, because the data is still accessible through any tool that speaks HDF5, even if they don't understand the units.

**Comment by DBerke** [comment]
> I would do this by attaching [attributes](http://docs.h5py.org/en/stable/high/attr.html) describing the units. That way the data is still readable and comprehensible whether or not a tool knows how to reconstruct the units.

Yeah, I read more of the documentation and played around with it after posting and figured out a simple solution using attributes. (Example code below in case people are interested.) This is my first time creating HDF5 files so I wasn't aware of all the available functionality, but I agree this is a better solution than specifically adding compatibility for all the reasons you mentioned. I'll go ahead and close the issue.

```python
import unyt as u
import h5py
import tempfile
tf = tempfile.TemporaryFile()
f = h5py.File(tf)
test_data = [2, 4, 6, 8] * u.m / u.s
f.create_dataset('test data', data=test_data)
f['test data'].attrs['units'] = str(test_data.units)
reconstituted_data = u.unyt_array(f['test data'], units=f['test data'].attrs['units'])
```
Then
```python
test_data == reconstituted_data
```
passes.

**Comment by takluyver** [comment]
Thanks, that sounds good. I think something like that (maybe plus comments) would be a good addition to the examples directory, if you want to make a PR: https://github.com/h5py/h5py/tree/master/examples

**Comment by DBerke** [comment]
I've written a simple example of what I had above with some comments at:
https://github.com/DBerke/h5py/blob/patch-1/examples/store_and_retrieve_units_example.py
I ran all the code in IPython and verified it worked then created a new file directly from GitHub so I don't have the repository on my machine; should I clone it and run the tox tests, or would such an example script be fine to open a pull request for directly?

**Comment by takluyver** [comment]
Thanks! I think you can open a PR directly. As far as I know, the tox tests don't run the examples anyway, so if you've run the code locally it should be fine.

**Comment by DBerke** [comment]
OK! I've opened PR #1425 with my example script.
