### ISSUE TITLE
visititems fails adding an integer

### ISSUE THREAD

**Issue by psteinb** [h5py/h5py#1419]
Hi, 
I am using visititems to compute the total size of the data contained in a h5 file. I attached both the sample input and a script to reproduce the error. Effectively, I am doing
```
small_nbytes = 0
def get_small_nbytes(name, obj):
        if isinstance(obj, h5.Dataset) and len(obj) < 10:
            small_nbytes += obj.dtype.itemsize * len(obj)

ifile5[groupname].visititems(get_large_nbytes)
```
This code fails with an UnboundLocalError as it considers `small_nbytes` to be local. 
```
Traceback (most recent call last):
  File "error.py", line 23, in <module>
    main()
  File "error.py", line 19, in main
    ifile5[groupname].visititems(get_large_nbytes)
  File "/usr/lib64/python3.7/site-packages/h5py/_hl/group.py", line 563, in visititems
    return h5o.visit(self.id, proxy)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 355, in h5py.h5o.visit
  File "h5py/defs.pyx", line 1594, in h5py.defs.H5Ovisit_by_name
  File "h5py/h5o.pyx", line 302, in h5py.h5o.cb_obj_simple
  File "/usr/lib64/python3.7/site-packages/h5py/_hl/group.py", line 562, in proxy
    return func(name, self[name])
  File "error.py", line 13, in get_large_nbytes
    large_nbytes = large_nbytes + (obj.dtype.itemsize * len(obj))
UnboundLocalError: local variable 'large_nbytes' referenced before assignment
```

Funny enough I adapted this code directly from the docstring of visititems:
```
    # Get a list of all datasets in the file
    >>> mylist = []
    >>> def func(name, obj):
    ...     if isinstance(obj, Dataset):
    ...         mylist.append(name)
    ...
    >>> f = File('foo.hdf5')
    >>> f.visititems(func)
```
This code with a list works perfectly. The one with updating an integer variable does not. Can anyone help or am I overseeing something obvious?

[bugreport.zip](https://github.com/h5py/h5py/files/3762709/bugreport.zip)

I am working on a fedora core 30 system with kernel `5.3.6-200.fc30.x86_64`.
```
$ python3 -c 'import h5py; print(h5py.version.info)'
Summary of the h5py configuration
---------------------------------

h5py    2.9.0
HDF5    1.8.20
Python  3.7.4 (default, Jul  9 2019, 16:32:37) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.16.4
```

**Comment by takluyver** [comment]
That's a general Python limitation. `l.append()` modifies an existing list, so it doesn't affect variable bindings. But `+=` counts as a kind of assignment, so it makes `small_nbytes` a local variable.

To avoid this, put `nonlocal small_nbytes` as the first line in the function. This declares that it's not a local variable, so you can modify the variable in the outer scope. ([Docs detailing how Python variable binding works](https://docs.python.org/3/reference/executionmodel.html?highlight=nonlocal#binding-of-names)).

This kind of problem is a good case for issue #1384, about making it possible to iterate without callbacks.

**Comment by takluyver** [comment]
To be clear, you don't have to use *global* variables - a `nonlocal` variable can still be local in an outer scope, like this:

```python
def count_datasets(grp):
    n = 0  # Local variable here
    def visitor(name, obj):
        nonlocal n
        if isinstance(obj, Dataset):
            n += 1

    grp.visititems(visitor)
```

An iterator interface would be nicer. Unfortunately HDF5 only has a callback interface at the C level.
