### ISSUE TITLE
Check correct behaviour of require_dataset

### ISSUE THREAD

**Issue by pierlauro** [h5py/h5py#1432]
Following the discussion in #1431, it would be useful to check that [require_dataset](https://github.com/h5py/h5py/blob/7073098eed26904f2077bac98ee450894b99468e/h5py/_hl/group.py#L198) is working as expected.

I will write some unit tests to check that intermediate groups are correctly created.

**Comment by takluyver** [comment]
I think it was `require_group` that we were talking about? But it would be good to make sure both are working properly.

**Comment by pierlauro** [comment]
I will test both to have full coverage

**Comment by takluyver** [comment]
@pierlauro - did you get anywhere with this?

**Comment by pierlauro** [comment]
@takluyver Planning to write the tests next week's holidays, still in my backlog

**Comment by takluyver** [comment]
Thanks! Just wanted to make sure it hadn't fallen off the radar.

**Comment by takluyver** [comment]
Ping? ;-)

**Comment by pierlauro** [comment]
Ping back ;-)

**Comment by pierlauro** [comment]
I had mentioned (edited) the wrong pull request, here is the one: #1473
