### ISSUE TITLE
AttributeError: 'h5py.h5p.PropFAID' object has no attribute 'set_fapl_mpio'

### ISSUE THREAD

**Issue by chrisspen** [h5py/h5py#1437]
To assist reproducing bugs, please include the following:
 * Operating System: Ubuntu 18.04
 * Python version: 3.6
 * h5py version: 2.10.0
 * HDF5 version (e.g. 1.8.17)
 * The full traceback/stack trace shown (if it appears)

```
    Traceback (most recent call last):
      File "test.py", line 203, in handle
        r = Parallel(n_jobs=processes)(tqdm(parallel_tasks))
      File "~/.env/lib/python3.6/site-packages/joblib/parallel.py", line 1016, in __call__
        self.retrieve()
      File "~/.env/lib/python3.6/site-packages/joblib/parallel.py", line 908, in retrieve
        self._output.extend(job.get(timeout=self.timeout))
      File "~/.env/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 554, in wrap_future_result
        return future.result(timeout=timeout)
      File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
        return self.__get_result()
      File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
    AttributeError: 'h5py.h5p.PropFAID' object has no attribute 'set_fapl_mpio'
```

I created my virtualenv with:

    sudo apt -yq install libopenmpi-dev python3-h5py python3.6-dev
    virtualenv -p python3.6 .env
    . .env/bin/activate
    pip install mpi4py

I'm trying to read from an h5 file from multiple processes in script is like:

    import h5py
    from joblib import Parallel, delayed
    from tqdm import tqdm

    MODEL = 'file.h5'

    def process(id):
        h = h5py.File(MODEL, driver='mpio')
        do_stuff(h)

    parallel_tasks = [
        delayed(process)(i) for i in range(10)
    ]
    r = Parallel(n_jobs=2)(tqdm(parallel_tasks))

**Comment by takluyver** [comment]
If you want to work with MPI, h5py and hdf5 both have to be built with MPI support ([docs](http://docs.h5py.org/en/stable/mpi.html#building-against-parallel-hdf5)). But I don't think that's actually necessary in this case - you can open the file read-only in several processes (`h5py.File(path, 'r')`) without any special measures. It's only parallel writing that needs MPI.

I'll leave this issue open until it gives a better error on trying to use the MPI driver from h5py that hasn't been built for it.

**Comment by takluyver** [comment]
#1443 adds an explicit error message for this case.

**Comment by chrisspen** [comment]
Thank you.

**Comment by chrisspen** [comment]
And you were right, adding 'r' fixes the problem for my case.
