### ISSUE TITLE
h5py.h5d.DatasetID.get_num_chunks missing in 2.10.0 release

### ISSUE THREAD

**Issue by wrobell** [h5py/h5py#1449]
The method is documented here http://api.h5py.org/h5d.html#h5py.h5d.DatasetID.

The method can be found in the source code of Git repository.

The method is missing in source code published on Pypi.

**Comment by takluyver** [comment]
It was added since 2.10 (PR #1200 is marked for the 3.0 milestone).

The low-level API docs are built from master. Ideally, the new functions should have a "New in version" notice (Sphinx `.. versionadded::` directive). Do you want to make a pull request for that?
