### ISSUE TITLE
Attributes are not really overridden

### ISSUE THREAD

**Issue by paulmueller** [h5py/h5py#1460]
* Ubuntu 18.04.3
 * Python 3.6 (system Python)
 * h5py 2.9.0
 * HDF5 1.10.4

When I modify attributes in an hdf5 file, the original values are still present in the original file:

```python
import h5py

with h5py.File("test.h5") as h5:
    h5.attrs["tests"] = "private0815"

with h5py.File("test.h5" "a") as h5:
    h5.attrs["tests"] = "deleted"

with open("test.h5", "rb") as fd:
    data = fd.read()

str(data).count("private0815")
# prints "1"
```

I would have expected that the old attribute data are overridden, at least according to the documentation (http://docs.h5py.org/en/stable/high/attr.html#AttributeManager.__setitem__).

**Comment by kif** [comment]
No, they are not overwritten as "deleted" may have a different size than "private0815".
@epourmal may have some comment on that.
You will need to use the h5repack tool to rewrite the whole file to get
rid of unused parts in it. 

For this reason, it is advisable to use attributes only for static metadata.

Sometimes HDF5 reminds me the FAT filesystem with its defragmentation issues in the good old times.

**Comment by takluyver** [comment]
The attributes are *logically* overwrittten them, so the new value is the one you get when accessing them through the API. That doesn't necessarily mean that the data is physically replaced. In the same way, overwriting a file may leave parts of the old data on the disk in what the filesystem considers empty space.

See also: https://support.hdfgroup.org/HDF5/hdf5-quest.html#del
