### ISSUE TITLE
Compile error when missing libhdf5.so not clear

### ISSUE THREAD

**Issue by gswebspace** [h5py/h5py#1461]
Hi,

The hardware I am using is ODROID C2, which has an ARM based processor.
Trying to install h5py as it is a dependency of one the packages I need to use. 
I first ran `sudo apt-get install python3-h5py` and then in the virtualenv I ran `pip install h5py`.
pip is using `h5py-2.10.0.tar.gz` to build the wheel.

But running into the following error -
```
    Loading library to get version: libhdf5.so
    error: libhdf5.so: cannot open shared object file: No such file or directory
```
Let me know if you have any clue how to successfully have the pip package installed.

To assist reproducing bugs, please include the following:
 * Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 16.04.2 LTS, CentOS 7)
From /etc/os-release : `Ubuntu 18.04.3 LTS`
From uname : `Linux odroid 3.16.72-46 #1 SMP PREEMPT Tue Aug 13 18:09:58 -03 2019 aarch64 aarch64 aarch64 GNU/Linux`

 * Python version (e.g. 2.7, 3.5)
3.7.5

 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows)
Installed to system using `sudo apt-get install python3.7` and then using it in virtualenv
 * h5py version (e.g. 2.6)
python3-h5py version 2.7.1-2
 * HDF5 version (e.g. 1.8.17)
Not sure, how do I check ?

 * The full traceback/stack trace shown (if it appears)
```
(venv) rmc@odroid:~/tf-arm$ pip install h5py
Collecting h5py
  Using cached https://files.pythonhosted.org/packages/5f/97/a58afbcf40e8abecededd9512978b4e4915374e5b80049af082f49cebe9a/h5py-2.10.0.tar.gz
Requirement already satisfied: numpy>=1.7 in ./venv/lib/python3.7/site-packages (from h5py) (1.17.4)
Requirement already satisfied: six in ./venv/lib/python3.7/site-packages (from h5py) (1.13.0)
Building wheels for collected packages: h5py
  Building wheel for h5py (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/rmc/tf-arm/venv/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2n_pntd7/h5py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2n_pntd7/h5py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-z5x7lfhv --python-tag cp37
       cwd: /tmp/pip-install-2n_pntd7/h5py/
  Complete output (64 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-3.7
  creating build/lib.linux-aarch64-3.7/h5py
  copying h5py/ipy_completer.py -> build/lib.linux-aarch64-3.7/h5py
  copying h5py/version.py -> build/lib.linux-aarch64-3.7/h5py
  copying h5py/h5py_warnings.py -> build/lib.linux-aarch64-3.7/h5py
  copying h5py/__init__.py -> build/lib.linux-aarch64-3.7/h5py
  copying h5py/highlevel.py -> build/lib.linux-aarch64-3.7/h5py
  creating build/lib.linux-aarch64-3.7/h5py/_hl
  copying h5py/_hl/attrs.py -> build/lib.linux-aarch64-3.7/h5py/_hl
  copying h5py/_hl/vds.py -> build/lib.linux-aarch64-3.7/h5py/_hl
  copying h5py/_hl/files.py -> build/lib.linux-aarch64-3.7/h5py/_hl
  copying h5py/_hl/base.py -> build/lib.linux-aarch64-3.7/h5py/_hl
  copying h5py/_hl/selections2.py -> build/lib.linux-aarch64-3.7/h5py/_hl
  copying h5py/_hl/group.py -> build/lib.linux-aarch64-3.7/h5py/_hl
  copying h5py/_hl/compat.py -> build/lib.linux-aarch64-3.7/h5py/_hl
  copying h5py/_hl/filters.py -> build/lib.linux-aarch64-3.7/h5py/_hl
  copying h5py/_hl/__init__.py -> build/lib.linux-aarch64-3.7/h5py/_hl
  copying h5py/_hl/datatype.py -> build/lib.linux-aarch64-3.7/h5py/_hl
  copying h5py/_hl/dims.py -> build/lib.linux-aarch64-3.7/h5py/_hl
  copying h5py/_hl/dataset.py -> build/lib.linux-aarch64-3.7/h5py/_hl
  copying h5py/_hl/selections.py -> build/lib.linux-aarch64-3.7/h5py/_hl
  creating build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_file.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_h5pl.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_dtype.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_objects.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_h5.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_deprecation.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_dataset.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_attribute_create.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_base.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_h5d_direct_chunk.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_slicing.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_dataset_swmr.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_dims_dimensionproxy.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/common.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_group.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_h5f.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_dimension_scales.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_file2.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_attrs.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_datatype.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_dataset_getitem.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_filters.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_file_image.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_completions.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_selections.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/__init__.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_threads.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_h5p.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_attrs_data.py -> build/lib.linux-aarch64-3.7/h5py/tests
  copying h5py/tests/test_h5t.py -> build/lib.linux-aarch64-3.7/h5py/tests
  creating build/lib.linux-aarch64-3.7/h5py/tests/test_vds
  copying h5py/tests/test_vds/test_highlevel_vds.py -> build/lib.linux-aarch64-3.7/h5py/tests/test_vds
  copying h5py/tests/test_vds/__init__.py -> build/lib.linux-aarch64-3.7/h5py/tests/test_vds
  copying h5py/tests/test_vds/test_virtual_source.py -> build/lib.linux-aarch64-3.7/h5py/tests/test_vds
  copying h5py/tests/test_vds/test_lowlevel_vds.py -> build/lib.linux-aarch64-3.7/h5py/tests/test_vds
  running build_ext
  Loading library to get version: libhdf5.so
  error: libhdf5.so: cannot open shared object file: No such file or directory
  ----------------------------------------
  ERROR: Failed building wheel for h5py
  Running setup.py clean for h5py
Failed to build h5py
Installing collected packages: h5py
    Running setup.py install for h5py ... error
    ERROR: Command errored out with exit status 1:
     command: /home/rmc/tf-arm/venv/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2n_pntd7/h5py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2n_pntd7/h5py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-405hfpno/install-record.txt --single-version-externally-managed --compile --install-headers /home/rmc/tf-arm/venv/include/site/python3.7/h5py
         cwd: /tmp/pip-install-2n_pntd7/h5py/
    Complete output (64 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-3.7
    creating build/lib.linux-aarch64-3.7/h5py
    copying h5py/ipy_completer.py -> build/lib.linux-aarch64-3.7/h5py
    copying h5py/version.py -> build/lib.linux-aarch64-3.7/h5py
    copying h5py/h5py_warnings.py -> build/lib.linux-aarch64-3.7/h5py
    copying h5py/__init__.py -> build/lib.linux-aarch64-3.7/h5py
    copying h5py/highlevel.py -> build/lib.linux-aarch64-3.7/h5py
    creating build/lib.linux-aarch64-3.7/h5py/_hl
    copying h5py/_hl/attrs.py -> build/lib.linux-aarch64-3.7/h5py/_hl
    copying h5py/_hl/vds.py -> build/lib.linux-aarch64-3.7/h5py/_hl
    copying h5py/_hl/files.py -> build/lib.linux-aarch64-3.7/h5py/_hl
    copying h5py/_hl/base.py -> build/lib.linux-aarch64-3.7/h5py/_hl
    copying h5py/_hl/selections2.py -> build/lib.linux-aarch64-3.7/h5py/_hl
    copying h5py/_hl/group.py -> build/lib.linux-aarch64-3.7/h5py/_hl
    copying h5py/_hl/compat.py -> build/lib.linux-aarch64-3.7/h5py/_hl
    copying h5py/_hl/filters.py -> build/lib.linux-aarch64-3.7/h5py/_hl
    copying h5py/_hl/__init__.py -> build/lib.linux-aarch64-3.7/h5py/_hl
    copying h5py/_hl/datatype.py -> build/lib.linux-aarch64-3.7/h5py/_hl
    copying h5py/_hl/dims.py -> build/lib.linux-aarch64-3.7/h5py/_hl
    copying h5py/_hl/dataset.py -> build/lib.linux-aarch64-3.7/h5py/_hl
    copying h5py/_hl/selections.py -> build/lib.linux-aarch64-3.7/h5py/_hl
    creating build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_file.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_h5pl.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_dtype.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_objects.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_h5.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_deprecation.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_dataset.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_attribute_create.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_base.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_h5d_direct_chunk.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_slicing.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_dataset_swmr.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_dims_dimensionproxy.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/common.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_group.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_h5f.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_dimension_scales.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_file2.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_attrs.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_datatype.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_dataset_getitem.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_filters.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_file_image.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_completions.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_selections.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/__init__.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_threads.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_h5p.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_attrs_data.py -> build/lib.linux-aarch64-3.7/h5py/tests
    copying h5py/tests/test_h5t.py -> build/lib.linux-aarch64-3.7/h5py/tests
    creating build/lib.linux-aarch64-3.7/h5py/tests/test_vds
    copying h5py/tests/test_vds/test_highlevel_vds.py -> build/lib.linux-aarch64-3.7/h5py/tests/test_vds
    copying h5py/tests/test_vds/__init__.py -> build/lib.linux-aarch64-3.7/h5py/tests/test_vds
    copying h5py/tests/test_vds/test_virtual_source.py -> build/lib.linux-aarch64-3.7/h5py/tests/test_vds
    copying h5py/tests/test_vds/test_lowlevel_vds.py -> build/lib.linux-aarch64-3.7/h5py/tests/test_vds
    running build_ext
    Loading library to get version: libhdf5.so
    error: libhdf5.so: cannot open shared object file: No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/rmc/tf-arm/venv/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2n_pntd7/h5py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2n_pntd7/h5py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-405hfpno/install-record.txt --single-version-externally-managed --compile --install-headers /home/rmc/tf-arm/venv/include/site/python3.7/h5py Check the logs for full command output.

```

`h5py.version.info` contains the needed versions, which can be displayed by
```
python -c 'import h5py; print(h5py.version.info)'
```
where `python` should be substituted for the path to python used to install
`h5py` with.

hmm... could not install h5py so can't provide this info.

**Comment by tacaswell** [comment]
We do not provide wheels for aarch64 so you will need to follow https://h5py.readthedocs.io/en/stable/build.html#source-installation to install h5py.

```
  Loading library to get version: libhdf5.so
  error: libhdf5.so: cannot open shared object file: No such file or directory
```

It looks like the underlying issue is that you do not have hdf5 installed on your system.

**Comment by gswebspace** [comment]
Thanks ! Seems like that was the issue. It could have been much better if pip was able to point out the missing dependency.

pip is installing from source but hdf5 was not installed.

Installed required packages using `sudo apt-get install pkg-config libhdf5-100 libhdf5-dev`
and now pip was able to build the `.whl` file.

**Comment by tacaswell** [comment]
@gswebspace How could we re-word the exception "error: libhdf5.so: cannot open shared object file: No such file or directory" in a way that would have made it clear you needed to install hdf5 at the system level?  Would you be willing to open a PR changing the exception to something that would have helped you more?

I'm going to re-name this issue to "Compile error when missing libhdf5.so not clear".

**Comment by gswebspace** [comment]
The new title is more appropriate now(since you mentioned the missing dependency). But the original title is the better version.

To add to context, I was installing Tensorflow and h5py happens to be a dependency for it. 

Now I did not expect the Tensorflow install using pip to fail, as I was hoping pip could install any missing dependencies of tensorflow.

From my view, I had no idea about h5py or its dependency hdf5 when I started installing the Tensorflow package.

It is only when you pointed it out, I realised that I had to do something which pip couldn't.

So I really don't know if it is just the language of the error that is wrong. Maybe I shouldn't be getting that error at all.

From what I gather from [here](https://python-packaging.readthedocs.io/en/latest/dependencies.html#packages-not-on-pypi) is that there is no way to specify a system package dependency(i.e not on PyPI) that needs to be installed prior to package installation.

So that's probably why the compilation is attempted by pip, rather than the better scenario where compilation is not started (due to a missing dependency). 

This issue is probably in domain for pip I guess. 
All good here. Issue can be closed.

**Comment by tacaswell** [comment]
>  But the original title is the better version.

But if you have the correct system dependencies it does compile.  The original title suggests that we have some non-portable c code that won't compile on aarch64

> rather than the better scenario where compilation is not started (due to a missing dependency).

Why would you want pip to _not_ try to compile if binary wheels are not available?  The only way it can discover if `libhdf5.so`.  I think at that point it should give a verbose error like "We can't find a version of libhdf5, you may need to install it at the system level <hints on how to install in various platforms>".  Still fails, but gives you the next step you got from this issue immediately.

**Comment by gswebspace** [comment]
> The original title suggests that we have some non-portable c code that won't compile on aarch64
Got it, not suggesting incompatible code in any way. This turned out to be a dependency issue. So as mentioned before, all good here. Let's keep the updated title.

> Why would you want pip to not try to compile if binary wheels are not available?
Because the required system dependencies should be declared in the pip package and thus can be checked by pip for availability before compilation is to be attempted. If pip finds out the dependency is missing, compilation is bound to fail. 

In the end the user should get a message similar to yours but more focused on the package name, rather than the shared object file. Ex: `missing system dependency HDF5, would you like to install it ? (Yes/no)`. After all, pip's job is to automate and make installation of packages easier. 
(Ofcourse pip may not want to do the job of apt-get, but that's another discussion)

I would recommend leaving the error message as it is for now.

**Comment by takluyver** [comment]
> Because the required system dependencies should be declared in the pip package and thus can be checked by pip for availability before compilation is to be attempted. If pip finds out the dependency is missing, compilation is bound to fail.

pip itself doesn't know anything about system dependencies, and isn't likely to any time soon. They work differently on different systems, even different Linux distributions, and you might want to use something like conda instead of a system package manager. Or even build HDF5 from source manually. It's a massive headache which pip absolutely doesn't want to get into - there are plenty of headaches in packaging already.

So the bit that checks for libhdf5 is h5py's own `setup.py` script, when pip runs it to compile h5py. That's what's already giving you the error message about `libhdf5.so`. We could make that error message a bit more informative - that's what @tacaswell is suggesting. But I don't think we should be trying to run system-level packaging tools if HDF5 is missing.

**Comment by gswebspace** [comment]
Hi @takluyver ! 

Considering the behaviour of pip, and complexity of various linux distros, it makes sense that writing your own `setup.py` becomes necessary.

If the message can say "HDF5 not found. Please install the same using your system package manager"  it would make it much more clear for noobs like me.

We can consider this problem resolved as the issue does not arise within h5py.

**Comment by takluyver** [comment]
Great. Do you want to make a pull request? The bit of code where the error is produced is here:

https://github.com/h5py/h5py/blob/21cd476caf4d0645770722245dab22aabd8f1853/setup_configure.py#L237-L239

I think we should make sure the original error message (coming from ctypes) is still shown, because it might have more detailed information. But we can print an extra message pointing to the likely solution.

**Comment by gswebspace** [comment]
PR #1469 created.

**Comment by takluyver** [comment]
#1469 was merged - closing this.

**Comment by rachmadaniHaryono** [comment]
i'm on ubuntu 21.10 and there is no `libhdf5-100`. but `libhdf5-dev` is already enough

```shell
> agi libhdf5-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  hdf5-helpers libaec-dev libaec0 libhdf5-103-1 libhdf5-cpp-103-1 libhdf5-fortran-102 libhdf5-hl-100 libhdf5-hl-cpp-100 libhdf5-hl-fortran-100 libsz2
Suggested packages:
  libhdf5-doc
The following NEW packages will be installed:
  hdf5-helpers libaec-dev libaec0 libhdf5-103-1 libhdf5-cpp-103-1 libhdf5-dev libhdf5-fortran-102 libhdf5-hl-100 libhdf5-hl-cpp-100 libhdf5-hl-fortran-100 libsz2
```
