### ISSUE TITLE
Blosc resulting in *error* cells

### ISSUE THREAD

**Issue by seanngpack** [h5py/h5py#1463]
To assist reproducing bugs, please include the following:
 * Operating System: Windows 10 and macOS Catalina
 * Python version: 3.7.4
 * Where Python was acquired: python website on windows, brew on Mac
 * h5py version: 2.10.0
 * HDF5 version 1.10.4

I'm writing pandas data frames (read from csv files) to hdf5 files and would like to use Blosc compression. However, when exported every cell says *error* instead of the correct value.
Here is an example of a small set:

| col1 | col2 |
| 1 | 1.2|
| 2 |1.1 |
| 3 | 1.4 |

| col1 | col2 |
| *error* |*error*|
| *error* |*error* |
| *error* | *error* |

example of code:

```
hdf = pd.HDFStore('./notebooks/example.h5', complib='blosc', complevel=5)
chunksize = 10000
tp = pd.read_csv('./notebooks/example.csv',
                 comment='#', chunksize=chunksize)

df = pd.concat(tp)

hdf.put('DF1', df1, format='table', data_columns=True, )
```

**Comment by tacaswell** [comment]
Can you reproduce this without pandas?

**Comment by takluyver** [comment]
As far as I know, pandas' HDFstore uses pytables, not h5py. So it's not clear there's anything for us to fix here.

**Comment by takluyver** [comment]
Closing as I still think my guess that this is not related to h5py is right. We can always reopen it if we establish otherwise.
