### ISSUE TITLE
h5py not playing nicely with subprocess and mpirun

### ISSUE THREAD

**Issue by rlaboiss** [h5py/h5py#1467]
[N.B.: I [have reported](https://groups.google.com/forum/#!topic/h5py/OTF12wyJqgU) the problem below in the h5py mailing list.]

I have stumbled upon a bug when using h5py in a Python script which uses subprocess to run a command through mpirun. The [ZIP file](https://github.com/h5py/h5py/files/3978345/h5py-mpirun-subprocess-bug.zip) attached to the current message contains a demonstration of the bug. In this ZIP archive, there is a C++ file (mpi_hello_world.cc) that uses OpenMPI and can be run through mpirun from the command line without problems (mpirun -n 2 ./mpi_hello_world).

The ZIP file contains also a Python script (bugtest.py) that uses the subprocess module to run 'mpirun -n 2 ./mpi_hello_world'.  That works fine, provided that the h5py module is not imported, in which case the script fails. Notice that the whole code has nothing to do whatsoever with h5py.

Here is the recipe for reproducing this bug:

```
    $ unzip h5py-mpirun-subprocess-bug.zip
    $ cd h5py-mpirun-subprocess-bug
    $ make
    mpic++ mpi_hello_world.cc -o mpi_hello_world
    mpirun -n 2 ./mpi_hello_world
    Hello world, rank 0 out of 2 processors
    Hello world, rank 1 out of 2 processors
    python3 bugtest.py
    stdout =  b'Hello world, rank 0 out of 2 processors\nHello world, rank 1 out of 2 processors\n'
    stderr =  b''
    return code =  0
    python3 bugtest.py import-h5py
    stdout =  b''
    stderr =  b''
    return code =  1
```

I did the test in a Debian testing (bullseye) system with : 

-  Python 3.7.5
- h5py 2.10.0
- HDF5 1.10.4
- libopenmpi-dev 4.0.2.

**Comment by takluyver** [comment]
Hi @rlaboiss - are you installing h5py from a Debian package? It appears that Debian recently decided to build h5py against OpenMPI by default, which causes various issues:

- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944192
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944769
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944617

I would guess that what you're seeing is another symptom of this, although I don't know enough about MPI to understand exactly how it would happen.

It's somewhat unfortunate that AIUI merely loading mpi4py calls some MPI initialisation.

**Comment by rlaboiss** [comment]
Thanks for the suggestion @takluyver, Indeed the problem comes from the Debian package python3-h5py, version 2.10.0, in Debian testing.  When I downgrade to 2.8.0 (the version in Debian stable. The problem disappears.
