### ISSUE TITLE
virtual dataset gets created with dtype=float32

### ISSUE THREAD

**Issue by asmeurer** [h5py/h5py#1474]
```
>>> print(h5py.version.info)
Summary of the h5py configuration
---------------------------------

h5py    2.10.0
HDF5    1.10.5
Python  3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 15:43:19)
[Clang 4.0.1 (tags/RELEASE_401/final)]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.16.5

```

If you create a VirtualLayout with dtype=None and then create a virtual dataset out of it, the dtype of the dataset becomes float32. 
 
```py
>>> import h5py
>>> f = h5py.File('test.hdf5', 'w')
>>> import numpy as np
>>> data = np.ones(10)
>>> data.dtype
dtype('float64')
>>> f['data'] = data
>>> vs = h5py.VirtualSource(f['data'])
>>> vl = h5py.VirtualLayout((10,))
>>> vl[0:10] = vs
>>> f.create_virtual_dataset('virtual_data', vl)
<HDF5 dataset "virtual_data": shape (10,), type "<f4">
>>> f['virtual_data'].dtype
dtype('<f4')
>>> vs.dtype
dtype('<f8')
>>> print(vl.dtype)
None
```

I would expect the dtype to either default to be the same as the source, or, if that is not possible (it seems like it might not be from the way the API works), make the dtype a required argument. At the very least, I would expect the default dtype to be float64, since that is the default dtype used by h5py when creating a new dataset. 

If you specify the dtype it works as expected:

```py
>>> vl = h5py.VirtualLayout((10,), dtype=np.float64)
>>> vl[0:10] = vs
>>> f.create_virtual_dataset('virtual_data2', vl)
<HDF5 dataset "virtual_data2": shape (10,), type "<f8">
>>> f['virtual_data2'].dtype
dtype('<f8')
```

CC @scopatz

**Comment by takluyver** [comment]
> I would expect the default dtype to be float64, since that is the default dtype used by h5py when creating a new dataset.

This depends how you do it. If I create an empty dataset with no data, the default is float32; I think this is where I copied from for virtual datasets.

```
In [6]: ds = f.create_dataset('a', (10,))                                       

In [7]: ds                                                                      
Out[7]: <HDF5 dataset "a": shape (10,), type "<f4">
```

Whereas I guess you tried creating a dataset from a list of floats, which gets float64 when we convert it to a numpy array:

```
In [16]: f['d'] = [1., 2., 3.]                                                  

In [17]: f['d']                                                                 
Out[17]: <HDF5 dataset "d": shape (3,), type "<f8">
```

It seems reasonable to make this more consistent, one way or another. My feeling is that taking the dtype automatically from the first source would be trying to be a bit too clever, but I'd be happy with either aligning the defaults or requiring the dtype to be specified.

**Comment by asmeurer** [comment]
> If I create an empty dataset with no data, the default is float32; I think this is where I copied from for virtual datasets.

Oh I hadn't noticed this. I thought it was float64. 

> but I'd be happy with either aligning the defaults or requiring the dtype to be specified.

I didn't even realize at first that the dtype of a virtual dataset could be different from the source. To me making it required makes the most sense. I would also be equally surprised if an int64 dataset got created as float64 in the virtual dataset if I never specified float.

**Comment by takluyver** [comment]
I'm OK with requiring it when creating virtual datasets for h5py 3.0.

**Comment by takluyver** [comment]
For a while I was leaning towards dtype-from-first-source. I suspect that's the obvious right thing 90% of the time. But I've changed my mind again, because:

- You can create a virtual dataset before the source data exists
- Even if the data exists, we don't currently open the source files & datasets if you pass names, and it might be slow to do so
- Something that works with 1, 2, 3... sources should also work with 0. I'm not sure it does the right thing at the moment, but relying on the first source definitely won't.

So I'm back to thinking that `h5py.VirtualLayout` should require dtype to be specified.
