### ISSUE TITLE
Unspecified error in H5Dget_storage_size (return value ==0)

### ISSUE THREAD

**Issue by ajelenak** [h5py/h5py#1475]
`H5Dget_storage_size()` correctly reports zero byte size for contiguous HDF5 datasets that were created but with no data written to their files. H5py, however, interprets return value of zero as an error code. The function's description page at the HDF [portal](https://portal.hdfgroup.org/display/HDF5/H5D_GET_STORAGE_SIZE) states:

> Note that `H5D_GET_STORAGE_SIZE` does not differentiate between 0 (zero), the value returned for the storage size of a dataset with no stored values, and 0 (zero), the value returned to indicate an error.

#### Proposed solution

Modify `DatasetID.get_storage_size()` method:
```python
    def get_storage_size(self):
        """ () => LONG storage_size

            Determine the amount of file space required for a dataset.  Note
            this only counts the space which has actually been allocated; it
            may even be zero.
        """
        cdef haddr_t offset
        offset = H5Dget_offset(self.id)
        if offset == HADDR_UNDEF:
            return 0
        else:
            return H5Dget_storage_size(self.id)
```
`H5Dget_offset()` is guaranteed to return `HADDR_UNDEF` for such HDF5 datasets and this can be used to avoid calling `H5Dget_storage_size()`.

#### h5py configuration
```
h5py    2.10.0
HDF5    1.10.6
Python  3.8.1 (default, Jan  5 2020, 21:31:55) [Clang 9.1.0 (clang-902.0.39.2)]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.18.1
```

**Comment by takluyver** [comment]
Thanks for reporting, that's a frustrating ambiguity.

Unfortunately, checking `H5Dget_offset()` has other issues - that only works for contiguous datasets, and returns `HADDR_UNDEF` for all other layout types. But maybe we can use [H5Dget_space_status](https://portal.hdfgroup.org/display/HDF5/H5D_GET_SPACE_STATUS) instead to check if space has been allocated for the dataset. Do you want to make a PR?

Also, check what happens in the corner case of a zero-size dataset, where it doesn't need any space to store data.

**Comment by ajelenak** [comment]
I sincerely appologize for not following through with this sooner but hope we can do it quickly now.

Unfortunately, there does not seem to be a single HDF5 function that can help here. Because `H5Dget_strorage_size()` is applicable to both contiguous and chunked datasets, below is my second approach:

```python
    def get_storage_size(self):
        """ () => LONG storage_size

            Report the size of storage, in bytes, that is allocated in the
            file for the dataset's raw data. The reported amount is the storage
            allocated in the written file, which will typically differ from the
            space required to hold a dataset in working memory (any associated
            HDF5 metadata is excluded).

            For contiguous datasets, the returned size equals the current
            allocated size of the raw data. For unfiltered chunked datasets, the
            returned size is the number of allocated chunks times the chunk
            size. For filtered chunked datasets, the returned size is the space
            required to store the filtered data.
        """
        cdef int layout

        layout = self.get_create_plist().get_layout()
        if layout == H5D_CONTIGUOUS:
            if self.get_offset() == <haddr_t>HADDR_UNDEF:
                return 0
        elif layout == H5D_CHUNKED:
            if self.get_num_chunks() == 0:
                return 0
        else:
            raise ValueError('Storage size not available for compact or '
                             'virtual datasets')

        return H5Dget_storage_size(self.id)
```

I know that h5py low-level methods should be kept simple. Perhaps the `get_storage_size()` method should be left unchanged then and its use be delegated to either high-level API or user code.

**Comment by takluyver** [comment]
Thanks, and no problem about putting it on hold for a while.

I still think that `get_space_status()` might be a better option if it works; something like this:

```python
if self.get_space_status() == SPACE_STATUS_NOT_ALLOCATED:
    return 0

return H5Dget_storage_size(self.id)
```

Alternatively, we could special case the generated wrapper function which is producing the error. At present, h5py generates a wrapper which does error checking, including a fallback for when a return value indicates an error but HDF5 doesn't have error details:

```cython
cdef hsize_t H5Dget_storage_size(hid_t dset_id) except <hsize_t>0:
    cdef hsize_t r
    set_default_error_handler()
    r = _hdf5.H5Dget_storage_size(dset_id)
    if r==0:
        if set_exception():
            return <hsize_t>0
        else:
            raise RuntimeError("Unspecified error in H5Dget_storage_size (return value ==0)")
    return r
```

We could special case this function to skip the defensive `else:` branch there, so it only raises an error if HDF5 has error details, and otherwise treats 0 as valid.

**Comment by ajelenak** [comment]
`get_space_status()` cannot help here. (I am an HDF Group employee and had consulted with the HDF5 library experts.) Generating  a special wrapper for the `H5Dget_storage_size()` C function seems like the best approach to resolve this particular issue and keep everything else unchanged.

I would also update the `get_storage_size()` method's docstring as in my previous comment since it explains better what the return values may represent.

**Comment by takluyver** [comment]
Thanks. I'd be interested in knowing why `get_space_status()` can't help, because it looks like what we need. But I agree that special casing the binding is probably a better approach, so that's just academic interest.
