### ISSUE TITLE
Test failures with HDF5 1.10.6

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#1492]
Two tests recently started failing in the CI. It looks like this coincides with those builds being switched from HDF5 1.10.5 to 1.10.6. It's entirely possible that this change will affect other platforms; I think the Mac builds are the first to get the new HDF5 version, as the others either build a specified HDF5 version, or get it from Ubuntu repos.

```
_______________________ TestRegionRefs.test_empty_region _______________________

self = <h5py.tests.test_dataset.TestRegionRefs testMethod=test_empty_region>

    def test_empty_region(self):
        ref = self.dset.regionref[:0]
        out = self.dset[ref]
>       assert out.size == 0
E       AssertionError: assert 10000 == 0
E        +  where 10000 = array([[   0,    1,    2, ...,   97,   98,   99],\n       [ 100,  101,  102, ...,  197,  198,  199],\n       [ 200,  201...9797, 9798, 9799],\n       [9800, 9801, 9802, ..., 9897, 9898, 9899],\n       [9900, 9901, 9902, ..., 9997, 9998, 9999]]).size

py37-test-deps/lib/python3.7/site-packages/h5py/tests/test_dataset.py:1174: AssertionError
______________________ TestRegionRefs.test_scalar_dataset ______________________

self = <h5py.tests.test_dataset.TestRegionRefs testMethod=test_scalar_dataset>

    def test_scalar_dataset(self):
        ds = self.f.create_dataset("scalar", data=1.0, dtype='f4')
        sid = h5py.h5s.create(h5py.h5s.SCALAR)
    
        # Deselected
        sid.select_none()
        ref = h5py.h5r.create(ds.id, b'.', h5py.h5r.DATASET_REGION, sid)
>       assert ds[ref] == h5py.Empty(np.dtype('f4'))
E       AssertionError: assert array(1., dtype=float32) == Empty(dtype=dtype('float32'))
E        +  where Empty(dtype=dtype('float32')) = <class 'h5py._hl.base.Empty'>(dtype('float32'))
E        +    where <class 'h5py._hl.base.Empty'> = h5py.Empty
E        +    and   dtype('float32') = <class 'numpy.dtype'>('f4')
E        +      where <class 'numpy.dtype'> = np.dtype

py37-test-deps/lib/python3.7/site-packages/h5py/tests/test_dataset.py:1184: AssertionError
```

**Comment by takluyver** [comment]
I can reproduce these failures with HDF5 1.10.6 on Linux.

**Comment by takluyver** [comment]
My suspicion is that this is a bug in HDF5, but I'd like to confirm that before adding a skip for those tests.

I made a forum post about it: https://forum.hdfgroup.org/t/region-reference-to-zero-size-region-broken-in-hdf5-1-10-6/6649

**Comment by takluyver** [comment]
I've opened #1497 to try to get this out of the way for h5py development, but there's a frustrating lack of any response on the HDF forum.

**Comment by epourmal** [comment]
We confirmed that it is a bug that was introduced between 1.10.5 and 1.10.6 releases. The issue is not present in 1.12.0. Please see comments to [HDFFV-11055]( https://jira.hdfgroup.org/browse/HDFFV-11055. I created new issue [HDFFV-11067]( https://jira.hdfgroup.org/browse/HDFFV-11067). We will try to address it in the next maintenance release this May-June.

**Comment by takluyver** [comment]
Thanks Elena! I can't see [issue 110677](https://jira.hdfgroup.org/browse/HDFFV-11067) at the moment - can I ask you to mark it as community visible?

**Comment by epourmal** [comment]
Sorry! Fixed.

**Comment by takluyver** [comment]
Thanks, I see it now :-)

**Comment by epourmal** [comment]
[HDFFV-110677](https://jira.hdfgroup.org/browse/HDFFV-11067) was resolved. The fix is in 1_10 branch.

**Comment by takluyver** [comment]
Excellent, thanks. Then I think we can close this issue.
