### ISSUE TITLE
lock file is handled differently on Windows vs Linux

### ISSUE THREAD

**Issue by annehulsey** [h5py/h5py#1493]
I'm getting different behavior with h5py and pandas when I run it on Windows vs Linux. On Windows, I can have a file open using h5py and still read and write to it via pandas. However, on Linux, I get an error that pandas couldn't open/create the file because it could not get a lock on the file. Below is the test code to reproduce the behavior. All three portions work on Windows and don't work on Linux. 

Can you provide insight as to whether it is a Windows versus Linux issue or whether it is due to the version of hp5y that I am using on each system? I would like to find a way to get this working on Linux, otherwise I will have to re-structure a lot of my codes.

    import h5py
    import pandas as pd
    import numpy as np

    filename = 'test.h5'

(test writing to the file using 'w' mode)

    with h5py.File(filename, 'w') as hf:
         pd1 = pd.DataFrame(np.random.rand(10,5))
         key = 'pd1'
         pd1.to_hdf(filename, key=key)

(test reading from and writing to the file using 'r+' mode)

    with h5py.File(filename, 'r+') as hf:
    
        key = 'pd1'
        p1 = pd.read_hdf(filename, key=key)
    
        pd2 = pd.DataFrame(np.random.rand(10,5))
        key = 'pd2'
        pd2.to_hdf(filename, key=key)

(test reading from the file using 'r' mode)

    with h5py.File(filename, 'r') as hf:
    
        key = 'pd2'
       p2 = pd.read_hdf(filename, key=key)

Windows Desktop:
h5py    2.9.0
HDF5    1.10.4
Python  3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.16.5

Linux Server:
h5py    2.10.0
HDF5    1.10.4
Python  3.6.1 (default, Apr 27 2017, 10:57:56) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.18.1

**Comment by takluyver** [comment]
In general, HDF5 locks the file when you write it, so only one writer or several readers can have it open at a time. So it's normal that if one thing has the file open for writing, nothing else can open it.

This normally applies to different processes, though. I'd guess that on Windows, h5py and pandas (which uses pytables internally) are using the same underlying HDF5 library, so they can 'share' the open file (though how well this works depends on whether the Python libraries expect a file to change under them). On Linux, you've probably got two separate HDF5 libraries, so it treats them as two separate things trying to open the file. This will depend how you installed things.

In most cases, the best option is probably: don't do both at the same time. Write the file and close it, then open it in the other library.

**Comment by annehulsey** [comment]
Thanks for the explanation. I ended up coming to the same conclusions and reorganized all my functions.
