### ISSUE TITLE
Document that high-level objects' truth value means valid ID

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#1499]
This is a useful feature, and it's clear in the code that it's intended - `bool(hlobj)` wraps `bool(hlobj.id)`:

https://github.com/h5py/h5py/blob/034268471163d720f9d424c16c3ab7080d61cd03/h5py/_hl/base.py#L285-L287

and `bool(id)` wraps `id.valid`:

https://github.com/h5py/h5py/blob/034268471163d720f9d424c16c3ab7080d61cd03/h5py/_objects.pyx#L230-L231

But I can't see it documented anywhere.

**Comment by cydanil** [comment]
I'd like to work on this: it seems to tie in with what was documented in #1529 (but I only saw it now). I think it would make sense to add a brief sentence in each entry documenting this.

**Comment by takluyver** [comment]
I guess this illustrates the difficulty of searching for information on this. This is pretty much a duplicate of #1363, but apparently I didn't find that one when writing this. Anyway, if you think there's another place that this should be mentioned, go for it - otherwise, I'm happy enough to say #1529 fixed it.

**Comment by cydanil** [comment]
I thought about it, and I added a short paragraph to explain it, but the result was a bit gauche in the document. I now think it's okay as it is.

**Comment by takluyver** [comment]
Ok, thanks for looking into it.
