### ISSUE TITLE
Get the python File from h5py File

### ISSUE THREAD

**Issue by GTimothee** [h5py/h5py#1501]
My question is very simple: I need to access st_ino and st_dev from the actual hdf5 file for sanity check but I can't find a way to access it. Is there an actual python File object inside an h5py File object? In either case, how can I access those attributes?

Thank you for your help

Edit: I am supposed to access it from the stat object like this: 
`stat = os.fstat(file_pointer.fileno())`

**Comment by tacaswell** [comment]
No, under normal usage if you pass a filename into `h5py.File` the file actually gets opened by libhdf and is opaque to us at the python level.  That said, there may be a way to get libhdf5 to give you that information, but I don't know it off the top of my head.

You can open the file on python and pass the python file object into h5py, but I suspect (but have not tested) that will result in a performance penalty.

**Comment by GTimothee** [comment]
Oh OK thank you for your answer. Is there any simple mean to find if two h5py File objects are pointing to the same hdf5 file then ?

**Comment by takluyver** [comment]
It looks like comparing `f1 == f2` tells you if two file objects refer to the same file. This is ultimately using `f.id.fileno` among other information. This works in a quick interactive test with opening the same file twice, but there may be corner cases where it goes wrong.

In typical use cases, you can get the file descriptor (to pass to `os.fstat()`) with [`file.id.get_vfd_handle()`](http://api.h5py.org/h5f.html#h5py.h5f.FileID.get_vfd_handle). With some [file drivers](http://docs.h5py.org/en/stable/high/file.html#file-drivers), the HDF5 'file' can be several real files, in which case you have to specify which file you mean.

HDF5 has various ways for one file to reference data in another. So knowing which file you've opened doesn't necessarily tell you where the data you're accessing is. But if this is for a specific use case and you know how the files are created, that may well not be a problem.

**Comment by GTimothee** [comment]
I see, thank you very much for your help. I mark this issue as closed and in the meantime I will do some tests. I may open the issue again if I have some more trouble. 

Thank you
