### ISSUE TITLE
Conda has no h5py-2.10 release for Python 3.5

### ISSUE THREAD

**Issue by eric-wieser** [h5py/h5py#1511]
It looks like 2.10 is supposed to support Python 3.5, but conda does not appear to have any builds that work below Python 3.6.

* https://anaconda.org/conda-forge/h5py/files?version=2.10.0
* https://anaconda.org/anaconda/h5py/files?version=2.10.0

**Comment by scopatz** [comment]
Yeah, I think that conda v2.x is no loger supported

**Comment by eric-wieser** [comment]
I'm not sure what you mean by that. Are you referring to versions of conda? Versions of h5py published on conda?

**Comment by scopatz** [comment]
Oh yeah, I thought you were talking about conda v2.10.  For h5py v2.10 on Python 3.5 on conda-forge, you just need to modify the `conda-forge.yaml` file to add another python version https://conda-forge.org/docs/maintainer/conda_forge_yml.html#min-py-ver

**Comment by eric-wieser** [comment]
You mean in this file? https://github.com/conda-forge/h5py-feedstock/blob/master/conda-forge.yml

If that file doesn't specify it, and the current default is `2.7`, why would changing it have an effect?

**Comment by scopatz** [comment]
Sorry, wrong file.  It is `conda_build_config.yaml` that needs to be modified, https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html

**Comment by eric-wieser** [comment]
Modify or create?

**Comment by scopatz** [comment]
In the feedstock, and after the file is modified or created, you will need to do a conda smithy rerender  to generate the new CI files

**Comment by eric-wieser** [comment]
Ah, this file? https://github.com/conda-forge/h5py-feedstock/blob/master/recipe/conda_build_config.yaml

**Comment by scopatz** [comment]
yep! that one!

**Comment by eric-wieser** [comment]
Looks like conda-forge dropped support for python 3.5:  conda-forge/conda-forge-pinning-feedstock#127

**Comment by scopatz** [comment]
Yes, conda-forge did by default, but you can still build packages for it

**Comment by takluyver** [comment]
Closing as this is about how conda-forge builds h5py, not h5py itself. But feel free to keep using the comments to discuss it if necessary.
