### ISSUE TITLE
ENH: Don't use non-portable array.array in cython

### ISSUE THREAD

**Issue by mattip** [h5py/h5py#1514]
It turns out there is no clean C interface to the `array.array` object in Python. Cython reproduces the CPython internal `arrayobject` in its [`array.pxd`](https://github.com/cython/cython/blob/master/Cython/Includes/cpython/array.pxd#L2) code, but this does not work on other implementations (like PyPy). Cython's recommendation in this case, if one wishes to be portable, is to [avoid its use](https://github.com/cython/cython/issues/1818). In general, [importing from CPython](https://github.com/h5py/h5py/blob/master/h5py/h5d.pyx#L21) will cause protability problems.

Would you be open to a PR to change the [use of `array.array`](https://github.com/h5py/h5py/blob/master/h5py/h5d.pyx#L481) to a `bytearray`?

**Comment by scopatz** [comment]
Hi @mattip - I think we'd be open to PR with this change.  We'd like to see the code at least, and maybe there is a way to conditionally use `array.array` in CPython for the moment and `bytearray` in PyPy if there end up being performance issues
