### ISSUE TITLE
Nested dimension scales: Unspecified error in H5DSattach_scale

### ISSUE THREAD

**Issue by jhofinger** [h5py/h5py#1523]
Trying to execute the following code
```
f = h5py.File("testfile.hdf5", "w")
scale1 = f.create_dataset("test", data=(1, 2, 3))
scale1.make_scale()
scale2 = f.create_dataset("test2", data=np.zeros((3, 3)))
scale2.dims[0].attach_scale(scale1)
scale2.make_scale()
```
yields the following error:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-27-401f8549cbbe> in <module>
      4 scale2 = f.create_dataset("test2", data=np.zeros((3, 3)))
      5 scale2.dims[0].attach_scale(scale1)
----> 6 scale2.make_scale()

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

c:\users\jonat\appdata\local\programs\python\python37\lib\site-packages\h5py\_hl\dataset.py in make_scale(self, name)
    839         You can optionally pass a name to associate with this scale.
    840         """
--> 841         h5ds.set_scale(self._id, self._e(name))

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\h5ds.pyx in h5py.h5ds.set_scale()

h5py\defs.pyx in h5py.defs.H5DSset_scale()

RuntimeError: Unspecified error in H5DSset_scale (return value <0)
```

The [documentation](http://docs.h5py.org/en/latest/high/dataset.html#creating-datasets) says:

> A dimension scale is simply another HDF5 dataset.

It doesn't say that this other dataset mustn't have a dimension scale attached. Is this a bug in h5py or a limitation of HDF5? In the latter case, the documentation should be updated to include this information.

Summary of the h5py configuration
---------------------------------
h5py    2.10.0
HDF5    1.10.5
Python  3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.16.1

**Comment by takluyver** [comment]
The HDF5 [docs for H5DSset_scale](https://confluence.hdfgroup.org/display/HDF5/H5DS_SET_SCALE) list error cases including

> If dsid is a dataset which already has dimension scales

A PR to clarify this limtation in the h5py docs would be welcome.
