### ISSUE TITLE
Custom HDF5 plugin can't find libhdf5.so when using h5py

### ISSUE THREAD

**Issue by mraspaud** [h5py/h5py#1537]
In preparation for a future satellite mission, the provider of the data has implemented a compression method based on charls as a plugin to HDF5, FCIDECOMP, last filter on this page: https://support.hdfgroup.org/services/filters.html

The building and using of this filter works as expected with h5dump:
```
❯ h5dump -d effective_radiance sample.nc
HDF5 "sample.nc" {
DATASET "effective_radiance" {
   DATATYPE  H5T_STD_I16LE
   DATASPACE  SIMPLE { ( 60, 30 ) / ( 60, 30 ) }
   DATA {
   (0,0): 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
   (0,19): 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
...
```
(here is the test file for completeness: [sample.zip](https://github.com/h5py/h5py/files/4508049/sample.zip), 1.3kB)

However, trying to achieve the same thing from h5py leads to an error:
```python
>>> import h5py
>>> h5f = h5py.File('sample.nc', mode='r')
>>> h5f['effective_radiance'][:]
```
```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/a001673/miniconda3/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 651, in __getitem__
    return self._fast_reader.read(args)
  File "h5py/_reader.pyx", line 243, in h5py._reader.Reader.read
OSError: Can't read data (can't dlopen:/home/a001673/miniconda3/envs/fcidecomp3/hdf5/lib/plugin/libH5Zjpegls.so: undefined symbol: H5Pmodify_filter)
```
The HDF_PLUGIN_PATH and LD_LIBRARY_PATH are setup correctly to:
```shell
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib
export HDF5_PLUGIN_PATH=:$CONDA_PREFIX/hdf5/lib/plugin
```
again, as h5dump has no issue reading the file.
(The filter FCIDECOMP was built by me as a conda package)

Running `nm -D` on `libH5Zjpegls.so` lists of course `H5Pmodify_filter` as undefined, but it is present in `libhdf5.so` which itself is located on the defined `LD_LIBRARY_PATH`.

So, I don't know how to go further in the debugging here, I would need some assistance :)
1. Have custom filters been tested and reported to work with h5py ?
2. Is there some `LD_LIBRARY_PATH` magic happening in the h5py code, and in this case where can I find it ?
3. Any other idea of things I could try ?

To assist reproducing bugs, please include the following:
 * Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 16.04.2 LTS, CentOS 7)
RHEL8
 * Python version (e.g. 2.7, 3.5)
3.7.4
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows)
Miniconda
 * h5py version (e.g. 2.6)
Latest from conda-forge (2.10.0), then github's master branch, fetched one hour ago
 * HDF5 version (e.g. 1.8.17)
1.10.6_nompi, from conda-forge

```
Summary of the h5py configuration
---------------------------------

h5py    2.10.0
HDF5    1.10.6
Python  3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.18.1
```

**Comment by vasole** [comment]
I can only try point 3...

Are you sure the filter was compiled using the same hdf5 library as h5py was built against?

If so, I had once a similar issue problem compiling an extension module that was traced back to having used different compilers. I had to "conda install gcc" prior to build the module to make sure there were no undefined symbols at run time. Make sure you build your filter in your conda environment with the conda gcc installed to eliminate that possibility.

**Comment by mraspaud** [comment]
@vasole thanks for the hints! so you mean that you rebuilt the h5py conda package, right?

**Comment by vasole** [comment]
I was more thinking about rebuilding the filter plugin in the conda environment.

**Comment by mraspaud** [comment]
ok, I'm testing this now, after having installed `gcc_linux-64`

**Comment by mraspaud** [comment]
Alright, not luck unfortunately: I rebuilt the filter package in the environment containing h5py and hdf5, and even required h5py in the build requirements to make sure the versions were the same, but still the same error in the end.

**Comment by vasole** [comment]
Sorry no more ideas.

I just wanted to mention that I am really curious about FCIDECOMP and JPEG-LS being listed as implementing the same compression in https://support.hdfgroup.org/services/filters.html. Furthermore, and probably irrelevant, the filter ID in your file corresponds to FCIDECOMP but the filter name says JPEG-LS and not FCIDECOMP 

![image](https://user-images.githubusercontent.com/5636251/79849435-c037d500-83c2-11ea-8aeb-c2d1f84acd58.png)

**Comment by mraspaud** [comment]
Indeed, very interesting. I'll take this up with the data provider.

**Comment by vasole** [comment]
To me it is not an h5py issue.

I have tested under windows with the wheel below and it seems to work:

http://ftp.esrf.fr/pub/bliss/hdf5plugin-2.1.3a0-py3-none-win_amd64.whl

If you want to try it (under windows), just install it and ``import hdf5plugin`` prior to open your file.

![image](https://user-images.githubusercontent.com/5636251/79890622-0f502b00-8400-11ea-8e05-627655c1caf6.png)

**Comment by mraspaud** [comment]
I'm confused: hdf5plugin implements the FCIDECOMP filter then ?

**Comment by mraspaud** [comment]
Oh, I don't have access to a windows computer...

**Comment by vasole** [comment]
I put FIDECOMP yesterday on a local branch. I wanted to try the usefulness of a JPEG-LS codec in view of the interest we have on JPEG2000. However I'm still not sure what I did it will be merged.

I will give a try at building it on a linux computer and I will let you know.

**Comment by vasole** [comment]
Please give a try at the following wheel. It is not a finished work (I have no clue about how to compress data with it) but if it allows you to read your files will integrate the development in hdf5plugin:

http://ftp.esrf.fr/pub/bliss/hdf5plugin-2.1.3a0-py2.py3-none-linux_x86_64.whl

The wheel was built on CentOS 7 and not on CentOS 5 but I have tested it on Ubuntu 16.04 LTS and it worked.

**Comment by vasole** [comment]
We have successfully added the support of this filter into hdf5plugin and we have merged it into the master branch. In my opinion this issue is not directly related to h5py.

**Comment by mraspaud** [comment]
@vasole thanks a lot for you work, and sorry for the delay in my answers!
I'm checking it now, but it seems it's failing. I'll open an issue on the hdf5plugin github then.

There is actually a version 1.0.2 of the FCIDECOMP with isn't advertised on the HDF5 website (yet?): ftp://ftp.eumetsat.int/pub/OPS/out/test-data/Test-data-for-External-Users/MTG_FCI_Test-Data/FCI_Decompression_Software_V1.0.2/

I'd like to ping @erget and @ameraner which are on the provider side of this plugin.

I'm still not sure why h5py isn't finding the plugin I compiled, while h5dump can, but if you think this is not an h5py issue, feel free to close it.

**Comment by vasole** [comment]
You have to import the hdf5plugin module for it to be used.

Just add ``import hdf5plugin`` to your scripts.

**Comment by vasole** [comment]
You also have to make sure your FCIDECOMP plugin is not already in your HDF5_PLUGIN_PATH. Our module is very conservative and if it finds the user has already registered the plugin via the environmental variable, the plugin is not registered in order to respect user's choice.

**Comment by vasole** [comment]
This should be closed. It is clear this is not an h5py issue and the last release of hdf5plugin supports it.

**Comment by mraspaud** [comment]
@vasole Thank you for fixing the hdf5plugin to support this plugin. I'm ok with closing this issue, I would just like to know if there is some magic involved in hdf5plugin, or if in principle a plugin compiled and installed way I did here should just work with h5py ?

**Comment by takluyver** [comment]
Thanks all, I'm going to close this as it doesn't seem like there's something to fix in h5py.

I'm pretty sure hdf5plugin does have to do something clever to link to the HDF5 library h5py is using. I don't remember all the details, but some of the discussion is on #1315.

**Comment by mraspaud** [comment]
Thanks all for your help!

**Comment by vasole** [comment]
@mraspaud 

A plugin compiled the way you did should work if the whole chain (HDF5 library, h5py, CharLS, FCIDECOMP plugin) is built using the same compiler . The only difficulty I had was that the first version of the plugin sources (the one pointed at by the HDF group) did not have the proper filter ID. Version 1.0.2 had the proper filter ID.
