### ISSUE TITLE
Cannot create attribute with h5py.Empty value

### ISSUE THREAD

**Issue by peterbednar** [h5py/h5py#1540]
Cannot create an attribute with h5py.Empty value. To reproduce run:

```python
import h5py

with h5py.File('test.h5', 'w') as f:
    f.attrs['empty'] = h5py.Empty('f')
```

**Version information:**

h5py    2.10.0
HDF5    1.10.4
Python  3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.15.2

**Complete traceback:**
```
Traceback (most recent call last):
  File "error.py", line 4, in <module>
    f.attrs['empty'] = h5py.Empty('f')
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.7/site-packages/h5py/_hl/attrs.py", line 100, in __setitem__
    self.create(name, data=value)
  File "/usr/local/lib/python3.7/site-packages/h5py/_hl/attrs.py", line 156, in create
    if dtype.subdtype is not None:
AttributeError: 'str' object has no attribute 'subdtype'
```

**Comment by takluyver** [comment]
I think the `Empty()` constructor should normalise its dtype to a numpy dtype object when it's created. This normally just involves doing `dtype = np.dtype(dtype)`.

**Comment by dota17** [comment]
Given that we set dtype to `f` when construct Empty(), then set `dtype = np.dtype('f')` inside, the dtype still has no attribute  `subdtype` in create() in attrs.py. So I think we'd better check it in `create()` method, and set it when it has no subdtype.

**Comment by dota17** [comment]
Oh, I misunderstand, it works.
