### ISSUE TITLE
Bug when nesting vlen_dtype and assigning a list with a single nested array e.g. [array([1,2,3])]

### ISSUE THREAD

**Issue by malpunek** [h5py/h5py#1548]
### What happens
I wanted to store nested vlen arrays of ints. It looks it's working, but breaks when I'm trying to assign a list with a single element (that element being an array).
### Code

```python
import h5py
import numpy as np


with h5py.File("test.hdf5", "w") as f:
    dt = h5py.vlen_dtype(h5py.vlen_dtype(np.dtype("int32")))
    caps = f.create_dataset("show_bug", (10,), dtype=dt)

    caps[0] = []  # OK
    caps[1] = [np.array([1, 2, 3]), np.array([4, 5]), np.array([67, 89, 120, 140])]  # OK
    caps[2] = [np.arange(20), np.arange(10)]  # OK
    caps[3] = [np.array([0, 1, 2, 3]), np.array([])]  # OK
    caps[4] = [np.array([0, 1, 2, 3])]  # Fails
```

### Expected result
One of the two:
  * h5py to work properly (preferred)
  * h5py to spit in my face with an error "You can't nest vlen dtypes" upon creating the dtype, with an additional warning in the docs

### Actual result
Ugly stacktrace:

```
Traceback (most recent call last):
  File "bug.py", line 12, in <module>
    caps[3] = [np.array([0, 1, 2, 3])]  # Fails
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/malpunek/.local/share/virtualenvs/msc-fMydB2_4/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 708, in __setitem__
    self.id.write(mspace, fspace, val, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 222, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 163, in h5py._proxy.dset_rw
  File "h5py/defs.pyx", line 3536, in h5py.defs.H5Tconvert
  File "h5py/_conv.pyx", line 771, in h5py._conv.ndarray2vlen
  File "h5py/_conv.pyx", line 808, in h5py._conv.conv_ndarray2vlen
  File "h5py/defs.pyx", line 3536, in h5py.defs.H5Tconvert
  File "h5py/_conv.pyx", line 753, in h5py._conv.ndarray2vlen
AttributeError: 'int' object has no attribute 'dtype'
```

### Setup data

* Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 16.04.2 LTS, CentOS 7)
    **ArchLinux**
    ```fish
    ~> uname -r
    5.6.12-arch1-1
    ```
* `h5py.version.info` 
    ```
    Summary of the h5py configuration
    ---------------------------------

    h5py    2.10.0
    HDF5    1.10.4
    Python  3.8.2 (default, Apr  8 2020, 14:31:25) 
    [GCC 9.3.0]
    sys.platform    linux
    sys.maxsize     9223372036854775807
    numpy   1.18.4
    ```
* Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows)
    System python (virtualenv via pipenv)
    ```fish
    ~> which python
    /home/malpunek/.local/share/virtualenvs/msc-fMydB2_4/bin/python
    ```

**Comment by vasole** [comment]
Perhaps (unchecked) case 4 would work if instead of writing ``[np.array([0, 1, 2, 3])] `` 
you would write ``[np.array([0, 1, 2, 3]),] `` 
(note the colon after the parenthesis)

**Comment by takluyver** [comment]
Does the same happen if your arrays are the same size, like `[np.arange(3), np.arange(3)]`?

It's expecting something that converts to a numpy object array of arrays, but numpy prefers to make a multidimensional array if possible. Even specifying `dtype=object` creates a 2D object array of integers rather than an array of array objects.

Here's a workaround [from Stackoverflow](https://stackoverflow.com/a/3278340/434217) to force it to make a 1D array of objects:

```python
np.array([None, np.array([0, 1, 2, 3])])[1:]
```

That's ugly, but it's kind of reflecting the reality that HDF5 and especially numpy are really designed around 'rectangular' data, and that's where they work best. Numpy in particular has no real support for 'ragged' arrays, so everything is workarounds.

The [awkward-array](https://github.com/scikit-hep/awkward-array) package has some functionality built on top of h5py for saving ragged arrays as HDF5 datasets, but I don't know how it represents them.

**Comment by malpunek** [comment]
> Does the same happen if your arrays are the same size, like [np.arange(3), np.arange(3)]?

I don't exactly know what you mean. It only happens when I try to insert a list with a single array.

> Here's a workaround from Stackoverflow to force it to make a 1D array of objects:
np.array([None, np.array([0, 1, 2, 3])])[1:]

Yup, it's ugly. It doesn't work but a simple variation does. For future googlers:

```python
import h5py
import numpy as np


with h5py.File("test.hdf5", "w") as f:
    dt = h5py.vlen_dtype(h5py.vlen_dtype(np.dtype("int32")))
    caps = f.create_dataset("show_bug", (10,), dtype=dt)

    caps[0] = [np.array([])]  # FOR SOME REASON THIS IS OK
    caps[1] = [np.array([]), np.array([1, 2, 3]), np.array([4, 5]), np.array([67, 89, 120, 140])]  # OK
    caps[2] = [np.array([]), np.arange(20), np.arange(10)]  # OK
    caps[3] = [np.array([]), np.array([0, 1, 2, 3]),  np.array([])]  # OK
    caps[4] = [np.array([]), np.array([0, 1, 2, 3])]  # OK
```

And then you can operate on `caps[:, 1:]`. Imho that's indeed very hacky & ugly & IF YOU COPY THIS CODE YOU'RE ON YOUR OWN. I ended up splitting my dataset: I stored the heavy rectangular part as hdf5 dataset, and used json for the light variable-length part

> Numpy in particular has no real support for 'ragged' arrays, so everything is workarounds. The [awkward-array](https://github.com/scikit-hep/awkward-array) package has some functionality built on top of h5py for saving ragged arrays as HDF5 datasets.

I think these two sentences should end up in the documentation as a Warning/Note near the vlen dtype part of the docs.

Thanks a lot!

**Comment by takluyver** [comment]
I've marked this as a documentation issue, based on your suggestion. For anyone who wants to tackle it, here's the relevant bit of the docs: http://docs.h5py.org/en/stable/special.html#arbitrary-vlen-data

**Comment by takluyver** [comment]
I've opened #1816 to add a more carefully worded version of my 'everything is workarounds' comment from this discussion.
