### ISSUE TITLE
Single Writer Multiple Reader (SWMR) - Raspberry Pi boards

### ISSUE THREAD

**Issue by markub3327** [h5py/h5py#1550]
Hi, I'm working with the latest version of h5py. I have 3 Raspberry Pi boards and I share h5 file with datasets between boards through NFS v4 service. I'm testing SWMR mode (one of the Raspberry Pi is writing to h5 file and all another are reading from it at the same time).
 
**Screenshot of working process**
<img width="1440" alt="Snímka obrazovky 2020-05-18 o 15 54 37" src="https://user-images.githubusercontent.com/16693449/82222060-13993680-9921-11ea-86e6-113593ae0f13.png">

Can I tell it is an issue or random when it's working? How can I safety share h5 file on network filesystem between Raspberry Pi boards with using NFS (or another network sharing service)? I use this file like a replay buffer.

Here is my code: https://github.com/markub3327/DistributedTwinDelayedDDPG 
(in test_buffer.py I try to read from h5 file)

Thanks.

**Comment by takluyver** [comment]
To be clear, are you seeing a problem? Or are you asking for confirmation that your design should work?

It sounds like you're using the SWMR feature as designed, but I'm not very familiar with it. Be aware that your writer needs to open and set up the file before the readers try to access it.

**Comment by markub3327** [comment]
Yes, I asked for confirmation that my design should work stable, but in the documentation, I read that on NFS it doesn't work and it's working.

I must create for example lock file, that will be removed after the writer finish writing and when readers see the lock file, they don't access the h5 file? After deleting the lock file readers can access it.

**Comment by takluyver** [comment]
Oh, right, I see it:

>  The SWMR feature does not work on network file systems (NFS, SMB/Windows file shares, and so on) since write ordering may not be preserved on those systems.

-- [HDF5 SWMR user's guide](https://support.hdfgroup.org/HDF5/docNewFeatures/SWMR/HDF5_SWMR_Users_Guide.pdf)

I doubt HDF5 is checking what filesystem a file is on, so it will probably try to use SWMR mode regardless. The ordering issues could be very rare, or they could depend on the details of how you access the file, or how busy the network is, or some other factor I haven't thought of. It's unsupported, so don't be surprised if it breaks, but that doesn't mean it will fail all the time.

**Comment by markub3327** [comment]
Okej, but how I solve this sharing problem between Raspberry Pi boards? How can I share an h5 file between devices? Exists something better like SWMR? I need to create and write to an h5 file from one device and read from it from other devices in the local network concurrently.

dataset.refresh() is the best solution for my problem because readers can refresh the content of the file and readers aren't wasting time for opening and closing the writer's file.

**Comment by vasole** [comment]
Since SWMR is warranted to work on NFS, you can use the this approach:

a) the reader processes run with HDF5_USE_FILE_LOCKING=FALSE and open the file explicitly in read mode (some h5py versions defaulted to append mode) while

b) the writer process uses the default locking (equivalent to HDF5_USE_FILE_LOCKING=TRUE). 

That way you are sure never to corrupt the file because only one process can access the file for writing while the readers will still be able to access the file. You might need to close and open to refresh the file contents for the readers.

**Comment by vasole** [comment]
Sorry, the NOT was missing.

**Comment by markub3327** [comment]
Okej thanks a lot. I try this method and reply whether it works.

**Comment by vasole** [comment]
I use something like this in the readers:

    if "HDF5_USE_FILE_LOCKING" not in os.environ:
        if "h5py" in sys.modules:
             _logger.warning("h5py already imported")
        os.environ["HDF5_USE_FILE_LOCKING"] = "FALSE"
        _logger.info("%s set to %s" % ("HDF5_USE_FILE_LOCKING",
                                       os.environ["HDF5_USE_FILE_LOCKING"]))

**Comment by takluyver** [comment]
How far is that actually guaranteed to work? I'd assume that it's OK from the writer side, but the readers may throw random errors or potentially even crash, if they attempt to read something which hasn't been completely written. Of course, it may work 99% of the time in practice, but I'd be wary of relying on a solution that just skips the file locks.

I think reliably tracking changes to a file over NFS is just hard in general. Even SQLite has problems on NFS, and that has a much stronger focus on concurrent access than HDF5 does.

Depending on your use case, it might make more sense to look at ways to pass the data around that don't rely on the filesystem. E.g. using ZMQ PUB/SUB sockets to send it out to the receivers, or some kind of a database server if they need to request non-current data.

**Comment by vasole** [comment]
If HDF5 updates its metadata after having written the data you can be reading part of everything written but not crashing. If you are allocating a certain amount of memory and then you blindly read the whole dataset into the allocated memory then you will certainly run into troubles. 

In any case, you might be already facing that situation (what is written might not be what is reported) if using NFS.
 
All what I can say is that

- we are not having issues with it and 
- the possibility for the writer to change the layout of the file largely compensates eventual additional work (if any) at the readers side.

**Comment by markub3327** [comment]
The database server is not a good solution, because I work with big matrics of float numbers and DB is slower than the file system. 

It's complicated for me because I'm working on a deep neural network and I don't know about network technology of sharing data. I must use a complete solution provided by a third-party. I read about h5 that it is used to save big matrices in Keras framework and datasets too. I thought that it is a good choice for me.

**Comment by markub3327** [comment]
> Since SWMR is NOT warranted to work on NFS, you can use the this approach:
> 
> a) the reader processes run with HDF5_USE_FILE_LOCKING=FALSE and open the file explicitly in read mode (some h5py versions defaulted to append mode) while
> 
> b) the writer process uses the default locking (equivalent to HDF5_USE_FILE_LOCKING=TRUE).
> 
> That way you are sure never to corrupt the file because only one process can access the file for writing while the readers will still be able to access the file. You might need to close and open to refresh the file contents for the readers.

I try it without SWMR and I get an error:
> HDF5_USE_FILE_LOCKING set to FALSE
> Error reading: Unable to open file (file is already open for write (may use 'h5clear file' to clear file consistency flags))

**Comment by vasole** [comment]
You have an indentation problem on lines 24 and 25

**Comment by markub3327** [comment]
> You have an indentation problem on lines 24 and 25

No, it isn't a problem with indentation, but I get an error when trying to open the file for reading.

<img width="1097" alt="Snímka obrazovky 2020-05-19 o 18 29 42" src="https://user-images.githubusercontent.com/16693449/82352820-d7d49e80-99fe-11ea-9730-e850fbdb0447.png">

**Comment by vasole** [comment]
What version of HDF5 are you using? You should be >= 1.10.2

**Comment by markub3327** [comment]
I think that here is version 1.10.4. I use Ubuntu 20.04 and the latest Raspbian.

<img width="1153" alt="Snímka obrazovky 2020-05-19 o 19 04 19" src="https://user-images.githubusercontent.com/16693449/82356454-e07ba380-9a03-11ea-8823-2a7f68292ba1.png">

**Comment by vasole** [comment]
Strange. It should work if the writer opened the file in non-SWMR mode. We are working that way.

Please replace lines 21-27 by the line:

os.environ["HDF5_USE_FILE_LOCKING"] = "FALSE"

to make sure there is nothing hidden somewhere, but I do not have much hope.

**Comment by woutdenolf** [comment]
What happens if you run this on your machines?

```python
# writer
import os
import h5py
from time import sleep

os.environ["HDF5_USE_FILE_LOCKING"] = "TRUE"
with h5py.File("test.h5", mode="a") as f:
    while True:
        sleep(0.1)
        k = f"{len(f.keys())}"
        f[k] = 1
        print(k)
        f.flush()
```

```python
#reader
import os
import h5py
from time import sleep

os.environ["HDF5_USE_FILE_LOCKING"] = "FALSE"
while True:
    try:
        with h5py.File("test.h5", mode="r") as f:
            print(len(f))
    except Exception as e:
        print(e)
```

If you're looking for new datasets, you'll have to open/close + catch/ignore exception.

If you're only looking at growing datasets after a successful open (you might need to try a few times), you should not get any exceptions anymore.

**Comment by woutdenolf** [comment]
Here is an example of a reader only looking at an existing dataset

```python
# writer
import os
import h5py
from time import sleep

os.environ["HDF5_USE_FILE_LOCKING"] = "TRUE"
with h5py.File("test.h5", mode="w") as f:
    dset = f.create_dataset("data", shape=(1000,), fillvalue=0)
    for i in range(1000):
        sleep(0.1)
        dset[i] = i
        f.flush()
        print(i)
```

```python
#reader
import os
import h5py
from time import sleep

os.environ["HDF5_USE_FILE_LOCKING"] = "FALSE"
try:
    while True:
        try:
            f = h5py.File("test.h5", mode="r")
            break
        except Exception as e:
            print(e)
    while max(f["data"]) != 999:
        print(max(f["data"]))
finally:
    f.close()
```

**Comment by markub3327** [comment]
> Here is an example of a reader only looking at an existing dataset. Once you get the dataset, you will not get exceptions anymore. Before that, you'll need to catch open/get exceptions.
> 
> ```python
> # writer
> import os
> import h5py
> from time import sleep
> 
> os.environ["HDF5_USE_FILE_LOCKING"] = "TRUE"
> with h5py.File("test.h5", mode="w") as f:
>     dset = f.create_dataset("data", shape=(1000,), fillvalue=0)
>     for i in range(1000):
>         sleep(0.1)
>         dset[i] = i
>         f.flush()
>         print(i)
> ```
> 
> ```python
> #reader
> import os
> import h5py
> from time import sleep
> 
> os.environ["HDF5_USE_FILE_LOCKING"] = "FALSE"
> try:
>     while True:
>         try:
>             f = h5py.File("test.h5", mode="r")
>             f["data"][()]
>             break
>         except Exception as e:
>             print(e)
>     while max(f["data"]) != 999:
>         print(max(f["data"]))
> finally:
>     f.close()
> ```

The result is interesting, but I get exceptions until number 294 and values are not synchronizing at the same time. You can see it on the screenshot.

<img width="1145" alt="Snímka obrazovky 2020-05-19 o 20 30 14" src="https://user-images.githubusercontent.com/16693449/82364617-cba50d00-9a0f-11ea-88d9-ccb79ea72a73.png">
<img width="1140" alt="Snímka obrazovky 2020-05-19 o 20 43 32" src="https://user-images.githubusercontent.com/16693449/82365833-8a156180-9a11-11ea-90c8-6c716ee24412.png">

**Comment by markub3327** [comment]
```python
class ReplayBuffer:
    def __init__(self, fileName, write=True, state_shape=None, action_shape=None, max_size=1e6):
        if (write == True):         # pre program Agent
            os.environ["HDF5_USE_FILE_LOCKING"] = "TRUE"

            self.max_size = int(max_size)
            self.buffer = deque()   # docasna fronta v RAM pre niekolko prechodov
            self.file = h5py.File(fileName, 'w')     # vytvor novy subor skusenosti

            self.state_dataset = self.file.create_dataset('state', shape=((0,) + state_shape), dtype=np.float32, maxshape=((self.max_size,) + state_shape))
            self.action_dataset = self.file.create_dataset('action', shape=((0,) + action_shape), dtype=np.float32, maxshape=((self.max_size,) + action_shape))
            self.reward_dataset = self.file.create_dataset('reward', shape=(0, 1), dtype=np.float32, maxshape=(self.max_size, 1))
            self.next_state_dataset = self.file.create_dataset('next_state', shape=((0,) + state_shape), dtype=np.float32, maxshape=((self.max_size,) + state_shape))
            self.terminal_dataset = self.file.create_dataset('terminal', shape=(0, 1), dtype=np.float32, maxshape=(self.max_size, 1))
            self.gamma_dataset = self.file.create_dataset('gamma', shape=(0, 1), dtype=np.float32, maxshape=(self.max_size, 1))
        else:       # pre program Learner
            os.environ["HDF5_USE_FILE_LOCKING"] = "FALSE"
            self.fileName = fileName

    def add(self, transition):
        # transiton is tuple of (state, action, reward, next_state, done, gamma)
        self.buffer.append(transition)

    def read_from_file(self):
        while True:
            try:
                # open file for reading
                self.file = h5py.File(self.fileName, 'r')

                self.state_dataset = self.file['state']
                self.action_dataset = self.file['action']
                self.reward_dataset = self.file['reward']
                self.next_state_dataset = self.file['next_state']
                self.terminal_dataset = self.file['terminal']
                self.gamma_dataset = self.file['gamma']
                break
            except Exception as e:
                print(e)
                time.sleep(2)

    def write_to_file(self):
        # vypocet velkosti
        self.old_size = self.state_dataset.shape[0]
        self.new_size = self.old_size + len(self.buffer)
        print(self.old_size, self.new_size)

        self.state_dataset.resize(self.new_size, axis=0)
        self.action_dataset.resize(self.new_size, axis=0)
        self.reward_dataset.resize(self.new_size, axis=0)
        self.next_state_dataset.resize(self.new_size, axis=0)
        self.terminal_dataset.resize(self.new_size, axis=0)
        self.gamma_dataset.resize(self.new_size, axis=0)
        
        # citaj vsetky prvky z fronty
        idx = self.old_size
        while (len(self.buffer) != 0):
            state, action, reward, next_state, terminal, gamma = self.buffer.popleft()
            self.state_dataset[idx, :] = state[0]
            self.action_dataset[idx, :] = action
            self.reward_dataset[idx, 0] = reward
            self.next_state_dataset[idx, :] = next_state[0]
            self.terminal_dataset[idx, 0] = terminal
            self.gamma_dataset[idx, 0] = gamma 
            #print(state, action, reward, next_state, float(terminal), gamma)
            #print(state.shape, action.shape, next_state.shape)
            idx += 1
        
        # vynuteny zapis do susboru
        self.file.flush()
```
```python
#reader
my_buffer = ReplayBuffer('agent_exp.h5', write=False)

try:
    i = 0
    while i != 100:
        # wait for file
        my_buffer.read_from_file()

        x = my_buffer.sample(1)
        print(x)

        time.sleep(2)

        # close file after reading
        my_buffer.file.close()

        i += 1
except KeyboardInterrupt:
    print('Terminated by user')
    sys.exit()    
```

It's working, but I must open/close the file in the reader when datasets are resized? Is it necessary?

**Comment by vasole** [comment]
It seems you need some time to get the file actually available (probably due to NFS) but then things work.

Concerning resizing, in our case we need to close and to open the files at the reader side to make sure they see the updated layout. Furthermore, the writer explicitly flushes and does not only rely on HDF5 deciding when to write.

**Comment by markub3327** [comment]
> ```python
> import numpy as np
> from collections import deque
> import h5py
> import os
> import time
> 
> class ReplayBuffer:
>     def __init__(self, fileName, write=True, state_shape=None, action_shape=None, max_size=1e6):
>         if (write == True):         # pre program Agent
>             os.environ["HDF5_USE_FILE_LOCKING"] = "TRUE"
> 
>             self.max_size = int(max_size)
>             self.buffer = deque()   # docasna fronta v RAM pre niekolko prechodov
>             self.file = h5py.File(fileName, 'w')     # vytvor novy subor skusenosti
> 
>             self.state_dataset = self.file.create_dataset('state', shape=((0,) + state_shape), dtype=np.float32, maxshape=((self.max_size,) + state_shape))
>             self.action_dataset = self.file.create_dataset('action', shape=((0,) + action_shape), dtype=np.float32, maxshape=((self.max_size,) + action_shape))
>             self.reward_dataset = self.file.create_dataset('reward', shape=(0, 1), dtype=np.float32, maxshape=(self.max_size, 1))
>             self.next_state_dataset = self.file.create_dataset('next_state', shape=((0,) + state_shape), dtype=np.float32, maxshape=((self.max_size,) + state_shape))
>             self.terminal_dataset = self.file.create_dataset('terminal', shape=(0, 1), dtype=np.float32, maxshape=(self.max_size, 1))
>             self.gamma_dataset = self.file.create_dataset('gamma', shape=(0, 1), dtype=np.float32, maxshape=(self.max_size, 1))
>         else:       # pre program Learner
>             os.environ["HDF5_USE_FILE_LOCKING"] = "FALSE"
>             self.fileName = fileName
> 
>     def read_from_file(self):
>         while True:
>             try:
>                 # open file for reading
>                 self.file = h5py.File(self.fileName, 'r')
> 
>                 self.state_dataset = self.file['state']
>                 self.action_dataset = self.file['action']
>                 self.reward_dataset = self.file['reward']
>                 self.next_state_dataset = self.file['next_state']
>                 self.terminal_dataset = self.file['terminal']
>                 self.gamma_dataset = self.file['gamma']
>                 break
>             except Exception as e:
>                 print(e)
>                 time.sleep(2)
> 
>     def add(self, transition):
>         # transiton is tuple of (state, action, reward, next_state, done, gamma)
>         self.buffer.append(transition)
> 
>     def write_to_file(self):
>         # vypocet velkosti
>         self.old_size = self.state_dataset.shape[0]
>         self.new_size = self.old_size + len(self.buffer)
>         print(self.old_size, self.new_size)
> 
>         self.state_dataset.resize(self.new_size, axis=0)
>         self.action_dataset.resize(self.new_size, axis=0)
>         self.reward_dataset.resize(self.new_size, axis=0)
>         self.next_state_dataset.resize(self.new_size, axis=0)
>         self.terminal_dataset.resize(self.new_size, axis=0)
>         self.gamma_dataset.resize(self.new_size, axis=0)
>         
>         # citaj vsetky prvky z fronty
>         idx = self.old_size
>         while (len(self.buffer) != 0):
>             state, action, reward, next_state, terminal, gamma = self.buffer.popleft()
>             self.state_dataset[idx, :] = state[0]
>             self.action_dataset[idx, :] = action
>             self.reward_dataset[idx, 0] = reward
>             self.next_state_dataset[idx, :] = next_state[0]
>             self.terminal_dataset[idx, 0] = terminal
>             self.gamma_dataset[idx, 0] = gamma 
>             #print(state, action, reward, next_state, float(terminal), gamma)
>             #print(state.shape, action.shape, next_state.shape)
>             idx += 1
>         
>         # vynuteny zapis do susboru
>         self.file.flush()
> 
>     def sample(self, batch_size):
>         indexes = np.random.randint(0, self.state_dataset.shape[0], size=batch_size)
>         state, action, reward, next_state, done, gamma = [], [], [], [], [], []
>         
>         print(self.state_dataset.shape, self.state_dataset.dtype)
>         print(self.action_dataset.shape, self.action_dataset.dtype)
>         print(self.reward_dataset.shape, self.reward_dataset.dtype)
>         print(self.next_state_dataset.shape, self.next_state_dataset.dtype)
>         print(self.terminal_dataset.shape, self.terminal_dataset.dtype)
>         print(self.gamma_dataset.shape, self.gamma_dataset.dtype)
> 
>         for i in indexes:     
>             state.append(self.state_dataset[i])
>             action.append(self.action_dataset[i])
>             reward.append(self.reward_dataset[i])
>             next_state.append(self.next_state_dataset[i])
>             done.append(self.terminal_dataset[i])
>             gamma.append(self.gamma_dataset[i])
> 
>         return np.array(state), np.array(action), np.array(reward), np.array(next_state), np.array(done), np.array(gamma)
> ```
> 
> ```python
> # reader
> my_buffer = ReplayBuffer('agent_exp.h5', write=False)
> 
> try:
>     i = 0
>     while i != 100:
>         # wait for file
>         my_buffer.read_from_file()
> 
>         x = my_buffer.sample(1)
>         print(x)
> 
>         time.sleep(2)
> 
>         # close file after reading
>         my_buffer.file.close()
> 
>         i += 1
> except KeyboardInterrupt:
>     print('Terminated by user')
>     sys.exit()
> ```
> 
> It's working, but I must open/close the file in the reader when datasets are resized? Is it necessary? The results are delayed.
> 
> <img alt="Snímka obrazovky 2020-05-19 o 21 48 00" width="1025" src="https://user-images.githubusercontent.com/16693449/82371576-b681ab80-9a1a-11ea-8b70-958b4f9c640e.png">

This means that this code below is working fine and I can use it stable?

**Comment by vasole** [comment]
The delay is expected due to NFS.

**Comment by markub3327** [comment]
Okej, I think this issue is solved. Thanks a lot for your time.
