### ISSUE TITLE
enabling simultaneous (alternative) installation of serial and mpi builds

### ISSUE THREAD

**Issue by RizzerOnGitHub** [h5py/h5py#1559]
h5py can be built against either serial or mpi versions of libhdf5.

An mpi build still runs fine as a serial process. But a Debian user was complaining that the cost of loading up MPI degraded performance. PR #1552 might help with that, but they'll still complain about even having to install mpi libraries. It could be useful to provide the serial build for those who prefer it, while at the same time also providing the MPI build for those that need mpio.

So in Debian I made a patch to enable simultaneous installation of both builds, either of them accessible to users. Our approach was
* install the standard existing builds into subdirectories: `h5py/_debian_h5py_mpi` and `h5py/_debian_h5py_serial` rather than the usual `h5py`. 
* provide a h5py/\__init__.py that imports  _debian_h5py_mpi as _h5py if an MPI process is detected. If not, import _debian_h5py_serial as _h5py
* load symbols from _h5py.\__dict__ into sys_modules

MPI detection checks for OpenMPI/MPICH environment variables, OMPI_COMM_WORLD_SIZE and MPI_LOCALNRANKS.  We couldn't identify a more general method of detecting if the process is part of an MPI run. I also added a check for H5PY_ALWAYS_USE_MPI which could be set by the user, e.g. to force use of h5py-mpi in a serial process.

In principle the user could import directly `import h5py/_debian_h5py_serial as h5py` if they really wanted to.

It's been operating for more than 2 months now, since late March (with h5py 2.10.0). It seems to be working fine as intended.  The required patches are not particularly large,
* [build_flavour.patch](https://salsa.debian.org/science-team/h5py/-/blob/master/debian/patches/build_flavour.patch)
* [hdf5_pkgconfig.patch](https://salsa.debian.org/science-team/h5py/-/blob/master/debian/patches/hdf5_pkgconfig.patch)
* [stop_circular_dep.patch](https://salsa.debian.org/science-team/h5py/-/blob/master/debian/patches/stop_circular_dep.patch)
* [tests_as_local_build.patch](https://salsa.debian.org/science-team/h5py/-/blob/master/debian/patches/tests_as_local_build.patch)
* [\__init__.py](https://salsa.debian.org/science-team/h5py/-/blob/master/debian/wrapper_module/h5py/__init__.py)

I used the [debian build scripts](https://salsa.debian.org/science-team/h5py/-/tree/master/debian) to make separate serial and mpi builds and install them in their subdirectories.

Is this something that the h5py project would find useful to bring on board?

**Comment by takluyver** [comment]
I can't speak for all the maintainers, but from my perspective: no thanks. I'm happy enough with the existing solution where people who need MPI support specify that at build time.

**Comment by takluyver** [comment]
As none of the other maintainers have spoken up in favour of this, I'm going to close the issue. Thanks for getting in touch, though - it's nicer hearing what Debian packagers are doing directly than figuring it out when we get bug reports. :wink:
