### ISSUE TITLE
OSError: Unable to open file (file signature not found)

### ISSUE THREAD

**Issue by adithyaOvGu** [h5py/h5py#1562]
* Operating System: MacOS 10.15.5
 * Python version: 3.7
 * System Python: on MacOS or Linux
 * h5py version: 2.10

I am trying to train a deep learning model from facebookresearch/fastMRI git repo. When I run the commands mentioned in fastMRI/models/unet/, where I have passed the necessary arguments. I am faced with the following error;

```
File "/Users/user/PycharmProjects/fastMRI/fastMRI/data/mri_data.py", line 49, in init
data = h5py.File(fname, 'r')
File "/Users/user/PycharmProjects/fastMRI/venv/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in init swmr=swmr)
File "/Users/user/PycharmProjects/fastMRI/venv/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid

fid = h5f.open(name, flags, fapl=fapl)
File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

This part of the scrip is where the error occurs;

```python
        self.examples = []
        files = list(pathlib.Path(root).iterdir())
        print(files)  # added
        if sample_rate < 1:
            random.shuffle(files)
            num_files = round(len(files) * sample_rate)
            files = files[:num_files]

        for fname in sorted(files):
            print("FILE NAME:", fname)  # PROBLEM HERE !
            data = h5py.File(fname, 'r')
```

Print output to check files: 

```
[....., PosixPath('/Volumes/Macintosh_HD/MRImageRecon/singlecoil_train/file1002538.h5')]
FILE NAME: /Volumes/Macintosh_HD/MRImageRecon/singlecoil_train/.DS_Store
```
After some online searches, I found that this error occurs only if the .h5 files are corrupted during download or that the files in the specified path are not of .h5 type. But in my case, the files are fine because I can access them when I try from a new script. 

I asked the question in FastMRI repo, but the developers said it might a h5py issue, so I am asking this question here. I kindly request you to provide your insight into what could be the issue. Thanks in advance.

**Comment by takluyver** [comment]
`.DS_Store` [is a special Mac file](https://en.wikipedia.org/wiki/.DS_Store) which the OS creates automatically. It's not an HDF5 file, so trying to open it with h5py throws an error. You'll need to skip it, or somehow make a list of only files which are HDF5.

**Comment by XiongchaoChen** [comment]
I have the same error in h5py as you. The version of h5py I am currently using is 3.8.0. Have you solved the problem yet?

**Comment by adithyaOvGu** [comment]
> I have the same error in h5py as you. The version of h5py I am currently using is 3.8.0. Have you solved the problem yet?

Yes. There were ".DS_Store" files inside the data folder where the h5 files reside. You could modify your script to only read h5 files from the data path using *.h5, or delete the ".DS_Store" from the data folder. The former is a better solution in terms of code, but the latter also works as long as you do not modify the contents of the folder.

**Comment by takluyver** [comment]
This error message usually means that you're trying to open something that's not an HDF5 file. Avoiding or fixing it is likely to depend on the software you're using or how you're using it.

**Comment by Luckaswww** [comment]
@niuniu800 hello. I have the same problem. How did you solve it

**Comment by niuniu800** [comment]
It is possible that the data folder obtained from your first-principles calculation is missing during some iteration process, or the deepmd folder generated by the init function does not exist. You may want to check on that.

**Comment by Luckaswww** [comment]
@niuniu800 OK. I'll check these files. Thank you very much for you reply.
