### ISSUE TITLE
"OSError: Unable to open file (unable to open file)" for in-memory image

### ISSUE THREAD

**Issue by radarsat1** [h5py/h5py#1572]
Hello,

I am investigating a bug recently reported for the Keras package in Debian Unstable.  It appears that some tests that were working are not broken after some udpates to the python3-h5py package, but I cannot understand the problem so I was hoping to get some help here.

The test that is failing has the following code:

```
def save_to_binary_h5py(save_function, stream):
    with h5py.File('in-memory-h5py', driver='core', backing_store=False) as h5file:
        return_value = save_function(h5file)
        h5file.flush()
        binary_data = h5file.fid.get_file_image()
    stream.write(binary_data)
```

And the crash happens on the `with h5py.File` line.  Apparently the file cannot be opened, but I have no idea what is going on beyond that.  Any ideas?

The full build log can be found [here](http://qa-logs.debian.net/2020/06/20/keras_2.3.1+dfsg-1_unstable.log)

 * Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 16.04.2 LTS, CentOS 7)

Debian Unstable

 * Python version (e.g. 2.7, 3.5)

3.8.3

 * h5py version (e.g. 2.6)

2.10.0

 * HDF5 version (e.g. 1.8.17)

N/A

 * The full traceback/stack trace shown (if it appears)

```
Traceback (most recent call last):
  File "tests/keras/utils/io_utils_test.py", line 354, in <module>
    test_save_to_binary_h5py_direct_to_file()
  File "tests/keras/utils/io_utils_test.py", line 261, in test_save_to_binary_h5py_direct_to_file
    save_to_binary_h5py(save_function, f)
  File "/usr/lib/python3/dist-packages/keras/utils/io_utils.py", line 416, in save_to_binary_h5py
    with h5py.File('in-memory-h5py', driver='core', backing_store=False) as h5file:
  File "/usr/lib/python3/dist-packages/h5py/_debian_h5py_serial/_hl/files.py", line 387, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/usr/lib/python3/dist-packages/h5py/_debian_h5py_serial/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_debian_h5py_serial/_objects.pyx", line 54, in h5py._debian_h5py_serial._objects.with_phil.wrapper
  File "h5py/_debian_h5py_serial/_objects.pyx", line 55, in h5py._debian_h5py_serial._objects.with_phil.wrapper
  File "h5py/_debian_h5py_serial/h5f.pyx", line 88, in h5py._debian_h5py_serial.h5f.open
OSError: Unable to open file (unable to open file)
```

`h5py.version.info` contains the needed versions, which can be displayed by

```
$ python3 -c 'import h5py; print(h5py.version.info)'
Summary of the h5py configuration
---------------------------------

h5py    2.10.0
HDF5    1.10.6
Python  3.8.3 (default, May 14 2020, 11:03:12) 
[GCC 9.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.19.0
```

**Comment by tacaswell** [comment]
```
import h5py

with h5py.File('in-memory-h5py', driver='core', backing_store=False, mode='w') as h5file:
    
    h5file.flush()
    binary_data = h5file.id.get_file_image()

```

I think you got caught by two changes: 

 1) the default mode changed to 'r' (from rw, but make if it exists) http://docs.h5py.org/en/latest/whatsnew/2.10.html#deprecations
 2) using the deprecated `fid` attribute (which is documented https://github.com/h5py/h5py/blob/master/news/rm-file-fid.rst but I am having trouble finding in the docs)

so I think the keras tests need to fixed (probably upstream with them), but we also need to sort out our docs...

**Comment by radarsat1** [comment]
Thank you, that was it! Just the kind of hints that I was looking for, seems to fix the issue.  cheers
