### ISSUE TITLE
Unable to raise max_size in cache config permanently

### ISSUE THREAD

**Issue by kecsap** [h5py/h5py#1575]
* Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 16.04.2 LTS, CentOS 7)
Ubuntu 18.04
 * Python version (e.g. 2.7, 3.5)
Python 3.6.9
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows)
Package manager
 * h5py version (e.g. 2.6)
2.10.0
 * HDF5 version (e.g. 1.8.17)
1.10.4

``` python
import h5py

f = h5py.File('myfile.hdf5','w')

f['dataset'] = range(10)
config = f.id.get_mdc_config()
print("Initial:", config.max_size)
config.max_size = 128*1024*1024
f.id.set_mdc_config(config)
config = f.id.get_mdc_config()
print("New:", config.max_size)
f.close()

f = h5py.File('myfile.hdf5','r+')
config = f.id.get_mdc_config()
print("Read:", config.max_size)
config.max_size = 128*1024*1024
f.id.set_mdc_config(config)
config = f.id.get_mdc_config()
print("New again:", config.max_size)
f.close()

f = h5py.File('myfile.hdf5','r')
config = f.id.get_mdc_config()
print("Still bad:", config.max_size)
f.close()
```

Problem: max_size always reverts back to 32M. It is not written back to the file although reading back the new config indicates, it is changed. Is not the cache config stored inside the file? Now I have to open my hdf5 file and manually change this value before processing otherwise the cache size is a huge bottleneck for my hdf5 reading. It is not very convenient.

```
Initial: 33554432
New: 134217728
Read: 33554432
New again: 134217728
Still bad: 33554432
```

**Comment by takluyver** [comment]
That method is a pretty plain wrapper around a [libhdf5 function](https://confluence.hdfgroup.org/display/HDF5/H5F_SET_MDC_CONFIG), the docs for which say:

> See the overview of the metadata cache in the special topics section of the user manual for details on what is being configured. If you haven't read and understood that documentation, you really shouldn't be using this API call.

I think that's referring to https://confluence.hdfgroup.org/display/HDF5/Metadata+Caching+in+HDF5 .

I haven't read through that, but if it doesn't explain what you're seeing, I'd suggest contacting help@hdfgroup.org about it. If possible, try to reproduce it with C code using libhdf5 directly.

**Comment by kecsap** [comment]
After browsing the sources libhdf5, the cache config is not stored in the HDF5 file, but it is an in-memory config that is created with default values when a file is opened. Can you add this information to your documentation of get_mdc_config()/set_mdc_config()? And this issue can be closed.

**Comment by takluyver** [comment]
This is the relevant code, if you're interested in making a PR:

https://github.com/h5py/h5py/blob/master/h5py/h5f.pyx#L499-L519

**Comment by takluyver** [comment]
(Docs for low-level methods like these are generated from the docstrings)

**Comment by kecsap** [comment]
https://github.com/h5py/h5py/pull/1576
