### ISSUE TITLE
How to extract the data from a .h5 format with no keys?

### ISSUE THREAD

**Issue by AllenWu18** [h5py/h5py#1578]
* Operating System Linux
 * Python version 3.7.3
 * Where Python was acquired system Python on Linux
 * h5py version 2.9.0
 * HDF5 version 1.10.4
 * The full traceback/stack trace shown (if it appears)
h5py    2.9.0
HDF5    1.10.4
Python  3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.16.2

I just have a question: I downloaded a data file with h5 format from https://support.10xgenomics.com/single-cell-gene-expression/datasets/2.1.0/pbmc4k 
and I tried to load the data from the file
But when I run the code as follows:
_import h5py
data = h5py.File('pbmc4k.h5')
data.keys()_

it just showed like:
_<KeysViewHDF5 []>_

While I think this file has not any key values. So how can I extract the data from it?
Thx!

**Comment by takluyver** [comment]
If it's really an HDF5, it should always have keys.

I'd suggest opening it with `'r'` mode (`h5py.File(..., 'r')`), so that you get an error if you get the name wrong, rather than just creating a new file. This will be the default in h5py 3.0.

**Comment by AllenWu18** [comment]
OK it works. THX a lot!
:)
:+1:

**Comment by takluyver** [comment]
Great!
