### ISSUE TITLE
SWMR querying: AttributeError: 'File' object has no attribute '_swmr_mode'

### ISSUE THREAD

**Issue by miketrumpis** [h5py/h5py#1580]
Hi h5py devs. Thank you for the incredible software!

First off:

```
Summary of the h5py configuration
---------------------------------

h5py    2.10.0
HDF5    1.10.4
Python  3.8.2 (default, May 23 2020, 11:49:39) 
[Clang 11.0.0 (clang-1100.0.33.8)]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.18.4
```

I am trying to find out whether and how to re-open an HDF5 file for read-only access in a subprocess: i.e. in SWMR mode or just in simple read mode. I am trying to get that info by querying a ``h5py._hl.dataset.Dataset`` object about the status of its parent file.

So a brief example

```python
import numpy as np
import h5py as h5py

h5 = h5py.File('foo.h5', 'w', libver='latest')
h5['array'] = np.ones((10, 20))
h5.swmr_mode = True
array = h5['array']
array.file.swmr_mode
```

However, I am getting this attribute error.

```python
AttributeError: 'File' object has no attribute '_swmr_mode'
```

And the same result if the file was opened again in 'r' mode.

I don't understand the difference between ``h5`` and ``array.file`` (they are equal but not identical). But I do see in the code that the attribute in question is only defined conditionally in the constructor (alternatively, in the property setter). Should it be defaulted outside the conditional?

https://github.com/h5py/h5py/blob/2881b7cc1d24989e9d8d54814c4855522f7a9607/h5py/_hl/files.py#L428-L431

**Comment by miketrumpis** [comment]
For clarity, the attribute error is coming from the "swmr_mode" property getter.

**Comment by miketrumpis** [comment]
Related: setting ``h5.swmr_mode = True`` changes ``h5.mode``

```python
>>> h5 = h5py.File('foo.h5', 'w', libver='latest')                                                                                
>>> h5['array'] = np.ones((10, 20))                                                                                               
>>> h5.mode                                                                                                                       
'r+'
>>> h5.swmr_mode = True                                                                                                           
>>> h5.mode is None                                                                                                               
True
```

And the same None value occurs with this read-mode construction: ``h5 = h5py.File('foo.h5', 'r', libver='latest', swmr=True)``

Is that proper behavior? Makes it difficult to know whether a dataset can be written to.

**Comment by takluyver** [comment]
I agree with you that the private attribute should always exist, so that the property access can't fail like that. But that alone won't solve your problem, because `dataset.file` will create a new file object, which would always have the default `swmr_mode`.

To be honest, the `smwr_mode` attribute seems like a mess: it's confusing the read and write parts of SWMR, which are quite different things.

The change in `file.mode` is related. The [H5Fget_intent](https://confluence.hdfgroup.org/display/HDF5/H5F_GET_INTENT) function can now return four possible modes, two of which relate to SWMR. But we're only checking two of them:

https://github.com/h5py/h5py/blob/2881b7cc1d24989e9d8d54814c4855522f7a9607/h5py/_hl/files.py#L255-L258

**Comment by miketrumpis** [comment]
I noticed the ``get_intent`` business. It seems to faithfully reflect SWMR, so it's a good way to deal with the ``swmr_mode`` property getter, too (rather than a private attribute). Something like this?

```python
return 0 < (self.id.get_intent() & (h5f.ACC_SWMR_READ | h5f.ACC_SWMR_WRITE))
```

Similar for mode

```python
intent = self.id.get_intent() & (h5f.ACC_SWMR_READ | h5f.ACC_RDONLY)
if 0 < intent:
    return 'r'
else:
    return 'r+'
```

**Comment by takluyver** [comment]
That looks like a good idea. Do you want to make a PR for it?

**Comment by miketrumpis** [comment]
Yep made the fork & committed some changes and (passing) unit tests. There were some instructions about running tox that look intended for devs. Can I just make the PR without those steps?

**Comment by takluyver** [comment]
You can: the checks will be run by CI (continuous integration) services when you open the PR.

It can save some time to run the tests - or just the static checks - locally first and fix anything it complains about. h5py has some quite fussy static checkers, and pushing a commit and waiting for CI to tell you about problems is a bit slow. If you want to use tox, it's a standard Python tool which you can get with `pip install tox`. But it's not required.

**Comment by miketrumpis** [comment]
Funny--there is a unit test to check that the AttributeError is raised for older versions. Right now I just let the class attribute be False for this case. It's hard to imagine anyone relying on the present behavior, but then again it's definitely something I'd do in a rush! Any input?

https://github.com/h5py/h5py/blob/99328316c9b9f8ac247d3cc2ea2d54465d82d86c/h5py/tests/test_dataset_swmr.py#L39-L41
