### ISSUE TITLE
hdf5 1.12.X

### ISSUE THREAD

**Issue by zerothi** [h5py/h5py#1594]
Additions to issues #1506, #1504, #1505 

It seems that the above issues request users to compile hdf5 with default 1.10 compatibility flags. I would not advice this...

hdf5 have added a compatibility definition flag:
```
-DH5_USE_110_API
```
which allows one to use the 110 api directly without recompiling 1.12 (and without requiring wrappers). This could easily be handled in `setup.py` to automatically insert the definition at compile time.

However, h5py exposes `H5I_REFERENCE` which has been deprecated since 1.10.2 (see [here](https://support.hdfgroup.org/ftp/HDF5/prev-releases/ReleaseFiles/hdf5-1.10.2-RELEASE.txt)). In #1536 a patch is required to remove the variables. I would advice this is completely removed.

**Comment by takluyver** [comment]
No, we don't require HDF5 to be built with any special options. h5py already specifies using the 1.8 API by default (as we still support some 1.8 versions) - here's the flag:

https://github.com/h5py/h5py/blob/21bc91f14c7d50cf9af67a6161bffe270a9150f3/setup_build.py#L41

No patch is required either - h5py master is now built and tested against a standard build of HDF5 1.12 on CI. There are some remaining changes we want to do before releasing this.

**Comment by zerothi** [comment]
Ok, my take on the issues was erroneous then. Thanks, for this! I'll close.

**Comment by takluyver** [comment]
Thanks!
