### ISSUE TITLE
h5py doesn't play well with Pytables on Windows

### ISSUE THREAD

**Issue by andrewcollette** [h5py/h5py#16]
_Original author: scott.si...@gmail.com (December 04, 2008 13:37:13)_

h5py and Pytables can't be used at the same time when installed from the
windows installers. This appears to be due to an API incompatibility
between the HDF5 dll's used. The h5py installer provides the 1.8 API by
default and the Pytables installer provides the 1.6 API.

&gt;&gt;&gt; import h5py
&gt;&gt;&gt; import tables # fails to find dll entry point

or

&gt;&gt;&gt; import tables
&gt;&gt;&gt; import h5py # fails to find dll entry point

This will probably be surprising to many users and should at least be
documented in the name of the installer that is offered.
- What version of h5py, and HDF5
# Summary of h5py config

HDF5: 1.8.2
1.6 API: True
1.8 API: True
Thread-aware: True
Diagnostic mode: False
Complex names: ('r', 'i')

<b>\* What operating system (Linux/Windows/etc)</b>

Windows XP

<b>\* What major version of Python (2.5 or 2.6)</b>

Python 2.5

_Original issue: http://code.google.com/p/h5py/issues/detail?id=16_

**Comment by stefanoborini** [comment]
The problem still exists as of today. Both libraries are now called hdf5.dll, and they collide on windows.
