### ISSUE TITLE
h5py: cached-property not found

### ISSUE THREAD

**Issue by rmvanhees** [h5py/h5py#1601]
Hi,
Yesterday I pulled the latest source of h5py from gitHub to give it a try. I noticed that the 'cached-property' distribution was installed by h5py, but not in the right location:

  >> pip3 install cached-property
  Requirement already satisfied: cached-property in ~/git/h5py/.eggs/cached_property-1.5.1-py3.8.egg (1.5.1)

I had to remove it using 'pip3 uninstall cached-property' and reinstall it 'pip3 install --upgrade cached-property'. Then everything worked.

Thanks for all the good work.

Greetings, Richard

To assist reproducing bugs, please include the following:
 * Operating System Debian 9
 * Python version 3.8.5
 * h5py version pulled from gitHub yesterday
 * HDF5 version 12.0
 * Problem:
pkg_resources.DistributionNotFound: The 'cached-property' distribution was not found and is required by h5py

**Comment by takluyver** [comment]
How did you install it? I've just tried with a fresh conda environment and `pip install .`, and I didn't get this.

**Comment by rmvanhees** [comment]
Hi Thomas,
It probably has to do with the way I installed the development version of h5py. Inside the source tree I installed h5py using 'python3 setup.py install', instead of 'pip3 install h5py'. In the latter case, pip takes care of the required packages. At the end of the installation, I get the following message:
   Processing dependencies for h5py==2.10.0
   Searching for cached-property==1.5.1
   Best match: cached-property 1.5.1
   Processing cached_property-1.5.1-py3.8.egg
   cached-property 1.5.1 is already the active version in easy-install.pth

   Using ~/git/h5py/.eggs/cached_property-1.5.1-py3.8.egg
   Searching for numpy==1.19.1
   Best match: numpy 1.19.1
   Adding numpy 1.19.1 to easy-install.pth file
I only noticed the unexpected installation location of cached_property when working on a different server without access to ~/git/h5py/.eggs.

Anyway, I have no clue how to fix this problem for people who do not use pip or conda. Probably, this is a non-issue, because using 'python setup.py install', I should have checked the dependency myself. What do you think?

Greetings, Richard

**Comment by takluyver** [comment]
Does it work correctly if you do `pip install .`? You may need to remove the `.eggs` directory first to simulate a clean checkout.

`pip install .` is now the recommended way to install a package from a local folder, rather than `setup.py install`. I've opened issue #1605 to fix it in the h5py install docs.

**Comment by rmvanhees** [comment]
Yes, this works and should be recommended to pip-users.

I tested it as follows:
cd git/h5py
git pull
rm -rf dist/ build/ .eggs/ h5py.egg-info
pip3 uninstall cached-property
pip3 install .

And both cached-property and h5py are installed correctly. Thanks!

Greetings, Richard

**Comment by takluyver** [comment]
Great, thanks. In that case, I think this is covered by #1605, so I'll close this one.
