### ISSUE TITLE
OSError: Can't read data - unexpectedly large 'bytes actually read'

### ISSUE THREAD

**Issue by Hrovatin** [h5py/h5py#1610]
I was trying to load some datasets with scanpy.read_h5ad(file_name), which is based on h5py. The developers of the Scanpy instructed me that this is in fact h5py problem and that they can not help me with it (see https://github.com/theislab/scanpy/issues/1351). When trying to load the h5ad dataset (based on hdf5) I frequently get the below error. When I re-run the code multiple times or at different times it sometimes works, but often I get the error (using the same code and data). This happens when reading different h5ad datasets (e.g. is not specific to one dataset). At all times there seems to be enough free RAM / similar amount of free RAM - one of the h5ad files is 63M and the server has more than 300GB free RAM and 40GB free sweep. I also tried using different servers, but this did not help. This happens both when using jupyter-notebook and python without jupyter-notebook.

 * Operating System: Fedora 28 
 * Python version: Python 3.8.5
 * Where Python was acquired: Anaconda
 * h5py version: 2.10.0
 * HDF5  version:  1.10.6
 * The full traceback/stack trace shown (if it appears):
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~/miniconda3/envs/rpy2_3/lib/python3.8/site-packages/anndata/_io/utils.py in func_wrapper(elem, *args, **kwargs)
    155         try:
--> 156             return func(elem, *args, **kwargs)
    157         except Exception as e:

~/miniconda3/envs/rpy2_3/lib/python3.8/site-packages/anndata/_io/h5ad.py in read_group(group)
    505     if "h5sparse_format" in group.attrs:  # Backwards compat
--> 506         return SparseDataset(group).to_memory()
    507 

~/miniconda3/envs/rpy2_3/lib/python3.8/site-packages/anndata/_core/sparse_dataset.py in to_memory(self)
    370         mtx = format_class(self.shape, dtype=self.dtype)
--> 371         mtx.data = self.group["data"][...]
    372         mtx.indices = self.group["indices"][...]

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

~/miniconda3/envs/rpy2_3/lib/python3.8/site-packages/h5py/_hl/dataset.py in __getitem__(self, args)
    572         fspace = selection.id
--> 573         self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
    574 

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5d.pyx in h5py.h5d.DatasetID.read()

h5py/_proxy.pyx in h5py._proxy.dset_rw()

h5py/_proxy.pyx in h5py._proxy.H5PY_H5Dread()

OSError: Can't read data (file read failed: time = Sat Aug  1 13:27:54 2020
, filename = '/path.../filtered_gene_bc_matrices.h5ad', file descriptor = 47, errno = 5, error message = 'Input/output error', buf = 0x55ec782e9031, total read size = 7011, bytes this sub-read = 7011, bytes actually read = 18446744073709551615, offset = 0)

During handling of the above exception, another exception occurred:

AnnDataReadError                          Traceback (most recent call last)
<ipython-input-14-faac769583f8> in <module>
     17     #while True:
     18         #try:
---> 19             adatas.append(sc.read_h5ad(file))
     20             file_diffs.append('_'.join([file.split('/')[i] for i in diff_path_idx]))
     21             #break

~/miniconda3/envs/rpy2_3/lib/python3.8/site-packages/anndata/_io/h5ad.py in read_h5ad(filename, backed, as_sparse, as_sparse_fmt, chunk_size)
    411                 d[k] = read_dataframe(f[k])
    412             else:  # Base case
--> 413                 d[k] = read_attribute(f[k])
    414 
    415         d["raw"] = _read_raw(f, as_sparse, rdasp)

~/miniconda3/envs/rpy2_3/lib/python3.8/functools.py in wrapper(*args, **kw)
    873                             '1 positional argument')
    874 
--> 875         return dispatch(args[0].__class__)(*args, **kw)
    876 
    877     funcname = getattr(func, '__name__', 'singledispatch function')

~/miniconda3/envs/rpy2_3/lib/python3.8/site-packages/anndata/_io/utils.py in func_wrapper(elem, *args, **kwargs)
    160             else:
    161                 parent = _get_parent(elem)
--> 162                 raise AnnDataReadError(
    163                     f"Above error raised while reading key {elem.name!r} of "
    164                     f"type {type(elem)} from {parent}."

AnnDataReadError: Above error raised while reading key '/X' of type <class 'h5py._hl.group.Group'> from /.
```
Please note that I deleted most of the path of my file from the stacktrace - it is stored in my workspace on the server.

**Comment by takluyver** [comment]
There was a similar error reported recently in #1592. 18446744073709551615 is `2 ** 64 - 1`, but that doesn't really help me diagnose it.

Are you parallelising anything with multiple processes - or could scanpy be doing some internal parallelism? Opening an HDF5 file before a fork can cause weird problems with reading it. I thought of this because you said it sometimes works and sometimes doesn't, which suggests a race condition.

Other than that, we may just have to pass you on again, to HDF5 itself. You can email help@hdfgroup.org or use the [HDF forum](https://forum.hdfgroup.org/) for that.

**Comment by Hrovatin** [comment]
Thank you. I do not think that any of it is parallelized.

**Comment by takluyver** [comment]
In that case, the only thing I can think to suggest is asking HDF group about it. The error is coming from HDF5, and h5py is just another layer of code wrapping around that.

If it's not something they already recognise, someone will need to try to reduce it to a minimal example which reproduces the problem.

**Comment by Hrovatin** [comment]
It seems that the problem was due to https://github.com/theislab/scanpy/issues/1351#issuecomment-668009684 . This comment seems to resolve my problems for now.

**Comment by takluyver** [comment]
OK, thanks. I guess we should remember to check for network filesystems when these errors come up. Maybe we should have a troubleshooting bit in the docs somewhere.

**Comment by takluyver** [comment]
Is it possible that `/store` is some sort of network filesystem?

**Comment by mas-dot** [comment]
Hey,
Thanks for your message.
Yeah, it is. 
I'm running everything on a HPC cluster.

**Comment by JSegueni** [comment]
Should I create a new issue for this or could it be possible to reopen this one ?

**Comment by takluyver** [comment]
The error is coming from HDF5, so you might want to ask HDF group about it - help@hdfgroup.org, or on the [HDF forum](https://forum.hdfgroup.org/). But if you're accessing data on a network filesystem, there's a good chance that's the problem. You *might* be able to avoid the error by using SWMR mode, but that has its own limitations.

**Comment by takluyver** [comment]
The error is coming from HDF5, so you might want to ask HDF group about it - help@hdfgroup.org, or on the [HDF forum](https://forum.hdfgroup.org/). But if you're accessing data on a network filesystem, there's a good chance that's the problem. You *might* be able to avoid the error by using SWMR mode, but that has its own limitations.
