### ISSUE TITLE
OSError: Unable to open file(file names not unique)

### ISSUE THREAD

**Issue by dota17** [h5py/h5py#1616]
```
Summary of the h5py configuration
---------------------------------

h5py    2.10.0
HDF5    1.10.6
Python  3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.18.0
```

When I wrote the test case about file drivers, it always failed when I set `driver=family`, the log shows like:
> OSError: Unable to open file(file names not unique)

so I wander if it really support this kind of driver,

**Comment by takluyver** [comment]
Did you follow the note in [the docs](https://docs.h5py.org/en/latest/high/file.html#file-drivers)?

> the filename you provide must contain a printf-style integer format code (e.g. %d”), which will be replaced by the file sequence number.

**Comment by dota17** [comment]
@takluyver Thank you, it helps. 
I will add a test case `test_family` soon.
