### ISSUE TITLE
Missing entries in low-level API docs

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#1631]
Including at least:

- [x] h5py.h5d functions
- [x] h5py.h5i functions
- [x] h5py.h5z functions
- [x] h5py.h5d.PropDAID

From https://github.com/h5py/h5py/issues/1620#issuecomment-670603173

**Comment by takluyver** [comment]
It looks like where we use

```rst
.. automodule:: h5py.h5i
    :members:
```

to document all functions in a module, it only includes functions which are declared in the relevant `.pxd` file. We either need to list the functions explicitly in the doc source (like we do for `h5f` and a number of other modules), or make sure they're in the `.pxd` file (like we do for `h5pl`).

**Comment by aragilar** [comment]
Does `:nodoc-members:` help? I'm surprised that the `.pxd` file is used, I would have thought that would only be for the build, and not for runtime, or is something implicitly set on objects defined within the `.pxd` which is then reflected by them being found by sphinx?

**Comment by takluyver** [comment]
`h5d.open` has a docstring, so it can't just be that.

I can never remember which bits of Sphinx use runtime introspection and which parse source code. I'm surprised that the pxd file matters as well, but it seems like it does!

**Comment by takluyver** [comment]
Weirdly, today the functions are there. Either one of our recent PRs fixed it (#1624?), or it's an intermittent fault, or I was just somehow rather blind yesterday.

I'm going to reorganise the `h5d` page to better match other similar pages, with 'Functional API' at the top.

**Comment by takluyver** [comment]
Done in #1637.
