### ISSUE TITLE
Writing sliced NumPy array stores wrong values

### ISSUE THREAD

**Issue by KurtAhn** [h5py/h5py#1649]
Environment
 * Operating System: Ubuntu 18.04.4 LTS
 * Python version: 3.8.3
 * Where Python was acquired: Anaconda on Linux
 * h5py version: 2.10.0
 * HDF5 version: 1.10.4

When writing a sliced NumPy array to a dataset, the value stored in the dataset does not match the value being written unless `.copy()` is called on the sliced array first.

```python
import h5py
import numpy as np

f = h5py.File('/tmp/data.hdf5', 'w')
f.create_dataset('x', (10,), dtype=h5py.vlen_dtype('bool'))
x = np.array([True, False, True, True, False, False, False])
print(x[::2]) # [ True  True False False]
f['x'][0] = x[::2]
print(f['x'][0]) # [ True False  True  True]
f['x'][0] = x[::2].copy()
print(f['x'][0]) # [ True  True False False]
```

**Comment by takluyver** [comment]
I'd guess this is the culprit - I think it copies a contiguous block of data from memory without considering that it may need strides:

https://github.com/h5py/h5py/blob/7a4966ac608f72f4b28ba1709f9d38bef5c7dde0/h5py/_conv.pyx#L822

I think we can get a Python buffer object for the numpy array, and use [PyBuffer_ToContiguous](https://docs.python.org/3/c-api/buffer.html#c.PyBuffer_ToContiguous) to copy the data correctly.

**Comment by takluyver** [comment]
If that makes sense to you, do you want to make a pull request?

**Comment by cydanil** [comment]
If it's up for grabs, I'd like to work on that.
I think that the example provided by @KurtAhn makes sense, but I don't know whether it's sufficient.

**Comment by takluyver** [comment]
@cydanil yup, go for it! I'm not exactly sure what you mean about sufficiency. If I've guessed the cause correctly, I think it affects using a non-contiguous view of a numpy array as an entry in a vlen dataset.
