### ISSUE TITLE
Remove old Cython workaround?

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#1661]
While working on the build scripts, I noticed there's an odd workaround which calls `cythonize()`, then checks to see if it worked, and if not, tries to run Cython in a subprocess as a fallback.

https://github.com/h5py/h5py/blob/ea576b3df60778f8d7b1b98f80bbbe0439a35394/setup_build.py#L115-L128

This was added in #541 in 2015. That PR refers to "old versions of setuptools (probably <0.7)". Setuptools 0.7 was released in 2013, so if that's the only problem it addresses, it's probably safe to assume people have a newer setuptools by now.

**Comment by aragilar** [comment]
I haven't seen the fallback run whenever I've built h5py, and given we need newer cython versions to build anyway, I think we should remove this (and if the cythonize function doesn't work, there's probably bigger issues going on). I think we can drop this.

**Comment by takluyver** [comment]
PR #1663 would remove this.
