### ISSUE TITLE
Missing module H5DS in low-level API Reference.

### ISSUE THREAD

**Issue by dota17** [h5py/h5py#1667]
In h5py low-level API [Reference](https://api.h5py.org), there is no module H5E and module H5DS, I don't know if this is intentional.

**Comment by takluyver** [comment]
H5E is deliberate, because there is no `h5py.h5e` module - we convert HDF5 errors into Python exceptions internally.

I don't think there's any particular reason H5DS is missing. Do you want to add it in the `docs_api` folder?

**Comment by dota17** [comment]
OK, I will do it in the next day.

**Comment by takluyver** [comment]
Specifically, we'll need a new file `h5ds.rst` - look at e.g. `h5pl.rst` to see what it should contain. And it will need to be added to the list in `index.rst`.
