### ISSUE TITLE
hd5f to access to nested structures in *.mat files

### ISSUE THREAD

**Issue by JControlReserch** [h5py/h5py#1668]
General information
 * Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 16.04.2 LTS, CentOS 7): **Windows 10**
 * Python version (e.g. 2.7, 3.5): **3.7.3**
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows): **Anaconda**
 * h5py version (e.g. 2.6): **2.9**
 * HDF5 version (e.g. 1.8.17) **1.10.4**
 * The full traceback/stack trace shown (if it appears)

I getting access to the following structure of matlab file (*.mat):
![image](https://user-images.githubusercontent.com/57429237/93149977-8ba01f00-f6bd-11ea-95af-d11ace49ab99.png)

which contains the following set of structures:

![image](https://user-images.githubusercontent.com/57429237/93150017-a4a8d000-f6bd-11ea-98f9-25ee83792b33.png)

I try to access to the fields inside each structure using hd5f python lib

![image](https://user-images.githubusercontent.com/57429237/93150042-b8543680-f6bd-11ea-968a-ef156bd56214.png)

using the following code:

```
mat_dict = h5py.File(file_path, 'r')
result = mat_dict['JKPRR']['results']['ChangingKnob'][0]['result']
```
But apparently I can't go deep from:

`result = mat_dict['JKPRR']['results']['ChangingKnob'][0]`

Do you know how I can go to the deeper fields?

**Comment by takluyver** [comment]
It's probably possible, but I'm not used to reading HDF5 structure in Matlab screenshots, so I don't know exactly what your file is.

What error do you get from `mat_dict['JKPRR']['results']['ChangingKnob'][0]['result']`? And what does the result look like when you get `mat_dict['JKPRR']['results']['ChangingKnob'][0]`.

**Comment by JControlReserch** [comment]
The error that I get is the following:
**mat_dict['JKPRR']['results']['ChangingKnob'][0]['result']**

![image](https://user-images.githubusercontent.com/57429237/93275028-62e15d80-f781-11ea-9904-189730da1f03.png)

If I try to access to upper level, that's the output
**mat_dict['JKPRR']['results']['ChangingKnob'][0]**

![image](https://user-images.githubusercontent.com/57429237/93275107-9d4afa80-f781-11ea-9064-bbd390fcde3c.png)

thats the code that I'm using to perform this task:


```
import h5py

# file: *.mat
file_path = os.path.join(location_path, file_name)
# load the file
mat_dict = h5py.File(file_path)
# this works
name = int_list_str(mat_dict[test_tag]['name'])
# this wors
description = int_list_str(mat_dict[test_tag]['description']) 
# this doesn´t work
result = mat_dict['JKPRR']['results']['ChangingKnob'][0]['result']

```

**Comment by vasole** [comment]
Can you print what is mat_dict['JKPRR']['results']['ChangingKnob'][0]?

**Comment by takluyver** [comment]
First, the easy bit: it looks like the `ChangingKnob` dataset is 2D, so to get one item out, you need two indices:

```python
mat_dict['JKPRR']['results']['ChangingKnob'][0, 0]

# This is equivalent but a bit easier to read:
mat_dict['JKPRR/results/ChangingKnob'][0, 0]
```

It looks like Matlab is storing HDF5 references (a kind of link) in the dataset, so then you need to follow the reference:

```python
ref = mat_dict['JKPRR/results/ChangingKnob'][0, 0]
dataset = mat_dict[ref]
```

Hopefully after that you can do `dataset['result']` to access one field, unless Matlab has made more obstacles.

**Comment by takluyver** [comment]
Closing this as it looks (from the :+1:) like it's resolved. We can continue the discussion or reopen it if needed.

To summarise for other people looking at this: Matlab's `.mat` files do appear to be HDF5, but they might be oddly structured and require some fiddling to work out how to get the data you want. You may want to use a HDF viewer tool like [HDFview](https://confluence.hdfgroup.org/display/HDFVIEW/HDFView) or [h5glance](https://github.com/European-XFEL/h5glance) to inspect it.
