### ISSUE TITLE
h5py.h5ds functions missing docstrings

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#1672]
Several of the low-level functions in `h5ds` are missing docstrings: https://api.h5py.org/h5ds.html

For low-level functions, the docstring also describes the function signature (parameters and return values). If tackling this, please look at other low-level functions (`h5py.h5*` modules) to see the expected format.

Once this is done, we can remove the `:undoc-members:` option for Sphinx autodoc (which includes functions without a docstring).

**Comment by dota17** [comment]
Great, I think I can tackle this.
