### ISSUE TITLE
Release 3.0

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#1673]
I think we're nearly ready to release h5py 3.0. What needs to be done?

- [x] Remaining pull requests to merge (please add any you think need to be in 3.0):
  - [x] #1666
  - [x] #1662
- [x] Generate release notes with rever & tidy up manually.
- [x] Tag release on Github
- [x] Generate wheels (Now done on CI, see #1674)
  - [x] Do we need to solve the uploading issues from https://github.com/MacPython/h5py-wheels/issues/11 ? Is this now easier if we generate wheels as part of our own CI, rather than in a separate repository?
  - [x] Are we still relying on Christoph Gohlke for Windows wheels?
- [ ] Upload wheels & sdist to PyPI

@h5py/team-h5py

**Comment by aufdenkampe** [comment]
Might this new release be able to include HDF5 v1.10.7, which was released on Sep. 15?

This new version boasts important performance improvements and full backward compatibility back to v1.10.3. See:
- [New Features Introduced in HDF5 1.10.7](https://portal.hdfgroup.org/display/HDF5/New+Features+in+HDF5+Release+1.10#NewFeaturesinHDF5Release1.10-1_10_7)
- [Compatibility and Performance Issues](https://portal.hdfgroup.org/display/HDF5/Software+Changes+from+Release+to+Release+for+HDF5-1.10#SoftwareChangesfromReleasetoReleaseforHDF5-1.10-issues)

**Comment by takluyver** [comment]
I'm hoping to include 1.12. I believe the files created are backwards compatible as long as they don't use new features, so it shouldn't be a problem to use the latest version.

**Comment by aufdenkampe** [comment]
Thanks for the quick response!

I'm glad to hear that you'll be updating to a newer HDF5 versions. 
HSF5 version 1.10.0 to 1.10.5 had some substantial performance issues when compared to v1.8 releases. v1.6 releases were even faster. See figure below and [Compatibility and Performance Issues](https://portal.hdfgroup.org/display/HDF5/Software+Changes+from+Release+to+Release+for+HDF5-1.10#SoftwareChangesfromReleasetoReleaseforHDF5-1.10-issues) for details.
![image](https://user-images.githubusercontent.com/5166036/94017961-a2a5d780-fd75-11ea-95e1-73ecaa236f80.png)

Version 1.10.7 helped get back closer to v1.8 performance, but v1.12 seems to slide back toward slower performance.

For those of us who are trying to get all performance we can get, I wonder if there might be a way to specify which HDF5 version is used by H5py?

For some info on our issues, see https://github.com/respec/HSPsquared/issues/36.

**Comment by takluyver** [comment]
> For those of us who are trying to get all performance we can get, I wonder if there might be a way to specify which HDF5 version is used by H5py?

Yes, you can always do that by building h5py from source. Instructions on installing from source start from here: https://docs.h5py.org/en/stable/build.html#source-installation

We provide pre-built binary packages on PyPI, for which we have to bundle a specific HDF5 version. I'm just working on how that happens (#1674), and I'm inclined to use the latest compatible HDF5. But you can always build it yourself with any supported HDF5 (currently back to 1.8.? - I don't know exactly which bugfix version still works).

**Comment by aufdenkampe** [comment]
That's perfect. Thanks!
