### ISSUE TITLE
Alternative to Google Groups?

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#1683]
H5py's discussion list is on Google Groups (https://groups.google.com/g/h5py ). It's not very busy, but there are a few threads per month, mostly users asking how to do something. @dota17 tells me that Google Groups is still not so easily accessible from China, which may be making it harder for people there to collaborate.

Should we consider switching to something else? We could:

1. Ask HDF group to create an h5py category on their [HDF Forum](https://forum.hdfgroup.org/) (Discourse)
2. Ask for a traditional [mailing list at python.org](https://mail.python.org/mailman3/lists/) (Mailman 3)
3. Point people to Github issues for questions & discussions - this can work surprisingly well for some projects.
4. Run something ourselves (probably either Discourse or Mailman)

I've put those roughly in the order I prefer (i.e. I don't want to run a server ourselves). Any other platforms we should consider?

**Comment by matthew-brett** [comment]
That order seems reasonable to me.  I personally prefer email, but Discourse is OK, and I can see that it would be easier for people who don't have good email clients.

**Comment by takluyver** [comment]
I think that Discourse makes it easier to dip in, because you can participate in a topic without subscribing to all messages. Whether that's desirable depends on your goals, but I'd note that the Google Group (which also allows joining without subscribing) is mainly used for user questions rather than in-depth development discussions.

**Comment by aragilar** [comment]
I'd remove 4 from the options.

I wonder if either 1 or 2 are blocked anywhere (I'm guessing Google Groups gets caught up in the blocking of Google - are there any other services blocked other than the big social media platforms)?

I personally like mailing lists (I'm not a fan of Discourse, I've found it sometimes limits you in weird ways if you're too new, and tries to make you engage in ways old-school phpbb forums didn't, which I find somewhat off-putting), but I think the advantages of having a h5py category on the HDF Discourse (there's less sending people to a different media to discuss things, h5py related questions on the HDF Discourse are more findable, and h5py maintainers usually need an account there anyway, so it not another login) outweigh the disadvantages. We may want an announce-only list (e.g. for releases), which is a thing Discourse does not cover, but that can be a separate discussion.

**Comment by tacaswell** [comment]
I would go with 1 or 4 (Matplotlib runs our own discourse, it is ~10$/mo but pretty low maintenance otherwise).

**Comment by takluyver** [comment]
I get the impression that option 1 (the HDF discourse forum) is something we're all happy enough with - some of us individually prefer other options, but that one seems closest to a consensus.

So, any objections to me asking HDF group to create a section on the forum? This could be for h5py specifically, or HDF5 & Python (i.e. also covering Pytables, netcdf4-python, and higher-level wrappers like pandas' HDF5 interface). I'll take silence as agreement in a few days.

If they're OK with that, I suggest we then set the Google group to only allow admins to post, so we're not scattering discussions over different venues. Obviously we should also make sure there's a clear link from the group page to the new venue.

**Comment by tacaswell** [comment]
Can you also ask that some of us get given privliages?

Do we want to try to export the google groups into discourse?  It is technically possible (I moved mailman history for Matplotlib, for google groups it seems you export to mailman format and then it is the same process) and may be a good way to jump-start the discussion there.

**Comment by loricooperhdf** [comment]
Hi, my coworker @jreadey alerted me to this discussion. I manage the HDF Forum and am happy to create a category there. I just need a decision of what to call it, and some words for the first starter post in that category and THG login names if anyone would like to be a category moderator. 

Although I have not checked with my coworkers in IT, I am in favor of importing the archives. (Holding all relevant content in one place seems important, you know...) This would also require internal discussion, but we have struggled to keep up with Discourse updates and could use a volunteer to help with that, if anyone was so inclined.

Feel free to reach out to me with any other questions.

**Comment by takluyver** [comment]
Thanks Lori! I was going to get in touch soon. :-)

I think we still have an open question over whether to aim for an 'h5py' category, or a more general 'HDF5 in Python'. Do you have a preference? Assuming it's possible to rename categories later, I think I'd suggest starting with 'h5py' and seeing how it gets used.

I'm in favour of importing the archives as well - I've found it useful on occasion that the old mailing list posts for HDF5 are also on the forum. I don't know if there are any legal implications to consider about personal information, although as the messages are all public anyway, it seems unlikely anyone would object in practice.

My username on the Discourse forum is 'thomas1' and I log in with my email thomas@kluyver.me.uk .

----

Suggested wording for an introductory post (feel free to adjust or expand this):

**h5py** is a Python wrapper of HDF5. It offers both a [Pythonic high-level API](https://docs.h5py.org/en/stable/) and a [low-level API](https://api.h5py.org/) which is more similar to the HDF5 C API.

This forum section is for questions, discussion and announcements about h5py, replacing the previous Google Group. If you think you have found a bug in h5py, please look at [h5py's GitHub issues](https://github.com/h5py/h5py/issues) to see if it has already been reported, and create a new issue there if not.

**Comment by loricooperhdf** [comment]
OK, I will go ahead and make this category live, unless you want to wait until you can get the archives in as well?

I have not talked to our IT team (of 2) about this yet. The IT person who helped me setup the forum and brought in our archives is no longer with THG, and it was a huge task for him to import the archives from mailman. Would you, or someone else trusted be willing to volunteer to do the import work? I would have to get the IT department’s OK or approval to move ahead with this, but they don’t have time to even keep our install up to date so I think some attention is better than none.

Thanks,

Lori

**Comment by takluyver** [comment]
Thanks Lori!

It looks like importing from a Google Group is [possible, but not entirely straightforward](https://meta.discourse.org/t/importing-mailing-lists-mbox-listserv-google-groups-emails/79773). I'm also not sure if there are any data protection implications of taking all that data and putting them onto another site. So maybe it's best to leave it where it is and point to the Google Group for old posts.

@tacaswell @aragilar et al: What do you think? How much effort is it worth putting in to get the old posts on Discourse?

**Comment by aragilar** [comment]
I think if there's not going to be an issue if we add the archives later, setting up the Discourse category and making the Google Group read-only is probably better to spend time on, rather than trying to export and import the archives.

**Comment by loricooperhdf** [comment]
I will go ahead and make this category live on the site tomorrow, since it seems there are no questions about moving ahead with that decision.

**Comment by loricooperhdf** [comment]
This is live now at https://forum.hdfgroup.org/c/hdf-tools/h5py

**Comment by takluyver** [comment]
Thanks Lori!

@tacaswell do you have the power to make the h5py Google group read-only so we can point people to Discourse for new discussions?

**Comment by tacaswell** [comment]
I do not seem to have any power over the google group, I hope @andrewcollette does.

**Comment by takluyver** [comment]
@andrewcollette if you see this, we've agreed to move mailing list style discussions to the HDF Group discourse forum (they have created a category for us), and now we'd like to lock the Google group to new posts, so we're not splitting discussions over two venues.

Could you make one of us (me, @tacaswell or @aragilar ) an admin on the Google group so we can do this and make sure it points people to the forum.

**Comment by takluyver** [comment]
Andrew got back to me, I've made the Google Group read-only (to be precise: posting restricted to group managers), with a final message pointing people to the forum instead. It's reversible if we ever want to go back to the Google Group.

Thanks everyone!
