### ISSUE TITLE
Wheels for Python 3.9

### ISSUE THREAD

**Issue by gmichaeljaison** [h5py/h5py#1692]
Currently, with Python 3.9, `pip install h5py` downloads and builds from source which raises the below exception.
Similar to [this issue](https://github.com/h5py/h5py/issues/1410), h5py needs wheels for Python 3.9

```
  copying h5py/tests/test_vds/test_lowlevel_vds.py -> build/lib.linux-x86_64-3.9/h5py/tests/test_vds
  copying h5py/tests/test_vds/__init__.py -> build/lib.linux-x86_64-3.9/h5py/tests/test_vds
  copying h5py/tests/test_vds/test_virtual_source.py -> build/lib.linux-x86_64-3.9/h5py/tests/test_vds
  copying h5py/tests/test_vds/test_highlevel_vds.py -> build/lib.linux-x86_64-3.9/h5py/tests/test_vds
  running build_ext
  Loading library to get version: libhdf5.so
  error: libhdf5.so: cannot open shared object file: No such file or directory
  ----------------------------------------
  ERROR: Failed building wheel for h5py
```

**Comment by takluyver** [comment]
It's a work in progress - see #1690. Like last time round, we need various other pieces of the ecosystem to support Python 3.9 first.

**Comment by takluyver** [comment]
In the meantime, you probably need libhdf5 installed on your system in order to build h5py from source. See the docs here: https://docs.h5py.org/en/latest/build.html#source-installation

**Comment by amrosado** [comment]
I'm also having problems building h5py in a python 3.9 environment and I had to revert back to python 3.8.

**Comment by joshsackos** [comment]
I just had the same issue with Python 3.9.0 on Ubuntu 20.04, and installing "libhdf5" as **takluyver** mentioned worked for me. My steps were:

1.) sudo apt install libhdf5
2.) pip3.9 install h5py

Thanks takluyver!

**Comment by AnonymousCodes911** [comment]
hi I am having issues building h5py on python3.9 I tried using the documentation that @takluyver  suggested but it didn't work.
