### ISSUE TITLE
Cannot import h5py on macos 10.12

### ISSUE THREAD

**Issue by t20100** [h5py/h5py#1701]
Issue found on macos10.12 with h5py wheel v3.0rc1 (tested with python3.7 and 3.8):

```
>>> import h5py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "py37env/lib/python3.7/site-packages/h5py/__init__.py", line 25, in <module>
    from . import _errors
ImportError: dlopen(py37env/lib/python3.7/site-packages/h5py/_errors.cpython-37m-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: py37env/lib/python3.7/site-packages/h5py/.dylibs/libsz.2.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in py37env/lib/python3.7/site-packages/h5py/.dylibs/libsz.2.dylib
```
It is fine with h5py 2.10.0.

It sounds wheels were built without setting `MACOSX_DEPLOYMENT_TARGET` environment variable set to enable backward compatibility.

**Comment by t20100** [comment]
According to [cibuildwheel](https://pypi.org/project/cibuildwheel/), this should be set since version 1.4.0:

> 🛠 On macOS, we make MACOSX_DEPLOYMENT_TARGET default to 10.9 if it's not set. This should make things more consistent between Python versions.

**Comment by takluyver** [comment]
Thanks for testing - I don't have easy access to any Macs to test on. Would you like to make a PR? Azure now builds wheels for every commit, so it should be easy to download the relevant one manually and try it out. I think this is where the setting would be needed:

https://github.com/h5py/h5py/blob/deb80dd3ed916e49345d8e39432a38142b803fff/azure-pipelines.yml#L55-L57

**Comment by t20100** [comment]
The missing symbol actually comes from libhdf5 (and libsz) which comes from homebrew.
I'm looking into it.

**Comment by takluyver** [comment]
Maybe we need to compile HDF5 ourselves for the wheel builds, rather than relying on HDF5 from Homebrew? We've already got the scripts there to build it from source, so it shouldn't be too hard if that's what we need to do.

**Comment by t20100** [comment]
It depends how far you want to be backward compatible.
10.12 is no longer supported by macos, but I first get the issue on travis with the default macos config: 10.13.6 (https://travis-ci.org/github/silx-kit/silx/jobs/732009217).

For building HDF5, you mean the `ci/travis/get_hdf5_if_needed.sh` script? I'm giving it a try.

**Comment by takluyver** [comment]
> It depends how far you want to be backward compatible.

I don't have a good feel for how quickly old Mac OS versions can be dropped. But if setting an environment variable and building HDF5 from source can easily extend support to older versions, I'm happy for it to support as far back as you want.

> For building HDF5, you mean the ci/travis/get_hdf5_if_needed.sh script? 

Yup! Thanks :slightly_smiling_face:
