### ISSUE TITLE
Works with new HDF5 v1.12.0 VOL plugins?

### ISSUE THREAD

**Issue by MichaelLaufer** [h5py/h5py#1709]
Hi,
I understand that h5py now supports HDF5 v1.12.0. 
Does it support the new VOL features/plugins?
In particular I am interested in support for [asynchronous IO](https://sc19.supercomputing.org/proceedings/workshops/workshop_files/ws_pdsw109s2-file1.pdf) and [Intel DAOS](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwj628qZvbbsAhUQDOwKHR3wBQgQFjABegQIBRAC&url=https%3A%2F%2Fwiki.hpdd.intel.com%2Fdownload%2Fattachments%2F98341354%2FHDF5%2520DAOS%2520VOL%2520plugin.pdf%3Fversion%3D1%26modificationDate%3D1542638338000%26api%3Dv2&usg=AOvVaw2tT4W175n7MB_vJAtWFe6T) support.
I found this [h5pyVOL](https://github.com/pierlauro/H5PyVOL) repo, which is relavant, but does not appear to be active anymore. @pierlauro :)

Thanks.

**Comment by pierlauro** [comment]
Hi,
if no major happened on the VOL interface in the last months, everything should work fine with h5py and VOL. You just need to set the proper environment variables to let instruct the HDF library to use the DAOS connector.

The purpose of h5pyvol was to give an easy way to write a connector in Python, so I guess it's out of scope if you just want to plug existing connectors :)

**Comment by takluyver** [comment]
I'm going to close this as I don't think there's anything for h5py to do at the moment.
