### ISSUE TITLE
Disable file locking when opening a file in read only mode?

### ISSUE THREAD

**Issue by vasole** [h5py/h5py#1722]
Would it be possible to disable file locking when opening a file in read-only mode?

Users are quite aware that if they do not want to modify a file they have to open it in read only mode. However, they are not aware that despite opening the file in read-only mode they are blocking the access to the file by other processes.

I would like to know if that behavior would be accepted (not locking the file when accessing in read-only) prior to consider a PR.

**Comment by takluyver** [comment]
AFAIK, this is part of how HDF5 is designed: read mode assumes that the file is not changing underneath it, so locking prevents you from modifying it while it is open for reading. There are two exceptions to that:

- SWMR mode allows certain kinds of modifications in coordination with reader processes
- You can disable file locking by setting the environment variable `HDF5_USE_FILE_LOCKING=FALSE`. There's no other protection, so if you do this it's up to you to ensure a file is not modified while you're reading it.

I'm -1 on h5py disabling HDF5's locking by default. If you don't like the options available, I'd suggest talking to HDF group.

**Comment by takluyver** [comment]
I'll close this at some point unless one of the other maintainers wants to argue in favour of it. I'm still against h5py altering HDF5's default file locking behaviour: I believe HDF5 locks files for a good reason, and if you're unhappy with it, it's better to discuss that with the HDF group than to override their decisions in h5py.

**Comment by takluyver** [comment]
Closing for the reasons described above. It's possible that HDF5 will at some point remove file locking entirely (see discussion on #2137), but I don't think we should do that in advance. There's an environment variable to disable locking if you really want to.
