### ISSUE TITLE
Dataset.dims.items() is not iterable

### ISSUE THREAD

**Issue by quazgar** [h5py/h5py#1724]
* Operating System: Debian 10
 * Python version: 3.7.3 from distro's repository
 * h5py version: 2.8.0 from distro's repository
 * HDF5 version: 1.10.4

## Problem

`h5py.Dataset.dims.items()` is not iterable, although it would be great if it was.  When trying to iterate over the dimensions (for example for printing them all), a `TypeErrror` is raised:

```
[d for d in ds.dims.items()]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[...]
----> 1 [d for d in ds.dims.items()]

/usr/lib/python3/dist-packages/h5py/_hl/base.py in __iter__(self)
    340         with phil:
    341             for key in self._mapping:
--> 342                 yield (key, self._mapping.get(key))
    343
    344

/usr/lib/python3.7/_collections_abc.py in get(self, key, default)
    658         'D.get(k[,d]) -> D[k] if k in D, else d.  d defaults to None.'
    659         try:
--> 660             return self[key]
    661         except KeyError:
    662             return default

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

/usr/lib/python3/dist-packages/h5py/_hl/dims.py in __getitem__(self, index)
    155         """ Return a Dimension object
    156         """
--> 157         if index > len(self) - 1:
    158             raise IndexError('Index out of range')
    159         return DimensionProxy(self._id, index)

TypeError: '>' not supported between instances of 'DimensionProxy' and 'int'
```

Summary of the h5py configuration
---------------------------------

h5py    2.8.0
HDF5    1.10.4
Python  3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.16.2

**Comment by takluyver** [comment]
This was already reported as #744. For 3.0, `ds.dims` will behave like a sequence, rather than a mapping, so there is no `ds.dims.items()` method.
