### ISSUE TITLE
Do we need to move away from Travis CI?

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#1733]
Travis have [made a blog post](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) which appears to say that, effective immediately, free users will be 'upgraded' to a trial plan with a one-time allocation of 10k credits (equivalent to 1000 minutes). After that, we'd have to request an allocation of OSS credits. It's not very clear, but it sounds like that's a manual process, you might get a one-time allocation rather than a recurring one, and possibly there's even a limited pool of credits for all OSS projects.

If that's the case, Travis looks like a pretty unappealing option compared to our other CI services. It's not clear what's actually going on, though - one of my colleagues got an email this morning saying he would get 1k credits per month. If that was the case, we might be OK if we're careful about what runs on Travis.

We currently use Travis for:

- ppc64le builds (cc @kif) - I'm not aware where else we can do this if Travis is unavailable. But [this IBM blog post](https://developer.ibm.com/technologies/linux/tutorials/travis-ci-on-power/) suggests IBM provided the servers for Travis to help open-source projects, so perhaps they'll ensure there's still some option.
- Low-level API docs - [doctr](https://drdoctr.github.io/) has specific integration with Travis which makes this very convenient, but we could use any CI service with a bit more work.
- MPI tests - @aragilar, was there a specific reason these were on Travis?
- Allowed failure builds on Python nightly and Pypy. We don't pay any attention to these anyway, so no great loss, and they could go to other services if we needed them.

**Comment by aragilar** [comment]
Yeah, it really unclear whether that's a monthly thing, or a one off. For MPI, I did try to move it to azure pipelines, but there were odd issues around it timing out, so I left it on Travis (as it seemed to work there).

I haven't received any emails from Travis about the change (maybe they're doing some kind of rollout about who gets the emails in relation to when the service switches over).

**Comment by takluyver** [comment]
There's also the added complexity that is still - for now - on travis-ci.org, which has no billing. I think everything is meant to migrate to travis-ci.com within a few months.

**Comment by yousef92-tech** [comment]
Why not use GitHub actions instead of Travis CI? You get unlimited minutes/month. I can help with creating and maintaing the pipeline if needed.

**Comment by takluyver** [comment]
We already use other CI services, especially Azure pipelines (which is similar to Github actions). But there are some specific things that are easier (or perhaps even only possible) on Travis, hence this discussion.

**Comment by kif** [comment]
Hi Thomas,

We tried to move `silx` to Travis.com and run out of credits within a week ...

So you reading is correct and we are also thinking "hard" on a solution.

Cheers,

Jerome

**Comment by takluyver** [comment]
@aragilar moved the MPI jobs to Azure in #1766. I think it should be reasonably practical to do the low-level API docs on Github actions (as it publishes to Github pages anyway) - we just need to get round to doing that.

That only leaves the powerpc jobs - I've not seen that any other free service has powerpc available. We'll probably have to drop that unless someone finds an alternative. I think the little-endian builders on Travis are less useful than getting regular tests on a big-endian machine would be, in any case. Big-endian CI should have caught the worst issues with 3.0, which in the event were only discovered after release.

**Comment by aragilar** [comment]
I wonder if we should email https://osuosl.org/services/, and see if they would happy to run CI for h5py (they also seem to have ARM64, and IBM Z (!), the latter being big-endian). There's also https://openpower.ic.unicamp.br/minicloud/. Both are linked from https://power-developer.mybluemix.net/#hardware.

**Comment by takluyver** [comment]
I guess that would be a good idea. I don't relish the idea of maintaining Jenkins config again, though. Maybe things have got better since I last had to deal with it. :crossed_fingers:

**Comment by takluyver** [comment]
This seems to be OK for now :crossed_fingers: . We still use Travis for ppc64le and arm64 builds, which are free through Travis' [Partner Queue Solution](https://docs.travis-ci.com/user/billing-overview/#partner-queue-solution) mechanism - i.e. IBM and ARM sponsor open source builds on these architectures. Everything else has moved to other CI platforms.
