### ISSUE TITLE
Dataset read returning wrong values for big-endian datasets

### ISSUE THREAD

**Issue by jreadey** [h5py/h5py#1738]
Reading big-endian datasets is returning incorrect values.  This is with the test file https://s3.amazonaws.com/hdfgroup/data/hdf5test/tall.h5. (wget it before running test):

With h5py 3.0 I get:

    >>> import h5py
    >>> h5py.version.version
    '3.0.0'.  
    >>> h5py.version.hdf5_version
    '1.12.0' 
    >>> f = h5py.File("tall.h5", "r")
    >>> dset = f["/g1/g1.1/dset1.1.2"]
    >>> dset
    <HDF5 dataset "dset1.1.2": shape (20,), type ">i4">
    >>> arr = dset[...]
    >>> arr[1]
    16777216

With h5py 2.9 I get:

    >>> import h5py
    >>> h5py.version.version
    '2.9.0'.  
    >>> h5py.version.hdf5_version
    '1.10.4' 
    >>> f = h5py.File("tall.h5", "r")
    >>> dset = f["/g1/g1.1/dset1.1.2"]
    >>> dset
    <HDF5 dataset "dset1.1.2": shape (20,), type ">i4">
    >>> arr = dset[...]
    >>> arr[1]
    1

This is with:
 CentOS 8, Python 3.8
 Pip install
  h5py, hdf5 versions as indicated

**Comment by takluyver** [comment]
Thanks John! I think this is the same as #1729, which was already fixed in master. There are a few more small fixes I'd like to merge (#1731 #1734 #1737), then I'm planning to do a release.
