### ISSUE TITLE
test_vlen_big_endian and test_custom_float_promotion fail on s390x and other arches

### ISSUE THREAD

**Issue by drew-parsons** [h5py/h5py#1745]
* Operating System: Debian unstable
 * Python version 3.8
 * system python3.8     3.8.6-1
 * h5py version 3.0.0
 * HDF5 version 1.10.6

```
$python3 -c 'import h5py; print(h5py.version.info)'
h5py    3.0.0
HDF5    1.10.6
Python  3.8.6 (default, Sep 25 2020, 09:36:53) 
[GCC 10.2.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.19.4
cython (built with) 0.29.21
numpy (built against) 1.19.4
HDF5 (built against) 1.10.6
```

Two tests are failing on various arches when trying to build h5py 3.0.0 for Debian unstable.  The failing arches are s390x and hppa, powerpc, ppc64. Build logs are found at https://buildd.debian.org/status/package.php?p=h5py&suite=experimental
e.g. https://buildd.debian.org/status/fetch.php?pkg=h5py&arch=s390x&ver=3.0.0-1exp1&stamp=1604656628&raw=0

The failing tests are `test_vlen_big_endian` from `test_big_endian_file.py`, and `TestTypeFloatID.test_custom_float_promotion` from `test_h5t.py`. Both tests seem to involve float conversions.

The error message for `test_vlen_big_endian` is 
```
_____________________________ test_vlen_big_endian _____________________________

    def test_vlen_big_endian():
        with File(get_data_file_path("vlen_string_s390x.h5")) as f:
            assert f.attrs['created_on_s390x'] == 1
    
            dset = f['DSvariable']
            assert dset[0] == b'Parting'
            assert dset[1] == b'is such'
            assert dset[2] == b'sweet'
            assert dset[3] == b'sorrow...'
    
            dset = f['DSLEfloat']
>           assert dset[0] == 3.14
E           assert 7.9824696849641e-157 == 3.14
E             -7.9824696849641e-157
E             +3.14

build/h5py/_debian_h5py_serial/tests/test_big_endian_file.py:18: AssertionError
```

The error for `test_custom_float_promotion` is 
```
_________________ TestTypeFloatID.test_custom_float_promotion __________________

self = <h5py._debian_h5py_serial.tests.test_h5t.TestTypeFloatID testMethod=test_custom_float_promotion>

    def test_custom_float_promotion(self):
...
        # ebias promotion to float32
        values = f[dataset][:]
>       np.testing.assert_array_equal(values, wdata)
E       AssertionError: 
E       Arrays are not equal
E       
E       Mismatched elements: 28 / 28 (100%)
E       Max absolute difference: 1.5006663e-09
E       Max relative difference: 1.
E        x: array([[5.951617e-39, 1.182389e-38, 5.903008e-39, 1.183393e-38,
E               5.961840e-39, 5.584735e-41, 1.082923e-41],
E              [5.951617e-39, 1.763428e-38, 1.182245e-38, 1.763679e-38,...
E        y: array([[-1.500666e-09,  1.400622e-09,  1.812168e-10,  4.010872e-10,
E                4.279173e-10, -7.048584e-11,  5.748007e-10],
E              [-1.500666e-09,  4.865797e-10,  3.428795e-10,  5.120455e-10,...

build/h5py/_debian_h5py_serial/tests/test_h5t.py:167: AssertionError
```

**Comment by takluyver** [comment]
The issue with `test_vlen_big_endian` was already reported (#1739) and fixed. I'm getting ready to do a new release with that.

@opoplawski didn't run into any failures with `test_custom_float_promotion` on s390x for Fedora. Can the two of you work out what the important difference is, and what's going on with that test?

**Comment by drew-parsons** [comment]
I see in #1739 @opoplawski reported both the same errors.
From https://github.com/h5py/h5py/issues/1739#issuecomment-721475925, looks like test_custom_float_promotion must have been fixed by the first patch.

**Comment by takluyver** [comment]
Ah, my mistake - I must have read it too quickly and only seen the one error.

In that case, 3.1 is coming soon, and should fix all of this. Given these bugs, I'd suggest packagers skip 3.0.

**Comment by drew-parsons** [comment]
Thanks!  I've got 3.0 in the Debian experimental archive for, now. Looking forward to 3.1.

I've got an mpi test anomaly which I'll report separately.
