### ISSUE TITLE
test_file::TestMPI tests are always skipped 

### ISSUE THREAD

**Issue by drew-parsons** [h5py/h5py#1746]
Hi @aragilar, I'm trying the test the new MPI tests in h5py 3.0.0 on Debian unstable.  pytest-mpi is installed.
The problem is that the TestMPI tests in test_file.py are _always_ skipped.

I've separated test_file.py on its own and added some print statements to confirm that the MPI build is indeed being accessed (Debian provides both serial and mpi builds).  pytest reports:
```
$ mpirun -n 2 pytest-3 -vv -s -k TestMPI
============================= test session starts ==============================
platform linux -- Python 3.8.6, pytest-4.6.11, py-1.9.0, pluggy-0.13.0 -- /usr/bin/python3
============================= test session starts ==============================
platform linux -- Python 3.8.6, pytest-4.6.11, py-1.9.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/drew/projects/python/build/test/h5py-tests/.hypothesis/examples')
rootdir: /home/drew/projects/python/build/test/h5py-tests
plugins: forked-1.3.0, xdist-1.32.0, doctestplus-0.7.0, astropy-header-0.1.2, asyncio-0.14.0, hypothesis-5.32.1, filter-subpackage-0.1.1, cov-2.8.1, remotedata-0.3.2, mpi-0+unknown, arraydiff-0.3, openfiles-0.5.0
cachedir: .pytest_cache
collecting ... hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/drew/projects/python/build/test/h5py-tests/.hypothesis/examples')
rootdir: /home/drew/projects/python/build/test/h5py-tests
plugins: forked-1.3.0, xdist-1.32.0, doctestplus-0.7.0, astropy-header-0.1.2, asyncio-0.14.0, hypothesis-5.32.1, filter-subpackage-0.1.1, cov-2.8.1, remotedata-0.3.2, mpi-0+unknown, arraydiff-0.3, openfiles-0.5.0
collecting ... using h5py [h5py._h5py]:  <module 'h5py._debian_h5py_mpi' from '/usr/lib/python3/dist-packages/h5py/_debian_h5py_mpi/__init__.py'>
supports MPI [h5py.get_config().mpi]:  True
using h5py [h5py._h5py]:  <module 'h5py._debian_h5py_mpi' from '/usr/lib/python3/dist-packages/h5py/_debian_h5py_mpi/__init__.py'>
supports MPI [h5py.get_config().mpi]:  True
collected 57 items / 54 deselected / 3 selected                                

tests/test_file.py::TestMPI::test_mpio SKIPPED
tests/test_file.py::TestMPI::test_mpi_atomic SKIPPED
collected 57 items / 54 deselected / 3 selected                                


=================== 3 skipped, 54 deselected in 0.08 seconds ===================

tests/test_file.py::TestMPI::test_mpio SKIPPED
tests/test_file.py::TestMPI::test_mpi_atomic SKIPPED
tests/test_file.py::TestMPI::test_close_multiple_mpio_driver SKIPPED

=================== 3 skipped, 54 deselected in 0.08 seconds ===================
```

Any idea what's gone wrong?  Could the Debian coinstallable build (serial and mpi both accessible) be inculpated? Or is this one of the things fixed for h5py 3.1?

Build logs at https://buildd.debian.org/status/package.php?p=h5py&suite=experimental
i.e. https://buildd.debian.org/status/fetch.php?pkg=h5py&arch=amd64&ver=3.0.0-1exp1&stamp=1604655422&raw=0

 * Operating system: Debian unstable
 * h5py 3.0.0
 * pytest 4.6.11-1
 * pytest-mpi 0.4-2
```
$ python3 -c 'import h5py; print(h5py.version.info)'
Summary of the h5py configuration
---------------------------------

h5py    3.0.0
HDF5    1.10.6
Python  3.8.6 (default, Sep 25 2020, 09:36:53) 
[GCC 10.2.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.19.4
cython (built with) 0.29.21
numpy (built against) 1.19.4
HDF5 (built against) 1.10.6
```

**Comment by takluyver** [comment]
Looking at https://pytest-mpi.readthedocs.io/en/latest/usage.html , I believe you need a `--with-mpi` flag. Or you can run the tests through tox, as described here: https://docs.h5py.org/en/stable/contributing.html#testing-mpi-only-features-code

**Comment by drew-parsons** [comment]
You're right, `pytest --with-mpi` gets the MPI tests running.  I had seen that flag, but thought it was for building h5py with MPI, didn't realize it's also for running the pytest-mpi tests.

`pytest --with-mpi` works in serial mode too, where it launches the mpi tests and generates the error `ValueError: h5py was built without MPI support, can't use mpio driver`, as you'd expect for the serial build.

**Comment by drew-parsons** [comment]
You're right, `pytest --with-mpi` gets the MPI tests running.  I had seen that flag, but thought it was for building h5py with MPI, didn't realize it's also for running the pytest-mpi tests.

`pytest --with-mpi` works in serial mode too, where it launches the mpi tests and generates the error `ValueError: h5py was built without MPI support, can't use mpio driver`, as you'd expect for the serial build.
