### ISSUE TITLE
Erroneous 'No space left on device' error while creating dataset.

### ISSUE THREAD

**Issue by nanthony21** [h5py/h5py#1749]
I am trying to save a series of hdf5 files to a QNAP NAS from my Windows 10 computer. The computer is connected to the NAS as a shared windows folder (SMB). The final hdf5 files aren't that large (<200MB). While writing the files I will randomly get the error shown below. The NAS has over 100TB of free space so I know that the "No space left on device" message isn't correct.

I don't know for sure that this is an issue with h5py rather than some other issue but I'm hoping that someone will have some advice. One thing that caught my eye is that even though `total write size = 190840832`, the message says: `bytes actually written = 18446744073709551615`. Why would the bytes written be so huge?

Operating System: Windows 10 writing to QTS NAS over local network.

h5py    2.10.0
HDF5    1.10.4
Python  3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.19.2

Traceback:
```
  File "C:\Users\backman05\Documents\Bitbucket\pwspython\src\pwspy\dataTypes\_data.py", line 325, in toHdfDataset
    dset = g.create_dataset(name, data=fpData)  # , chunks=(64,64,self.data.shape[2]), compression=2)
  File "C:\Users\backman05\Anaconda3\envs\pwspyDev\lib\site-packages\h5py\_hl\group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "C:\Users\backman05\Anaconda3\envs\pwspyDev\lib\site-packages\h5py\_hl\dataset.py", line 170, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5d.pyx", line 222, in h5py.h5d.DatasetID.write
  File "h5py\_proxy.pyx", line 132, in h5py._proxy.dset_rw
  File "h5py\_proxy.pyx", line 93, in h5py._proxy.H5PY_H5Dwrite
OSError: Can't write data (file write failed: time = Fri Nov  6 18:57:26 2020
, filename = '//backmanlabnas/AcquiredData/Nick/ITOPositionStability\Cell1\PWS\analyses\analysisResults_p0.h5', file descriptor = 5, errno = 28, error message = 'No space left on device', buf = 0000027B8B638040, total write size = 190840832, bytes this sub-write = 190840832, bytes actually written = 18446744073709551615, offset = 2083)
```

**Comment by takluyver** [comment]
Is it possible you're using [SWMR](https://docs.h5py.org/en/stable/swmr.html)? If this is code you wrote yourself, you'd need to have explicitly enabled it, but if you're using some wrapper module, it may use SWMR for you. I can find references to SWMR not being supported on SMB.

Otherwise, here's someone last year who appears to have seen similar problems with reading, also on HDF5 1.10.4: https://forum.hdfgroup.org/t/errors-accessing-hdf5-over-cifs-and-or-nfs/6341

**Comment by nanthony21** [comment]
@takluyver Thanks for getting back to me. 

I'm not using SWMR or any other non-basic usage of h5py. So I can rule that out.

Unlike the person in the link you sent, I am seeing this issue much more commonly, about1 in 3 file writes fail. Also I'm only seeing this during writing, not reading and it always give me the same error.

I updated to h5py: 3.1.0 and HDF5: 1.10.6 but the same issue persists.

Right now I've only seen this in the context of a larger application which is somewhat complicated. I tried a simple example that uses h5py to write a series of files containing large numpy arrays but I wasn't able to reproduce the issue. I'll keep working on making a simple example that reproduces the issue and I'll post it here.

**Comment by nanthony21** [comment]
After converting the storage on the NAS that I was writing to from a "thin volume" to a "thick volume" I am no longer seeing this issue. More information here: https://www.qnap.com/en/how-to/knowledge-base/article/what-is-the-difference-between-static-volume-thin-volume-and-thick-volume/

**Comment by nanthony21** [comment]
Actually, it appears that the same issue is still occurring after switching from thin volume to thick volume

**Comment by nanthony21** [comment]
I think that the part of the message saying `bytes actually written = 18446744073709551615` may be important since this is a huge number that would definitely trigger `No Space Left On Device` on any system. One thing I notice is that the number given for `bytes actually written` is equal to 2^64. Is it possible that there is some sort of integer overflow going on here?

**Comment by nanthony21** [comment]
It appears that by opening the h5py.File with a reference to a python file object rather than using the default driver I am able to bypass this issue.

So instead of:
```
with h5py.File(filePath, 'w') as hf:
   doStuff
```

I am now doing:
```
with open(filePath, 'wb') as pythonFile:
   with h5py.File(pythonFile, 'w', driver='fileobj') as hf:
      doStuff
```
