### ISSUE TITLE
dataset can not downald

### ISSUE THREAD

**Issue by zhou-rui1** [h5py/h5py#1752]
How to downald the datasets (zip) now ?

**Comment by takluyver** [comment]
If you want to download an entire file before opening it with h5py, you need to do that outside h5py. If you want to download it in Python, [requests](https://requests.readthedocs.io/en/master/) is the most popular library for using HTTP to fetch data.

There are projects aiming to expose HDF5 over HTTP requests so you can download just part of a large file. If that's what you're interested in, see the HDF group's HSDS project: https://github.com/HDfGroup/hsds
