### ISSUE TITLE
Allow Blocks to overlap

### ISSUE THREAD

**Issue by sehoffmann** [h5py/h5py#1754]
I want to use MultiBlockSlices for a windowing oepration. The check in https://github.com/h5py/h5py/blob/3.1.0/h5py/_selector.pyx#L397 prevents me from doing so. Is there are technical reason for this?

**Comment by takluyver** [comment]
It looks like HDF5 also prevents that, even if h5py allowed it:

https://github.com/HDFGroup/hdf5/blob/04e50c876cfa48458402b2fa8a412feed472b58e/src/H5Shyper.c#L9925-L9927

I'm not an expert, but I'd hope there are more efficient ways of doing a windowing operation than duplicating each piece of data several times in memory.

**Comment by sehoffmann** [comment]
I've resorted to perform the windowing operation in numpy now, which has proven to be extremly fast as well (e.g compared to virtual datasets).

```
def as_windowed(arr: np.ndarray, window: int):
    """
    Returns an array with an additional dimension of size `window`
    such that x[i, j] of the new array corresponds to arr[i+j] of the original array.

    If arr has shape (s[0], ..., s[n]) then the new array has shape (s[0] - window + 1, window, s[1], ..., s[n]).
    
    The returned array is a view into the original array which makes this operation extremly fast.
    As a direct consequence however, the returned array is not writeable.
    """
    shape = list(arr.shape)
    strides = list(arr.strides)

    new_shape = tuple([shape[0] - window + 1, window] + shape[1:])
    new_strides = tuple([strides[0], strides[0]] + strides[1:])
    
    return np.lib.stride_tricks.as_strided(arr, new_shape, new_strides, writeable=False)
```

```
arr = ds[self.i * self.batch_size : (self.i + 1) * self.batch_size + window - 1]
arr = as_windowed(arr, window)
```
