### ISSUE TITLE
Unable to decode strings with asstr()[0]

### ISSUE THREAD

**Issue by jtebert** [h5py/h5py#1756]
To assist reproducing bugs, please include the following:
 * Operating System (MacOS 10.14)
 * Python version (3.7)
 * h5py version (3.1.0)
 * HDF5 version (1.10.2_1)

I am having trouble correctly accessing a string dataset saved with h5py as [described in the documentation](https://docs.h5py.org/en/stable/high/dataset.html#h5py.Dataset.asstr).

As a minimal example, here's what I'm doing. First, saving a string dataset:
```python
h5_file.create_dataset('dset_name', data='some-string', dtype=h5py.string_dtype('utf-8'))
```

Then I try to get it from the file with the `.asstr()` method:
```python
h5_file['dset_name'].asstr()[0]
```
which results in the following error + stack trace:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/-----------------/venv/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 203, in __getitem__
    bytes_arr = self.dset[args]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/-----------------/venv/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 766, in __getitem__
    selection = sel2.select_read(fspace, args)
  File "/Users/-----------------/venv/lib/python3.7/site-packages/h5py/_hl/selections2.py", line 101, in select_read
    return ScalarReadSelection(fspace, args)
  File "/Users/-----------------/venv/lib/python3.7/site-packages/h5py/_hl/selections2.py", line 86, in __init__
    raise ValueError("Illegal slicing argument for scalar dataspace")
ValueError: Illegal slicing argument for scalar dataspace
```

If, instead, I call `h5_file['dset_name'].asstr()[...]`, I am able to see that the string is stored in there:
```python
array('some-string', dtype=object)
```
but I can't figure out how to actually retrieve it. When I call `.shape` on that output, it returns `()`, which does explain the above error that it's a "scalar" database.

But I'm not sure what form this data is *supposed to be* in, to be accessed as the documentation describes. Is it an issue with the way I saved the string in the first place?

**Comment by aragilar** [comment]
@jtebert The object you've created is a [numpy scalar (0-d array)](https://numpy.org/doc/stable/reference/arrays.scalars.html). There are subtle differences between it and a 1-d array, one of which is the indexing is different (see the bottom of the numpy link).

`h5_file['dset_name'].asstr()[()]` should give you back a python string (the use of `()` isn't unique to strings, if you saved a scalar int or float, you would need to do the same indexing).

**Comment by jtebert** [comment]
I ended up figuring this out shortly before you posted this. Using `[()]` is some weird syntax that feels rather non-pythonic. Is this specific to h5py, or is that used elsewhere?

**Comment by aragilar** [comment]
`[()]` is from numpy, which I think comes from how `__getitem__` works (as I think the idea is to make the scalar not iterable). Generally I've avoided the issue of dealing with scalars by saving scalars as attributes (which automatically does the slicing of the scalar).
