### ISSUE TITLE
Using tuple as dataset index raises TypeError

### ISSUE THREAD

**Issue by Xarthisius** [h5py/h5py#1757]
### How to reproduce?

```python
import h5py

with h5py.File("test.h5", mode="w") as h5f:
    dset = h5f.create_dataset("matrix", (2, 2), dtype="=f8")

with h5py.File("test.h5", mode="r") as h5f:
    print(h5f["matrix"][0, (0, 1)])
```

### Actual result

```
Traceback (most recent call last):
  File "bug.py", line 7, in <module>
    print(h5f["matrix"][0, (0, 1)])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File ".../h5py/_hl/dataset.py", line 777, in __getitem__
    selection = sel.select(self.shape, args, dataset=self)
  File ".../h5py/_hl/selections.py", line 82, in select
    return selector.make_selection(args)
  File "h5py/_selector.pyx", line 269, in h5py._selector.Selector.make_selection
  File "h5py/_selector.pyx", line 210, in h5py._selector.Selector.apply_args
TypeError: not all arguments converted during string formatting
```

### Expected result

```
[0. 0.]
```

### System info

* Operating System: Ubuntu 18.04.5 LTS
* Python version: 3.8.6
* Where Python was acquired: apt

Bisection result:
```text
474ef53d2698f6fa8988df2a2ec99525863bc8c4 is the first bad commit
commit 474ef53d2698f6fa8988df2a2ec99525863bc8c4
Author: Thomas Kluyver <thomas@kluyver.me.uk>
Date:   Thu Apr 2 15:37:32 2020 +0100

    Use selector in creating selections
```

**Comment by takluyver** [comment]
This is actually deliberate, and it matches NumPy, as [documented here](https://numpy.org/doc/stable/user/basics.indexing.html#index-arrays):

> NumPy arrays may be indexed with other arrays (or any other sequence- like object that can be converted to an array, such as lists, with the exception of tuples; see the end of this document for why this is).

(The 'end of this document' being [this section](https://numpy.org/doc/stable/user/basics.indexing.html#dealing-with-variable-numbers-of-indices-within-programs))

**Comment by Xarthisius** [comment]
> This is actually deliberate, and it matches NumPy, as [documented here](https://numpy.org/doc/stable/user/basics.indexing.html#index-arrays):
> 
> > NumPy arrays may be indexed with other arrays (or any other sequence- like object that can be converted to an array, such as lists, with the exception of tuples; see the end of this document for why this is).
> 
> (The 'end of this document' being [this section](https://numpy.org/doc/stable/user/basics.indexing.html#dealing-with-variable-numbers-of-indices-within-programs))

Just to be clear: my fix for it is wrong, cause it converts a tuple to a list, but in general indexing with tuples should be possible, right?

**Comment by Xarthisius** [comment]
It matches what's numpy is doing:

```
import numpy as np
>>> a = np.ones((2,2))
>>> a[0, (0, 1)]
array([1., 1.])
```

**Comment by takluyver** [comment]
The rationale against doing this is that you get weird behaviour if you only index with a tuple. `ds[(1, 2)]` is semantically exactly the same as `ds[1, 2]`, i.e. a single index in two dimensions. So `ds[(1, 2)]` ends up meaning something totally different from `ds[(1, 2),]`, when in all other cases `ds[a] == ds[a,]`. Given that the caller can always convert the tuple to a list or array before passing it, I'd say it's better to avoid the ambiguity and reject tuples altogether.

It's somewhat disappointing that what NumPy is actually doing differs from what its docs say (at least as I read them). Maybe that's reason enough to make it work in h5py too. Not sure.
