### ISSUE TITLE
pip install h5py stops with error on Jetson NX

### ISSUE THREAD

**Issue by ArefAz** [h5py/h5py#1760]
Hi,

I have a problem installing h5py on my device.

 * Operating System: Ubuntu 18.04 aarch64
 * Python version: 3.6
 * How Python acquired: /usr/bin/python3 -m venv venv

Traceback:

[h5py_error.txt](https://github.com/h5py/h5py/files/5547777/h5py_error.txt)

Please help me fix this.
Thanks!

**Comment by justin1380foxconn** [comment]
maybe you can downgrade h5py==2.10,
and I have the same problem in h5py==3.1.0
*********************************************************************
Operating System: Ubuntu 18.04 
Platform：aarch64
Python version: 3.6

**Comment by PhilMiller** [comment]
I saw a similar error. What seems to be going on is that h5py installs the oldest possible version of numpy that it can work with, to use as a reference point for the ABI it should build against. A header file, `xlocale.h`, was non-standard and got removed in recent C standard library versions. Newer versions of numpy are aware of that move, and handle it fine.

The workaround I found was to set `H5PY_SETUP_REQUIRES=0` in the environment. Unfortunately, that still runs into another issue, #1771 depending on how you're installing.

**Comment by laoshaw** [comment]
Could not install h5py in virtual python env on jetson nano 4.6 jetpack, install with 'sudo pip3' works fine though, tried all the H5PY_SETUP_REQUIRES and --no-build-isolation, did not help

**Comment by sachinkmohan** [comment]
Got fixed after doing this. Saw this solution somewhere on a github issue, can't remember where, so unable to link. Apologies! Thanks to that gentelman! 

`sudo ln -s /usr/include/locale.h /usr/include/xlocale.h`

**Comment by tacaswell** [comment]
I am going to close this as there is nothing we can do upstream.
