### ISSUE TITLE
Cannot create dataset with trailing slash

### ISSUE THREAD

**Issue by StevenSong** [h5py/h5py#1762]
In the update from h5py version 3.0.0 to 3.1.0, PR #1734 changed the way that dataset names are parsed in `create_dataset`.

These are the specific lines that changed: https://github.com/h5py/h5py/pull/1734/files#diff-547b981eff8da23e6749727538727548a5809609dbcdf66587eb6937e8486d0cL143-R146

Previously, a dataset name like `/path/to/data/` would get or create the groups `path` and `to`. It would then create the dataset with name `data`:

The old section of code discarded splits of 0 length so `h5objects` would be `['path', 'to', 'data']` and name would be set to `'data'`:
```python
if '/' in name:
    h5objects = [obj for obj in name.split('/') if len(obj)]
    name = h5objects[-1]
    h5objects = h5objects[:-1]

    for new_group in h5objects:
        group = group.get(new_group) or group.create_group(new_group)
```

In version 3.1.0, the trailing slash is split via `rsplit('/', 1)`, so `parent_path = 'path/to/data'` and `name` becomes the empty string which is causes an exception downstream
```python
if b'/' in name.lstrip(b'/'):
    parent_path, name = name.rsplit(b'/', 1)
    group = self.require_group(parent_path)
```

Is this change intentional? My personal opinion is that this is actually cleaner as a right side slash denotes a group. if hd5 were like a filesystem, `$ touch file.txt/` would treat `file.txt` as a directory

**Comment by takluyver** [comment]
It wasn't intentional, but if it had always been that way, I'd probably say it was fine - I agree that a trailing slash implies a group, by analogy with files and folders.

As it is, I'm 50/50. We hopefully never documented that it did work, but if it has worked for years and it's causing problems now that it doesn't work, I'm open to making it work again.

**Comment by StevenSong** [comment]
I hadn't seen it mentioned anywhere in documentation either. It's not causing problems for me, its easy enough for me to fix my old code that used it. Thanks for the reply though, I'm happy to close this issue as answered!
