### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by kdpenner** [h5py/h5py#1774]
Operating System: Windows Server 2016 Standard

 Python version: 3.8.5

 Where Python was acquired: conda

 h5py version: 2.10.0

HDF5 version: 1.10.4

Here's a snippet of the traceback, since h5py is imported from pymc3:

```
 File "<path>\lib\site-packages\pymc3\backends\hdf5.py", line 16, in <module>
   import h5py
 File "<path>\lib\site-packages\h5py\__init__.py", line 34, in <module>
   from . import version
 File "<path>\lib\site-packages\h5py\version.py", line 17, in <module>
   from . import h5 as _h5
 File "h5py\h5.pyx", line 1, in init h5py.h5
ImportError: DLL load failed while importing defs: The specified procedure could not be found.
```

However importing h5py from an interpreter works fine:

```
>>> import h5py
>>>
```

**Comment by thunderflash** [comment]
I have the same problem, any idea? I search the h5.pyx in fold, not found.

**Comment by Whale-fall** [comment]
same problems

**Comment by aragilar** [comment]
@kdpenner I think this may be a conda build/packing bug, if the search paths for DLLs is not set correctly. I would ask on their mailing list (https://groups.google.com/access-error?continue=https://groups.google.com/a/anaconda.com/g/anaconda) about what information they need to debug this.

**Comment by Nyquist0** [comment]
Still got the same problem:

```
2022-02-17 10:02:24 [24,168ms] [Error] [omni.ui.python] ImportError: DLL load failed: The specified procedure could not be found.

At:
  h5py\h5.pyx(1): init h5py.h5
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(1050): exec_module
  <frozen importlib._bootstrap>(677): _load_unlocked
  <frozen importlib._bootstrap>(967): _find_and_load_unlocked
  <frozen importlib._bootstrap>(983): _find_and_load
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap>(1043): _handle_fromlist
  C:\Users\litao\AppData\Local\ov\data\Kit\kit\102.1\pip3-envs\default\h5py\version.py(15): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(728): exec_module
  <frozen importlib._bootstrap>(677): _load_unlocked
  <frozen importlib._bootstrap>(967): _find_and_load_unlocked
  <frozen importlib._bootstrap>(983): _find_and_load
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap>(1043): _handle_fromlist
  C:\Users\litao\AppData\Local\ov\data\Kit\kit\102.1\pip3-envs\default\h5py\__init__.py(33): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(728): exec_module
  <frozen importlib._bootstrap>(677): _load_unlocked
  <frozen importlib._bootstrap>(967): _find_and_load_unlocked
  <frozen importlib._bootstrap>(983): _find_and_load
```

But importing h5py from an interpreter works fine too, like this.
```
>>> import h5py
>>>
```


Conda environment
python == 3.7.12
h5py == 3.6.0
hdf5 == 1.12.1

Is there one way that I add these DLL files manually?

**Comment by mmagnuski** [comment]
I have the same problem with h5py 3.6.0 from conda, and would also be thankful if someone pointed me in the right direction (adding the missing DLLs or correcting the path so they can be found).

**Comment by tacaswell** [comment]
I am going to close this as these are all likely due to installation or packaging issues.

While manually moving dlls or adjusting the path my appear to fix the problem, that is only papering over the deeper problem that something is wrong with the Python installation.  I strongly suggest uninstalling everything and starting with a fresh virtualenv or conda environment.

I'm going to close this because there is nothing we can do upstream to fix these problems.

**Comment by vernimmen** [comment]
I confirm the issue still exists when installed through conda (Python 3.9.5). My h5py package was updated (to version 3.7.0) while installing wradlib (1.18.0) through conda. My solution was to uninstall h5py (pip uninstall h5py) and install it again using pip
