### ISSUE TITLE
Numpy 1.20 deprecation warnings

### ISSUE THREAD

**Issue by vasole** [h5py/h5py#1777]
Numpy 1.20 introduces several deprecation warnings and some are very annoying (at least to me).

I am ready to submit a PR but I would like to know what approach you prefer concerning the cases where several alternatives are possible:

- Replace numpy.float by numpy.float64 or by float because it was just an alias to it?
- Replace numpy.int by numpy.int64 or by int because it was just an alias to it?

**Comment by aragilar** [comment]
I think this will depend on context—I think create the PR, and if there's any bits that need discussion, they can get discussed then.

**Comment by vasole** [comment]
Addressed by #1780 

CI error messages do not seem to have anything to do with my PR:

``
ERROR:   py39-test-mindeps: could not install deps [pytest, pytest-cov, pytest-mpi>=0.2, cython==0.29.14, numpy==1.19.3]; v = InvocationError("'D:\\a\\1\\s\\.tox\\py39-test-mindeps\\Scripts\\python.EXE' -m pip install pytest pytest-cov 'pytest-mpi>=0.2' cython==0.29.14 numpy==1.19.3", 1) 
``

**Comment by vasole** [comment]
Solved by #1780
