### ISSUE TITLE
Documentation mistakenly refers to chunk_iter rather than iter_chunks

### ISSUE THREAD

**Issue by matthew-d-jones** [h5py/h5py#1784]
Mistake in h5py 3.1.0 documentation

"Chunked storage" section refers to `dset.chunk_iter()` but the actual method is `dset.iter_chunks()`
https://docs.h5py.org/en/stable/high/dataset.html#chunked-storage

**Comment by tacaswell** [comment]
Thanks for catching that!

**Comment by patiencedaur** [comment]
I fixed the typo: https://github.com/h5py/h5py/pull/1791
