### ISSUE TITLE
read_direct bug when dest and source have different shape

### ISSUE THREAD

**Issue by jasondet** [h5py/h5py#1792]
h5py    3.1.0
HDF5    1.12.0
Python  3.9.1 (default, Dec 29 2020, 09:45:39) 
[Clang 12.0.0 (clang-1200.0.32.28)]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.19.5
cython (built with) 0.29.21
numpy (built against) 1.19.3
HDF5 (built against) 1.12.0

read_object gives an error if a dest_sel is provided but source and dest have a different shape. Example script:
```
f = h5py.File('tmp.h5', 'w')
dset = f.create_dataset("dset", (10,), dtype='int64')
dset[:] = range(10)
arr = np.zeros((12,), dtype='int32')
dset.read_direct(arr, None, np.s_[2:])
print(arr)
```
Running this results in:
```
Traceback (most recent call last):
  File "/Users/jasondet/Downloads/h5py_bug.py", line 9, in <module>
    dset.read_direct(arr, None, np.s_[2:])
  File "/usr/local/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 970, in read_direct
    for mspace in dest_sel.broadcast(source_sel.mshape):
  File "/usr/local/lib/python3.9/site-packages/h5py/_hl/selections.py", line 291, in broadcast
    tshape = self.expand_shape(source_shape)
  File "/usr/local/lib/python3.9/site-packages/h5py/_hl/selections.py", line 264, in expand_shape
    raise TypeError("Can't broadcast %s -> %s" % (source_shape, self.array_shape))  # array shape
TypeError: Can't broadcast (10,) -> (8,)
```

It appears that the problem is in dataset.py line 967:
```
                dest_sel = sel.select(dest.shape, dest_sel, self)
```
In the 3rd argument, self (the source dataset) is provided for select() to make a selection on dest_sel, which seems wrong. Indeed, if I simply change "self" to "None", my example code runs without error producing the expected output:
```
[0 0 0 1 2 3 4 5 6 7 8 9]
```

**Comment by takluyver** [comment]
Yes, I think you're right. Do you want to make a PR? It would be good to add a test that would fail at the moment, as part of this test class:

https://github.com/h5py/h5py/blob/552a4322c2523c01e4344beaa594df2d0eb93ee2/h5py/tests/test_dataset.py#L215

**Comment by takluyver** [comment]
#1773 appears to be describing the same problem.

**Comment by jasondet** [comment]
agreed, and the fix proposed there is effectively identical.

sorry I'm not a dev just a user, won't have time to get setup to do a PR. can someone on the team take care of it? it's a matter of changing one word in one line...
