### ISSUE TITLE
absolute path  ending up in the egg-info SOURCES.txt

### ISSUE THREAD

**Issue by Mingli-Yu** [h5py/h5py#1802]
$ cat SOURCES.txt
ANN.rst
AUTHORS
LICENSE
MANIFEST.in
README.rst
api_gen.py
pylintrc
pytest.ini
setup.cfg
setup.py
setup_build.py
setup_configure.py
tox.ini
/work/h5py/_conv.c
/work/h5py/_errors.c
[snip]

**Comment by aragilar** [comment]
@Mingli-Yu Which OS/python version/h5py version did you run into this, I've tried using latest master on linux (python 3.9) and do not find this to be the case.

**Comment by takluyver** [comment]
I also don't see absolute paths in there, and it's not clear that it's a big problem if they do. I'm going to close this issue and PR #1803 as something we don't need to worry about. We can always reopen if someone offers more details.
