### ISSUE TITLE
h5py\_hl\dataset.py:767: DeprecationWarning

### ISSUE THREAD

**Issue by mauro835** [h5py/h5py#1808]
Windows 10
h5py    3.1.0
HDF5    1.12.0
Python  3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.20.0
cython (built with) 0.29.21
numpy (built against) 1.17.5

`
***\venv\lib\site-packages\h5py\_hl\dataset.py:767: DeprecationWarning: Passing None into shape arguments as an alias for () is deprecated.
  arr = numpy.ndarray(selection.mshape, dtype=new_dtype)
`

**Comment by vasole** [comment]
Already solved by #1780

**Comment by takluyver** [comment]
Thanks @vasole . I'm aiming to do a new release soon.
