### ISSUE TITLE
Use low level API to create h5py objects from ID

### ISSUE THREAD

**Issue by kerim371** [h5py/h5py#1821]
Hi,

I'm trying to write python wrapper for [HighFive C++ hdf5 wrapper](https://github.com/BlueBrain/HighFive) via pybind11.
On the lower level I would like to make it possible creating h5py objects from HighFive object's ID (and vice versa). 

I create HighFive::Group in python and then I try to create h5py group from HighFive::Group's ID (see inline comments):
```py
import HFGt   # it is HighFive fork
import h5py

hfgt_file = HFGt.File("myFile.h5", HFGt.OpenFlag.Overwrite)
hfgt_file_id = hfgt_file.getId(False)
hfgt_group = hfgt_file.createGroup("myGroup", HFGt.LinkCreateProps(), HFGt.GroupCreateProps(), HFGt.GroupAccessProps())
hfgt_group_id = hfgt_group.getId(False)  # 144115188075855872

h5py_file = h5py.File('myFile_py.h5','w')
h5py_file_id = h5py_file._id
h5py_group = h5py_file.create_group("myGroup")
h5py_group_id = h5py_group._id  # 144115188075855873

# here I try to instantiate h5py::Group from HighFive::Group's ID
h5py_group = h5py.Group(hfgt_group_id)  # Exception has occurred: ValueError. 144115188075855872 is not a GroupID
```

I use the same HDF5 C-lib that h5py uses. As you can see `hfgt_group_id` is 144115188075855872, wich is by one smaller than `h5py_group_id` and this proves that both libs uses the same HDF5 lib.

How do you think, why I get this error and I can't instantiate `h5py::Group` from `HighFive::Group's ID` ? 

My configuration:
 * Operating System: Windows 10
 * Python version: 3.8.5
 * Where Python was acquired: Windows miniconda
 * h5py version: 2.10.0
 * HDF5 version: 1.10.4
 * The full traceback/stack trace shown (if it appears)

**Comment by aragilar** [comment]
@kerim371 You're using the high-level API in your example, if you want to interact with the h5py HDF5 library wrappers, you need to use the [low-level API](https://api.h5py.org/).

**Comment by kerim371** [comment]
@aragilar thank you.
`h5py.h5g.GroupID(hfgt_group_id)` creates new h5py ID and this ID I can use as a parameter when creating new instance of group

**Comment by takluyver** [comment]
See also [this page on how the high-level and low-level APIs fit together](https://docs.h5py.org/en/stable/high/lowlevel.html).

You may need to watch out for reference counting issues. E.g. when an `h5py.h5g.GroupID` object is released, it will decrement HDF5's reference count for that ID, so it may be necessary to increment the reference count when you create the h5py object, if you want to keep using the same ID outside h5py as well.

**Comment by kerim371** [comment]
@takluyver thank you for the link
Yes, I keep in mind the refernce count staff. In addition to what you explained (about decreasing reference count when object is released), am I right that low level `FileID`, `GroupID` and `DatasetID` created from integer ID value (like I did in upper post) **doesn't internally increase the reference count?**

**Comment by takluyver** [comment]
Yes, that's right. The Cython code for initialising one of these low-level objects is here, and you can see nothing is incrementing a refcount (the specific FileID, GroupID etc. classes subclass this ObjectID class - you can verify if you like that they're not incrementing the ref count either):

https://github.com/h5py/h5py/blob/64f7b7da5e996d99ab29c64e7bb95e5a13a0c850/h5py/_objects.pyx#L184-L191

For comparison, here's the code called when an object is released, which calls `H5Idec_ref`:

https://github.com/h5py/h5py/blob/64f7b7da5e996d99ab29c64e7bb95e5a13a0c850/h5py/_objects.pyx#L194-L206

**Comment by kerim371** [comment]
@takluyver thank you very much!
