### ISSUE TITLE
Reading custom opaque types

### ISSUE THREAD

**Issue by kutoga** [h5py/h5py#1822]
To assist reproducing bugs, please include the following:
 * Operating System: Ubuntu 18.04
 * Python version: 3.6.9
 * Where Python was acquired: System python
 * h5py version: 3.1.0
 * HDF5 version: 1.12.0

I have a h5-file which contains an array of a custom opaque 2-byte datatype (`bfloat16`). The data is written by a non-python application and should now be read with h5py.

I try to read the data as 2-byte-blobs and then to convert them to a float32 numpy-array. Unfortunately, I could not find a way to just read the blobs (the conversion should then be trivial).

I always get this error:

```
h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

/mnt/c/git/test/.venv/lib/python3.6/site-packages/h5py/_hl/dataset.py in __getitem__(self, args)
    571         mspace = h5s.create_simple(mshape)
    572         fspace = selection.id
--> 573         self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
    574 
    575         # Patch up the output for NumPy

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5d.pyx in h5py.h5d.DatasetID.read()

h5py/_proxy.pyx in h5py._proxy.dset_rw()

h5py/_proxy.pyx in h5py._proxy.H5PY_H5Dread()

OSError: Can't read data (no appropriate function for conversion path)
```

Is there a possibility to register a custom function for reading opaque data? Alternatively it would also be okay to read the data as (u)int16 if this is possible.

Thanks

**Comment by aragilar** [comment]
Do you have some example code? Incidentally, you should not store bfloats in an opaque type, HDF5's floating point support allows you to specify enough details such that you can store it natively, and h5py will do the automatic conversion to the smallest floating point type which can losslessly hold the data that your system supports.

**Comment by kutoga** [comment]
Okay, I see. I'll check the documentation regarding custom floating point types.

A snippet of the C-code:
```c
hid_t h5_float_dtype = H5Tcreate(H5T_OPAQUE, float_size);
const herr_t status = H5Tset_tag(file->h5_float_dtype, "bfloat16");
```
Later the data is converted to a bfloat16 and written.

There is not yet too much python-code. Just some playground:
```python
f = h5py.File('my_file.h5', 'r')
f["data"]["x"] # This line throw the error from the first line
```

Thanks for the hint with the custom floating point types. I did not know that. I'll have a look how they work.

**Comment by takluyver** [comment]
It's odd that it fails, though, because opaque data is meant to be read as numpy 'void' data by default. I've added a test in #1823, which is passing for me locally.

I agree with @aragilar that it's better to use a custom float type (with `H5Tset_fields` & `H5Tset_ebias`) if possible.

**Comment by kutoga** [comment]
I've started to play around with the custom float type (which is actually quite easy):

```c
          float_size = 2;
          file->h5_float_dtype = H5Tcopy(H5T_NATIVE_FLOAT); 
          herr_t status;
          status = H5Tset_fields(file->h5_float_dtype, 15, 7, 8, 0, 7);
          assert(status >= 0);
          status = H5Tset_size(file->h5_float_dtype , float_size);
          assert(status >= 0);
          status = H5Tset_ebias(file->h5_float_dtype, 15);
          assert(status >= 0);
          status = H5Tlock(file->h5_float_dtype);
          assert(status >= 0);
```

Writing works perfectly, but when I try to read the data I get a weird error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-66-83a9f31d3eea> in <module>
----> 1 d_b2 = h_b2["set"]["features"]

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

~/.local/lib/python3.6/site-packages/h5py/_hl/dataset.py in __getitem__(self, args, new_dtype)
    724                 names = names[0]  # Read with simpler dtype of this field
    725             args = tuple(x for x in args if not isinstance(x, str))
--> 726             return self.fields(names, _prior_dtype=new_dtype)[args]
    727 
    728         if new_dtype is None:

~/.local/lib/python3.6/site-packages/h5py/_hl/dataset.py in fields(self, names, _prior_dtype)
    381         """
    382         if _prior_dtype is None:
--> 383             _prior_dtype = self.dtype
    384         return FieldsWrapper(self, _prior_dtype, names)
    385 

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

~/.local/lib/python3.6/site-packages/h5py/_hl/dataset.py in dtype(self)
    482     def dtype(self):
    483         """Numpy dtype representing the datatype"""
--> 484         return self.id.dtype
    485 
    486     @property

h5py/h5d.pyx in h5py.h5d.DatasetID.dtype.__get__()

h5py/h5d.pyx in h5py.h5d.DatasetID.dtype.__get__()

h5py/h5t.pyx in h5py.h5t.TypeID.dtype.__get__()

h5py/h5t.pyx in h5py.h5t.TypeID.dtype.__get__()

h5py/h5t.pyx in h5py.h5t.TypeCompoundID.py_dtype()

ValueError: NumPy dtype descriptor requires 9280 bytes, cannot override to smaller itemsize of 2818
```

**Comment by takluyver** [comment]
The fact that you're reading it with a name (`h_b2["set"]["x"]`) suggests this is part of a compound dtype. Could you try:

1. Reading the entire struct (like `ds[0]`) rather than just one field (`ds['x']`).
2. Storing just the custom float data outside of a compound dtype.

This might give us a hint about what's going wrong. We have a (passing) test of custom float dtypes here:

https://github.com/h5py/h5py/blob/64f7b7da5e996d99ab29c64e7bb95e5a13a0c850/h5py/tests/test_h5t.py#L59-L188

**Comment by kutoga** [comment]
Yes, it is a compound type.

`ds[0]` results in the same error. On the other side, moving the bfloat64-data to the top-level of the file "works". `h5dump` shows this file-structure:

```bash
HDF5 "my_file.h5" {
GROUP "/" {
   DATASET "x" {
      DATATYPE  16-bit little-endian floating-point
      DATASPACE  SIMPLE { ( 222, 1157 ) / ( H5S_UNLIMITED, 1157 ) }
      DATA {h5dump error: unable to print data
      }
   }
}
```

If I load the data with h5py, the values seem to be wrong:
```python
h_b4 = h5py.File("my_file.h5", 'r')
print(h_b4["features"][0, 0])
```

This outputs 6.884257312483485e+53 instead of the expected value 1.1640625. Actually, the produced value is bigger than the biggest possible bfloat16 value. So I guess I do something wrong when I load the data?

**Comment by kutoga** [comment]
In the meanwhile I've switched to a simple fallback: I store the bfloat16 values in a uint16-dataset. This is not really nice, because the datatype is no longer descriptive. Nevertheless, loading the data works if the dataset is "converted" with this function:

```python
def np_load_bfloat16(x):
    assert(x.dtype == np.uint16)
    return np.left_shift(x.astype(np.uint32), np.uint32(16)).view('<f4')
```

**Comment by takluyver** [comment]
There shouldn't be anything special you need to do when loading it - HDF5 is meant to convert automatically based on your description of the float. If there's a mistake on your part, it's probably in the code creating the dataset. But I also imagine this is not the most tested corner of HDF5, so it's possible there's a bug.

What dtype is the data you get when reading it in h5py? It should automatically expand it to float32 to avoid losing data.

Can you reproduce this by creating the type & the dataset in Python, based on the test code I linked above?

**Comment by kutoga** [comment]
thanks for your help:)

I've tried it with this reimplementation of float16:
https://github.com/h5py/h5py/blob/64f7b7da5e996d99ab29c64e7bb95e5a13a0c850/h5py/tests/test_h5t.py#L130

This works perfectly fine. Unfortunately, I had problems writing the data with `H5Dwrite` when the memory datatype is not identical with the dataset data type. At least my C-code seems to work for this reimplemented IEEE float16.

I'll do more investigation why bfloat16 still does not work for me (I guess something in the C-code is not done as it should be).

I've also started to play around with the test and I've seen if I encode bfloat16 values, they're decoded into float64:

```python
class TestTypeFloatID(TestCase):
    """Test TypeFloatID."""

    def test_custom_float_promotion(self):
        """Custom floats are correctly promoted to standard floats on read."""

        # This test uses the low-level API, so we need names as byte strings
        test_filename = 'tmp.h5'.encode() #self.mktemp().encode()
        dataset = b'DS1'

        dims = (1, 1)

        wdata = np.array([[1.1640625]], dtype=np.float32)

        # Create a new file using the default properties.
        fid = h5py.h5f.create(test_filename)
        # Create the dataspace.  No maximum size parameter needed.
        space = h5py.h5s.create_simple(dims)

        # bfloat16
        mytype = h5t.IEEE_F16LE.copy()
        mytype.set_fields(15, 7, 8, 0, 7)
        mytype.set_size(2)
        mytype.set_ebias(15)
        mytype.lock()

        # mytype = h5t.IEEE_F16LE.copy()
        # mytype.set_fields(15, 10, 5, 0, 10)
        # mytype.set_size(2)
        # mytype.set_ebias(15)
        # mytype.lock()

        dset = h5py.h5d.create(fid, dataset, mytype, space)
        dset.write(h5py.h5s.ALL, h5py.h5s.ALL, wdata)

        del dset

        f = h5py.File(test_filename, 'r')

        # ebias promotion to float32
        values = f[dataset][:]
        np.testing.assert_array_equal(values, wdata)
        self.assertEqual(values.dtype, np.dtype('<f4')) # <---- this fails
```

Is this by intention? A bfloat16 would fit perfectly into a float32. Maybe there is a reason for the choice of this datatype?
(at least for my use-case I highly prefer a direct conversion to float32, because otherwise it has to be done afterwards)

thanks

**Comment by kutoga** [comment]
I created a small minimal example. It works well with IEEE float16 and plain uint16, but it does not work with bfloat16.

First I'll post the C-code:
```C
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <assert.h>
#include <hdf5.h>

#define USE_BFLOAT16

enum t_used_datatype {
    IEEE_FLOAT16,
    BFLOAT16,
    UINT16
};

int main() {

    // define the used datatype
    enum t_used_datatype used_datatype = UINT16;

    hid_t fid = H5Fcreate("my_file.h5", H5F_ACC_TRUNC, H5P_DEFAULT, H5P_DEFAULT);

    // specify the h5-type
    hid_t dtype;
    herr_t status;
    switch (used_datatype) {
        case IEEE_FLOAT16:
            dtype = H5Tcopy(H5T_NATIVE_FLOAT);
            status = H5Tset_fields(dtype, 15, 10, 5, 0, 10);
            status = H5Tset_size(dtype , 2);
            assert(status >= 0);
            status = H5Tset_ebias(dtype, 15);
            assert(status >= 0);
            status = H5Tlock(dtype);
            assert(status >= 0);
            break;
        case BFLOAT16:
            dtype = H5Tcopy(H5T_NATIVE_FLOAT);
            status = H5Tset_fields(dtype, 15, 7, 8, 0, 7);
            status = H5Tset_size(dtype , 2);
            assert(status >= 0);
            status = H5Tset_ebias(dtype, 15);
            assert(status >= 0);
            status = H5Tlock(dtype);
            assert(status >= 0);
            break;
        case UINT16:
            dtype = H5Tcopy(H5T_NATIVE_UINT16);
            break;
        default:
            printf("invalied type!\n");
            exit(1);
    }

    // some bfloat16 values: https://en.wikipedia.org/wiki/Bfloat16_floating-point_format#Special_values
    uint16_t values[] = {
        0x4049, // approx. PI
        0x3eab, // approx. 1 / 3
        0x3f80, // 1
    };
    #define VALUES_COUNT        (sizeof(values) / sizeof(values[0]))

    // create the dataset
    hid_t proplist = H5Pcreate(H5P_DATASET_CREATE);
    hsize_t chunks[2] = {1, 1};
    hsize_t dims[2] = {0, 1};
    hsize_t max_dims[2] = {VALUES_COUNT, 1};
    H5Pset_chunk(proplist, 1, chunks);
    hid_t filespace = H5Screate_simple(1, dims, max_dims);
    hid_t dataset = H5Dcreate(fid, "x", dtype, filespace, H5P_DEFAULT, proplist, H5P_DEFAULT);

    // write the data
    H5Dextend(dataset, max_dims);
    filespace = H5Dget_space(dataset);
    hid_t memspace = H5Screate_simple(1, max_dims, NULL);
    status = H5Dwrite(dataset, dtype, memspace, filespace, H5P_DEFAULT, values);
    assert(status >= 0);

    // close everything
    H5Sclose(memspace);
    H5Sclose(filespace);
    H5Dclose(dataset);
    H5Fclose(fid);
}

```

Makefile:
```makefile
minimal-example: minimal-example.c
	gcc -Wall -Werror -Wextra $^ -o $@ $(shell pkg-config --cflags --libs hdf5)
```

The code basically write three values to the resulting file:
0x4049 (bfloat16 for pi), 0x3eab (bfloat16 for 1/3) and 0x3f80 (bfloat16 for 1).

I did three tests:

# Using UINT16
Change the first line in main to:
```c
enum t_used_datatype used_datatype = UINT16;
```

Execute:
```
make && ./minimal-example
```

Now we can have a look into the file with h5py:
```python
f = h5py.File('my_file.h5', 'r')
hex(f["x"][:][0])     # prints 0x4049
```

This works as expected. The defined values are just printed in their hex-representation.

# Using IEEE float16
The specification is copied from the unit test.

Change the first line in main to:
```c
enum t_used_datatype used_datatype = IEEE_FLOAT16;
```

Execute:
```
make && ./minimal-example
```

Now we can have a look into the file with h5py:
```python
f = h5py.File('my_file.h5', 'r')
hex(f["x"][:].view(np.uint16)[0])     # prints 0x4049
```
As expected, the binary representation of the number is unchanged (because it's a IEEE float like np.float16). h5py correctly chose a np.float16 to store the value. 

# Using bfloat16
Change the first line in main to:
```c
enum t_used_datatype used_datatype = BFLOAT16;
```

Execute:
```
make && ./minimal-example
```

Now we can have a look into the file with h5py:
```python
f = h5py.File('my_file.h5', 'r')
f["x"].dtype # This shows <f8. It's unexpected, but it could hold a bfloat16, so it is okay
f["x"][0] # This shows "1.6307057321335943e+34" which I cannot explain. I would expect to show it the first value in our dataset: pi
# In general f["x"][:] shows these values:
# array([1.63070573e+34, 1.73414602e+33, 5.19229686e+33])
```

# Other formats
Unfortunately, it is hard for me to reproduce other formats int C. It seems h5py can successfully write & read different custom floats (like in the unit-test), but maybe I use the hdf5 C-library wrong.

**Comment by takluyver** [comment]
The code that picks a NumPy dtype to convert a float dtype to is here - it's certainly possible that there's some mistake; it's not tested very often:

https://github.com/h5py/h5py/blob/64f7b7da5e996d99ab29c64e7bb95e5a13a0c850/h5py/h5t.pyx#L1029-L1048

**Comment by aragilar** [comment]
@kutoga The exponential bias (set by `H5Tset_ebias`) you have for the bfloat16 looks wrong, it should be [127](https://en.wikipedia.org/wiki/Half-precision_floating-point_format#Exponent_encoding) not 15 (which is from half/IEEE-16 bit float), which would explain the large values.

**Comment by kutoga** [comment]
Ahhh, thanks! You are absolutely right. I've misinterpreted something an never questioned it again.

I'll test my things again.

Thx:)

**Comment by aragilar** [comment]
That change seemed to work:
```
$ h5dump my_file.h5
HDF5 "my_file.h5" {
GROUP "/" {
   DATASET "x" {
      DATATYPE  16-bit little-endian floating-point
      DATASPACE  SIMPLE { ( 3 ) / ( 3 ) }
      DATA {
      (0): 3.14062, 0.333984, 1
      }
   }
}
}
```

```
>>> import h5py
>>> f = h5py.File('my_file.h5', 'r')
>>> print(f["x"].dtype)
float32
>>> print(f["x"][0])
3.140625
```

**Comment by kutoga** [comment]
Yes, actually also the "real" application works fine with this fix 👍. Thank you very much for pointing out the "bug".

Also thank @takluyver for pointing out where the numpy type is determined.

So, there is only one problem left: If I use this dataset inside a compound type, I still get the following error. Which, unfortunately, is a requirement for me. I'll try to adjust the minimal example for this scenario.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-286-a51a6055448a> in <module>
----> 1 h_final_b2['set']["x"]

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

~/.local/lib/python3.6/site-packages/h5py/_hl/dataset.py in __getitem__(self, args, new_dtype)
    724                 names = names[0]  # Read with simpler dtype of this field
    725             args = tuple(x for x in args if not isinstance(x, str))
--> 726             return self.fields(names, _prior_dtype=new_dtype)[args]
    727 
    728         if new_dtype is None:

~/.local/lib/python3.6/site-packages/h5py/_hl/dataset.py in fields(self, names, _prior_dtype)
    381         """
    382         if _prior_dtype is None:
--> 383             _prior_dtype = self.dtype
    384         return FieldsWrapper(self, _prior_dtype, names)
    385 

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

~/.local/lib/python3.6/site-packages/h5py/_hl/dataset.py in dtype(self)
    482     def dtype(self):
    483         """Numpy dtype representing the datatype"""
--> 484         return self.id.dtype
    485 
    486     @property

h5py/h5d.pyx in h5py.h5d.DatasetID.dtype.__get__()

h5py/h5d.pyx in h5py.h5d.DatasetID.dtype.__get__()

h5py/h5t.pyx in h5py.h5t.TypeID.dtype.__get__()

h5py/h5t.pyx in h5py.h5t.TypeID.dtype.__get__()

h5py/h5t.pyx in h5py.h5t.TypeCompoundID.py_dtype()

ValueError: NumPy dtype descriptor requires 4652 bytes, cannot override to smaller itemsize of 2818
```

**Comment by kutoga** [comment]
Okay, I've modified the minimal example:

Code:
```c
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <assert.h>
#include <hdf5.h>

#define USE_BFLOAT16

enum t_used_datatype {
    IEEE_FLOAT16,
    BFLOAT16,
    UINT16
};

int main() {

    // define the used datatype
    enum t_used_datatype used_datatype = BFLOAT16;

    hid_t fid = H5Fcreate("my_file.h5", H5F_ACC_TRUNC, H5P_DEFAULT, H5P_DEFAULT);

    // specify the h5-type
    hid_t dtype;
    herr_t status;
    switch (used_datatype) {
        case IEEE_FLOAT16:
            dtype = H5Tcopy(H5T_NATIVE_FLOAT);
            status = H5Tset_fields(dtype, 15, 10, 5, 0, 10);
            status = H5Tset_size(dtype , 2);
            assert(status >= 0);
            status = H5Tset_ebias(dtype, 15);
            assert(status >= 0);
            status = H5Tlock(dtype);
            assert(status >= 0);
            break;
        case BFLOAT16:
            dtype = H5Tcopy(H5T_NATIVE_FLOAT);
            status = H5Tset_fields(dtype, 15, 7, 8, 0, 7);
            status = H5Tset_size(dtype , 2);
            assert(status >= 0);
            status = H5Tset_ebias(dtype, 127);
            assert(status >= 0);
            status = H5Tlock(dtype);
            assert(status >= 0);
            break;
        case UINT16:
            dtype = H5Tcopy(H5T_NATIVE_UINT16);
            break;
        default:
            printf("invalied type!\n");
            exit(1);
    }

    // dummy compoud type: it only contains one value of "dtype"
    hid_t c_dtype = H5Tcreate(H5T_COMPOUND, H5Tget_size(dtype));
    hsize_t num_cols = 1;
    H5Tinsert(c_dtype, "values", 0, H5Tarray_create(dtype, 1, &num_cols));

    // some bfloat16 values: https://en.wikipedia.org/wiki/Bfloat16_floating-point_format#Special_values
    uint16_t values[] = {
        0x4049, // approx. PI
        0x3eab, // approx. 1 / 3
        0x3f80, // 1
    };
    #define VALUES_COUNT        (sizeof(values) / sizeof(values[0]))

    // create the dataset
    hid_t proplist = H5Pcreate(H5P_DATASET_CREATE);
    hsize_t chunks[2] = {1, 1};
    hsize_t dims[2] = {0, 1};
    hsize_t max_dims[2] = {VALUES_COUNT, 1};
    H5Pset_chunk(proplist, 1, chunks);
    hid_t filespace = H5Screate_simple(1, dims, max_dims);
    hid_t dataset = H5Dcreate(fid, "x", c_dtype, filespace, H5P_DEFAULT, proplist, H5P_DEFAULT);

    // write the data
    H5Dextend(dataset, max_dims);
    filespace = H5Dget_space(dataset);
    hid_t memspace = H5Screate_simple(1, max_dims, NULL);
    status = H5Dwrite(dataset, c_dtype, memspace, filespace, H5P_DEFAULT, values);
    assert(status >= 0);

    // close everything
    H5Tclose(c_dtype);
    H5Sclose(memspace);
    H5Sclose(filespace);
    H5Dclose(dataset);
    H5Fclose(fid);
}
```

Makefile:
```makefile
minimal-example: minimal-example.c
        gcc -Wall -Werror -Wextra $^ -o $@ $(shell pkg-config --cflags --libs hdf5)
```

Python code to access values:
```python
f = h5py.File('/mnt/c/git/h5py_report/my_file.h5', 'r')
f["x"]["values"]
```

The python code works perfectly fine for IEEE float16 and uint16. For bfloat16 it just shows this error:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-302-0bdc10ced6f8> in <module>
----> 1 f["x"]["values"]

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

~/.local/lib/python3.6/site-packages/h5py/_hl/dataset.py in __getitem__(self, args, new_dtype)
    724                 names = names[0]  # Read with simpler dtype of this field
    725             args = tuple(x for x in args if not isinstance(x, str))
--> 726             return self.fields(names, _prior_dtype=new_dtype)[args]
    727 
    728         if new_dtype is None:

~/.local/lib/python3.6/site-packages/h5py/_hl/dataset.py in fields(self, names, _prior_dtype)
    381         """
    382         if _prior_dtype is None:
--> 383             _prior_dtype = self.dtype
    384         return FieldsWrapper(self, _prior_dtype, names)
    385 

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

~/.local/lib/python3.6/site-packages/h5py/_hl/dataset.py in dtype(self)
    482     def dtype(self):
    483         """Numpy dtype representing the datatype"""
--> 484         return self.id.dtype
    485 
    486     @property

h5py/h5d.pyx in h5py.h5d.DatasetID.dtype.__get__()

h5py/h5d.pyx in h5py.h5d.DatasetID.dtype.__get__()

h5py/h5t.pyx in h5py.h5t.TypeID.dtype.__get__()

h5py/h5t.pyx in h5py.h5t.TypeID.dtype.__get__()

h5py/h5t.pyx in h5py.h5t.TypeCompoundID.py_dtype()

ValueError: NumPy dtype descriptor requires 4 bytes, cannot override to smaller itemsize of 2
```

Thanks for your help:)!

**Comment by aragilar** [comment]
The problematic line is https://github.com/h5py/h5py/blob/d25f65ef4c9660ba29df88f443e8371cacf8e6d0/h5py/h5t.pyx#L1205, which is assuming that the numpy dtype size and the HDF5 type size match (which they don't in this case). Instead, we need to update the size to follow the same strategy (but inverse) of https://github.com/h5py/h5py/blob/d25f65ef4c9660ba29df88f443e8371cacf8e6d0/h5py/h5t.pyx#L1558-L1605 (hopefully linking to a specific commit means the links won't break in the future). We'd probably want a bunch of test cases doing the actual conversion to be sure that something hasn't broken though (as that bit of code is quite old, and probably undertested).

**Comment by takluyver** [comment]
Nice work - I had just started trying to compile the minimal example, and you beat me to it. :-)

**Comment by kutoga** [comment]
Thank for this very quick response. In general: All responses were always quick. Thanks a lot for this :-)!

If I could, I would provide a PR which fixes this, but I don't know the code base (so my solution would be hacky). Until this is fixed, I'll go for the not-so-nice `uint16`-solution.

Thanks:-)!

**Comment by takluyver** [comment]
I suspect this is going to be a bit fiddly to fix, because we also specify offsets. If one member of a compound datatype gets larger when converting to numpy, we may need to shift the offsets of the fields after it to make room. But we don't want to just ignore the offsets, because it's probably more efficient to read & write if it can preserve the data structure. I guess we'd check 'are these offsets & sizes valid', then recalculate them all if not, to keep things simple.

If you'd like to have a go, go for it (unless @aragilar says he's already working on it :-). I think this bit of code is fairly self contained, and you're clearly comfortable with C - this file is in Cython, which is a bit like C written in Python syntax.

**Comment by kutoga** [comment]
> 
> 
> I suspect this is going to be a bit fiddly to fix, because we also specify offsets. If one member of a compound datatype gets larger when converting to numpy, we may need to shift the offsets of the fields after it to make room. But we don't want to just ignore the offsets, because it's probably more efficient to read & write if it can preserve the data structure. I guess we'd check 'are these offsets & sizes valid', then recalculate them all if not, to keep things simple.

I see the problem. So it is not trivial.

> 
> If you'd like to have a go, go for it (unless @aragilar says he's already working on it :-). I think this bit of code is fairly self contained, and you're clearly comfortable with C - this file is in Cython, which is a bit like C written in Python syntax.

If I had more time for it, it would be a very interesting task ;-)! I've never used Cython, but it is somewhere on my todo-list. Unfortunately, I do not have to much time to do it now.

In general thanks for the help! Unfortunately, I could not find a donate-button which I could use to send you a few $ for a beer. Let me know if it is possible to donate a few $:)!

(btw: the fix is not very critical for me, so if it is (very very) low on your todo-list it's completely okay for me. even if you do not plan to fix it at all)

**Comment by takluyver** [comment]
I'm glad you're happy! There's a degree of luck involved - plenty of issues don't get such prompt attention.

I don't think we've got any project donation mechanism - there's not really any legal entity to receive them. And I'm personally fine for beer money. @aragilar is a PhD student, so perhaps he'll accept beer money :wink: . Otherwise, if you really want to send someone money, lots of the projects we depend on (Python, HDF5, NumPy, Cython) can handle donations. :-)

It might be best to open a new issue for the custom-float-in-compound issue we've now identified, as the history of this issue would be a lot of distractions for someone looking to contribute. Could you put your minimal example from a few comments ago in a new issue? Even better, is it possible to translate the C code to create the dataset into Python, so it's easier for someone to reproduce the issue?

**Comment by kutoga** [comment]
I've quickly tried to translate the code, but I failed. I'll try it again later (I am in a hurry right now).

The new issue is here:
https://github.com/h5py/h5py/issues/1825
