### ISSUE TITLE
Core driver is very slow when writing on Windows

### ISSUE THREAD

**Issue by stafak** [h5py/h5py#1827]
Hello, I'm trying to write to a dataset using the core driver, but while it works fine in my Ubuntu VM it's extremely slow on Windows (I tested on 2 different computers).

### Minimal working example

```python
import h5py
import numpy
import time

shape = (3072, 3072)
numItems = 10
items = numpy.random.rand(numItems, *shape)

file = h5py.File('test.hdf5', 'w', driver='core')
dataset = file.create_dataset('data', (numItems, *shape))

startTime = time.time()
for i in range(numItems):
    itStartTime = time.time()
    dataset[i] = items[i]
    itEndTime = time.time()
    print(f'Wrote item {i}, time: {itEndTime - itStartTime:.2f} s, total: {itEndTime - startTime:.2f} s')

file.close()
```

Which outputs the following when I test it on my main Windows 10 machine:
```
Wrote item 0, time: 0.46 s, total: 0.46 s
Wrote item 1, time: 1.35 s, total: 1.81 s
Wrote item 2, time: 2.34 s, total: 4.15 s
Wrote item 3, time: 3.07 s, total: 7.22 s
Wrote item 4, time: 4.01 s, total: 11.23 s
Wrote item 5, time: 4.90 s, total: 16.13 s
Wrote item 6, time: 5.96 s, total: 22.09 s
Wrote item 7, time: 6.72 s, total: 28.81 s
Wrote item 8, time: 7.38 s, total: 36.18 s
Wrote item 9, time: 8.98 s, total: 45.16 s
```

The default driver doesn't suffer from this issue – removing `driver='core'` results in this output:
```
Wrote item 0, time: 0.04 s, total: 0.04 s
Wrote item 1, time: 0.03 s, total: 0.07 s
Wrote item 2, time: 0.03 s, total: 0.10 s
Wrote item 3, time: 0.03 s, total: 0.13 s
Wrote item 4, time: 0.03 s, total: 0.16 s
Wrote item 5, time: 0.03 s, total: 0.19 s
Wrote item 6, time: 0.03 s, total: 0.22 s
Wrote item 7, time: 0.03 s, total: 0.25 s
Wrote item 8, time: 0.03 s, total: 0.28 s
Wrote item 9, time: 0.03 s, total: 0.31 s
```

Is this a bug in h5py? Or perhaps in the underlying HDF5 library?

### Configuration

This is the configuration on my main Windows 10 computer:
```
h5py    3.1.0
HDF5    1.12.0
Python  3.9.0 | packaged by conda-forge | (default, Oct 14 2020, 22:54:35) [MSC v.1916 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.20.1
cython (built with) 0.29.21
numpy (built against) 1.19.3
HDF5 (built against) 1.12.0
```

And on Ubuntu, for comparison:
```
h5py    3.1.0
HDF5    1.12.0
Python  3.9.0+ (default, Oct 20 2020, 08:43:38) 
[GCC 9.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.20.1
cython (built with) 0.29.21
numpy (built against) 1.19.3
HDF5 (built against) 1.12.0
```

**Comment by takluyver** [comment]
h5py doesn't do anything different depending on the file driver after you've opened the file, so if it is a bug, I think it would have to be in HDF5. You could verify that by doing the same operations in C code (you can borrow the skeleton from one of the [example programs](https://github.com/HDFGroup/hdf5/tree/develop/examples) to write it quickly).

It looks like it's getting slower on each write. I'd guess it's allocating a larger chunk of memory each time and copying all the previous data into it. Using [chunked storage](https://docs.h5py.org/en/stable/high/dataset.html#chunked-storage) might avoid this.

**Comment by stafak** [comment]
Thanks for the direction. I tried porting the code to C, and the pattern of getting slower with each write showed up there as well (though it was not as bad), so it seems like this is a HDF5 thing.

Chunked storage did improve the overall performance, but also introduced pauses when new chunks are created. In the end, the fileobj driver turned out to be the best solution for me.

Anyway, since the cause doesn't seem to be located in h5py I guess I'll close this.

**Comment by takluyver** [comment]
OK. If you see the same pattern in C, you could contact help@hdfgroup.org or post about it on the [HDF forum](https://forum.hdfgroup.org/). It might be something HDF group is interested to improve. If it's possible to do better by wrapping a Python file-like object, it must be possible to do better in HDF5 itself.

I'd still expect some pauses to allocate spaces for new chunks, but that should only depend on how much new data you're adding, rather than increasing as the dataset grows.

**Comment by stafak** [comment]
Yeah, I forgot to mention it – the pauses got longer and longer with each new chunk. But yes, I'll bring this to the attention of the HDF group.

**Comment by takluyver** [comment]
Hmm, maybe the core driver allocates a single block of memory for the entire HDF5 file, so it has to reallocate each time it grows. I am just guessing, though - talking to HDF group is a good idea.
