### ISSUE TITLE
How do I move a group?

### ISSUE THREAD

**Issue by aleksejs-fomins** [h5py/h5py#1846]
Hi. I would like to be able to move an existing group inside a file, to become a subgroup of another group. So I need a function

`move_group(h5file, '/internal/path/existing/group', '/internal/new/path')`

Does this already exist? Or how do I implement this?

**Comment by takluyver** [comment]
That sounds like the [Group.move()](https://docs.h5py.org/en/stable/high/group.html#h5py.Group.move) method.

File objects are also groups, so you should be able to call `h5file.move('/internal/path/existing/group', '/internal/new/path')`.

**Comment by aleksejs-fomins** [comment]
Thanks, that is it :)
