### ISSUE TITLE
Indexing arrays must have integer dtypes - Why? This was not the case before

### ISSUE THREAD

**Issue by mjpietrzak** [h5py/h5py#1847]
h5py version: 3.1.0 (bug not present in 2.10.0)

During the transition from 3.10 to 2.10.0 my code stopped working due to an error that can be easily reproduced using the following code:

```
import h5py
import numpy as np

mask = np.array((0,1,0), dtype=bool)
d = np.arange(6).reshape((3,2))
print(d)
print(d[mask,:])  # works and prints [2 3] (middle row)
f = h5py.File("temp.h5py", "w")
f.create_dataset("temp", data=d)
print(f["temp"][:,:][mask,:])  # workaround, because the code below:
print(f["temp"][mask,:])  # does not work: TypeError: Indexing arrays must have integer dtypes
```

**Comment by tacaswell** [comment]
I agree not taking bool arrays is a bug.

This is still a problem on the default branch.

**Comment by tacaswell** [comment]
I suspect we were too-broad in the logic that forbid float types as indexes.

**Comment by takluyver** [comment]
See also #1750.

**Comment by mjpietrzak** [comment]
In my case, it was a package upgrade using pip. Version 3.1.0 is there since November, so it is rather a coincidence.

**Comment by nzjrs** [comment]
In my case it was coincidence I found this - doing release engineering for
my own stack.

**Comment by WetzelVictor** [comment]
Hi there,
I'm having the same exact problem. I reopened old scripts that were working fine and this error came up. I am on a fresh install.
Are there any workaround beside converting the data to a numpy array?

**Comment by takluyver** [comment]
Yup, you can convert the array of bools to an array of integer indices using [nonzero()](https://numpy.org/doc/stable/reference/generated/numpy.nonzero.html):

```python
result = dset[include.nonzero()[0]]
```

**Comment by WetzelVictor** [comment]
Thank you for the workaround. It works like a charm and saved me a bit of covid headaches!

**Comment by dguest** [comment]
If this is still a problem, maybe @takluyver's solution above 
> ```python
> result = dset[include.nonzero()[0]]
> ```
should just be hacked into the `__getitem__` method for bool arrays. I don't know how efficient it is but if this is a bug I guess it would fix it.

**Comment by tacaswell** [comment]
That seems reasonable first step.

There may be a more efficient way to build the selectors, but slow working code is better than broken code!
