### ISSUE TITLE
"Cannot initialize filter fcidecomp: File not found"

### ISSUE THREAD

**Issue by texadactyl** [h5py/h5py#1849]
To assist reproducing bugs, please include the following:
 * Operating System: Xubuntu 20.10 up-to-date
 * Python version 3.8.6
 * h5py version 3.2.1
 * Package mgmt: pip/pypi

`h5py.version.info` :
```
h5py    3.2.1
HDF5    1.12.0
Python  3.8.6 (default, Jan 27 2021, 15:42:20) 
[GCC 10.2.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.20.1
cython (built with) 0.29.22
numpy (built against) 1.17.5
HDF5 (built against) 1.12.0
```

When I uninstall and reinstall h5py==2.10.0, the subject message goes away.

`h5py.version.info` :
```
h5py    2.10.0
HDF5    1.10.4
Python  3.8.6 (default, Jan 27 2021, 15:42:20) 
[GCC 10.2.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.20.1
```

**Comment by texadactyl** [comment]
Source code:

**Comment by takluyver** [comment]
Being discussed at https://github.com/silx-kit/hdf5plugin/issues/112 . If you raise the same issue on different projects, it's good to link them up so people can see what is being said in different places.

**Comment by takluyver** [comment]
Closing this one as it looks like it is up to hdf5plugin. See the thread there.

**Comment by texadactyl** [comment]
@takluyver 
I closed the hdf5plugin issue once I realized that it was not their issue.  Afterwards, I opened the issue here.

**Comment by takluyver** [comment]
Yup, but the hdf5plugin issue has since been reopened. :wink:

**Comment by texadactyl** [comment]
Who knows?  It could be yet another bloody problem with pip  and Python3 package management.  Its happened before.

If you need anything else from me like trying out a fledging PR, please let me know.
