### ISSUE TITLE
AttributeError: 'h5py.h5p.PropFAID' object has no attribute 'set_fapl_mpio'

### ISSUE THREAD

**Issue by tanmayagrawal7** [h5py/h5py#1850]
To assist reproducing bugs, please include the following:
 * Operating System: Ubuntu 20.04
 * Python version: 2.7, 3.6 and 3.8 (Have been using alias python='python3.6' and alias python3='python3.6' in bashrc file, as well as python 3.6 in alternative configuration. python --version, python -V provides 3.6.13 as output)
 * Where Python was acquired: Linux (sudo apt install...) - regular as well as development header files (libpython-dev)
 * h5py version 2.10.0
 * HDF5 version 1.10.4
 * The full traceback/stack trace shown (if it appears): 

```
Traceback (most recent call last):
  File "../PythonScripts/SOMAR.py", line 55, in wrapper
    return func(*args, **kargs)
  File "../PythonScripts/IO.py", line 38, in OpenFileForWrite
    FileHandle.append(WPF(filename))
  File "../PythonScripts/ChomboIO.py", line 21, in __init__
    self.FileHandle = h5.File(filename, 'a', driver='mpio', comm=MPI.COMM_WORLD)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 405, in __init__
    fapl = make_fapl(driver, libver, rdcc_nslots, rdcc_nbytes, rdcc_w0, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 135, in make_fapl
    set_fapl(plist, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 48, in _set_fapl_mpio
    plist.set_fapl_mpio(**kwargs)
AttributeError: 'h5py.h5p.PropFAID' object has no attribute 'set_fapl_mpio'
Exception ignored in: <bound method WriteCheckPoint.__del__ of <ChomboIO.WriteCheckPoint object at 0x7fb70790a908>>
Traceback (most recent call last):
  File "../PythonScripts/ChomboIO.py", line 29, in __del__
    if self.IsOpen:
AttributeError: 'WriteCheckPoint' object has no attribute 'IsOpen'
```

I have installed MPICH (no OpenMPI separately) through official installation and the path to mpicc is also present in my bashrc file.
I built and tested parallel MPI4PY, HDF5 and H5PY according to this guide:
https://drtiresome.com/2016/08/23/build-and-install-mpi-parallel-hdf5-and-h5py-from-source-on-linux/

I am a Linux beginner, therefore please tolerate my stupidity, happy to provide more information through running commands on terminal.

**Comment by takluyver** [comment]
It sounds like you've got a non-MPI build of h5py (same error messages as #1437).

Have a look at [the h5py docs on MPI](https://docs.h5py.org/en/stable/mpi.html) and [building from source](https://docs.h5py.org/en/stable/build.html#source-installation). The MPI integration is kind of an 'advanced mode' - it should all work, but it's not the easiest bit of h5py to use.

**Comment by tanmayagrawal7** [comment]
> 
> 
> It sounds like you've got a non-MPI build of h5py (same error messages as #1437).
> 
> Have a look at [the h5py docs on MPI](https://docs.h5py.org/en/stable/mpi.html) and [building from source](https://docs.h5py.org/en/stable/build.html#source-installation). The MPI integration is kind of an 'advanced mode' - it should all work, but it's not the easiest bit of h5py to use.

Thank you very much. Does it mean I have to reinstall h5py? If so, do I need to remove the existing version or simply overwrite the current one?
PS: The code I was trying to compile and test was done in serial mode, does that mean the mpi check would still happen resulting in this error?

**Comment by takluyver** [comment]
Your code that's opening the file is using the `driver='mpio', comm=MPI.COMM_WORLD` options, which tells h5py to use parallel mode. If you want to use it in serial mode (only one process writing the file), you can remove those options and carry on with a non-MPI installation.

If you do need the MPI support, then you will have to reinstall h5py (from source, with the necessary settings to build the MPI integration). If you're using `pip` to install it, you can either remove the previous installation manually, or add the `--force-reinstall` version to tell it to replace h5py even if you're not asking for a newer version.

**Comment by tanmayagrawal7** [comment]
> 
> 
> It sounds like you've got a non-MPI build of h5py (same error messages as #1437).
> 
> Have a look at [the h5py docs on MPI](https://docs.h5py.org/en/stable/mpi.html) and [building from source](https://docs.h5py.org/en/stable/build.html#source-installation). The MPI integration is kind of an 'advanced mode' - it should all work, but it's not the easiest bit of h5py to use.
 
Thanks Thomas! This worked out after rebuilding parallel HDF5 and subsequently parallel h5py. Also, I used this link (for anyone who faces similar issue):
https://distarray.readthedocs.io/en/v0.6.0/hdf5-notes.html
