### ISSUE TITLE
osx builds failing on h5py-feedstock on conda-forge

### ISSUE THREAD

**Issue by satra** [h5py/h5py#1853]
opening this issues to track: https://github.com/conda-forge/h5py-feedstock/pull/87

they errors are all on arm64 osx builds.

>  Loading library to get build settings and version: /Users/runner/miniforge3/conda-bld/h5py_1614964740728/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/libhdf5.dylib
  error: Unable to load dependency HDF5, make sure HDF5 is installed properly
  error: dlopen(/Users/runner/miniforge3/conda-bld/h5py_1614964740728/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/libhdf5.dylib, 6): no suitable image found.  Did find:
  	/Users/runner/miniforge3/conda-bld/h5py_1614964740728/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/libhdf5.dylib: mach-o, but wrong architecture
  	/Users/runner/miniforge3/conda-bld/h5py_1614964740728/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/libhdf5.103.dylib: mach-o, but wrong architecture
  Building wheel for h5py (PEP 517): finished with status 'error'
  ERROR: Failed building wheel for h5py

**Comment by satra** [comment]
see related issue: #1810

**Comment by takluyver** [comment]
I think this is to do with how conda-forge is cross-compiling it. Copying my comment from the conda-forge thread:

> I think the failures on the OSX ARM builds are because the build process now loads the HDF5 library to see if it's built with the ROS3 driver, and the library it finds has the wrong architecture. Previously, it only did this to get the HDF5 version, so setting the HDF5_VERSION env variable would skip that step.

**Comment by satra** [comment]
@takluyver - ah that makes sense, so technically it should install the osx_arm64 hdf5 library and setup.py has to find it. i don't know if conda-forge already uses https://crossenv.readthedocs.io/en/latest/ - but that may help. but it does mean that at this point it's a conda-forge issue rather than anything we can do with the recipe to address this?

**Comment by takluyver** [comment]
I don't know much about cross compilation, but my working assumption at the moment is that this is up to how the conda-forge build is configured.

**Comment by satra** [comment]
this should be now resolved. new packages available on conda (https://anaconda.org/conda-forge/h5py)
