### ISSUE TITLE
error reading szip-compressed dataset with conda-installed h5py

### ISSUE THREAD

**Issue by djuncu** [h5py/h5py#1862]
### problem
Sorry this one might be hard to reproduce but I've seen people have similar issues posting on stackoverflow e.g. (https://stackoverflow.com/questions/26301346/ioerror-cant-read-data-cant-open-directory-missing-gzip-compression-filte).
Not sure if this is a h5py or a conda issue

I get the following error with my conda-installed h5py

```bash
python3 -c 'import h5py; f=h5py.File("file.h5"); d=f["VAR"][:,:]; f.close()'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/juncud/miniconda3/envs/h5env/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 787, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 192, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 112, in h5py._proxy.dset_rw
OSError: Can't read data (can't open directory: /home/juncud/miniconda3/envs/h5env/lib/hdf5/plugin)
```
where file.h5 is a very large  >1GB h5 file, some other files open fine. (could share h5stat output if that helps)

This problem only occurs with conda-based h5py, e.g. installed like:

```bash
conda create -n h5env python pip h5py 
```

The problem is resolved when I use pip to reinstall, within the same conda environment:
```
conda remove h5py
pip install h5py
```

### versions
- OS: Linux Mageia Release 7
- problem persists through varied combinations of python (3.6+), h5py (2.x, 3.x) and HDF5 versions

**Comment by takluyver** [comment]
This sounds like the 'VAR' dataset uses a [filter](https://docs.h5py.org/en/stable/high/dataset.html#filter-pipeline), probably for compression, and the conda package doesn't have that filter available. HDF5 can use plugins for filters, which is why it's trying to open a plugin directory.

With the pip package that can read the file, it should be easy to poke around and figure out what filter/filters it needs. Depending on what it is, it might be reasonable to request that the Anaconda or conda-forge package adds it, or you might need to install a plugin for it.

**Comment by vasole** [comment]
Can we have access to your file.h5?

**Comment by djuncu** [comment]
thanks for looking into this.

I am currently waiting for an answer on whether the file can be shared or not.

What I can add for now:
- the 'VAR' dataset is indeed compressed. With szip as far as I can tell
- the file is written using Fortran 90
- and I should add regarding the `can't open directory` error mentioned above: there is no `hdf5` directory in `/home/juncud/miniconda3/envs/h5env/lib`. So I guess conda-h5py is just looking for the plugin in the wrong place?

**Comment by takluyver** [comment]
See also https://github.com/conda-forge/h5py-feedstock/issues/63 (for packages from conda-forge) and https://github.com/ContinuumIO/anaconda-issues/issues/11382 (for packages from the default Anaconda channel).

If you know an szip HDF5 plugin library is available somewhere, you can set the environment variable HDF5_PLUGIN_PATH to the directory where it should be found. But if you don't have a plugin, that will probably just change the error message HDF5 gives.

**Comment by vasole** [comment]
As far as I remember SZIP is an option you have to enable when building the HDF5 library. It is not intended to be used as a filter plugin.

I recall to have produced h5py versions with SZIP enabled many years ago.

**Comment by vasole** [comment]
If anaconda does not work while h5py from pip it does, it is clearly an anaconda issue.

**Comment by djuncu** [comment]
perfect, this clarifies a lot!
