### ISSUE TITLE
Invalid data for LZF decompression error

### ISSUE THREAD

**Issue by lengstrom** [h5py/h5py#1870]
I get the following traceback when I try to access a row in my h5py matrix:
```
OSError                                   Traceback (most recent call last)
<ipython-input-26-d168ee847c59> in <module>
----> 1 h['cifar']['train']['confs']['24'][22284]

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

~/miniconda3/envs/cuda11/lib/python3.8/site-packages/h5py/_hl/dataset.py in __getitem__(self, args, new_dtype)
    788         mspace = h5s.create_simple(selection.mshape)
    789         fspace = selection.id
--> 790         self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
    791 
    792         # Patch up the output for NumPy

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5d.pyx in h5py.h5d.DatasetID.read()

h5py/_proxy.pyx in h5py._proxy.dset_rw()

OSError: Can't read data (Invalid data for LZF decompression)
```

What could cause this kind of error? It only occurs when accessing a small number of rows in my table. Each row in my table is written by a different process, but each uses the same code. I am also storing the table over NFS, if this means anything.

Here is my version information:
```
h5py    3.2.1
HDF5    1.12.0
Python  3.8.0 (default, Nov  6 2019, 21:49:08)
[GCC 7.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.20.2
cython (built with) 0.29.22
numpy (built against) 1.17.5
HDF5 (built against) 1.12.0
```

**Comment by takluyver** [comment]
> Each row in my table is written by a different process, but each uses the same code. I am also storing the table over NFS

That sounds suspect. HDF5 normally uses file locking so only one process can have a file open for writing at once, but this is known not to work reliably over NFS. So writing to a file on NFS can corrupt the data.

Depending on what you're doing, you might be able to give each writer process its own file, and then combine the data on read. Or you could have the processes producing the data send it to a single writer process which puts it into a file.

**Comment by takluyver** [comment]
Closing this as presumed NFS corruption. We can reopen it if it's reproducible with a local filesystem. Although if it is, the chances are it's an HDF5 bug anyway, so it may make more sense to contact HDF group.
