### ISSUE TITLE
Cython wheel not used but numpy wheel is

### ISSUE THREAD

**Issue by nathanblair** [h5py/h5py#1872]
* Operating System: Alpine Linux 3.13
 * Python version: 3.8.8
 * Where Python was acquired: Alpine Package Registry
 * h5py version: 3.2.1

I am building an h5py wheel in an Alpine build image. I have the wheels for `numpy` and `Cython` copied into the `/wheels` directory. During the `pip wheel` of `h5py` it correctly finds the `numpy` wheel in the wheels directory but does not seem to care about the `Cython` wheel.

Any thoughts on this? It doesn't look like the build requirements list Cython as a requirement but I may be missing something.

```
/ # ls -lA /wheels
total 6428
-rw-r--r--    1 root     root        980535 Apr 11 01:13 Cython-0.29.22-py2.py3-none-any.whl
-rw-r--r--    1 root     root       5597218 Apr 10 08:50 numpy-1.20.2-cp38-cp38-linux_x86_64.whl
```

```
#11 [build 1/1] RUN pip wheel -w "/wheels" h5py=="3.2.1"
#11 sha256:52c8ae1fd876b277c3fcee034ee9d0c49c398f29167904a34f76b6047e2c1b29
#11 1.176 Looking in links: /wheels
#11 1.478 Collecting h5py==3.2.1
#11 1.694   Downloading h5py-3.2.1.tar.gz (368 kB)
#11 1.950   Installing build dependencies: started
#11 4.290   Installing build dependencies: finished with status 'done'
#11 4.291   Getting requirements to build wheel: started
#11 4.565   Getting requirements to build wheel: finished with status 'done'
#11 4.568     Preparing wheel metadata: started
#11 4.897     Preparing wheel metadata: finished with status 'done'
#11 5.393 Processing /wheels/numpy-1.20.2-cp38-cp38-linux_x86_64.whl
#11 5.393   File was already downloaded /wheels/numpy-1.20.2-cp38-cp38-linux_x86_64.whl
#11 5.403 Building wheels for collected packages: h5py
#11 5.404   Building wheel for h5py (PEP 517): started
#11 5.627   Building wheel for h5py (PEP 517): finished with status 'error'
#11 5.627   ERROR: Command errored out with exit status 1:
#11 5.627    command: /usr/bin/python3 /usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpfp6zj27g
#11 5.627        cwd: /tmp/pip-wheel-0ln7tye0/h5py_a41493a5e4e7463fa8aa4e1b832d6939
```

...

```
#11 5.627   Traceback (most recent call last):
#11 5.627     File "/usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
#11 5.627       main()
#11 5.627     File "/usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
#11 5.627       json_out['return_val'] = hook(**hook_input['kwargs'])
#11 5.627     File "/usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
#11 5.627       return _build_backend().build_wheel(wheel_directory, config_settings,
#11 5.627     File "/tmp/pip-build-env-df_0oxkq/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 221, in build_wheel
#11 5.627       return self._build_with_temp_dir(['bdist_wheel'], '.whl',
#11 5.627     File "/tmp/pip-build-env-df_0oxkq/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
#11 5.627       self.run_setup()
#11 5.627     File "/tmp/pip-build-env-df_0oxkq/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
#11 5.627       exec(compile(code, __file__, 'exec'), locals())
#11 5.627     File "setup.py", line 156, in <module>
#11 5.627       setup(
#11 5.627     File "/tmp/pip-build-env-df_0oxkq/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
#11 5.627       return distutils.core.setup(**attrs)
#11 5.627     File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
#11 5.627       dist.run_commands()
#11 5.627     File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
#11 5.627       self.run_command(cmd)
#11 5.627     File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
#11 5.627       cmd_obj.run()
#11 5.627     File "/tmp/pip-build-env-df_0oxkq/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
#11 5.627       self.run_command('build')
#11 5.627     File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
#11 5.627       self.distribution.run_command(command)
#11 5.627     File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
#11 5.627       cmd_obj.run()
#11 5.627     File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
#11 5.627       self.run_command(cmd_name)
#11 5.627     File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
#11 5.627       self.distribution.run_command(command)
#11 5.627     File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
#11 5.627       cmd_obj.run()
#11 5.627     File "/tmp/pip-wheel-0ln7tye0/h5py_a41493a5e4e7463fa8aa4e1b832d6939/setup_build.py", line 121, in run
#11 5.627       from Cython import __version__ as cython_version
#11 5.627   ModuleNotFoundError: No module named 'Cython'
#11 5.627   ----------------------------------------
#11 5.628   ERROR: Failed building wheel for h5py
#11 5.628 Failed to build h5py
#11 5.628 ERROR: Failed to build one or more wheels
```

**Comment by takluyver** [comment]
What version of pip do you have? Cython is listed as a build requirement:

https://github.com/h5py/h5py/blob/7f918857e2a63477038afccda518ebd3159c13b2/setup.py#L41-L54

**Comment by nathanblair** [comment]
@takluyver I was looking at those lines as well. It does seem like it should be finding it. I wonder if it may the the `H5PY_SETUP_REQUIRES=0` interfering in some way? I don't know how it would mess up `Cython` but not `numpy`. If I leave that env variable undefined the setup didn't recognize either of the existing wheels on the system and just tried to download (and build) them on its own.

Here's my python ecosystem versioning information:

```
/ # python3 --version
Python 3.8.8
/ # pip3 --version
pip 20.3.4 from /usr/lib/python3.8/site-packages/pip (python 3.8)
/ # pip --version
pip 20.3.4 from /usr/lib/python3.8/site-packages/pip (python 3.8)
```

**Comment by takluyver** [comment]
Are you saying you were setting `H5PY_SETUP_REQUIRES=0` before? If you set that, you are telling it to pretend it has no build requirements, so it's no surprise if they don't get installed.

When you don't set that, what you describe sounds like expected behaviour. I don't think pip will automatically use the output directory (`-w`) to satisfy build requirements. If you want it to do that, you'll need to tell it to use that with something like `--find-links /wheels`.

**Comment by nathanblair** [comment]
Indeed, `PIP_FIND_LINKS` is set with the `/wheels` directory as well.

My goal is to use the already built `Cython` and `numpy` wheels - it was my understanding that `H5PY_SETUP_REQUIRES` more-or-less tells `h5py` to not look for them and just download and build them with `h5py`.

Let me try finagling with it again without the `H5PY_SETUP_REQUIRES` being defined before building. Maybe I gave up on something too quickly before setting that.

It is weird that it recognizes and uses the `numpy` wheel but not the `Cython` one, right?

**Comment by nathanblair** [comment]
Yeah, if I leave `H5PY_SETUP_REQUIRES` undefined I get this:

```
#12 [build 1/1] RUN pip wheel -w "/wheels" h5py=="3.2.1"
#12 sha256:82e0f4c963b9503f9736765d47e6e4b7295b04970191ee2f2a6ddbb941d9d245
#12 1.034 Looking in links: /wheels
#12 1.392 Collecting h5py==3.2.1
#12 1.603   Downloading h5py-3.2.1.tar.gz (368 kB)
#12 1.848   Installing build dependencies: started
#12 4.273   Installing build dependencies: finished with status 'done'
#12 4.274   Getting requirements to build wheel: started
#12 4.464   Getting requirements to build wheel: finished with status 'done'
#12 4.476   Installing backend dependencies: started
#12 8.342   Installing backend dependencies: finished with status 'error'
#12 8.343   ERROR: Command errored out with exit status 1:
#12 8.343    command: /usr/bin/python3 /usr/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ko0_3diw/normal --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --find-links /wheels -- 'numpy==1.14.5; python_version == "3.7"' 'numpy==1.19.3; python_version >= "3.9"' 'Cython>=0.29; python_version < "3.8"' 'Cython>=0.29.15; python_version >= "3.9"' 'Cython>=0.29.14; python_version == "3.8"' 'numpy==1.17.5; python_version == "3.8"' pkgconfig
#12 8.343        cwd: None
#12 8.343   Complete output (317 lines):
#12 8.343   Looking in links: /wheels, /wheels
#12 8.343   Ignoring numpy: markers 'python_version == "3.7"' don't match your environment
#12 8.343   Ignoring numpy: markers 'python_version >= "3.9"' don't match your environment
#12 8.343   Ignoring Cython: markers 'python_version < "3.8"' don't match your environment
#12 8.343   Ignoring Cython: markers 'python_version >= "3.9"' don't match your environment
#12 8.343   Collecting Cython>=0.29.14
#12 8.343     Downloading Cython-0.29.22-py2.py3-none-any.whl (980 kB)
#12 8.343   Collecting numpy==1.17.5
#12 8.343     Downloading numpy-1.17.5.zip (6.4 MB)
#12 8.343   Collecting pkgconfig
```

I've left the same `PIP_FIND_LINKS` directory set as before where it was able to find `numpy` fine but without the `SETUP_REQUIRES` something in the setup doesn't seem to look at all in the `/wheels` directory.

**Comment by takluyver** [comment]
> It is weird that it recognizes and uses the numpy wheel but not the Cython one, right?

Looking at your output, I think it's not actually installing NumPy in a build environment. `pip wheel` by default tries to create wheels of a package plus its (runtime) dependencies. Numpy is a runtime dependency of h5py. I think it's just confirming that there's already a wheel there, so it won't create another one.

> Yeah, if I leave H5PY_SETUP_REQUIRES undefined I get this:

That looks closer to correct than before. It is identifying that it needs Cython & Numpy installed. However, h5py asks pip to build with the oldest compatible numpy, so the resulting wheel can be used with that version or any newer one. That's not the version you have in `/wheels`. You'll want to either make a wheel for that version, or manually set up a build environment and then use `H5PY_SETUP_REQUIRES=0` together with `--no-build-isolation` to tell pip not to create an isolated build environment. See [development installation](https://docs.h5py.org/en/stable/build.html#development-installation) about that.

I don't know why it downloads the Cython wheel instead of using the one you already have. Maybe PyPI takes precedence if the same file exists there and in the `--find-links` directory.

**Comment by nathanblair** [comment]
So `h5py` locks in a version (the oldest compatible) for `numpy`? Is there a way to get it to recognize later releases of `numpy`?

This all worked without any issue with `scipy` (which in turn requires `numpy` so I don't get the sense its a conflict between PyPI and the `-w` and `--find-links` flags :/

**Comment by nathanblair** [comment]
I'll go ahead and close this as it seems like the expectation is for a separate build environment to be maintained when using pre-built wheels. And I think this case seems to be treading undocumented/undefined behavior.

I think this warrants some further research to discover the edge cases like this that fall between the cracks of using hard-coded versions for dependencies. But I leave that to the maintainers of the project to decide if that's in their goal and scope to support.

For everyone else, there's always `requirements.txt` 🤷‍♂️

**Comment by takluyver** [comment]
It's definitely not an ideal solution, but what we're doing seems to be the best available option - Python packaging isn't really set up to understand 'links against' relationships or ABI compatibility.

Scipy also [pins the oldest compatible numpy](https://github.com/scipy/scipy/blob/c4a1f02b5fa44aa660aaac96151705fcdfdf624d/pyproject.toml#L31), and this approach is [recommended by NumPy](https://numpy.org/devdocs/user/depending_on_numpy.html#build-time-dependency). I'm not sure why you see different behaviour for scipy - maybe because it doesn't define a PEP 517 buildsystem, it doesn't get build isolation by default yet. That will probably change one day, but the `--no-build-isolation` flag is there if you need it.
