### ISSUE TITLE
OSError: Can't write data (wrong B-tree signature)

### ISSUE THREAD

**Issue by SamTov** [h5py/h5py#1876]
I am using h5py to construct a database within some software I am developing. It is a database structure built on data that I have used hundreds of times with no issues. The only difference in this case is that the data is much lager (120 GB) than what I ordinarily process (1-50 GB). I have processed data this size before, but not very often. I don't understand what could be going wrong. In the method being called, data is being written to a hdf5 database from a numpy array. It is hard to provide a gist as the backend of the software has quite a number of processes.

One important note is that I have run this code on different parts of the data and it fails after a similar amount of time. The idea here is that it isn't seeing the same piece of data and failing, it is failing at different points so the issue is not, as far as I can tell, data dependent.

To assist reproducing bugs, please include the following:
 * Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 16.04.2 LTS, CentOS 7)
I am using Ubuntu 20
 * Python version (e.g. 2.7, 3.5)
 Python 3.8.5
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows)
On Linux
 * h5py version (e.g. 2.6)
 h5py 3.2.1
 * HDF5 version (e.g. 1.8.17)
 1.10.4+repack-11ubuntu1
 * The full traceback/stack trace shown (if it appears)
 ```sh
Traceback (most recent call last):
  File "analysis.py", line 6, in <module>
    argon.add_data(trajectory_file='gk_data.lmp_traj')
  File "/tikhome/stovey/work/Repositories/MDSuite/mdsuite/experiment/experiment.py", line 513, in add_data
    self._build_new_database(trajectory_reader, trajectory_file, database, rename_cols=rename_cols, flux=flux)
  File "/tikhome/stovey/work/Repositories/MDSuite/mdsuite/experiment/experiment.py", line 535, in _build_new_database
    database.add_data(data=trajectory_reader.read_configurations(self.batch_size, f_object, line_length),
  File "/tikhome/stovey/work/Repositories/MDSuite/mdsuite/database/database.py", line 133, in add_data
    database[item][:, start_index:stop_index, :] = self._get_data(data, structure, item, batch_size, sort,
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/tikhome/stovey/.local/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 948, in __setitem__
    self.id.write(mspace, fspace, val, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 232, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 114, in h5py._proxy.dset_rw
OSError: Can't write data (wrong B-tree signature)
```
`h5py.version.info` contains the needed versions, which can be displayed by
```
python -c 'import h5py; print(h5py.version.info)'
```
```sh
h5py    3.2.1
HDF5    1.12.0
Python  3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.19.5
cython (built with) 0.29.22
numpy (built against) 1.17.5
HDF5 (built against) 1.12.0
```

**Comment by aragilar** [comment]
@SamTov What filesystem are you using, issues have been seen on NFS for example?

**Comment by SamTov** [comment]
It is on an NFS

**Comment by takluyver** [comment]
Unfortunately there are known problems with file locking on NFS which can corrupt files, and your mention of "quite a number of processes" fits with that. If you can reproduce it on a local filesystem, we'll probably point you towards HDF5, because h5py doesn't deal with the details of the file format (like B-trees) directly.

**Comment by tacaswell** [comment]
hdf5 assumes it is on a filesystem with POSIX write semantics (critically that if the low level write returns it can the immediately read the file back and get the bits just written).  On non compliant file systems (like NFS) when this fails libhdf5 gets it self crossed on the internal metadata (internally hdf5 maintains a couple of b-trees that map the data set / group names to chunk uid and chunk uids to byte offsets in the file (to zeorth order)).  Finding a good link to document this is surprisingly hard, https://portal.hdfgroup.org/display/knowledge/What+is+HDF5 at the bottom may be the best reference?

If it every works on an NFS file system at all I think that means you are getting lucky and winning the race.  When you push to bigger files you eventually lose the race and get this failure.

**Comment by SamTov** [comment]
So just has a solution for others perhaps because the issue has arisen from an unrelated point. I was running database construction locally before performing other operations using this database on a cluster. So the NFS was just the how my local machine was accessing the cluster drive. So at least in my case the solution is to run it all on the cluster.

Thanks for all the information!
