### ISSUE TITLE
ImportError: dlopen(..) : no suitable image found.

### ISSUE THREAD

**Issue by Joeycooky** [h5py/h5py#1879]
I try to use huggingface library and the following error occur when huggingface's transformer try to import h5py

Please find the following error information 
 * Operating System macOS 11.2.3
 *  Python version : 3.8.2
 * Where Python was acquired : miniforge3
 * h5py version : 2.10.0
 * HDF5 version : 1.10.6
 * The full traceback/stack trace shown (if it appears)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wirachlee/.local/lib/python3.8/site-packages/h5py/__init__.py", line 26, in <module>
    from . import _errors
ImportError: dlopen(/Users/wirachlee/.local/lib/python3.8/site-packages/h5py/_errors.cpython-38-darwin.so, 2): no suitable image found.  Did find:
	/Users/wirachlee/.local/lib/python3.8/site-packages/h5py/_errors.cpython-38-darwin.so: mach-o, but wrong architecture
	/Users/wirachlee/.local/lib/python3.8/site-packages/h5py/_errors.cpython-38-darwin.so: mach-o, but wrong architecture

please advise how to solve this problem?

**Comment by tacaswell** [comment]
This is almost most certainly a packaging or local installation issue.  Please report this against conda-forge.

Do you happen to have an M1 mac?  If so you may need to build h5py from source.

I am going to close this as there is nothing that we can do from the h5py side to help.

**Comment by Joeycooky** [comment]
> This is almost most certainly a packaging or local installation issue. Please report this against conda-forge.
> 
> Do you happen to have an M1 mac? If so you may need to build h5py from source.
> 
> I am going to close this as there is nothing that we can do from the h5py side to help.

Hello @tacaswell , thank you for your suggestion. I have rebuilt h5py from source and it work perfectly fine for me!
