### ISSUE TITLE
Attribute as STR_NULLTERM

### ISSUE THREAD

**Issue by xgarnaud** [h5py/h5py#1885]
Hi.

I'd like to create attributes that look like this:
```
ATTRIBUTE "label" {
   DATATYPE  H5T_STRING {
      STRSIZE 33;
      STRPAD H5T_STR_NULLTERM;
      CSET H5T_CSET_ASCII;
      CTYPE H5T_C_S1;
   }
   DATASPACE  SCALAR
   DATA {
   (0): "Zone_t"
   }
}
```
so I tried doing this
```python
tid = h5py.h5t.TypeID.copy(h5py.h5t.C_S1)
tid.set_size(33)
tid.set_strpad(h5py.h5t.STR_NULLTERM)
grp.attrs.create('label', node.label.encode(), None, tid)
```
however I get this
```
ATTRIBUTE "label" {
   DATATYPE  H5T_STRING {
      STRSIZE 33;
      STRPAD H5T_STR_NULLPAD;
      CSET H5T_CSET_ASCII;
      CTYPE H5T_C_S1;
   }
   DATASPACE  SCALAR
   DATA {
   (0): "UserDefinedData_t\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
   }
}
```
Is this the expected behavior? Is there a way to get the desired output?

Best regards,

PS: adding the following line in `attrs.py`, l. 195
```python
            if isinstance(htype, h5t.TypeStringID):
                htype.set_strpad(h5t.STR_NULLTERM)
```
and I get the correct output.

**Comment by xgarnaud** [comment]
Sorry I forgot:
```
python
Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20) 
[Clang 11.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
>>> h5py.__version__
'3.1.0'
```

**Comment by takluyver** [comment]
I don't think passing in an HDF5 datatype to `attrs.create()` is fully supported - [the docs say](https://docs.h5py.org/en/stable/high/attr.html#h5py.AttributeManager.create) it takes a NumPy dtype. It probably gets converted to a dtype and back again, losing some detail in the process.

You could probably fix that if you wanted. If you need to work with existing versions, you'll need to create the attribute with the low-level API ([h5py.h5a](https://api.h5py.org/h5a.html) module).

**Comment by xgarnaud** [comment]
Thank you for your help. Using h5py.h5a works fine.
Best regards
