### ISSUE TITLE
How to read H5 file and after read how modify a data inside h5 file ?

### ISSUE THREAD

**Issue by anbuharry** [h5py/h5py#1888]
I have an h5 file named eccv16_dataset_summe_google_pool5.hdf5 how to read this file after reading how can I modify a data

**Comment by takluyver** [comment]
The documentation explains how to read & write HDF5 files.

https://docs.h5py.org/en/stable/quick.html#quick

**Comment by anbuharry** [comment]
> The documentation explains how to read & write HDF5 files.
> 
> https://docs.h5py.org/en/stable/quick.html#quick

Thank you
