### ISSUE TITLE
ImportError on CentOS 7 in Anaconda VEnv

### ISSUE THREAD

**Issue by DLeeSolar** [h5py/h5py#1893]
Simply, `import h5py` fails with an `ImportError`. Found this when importing other modules, which had a Traceback leading to here. Any help would be greatly appreciated. Perhaps worth noting that h5py version 2.9.0 works without error. 

Here's the versions I'm using. 
 * OS: CentOS 7, 7.9.2009 
 * Python: 3.7.10 
 * Using Anaconda
 * h5py version: 3.2.1, build: nompi_py37ha3df211_100, channel: conda-forge
 * HDF5 version: 1.10.6

```
Python 3.7.10 (default, Feb 26 2021, 18:47:35)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.23.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import h5py
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c9f0b8c65221> in <module>
----> 1 import h5py

~/.conda/envs/SunPy2021/lib/python3.7/site-packages/h5py/__init__.py in <module>
     31         raise
     32
---> 33 from . import version
     34
     35 if version.hdf5_version_tuple != version.hdf5_built_version_tuple:

~/.conda/envs/SunPy2021/lib/python3.7/site-packages/h5py/version.py in <module>
     13
     14 from collections import namedtuple
---> 15 from . import h5 as _h5
     16 import sys
     17 import numpy

h5py/h5.pyx in init h5py.h5()

ImportError: ~/.conda/envs/SunPy2021/lib/python3.7/site-packages/h5py/defs.cpython-37m-x86_64-linux-gnu.so: undefined symbol: H5Pset_fapl_ros3

In [2]:
```

**Comment by takluyver** [comment]
That looks like h5py was built against HDF5 with ROS3 enabled, but is finding an HDF5 library at runtime which doesn't have ROS3 enabled. This is either a problem with your environment, or with how conda-forge is building the package (see the https://github.com/conda-forge/h5py-feedstock/ repo).

**Comment by takluyver** [comment]
Closing as I don't think there's anything to do in HDF5 - it looks like an issue with how it was built or used.
