### ISSUE TITLE
who wrote this library like rubbish,please close it right now and throw your computer 

### ISSUE THREAD

**Issue by xkungfu** [h5py/h5py#1894]
To assist reproducing bugs, please include the following:
 * Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 16.04.2 LTS, CentOS 7)
 * Python version (e.g. 2.7, 3.5)
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows)
 * h5py version (e.g. 2.6)
 * HDF5 version (e.g. 1.8.17)
 * The full traceback/stack trace shown (if it appears)

`h5py.version.info` contains the needed versions, which can be displayed by
```
python -c 'import h5py; print(h5py.version.info)'
```
where `python` should be substituted for the path to python used to install
`h5py` with.

**Comment by tacaswell** [comment]
We will not tolerate abusive and non-productive comments like this on h5py.  I am going to block @xkungfu for 30 days and locking conversation to only organization members.

If after that time, @xkungfu you have constructive comments or an actionable bug report please open a new issue.
