### ISSUE TITLE
opening a file in mode 'a' fails

### ISSUE THREAD

**Issue by alexlenail** [h5py/h5py#1901]
The docs say

    >>> f = h5py.File('myfile.hdf5','r')

The file name may be a byte string or unicode string. Valid modes are:

    ========  ================================================
     r        Readonly, file must exist (default)
     r+       Read/write, file must exist
     w        Create file, truncate if exists
     w- or x  Create file, fail if exists
     a        Read/write if exists, create otherwise
    ========  ================================================

But opening a file in mode `'a'` causes `OSError: Unable to create file (file exists)` if the file exists. 

<details>
h5py    3.2.1
HDF5    1.12.0
Python  3.7.10 (default, Feb 27 2021, 02:19:57)
[Clang 12.0.0 (clang-1200.0.32.29)]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.18.1
cython (built with) 0.29.22
numpy (built against) 1.14.5
HDF5 (built against) 1.12.0
</details>

**Comment by takluyver** [comment]
Do you have permission to open the file in write mode? I suspect this is a problem with reporting the error - it's failing to open it, then falling back to trying to create it.

**Comment by alexlenail** [comment]
I do have permission. It seems like my mistake may have been that the file might have already been open, with a different handle, elsewhere in my notebook. If that explains it, please close this issue -- unless you think it would make sense to catch that specific error case.

**Comment by takluyver** [comment]
That might do it, although normally HDF5 is OK with opening the same file twice in the same process (the library coordinates access internally). I've opened PR #1902 to improve how errors are handled with append mode.
