### ISSUE TITLE
ipython tab complete on dataset hangs, possibly loading data

### ISSUE THREAD

**Issue by scottstanie** [h5py/h5py#1908]
When I hit `ds.<tab>` on a dataset in ipython, it hangs and/or uses a lot of memory:

```python
In [1]: import h5py
In [3]: import numpy as np
In [4]: with h5py.File("testipy.h5", "w") as hf:
   ...:     hf['test'] = np.random.random((1000, 1000, 1000))
   ...:
```
This is a 7.5 GB test file:

```python
In [5]: hf = h5py.File("testipy.h5")

In [6]: hf.keys()
Out[6]: <KeysViewHDF5 ['test']>

In [7]: ds = hf['test']

In [8]: ds.
```
If I double tap tab on this small example, it hangs for just a few seconds, but then ipython is using ~15 GB of RAM.

If I hit tab once, it freezes for awhile. On my bigger dataset (a ~50 GB file), this made ipython slowly grow in memory until i killed it (I'm on a workstation and it was up to 30-40 GB of memory and climibing).

```python
In [6]: print(h5py.version.info)
Summary of the h5py configuration
---------------------------------

h5py    2.10.0
HDF5    1.10.6
Python  3.8.5 | packaged by conda-forge | (default, Aug 29 2020, 01:22:49)
[GCC 7.5.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.19.2
```

**Comment by scottstanie** [comment]
Just noting that the hanging/memory growth doesn't seem to happen when I upgrade to the latest 3.2.1 version. Not sure if this is worth a backward patch or not (I'm not sure what is causing the data to get loaded from tab completing)

**Comment by takluyver** [comment]
We don't normally do bugfix releases for old feature versions, so if it's working as expected in the latest version, there's nothing really to do. You're probably seeing #1312.
