### ISSUE TITLE
Unable to open file (file signature not found) in version 3.1.0 if using bytesIO

### ISSUE THREAD

**Issue by pokecheater** [h5py/h5py#1915]
Hey H5py Dev Team :-),

I am facing a strange error after updating my python packages. Before I was using verison 2.10.0 and now it is 3.1.0 of your h5py library. 

My situation is as follows: 
Because keras save_model method need a h5 file handle for saving the model and I want to store it into a memfile (for saving it into a database), I am using a bytesIO stream instead of a real file handle. This worked out in the version 2.10.0 like a charm:

` 
 bytes_file = io.BytesIO()
 hdf5_file = h5py.File(bytes_file)
 model.save(hdf5_file)
`

Since the new version I am getting the error:
`
 Unable to open file (file signature not found)
  File "****", line ***, in save_model
    hdf5_file = h5py.File(bytes_file)
`

My solution is to go back in time and using your old version.
But I think this is an error that can be quickly fixed on your site (since it worked out before).

Greetz and Thx in advance.

**Comment by aragilar** [comment]
The open mode is missing, currently you're trying to open the file in read-only mode (which then fails).

Try `h5py.File(bytes_file, mode="w")`.

**Comment by aragilar** [comment]
I've dug into this more, looks like there an issue specific to BytesIO (I would suspect StringIO wouldn't work at all with the fileobj driver, but if it did, then it would have the same issue): if you try to operate in read-only mode on an 0-length buffer, then the superblock cannot be read (hence `file signature not found`). We can do some checks about this when opening the file, to make the error more obvious (I'm not sure there's an actual use-case for reading an empty file).

Note that read only on an empty file (e.g. one created via tempfile) *does* work, so I suspect its a difference in how BytesIO is emulating a file-like interface.

We'd probably need to do more error checking in the fileobj read function to work out specifically what the difference is, but I don't think there would be a different conclusion from the "don't do that" above.

**Comment by pokecheater** [comment]
Hey aragilar,

I will try on opening it with a file mode and let you know. 
But even if this works out the elephant remains in the room: Why did it worked out in a previous version and is not supported yet anymore?
The open mode was not necessary before.

Greetz

**Comment by pokecheater** [comment]
Thanks aragilar, 
setting the write mode did the trick :).
