### ISSUE TITLE
Is there an example how to work with ValuesViewHDF5?

### ISSUE THREAD

**Issue by RGBYCP** [h5py/h5py#1918]
I cannot find in the documentation information about ValuesViewHDF5 or about `<class 'h5py._hl.base.ValuesViewHDF5'>`
Or about `closed HDF5 group`

I try to extract a group from an hdf5 file and want to store it in a Python variable. Then I close the file.
Later I wish to access this group to start now with postprocessing of single data sets contained in this group. 
I know when the hdf5 file is open, I could extract each dataset and store it in a variable. Is this the only way to do this, please?
I want to avoid touching the data structure when opening the file, but extract the data. There are around 25 datasets in the subgroup. 

Thank you for your advice.

**Comment by takluyver** [comment]
If you *explicitly* close the file, group & dataset objects from that file become invalid; you can no longer use them. So you have two options:

- Let the file stay open: so long as you don't call `f.close()` or leave a `with h5py.File():` block, storing the group object will keep the file open (documented under [closing files](https://docs.h5py.org/en/stable/high/file.html#closing-files)).
- Read all the datasets you want into numpy arrays before closing the file.

I hope that helps.

**Comment by RGBYCP** [comment]
Thank you for your reply. Yes, that helped.

I open files usually with the with statement and I understood using a with block is recommended (and it closes automatically my file when I leave the with block).
Within this with block, I tried to extract the whole subgroup, but it was later not anymore accessible (I had left the with block). Somebody else gave me the advise to try this, but maybe he did not realise this object wouldn't be accessible outside of with.
I guess, I have no choice then to extract all datasets from this subgroup while being in this with block.
My approach is currently a dict to have all data together. 

May I ask as well for an explanation/example how to use .values(), please?
I extracted the data with `f[path/to/dataset][:]`, but I did not understand how to use .values().
Thank you again.

**Comment by takluyver** [comment]
You don't have to use the with block if you don't want to:

```python
with h5py.File('xyz.h5', 'r') as f:
    grp = f['group']
# Now f and grp are both closed

f2 = h5py.File('xyz.h5', 'r')
grp2 = f2['group']
# grp2 is still usable, the file is kept open
```

Especially if you're using the file in read-only mode (`'r'`), it's probably OK to just leave it open as long as you need.

Groups behave like dictionaries, so they have `.keys()`, `.values()` and `.items()` methods like dicts ([docs](https://docs.h5py.org/en/stable/high/group.html#h5py.Group.keys)). So `.values()` gives you the datasets and subgroups under that group. None of these methods work once the file is closed, though.

**Comment by RGBYCP** [comment]
Thank you for the code example. That gives me something to think about how to potentially restructure my code and when to close the file. 

Technically, this was a new question. Sorry.
Re .values(): I asked here hoping to see a code example. I saw the manual entry, but I did not understand how to use it. 
'f[path_dataset].values() returned  the error: 'Dataset' object has no attribute 'values'. I cannot access with .values() the content of a dataset?
I think there was a .value before, but it was deprecated long time ago. 
If I apply f[subgroup].values() I get ValuesViewHDF5(<HDF5 group "path/to/subgroup" (25 members)>)
I don't understand what is the purpose of it. Thank you for your help.

**Comment by takluyver** [comment]
There are two main types of objects in HDF5 files - groups and datasets. These are a bit like folders (groups) and files (datasets). The HDF5 file itself also behaves like a group (the 'root group'). In h5py, groups work like dictionaries, so `.values()` lets you loop through all the objects within a group:

```python
f['xyz']  # Might give you a group or a dataset

for obj in f.values():
    ... # obj might be a group or a dataset
```
