### ISSUE TITLE
h5py with 32-bit python on windows 10

### ISSUE THREAD

**Issue by oholimoli** [h5py/h5py#1928]
Is it possible to use `h5py` with a 32-bit `python` on windows 10? I suppose `hdf5` must also be installed as a 32-bit version but I could only find a 32-bit version for `linux`.

**Comment by takluyver** [comment]
It should be possible. You can get a 32-bit version of [Anaconda](https://www.anaconda.com/products/individual) and install everything from that (or start with [Miniconda](https://docs.conda.io/en/latest/miniconda.html) if you prefer).

If you've got a 32-bit Python set up already without Anaconda, you'd probably need to build HDF5 and h5py from source, which is a fair bit of work, especially on Windows. It's probably easier to make a new Python installation, either with Anaconda or using 64-bit Python.

**Comment by takluyver** [comment]
Another option is to use the wheels Christoph Gohlke provides, which still have 32-bit versions as well as 64-bit.
