### ISSUE TITLE
How convert tensorflow.python.data.ops.dataset_ops.BatchDataset to HDF5?

### ISSUE THREAD

**Issue by bethven** [h5py/h5py#1930]
Hello,
I need to load large image datasets (JPEG and other types) with tensorflow and then transform them to HDF5, I have loaded the dataset with the following code, but I don't know how to transform it to HDF5.**

```python
img = tf.keras.preprocessing.image_dataset_from_directory(
    '/home/tiny-imagenet-200/train/',
    labels="inferred",
    label_mode="int",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(256, 256),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
)
```

I tried to do it like it did in python, but it doesn't work:

```python
    Imagen = cv2.imread(img)
    Imagen = cv2.resize(Imagen, (224, 224), interpolation=cv2.INTER_CUBIC)
    Imagen = cv2.cvtColor(Imagen, cv2.COLOR_BGR2RGB)
```

The error:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-18-94fcf3e072ce> in <module>
      8
      9   #  Direc = Address_imag[i]
---> 10     Imagen = cv2.imread(img)
     11     Imagen = cv2.resize(Imagen, (224, 224), interpolation=cv2.INTER_CUBIC)
     12     Imagen = cv2.cvtColor(Imagen, cv2.COLOR_BGR2RGB)

TypeError: Can't convert object of type 'tensorflow.python.framework.ops.EagerTensor' to 'str' for 'filename'
```

I guess it is because of the type of object it generates that it is: tensorflow.python.data.ops.dataset_ops.BatchDataset

Please I would appreciate if someone can help me to know how to transform this to HDF5. 
Thank you.

**Comment by takluyver** [comment]
You might need to ask in a Tensorflow forum about this - I don't know what you can do with a `BatchDataset` object. I think `imread` is expecting a filename for a single image.
