### ISSUE TITLE
Unable to use h5py with multiple Python versions when using Pipenv

### ISSUE THREAD

**Issue by AlexanderWells-diamond** [h5py/h5py#1932]
* Operating System: RH7, RH8
 * Python version: 3.7, 3.8, 3.9
 * Where Python was acquired: Issues occurs with both self-built from binaries and from RedHat package manager
 * h5py version: 3.3.0
 * HDF5 version: 1.12
```
Summary of the h5py configuration
---------------------------------

h5py    3.3.0
HDF5    1.12.0
Python  3.7.9 (default, Apr 23 2021, 13:40:12) 
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.20.2
cython (built with) 0.29.23
numpy (built against) 1.14.5
HDF5 (built against) 1.12.0
```

There is an issue when trying to use Pipenv virtual environments when targeting multiple different Python versions for a library. When we create our Pipfile.lock on Python 3.7 the line `"markers": "python_version == '3.7'",` is added to the `numpy` section. This means that when we attempt to use this Pipfile.lock to create a virtual environment on Python 3.8 or 3.9 we cannot, as the marker causes `numpy` to be skipped from the installation.

 This issue is caused by  [setup.cfg line 30](https://github.com/h5py/h5py/blob/master/setup.py#L30), and the `RUN_REQUIRES` definition on line 36, which causes the marker `python_version=='3.7'` to be added to the numpy requirement of h5py. 

This issue was not present on h5py 2.10, which we previously used but upgraded away from due to there not being pre-built packages for Python 3.9 available. However doing so introduces this new issue and leaves us in a sticky situation.

Help would be much appreciated :)

**Comment by aragilar** [comment]
This sounds like a pipenv bug to me (either it's assuming you're always using python 3.7, or it doesn't know how to handle environment markers correctly).

**Comment by AlexanderWells-diamond** [comment]
While I'm not a Pipenv expert by any means, to me it seems to be doing exactly as asked. I extracted this line from Pipenv's `install --verbose` output:
```
  h5py==3.3.0               requires cached-property; python_version < "3.8", numpy>=1.14.5; python_version == "3.7"
```

This to me seems quite clear that h5py is mandating Python3.7 for its `numpy` dependency, and Pipenv has no way to know that there's others for different Python versions.

**Comment by aragilar** [comment]
From the wheel on PyPI we have:
```
Requires-Dist: numpy (>=1.14.5) ; python_version == "3.7"
Requires-Dist: numpy (>=1.17.5) ; python_version == "3.8"
Requires-Dist: numpy (>=1.19.3) ; python_version >= "3.9"
```
so the information is definitely there. Some searching on the pipenv bugtracker finds https://github.com/pypa/pipenv/issues/4003 and https://github.com/pypa/pipenv/issues/3193 which sound like the problem you're having.

**Comment by AlexanderWells-diamond** [comment]
I agree that this is not a `h5py` bug. 

For anyone else who finds this: The `pipenv` issue can be worked around by specifying the `numpy` requirement in the Pipfile itself, which will override `h5py`'s marker for the python version and so the resultant `Pipfile.lock` will be usable on multiple Python versions.
