### ISSUE TITLE
h5py package installation on raspberry pi aarch64

### ISSUE THREAD

**Issue by vs1612** [h5py/h5py#1933]
Hello,
I am trying to install h5py package on aarch64(raspberry pi 4), but i am not able to install. 
could someone please help me with this?
 If any wheel file is available please share.

Regards,
vikas

**Comment by kif** [comment]
Raspbian is usually based on debian and python3-h5py is available for debian 10 and 11.
Did you try `sudo apt install python3-h5py` ? It works on Armbian (another flavour of arm64 boards)

**Comment by vs1612** [comment]
I already tried that. it was not working.
Then I decided to create conda environment.

**Comment by kif** [comment]
OK, then the issue is closed.

**Comment by vs1612** [comment]
yeah you close the issue. I have used conda environment for my use case,
but if someone wants to use python virtual environment then how to resolve
this issue?

**Comment by vs1612** [comment]
Ok, Thank you
