### ISSUE TITLE
Remove AUTHORS list?

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#1940]
h5py currently has a list of contributors (`AUTHORS`) sorted by how many commits they have made. This is updated on each release by rever from the git log plus `.authors.yml`.

This seems like a nice way to acknowledge contributions, but it has been a recurring pain for casual contributors. They try to submit a small fix or improvement, CI complains that they're not in `.authors.yml`, and when they make a second commit to fix that, it's not unusual for it to have a slightly different name or email, causing a further problem. I think this happens particularly when people move between machines, or between committing the old fashioned way and committing through GitHub's web interface. #1913 and #1937 are current examples of this kind of problem. It's a pain as a maintainer to keep explaining about this.

It's also a bit uncomfortable to be asking people to record their names and email addresses. Admittedly it's only information that's in the commit history anyway, and maybe asking people to add it to a file makes it clear what they're sharing. But it still feels odd (and Github obscures commit author info a bit unless you actually clone the repo).

I'm proposing that we remove `AUTHORS` and `.authors.yml`, and stop using the associated rever activity. Github [lists contributors](https://github.com/h5py/h5py/graphs/contributors) anyway with much more detail. The only downside is that it doesn't acknowledge contributors without a Github account, but my experience across various projects on Github is that it's vanishingly rare to receive patches from people not on Github, so this seems like the lesser of two evils.

Alternatively, we could find/make some other tool to list authors from commits, without forcing everyone to disambiguate themselves. Some people's commits would get split over multiple names, so this would be less accurate, but it wouldn't be restricted to people on Github. We could still have optional disambiguation (e.g. using `.mailmap`) without requiring it.

Preferences?

**Comment by tacaswell** [comment]
I am 👍🏻 on removing `.authors.yml`.  My biggest concern is the added friction it presents to contributors.

**Comment by aragilar** [comment]
Yep, happy to remove it. The main thing the `.authors.yml` seems to give us is the ordering, which anyone (independent of the project) could compute using `.mailmap` and some git-fu. I don't think the struggles people have are worth it (it's not like we require a DCO or similar, which is basically what we're forcing new users to do without the actual signing...).

I think leave the `.mailmap` as is (perhaps dropping the header about auto-generation), and if we really want to have a list of authors, generate that at release time.
