### ISSUE TITLE
ros3 file driver keyword arguments must be bytes objects

### ISSUE THREAD

**Issue by ajelenak** [h5py/h5py#1949]
The documentation does not mention that the keyword arguments for the `ros3` file driver must be `bytes` objects. I had them as strings and got a `TypeError` exception. For example, this works:
```python
h5py.File(s3url, mode="r", driver="ros3",
               aws_region=b"aws-region",
               secret_id=b"aws-secret",
               secret_key=b"aws-secret")
```
Either the documentaiton is updated or these arguments are converted to bytes in the code.

---
```
Summary of the h5py configuration
---------------------------------

h5py    3.3.0
HDF5    1.12.1
Python  3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20) 
[Clang 11.0.1 ]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.20.3
cython (built with) 0.29.23
numpy (built against) 1.20.3
HDF5 (built against) 1.12.1
```

**Comment by tacaswell** [comment]
What encoding does ros3 expect?  We might as well do that conversion.

**Comment by ajelenak** [comment]
ASCII should be enough.

**Comment by tacaswell** [comment]
> ASCII should be enough.

If that is the case, then I have changed my mind and we should document that it needs to be bytes and leave the users to do the conversion (as we do not want to get into the middle of the many ways you can go from high unicode code points to something that fits in ASCII).

**Comment by ajelenak** [comment]
That's why offered both options. 😄
