### ISSUE TITLE
Wrapping hdf5 v1.12.1 H5Pset_file_locking

### ISSUE THREAD

**Issue by t20100** [h5py/h5py#1950]
libhdf5 v1.12.1 provides a function to toggle file locking instead of using the `HDF5_USE_FILE_LOCKING` environment variable:
- [H5Pset_file_locking](https://portal.hdfgroup.org/display/HDF5/H5P_SET_FILE_LOCKING) 
- [H5Pget_file_locking](https://portal.hdfgroup.org/display/HDF5/H5P_GET_FILE_LOCKING)

It would be great to have access to this through h5py since at the same time libhdf5 changed the behaviour of the `HDF5_USE_FILE_LOCKING` environment variable and it's no longer possible to use it to workaround file locking on a per file basis.

related to #1722

**Comment by takluyver** [comment]
Adding it to the low-level API should be simple and uncontroversial, if you want to make a PR for that (there are [docs on how to add HDF5 functions](https://docs.h5py.org/en/stable/contributing.html#adding-a-function-from-the-hdf5-c-api)).

Whether & how to expose it in the high-level API might be a bit more controversial, so I'd suggest leaving that to a separate PR. But people have problems with file locking often enough that it's probably reasonable.

**Comment by t20100** [comment]
OK, I got something that starts to work, I'll prepare 2 PRs then.

**Comment by takluyver** [comment]
Closed by #1951 (low-level methods) and #1952 (high-level option for `File` class).
