### ISSUE TITLE
ValueError: Not a Location

### ISSUE THREAD

**Issue by ceregan** [h5py/h5py#1957]
To assist reproducing bugs, please include the following:
 * Operating System: Windows 10
 * Python version: 3.8.8
 * Where Python was acquired: Anaconda on Linux
 * h5py version: 3.3.0
 * HDF5 version: 1.10.6

I am quite new to python, and I am trying to get data from a HDF file to then use. 

I wrote a code that managed to access the data and manipulate it to how I needed it, and since re-starting my console I am now getting an error. I think that I have to change something about closing the file before I exit, but I'm not sure exactly what/how to do this. 

The lines of code I have are:

```
# Read in the file that contains all BS crossings data
with h5py.File('MEX_BS_2004_2017.hdf5', 'r') as f:
    # List all groups
    print("Keys: %s" % f.keys())
    timeUT              = list(f.keys())[8]
    PC_coord_old        = list(f.keys())[5]
    MSO_coord_old       = list(f.keys())[3] 
```

The error I am now getting: 

```
Traceback (most recent call last):

  File "C:\Users\cr2\AppData\Local\Temp/ipykernel_16532/3979548673.py", line 1, in <module>
    timeUT      = list(f[timeUT])

  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "C:\Users\cr2\anaconda3\lib\site-packages\h5py\_hl\group.py", line 305, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)

  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "h5py\h5o.pyx", line 190, in h5py.h5o.open

ValueError: Not a location (invalid object ID)
```

Any help would be hugely appreciated! Thanks

**Comment by kif** [comment]
I you are accessing some closed file, i.e. f is closed after leaving the "with h5py.File ...:" block.

**Comment by ceregan** [comment]
> I you are accessing some closed file, i.e. f is closed after leaving the "with h5py.File ...:" block.

How to I change this? Thanks

**Comment by takluyver** [comment]
If you use `with h5py.File(...)`, you can only access the file inside the indented block of code after that line. When it runs code after that block, the file has been closed, and you can't use it any more.

So you can either move code that uses the file object `f` into that block, or get rid of the block and use `f = h5py.File(...)` instead of `with h5py.File(...) as f`.  In that case, the file may not be closed automatically, but you can use `f.close()` to close it manually if you need to.
