### ISSUE TITLE
Importing h5py module takes significant amount of time

### ISSUE THREAD

**Issue by ReallyNiceGuy** [h5py/h5py#1959]
OS:
  Distributor ID:	Ubuntu
  Description:	Ubuntu 20.04.3 LTS
  Release:	20.04
  Codename:	focal
  CPU: AMD Ryzen 5 3600 6-Core Processor
  HD: WD Blue SSD

Summary of the h5py configuration
---------------------------------
h5py    2.10.0
HDF5    1.10.4
Python  3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.17.4

Importing h5py takes 0.3s in my desktop. My whole process takes 1.8s without considering the import time.
Is there a way to improve the loading time for read only operation?

**Comment by kif** [comment]
I measured 98ms for loading numpy, and 112ms for loading h5py.
But if you load first numpy, h5py loads in 24ms ... 
So to improve the load time of h5py, one should optimize the loading of
numpy and nobody complains about the load time of numpy...

I also performed a cold start[1] and h5py loads in 150ms. If you use a
spinning disk or an remote file-system (and not an NVME flash drive)
the disk access time will be much larger, but this is purely related to
the underlying hardware.

[1] all caches emptied as explaine at:
https://www.tecmint.com/clear-ram-memory-cache-buffer-and-swap-space-on-linux/

**Comment by takluyver** [comment]
I get timings roughly similar to the 0.3 seconds @ReallyNiceGuy mentioned, but like @kif, it appears that most of that time is spent loading numpy, which is not something we can practically avoid.

Maybe it would be feasible for NumPy to separate out the core array machinery so it was possible to load that without the auxiliary functionality for masked arrays, polynomials, and so on. But that would be a big change in NumPy, and I don't know what kind of difference it would make  (I'm looking at `python -X importtime -c 'import h5py'`, but I don't know which bits of numpy would still be needed).

You're still on 2.10 - there may be some improvement with h5py 3.x (from PR #1691).

**Comment by ReallyNiceGuy** [comment]
Hi, thanks for testing also.
I noticed that in my desktop, it doesn't matter if I import numpy first.
I get this in either case (numpy first or no numpy at all):
`import time:    274254 |     278385 |     mpi4py.MPI`

If you need any more specifics, please let me know.

**Comment by takluyver** [comment]
Ah, you've got an MPI build. If you're not using MPI, you might want to try a non-MPI build (like any of the pre-built packages we offer on PyPI). h5py 3.x should also have less overhead (but still some) for loading an MPI build if you're not using MPI.

Of course, if you are using MPI, then the cost of loading mpi4py is probably not easy to avoid.

**Comment by ReallyNiceGuy** [comment]
Now it makes sense, thank you again.
I will have to swallow the load time, I have to use the version supplied by the OS.
I am closing this one, as it is resolved for me.
