### ISSUE TITLE
Feature request: consider adding `Group.__reversed__`

### ISSUE THREAD

**Issue by BvB93** [h5py/h5py#1962]
Back in python 3.8 the `__reversed__` method was added to dictionary and its various keys/values/items-views, a change made possible by the fact that dictionaries were made ordered one release earlier. I noticed that this method is lacking from `h5py.Group` though, dispite the fact that they are very much ordered.

Is there a specific reason for it's absence, and, if not, would there be any interest in adding `__reversed__`?

Looking at relevant `GroupIter` class, it should be fairly trivial to implement a reversed iterator by calling `GroupIter.names.reverse()` after populating the relevant list. Afterwards you could just iterate through the `GroupIter` instance as usual.

https://github.com/h5py/h5py/blob/8a22294e27be0678f755d66b288b2d97b258b633/h5py/h5g.pyx#L110-L132

**Comment by aragilar** [comment]
The dictionary-like interfaces in h5py are set by https://docs.python.org/3/library/collections.abc.html#collections.abc.MutableMapping. It appears that `__reversed__` isn't on that class (which is why it's not defined on `Group`). I've got no objection to support being added, but given the ordering is defined by the file, I'd personally be cautious about depending on it.

**Comment by takluyver** [comment]
I'm  on the fence about this. By default, groups are unordered (we iterate over them in name order, but that's not inherent to the group itself), and in this case I would generally prefer not having `__reversed__`. But you can enable tracking order when you create a group. And if we iterate in a predictable order even for unordered groups, I guess there's no actual *problem* with being able to reverse that order.

**Comment by BvB93** [comment]
> By default, groups are unordered (we iterate over them in name order, but that's not inherent to the group itself)

To me this does sound like there is always a well defined iteration order, whether this is based on insertion- or alphabetical ordering. Its deterministic nature should, at the very least, allow for a sensible `__reversed__` implementation.
