### ISSUE TITLE
Support HDF5 library page buffering

### ISSUE THREAD

**Issue by ajelenak** [h5py/h5py#1965]
h5py currently supports HDF5 [file space management](https://portal.hdfgroup.org/display/HDF5/File+Space+Management) but not [page buffering](https://portal.hdfgroup.org/display/HDF5/Page+Buffering). The latter has the potential to improve the overall performance with carefully tailored file space page size when creating a file and the appropriately sized page buffer when reading it.

I propose to add these HDF5 functions: `H5Pset_file_space_page_size`, `H5Pget_file_space_page_size`, `H5Pset_page_buffer_size`, and `H5Pget_page_buffer_size`. All of them are available since HDF5-1.10.1, the same as the file space management functions.

If this is acceptable, I will create a PR where we can discuss high-level implementation details.

**Comment by tacaswell** [comment]
Seems good to me!

Would this helped with #1960 ?

**Comment by ajelenak** [comment]
Not directly. Page buffer holds "raw" bytes, prior they are turned into HDF5 objects or their data. It could help avoid reading the data from the file again if such datasets are opened later.

**Comment by ajelenak** [comment]
I also want to add these two HDF5 functions: [H5Fget_page_buffering_stats](https://docs.hdfgroup.org/hdf5/v1_12/group___h5_f.html#title27) and [H5Freset_page_buffering_stats](https://docs.hdfgroup.org/hdf5/v1_12/group___h5_f.html#title35).

**Comment by takluyver** [comment]
Closed by #1967
