### ISSUE TITLE
Issue parsing h5 file

### ISSUE THREAD

**Issue by drubinstein** [h5py/h5py#1968]
To assist reproducing bugs, please include the following:
 * MacOS
- h5py    3.4.0
- HDF5    1.12.1
- Python  3.7.4 (default, Oct  8 2019, 14:43:54)
- [Clang 10.0.1 (clang-1001.0.46.4)]
- sys.platform    darwin
- sys.maxsize     9223372036854775807
- numpy   1.19.4
- cython (built with) 0.29.24
- numpy (built against) 1.14.5
- HDF5 (built against) 1.12.1

Also tested h5py 2.10.

There seems to be something wrong with how h5py access grouped data, though I can't pin it down. The attached file, [P_547131_key.h5.zip](https://github.com/h5py/h5py/files/7230541/P_547131_key.h5.zip) seems to load fine with the [deepdish](https://pypi.org/project/deepdish/) library giving an output of
```
{'key_extractor': {'key': 'C', 'scale': 'major', 'strength': 0.9512807726860046}, 'label': 'W_163992', 'track_id': 'P_547131'}
```

However, h5py returns:
```
KeysViewHDF5 ['key_extractor']>
<HDF5 group "/key_extractor" (0 members)>
```
Note it seems to also be missing the label and track_id keys. 

A script to run that more or less demonstrates the issue:
```python
import ipdb
import h5py
import deepdish as dd

file = "P_547131_key.h5"

with open(file, "rb") as fhandle:
    # old way
    data = dd.io.load(fhandle.name)
    print(data)
    print("")

    # new way
    ipdb.set_trace()
    with h5py.File(fhandle, "r") as open_file:
        print(open_file)
        print(open_file.keys())
        group = open_file["key_extractor"]
        print(group)
        print(dir(group))
        print(group.ref)
        print(group.regionref)

        print(list(group.items()))
        print(list(group.keys()))
        print(list(group.values()))
        print(group.get("key"))
        print(group)
        print(open_file["label"])
```
Any help in figuring out the right commands to get this file to parse correctly would be amazing. Thanks in advance.

**Comment by aragilar** [comment]
@drubinstein There appear to be no actual datasets in the file: there's some attributes on the top-level root (which mainly seem to be metadata about what version of pytables and deepdish wrote the file), and then more attributes on the `"key_extractor"` group. To see those attributes in your code, use `open_file.attrs` (for the root) or `group.attrs` (for `"key_extractor"`). The [docs on attrs}(https://docs.h5py.org/en/stable/high/attr.html) should give further information about how to use them.

**Comment by drubinstein** [comment]
Thanks for the quick response @aragilar. I see them there.
