### ISSUE TITLE
API suggestions

### ISSUE THREAD

**Issue by tdegeus** [h5py/h5py#1974]
I am really satisfied with h5py. However, I have a number of complementary functions that I find useful to have, and I wonder if it would be interesting to merge these in the h5py API:

## visit

There are a couple of functionalities that I miss from visit:
* Visit datasets only (I know it is possible with a (lambda) function, but it might be a nice standard function).
* Visit only items containing data (datasets or groups with attributes).
* Visit the entire file but one or a few branches (suppose that they contain many datasets the efficiency of not visiting those branches can be significant). 

## path

It would be nice to have `h5py.path` with some `os.path`-like functions like `join` but with platform independent `"/"`.

## compare

Function to compare the (approximate) equality of two datasets (from two files) including their attributes. Currently one has to have a `for` on the attributes and one needs an `if` to distinguish string data.

**Comment by tdegeus** [comment]
> For the path-related logic, `posixpath` would cover what you want (see the second note on https://docs.python.org/3/library/os.path.html for more detail about it).

Indeed. Thanks!

**Comment by takluyver** [comment]
I'm going to close this one.

- Nicer recursion options can be discussed in #1384. I'm still toying with the idea of making something like this.
- As @aragilar pointed out, `posixpath` works for manipulating HDF5-style paths. They're also fairly tolerant of things like double slashes, in my experience, so it's often practical enough to just glue strings together.
- 'Approximate equality' for a complicated data structure is a can of worms I'd rather leave closed. As @tacaswell said, two different people are likely to have very different expectations for that. It's best to write out your checks explicitly.
