### ISSUE TITLE
Memory leak when reading from an hdf5 dataset

### ISSUE THREAD

**Issue by danielgafni** [h5py/h5py#1975]
OS
---------------------------------
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"

Summary of the h5py configuration
---------------------------------

h5py    3.4.0
HDF5    1.12.1
Python  3.8.9 (default, Oct 11 2021, 09:08:45) 
[GCC 9.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.21.2
cython (built with) 0.29.24
numpy (built against) 1.17.5
HDF5 (built against) 1.12.1

Code to reproduce the issue (memory is leaking, please track the currently used RAM):

```python
import h5py 
import numpy as np 
 
with h5py.File("leak.h5py", "w") as f: 
    f["dataset"] = np.random.rand(1000, 1000) 

with h5py.File("leak.h5py", "r") as f: 
    while True: 
        f["dataset"][0]

```

Am I doing something wrong? Perhaps, reading the data?

Will appreciate any help!

**Comment by tacaswell** [comment]
I was about to report I could not reproduce this, got distracted writing a reply by a phone call....and then I OOM'd my machine during the call when the test script exhausted my memory.

This seems to be a regression from 3.3 to 3.4.

**Comment by takluyver** [comment]
Thanks @aragilar ! Yes, today I can reproduce it with @FeryET's example as well. Perhaps I got myself in a muddle switching between different versions yesterday. :confused: 

It looks like even `dataset.id.close()` is enough to release the memory used again, which would fit with it being some problem with the chunk cache.
