### ISSUE TITLE
failing tests for MPI builds: correct behavior?

### ISSUE THREAD

**Issue by MarDiehl** [h5py/h5py#1997]
I've created a pull request to update the conda feedstock to h5py 3.5.0 (https://github.com/conda-forge/h5py-feedstock/pull/105). Currently, 3 tests from `test_file.py` are failing which have been marked with ` pytest.mark.mpi_skip` because they are not invoked correctly, i.e. with `mpirun -n 2 python -m pytest --with-mpi`. That error can be fixed in the feedstock recipe.

However, I wanted to confirm whether it is correct that these tests fail already because h5py uses an HDF5 version that was _build_ with MPI support. Unless `MPI_init` is called, a library that was compiled with a MPI support will behave like a serial library. That means, is it correct that `OSError: Unable to create file (page buffering is disabled for parallel)` is raised solely based on the build configuration or should it rather be a run time decision?

 * Operating System: Ubuntu 20.04.3
 * Python version: 3.7-3.9
 * Where Python was acquired: Creating the h5py conda package
 * h5py version: 3.5.0
 * HDF5 version: 1.12.1

**Comment by aragilar** [comment]
Sorry, are you marking additional tests with `pytest.mark.mpi_skip`? The tests currently marked with `pytest.mark.mpi_skip` were last time I looked were those which spawned additional subprocesses, which breaks under MPI.

**Comment by MarDiehl** [comment]
I'm just running `h5py.run_tests()` as part of the conda recipe. Some of the tests in https://github.com/h5py/h5py/blob/master/h5py/tests/test_file.py will fail if an MPI-enabled HDF5 library is used. This happens because `pytest.mark.mpi_skip` is only active if pytest is started with `mpirun -n 2 python -m pytest --with-mpi`. This is clearly a problem with the recipe that we can solve, nothing that concerns h5py directly.

My question is only about hdf5's behavior that requires to mark the tests with `pytest.mark.mpi_skip`: I understand that page buffering does not work in MPI-parallel situations. However, one can also use a HDF5 library with MPI support for sequential runs. Currently, in that case h5py will throw an OSError. To summarize the different behaviors:

* `python -m pytest --with-mpi` with MPI-aware HDF5: `pytest.mark.mpi_skip` is not set, tests fail. **Question**: is it correct that hdf5 raises an error based on the build time decision to use an HDF5+MPI or could page buffering be enabled based on a runtime check (no mpiexec/mpirun) such that the tests pass?
* `mpirun -n 2 python -m pytest --with-mpi` with MPI-aware HDF5: `pytest.mark.mpi_skip` is set, tests pass. All fine.
* `python -m pytest --with-mpi`: HDF5 without MPI: all tests pass, all fine.
*  `mpirun -n 2 python -m pytest --with-mpi`: HDF5 without MPI: meaningless situation.

**Comment by aragilar** [comment]
I would expect 1 to fail (as you're trying to test MPI features without running MPI). I suspect 3 is catching that you've not got an MPI build, so skipping MPI tests (but I'd need to check the logs). I'd expect 4 to be the opposite of 1, where you're skipping the tests that do not work under MPI, but not testing MPI features.

**Comment by MarDiehl** [comment]
> I would expect 1 to fail (as you're trying to test MPI features without running MPI). I suspect 3 is catching that you've not got an MPI build, so skipping MPI tests (but I'd need to check the logs). I'd expect 4 to be the opposite of 1, where you're skipping the tests that do not work under MPI, but not testing MPI features.

sorry, there was a copy and paste error in my explanation. Of course `--with-mpi` does not make sense without `mpiexec`. I meant:

* `python -m pytest` with MPI-aware HDF5: `pytest.mark.mpi_skip` is not set, tests fail. I assume that this is equivalent to `h5py.run_tests()`. __Question__: is it correct that hdf5 raises an error based on the build time decision to use an HDF5+MPI or could page buffering be enabled based on a runtime check (no mpiexec/mpirun) such that the tests pass?
* `mpirun -n 2 python -m pytest --with-mpi`: with MPI-aware HDF5: `pytest.mark.mpi_skip` is set, tests pass. All fine.
* `python -m pytest`: HDF5 without MPI: all tests pass, all fine.
* `mpirun -n 2 python -m pytest --with-mpi`: HDF5 without MPI: meaningless situation.

**Comment by ajelenak** [comment]
@MarDiehl The `OSError` you refer to comes from the HDF5 library.

**Comment by MarDiehl** [comment]
> @MarDiehl The `OSError` you refer to comes from the HDF5 library.

thanks for the clarification! Can someone close the issue?
