### ISSUE TITLE
Sequential calls to `read(n)` is slow over a high latency high bandwidth network connection for file-like objects

### ISSUE THREAD

**Issue by davidparks21** [h5py/h5py#2001]
```
Summary of the h5py configuration
---------------------------------

h5py    3.5.0
HDF5    1.12.1
Python  3.8.10 (default, Jun  4 2021, 15:09:15) 
[GCC 7.5.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.20.2
cython (built with) 0.29.24
numpy (built against) 1.17.5
HDF5 (built against) 1.12.1
```

Scenario: Read hdf5 files via file-like objects in Python which encapsulate a network based file, such as a file hosted on S3. Specifically using a performant streaming library such as `smart_open` for file access.

When accessing a python file-like object HDF5 translates a slice operation to about a half dozen small header read calls followed by one read per each `user-block-size` chunk. These read calls all happen in series. With a high latency network connected file, running many `read(n)` calls in series is inefficient. Also challenging is the fact that there is no optimal user block size for all use cases, for example a good user block size for column slices of a matrix is a poor choice for row slices of that same matrix. 

Two solutions seem reasonable:
 1) Offer users the option to parallelize calls to `read(n)` during the multiple reads per each block.
 2) Merge contiguous reads into a single `read(n)` call (allowing performant streaming libraries to parallelize the underlying requests).

I want to post this to the community and get thoughts on how realistic these two proposals seem, or if there are other feedback on improving the issue of slowness over high latency high bandwidth file-like objects.

If neither of those options are possible, the next best solution seems to be an independent predictive read-ahead wrapper of the file-like object. While most generic, it's also the least precise solution.

**Comment by aragilar** [comment]
I'm not a fan of adding more complexity to the `fileobj` driver, given it's effectively 3 layers of code (the underlying file-like object code, which is likely quite abstract compared to whatever protocol is being used, the python file to HDF5 wrapper, and the HDF5 IO system). I think looking at tools like HSDS (https://www.hdfgroup.org/solutions/highly-scalable-data-service-hsds/) or VOL or new connectors (https://forum.hdfgroup.org/c/hdf5-connectors) is going to be more effective, as then the HDF5 IO system can be aligned to whichever protocol you're using.

There is support for read-only S3 (if that covers what you need) in HDF5 (which we expose in h5py), if that covers your use-case, and if there are more HDF5 features we should expose, please file issues for them.

**Comment by davidparks21** [comment]
I was not aware of the read-only S3 support. I'm going to test that out asap. Read-only S3 is our primary use case, as I suspect it will be with many others who use S3. We house our large data files on a remote distributed S3 interface.

**Comment by tacaswell** [comment]
I'm going to close this with no action.  I agree with @aragilar that adding more complexity to the `fileobj` driver is a very high-risk activity and there are better solutions (both existing with the S3 driver and coming with VOL) for this use case that solve the problem at the libhdf layer.

**Comment by betolink** [comment]
@tacaswell Do you know if the S3 read-only mode supports concurrent reads to bypass the issue described here?

**Comment by ajelenak** [comment]
No, it does not. But there are some ways to improve. Contact me (ajelenak AT hdfgroup DOT org), or watch this YouTube [video](https://www.youtube.com/watch?v=rcS5vt-mKok&list=PLPyhR4PdEeGY45ue2qs61Xjg6eWElGX8F&index=92) which explains some options.
