### ISSUE TITLE
Understand error message 

### ISSUE THREAD

**Issue by PythonSchlumpf** [h5py/h5py#2006]
Dear all,
I hope I can find here some help. I have some hdf5 files. I open them once to check their content quickly. I open them with a context manager. After knowing what is inside, I open the files again, but this time with xarrays `xr.open_mfdataset` and a context manager to extract the data. When I re-run my Jupyter notebook a second time, I get the following error.  But the error message appears when the hdf5 is opened again. If I exclude the xarray-section, it runs through without a problem. I don't know how to solve this problem alone. 
My function `eiger_sanity_check()` works, it only open the hdf5 files to check the content of all files. `import_all_eiger_frames` calls as well `eiger_sanity_check()`, but in addition as well `xr.open_mfdataset`. Somehow this combination does not work. 
Thank you for helping me to understand the error message.

To assist reproducing bugs, please include the following:
 * Operating System:CentOS 7 
 * Python version: 3.9.7
 * Where Python was acquired: Anaconda
 * h5py version: 3.6
 * HDF5 version 1.10.6
 * The full traceback/stack trace shown (if it appears)

```py
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/tmp/ipykernel_34891/2417205999.py in <module>
     15 # create object for scan xxx
     16 scans=FileReaderP06(scan_number, path_in, path_out)
---> 17 scans.eiger_sanity_check() #this alone works, no matter how many times I execute the notebook
     18 all_data, xrds = scans.import_all_eiger_frames(group_path='/entry/data/') #this does not work after the second time anymore
     19 

/tmp/ipykernel_34891/1835829242.py in eiger_sanity_check(self)
     99 
    100             print('Checking current file: ', file_path)
--> 101             with h5py.File(file_path ,'r') as h5f:
    102 
    103 

~/.conda/envs/pyfai-0.20/lib/python3.9/site-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, fs_strategy, fs_persist, fs_threshold, fs_page_size, page_buf_size, min_meta_keep, min_raw_keep, locking, **kwds)
    505                                  fs_persist=fs_persist, fs_threshold=fs_threshold,
    506                                  fs_page_size=fs_page_size)
--> 507                 fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
    508 
    509             if isinstance(libver, tuple):

~/.conda/envs/pyfai-0.20/lib/python3.9/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    218         if swmr and swmr_support:
    219             flags |= h5f.ACC_SWMR_READ
--> 220         fid = h5f.open(name, flags, fapl=fapl)
    221     elif mode == 'r+':
    222         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (file close degree doesn't match)
```

**Comment by aragilar** [comment]
I'm not sure what `file close degree doesn't match` means, but it's coming from the underlying HDF5 library, you could ask on https://forum.hdfgroup.org/ and see if anyone can give you some advice.

**Comment by ajelenak** [comment]
@PythonSchlumpf  I think your problem is described in the #218 issue. Very likely that xarray's backend storage engine based on the netCDF library is using a different file close degree setting than h5py. You should make sure only one of h5py or xarray have the same HDF5 file at same time.

**Comment by PythonSchlumpf** [comment]
@ajelenak Thank you for your suggestion.

> You should make sure only one of h5py or xarray have the same HDF5 file at same time.

I am really sorry. That is what I don't understand, when I am using a) a context manager and b) code is executed linear. Dummy code as example. It only shows a simplified structure. 

```py
def check_files(file_list):
    for iscan, basename in enumerate(file_list):
        with h5py.File(basename ,'r') as h5f:
            try:
                sub_group='/entry/data/data'
                if sub_group in h5f:
                    print('Path in hdf5 file exists')
                data_shape=np.array(h5f[sub_group][()].shape)
            
            except KeyError as e:
                print(iscan, e)
                data_shape=(-1)*np.ones([1,3],dtype=int)
return file_list 
 
def new_function(file_list): 
    file_list_checked=check_files(file_list) 
    with xr.open_mfdataset(file_list_checked, combine='nested', concat_dim='phony_dim_0', group=group_path) as xrds:
        ds=xrds

```
When I call `new_function` a second time, the error appears in the function `check_files` while reading the hdf5 files. I thought a context manager closes always the files after usage.

**Comment by takluyver** [comment]
If you only get an error the second time you call that, that suggests that Xarray is not closing the files the first time round.

Does the same error happen with just your simplified example above, or only with the real code?

**Comment by PythonSchlumpf** [comment]
Good morning. @takluyver Yes, I came to the same conclusion. You are right, I did not get the same error with dummy code. That was really odd. I did not know how to check how to close the hdf5 files, because I used a context manager.

But yesterday, I was able to ask somebody in the xarray group and now it works.
I extended the `xr.open_mfdataset` command. It is now `xr.open_mfdataset(file_list_full_path, combine='nested', engine="h5netcdf",phony_dims='sort', concat_dim='phony_dim_0', group=group_path)`. I had to include
`engine='h5netcdf',phony_dims='sort' ` .
I understood that `engine='h5netcdf'` circumvents this problem with not closing the hdf5 files. `phony_dims="sort"` for getting dimensions xarray needs, but pure hdf5 files do not have.

**Comment by takluyver** [comment]
OK, thanks for recording that information. I'll close this issue since I don't think there's anything to fix in h5py.

I agree the error message is not very helpful in this case. But it's one of many possible error messages we pass on from HDF5, and I don't think h5py should try to guess what different error messages from HDF5 might mean.

**Comment by ajelenak** [comment]
H5netcdf package uses h5py and that ensures xarray opens all HDF5 files with the same file close degree setting. H5py uses the _strong_ file close degree:
https://github.com/h5py/h5py/blob/f4219bba033c46224976861cbdf9670349b69de8/h5py/_hl/base.py#L129-L135

Without explicitly stating `engine="h5netcdf"`, xarray will rely on its default engine based on the netCDF-C library. I quickly searched its code and found evidence that it uses the _weak_ file close degree:

https://github.com/Unidata/netcdf-c/blob/fcf0fa7dbd13c56c8a34282e673151640e079198/libhdf5/hdf5open.c#L767-L775

https://github.com/Unidata/netcdf-c/blob/4086bbd8877618384948d9bb6fbf15faf8b90867/libhdf5/hdf5create.c#L120-L127

The warning note for the [H5Pset_fclose_degree()](https://docs.hdfgroup.org/hdf5/v1_12/group___f_a_p_l.html#ga60e3567f677fd3ade75b909b636d7b9c) function provides the explanation for the reported h5py exception:

>If a file is opened multiple times without being closed, each open operation must use the same file close degree setting. For example, if a file is already open with H5F_CLOSE_WEAK, an H5Fopen() call with H5F_CLOSE_STRONG will fail.

**Comment by PythonSchlumpf** [comment]
@ajelenak Thank you very much for the explanation and your research. I am happy, we know now the solution.
