### ISSUE TITLE
Mac ARM Chip Support?

### ISSUE THREAD

**Issue by KTRosenberg** [h5py/h5py#2008]
I am trying to install via pip on macOS 11, on an M1 (ARM) chip. It looks like there's no built-in wheel yet. What might be the timeline for making this available? Otherwise, please advise on how to replace this manually.

Can I use home-brew to install hdf5? Then, how would I specify the path to this so installation would work?

**Comment by aragilar** [comment]
See https://docs.h5py.org/en/stable/build.html#source-installation. I think homebrew has HDF5, but I'm not sure.

**Comment by KTRosenberg** [comment]
I see.
What is pkg-config referencing though? Is it another libeary to install via pip?

In any case, will an ARM mac version become available on pip at some point in the near future? Building from source complicates things for potential users of my project.

**Comment by takluyver** [comment]
Homebrew does have HDF5 - some of our CI jobs install HDF5 using it:

https://github.com/h5py/h5py/blob/050c8fc923777b8f73d1b9addaba9804e84afa1b/ci/azure-pipelines-steps.yml#L43-L47

> What is pkg-config referencing though? Is it another libeary to install via pip, or is it the unix command line tool that I can install via homebrew?

The command line tool. There's a Python wrapper which is also used, but that should be installed automatically if you use pip to do a source installation.

> In any case, will an ARM mac version become available on pip at some point in the near future?

That's mostly up to the Mac users. :wink: If someone can configure the CI to build them, and show that it doesn't make the whole thing too much slower (or less reliable) than it already is, I think we'd be happy to merge it. But as far as I know, none of the main maintainers are Mac users.

**Comment by truedichotomy** [comment]
How to configure CI to build for the M1 Macs?

**Comment by tacaswell** [comment]
I think that you could copy the cibuildwheel setup that Matplotlib uses (we the wheel building on GHA over there) or sort out how to configure azure pipelines to build m1 compatible wheels.

**Comment by Amar1729** [comment]
A related issue on using homebrew for hdf5 - #1800

**Comment by janhartman** [comment]
@takluyver Hey! I really appreciate work on this issue. In the meantime, is it possible to build a `.whl` file on an M1 machine that bundles HDF5 and thus avoids all the workarounds?
I tried cloning the repo and running `./dev-install.sh` and what I get is:
```Building wheels for collected packages: h5py
  Building wheel for h5py (pyproject.toml) ... done
  Created wheel for h5py: filename=h5py-3.6.0-cp38-cp38-macosx_12_0_arm64.whl size=1236811 sha256=2b4f5d4024aea747369d8b399d7ea59ea192f378f20a3f05619a1ec8a1106804
  Stored in directory: /private/var/folders/yc/y4qzjvm54kz4m043l5_4h89r0000gn/T/pip-ephem-wheel-cache-7tfhbhnj/wheels/26/0c/9e/33a0c73bbd7db5404035f047b706eb24814bc29afcbd663c42
 ```

However, if I try to copy the wheel somewhere else after this, the directory is already gone. Would really appreciate any help with this,  I apologize if this is a noob question.

**Comment by takluyver** [comment]
If it builds and installs OK, then probably all you need is to `pip wheel .` to make a wheel of it.

When pip builds something from PyPI to install, it caches the wheel to reuse later. But if you install something from a local folder, you don't really have reliable version numbers (it's easy to make changes without changing the version), so it discards the wheel. `-ephem-` in the folder name means 'ephemeral'.
