### ISSUE TITLE
Building fails seemingly due to cythonization of the h5i.pyx file

### ISSUE THREAD

**Issue by zerothi** [h5py/h5py#2009]
I am trying to build h5py, this fail occurs for 3.5.0 and 3.6.0.

Python: 3.9.7
Cython: 0.29.24
hdf5: 1.12.1 (serial)
OS: Debian (latest)

```

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  GROUP       = H5I_GROUP
  DATASPACE   = H5I_DATASPACE
  DATASET     = H5I_DATASET
  ATTR        = H5I_ATTR
  IF HDF5_VERSION < VOL_MIN_HDF5_VERSION:
  GENPROP_CLS = H5I_GENPROP_CLS
  ^
  ------------------------------------------------------------

  h5py/h5i.pyx:28:0: Expected an increase in indentation level
  Loading library to get build settings and version: /opt/gnu/11.2.0/hdf5-serial/1.12.1/lib/libhdf5.so
  ********************************************************************************
                         Summary of the h5py configuration

  HDF5 include dirs: [
    '/opt/gnu/11.2.0/hdf5-serial/1.12.1/include'
  ]
  HDF5 library dirs: [
    '/opt/gnu/11.2.0/hdf5-serial/1.12.1/lib'
  ]
       HDF5 Version: (1, 12, 1)
        MPI Enabled: False
   ROS3 VFD Enabled: False
   Rebuild Required: True

  ********************************************************************************
```

This is weird since the file contains a correctly formatted indentation, but seemingly it gets re-created/changed when cythonization step occurs?

I issue the build as this:

```shell
CFLAGS='-m64 -fPIC -O3 -ftree-vectorize -fexpensive-optimizations -funroll-loops -fprefetch-loop-arrays -march=native -DH5_USE_110_API' HDF5_DIR=/opt/gnu/11.2.0/hdf5-serial/1.12.1 /opt/gnu/11.2.0/python/3.9.7/bin/python3 -s -m pip -vv install --no-build-isolation . --prefix=/opt/gnu/11.2.0/python/packages/3.9.7/h5py/3.6.0
```
The no-build-isolation is to ensure it is compatible with the rest of the stack and to not download the required packages at build-time.

What may be the reason for this?

I

**Comment by tacaswell** [comment]
one odd thing is that block uses 2 space indent but the rest of the file uses 4 space but that should not matter....

I can not reproduce this error and I'm pretty sure that we do not re-generate this file as part of the build process (I removed it and install failed, the files we auto-generate are `config.pxi` and `defs.*`).  

Are you applying any patching is part of the build process?  Where did you get the source from?

Can you try manually cythonizing the file before trying to install (that will at least sort out if it is really a cython issue or something we are doing in the install process).

**Comment by zerothi** [comment]
Sorry for the blurp, it was a user-defined function that had done stupid things to the pyx files... Sorry and thanks for the hint!
