### ISSUE TITLE
Allow creation of datasets with chunk size greater than the initial dataset size.

### ISSUE THREAD

**Issue by bryan-lunt** [h5py/h5py#2012]
https://github.com/h5py/h5py/blob/c62b34c1841afc05c4c7252317bba40f05f65e26/h5py/_hl/dataset.py#L72-L77

**Comment by ajelenak** [comment]
That is not supported by the HDF5 library. See the note in the [`H5Pset_chunk()`](https://docs.hdfgroup.org/hdf5/v1_12/group___d_c_p_l.html#ga3584d592e377da3604b7604e266dcf5b) function's documentation. The h5py code you cited correctly performs the size check only for fixed-size dimensions of an HDF5 dataset.

Can you explain what you are trying to achieve and maybe there is another way?

**Comment by takluyver** [comment]
If you want to have a resizeable dimension, specify the maxshape parameter, and then it should be OK with a chunk size larger than your initial size:

```python
# Resizeable up to a maximum:
f.create_dataset('a', shape=(0, 10), maxshape=(1000, 10), chunks=(50, 10))

# Unlimited dimension:
f.create_dataset('a', shape=(0, 10), maxshape=(None, 10), chunks=(50, 10))
```

Otherwise, you could trim the chunk shape down like `tuple([min(chk, dim) for (chk, dim) in zip(chunks, shape)])` to ensure it fits in the data shape.

**Comment by takluyver** [comment]
I'm going to close this one, as it's a restriction in HDF5 itself. h5py *could* modify the chunk size you pass to make it work, but that's getting towards guessing what the user wants. I think it's better to raise an error for incompatible parameters, rather than trying to adjust one parameter.
