### ISSUE TITLE
Exact shape matching hinders `require_dataset` usecase

### ISSUE THREAD

**Issue by Helveg** [h5py/h5py#2018]
What exactly is the usecase of `require_dataset` if one must go check the exact size of it to prevent these errors:

```
TypeError: Shapes do not match (existing (1, 3) vs new (0, 3))
```

In order to be able to satisfy that constraint you have to go check the existence of the dataset and retrieve its shape, what purpose could a call to `require_dataset` even serve after you've already checked existence?

I'd expect to be able to use `require_dataset` to retrieve or create similar to `require_group`:

```
ds = grp.require_dataset("name", some=args, that=only, matter=for_create)
safely_use(ds)
```

**Comment by tacaswell** [comment]
Groups and datasets are different in some critical ways.  Notable, groups have no addition structure to them, they are always just nodes in a tree that carry some attributes and a name.  On the other hand, datasets have a shape, dtype, chunking, extension rules, and compression settings.  However, looking at `create_dataset` you either need to tell us the shape and dtype _or_ provide data (which we then infer those from).  There is no way (to my knowledge) to create a dataset at the hdf5 level without giving an initial shape and dtype!  That is, the minimal tuple of information that describes a dataset is (name, shape, dtype).

In this case we are only checking that the shape matches by default (I am on the record for making `require_dataset` _stricter_ https://github.com/h5py/h5py/pull/897 ).  

Can you say a bit more about what you use case is where you do not care about the shape or type and only care about the name?

**Comment by takluyver** [comment]
I suspect `require_dataset` was written before datasets could be resized (or maybe resizing was possible but new - I wasn't there at the time). Without resizing, the shape is a fundamental property of the dataset, so it makes sense for `require_dataset` to validate that an existing dataset is the shape you expect. Datasets are still not resizable by default (with the default options in h5py).

With a resizable dataset, it makes sense to start with a length 0 dimension and grow it as you add data - I assume this is what you're doing?

Maybe if both `shape` and `maxshape` are passed, we should only validate maxshape? I think you have to specify maxshape to allow a dataset to grow. This would technically be an API change - the docs say that shape will be checked - but it might be one that doesn't bother too many people.

**Comment by Helveg** [comment]
Actually, the arguments to pass make sense, you need to know these things in order to create them, but then the second time around when the dataset already exist it errors out saying that the shape I'm giving (0, 3) doesn't match the data there is in there (1, 3) and errors out. This makes `require_dataset` unusable with resizable datasets where I'd like to pass by as much as I want to append data.

**Comment by takluyver** [comment]
I think your last suggestion - ignore shape checking on a resizable axis - is equivalent to my idea to validate maxshape instead of shape if that's passed. I assume your `require_dataset` call includes a `maxshape=` parameter with None (for unlimited) in at least one axis?

**Comment by Helveg** [comment]
Yep :)

**Comment by tacaswell** [comment]
🐑 I forgot about dataset resizing (most of my day-to-day hdf5 work is write-once/read-only these days and we typically know the data shape up front 🤦🏻 ) .

I have given up on #897 and if we are going to have `require_dataset` around we should make it work for this use case.

**Comment by takluyver** [comment]
@Helveg do you want to make a PR for the idea we both suggested? Is it clear how to implement that?

**Comment by Helveg** [comment]
Should be :) I'll take a look.

**Comment by takluyver** [comment]
Sorry, didn't notice your question until now.

> I'm just wondering about cases where it's resizable but the maxshape isn't None? Should require_dataset error if existing_dataset.shape > given maxshape?

I would say that if maxshape is passed, check that `maxshape == dset.maxshape`. The shape can't be greater than maxshape, and AFAIK maxshape can't be changed after creation, so for a resizeable dataset that's the fundamental, fixed property that we care about.

If maxshape isn't passed, then we can fall back to the existing check that `shape == dset.shape`. Even if the existing dataset is resizeable, not specifying `maxshape` suggests that the calling code doesn't require it to be resizeable, and thus won't try to resize it, so it should be the expected shape already.
