### ISSUE TITLE
Install issue while building h5py (pyproject.toml)

### ISSUE THREAD

**Issue by insung3511** [h5py/h5py#2035]
* Hardware : Apple M1
* O.S. : macOS Monterey (Version 12.0.1)
* Python Version : 3.9.5 (System Python, not a conda or virtual Environment)

Hi, I was install h5py command by 
`
pip3 install h5py
`
But I got error like this.
<pre>
$ pip3 install h5py                                 
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting h5py
  Using cached h5py-3.6.0.tar.gz (384 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.14.5 in /opt/homebrew/lib/python3.9/site-packages (from h5py) (1.22.0)
Building wheels for collected packages: h5py
  Building wheel for h5py (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/homebrew/opt/python@3.9/bin/python3.9 /opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/tmppozhj8tz
       cwd: /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae
  Complete output (123 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-12-arm64-3.9
  creating build/lib.macosx-12-arm64-3.9/h5py
  copying h5py/h5py_warnings.py -> build/lib.macosx-12-arm64-3.9/h5py
  copying h5py/version.py -> build/lib.macosx-12-arm64-3.9/h5py
  copying h5py/__init__.py -> build/lib.macosx-12-arm64-3.9/h5py
  copying h5py/ipy_completer.py -> build/lib.macosx-12-arm64-3.9/h5py
  creating build/lib.macosx-12-arm64-3.9/h5py/_hl
  copying h5py/_hl/files.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
  copying h5py/_hl/compat.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
  copying h5py/_hl/__init__.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
  copying h5py/_hl/selections.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
  copying h5py/_hl/dataset.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
  copying h5py/_hl/vds.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
  copying h5py/_hl/selections2.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
  copying h5py/_hl/group.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
  copying h5py/_hl/datatype.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
  copying h5py/_hl/attrs.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
  copying h5py/_hl/dims.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
  copying h5py/_hl/base.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
  copying h5py/_hl/filters.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
  creating build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_dimension_scales.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_attribute_create.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_file_image.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/conftest.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_h5d_direct_chunk.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_h5f.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_dataset_getitem.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_group.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_errors.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_dataset_swmr.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_slicing.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_h5pl.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_attrs.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/__init__.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_attrs_data.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_h5t.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_big_endian_file.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_h5p.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_dims_dimensionproxy.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_h5o.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_datatype.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/common.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_dataset.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_file.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_selections.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_dtype.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_h5.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_file2.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_completions.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_filters.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_base.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  copying h5py/tests/test_objects.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
  creating build/lib.macosx-12-arm64-3.9/h5py/tests/data_files
  copying h5py/tests/data_files/__init__.py -> build/lib.macosx-12-arm64-3.9/h5py/tests/data_files
  creating build/lib.macosx-12-arm64-3.9/h5py/tests/test_vds
  copying h5py/tests/test_vds/test_highlevel_vds.py -> build/lib.macosx-12-arm64-3.9/h5py/tests/test_vds
  copying h5py/tests/test_vds/test_virtual_source.py -> build/lib.macosx-12-arm64-3.9/h5py/tests/test_vds
  copying h5py/tests/test_vds/__init__.py -> build/lib.macosx-12-arm64-3.9/h5py/tests/test_vds
  copying h5py/tests/test_vds/test_lowlevel_vds.py -> build/lib.macosx-12-arm64-3.9/h5py/tests/test_vds
  copying h5py/tests/data_files/vlen_string_s390x.h5 -> build/lib.macosx-12-arm64-3.9/h5py/tests/data_files
  copying h5py/tests/data_files/vlen_string_dset_utc.h5 -> build/lib.macosx-12-arm64-3.9/h5py/tests/data_files
  copying h5py/tests/data_files/vlen_string_dset.h5 -> build/lib.macosx-12-arm64-3.9/h5py/tests/data_files
  running build_ext
  Loading library to get build settings and version: libhdf5.dylib
  ********************************************************************************
                         Summary of the h5py configuration

  HDF5 include dirs: []
  HDF5 library dirs: []
       HDF5 Version: (1, 12, 1)
        MPI Enabled: False
   ROS3 VFD Enabled: False
   Rebuild Required: True

  ********************************************************************************
  Executing api_gen rebuild of defs
  Executing cythonize()
  [ 1/24] Cythonizing /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/_conv.pyx
  [ 2/24] Cythonizing /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/_errors.pyx
  [ 3/24] Cythonizing /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/_objects.pyx
  [ 4/24] Cythonizing /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/_proxy.pyx
  [ 5/24] Cythonizing /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/_selector.pyx
  [ 6/24] Cythonizing /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/defs.pyx
  [ 7/24] Cythonizing /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/h5.pyx
  [ 8/24] Cythonizing /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/h5a.pyx
  [ 9/24] Cythonizing /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/h5ac.pyx
  [10/24] Cythonizing /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/h5d.pyx
  [11/24] Cythonizing /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/h5ds.pyx
  [12/24] Cythonizing /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/h5f.pyx
  [13/24] Cythonizing /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/h5fd.pyx
  [14/24] Cythonizing /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/h5g.pyx
  [15/24] Cythonizing /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/h5i.pyx
  [16/24] Cythonizing /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/h5l.pyx
  [17/24] Cythonizing /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/h5o.pyx
  [18/24] Cythonizing /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/h5p.pyx
  [19/24] Cythonizing /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/h5pl.pyx
  [20/24] Cythonizing /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/h5r.pyx
  [21/24] Cythonizing /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/h5s.pyx
  [22/24] Cythonizing /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/h5t.pyx
  [23/24] Cythonizing /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/h5z.pyx
  [24/24] Cythonizing /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/utils.pyx
  creating build/temp.macosx-12-arm64-3.9
  creating build/temp.macosx-12-arm64-3.9/private
  creating build/temp.macosx-12-arm64-3.9/private/var
  creating build/temp.macosx-12-arm64-3.9/private/var/folders
  creating build/temp.macosx-12-arm64-3.9/private/var/folders/01
  creating build/temp.macosx-12-arm64-3.9/private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn
  creating build/temp.macosx-12-arm64-3.9/private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T
  creating build/temp.macosx-12-arm64-3.9/private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c
  creating build/temp.macosx-12-arm64-3.9/private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae
  creating build/temp.macosx-12-arm64-3.9/private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -DH5_USE_18_API -DNPY_NO_DEPRECATED_API=0 -I./h5py -I/private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/lzf -I/private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/lzf/lzf -I/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include -I/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/defs.c -o build/temp.macosx-12-arm64-3.9/private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/defs.o
  In file included from /private/var/folders/01/5f5ftlvn2w7c9prxbs4410780000gn/T/pip-install-kxj8kd1c/h5py_72dcad2fa1ef4e7b9d05c4c92c290dae/h5py/defs.c:734:
  ./h5py/api_compat.h:27:10: fatal error: 'hdf5.h' file not found
  #include "hdf5.h"
           ^~~~~~~~
  1 error generated.
  error: command '/usr/bin/clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for h5py
Failed to build h5py
ERROR: Could not build wheels for h5py, which is required to install pyproject.toml-based projects
</pre>
I don't know why dose happen so please help me. thank u 😄

**Comment by takluyver** [comment]
There's no pre-built package for ARM Macs yet (#2008), so pip is trying to [build h5py from source](https://docs.h5py.org/en/stable/build.html#source-installation), and failing to find HDF5. See also #1810, where there's a suggestion of how to make it work if you use Homebrew.

**Comment by insung3511** [comment]
> There's no pre-built package for ARM Macs yet (#2008), so pip is trying to [build h5py from source](https://docs.h5py.org/en/stable/build.html#source-installation), and failing to find HDF5. See also #1810, where there's a suggestion of how to make it work if you use Homebrew.

Thanks but still not work. I try <a href="https://docs.h5py.org/en/stable/build.html#custom-installation">this</a> one, unfortunately got same errors.

**Comment by ajelenak** [comment]
What was the exact command? Where is the HDF5 library installed on that computer?

**Comment by insung3511** [comment]
Not installed on my mac. just try to install

**Comment by insung3511** [comment]
I tried these command
<pre>
$ pip install --no-binary=h5py h5py
$ HDF5_DIR=/path/to/hdf5 pip install --no-binary=h5py h5py
$ HDF5_VERSION=X.Y.Z pip install --no-binary=h5py h5py
$ CC="mpicc" HDF5_MPI="ON" HDF5_DIR=/path/to/parallel-hdf5 pip install --no-binary=h5py h5py
</pre>
Just did all of that I can see

**Comment by ajelenak** [comment]
The last command, the "mpicc", is not applicable to your case.

If I understand correctly: (1) you installed HDF5 library on your Mac; (2) tried to install h5py using the "HDF5_DIR=..." pip command, and still got an error? What was the error?

**Comment by takluyver** [comment]
To be clear, you need HDF5 installed before you can build h5py from source. Where the docs have `/path/to/hdf5`, that's an example - you're supposed to replace that with the path to where HDF5 is installed. Where that is will depend on how you installed HDF5 - the example in #1810 is from someone who installed it using [Homebrew](https://brew.sh/).

**Comment by Amar1729** [comment]
By default, if using formula `hdf5` (replace this with `hdf5@1.8` if using an older version of hdf5) - 

On an m1 (arm) mac, arm homebrew's default path for hdf5 will be `export HDF5_DIR=/opt/homebrew/opt/hdf5`

On an x86 mac (or using x86 brew on an arm mac), the path will be `export HDF5_DIR=/usr/local/opt/hdf5`

https://github.com/h5py/h5py/issues/1800#issuecomment-1028201592

**Comment by hardikajmani1** [comment]
> By default, if using formula `hdf5` (replace this with `hdf5@1.8` if using an older version of hdf5) -
> 
> On an m1 (arm) mac, arm homebrew's default path for hdf5 will be `export HDF5_DIR=/opt/homebrew/opt/hdf5`
> 
> On an x86 mac (or using x86 brew on an arm mac), the path will be `export HDF5_DIR=/usr/local/opt/hdf5`
> 
> [#1800 (comment)](https://github.com/h5py/h5py/issues/1800#issuecomment-1028201592)

most forums had a different export path, this worked for me.
Thanks!

**Comment by ZeryeZ** [comment]
It works with this tutorial on my m1 machine try it yourself.
[](https://www.logcg.com/en/archives/3548.html)

**Comment by ngam** [comment]
my 2c here (also see #2052 and #2053): just do yourself a favor and build hdf5 from source with something like,

```
git clone git@github.com:HDFGroup/hdf5.git
cd hdf5
git checkout tags/hdf5-1_13_0
./configure --prefix=/usr/local 
make
make check # optional, but good to check
sudo make install
sudo make install-check  # optional but good to check
```

and then you can safely install h5py like this:
```
HDF5_DIR=/usr/local/ python3 -m pip install h5py
```

Otherwise, the conda build is pretty solid and resolves all of this efficiently.

> Python Version : 3.9.5 (System Python,..

This is not the "system" python --- macos comes with pyhon2 (soon to be removed) and python3 (3.8).

**Comment by venera111** [comment]
> It works with this tutorial on my m1 machine try it yourself. [Solution here](https://www.logcg.com/en/archives/3548.html)

Thank you! Everything works for me)

**Comment by tacaswell** [comment]
I am going to close this because #2065 is merged which will build wheels for the next release and this issue can currently be fixed by installing hdf5 and a compiler on the user's machine.

**Comment by PragmatistWu** [comment]
> It works with this tutorial on my m1 machine try it yourself. [Solution here](https://www.logcg.com/en/archives/3548.html)
Thanks for sharing! I got everything done!

**Comment by Awaiskhan404** [comment]
> By default, if using formula `hdf5` (replace this with `hdf5@1.8` if using an older version of hdf5) -
> 
> On an m1 (arm) mac, arm homebrew's default path for hdf5 will be `export HDF5_DIR=/opt/homebrew/opt/hdf5`
> 
> On an x86 mac (or using x86 brew on an arm mac), the path will be `export HDF5_DIR=/usr/local/opt/hdf5`
> 
> [#1800 (comment)](https://github.com/h5py/h5py/issues/1800#issuecomment-1028201592)

Great thank you so much.

**Comment by MuhammadShifa** [comment]
This work for me:
Here is the final solution of installing h5py successfully in python 3.6 amd Jetson Nano. I have tried multiple answers from the community but nothing work. Actually the problem was in Cython version compatibility. 
Do as following in step by step, my issue was resolved in 2nd steps, if your still doesn't work then go for the 3 option.
```
0. pip install setuptools==59.6.0
 1. pip install Cython==0.29.16
 2. pip install --no-binary=h5py h5py==2.10.0
 3. install fenics-calc by python setup.py install
```

Almost 2nd option will resolve the issue.

**Comment by timeleft--** [comment]
I don't even know what hdf5 is, but why don't you guys make a Mac release and spare us all the pain? I'm building a docker container on my Mac, so several of the options here are even more complicated for me. I'm pretty sure we don't need HDFS access at all, but HDF5 is unfortunately a transitive dependency that I have to live with. Please make a Mac build if you are such a low level library. Thanks!

**Comment by ajelenak** [comment]
Try building your Docker image from the conda, miniconda, or mamba base images? Then you would have h5py for the arm64 (my guess for your Mac) architecture.

P.S. HDF5 is https://www.hdfgroup.org/solutions/hdf5

**Comment by timeleft--** [comment]
Thanks for the suggestion. I will try that next. But this seems to have worked: 
```
RUN apt install -y libhdf5-dev
RUN pip install --upgrade "setuptools>=44.0.0"
RUN pip install --upgrade "wheel>=0.37.1"
RUN pip install --upgrade Cython
RUN pip install --no-binary=h5py h5py
```
