### ISSUE TITLE
suggestion: better error message when building

### ISSUE THREAD

**Issue by ngam** [h5py/h5py#2052]
To assist reproducing bugs, please include the following:
 * Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 16.04.2 LTS, CentOS 7)
 * Python version (e.g. 2.7, 3.5)
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows)
 * h5py version (e.g. 2.6)
 * HDF5 version (e.g. 1.8.17)
 * The full traceback/stack trace shown (if it appears)

`h5py.version.info` contains the needed versions, which can be displayed by
```
python -c 'import h5py; print(h5py.version.info)'
```
where `python` should be substituted for the path to python used to install
`h5py` with.

---

```
      Building h5py requires pkg-config unless the HDF5 path is explicitly specified
      error: pkg-config probably not installed: FileNotFoundError(2, 'No such file or directory')
```

It could be helpful if this error message included the actual variable to be set, for example: "set `HDF5_DIR=/usr/local/` or to your installation of HDF5"

**Comment by tacaswell** [comment]
@ngam I think we would happily merge a PR adding text to the effect to the error message.

It might also be good to include a link to the docs for building from source.

**Comment by ngam** [comment]
Here's a simple PR #2053 (feel free to edit, etc.)

Thanks for making this relatively easy nonetheless :)
