### ISSUE TITLE
Can't Navigate the file with list.key of h5py

### ISSUE THREAD

**Issue by diesseh** [h5py/h5py#2054]
Hello everybody,

I am new in python and I try to use h5py package following the tutorial avalaible here : https://lpdaac.usgs.gov/resources/e-learning/getting-started-gedi-l1b-data-python/

When I want to know the list : list(gediL1B.keys())

Here is the error message that I receive :

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_13932/2859272625.py in <module>
----> 1 list(gediL1B.keys())

~\anaconda3\envs\geditutorial\lib\_collections_abc.py in __iter__(self)
    718 
    719     def __iter__(self):
--> 720         yield from self._mapping
    721 
    722 KeysView.register(dict_keys)

~\anaconda3\envs\geditutorial\lib\site-packages\h5py\_hl\group.py in __iter__(self)
    431     def __iter__(self):
    432         """ Iterate over member names """
--> 433         for x in self.id.__iter__():
    434             yield self._d(x)
    435 

h5py\h5g.pyx in h5py.h5g.GroupID.__iter__()

h5py\h5g.pyx in h5py.h5g.GroupID.__iter__()

h5py\h5g.pyx in h5py.h5g.GroupIter.__init__()

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\h5g.pyx in h5py.h5g.GroupID.get_num_objs()

TypeError: Not a group (not a group)

**Comment by ajelenak** [comment]
What `print(gediL1B)` shows?

I tried the file from the tutorial and it worked:

```python
In [1]: import h5py

In [2]: f = h5py.File('GEDI01_B_2019170155833_O02932_T02267_02_003_01.h5', mode='r')

In [3]: print(f)
Out[3]: <HDF5 file "GEDI01_B_2019170155833_O02932_T02267_02_003_01.h5" (mode r)>

In [4]: list(f.keys())
Out[4]: 
['BEAM0000',
 'BEAM0001',
 'BEAM0010',
 'BEAM0011',
 'BEAM0101',
 'BEAM0110',
 'BEAM1000',
 'BEAM1011',
 'METADATA']
```

Your error means `gediL1B` variable is not an `h5py.File` or `h5py.Group` object.

**Comment by ajelenak** [comment]
It looks like your GEDI file was not downloaded completely. The `.fdmdownload` extension indicates the download did not finish correctly (see explanation [here](https://fileinfo.com/extension/fdmdownload)). Your file after download must end with `.h5` only.

**Comment by takluyver** [comment]
Closing as this seems to have been a mistake downloading the file.
