### ISSUE TITLE
H5Pset_efile_prefix is missing

### ISSUE THREAD

**Issue by mkitti** [h5py/h5py#2055]
I noticed that a low-level interface (and thus high-level interface) is missing for [`H5Pset_efile_prefix`](https://portal.hdfgroup.org/display/HDF5/H5P_SET_EFILE_PREFIX), which sets the prefix for external datasets. It also allows external datasets to be made relative to location of the HDF5 file. External datasets should be differentiated from external links, which are references to other HDF5 files.

The function was mentioned in https://github.com/h5py/h5py/issues/945#issuecomment-366472956 but ultimately not implemented in https://github.com/h5py/h5py/pull/1000.

There are similar low-level functions for [links ](https://api.h5py.org/h5p.html#h5py.h5p.PropLAID.set_elink_prefix) and [virtual ](https://api.h5py.org/h5p.html#h5py.h5p.PropDAID.set_virtual_prefix) datasets. Those correspond to [H5Pset_elink_prefix](https://portal.hdfgroup.org/display/HDF5/H5P_GET_ELINK_PREFIX) and [H5Pset_virtual_prefix](https://portal.hdfgroup.org/display/HDF5/H5P_SET_VIRTUAL_PREFIX).

**Comment by aragilar** [comment]
I don't see any reason why we wouldn't accept a pull request add low-level wrappers around them. I'm less sure how best to expose them at the high level, but that can be discussed once there are low-level wrappers.
