### ISSUE TITLE
Poor performance for very large files utilizing object references?

### ISSUE THREAD

**Issue by tjdcs** [h5py/h5py#2056]
Summary of the h5py configuration
---------------------------------

h5py    3.6.0
HDF5    1.12.1
Python  3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.22.2
cython (built with) 0.29.24
numpy (built against) 1.21.4
HDF5 (built against) 1.12.1

I have an HDF5 file (.mat file from matlab, v7.3) that is around 6gb on disk. From matlab it is a cell array with around 1.7M cells, each cell contains a single vector if uint16's ranging from several dozen to several thousand values. When reading the data into python the cell array becomes a list of obj. references. to get to the list of uint16's I dereference the object and then try to read the first value out of the first list in the first cell.

This takes some time, understandably because the file is large. Then when I go to read the seccond cell array it is just as slow as the first access. it seems like the file is being read from the disk multiple times with no caching. This is a huge performance issue, but perhaps there's something wrong with how I'm accessing the data. 

Happy to provide the data file privately for debug but don't want to archive onto the public issue. 

```py
import h5py

def main():
    f = h5py.File("./Tiles.mat")
    obj = f['tiles'][0][0]
    data = f[obj]
    firstPt = data[0][0]
    seccondPt = data[0][1]
    pass

if __name__ == "__main__":
    main()
    pass
```

**Comment by tjdcs** [comment]
Also, this is just a trivial example. Really I eventually need to iterate over the "cells" and then iterate over the vectors that those cells contain.

**Comment by tjdcs** [comment]
Sorry to update again so quickly, I decided to scriptify the access to the various levels and it seems like everything runs much faster than I initially thought. So this might just be an issue with trying to access variables in an interactive debug console in VSCode. Still interesting, but perhaps I don't need support on this issue? But let me think on it for a few days. 

If the detail about the interactive console is still interesting I'm happy to provide the data file to developers.

**Comment by aragilar** [comment]
@tjdcs It's unclear how said cells are encoded into the file, are there many datasets, and tiles gives an id? Ideally, you want your code to take slices of data, rather than reading one bit at a time, as your code appears to do (which I'd expect to be slow).

**Comment by tjdcs** [comment]
Closing because things actually seem fine for real code. Bad in vscode debugger. Open to more discussion if it's valuable.
