### ISSUE TITLE
ImportError: DLL load failed while importing _errors: Not enough memory resources are available to process this command.

### ISSUE THREAD

**Issue by sanJuan2021** [h5py/h5py#2062]
Operating System: Microsoft Windows 10 Pro
Python Version: 3.8.0 Anaconda
Ive created a virtual environment
h5py version: 3.6.0

import h5py 

=> triggers the following error:

File "C:\ProgramData\Anaconda3\envs\env1\lib\site-packages\h5py\__init__.py", line 25, in <module>
    from . import _errors
ImportError: DLL load failed while importing _errors: Not enough memory resources are available to process this command.

**Comment by takluyver** [comment]
"Not enough memory resources are available" sounds like your system was running out of memory. This isn't an error message I've ever seen before, though. If you think it's an issue in h5py, can you work out a bit more of what causes it? We have CI on Windows which is working.

**Comment by takluyver** [comment]
Closing as it doesn't sound like there's anything for h5py to fix here. We can reopen it if necessary.

**Comment by MubinTokhi** [comment]
I am also getting the same problem tried to solve it, nothing is happening
