### ISSUE TITLE
Deadlock in Dataset._extent_type

### ISSUE THREAD

**Issue by ArvidJB** [h5py/h5py#2064]
Summary of the h5py configuration
---------------------------------

h5py    3.6.0
HDF5    1.10.5
Python  3.9.7 (default, Oct 25 2021, 01:04:21)
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.20.2
cython (built with) 0.29.27
numpy (built against) 1.19.3
HDF5 (built against) 1.10.5

We use `h5py` to read from the same file with multiple threads. Occasionally deadlocks happen in `Dataset._extent_type` which is wrapped in two locks.
```
    @cached_property
    @with_phil
    def _extent_type(self):
        return self.id.get_space().get_simple_extent_type()
```
The two locks are
1. the `h5py` `_phil` lock which is acquired with the `@with_phil` decorator
2. the `RLock` in `@functools.cached_property`

Here are two threads which deadlock. Thread one calls `Dataset.size` and acquired the `RLock` in `cached_property` for `_extent_type` and then tries to acquire the `_phil` lock:
```
Traceback (most recent call first):
  #19   File "/opt/python/python-3.9/lib64/python3.9/functools.py", line 1737, in __get__
  #29   File "/usr/local/python/python-3.9/std/lib64/python3.9/site-packages/h5py/_hl/dataset.py", line 581, in _is_empty
          return self._extent_type == h5s.NULL
  #36   File "/opt/python/python-3.9/lib64/python3.9/functools.py", line 1737, in __get__
  #46   File "/usr/local/python/python-3.9/std/lib64/python3.9/site-packages/h5py/_hl/dataset.py", line 436, in size
```
The other thread calls `h5py.Dataset.__getitem__` where it acquires the `_phil` lock and then calls `_extent_type` where it tries to acquire the `RLock` in `cached_property`:
```
Traceback (most recent call first):
  #7    <built-in method __enter__ of _thread.RLock object at remote 0x7fc21a0ac5c0>
  #12   File "/opt/python/python-3.9/lib64/python3.9/functools.py", line 1733, in __get__
  #22   File "/usr/local/python/python-3.9/std/lib64/python3.9/site-packages/h5py/_hl/dataset.py", line 687, in _fast_read_ok
          self._extent_type == h5s.SIMPLE
  #29   File "/opt/python/python-3.9/lib64/python3.9/functools.py", line 1737, in __get__
  #39   File "/usr/local/python/python-3.9/std/lib64/python3.9/site-packages/h5py/_hl/dataset.py", line 708, in __getitem__
          if self._fast_read_ok and (new_dtype is None):
```

**Comment by takluyver** [comment]
Oh, that's a pain. I hadn't thought about cached_property needing a lock, though I can see why it would.

I guess an easy fix would be to swap the decorators so it gets the `phil` lock before the cached_property one, even though that means it will acquire phil when it doesn't really need to.

**Comment by ArvidJB** [comment]
Thanks @takluyver that is a good idea.
Another option would be to downgrade `cached_property` to just `property` for `_extent_type` since it seems like `_extent_type` is only get called from `_is_empty` and `_fast_read_ok`, which are cached properties themselves. In the worst case we would then compute `_extent_type` twice.

**Comment by takluyver** [comment]
I think it would still be open to a deadlock on the `_is_empty` cached property, though? `.size` would get the lock for filling out `_is_empty`, and then try to get phil for `_extent_type`. But `__getitem__`, `read_direct` or `write_direct` might get phil and then try to evaluate `_is_empty`. Not totally sure, but I think it's still an issue. And if so, swapping the decorators on `_extent_type` doesn't help either.

Maybe we need to implement the cached properties ourselves, so we can avoid locking. There shouldn't be any issue if they get evaluated more than once.

**Comment by ArvidJB** [comment]
I think you are right, neither of these two ideas is guaranteed to help.
Implementing cached_property in h5py should be relatively easy, we could just copy
https://github.com/python/cpython/blob/e801e88744f34508aa338f9f7f3f3baee012f813/Lib/functools.py#L966
and remove all the locking logic.

FWIW: I also found this discussion
https://bugs.python.org/issue43468
on how cached_property is fundamentally broken anyway...

**Comment by tacaswell** [comment]
I'm in favor of flipping the decorator order and just dealing with extra locking.  If I remember how cached_property works, on first execution it shadows the class property with the result (so it really _is_ just attribute lookup) so we would still only have the `phil` lock the first time.

I remember giving the `cached_property` locking logic a careful reading.  I remember it being a bit subtle and am wary to just strip it all out.  If we go with the simple `if self._val is not None: ...` implementation in a normal property then we pay the property cost + phil every time.

**Comment by tacaswell** [comment]
Can we put `@with_phil` as the first decorator on  `_is_empty` and `_fast_read_ok` as well? 

It might be with making 

```python
from functools import cached_property as _cached_property

def with_phil_cached_property(func):
    return with_phil(_cached_property(func))
```

to make it less likely we will run into these problem again?

If we are sure we never try to grab the cached property lock unless we already hold the phil then I think we can not have the deadlock.

------

To be fair, I am biased against removing locks that I do not fully understand what they are locking (the presumption being that they are there for a good reason).

**Comment by ArvidJB** [comment]
I think the `cached_property` decorators were introduced as a performance improvement in afa86a174fa035d3660cd1b7f4045cc8200edc43. Previously these properties would have been read multiple times. Therefore I think the locks are just an implementation detail of `functools.cached_property`.

I like @tacaswell 's suggestion of a `with_phil_cached_property`. How about taking the code from
https://github.com/python/cpython/blob/434ffb7f1f86e6b0cdfad3ede59993934d86e464/Lib/functools.py#L966
and replacing the lock with the phil lock, i.e.,
```
_NOT_FOUND = object()

class with_phil_cached_property:
    def __init__(self, func):
        self.func = func
        self.attrname = None
        self.__doc__ = func.__doc__

    def __set_name__(self, owner, name):
        if self.attrname is None:
            self.attrname = name
        elif name != self.attrname:
            raise TypeError(
                "Cannot assign the same cached_property to two different names "
                f"({self.attrname!r} and {name!r})."
            )

    def __get__(self, instance, owner=None):
        if instance is None:
            return self
        if self.attrname is None:
            raise TypeError(
                "Cannot use cached_property instance without calling __set_name__ on it.")
        try:
            cache = instance.__dict__
        except AttributeError:  # not all objects have __dict__ (e.g. class defines slots)
            msg = (
                f"No '__dict__' attribute on {type(instance).__name__!r} "
                f"instance to cache {self.attrname!r} property."
            )
            raise TypeError(msg) from None
        val = cache.get(self.attrname, _NOT_FOUND)
        if val is _NOT_FOUND:
            with _phil:
                # check if another thread filled cache while we awaited lock
                val = cache.get(self.attrname, _NOT_FOUND)
                if val is _NOT_FOUND:
                    val = self.func(instance)
                    try:
                        cache[self.attrname] = val
                    except TypeError:
                        msg = (
                            f"The '__dict__' attribute on {type(instance).__name__!r} instance "
                            f"does not support item assignment for caching {self.attrname!r} property."
                        )
                        raise TypeError(msg) from None
        return val
```
I think this would preserve the previous behavior exactly and not introduce any additional overhead.

**Comment by tacaswell** [comment]
I am skeptical that just using `cached_property` as-is which,  while it will have a superfluous lock it will always be uncontested, is going to be noticeably slower that vendoring and modifying the code from CPython.  That said, I am very happy to be proven wrong!

**Comment by takluyver** [comment]
I think getting phil for `_is_empty` would suffice.

I lean towards implementing our own lock-free version of cached_property which we could freely combine with phil. We already have code to cache some things depending on whether the file is read-only. So long as we've got two different locks in play, any additions or refactorings risk reintroducing a deadlock. It's hard to catch in code review, because you need to follow all the different code paths that use the property in question, and it's kind of hard to catch with tests, because the deadlock might be rare, and the symptom is a hang rather than an error.

It makes sense that the general implementation of `cached_property` needs a lock - there could be strange bugs if a property was *sometimes* calculated twice and e.g. could give different results. But we're only using it where values should be constant, and we know calculating them is thread safe (because of phil), so in this scenario there should be no problem if two threads calculate the property.

**Comment by ArvidJB** [comment]
I am okay with any of the proposed solutions, whether it's the lock-free cached_property or with_phil_cached_property with one or two locks.
The original PR https://github.com/h5py/h5py/pull/1402 seems to have been motivated by performance issues in https://github.com/h5py/h5py/issues/1391 . It might be running those tests again and  checking the performance penalty due to repeatedly acquiring and releasing the phil lock in one of the proposals?

**Comment by takluyver** [comment]
I've had a go at my preferred solution - a `cached_property` with no lock - in #2066.

**Comment by ArvidJB** [comment]
Thanks a lot for the quick fix of this!
