### ISSUE TITLE
Read_direct: Cannot broadcast to zero-length array

### ISSUE THREAD

**Issue by hoongtong** [h5py/h5py#2070]
* Operating System Ubuntu 18.04
 * Python version 3.6
 * h5py version 3.1
 * HDF5 version 1.10.5
---
I wish to read various H5 files and read it into a large NumPy file. For this, I use the method read_direct. Assume my dataset 'x' to be a (2500 x 3) NumPy array. Now the code below throws a Type Error.
```
# Create a large buffer
a = np.empty((15000, 3), dtype=int)
# Read (2500 x 3) arrays
f['x'].read_direct(a, dest_sel = np.s_[0:2500])        # Succeeds
f['x'].read_direct(a, dest_sel = np.s_[2500:5000])     # Error

```
Does anyone know what might be the issue here? The array can be sliced by `np.s_[2500:5000]` without fail, however the error message tells me the dim-0 of the sliced result is 0.

Stack trace:
```
/opt/conda/envs/habitat/lib/python3.6/site-packages/h5py/_hl/dataset.py in read_direct(self, dest, source_sel, dest_sel)

/opt/conda/envs/habitat/lib/python3.6/site-packages/h5py/_hl/selections.py in broadcast(self, source_shape)
    289         for idx in xrange(1,rank+1):
    290             if len(target) == 0 or scalar[-idx]:     # Skip scalar axes
--> 291                 tshape.append(1)
    292             else:
    293                 t = target.pop()

/opt/conda/envs/habitat/lib/python3.6/site-packages/h5py/_hl/selections.py in expand_shape(self, source_shape)
    262 
    263         self._sel = (start, count, step, scalar)
--> 264 
    265         self._mshape = tuple(x for x, y in zip(count, scalar) if not y)
    266 

TypeError: Can't broadcast (2500, 3) -> (0, 3)
```

**Comment by tacaswell** [comment]
I think the issue is that direct read is expecting a (2500, 3) array to come back because that is the size implied by the slice object however when that is intersected with the shape of the data set the actual shape of the selected data is (0, 3) and that is what can not be broad cast.

**Comment by hoongtong** [comment]
I'm not sure I understand what you mean. What is intersected with what? The dataset x should be a (2500,3) array should fit in the matrix `a` with slice `np.s_[2500:5000])`, right?

**Comment by tacaswell** [comment]
@hoongtong 🐑 You are correct.  I miss-read `dest_sel` as `dset_sel` and assumed I know the API off the top of my head.

**Comment by tacaswell** [comment]
I can not reproduce this:

```python
import h5py
import numpy as np

with h5py.File("/tmp/test.h5", "w") as f:
    f["x"] = np.arange(2500).reshape(-1, 1) * np.ones(3).reshape(1, 3)

# Create a large buffer
a = np.empty((15000, 3), dtype=int)
with h5py.File("/tmp/test.h5", "r") as f:
    # Read (2500 x 3) arrays
    f["x"].read_direct(a, dest_sel=np.s_[0:2500])
    f["x"].read_direct(a, dest_sel=np.s_[2500:5000])


```

**Comment by takluyver** [comment]
@hoongtong can you make a piece of code that reproduces this? Or modify the code @tacaswell posted to reproduce it?

I see you're also on an older version of h5py - are you able to try with the current version (3.6)? Or even install it from master? This may mean using a newer Python version, because we dropped support for Python 3.6, although it *might* still work on 3.6 if you comment out the `python_requires=` in `setup.py`.
