### ISSUE TITLE
Need support of AWS credentials with tokens for h5py with ROS3 driver 

### ISSUE THREAD

**Issue by yanping2liao** [h5py/h5py#2072]
Summary of the h5py configuration
---------------------------------
h5py    3.6.0
HDF5    1.12.1
Python  3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:21:54) [MSC v.1929 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.21.5
cython (built with) 0.29.24
numpy (built against) 1.19.5
HDF5 (built against) 1.12.1

Our AWS S3 bucket configuration requires boto3 session credentials with
```
from boto3.session import Session
boto_session = Session(aws_access_key_id=cred.access_key,
             aws_secret_access_key=cred.secret_key
             , aws_session_token=cred.token
)
```

While we are trying to pass the same credentials to h5py.File(...) but we cannot pass the token:
```
h5_file = h5py.File(s3_file_name, driver='ros3',
    aws_region=bytes(region_name, 'utf-8'),
    secret_id = bytes(cred.access_key, 'utf-8'),
    secret_key = bytes(cred.secret_key, 'utf-8'),
    token=bytes(cred.token, 'utf-8'))
```
> Traceback (most recent call last):
>   File "<input>", line 1, in <module>
>   File "...\conda\conda\envs\py39_env\lib\site-packages\h5py\_hl\files.py", line 502, in __init__
>     fapl = make_fapl(driver, libver, rdcc_nslots, rdcc_nbytes, rdcc_w0,
>   File "...\conda\conda\envs\py39_env\lib\site-packages\h5py\_hl\files.py", line 166, in make_fapl
>     set_fapl(plist, \*\*kwds)
>   File "...\conda\conda\envs\py39_env\lib\site-packages\h5py\_hl\files.py", line 78, in <lambda>
>     _drivers['ros3'] = lambda plist, **kwargs: plist.set_fapl_ros3(**kwargs)
>   File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py\h5p.pyx", line 1057, in h5py.h5p.PropFAID.set_fapl_ros3
> TypeError: set_fapl_ros3() got an unexpected keyword argument 'token'

Without the token, we are getting the error.
```
h5_file = h5py.File(s3_file_name, driver='ros3',
    aws_region=bytes(region_name, 'utf-8'),
    secret_id = bytes(cred.access_key, 'utf-8'),
    secret_key = bytes(cred.secret_key, 'utf-8'))
```

>   File "<input>", line 1, in <module>
>   File "...\conda\conda\envs\py39_env\lib\site-packages\h5py\_hl\files.py", line 507, in __init__
>     fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
>   File "...\conda\conda\envs\py39_env\lib\site-packages\h5py\_hl\files.py", line 220, in make_fid
>     fid = h5f.open(name, flags, fapl=fapl)
>   File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py\h5f.pyx", line 106, in h5py.h5f.open
> OSError: Unable to open file (curl cannot perform request)
 
Could we please add support for credentials with required tokens?

**Comment by ajelenak** [comment]
Unfortunately, no. This is the limitation of the current _ros3_ driver implementation in the HDF5 library. Your options are either the [fsspec](https://filesystem-spec.readthedocs.io/en/latest/) package with the _fileobj_ driver, or [h5pyd](https://github.com/HDFGroup/h5pyd) and [HSDS](https://github.com/HDFGroup/hsds).

**Comment by yanping2liao** [comment]
Thanks for the prompt response. Could we add this as an enhancement
request? H5py is very efficient in fetching data from S3 and would really
like to use it if we can get over the credentials hurdle.

**Comment by ajelenak** [comment]
You will get your job done much quicker if you opt for the fsspec package, or s3fs if only interested in S3. See: [`S3FileSystem`](https://s3fs.readthedocs.io/en/stable/api.html#s3fs.core.S3FileSystem). It supports security tokens.

Something like this should work:
```python
from s3fs import S3FileSystem

s3 = S3FileSystem(...)
with s3.open('mybucket/myfile.h5', mode='rb') as s3f:
    with h5py.File(s3f, mode='r') as f:
        print(list(f.keys()))
```

**Comment by ajelenak** [comment]
You are welcome!

The ros3 driver is native to the HDF5 library, while s3fs or any other Python file-object has to pass through h5py prior to reaching the HDF5 library. So there is a little overhead in the s3fs case. However, the performance is dominated by the HDF5 library making many but small requests for data and executing them serially. I am actually intrigued that you find the ros3 driver efficient. What kind of HDF5 files are those?

**Comment by tacaswell** [comment]
I'm going to close this as there is nothing actionable on the h5py side (all of these solutions are either above or below h5py in the stack!), but please keep talking 😄 .
