### ISSUE TITLE
`h5diff` with files on AWS S3 bucket

### ISSUE THREAD

**Issue by gcaria** [h5py/h5py#2074]
I'm not sure this is the right place for this question, please feel free to point me to the appropriate venue if that's not the case.

As far as I can tell `h5diff` does not work with files on AWS S3 bucket, so I would like to ask whether support for S3 can be added.

**Comment by ajelenak** [comment]
`h5diff` is one of the HDF5 library command-line tools and has nothing to do with h5py. Better is to ask this question on the [HDF Forum](https://forum.hdfgroup.org/) or create an issue in the [HDF5 GitHub repository](https://github.com/HDFGroup/hdf5/issues).
