### ISSUE TITLE
Reading Matlab String classes fails

### ISSUE THREAD

**Issue by thht** [h5py/h5py#2077]
Hi,

I use h5py to read Matlab `.mat` files (which are hdf5 files under the hood). In 2016, Matlab introduced a dedicated [string class](https://de.mathworks.com/help/matlab/ref/string.html). Matlab saves and loads it just fine but when I try to read such a file with h5py, it results in a uint32 array whose contents do not seem to have anything to do with the contents of the string.

No mater what string is stored in the variable, the output is always: `[[3707764736          2          1          1          1          1]]`

You can download a testfile here: https://gitlab.com/obob/pymatreader/-/raw/master/tests/test_data/string_v73.mat (I cannot attach it to the issue because github does not accept the file type).

There are two variables in the `mat` file. `my_char` is an array of `char` which is the old way to represent strings in Matlab. This works fine. `my_string` is the string class that fails to import correctly.

Thanks a lot in advance!

```
Summary of the h5py configuration
---------------------------------
h5py    3.6.0
HDF5    1.12.1
Python  3.10.3 (main, Mar 28 2022, 09:30:03) [GCC 7.5.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.22.3
cython (built with) 0.29.24
numpy (built against) 1.21.4
HDF5 (built against) 1.12.1
```

**Comment by takluyver** [comment]
`[[3707764736 2 1 1 1 1]]` appears to be correct as far as h5py is concerned. It's stored in HDF5 as a 2D array of uint32 numbers. You can see this with h5dump:

```
   DATASET "my_string" {
      DATATYPE  H5T_STD_U32LE
      DATASPACE  SIMPLE { ( 1, 6 ) / ( 1, 6 ) }
      DATA {
      (0,0): 3707764736, 2, 1, 1, 1, 1
      }
      ATTRIBUTE "MATLAB_class" {
         DATATYPE  H5T_STRING {
            STRSIZE 6;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
         DATA {
         (0): "string"
         }
      }
      ATTRIBUTE "MATLAB_object_decode" {
         DATATYPE  H5T_STD_I32LE
         DATASPACE  SCALAR
         DATA {
         (0): 3
         }
      }
   }
```

Matlab presumably uses the `MATLAB_class` attribute to convert that to someone else. But it's not storing it as anything that HDF5 considers a string.

**Comment by thht** [comment]
yes, i already looked at the output of `h5dump` and did not find anything that i could relate to the actual content of the string. do you (or anybody else) have any idea where else i could look in the file or the hdf5 structure?

**Comment by takluyver** [comment]
Sorry, I have no idea about how Matlab structures its files. I don't wish to be snarky, but if you have Matlab licenses, surely your best option is to ask Mathworks? They've taken an open source library and used it to design an effectively proprietary file format. They should be willing to explain how it fits together.

**Comment by thht** [comment]
good idea! will do that and report back.

**Comment by skjerns** [comment]
If you find an answer let us know, I'm stuggleing with this as well with my library https://github.com/skjerns/mat7.3 (which is using h5py under the hood)

**Comment by takluyver** [comment]
Closing as I don't think there's anything to do in h5py - we seem to be reading the HDF5 file correctly, but Matlab seems to have invented some strange new flavour of HDF5. FWIW, looking at the .mat file from @thht's original comment in a hex editor, I can see some characters abcdefg in the file (starting at offset 0xDE8, reading every 8th byte), but I can't spot anything similar in the h5dump output.
