### ISSUE TITLE
Link to author list is broken in contributing guidelines

### ISSUE THREAD

**Issue by dguest** [h5py/h5py#2078]
I'm trying to follow the [contributing guidelines][1] and found an issue when I got to "add yourself to the author list". There is no author list! I'm happy to have my contribution counted via the git history (it's just a small fix) but maybe the docs should be fixed.

[1]: https://docs.h5py.org/en/stable/contributing.html

**Comment by takluyver** [comment]
Thanks, yes, the docs should be fixed. We got rid of the author list (#1941) because it could be a significant extra hassle for people just wanting to make a small contribution.

**Comment by takluyver** [comment]
In fact this is already changed in the repository, but the default view of the docs is `/stable/`, i.e. the last release. So it will be updated once we make a new release.
