### ISSUE TITLE
Error when accessing empty entries in vlen dataset 

### ISSUE THREAD

**Issue by sezelt** [h5py/h5py#2083]
In our application, we use h5py to store arrays of variable-length numpy structured arrays, where often some of the entries are empty. In h5py version 2.10, the behavior was that accessing an element of an h5py Dataset that had no data would return a zero-length numpy array, with the correct structured dtype.

However, in the latest version (I am using 3.6.0), accessing a dataset entry with no data (whether initialized with an empty array or not) causes a ValueError. The relevant issue in our project is here: https://github.com/py4dstem/py4DSTEM/issues/262 . A minimal example is below. 

```python
import h5py
import numpy as np

dtype = np.dtype([('a',np.float64),('b',np.float64)])

f = h5py.File("vlen_test.h5",'a')
h5dt = h5py.vlen_dtype(dtype)
dset = f.create_dataset('vlen_test',(4,),dtype=h5dt)

empty_arr = np.zeros((0,),dtype=dtype)
dset[0] = empty_arr

print(dset[0])
```

Running this yields this error:
```
----> 1 print(dset[0])

File h5py/_objects.pyx:54, in h5py._objects.with_phil.wrapper()

File h5py/_objects.pyx:55, in h5py._objects.with_phil.wrapper()

File ~/opt/miniconda3/envs/new4d/lib/python3.8/site-packages/h5py/_hl/dataset.py:793, in Dataset.__getitem__(self, args, new_dtype)
    791 mspace = h5s.create_simple(selection.mshape)
    792 fspace = selection.id
--> 793 self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
    795 # Patch up the output for NumPy
    796 if arr.shape == ():

File h5py/_objects.pyx:54, in h5py._objects.with_phil.wrapper()

File h5py/_objects.pyx:55, in h5py._objects.with_phil.wrapper()

File h5py/h5d.pyx:192, in h5py.h5d.DatasetID.read()

File h5py/_proxy.pyx:141, in h5py._proxy.dset_rw()

File h5py/_conv.pyx:660, in h5py._conv.vlen2ndarray()

File h5py/_conv.pyx:726, in h5py._conv.conv_vlen2ndarray()

ValueError: Cannot create cython.array from NULL pointer
```

Accessing `dset[1]`, which hasn't been initialized at all, gives the same error. 

Output of `h5py.version.info`:
```
h5py    3.6.0
HDF5    1.12.1
Python  3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:05:47)
[Clang 12.0.1 ]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.22.3
cython (built with) 0.29.24
numpy (built against) 1.17.3
HDF5 (built against) 1.12.1
```
and I am using macOS 12.2.1 on x86_64

**Comment by takluyver** [comment]
I guess the conversion code should check for NULL and create a zero length array. Here's the line your traceback points to:

https://github.com/h5py/h5py/blob/3.6.0/h5py/_conv.pyx#L726

In my opinion, vlen support is not something HDF5 or h5py do particularly well, and I'd try to avoid using it unless I really had to.
