### ISSUE TITLE
Reading h5 files occasionally fails with OSError: Can't read data, Invalid argument 

### ISSUE THREAD

**Issue by cwiede** [h5py/h5py#2084]
To assist reproducing bugs, please include the following:
 * Operating System: Windows 10
 * Python version: 3.7.7
 * Where Python was acquired: winpython
 * h5py version: 3.6.0 (installed via pip)
 * HDF5 version: 1.12.1
 * h5py.version.info:
h5py    3.6.0
HDF5    1.12.1
Python  3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.21.1
cython (built with) 0.29.24
numpy (built against) 1.14.5
HDF5 (built against) 1.12.1
 * The full traceback/stack trace shown (if it appears)
```
Traceback (most recent call last):
  File "C:\path\to\myhdf5.py", line 304, in getRcvTimestamp
    return self._file["streams"][stream][streamIdx]["_receive_timestamp"]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\venv\lib\site-packages\h5py\_hl\dataset.py", line 793, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5d.pyx", line 192, in h5py.h5d.DatasetID.read
  File "h5py\_proxy.pyx", line 140, in h5py._proxy.dset_rw
OSError: [Errno 22] Can't read data (file read failed: time = Tue Apr 12 11:27:54 2022
, filename = 'E:\h5file.h5', file descriptor = 4, errno = 22, error message = 'Invalid argument', buf = 0000019C55766FA0, total read size = 139712, bytes this sub-read = 139712, bytes actually read = 18446744073709551615, offset = 3538968)
```

Hi, I get this error occasionally when querying data from a hdf5 file. The python statement causing this issue is this:

    self._file["streams"][stream][streamIdx]["_receive_timestamp"]

where stream is a string and streamIdx is the index of a frame we want to access. The h5py.File object is always called from within the same thread. The file is on a local NTFS filesystem and is exclusively opened for read access (aka "r" mide), no other readers or writers have this file open. Sometimes the error seems to heal itself automatically (i.e. subsequent calls do not show the error. Sometimes the error shows up persistently. As a workaround, I re-open the file like this:

```
        try:
            return self._file["streams"][stream][streamIdx]["_receive_timestamp"]
        except OSError as e:
            if e.errno == 22:
                logger.warning("reopening due to errno 22")
                fn = self._file.filename
                self._file.close()
                self._file = h5py.File(fn, "r")
                return self._file["streams"][stream][streamIdx]["_receive_timestamp"]
```

and this seems to improve the situation (there are no persistent errors anymore afterwards, but there are still non-persistent errors).

The stream is created like this in the writer process (which is finished when reading the file):
```
    type_content = h5py.vlen_dtype(np.dtype(np.uint8))
    type_timestamp = np.int64
    type_dataType = h5py.string_dtype()
    dtype = [('content', type_content),
                  ('dataType', type_dataType),
                  ('dataTimestamp', type_timestamp),
                  ('rcvTimestamp', type_timestamp),
                  ]
    self._file["streams"].create_dataset(stream, (0,), chunks=(1,), maxshape=(None,), dtype=self.dtype)
```
and it is resized and filled with new frames when needed.

**Comment by takluyver** [comment]
That looks like an error coming from HDF5 itself. If you can reproduce it, try calling `h5py._errors.unsilence_errors()` beforehand to get HDF5 to print its own error stack trace, which will give more details about where exactly it fails.

@epourmal, do you know if this is a known issue (intermittent "Can't read data" with an "Invalid argument" system error)?

**Comment by cwiede** [comment]
The output with unsilence_errors() enabled is this:

```
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5Dio.c line 179 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5VLcallback.c line 2011 in H5VL_dataset_read(): dataset read failed
    major: Virtual Object Layer
    minor: Read failed
  #002: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5VLcallback.c line 1978 in H5VL__dataset_read(): dataset read failed
    major: Virtual Object Layer
    minor: Read failed
  #003: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5VLnative_dataset.c line 166 in H5VL__native_dataset_read(): can't read data
    major: Dataset
    minor: Read failed
  #004: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5Dio.c line 545 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #005: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5Dchunk.c line 2572 in H5D__chunk_read(): chunked read failed
    major: Dataset
    minor: Read failed
  #006: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5Dscatgath.c line 527 in H5D__scatgath_read(): datatype conversion failed
    major: Dataset
    minor: Can't convert datatypes
  #007: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5T.c line 5458 in H5T_convert(): datatype conversion failed
    major: Datatype
    minor: Can't convert datatypes
  #008: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5Tconv.c line 2591 in H5T__conv_struct_opt(): unable to convert compound datatype member
    major: Datatype
    minor: Unable to initialize object
  #009: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5T.c line 5458 in H5T_convert(): datatype conversion failed
    major: Datatype
    minor: Can't convert datatypes
  #010: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5Tconv.c line 3344 in H5T__conv_vlen(): can't read VL data
    major: Datatype
    minor: Read failed
  #011: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5Tvlen.c line 936 in H5T__vlen_disk_read(): unable to get blob
    major: Datatype
    minor: Can't get value
  #012: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5VLcallback.c line 6918 in H5VL_blob_get(): blob get failed
    major: Virtual Object Layer
    minor: Can't get value
  #013: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5VLcallback.c line 6883 in H5VL__blob_get(): blob get callback failed
    major: Virtual Object Layer
    minor: Can't get value
  #014: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5VLnative_blob.c line 125 in H5VL__native_blob_get(): unable to read VL information
    major: Virtual Object Layer
    minor: Read failed
  #015: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5HG.c line 599 in H5HG_read(): unable to protect global heap
    major: Heap
    minor: Unable to protect metadata
  #016: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5HG.c line 256 in H5HG__protect(): unable to protect global heap
    major: Heap
    minor: Unable to protect metadata
  #017: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5AC.c line 1426 in H5AC_protect(): H5C_protect() failed
    major: Object cache
    minor: Unable to protect metadata
  #018: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5C.c line 2368 in H5C_protect(): can't load entry
    major: Object cache
    minor: Unable to load metadata into cache
  #019: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5C.c line 7189 in H5C__load_entry(): Can't read image*
    major: Object cache
    minor: Read failed
  #020: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5Fio.c line 148 in H5F_block_read(): read through page buffer failed
    major: Low-level I/O
    minor: Read failed
  #021: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5PB.c line 721 in H5PB_read(): read through metadata accumulator failed
    major: Page Buffering
    minor: Read failed
  #022: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5Faccum.c line 252 in H5F__accum_read(): driver read request failed
    major: Low-level I/O
    minor: Read failed
  #023: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5FDint.c line 189 in H5FD_read(): driver read request failed
    major: Virtual File Layer
    minor: Read failed
  #024: C:\Users\VssAdministrator\AppData\Local\Temp\tmpdze8u987\hdf5-1.12.1\src\H5FDsec2.c line 761 in H5FD__sec2_read(): file read failed: time = Tue Apr 19 14:59:29 2022
, filename = 'h5file.h5', file descriptor = 4, errno = 22, error message = 'Invalid argument', buf = 000001F023943FB0, total read size = 4096, bytes this sub-read = 4096, bytes actually read = 18446744073709551615, offset = 61318816
    major: Low-level I/O
    minor: Read failed
```

**Comment by ajelenak** [comment]
> , filename = 'h5file.h5', file descriptor = 4, errno = 22, error message = 'Invalid argument', buf = 000001F023943FB0, total read size = 4096, bytes this sub-read = 4096, bytes actually read = 18446744073709551615, offset = 61318816

I think the value `18446744073709551615` above is the `HADDR_UNDEF` HDF5 constant which is typically used to indicate no data coming from the storage system. Where is this file stored?

**Comment by cwiede** [comment]
It's on a local NTFS file system (an internal SSD drive).

**Comment by ajelenak** [comment]
Since this problem appears occasionally, it must be caused by a specific set of conditions. Perhaps you could post your question on the [HDF Forum](https://forum.hdfgroup.org/)? Just include a lot more detail about your application and runtime environment.

**Comment by epourmal** [comment]
> That looks like an error coming from HDF5 itself. If you can reproduce it, try calling `h5py._errors.unsilence_errors()` beforehand to get HDF5 to print its own error stack trace, which will give more details about where exactly it fails.
> 
> @epourmal, do you know if this is a known issue (intermittent "Can't read data" with an "Invalid argument" system error)?

As far as I know there was no known issue. I would suggest to try a few things:

1. After file is closed for writing wait before opening it again. 
2. When this error occurs try h5dump and see if the error is reproducible. One should see similar HDF5 error stack. This will indicate that VL data was not stored properly (some metadata was not flushed).
3. Try 1.10.8 and see if the behavior is reproducible with 1.10 too.
4. As @ajelenak suggested post on HDF-FORUM for HDF5 developers to see the error. They may come up with more suggestions.

**Comment by takluyver** [comment]
I'm going to close this as I don't think there's anything for h5py to do. If the error is intermittent, it may suggest that there's a problem with the physical disk the data is stored on, but that's just a guess.

**Comment by aj95b** [comment]
I know, I see many people going through the same problem. I was able to work with the data just fine up until a few hours ago, and for the first time I am seeing this now.

**Comment by agirbau** [comment]
FYI, by installing [pytables](https://pypi.org/project/tables) it suddenly worked. 

[Credit to top answer](https://stackoverflow.com/questions/37464262/blosc-compression-in-hdf5-via-h5py)

**Comment by FarzanT** [comment]
What has helped me is to explicitly import the hdf5plugin at the top of the file, i.e. `import hdf5plugin`. Your IDE might suggest you to remove it to optimize imports, but you gotta ignore that.

**Comment by cwiede** [comment]
> What has helped me is to explicitly import the hdf5plugin at the top of the file, i.e. `import hdf5plugin`. Your IDE might suggest you to remove it to optimize imports, but you gotta ignore that.

If this helps, does it mean that we might suffer from some race condition when importing h5py from multiple threads? @takluyver @ajelenak 

Or maybe the import of the plugin is lazy, such that the race condition is really using h5py from multiple threads?

**Comment by takluyver** [comment]
If you have a scenario where one thread tries to use h5py while hdf5plugin is imported in a different thread, then you could have a race condition. But that's a pretty weird scenario. The import doesn't work lazily, once it finishes the plugins should all be registered.

The filters that hdf5plugin provides are applied after reading data from the file, though. So I suspect that @FarzanT is actually seeing a different error, even if it has a similar message.
