### ISSUE TITLE
Issue reading H5 with strings inside compound inside vlen dataset

### ISSUE THREAD

**Issue by p-e-s** [h5py/h5py#2085]
I am trying to read a H5 file that another of my programs has written in CPP. My CPP program stores randomly structured vlen/compound datasets. I have noticed that whenever my structures include a STRING element in a COMPOUND datatype in a VLEN datatype, then reading the file again with h5py fails on reading the dataset with a segmentation fault. I have attached a simplified H5 file with a 1x1 dataset that shows this behaviour (in my configuration at least) - see test.h5.txt - to be renamed to test.h5.
  [test.h5.txt](https://github.com/h5py/h5py/files/8475016/test.h5.txt)
The following python code triggers a segmentation fault: 
```
f = h5py.File('test.h5', 'r')
print(f.keys())
img = f['image']
img[0]
```
Generates the following output:
```
 <KeysViewHDF5 ['image']>
Segmentation fault (core dumped)
```

However, i am able to read the file using h5dump and custom CPP programs. Here is an output of h5dump:
```
h5dump test.h5 
HDF5 "test.h5" {
GROUP "/" {
   DATASET "image" {
      DATATYPE  H5T_COMPOUND {
         H5T_STRING {
            STRSIZE H5T_VARIABLE;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         } "deviceRole";
         H5T_STD_U64LE "frameId";
         H5T_VLEN { H5T_STD_U8LE} "data";
         H5T_STD_I64LE "timestamp_ns";
         H5T_STD_U64LE "height";
         H5T_STD_U64LE "width";
         H5T_STD_U64LE "bitDepth";
         H5T_STD_U64LE "format";
         H5T_STD_U64LE "encoding";
         H5T_VLEN { H5T_COMPOUND {
            H5T_STRING {
               STRSIZE H5T_VARIABLE;
               STRPAD H5T_STR_NULLTERM;
               CSET H5T_CSET_ASCII;
               CTYPE H5T_C_S1;
            } "name";
            H5T_STRING {
               STRSIZE H5T_VARIABLE;
               STRPAD H5T_STR_NULLTERM;
               CSET H5T_CSET_ASCII;
               CTYPE H5T_C_S1;
            } "value";
         }} "additionalInformation";
      }
      DATASPACE  SIMPLE { ( 1 ) / ( H5S_UNLIMITED ) }
      DATA {
      (0): {
            "TOTO",
            4294967295,
            (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            140734018973984,
            18446744071819729358,
            21975,
            0,
            0,
            65535,
            ({
                  "TOTOTOTOTOOT",
                  "TATATATATAT"
               }, {
                  "TYTYTYYTYTYTYTT",
                  "TUTUTUTUTUTTUUTUT"
               })
         }
      }
   }
}
}
```

Note that when my vlen array named "additionalInformation" is empty, I seem to be having the issue mentioned in #2083, when it is not empty, I have the error mentioned above.

Here is my system configuration:
 * Operating System : Ubuntu 20.04.2 
 * Python version : 3.8
 * Where Python was acquired : pip
 * h5py version : h5py==3.6.0
 * HDF5 version libhdf5-103/focal,now 1.10.4+repack-11ubuntu1 amd64 [installed,automatic]
 * The full traceback/stack trace shown (if it appears)
 <KeysViewHDF5 ['image']>
Segmentation fault (core dumped)

Summary of the h5py configuration
---------------------------------

h5py    3.6.0
HDF5    1.12.1
Python  3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.22.3
cython (built with) 0.29.24
numpy (built against) 1.17.3
HDF5 (built against) 1.12.1

**Comment by takluyver** [comment]
Variable length data and compound datatypes are two of the more complex and extra-feature-y bits that h5py tries to support. So when you have a vlen string within a compound datatype within a vlen array within another compound datatype, it doesn't really surprise me that you hit some bugs. Even though these are all things HDF5 *can* technically do, the combination is quite a long way from what it's really best at.

If you get to design the file structure, I'd suggest making more use of HDF5 groups and attributes for structuring the data, and make each individual dataset simpler.

**Comment by repagh** [comment]
I don't know if this is the exact same cause, but I am seeing the same problem with a fixed-length, null-terminated string, in a compound in a vlen array.
