### ISSUE TITLE
Clarify behavior of File.copy and Group.copy

### ISSUE THREAD

**Issue by ma-sadeghi** [h5py/h5py#2086]
I'm trying to copy an `h5` file to another `h5` file. But, after doing so, it seems that I get an extra folder level. Here's my code:

```python
f = h5py.File(fname_src, "r")
g = h5py.File("test.h5", "w")

group = "/conv3d_17"
group_id = g.require_group(group)

f.copy(f"{group}", group_id)

print(f["/conv3d_17/conv3d_17/bias:0"])
print(g["/conv3d_17/conv3d_17/conv3d_17/bias:0"])
```

and here's the output:

```bash
<HDF5 dataset "bias:0": shape (512,), type "<f4">
<HDF5 dataset "bias:0": shape (512,), type "<f4">
```

So, basically, my dataset is the same in both files, but it's buried under one extra layer of `/conv3d_17`

I'm very likely doing something wrong, would really appreciate it if you could help me with this.

```
Summary of the h5py configuration
---------------------------------

h5py    3.6.0
HDF5    1.12.1
Python  3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:59) 
[GCC 10.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.21.6
cython (built with) 0.29.24
numpy (built against) 1.19.5
HDF5 (built against) 1.12.1
```

**Comment by tacaswell** [comment]
This is the expected behavior.  https://docs.h5py.org/en/stable/high/group.html?highlight=copy#h5py.Group.copy is a bit ambigious, but the docstring on `File.copy` is clear:

```
 When the destination is a Group object, by default the target will
 be created in that group with its current name (basename of obj.name).
 You can override that by setting "name" to a string.
```

We need to make user that docstring shows up in the built docs and copy the clear language to the `Group.copy` docstring.

**Comment by ma-sadeghi** [comment]
@tacaswell Thank you so much, I made the fixed you proposed and sure enough, it is fixed now!
