### ISSUE TITLE
Check compression and chunks option of existing h5py files?

### ISSUE THREAD

**Issue by tijiang13** [h5py/h5py#2096]
Hi, I wonder if it's possible to check the compression and chunks option of an existing h5py file?

**Comment by ajelenak** [comment]
Compression and chunking are features of individual HDF5 datasets in an HDF5 file, but not entire HDF5 file. With that clarified... whether an HDF5 dataset is chunked is reported by [`h5py.Dataset.chunks`](https://docs.h5py.org/en/stable/high/dataset.html#h5py.Dataset.chunks).

Regarding dataset compression, is there any specific information you are interested in?
