### ISSUE TITLE
OSError: Unable to open file (file signature not found) While Saving .pb Model as .pbtxt

### ISSUE THREAD

**Issue by ashroice** [h5py/h5py#2098]
Windows 10
 Python 3.7.13
 Python on Google Colab
h5py    3.1.0
HDF5    1.12.0
Python  3.7.13 (default, Apr 24 2022, 01:04:09) 
[GCC 7.5.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.21.6
cython (built with) 0.29.21
numpy (built against) 1.14.5
HDF5 (built against) 1.12.0
 
So I recently created a machine learning model with Keras and saved it using the save_model function into a .pb file. I want to use this model with OpenCV, and therefore have been trying to obtain a .pbtxt file to use alongside the DNN module of OpenCV (net = cv2.dnn_DetectionModel(weightsPath,configPath)). Yet for some reason, I keep getting the error in the title: OSError: Unable to open file (file signature not found).

**What I've done**: I've been saving the model on Google Colab, so I've tried restarting the runtime a couple of times. I've made sure my file path was correct. I'm not sure how to check if the .pb file is corrupted, but I don't imagine it is since I directly downloaded it from Keras.

This is the code below:
```
model.save('mymodel5',save_format='pb')
loaded_model = tf.keras.models.load_model('/content/drive/MyDrive/grade1.pb')
import cv2 
cv2.dnn.writeTextGraph(loaded_model, 'graph.pbtxt')
```

This is the **full error traceback**:
[/usr/local/lib/python3.7/dist-packages/h5py/_hl/files.py](https://localhost:8080/#) in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    188         if swmr and swmr_support:
    189             flags |= h5f.ACC_SWMR_READ
--> 190         fid = h5f.open(name, flags, fapl=fapl)
    191     elif mode == 'r+':
    192         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (file signature not found)

**Comment by ajelenak** [comment]
Are you sure that your .pb file is actually an HDF5 file? Your code specifically states to use the “pb” format on save but doesn’t do the same on load.

**Comment by ashroice** [comment]
Fixed this issue - linked to the folder generated by Keras in the save_model function instead of just the saved_model.pb file.
