### ISSUE TITLE
Query: do read events circumvent conventional H5D "open" API?

### ISSUE THREAD

**Issue by tylerjereddy** [h5py/h5py#2107]
I'm working on another open source project that assumes that calls to `H5Dread()` are normally preceded by calls to `H5Dopen*()` or `H5Dcreate*()`. I'm wondering if the proxy code via `dset_rw()` in `h5py/_proxy.pyx` allows `h5py` to "circumvent" this conventional route?

For example, the following code appears to call `H5Dread()` via `dset_rw()` without using the traditional `H5Dopen*()` or creation symbols/functions--does that sound right?

For this code--assume the files have already been written by running the script once, and then we only use the read code on the second running:

```python
from mpi4py import MPI
import numpy as np
from numpy.testing import assert_array_equal
import h5py

def main():
    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()

    # round trip HDF5 IO test
    file_path = f"./test_rank_{rank}.hdf5"
    n_bytes = 10 * (rank + 1)

    bytes_to_write = np.ones(shape=n_bytes, dtype=np.int8)

    #with h5py.File(file_path, "w") as f:
        #f.create_dataset("dataset", data=bytes_to_write)

    print("before h5py.File()! on rank:", rank)
    with h5py.File(file_path, "r") as g:
        print("after h5py.File()! on rank:", rank)
        retrieved_data = np.asarray(g['dataset'])
        print("after retrieved_data on rank:", rank)
        assert_array_equal(retrieved_data, bytes_to_write)

if __name__ == "__main__":
    main()

```

Debug prints seem to only capture `H5Dread()` without prior opens and I was just hoping to confirm if I'm correct here (see below). The reason I care about this is that I'm trying to assess the usage of the HDF5 API in a profiling library over in https://github.com/darshan-hpc/darshan/pull/750.

```Creating a new File in h5py!
before h5py.File()! on rank: 0
Creating a new File in h5py!
after h5py.File()! on rank: 0
Creating a new File in h5py!
before calling dset_rw in read() method of DatasetID!
before H5Dread in _proxy.pyx checkpoint A!
dset number: 360287970189639680
ret from H5Dread: 0
after retrieved_data on rank: 0
```

**Comment by aragilar** [comment]
It looks like we use [H5Oopen](https://confluence.hdfgroup.org/display/HDF5/H5O_OPEN) in the high level API, see https://github.com/h5py/h5py/blob/cff8537cc74a4897e2c0dc523309be17bec06dd4/h5py/h5o.pyx#L184-L190 and https://github.com/h5py/h5py/blob/cff8537cc74a4897e2c0dc523309be17bec06dd4/h5py/_hl/group.py#L279-L301. So I guess the answer to your question depends on what you mean by "circumvent".

**Comment by tylerjereddy** [comment]
Thanks, I've confirmed that `H5Oopen` does indeed get called for the above control flow. That is most helpful to know, I don't think it was aniticipated downstream, but that's for us to deal with :)
