### ISSUE TITLE
[Question] Is there a way to save a dataset of strings of different size?

### ISSUE THREAD

**Issue by vasole** [h5py/h5py#2115]
Is this the intended behavior for datasets? (As it can be seen everything is fine with attributes)

![image](https://user-images.githubusercontent.com/5636251/175060449-9a5107cf-2a23-49dc-abe1-ff3fbb03ca32.png)

 * Operating System Windows 10
 * Python version 3.9
 * Where Python was acquired python.org
 * h5py version 3.7.0
 * HDF5 version 1.12.2
 * The full traceback/stack trace shown (if it appears)

**Comment by woutdenolf** [comment]
Something like this?

```python
import numpy
import h5py

list_of_strings = ["1", "12", "123"]
nxchar = h5py.special_dtype(vlen=str)
list_of_strings = numpy.array(list_of_strings, dtype=nxchar)

with h5py.File("test.h5", "w") as f:
    f["list_of_strings"] = list_of_strings
    f["list_of_strings"].attrs["list_of_strings"] = list_of_strings
```

**Comment by vasole** [comment]
I was doing that in the past, but it does not seem to work. I continue to read bytes.

![image](https://user-images.githubusercontent.com/5636251/175076086-48ce47f8-7525-4841-97d3-863d02741c27.png)

**Comment by woutdenolf** [comment]
Ah sorry yes, to read back you will always get bytes since h5py 3.5

https://docs.h5py.org/en/stable/high/dataset.html#h5py.Dataset.asstr

**Comment by vasole** [comment]
OK. Thanks. I will check in my code for the presence of the `asstr` method in the returned dataset.

**Comment by takluyver** [comment]
> Ah sorry yes, to read back you will always get bytes since h5py 3.5

It was actually 3.0 where that changed. See [breaking changes in 3.0](https://docs.h5py.org/en/stable/whatsnew/3.0.html#breaking-changes-deprecations) and [strings in HDF5](https://docs.h5py.org/en/stable/strings.html).
