### ISSUE TITLE
DatasetID.get_chunk_info() spend much longer than expected

### ISSUE THREAD

**Issue by li779** [h5py/h5py#2117]
My program would like to extract checksum produced by Fletcher32 filter and I was able to do it by following this post https://forum.hdfgroup.org/t/accessing-fletcher32-checksum/7299. 
However, there is some severe performance issue involving get_chunk_info() when I tried out files with some very large datasets in it. In my case, time spent in extracting chunk information takes ~40 times than time spent in file stream seeking the checksum position and read the checksum. It is quite bizarre to me because I would imagine get_chunk_info() should spend less than, or at least on the same scale of, memory access. 
It would be very helpful if anyone can provide some insight to how get_chunk_info() works and any suggestion for improvement. Thanks!

**Comment by ajelenak** [comment]
Can you share more information about the chunk shapes? How many chunks have the datasets with slow performance?

If you can build Docker images, try this: https://github.com/HDFGroup/hdf-docker/tree/master/storage-info. Try with the `-i` option, that should be faster.

**Comment by takluyver** [comment]
The program you followed on the HDF5 forum uses h5py's [Python file like object support](https://docs.h5py.org/en/stable/high/file.html#python-file-like-objects), which is somewhat fragile, and could well be inefficient: each time HDF5 needs to access the underlying file, it has to call back to Python again.

If you're doing that, I would suggest that you open the file twice instead - once in h5py, and once as a regular Python file handle. I.e.:

```python
# Replace this (from HDF forum):
with open('test.h5', 'rb') as stream:
    with h5py.File(stream, 'r') as f:
        ds = f['data']

# With this:
with open('test.h5', 'rb') as stream:
    with h5py.File('test.h5', 'r') as f:
        ds = f['data']
```

It might be something else altogether, but this is worth a try.

**Comment by li779** [comment]
Thanks for the reply! I have around 54844 Chunks per dataset and each chunk is 8 kb in single dimension. I will give a try with the Docker image.

**Comment by li779** [comment]
Thanks for your reply @takluyver. However, it turns out to be something else. I don't see much improvement on that.

**Comment by li779** [comment]
Thanks a lot. Is it possible to disclose the next official release date?

**Comment by ajelenak** [comment]
HDF5 release schedule is now regularly updated [here](https://github.com/HDFGroup/hdf5/#release-schedule). The current estimate for 1.14.0 release is end of this year.
