### ISSUE TITLE
regression: python range not accepted as FancySelection

### ISSUE THREAD

**Issue by ezavod** [h5py/h5py#2118]
I have an old project that relies on using python's built-in ranges as indices/selections.
For h5py versions < 3.0 this worked without an issue but since 3.0 (including latest master 50dfb96) it causes the reported crash (see end of the issue).

I believe the breaking change happened in #1526 - [here](https://github.com/h5py/h5py/commit/474ef53d2698f6fa8988df2a2ec99525863bc8c4#diff-a09e4221f2b07266b57d60d5bfd924721adbf123e85a8dd4222b4c5079898de6L78-R85) to be precise.
Previously, an internal exception was triggered and `args[0] == range(..)` was parsed by a `FancySelection`.
Now, the parsing is done by the `Selector` which [does not account for ranges anywhere](https://github.com/h5py/h5py/blob/474ef53d2698f6fa8988df2a2ec99525863bc8c4/h5py/_selector.pyx#L64-L206).
This is not listet as a breaking change in the [changelog](https://docs.h5py.org/en/latest/whatsnew/3.0.html#breaking-changes-deprecations).

A quick fix would be to do something like:
```diff
diff --git a/h5py/_selector.pyx b/h5py/_selector.pyx
index 1b06e75e..83c400fe 100644
--- a/h5py/_selector.pyx
+++ b/h5py/_selector.pyx
@@ -169,8 +169,8 @@ cdef class Selector:
                 continue
 
             # [[0, 2, 10]] - list/array of indices ('fancy indexing')
-            if isinstance(a, (list, np.ndarray)):
-                if isinstance(a, list) and len(a) == 0:
+            if isinstance(a, (list, range, np.ndarray)):
+                if isinstance(a, (list, range)) and len(a) == 0:
                     a = np.asarray(a, dtype=np.intp)
                 else:
                     a = np.asarray(a)
```
<hr>

To assist reproducing bugs, please include the following:
 * OS: Debian Buster
 * Python version 3.7.3 (from system package manager)
 * h5py version 3.0.0 and 3.7.0
 * HDF5 version 1.10.4+repack-10 (from package manager)
 * The test file `test.py` (adapted from [docs for Datasets](https://docs.h5py.org/en/3.0.0/high/dataset.html#reading-writing-data)) and traceback:

```python
import h5py

print(h5py.__version__)

f = h5py.File('mytestfile.hdf5', 'w')
dset = f.create_dataset("MyDataset", (10,10,10), 'f')
dset[range(0, 4)]
```

```python
>>> python3 test.py 
3.0.0
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    dset[range(0, 4)]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.7/dist-packages/h5py/_hl/dataset.py", line 774, in __getitem__
    selection = sel.select(self.shape, args, dataset=self)
  File "/usr/local/lib/python3.7/dist-packages/h5py/_hl/selections.py", line 82, in select
    return selector.make_selection(args)
  File "h5py/_selector.pyx", line 269, in h5py._selector.Selector.make_selection
  File "h5py/_selector.pyx", line 210, in h5py._selector.Selector.apply_args
TypeError: Simple selection can't process range(0, 4)
 ```

**Comment by tacaswell** [comment]
Interesting.  My initial reaction is "that ever worked?!" and inclined to consider that it did work an undocumented implementation detail rather than part of the API.  It looks like that usage it looks like slice (either spelled `0:4` or `slice(0, 4)`) would be a better option than `range`.

That said the counter argument is that (to my surprise)  `range` works on numpy arrays:

```

In [1]: import numpy as np

In [2]: a = np.arange(12)

In [3]: a[range(0, 5)]
Out[3]: array([0, 1, 2, 3, 4])

In [4]: 

```

and we claim that dataset slicing matches numpy slicing so we should.

**Comment by tacaswell** [comment]
Good first issue because there is no API design and there is a proposed patch.

In addition to this change, the tests that make sure we match numpy behavior need to be updated to also test support for using `range` .

**Comment by ezavod** [comment]
Thanks for the quick response. I'm glad that this is not considered an undocumented implementation detail and I don't have to change our code thoroughly.

**Comment by tacaswell** [comment]
I still would advise you change you code, using slice will likely improve your performance.

**Comment by takluyver** [comment]
Is there any scenario where it actually makes sense to use range() for selection? I think you can always express the same thing with a slice, and it will be more efficient (because the code isn't using the more complex 'fancy indexing' pathway). So I'd be inclined to leave it out and push people towards using slice() instead.

**Comment by tacaswell** [comment]
Fair, but I'm inclined to militantly stick to "do what numpy does"

**Comment by aragilar** [comment]
I wonder if the reason `range` works in numpy is numpy either implicitly or explicitly converts all iterators passed in into tuples/lists/arrays, and then does the normal slicing? #2119 hardcodes `range` in, perhaps it should be doing whatever conversion numpy is?

**Comment by tacaswell** [comment]
I think I prefer the targeted fix (which also makes clear in the code why it is) rather than overhauling how we do the casting.

**Comment by takluyver** [comment]
I'm still -0.5 on 'fixing' this. AFAICT, there is always a simple fix in calling code (replace `range` with `slice`) which will also make it more efficient and flexible (you can index with a slice on one axis and an array on another, but not with range & array). The change happened in a major release, which is the usual way of signalling 'some existing code may break'. And it's been this way for 2 years and 9 h5py releases by this point, so I imagine that most people affected by it have already fixed their code.

So, I'm unlikely to hit merge myself. But I also don't object strongly enough to complain if someone else does. :wink:

**Comment by takluyver** [comment]
Or if we do change it, let's check for the more generic `collections.abc.Sequence`, which would also cover #1757.
