### ISSUE TITLE
h5py 3.7.0 writes unreadable files

### ISSUE THREAD

**Issue by cwiede** [h5py/h5py#2120]
Hi,

I'm very sorry to report a diffuse issue here and I know that there is probably not enough information for reproducing this issue. However - because this has cost me a lot of time and my "solution" is to go back to 3.6.0 - I thought I'd create this issue anyways.

I'm modifying an existing .h5 file on a USB disk with the following pattern:

    with h5py.File(filename, "r+") as f:
          # modify datasets in f with dtype:
          # dtype({'names':['content','_data_timestamp','_receive_timestamp','_global_index'], 'formats':['O','<i8','<i8','<u8'], 'offsets':[0,16,24,32], 'itemsize':40})
          # content is a pretty large binary buffer stored as variable-length uint8 array and the shape of the dataset itself is variable as well
          # all in all the original file size was 12 GB and after modifying the file size has been doubled
          for sname in stream_names:
                for i in len( f["streams"][sname] ):
                      frame = f["streams"][sname][i:i+1].copy()
                      # modify frame[0]["content"]
                      frame[0]["content"] = newcontent
                      f["streams"][sname][i:i+1] = frame
                      f.flush()

Note that the original code was more straightforward (just one item was extracted instead of the slice, the copy was missing, etc).

The script runs through smoothly, no errors are reported. However, when h5repack'ing the modified files, I get segmentation faults for some of the modified files. Also, I can't read all of those files with h5py itself (this results in exceptions about heap allocation errors). This happens for about 25% of the files and when re-running the modify-scripts on these files, most of these files seem to be readable again (so it is not a deterministic issue).

In the end, I was left with one file of 40 which was always resulting in errors (~10 times in a row). Therefore I tried with version 3.6.0 of h5py and with that version, it has been working immediately.

Here are the version details:

h5py    3.6.0
HDF5    1.12.1
Python  3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.21.6
cython (built with) 0.29.24
numpy (built against) 1.14.5
HDF5 (built against) 1.12.1

h5py    3.7.0
HDF5    1.12.2
Python  3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.21.6
cython (built with) 0.29.30
numpy (built against) 1.14.5
HDF5 (built against) 1.12.2

**Comment by tacaswell** [comment]
Did you install our wheels or build locally?

If you built locally, could you try with h5py 3.7 and hdf5 1.12.1?

What version of the hdf5 CLI tools were you using?

What is the filesystem of the usb disk?  Does it work if you copy it to an internal harddrive?

**Comment by cwiede** [comment]
> Did you install our wheels or build locally?
I used the wheels from pypi.

> What version of the hdf5 CLI tools were you using?
I tried on windows version 1.12.2 and I also tried on linux version 1.10.4 (the one that comes with the distri).

> What is the filesystem of the usb disk? Does it work if you copy it to an internal harddrive?
the filesystem is reported as exFAT. I didn't try on the internal harddrive because of space issues. Maybe I find some time today for this.

**Comment by cwiede** [comment]
Just found some time for more testing. On the external drive, the issue is also present with 3.6.0. The error when reading the file with h5py is
    
      File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
      File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
      File "C:\Projects\iCV-Algo\O3R\workspace\py3\lib\site-packages\h5py\_hl\dataset.py", line 793, in __getitem__
        self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
      File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
      File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
      File "h5py\h5d.pyx", line 192, in h5py.h5d.DatasetID.read
      File "h5py\_proxy.pyx", line 140, in h5py._proxy.dset_rw
    OSError: Can't read data (bad global heap collection signature)

I tried with an internal disk and indeed it seems that the error doesn't happen anymore there. However, 

    chkdsk /R /X /offlinescanandfix 

doesn't find any issues on that disk.

**Comment by takluyver** [comment]
> On the external drive, the issue is also present with 3.6.0. 

> I tried with an internal disk and indeed it seems that the error doesn't happen anymore there.

Just to check, does this mean it's working OK on the internal drive with both versions of h5py, and the error can occur with both versions on the external drive? If so, that sounds like your USB stick is at fault, even if the Windows chkdsk tool doesn't detect any errors.

**Comment by cwiede** [comment]
Yes I was thinking the same. I'm closing the issue now thanks for commenting.
