### ISSUE TITLE
 fatal error: mpi.h: No such file or directory

### ISSUE THREAD

**Issue by xxLovy** [h5py/h5py#2121]
Can't find mpi when compiling h5py from source, but I have installed openmpi using command `sudo apt-get install libopenmpi-dev`.

 * Operating System Ubuntu: 22.04 LTS
 * Python version: 3.10.4
 * h5py version: 3.7.0
 * The full traceback/stack trace shown:
xuan@xuan-virtual-machine:~/h5py$ sudo python3 -m pip install -v .
[sudo] password for xuan:
Using pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
Processing /home/xuan/h5py
  Running command pip subprocess to install build dependencies
  Ignoring Cython: markers 'python_version < "3.8"' don't match your environment
  Ignoring Cython: markers 'python_version == "3.8"' don't match your environment
  Collecting setuptools
    Using cached setuptools-63.2.0-py3-none-any.whl (1.2 MB)
  Collecting wheel
    Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
  Collecting oldest-supported-numpy
    Using cached oldest_supported_numpy-2022.5.28-py3-none-any.whl (3.9 kB)
  Collecting pkgconfig
    Using cached pkgconfig-1.5.5-py3-none-any.whl (6.7 kB)
  Collecting Cython>=0.29.15
    Using cached Cython-0.29.30-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
  Collecting numpy==1.21.6
    Using cached numpy-1.21.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (15.9 MB)
  Installing collected packages: wheel, setuptools, pkgconfig, numpy, Cython, oldest-supported-numpy
  Successfully installed Cython-0.29.30 numpy-1.21.6 oldest-supported-numpy-2022.5.28 pkgconfig-1.5.5 setuptools-63.2.0 wheel-0.37.1
  WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  running egg_info
  warning: no files found matching 'AUTHORS'
  no previously-included directories found matching 'docs/_build'
  no previously-included directories found matching 'docs_api/_build'
  warning: no previously-included files matching '.DS_Store' found under directory '*'
  warning: no previously-included files found matching 'ci'
  warning: no previously-included files found matching 'other'
  warning: no previously-included files found matching '.github'
  warning: no previously-included files matching '*' found under directory 'ci'
  warning: no previously-included files matching '*' found under directory 'other'
  warning: no previously-included files matching '*' found under directory '.github'
  warning: no previously-included files found matching '*.yml'
  warning: no previously-included files found matching '*.yaml'
  warning: no previously-included files matching '__pycache__' found under directory '*'
  warning: no previously-included files matching '*.py[co]' found under directory '*'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.coverage_dir'
  warning: no previously-included files matching '*' found under directory '.coverage_dir'
  warning: no previously-included files found matching '.mailmap'
  warning: no previously-included files found matching 'github_deploy_key_h5py_h5py.enc'
  warning: no previously-included files found matching 'rever.xsh'
  no previously-included directories found matching 'news'
  writing manifest file 'h5py.egg-info/SOURCES.txt'
  Getting requirements to build wheel ... done
  Running command Preparing metadata (pyproject.toml)
  running dist_info
  creating /tmp/pip-modern-metadata-dqs3tzk6/h5py.egg-info
  writing manifest file '/tmp/pip-modern-metadata-dqs3tzk6/h5py.egg-info/SOURCES.txt'
  warning: no files found matching 'AUTHORS'
  no previously-included directories found matching 'docs/_build'
  no previously-included directories found matching 'docs_api/_build'
  warning: no previously-included files matching '.DS_Store' found under directory '*'
  warning: no previously-included files found matching 'ci'
  warning: no previously-included files found matching 'other'
  warning: no previously-included files found matching '.github'
  warning: no previously-included files matching '*' found under directory 'ci'
  warning: no previously-included files matching '*' found under directory 'other'
  warning: no previously-included files matching '*' found under directory '.github'
  warning: no previously-included files found matching '*.yml'
  warning: no previously-included files found matching '*.yaml'
  warning: no previously-included files matching '__pycache__' found under directory '*'
  warning: no previously-included files matching '*.py[co]' found under directory '*'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.coverage_dir'
  warning: no previously-included files matching '*' found under directory '.coverage_dir'
  warning: no previously-included files found matching '.mailmap'
  warning: no previously-included files found matching 'github_deploy_key_h5py_h5py.enc'
  warning: no previously-included files found matching 'rever.xsh'
  no previously-included directories found matching 'news'
  writing manifest file '/tmp/pip-modern-metadata-dqs3tzk6/h5py.egg-info/SOURCES.txt'
  Preparing metadata (pyproject.toml) ... done
Collecting numpy>=1.14.5
  Using cached numpy-1.23.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.0 MB)
Building wheels for collected packages: h5py
  Running command Building wheel for h5py (pyproject.toml)
  running bdist_wheel
  running build
  running build_py
  running build_ext
  Loading library to get build settings and version: /home/xuan/hdf5/install/lib/libhdf5.so
  ********************************************************************************
                         Summary of the h5py configuration

  HDF5 include dirs: [
    '/home/xuan/hdf5/install/include'
  ]
  HDF5 library dirs: [
    '/home/xuan/hdf5/install/lib'
  ]
       HDF5 Version: (1, 13, 2)
        MPI Enabled: False
   ROS3 VFD Enabled: False
  DIRECT VFD Enabled: False
   Rebuild Required: True

  ********************************************************************************
  Executing cythonize()
  [ 1/24] Cythonizing /home/xuan/h5py/h5py/_conv.pyx
  [ 2/24] Cythonizing /home/xuan/h5py/h5py/_errors.pyx
  [ 3/24] Cythonizing /home/xuan/h5py/h5py/_objects.pyx
  [ 4/24] Cythonizing /home/xuan/h5py/h5py/_proxy.pyx
  [ 5/24] Cythonizing /home/xuan/h5py/h5py/_selector.pyx
  [ 6/24] Cythonizing /home/xuan/h5py/h5py/defs.pyx
  [ 7/24] Cythonizing /home/xuan/h5py/h5py/h5.pyx
  [ 8/24] Cythonizing /home/xuan/h5py/h5py/h5a.pyx
  [ 9/24] Cythonizing /home/xuan/h5py/h5py/h5ac.pyx
  [10/24] Cythonizing /home/xuan/h5py/h5py/h5d.pyx
  [11/24] Cythonizing /home/xuan/h5py/h5py/h5ds.pyx
  [12/24] Cythonizing /home/xuan/h5py/h5py/h5f.pyx
  [13/24] Cythonizing /home/xuan/h5py/h5py/h5fd.pyx
  [14/24] Cythonizing /home/xuan/h5py/h5py/h5g.pyx
  [15/24] Cythonizing /home/xuan/h5py/h5py/h5i.pyx
  [16/24] Cythonizing /home/xuan/h5py/h5py/h5l.pyx
  [17/24] Cythonizing /home/xuan/h5py/h5py/h5o.pyx
  [18/24] Cythonizing /home/xuan/h5py/h5py/h5p.pyx
  [19/24] Cythonizing /home/xuan/h5py/h5py/h5pl.pyx
  [20/24] Cythonizing /home/xuan/h5py/h5py/h5r.pyx
  [21/24] Cythonizing /home/xuan/h5py/h5py/h5s.pyx
  [22/24] Cythonizing /home/xuan/h5py/h5py/h5t.pyx
  [23/24] Cythonizing /home/xuan/h5py/h5py/h5z.pyx
  [24/24] Cythonizing /home/xuan/h5py/h5py/utils.pyx
  x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DH5_USE_18_API -DNPY_NO_DEPRECATED_API=0 -I./h5py -I/home/xuan/hdf5/install/include -I/home/xuan/h5py/lzf -I/home/xuan/h5py/lzf/lzf -I/tmp/pip-build-env-ccg1nn33/overlay/local/lib/python3.10/dist-packages/numpy/core/include -I/usr/include/python3.10 -c /home/xuan/h5py/h5py/defs.c -o build/temp.linux-x86_64-3.10/home/xuan/h5py/h5py/defs.o
  In file included from /home/xuan/hdf5/install/include/hdf5.h:22,
                   from /home/xuan/h5py/h5py/api_compat.h:27,
                   from /home/xuan/h5py/h5py/defs.c:761:
  /home/xuan/hdf5/install/include/H5public.h:66:10: fatal error: mpi.h: No such file or directory
     66 | #include <mpi.h>
        |          ^~~~~~~
  compilation terminated.
  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
  error: subprocess-exited-with-error
 
  × Building wheel for h5py (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
 
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/bin/python3 /usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpxfcmu17s
  cwd: /home/xuan/h5py
  Building wheel for h5py (pyproject.toml) ... error
  ERROR: Failed building wheel for h5py
Failed to build h5py
ERROR: Could not build wheels for h5py, which is required to install pyproject.toml-based projects

`h5py.version.info` contains the needed versions, which can be displayed by
```
python -c 'import h5py; print(h5py.version.info)'
```
where `python` should be substituted for the path to python used to install
`h5py` with.

**Comment by MoonpieQ** [comment]
Have you tried `export C_INCLUDE_PATH=/usr/lib/openmpi/include`?

see: https://github.com/h5py/h5py/issues/216#issuecomment-15173983
