### ISSUE TITLE
Missing per-release docs on docs.h5py.org since 3.3.0

### ISSUE THREAD

**Issue by Repentinus** [h5py/h5py#2122]
Up until version 3.2.1, h5py used to upload per-release documentation to [Read the Docs](https://readthedocs.org/projects/h5py/). Since 3.3.0, this has no longer been done. As a consequence, users of affected releases can no longer browse the documentation online. Furthermore, distribution packagers have to build the documentation from scratch, instead of simply fetching the compressed archive for the relevant release from Read the Docs.

**Comment by takluyver** [comment]
I've just activated versions 3.3 to 3.7 on RTD. I thought it did this automatically, but seemingly not.

I also made a few of the older versions hidden. This means links to them will still work, but they won't be linked by RTD, and it will stop search engines indexing them.

**Comment by Repentinus** [comment]
Thanks! For some reason, 3.7.0 is still missing from the [downloads](https://readthedocs.org/projects/h5py/downloads/). It can be browsed online and the intervening versions are available both for download and for browsing online.

**Comment by takluyver** [comment]
I don't know how to fix that, I'm afraid. I just manually triggered another build of the docs for 3.7.0, but it only seems to build the HTML, and I don't see any option to build another format.

**Comment by Repentinus** [comment]
I suspect the culprit is somehow fcaca1d1b81d25c0d83b11d5bdf497469b5980e9. The 3.6.0 release predates it and there are clear differences in the build logs for [3.6.0](https://readthedocs.org/projects/h5py/builds/17519415/) and [3.7.0](https://readthedocs.org/projects/h5py/builds/17528229/).
