### ISSUE TITLE
Can't load object references saved by C++

### ISSUE THREAD

**Issue by jsiegle** [h5py/h5py#2123]
I am using a custom C++ program to generate HDF5 files, and then reading them in using `h5py`. Everything works as expected, except for reading datasets that contain an array of object references. The datatype and array size of these datasets appear correct when queried with `h5py`, but dereferencing always throws an error (see below).

The code I'm using to create the dataset is based on this example: https://bitbucket.hdfgroup.org/projects/HDFFV/repos/hdf5-examples/browse/1_12/C/H5T/h5ex_t_objref.c

Is there any obvious reason why these references wouldn't work on the Python side? Are there any checks I can run on the C++ side to ensure that the references are valid? 

#### Traceback:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-67-34062917b110> in <module>
----> 1 f[ref]

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

~\Miniconda3\envs\hdf5-test\lib\site-packages\h5py\_hl\group.py in __getitem__(self, name)
    299 
    300         if isinstance(name, h5r.Reference):
--> 301             oid = h5r.dereference(name, self.id)
    302             if oid is None:
    303                 raise ValueError("Invalid HDF5 object reference")

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\h5r.pyx in h5py.h5r.dereference()

KeyError: 'Unable to open object by token (address of object past end of allocation)'
```

#### Additional info:
 * Operating System: Windows 10
 * Python version: 3.8.5
 * Where Python was acquired: Miniconda
 * h5py version: 3.6.0
 * HDF5 version: 1.12.1

**Comment by takluyver** [comment]
> Are there any checks I can run on the C++ side to ensure that the references are valid?

You can call the [`H5Rdereference`](https://portal.hdfgroup.org/display/HDF5/H5R_DEREFERENCE) function. This is exactly what h5py is calling:

https://github.com/h5py/h5py/blob/50dfb964a9b318cf50f98f0879aba5e8a1c2c6b4/h5py/h5r.pyx#L82

If it initially works in the C++ code, try closing the file and reopening it, then reading the reference.

**Comment by jsiegle** [comment]
Thanks, this was helpful for troubleshooting!

I realized that the references were fine on the C++ side; the issue was that when calling `H5Dwrite` I was passing a pointer to the reference container, rather than the underlying array.

I'm still not able to save the full reference array to the dataset -- only the first reference is valid. However, I'm fairly certain the issue is with my C++ code, and doesn't have anything to do with `h5py`.
