### ISSUE TITLE
Add Dataset.is_scale() method?

### ISSUE THREAD

**Issue by ajelenak** [h5py/h5py#2125]
The Dataset class currently has `make_scale()` method but lacks a check if an HDF5 dataset is a dimension scale. Hence, I propose to add an `is_scale()` method. It would be a shortcut for:
```python
h5ds.is_scale(self._id)
```
Any objections?

**Comment by mullenkamp** [comment]
This would definitely be great.
What is currently the best way to check if a dataset is a scale?

**Comment by ajelenak** [comment]
@mullenkamp Thanks! This issue has been quiet for some time, I agree with you obviously.

The current way to check is what I outlined in the first comment, something like this:
```python
import h5py.h5ds

# If ds is an h5py.Dataset object...
h5py.h5ds.is_scale(ds._id)
```

**Comment by mullenkamp** [comment]
Oh! Thanks for that! I was originally a little confused by that one line.
That seems much better than my attempt which queries the attrs.
