### ISSUE TITLE
Support for configuring chunk cache per dataset

### ISSUE THREAD

**Issue by ajelenak** [h5py/h5py#2126]
Configuring dataset chunk cache is currently only supported at the file level, which means the same cache settings apply to all datasets in a file. This may cause excessive memory consumption for large number of datasets. I propose to allow configuring chunk cache per dataset as well. These settings override the file-level ones.

These three methods: `Dataset.open_dset()`, `Group.require_dataset()`, and `Group.create_dataset()`, should get `rdcc_nslots`, `rdcc_nbytes`, and `rdcc_w0` keyword arguments. Then modify `Dataset.make_new_dset()` accordingly.

Is this proposal acceptable? If yes, I will create a PR to track code changes.

**Comment by tacaswell** [comment]
Yes, seems reasonable to me.

**Comment by ajelenak** [comment]
Closed via #2127.
