### ISSUE TITLE
The behavior to query a cell array in MATLAB .mat files

### ISSUE THREAD

**Issue by Tianfeng-Lu** [h5py/h5py#2130]
To assist reproducing bugs, please include the following:
h5py    3.3.0
HDF5    1.10.6
Python  3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.20.3
cython (built with) 0.29.24
numpy (built against) 1.16.6
HDF5 (built against) 1.10.6

---

I am using h5py to read and manipulate the .mat file with v7.3. When I tempt to visit an element in an array that consists of cell arrays, I have to locate the content in an inconvenient way via [<HDF5 object reference>] as follows. So I add a method in class Dataset(HLObject) in file dataset.py to improve the behaviour and make it compatible with the original index way. Since it is a change in the package original code, I wonder whether it worth a pull request.
For example, 
```
data['Obj']['Units'] # an array with cell arrays elements
data[data['Obj']['Units'][0][0]]['trials'] # visit the member 'trials' in the first cell array
data['Obj']['Units'].query_cell(0)['trials'] # the equivalent expression
```
in the file dataset.py, 
```
    def query_cell(self, index):
        return self.parent[self[int(index)][0]]
```

**Comment by takluyver** [comment]
I guess this 'cell array' is some matlab concept? I'm not familiar with the term in HDF5.

My own view is that h5py provides a decent API to HDF5 files, and I'd rather not complicate that with things specifically for the contorted way that Matlab uses HDF5. Perhaps there's room for a separate package built on top of h5py specifically aimed at working with `.mat` files?

**Comment by Tianfeng-Lu** [comment]
Thanks for your reply! I am going to build a small wrapper to support reading the .mat files in python, since the other solutions convert MATLAB files to dict object, which is usually slow and do not support the cell arrays. Perhaps this issue can help others with the same problem.

**Comment by takluyver** [comment]
Thanks, please do drop a link here when there's something for people to try! :+1:
