### ISSUE TITLE
Long loading times of compound datasets when accessing fields with `np.asarray()`

### ISSUE THREAD

**Issue by tobiasjj** [h5py/h5py#2144]
I work in a team for a company and help to develop a Python package to analyze scientific data produced from devices. Recently, we stumbled over a major performance issue, when loading large compound datasets when accessing them via `np.asarray(dset.fields("FieldA"))`. We need to access it with `np.asarray()` for reasons. We figured out, that this is caused by `np.asarray()` iterating over all datapoints of the data via the `__getitem__()` method, as the `FieldsWrapper` object (returned by `fields()`) does not provide an `__array__()` method.

A simple solution would be to add the `__array__()` method to the `FieldsWrapper` class. I'm wondering if there is a specific reason behind the `FieldsWrapper` class not implementing the `__array__()` method or if it would be possible to add it? I would be happy to contribute. Should I open a PR?

What do you think?

**Comment by takluyver** [comment]
My expectation when I added FieldsWrapper was that you'd do `dset.fields("FieldA")[:]` to get a NumPy array. But I don't see any issue with adding a `__array__` method as well.
