### ISSUE TITLE
Add __array__() method to AstypeWrapper and AsStrWrapper

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#2152]
To support things like `np.asarray(dset.astype(np.int32))` and `np.asarray(dset.asstr())`.

See #2151 (doing the same for `dset.fields()`) for an example of what this will involve.

**Comment by ethanotran** [comment]
Can I work on this? Looking to make my first contribution to open source.

**Comment by takluyver** [comment]
Yes, please do! Have a look at PR #2151 for an example, and the [contributing docs](https://docs.h5py.org/en/stable/contributing.html#how-to-get-your-code-into-h5py), and feel free to ask if you have any questions.

**Comment by aragilar** [comment]
Closed via #2269.
