### ISSUE TITLE
Package(s) not found: h5py

### ISSUE THREAD

**Issue by rcpeene** [h5py/h5py#2158]
* Operating System: Windows 10
 * Python version: Python 3.9
 * Where Python was acquired: conda environment
 * h5py version: not installed
 * HDF5 version: unknown

I tried to install h5py via conda-forge using the following commands described [here](https://pynwb.readthedocs.io/en/stable/tutorials/advanced_io/streaming.html#sphx-glr-download-tutorials-advanced-io-streaming-py) for data analysis of .nwb files using ros3.

This is the output from my conda shell;
```
(base) C:\Users\carter.peene\Desktop\Projects\openscope_jupyterhubs>pip uninstall h5py
WARNING: Skipping h5py as it is not installed.

(base) C:\Users\carter.peene\Desktop\Projects\openscope_jupyterhubs>conda install -c conda-forge "h5py>=3.2"
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Retrieving notices: ...working... done

(base) C:\Users\carter.peene\Desktop\Projects\openscope_jupyterhubs>pip show h5py
WARNING: Package(s) not found: h5py
```

Am I missing something with installation?

**Comment by ajelenak** [comment]
Did you try `conda list`?

**Comment by rcpeene** [comment]
Here's the relevant portion of my conda list output.
```
# packages in environment at C:\Users\carter.peene\Miniconda3:
#
# Name                    Version                   Build  Channel
.
.
.
fonttools                 4.37.4                   pypi_0    pypi
fqdn                      1.5.1                    pypi_0    pypi
frozenlist                1.3.1                    pypi_0    pypi
fscacher                  0.2.0                    pypi_0    pypi
fsspec                    2022.8.2                 pypi_0    pypi
glib                      2.69.1               h5dc1a3c_1
gst-plugins-base          1.18.5               h9e645db_0
gstreamer                 1.18.5               hd78058f_0
hdf5                      1.10.6               h1756f20_1
hdmf                      3.4.6                    pypi_0    pypi
humanize                  4.4.0                    pypi_0    pypi
icc_rt                    2022.1.0             h6049295_2
icu                       58.2             vc14hc45fdbb_0  [vc14]  anaconda
idna                      3.3                pyhd3eb1b0_0
imageio                   2.22.1                   pypi_0    pypi
importlib-metadata        5.0.0                    pypi_0    pypi
intel-openmp              2021.4.0          haa95532_3556
interleave                0.2.1                    pypi_0    pypi
ipydatawidgets            4.3.2                    pypi_0    pypi
```

**Comment by ajelenak** [comment]
Did you try installing with just `h5py` instead of `h5py>=3.2`?

**Comment by rcpeene** [comment]
That worked, but it installed version 2.10.0 and unfortunately I need a newer version.

**Comment by rcpeene** [comment]
However, it looks like the original commands specified above (uninstalling and then installing via condaforge) work now. Odd behavior.

**Comment by ajelenak** [comment]
I think you not only need to specify the `conda-forge` channel but also say to be  used first. These are two commands to execute for that:
```
$ conda config --add channels conda-forge
$ conda config --set channel_priority strict
```

**Comment by rcpeene** [comment]
As a result I have received a very long list of package conflicts and h5py was not installed.

**Comment by kmuehlbauer** [comment]
Worth to note that installing in base environment is not recommended. @rcpeene you would need to create another environment apart from base, where you install your wanted packages.

**Comment by tacaswell** [comment]
I'm going to close this because there in nothing we can do upstream to address this sort of problem and it seems to have resolved itself.

I agree with @ajelenak and @kmuehlbauer, the best path here is to fully remove conda and start from scratch always using an environment.  Packaging is in general hard and using two package managers on the same set of files is multiplicatively (not additatively) hard.  There is a huge variety of ways that it can all go sideways and it is almost always faster to start from scratch than to try to recover a busted environment.
