### ISSUE TITLE
How select colomns in compound dataset for virtualDataset

### ISSUE THREAD

**Issue by Cdriko** [h5py/h5py#2159]
Hello

I want to create a dataset from colomns from a compound original dataset (that it will grow during an experience).

But I don't know exactly how selecting a compound colomn.
The attached code doesn't work at the line : 

`
layout[0, :h5py.h5s.UNLIMITED] = dataSource[0:h5py.h5s.UNLIMITED]["frequency"]
`

with
`
TypeError: Simple selection can't process 'frequency'
`

Anybody can help me to find the good syntax ?
I don't find anything about this case in the [documentation](https://support.hdfgroup.org/HDF5/docNewFeatures/NewFeaturesVirtualDatasetDocs.html).
Thanks

Summary of the h5py configuration
---------------------------------

h5py    3.4.0
HDF5    1.12.1
Python  3.9.6 (default, Aug 18 2021, 19:38:01) 
[GCC 7.5.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.20.3
cython (built with) 0.29.24
numpy (built against) 1.19.3
HDF5 (built against) 1.12.1

**Comment by rmvanhees** [comment]
I am not sure why you use h5py.h5s.UNLIMITED (on the right-side), you simply want to read all the data, thus [:] would do.
The syntax:  dataSource.fields("frequency")[:] is slightly faster.

Regards, Richard

**Comment by takluyver** [comment]
As far as I know, this isn't possible: virtual datasets don't have any way to store a field name within a compound dataset.
