### ISSUE TITLE
Variable length strings take a lot of space on-disk

### ISSUE THREAD

**Issue by ivirshup** [h5py/h5py#2162]
## Description

Variable length strings take up a large amount of space on disk.

Upstream of scverse/anndata#822 scverse/anndata#830 (cc: @ilia-kats)

### vlen strings lead to larger files

```python
import h5py
import numpy as np

strings = np.array("the quick brown fox jumps over the lazy dog".split(), dtype=object)
data = np.random.choice(strings, 1_000_000)

with h5py.File("vlen_strings.h5", "w") as f:
    str_dtype = h5py.string_dtype("utf-8")
    f.create_dataset("string-array", data=data.astype(str_dtype), dtype=str_dtype, compression="gzip")

with h5py.File("fixed_len_strings.h5", "w") as f:
    max_len = int(np.vectorize(len)(data).max())
    str_dtype = h5py.string_dtype("utf-8", max_len)
    f.create_dataset("string-array", data=data.astype(str_dtype), dtype=str_dtype, compression="gzip")

!du -hs *
```

```
712K	fixed_len_strings.h5
 25M	vlen_strings.h5
```

### vlen strings are not as effected by compression

```python
with h5py.File("vlen_strings_no_compression.h5", "w") as f:
    str_dtype = h5py.string_dtype("utf-8")
    f.create_dataset("string-array", data=data.astype(str_dtype), dtype=str_dtype)

with h5py.File("fixed_len_strings_no_compression.h5", "w") as f:
    max_len = int(np.vectorize(len)(data).max())
    str_dtype = h5py.string_dtype("utf-8", max_len)
    f.create_dataset("string-array", data=data.astype(str_dtype), dtype=str_dtype)

!du -hs *.h5
```

```
712K	fixed_len_strings.h5
4.8M	fixed_len_strings_no_compression.h5
 25M	vlen_strings.h5
 38M	vlen_strings_no_compression.h5
```

### Details

From this old piece of hdf5 docs, each vlen element in an array seems to take an additional 32 bytes of info: https://docs.hdfgroup.org/archive/support/HDF5/doc/TechNotes/VLTypes.html

That piece of documentation isn't in the current docs, but I'm not sure what to make of that since the size seems to work out.

The hdf5 docs do have an [RFC about inefficiencies of variable length data types](https://docs.hdfgroup.org/hdf5/rfc/var_len_data_sketch_design_190715.pdf), [but it doesn't seem like there has been any progress made towards implementation](https://forum.hdfgroup.org/t/variable-length-data-in-hdf5-sketch-rfc-status)

#### A theory

My suspicion here is that that 32 bytes per element is not being compressed. I'm hoping that this is an oversight in h5py, and not a fundamental limitation of hdf5. I have trouble figuring out if this is the case from the hdf5 docs.

### Version info

<details>
<summary> Version info  </summary>

```
Summary of the h5py configuration
---------------------------------

h5py    3.7.0
HDF5    1.12.2
Python  3.9.12 (main, Mar 26 2022, 15:52:10) 
[Clang 13.0.0 (clang-1300.0.29.30)]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.22.4
cython (built with) 0.29.30
numpy (built against) 1.19.3
HDF5 (built against) 1.12.2
```

</details>

**Comment by ivirshup** [comment]
Thanks for info. Should this just get closed then?

> 3. Consider the sharded (cloud-native) HDF5 format

I had not realized they were also changing the format for this. Seems like it could be useful to "backport". Our use of HDF5 is largely around data compatibility with other languages, so changes not in the typical wrapped implementation could be an issue.

**Comment by ajelenak** [comment]
> Should this just get closed then?

I think so, I'll do it now.

**Comment by jreadey** [comment]
Yes, HSDS has a native sharded format (though it can read regular HDF5 files as well).

Here's an example of the script using HSDS:
```

import h5pyd as h5py
import numpy as np

strings = np.array("the quick brown fox jumps over the lazy dog".split(), dtype=object)
data = np.random.choice(strings, 1_000_000)

with h5py.File("/home/john/vlen_strings_no_compression.h5", "w") as f:
    str_dtype = h5py.string_dtype("utf-8")
    f.create_dataset("string-array", data=data.astype(str_dtype), dtype=str_dtype)

with h5py.File("/home/john/fixed_len_strings_no_compression.h5", "w") as f:
    max_len = int(np.vectorize(len)(data).max())
    str_dtype = h5py.string_dtype("utf-8", max_len)
    f.create_dataset("string-array", data=data.astype(str_dtype), dtype=str_dtype)
```

With the original version, I got this:

```
$ du -h *.h5
4.8M	fixed_len_strings_no_compression.h5
39M	vlen_strings_no_compression.h5
```

With the HSDS version I get:
```

$ hsls -H -v /home/john/
john                                                folder   2022-07-14 17:51:02 /home/john/
john                                    4.8M        domain   2022-10-12 18:37:52 /home/john/fixed_len_strings_no_compression.h5
john                                    7.5M        domain   2022-10-12 18:37:49 /home/john/vlen_strings_no_compression.h5
```

The sharded version of the HDF5 used the same amount of storage, while there was a bit of inflation with the variable strings, but not too bad.   HSDS stores variable length chunks as a 4- byte element length, followed by the element, next element length, etc.
