### ISSUE TITLE
Fixed size string attributes UTF8 encoded are returned as bytes

### ISSUE THREAD

**Issue by sdebionne** [h5py/h5py#2172]
```bash
$ python -c 'import h5py; print(h5py.version.info)'

Summary of the h5py configuration
---------------------------------

h5py    2.10.0
HDF5    1.10.5
Python  3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:57:06)
[GCC 9.4.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.21.4
```

With a variable-size string attribute (`STRSIZE  = H5T_VARIABLE`)

```bash
$ h5dump -A /tmp/output_0_00000.h5
HDF5 "/tmp/output_0_00000.h5" {
GROUP "/" {
   ATTRIBUTE "creator" {
      DATATYPE  H5T_STRING {
         STRSIZE H5T_VARIABLE;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_UTF8;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "LIMA2-1.0.0"
      }
   }
...
```

return a `str`:

```py
In [0]: h5py.File("/tmp/output_0_00000.h5").attrs["creator"]

Out[0]: 'LIMA2-1.0.0'


```

while a fixed-size string attribute (`STRSIZE = 12`)

```bash
$ h5dump -A /tmp/output_0_00000.h5
HDF5 "/tmp/output_0_00000.h5" {
GROUP "/" {
   ATTRIBUTE "creator" {
      DATATYPE  H5T_STRING {
         STRSIZE 12;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_UTF8;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "LIMA2-1.0.0"
      }
   }
```

return `bytes`:

```py
In [0]: h5py.File("/tmp/output_0_00000.h5").attrs["creator"]
Out[0]: b'LIMA2-1.0.0'
```

I believe this is an issue.

**Comment by takluyver** [comment]
I believe this is [as documented](https://docs.h5py.org/en/stable/strings.html):

> Variable-length strings in attributes are read as `str` objects.

We could explicitly say in that page that fixed-length strings in attributes are kept as bytes, but this is what we decided in #1338, not a bug.

There is no 'right' mapping between string types in HDF5 and Python. I'd rather not rehash all the details again, so please take my word as a maintainer whose life would be easier if there was one. :wink: h5py has some heuristics, but obviously they won't be right for everyone. I hope we can agree that it's good for h5py to be consistent between versions, even if the behaviour it's sticking with isn't the one you prefer.

**Comment by sdebionne** [comment]
Sorry to reopen a difficult subject then!

>We could explicitly say in that page that fixed-length strings in attributes are kept as bytes, but this is what we decided in https://github.com/h5py/h5py/issues/1338, not a bug.

Indeed, I think that would be an improvement to mention that *fixed-length strings in attributes, even if UTF8 encoded, are kept as bytes* in the documentation, as the mapping is not so intuitive (at least from the  C API perspective).

In #1338,  in the "3. Reading data" section , "UTF-8 Fixed -> numpy 'S' (tagged with UTF-8 encoding)". Why would reading attributes be different? Again, attributes written from the C API with `H5T_CSET_UTF8`, must currently be vlen string attributes (when vlen is not necessary) to get a `str` in Python.

**Comment by takluyver** [comment]
> In #1338, in the "3. Reading data" section , "UTF-8 Fixed -> numpy 'S' (tagged with UTF-8 encoding)". Why would reading attributes be different?

It's not different - numpy's 'S' dtype means bytes (in the same way that str in Python 2 does), and you're getting precisely that:

```
$ h5dump attr-str-test.h5 
HDF5 "attr-str-test.h5" {
GROUP "/" {
   ATTRIBUTE "foo" {
      DATATYPE  H5T_STRING {
         STRSIZE 3;
         STRPAD H5T_STR_NULLPAD;
         CSET H5T_CSET_UTF8;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "bar"
      }
   }
}
}

In [5]: f.attrs['foo']
Out[5]: b'bar'

In [6]: f.attrs['foo'].dtype
Out[6]: dtype('S3')
```
