### ISSUE TITLE
suggested setup.py hack for compiling with mpi4py & py3.11

### ISSUE THREAD

**Issue by filefolder** [h5py/h5py#2173]
hi all, if it solves anyone else's issue:

I am currently using the master of mpi4py (~4.0) and trying to compile h5py for python 3.11 with all the mpi features turned on. since I didn't have mpi4py 3.1.0 it kept trying to download and compile it but there is still the issue in that version where it doesn't know `longintrepr.h` is in the `cython` part of `user/include/python3.11`. I believe this is now fixed in mpi4py 3.1.4+

anyway, long story short but I had to edit setup.py to use at least mpi4py 3.1.4 if compiling with python3.11

it is probably not very robust if using python 3.10 or something but it seems to work ok otherwise

```
if setup_configure.mpi_enabled():
    RUN_REQUIRES.append('mpi4py >=3.0.2')
    SETUP_REQUIRES.append("mpi4py ==3.0.2; python_version<'3.8'")
    SETUP_REQUIRES.append("mpi4py ==3.0.3; python_version=='3.8.*'")
    SETUP_REQUIRES.append("mpi4py ==3.1.0; python_version=='3.9'")   *** change to ==
    SETUP_REQUIRES.append("mpi4py >=3.1.4; python_version>='3.11'")  *** add this line
```

**Comment by takluyver** [comment]
I made a PR: #2213.
