### ISSUE TITLE
Reading H5PY is very slow

### ISSUE THREAD

**Issue by LiuCMU** [h5py/h5py#2174]
To assist reproducing bugs, please include the following:
 * Operating System: Ubuntu 18.04.5 LTS
 * Python version: 3.9
 * Where Python was acquired: Anaconda
 * h5py version: 3.6.0
 * HDF5 version: 1.10.6

Hey, I find it's very slow to read groups using H5PY. Here is my H5PY object, which contains about 40,000 groups:
```
self.h5 = h5py.File(os.path.join(folder, "molecules", "AEV00001.h5"), "r")  #initialize the h5py in a class
```
Each group contains two numpy arrays, which I'm reading as follows:
```
group = self.h5[acid_key]  #access the group in a class method
species = group["species"][:]
aevs = np.squeeze(group["aevs"][:], axis=0)
```

However, I can only read about 10 groups per second. This took about 1.5 hours to read every group from the h5py object. I wanser if this was the expected speed, or if I did something wrong. Thank you very much!

**Comment by tacaswell** [comment]
I'm going to close this because there is nothing we can do at the h5py layer.
