### ISSUE TITLE
Nested context managers exit early? Possible bug in fid comparison? 

### ISSUE THREAD

**Issue by root-11** [h5py/h5py#2186]
Good morning,
In the `test.py` below I assumed that nesting of context managers was a valid method, but it turns out that `h5.create_group("2")` fails as `h5py.File` calls `self.close()` when level 2 context manager exits:

```
# test.py
import os
import pathlib
import h5py
import tempfile

def test_h5_context_mgr():
    x = pathlib.Path(tempfile.gettempdir()) / "decafbad.h5"
    h5py.File(x, "w").close()

    with h5py.File(x, "r+") as h5:      # enter level 1.
        h5.create_group("1")  
        with h5py.File(x, "r+") as h5:  # enter level 2.
            h5.create_group("1.1")  
                                        # exit level 2.
        h5.create_group("2")  # this should fail if level 2 exit closes the h5 session.
    
    os.remove(x)
```

I also see that upon entry the `self.id`s are unique:

level 1: 72057594037927937
level 2: 72057594037927938

Which I presume should make the sessions unique.

However during the exit from level 2 where the check is in place with `self.id`:

```
    @with_phil
    def __exit__(self, *args):
        if self.id:
            self.close()
```
Both fid-handles are closed.

Did I miss something?

```
h5py    3.7.0
HDF5    1.12.2
Python  3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.23.4
cython (built with) 0.29.30
numpy (built against) 1.21.6
HDF5 (built against) 1.12.2
Python source: python.org/downloads
```

**Comment by root-11** [comment]
This kind of sub-classing seems to do the job:

```
class HDF5(h5py.File):
    sessions = {}
    session_depth = {}

    def __init__(self, name, mode="r", **kwargs):
        self.key = name, mode
        if self.key not in self.sessions:
            if not pathlib.Path(name).exists():  # make it.
                h5py.File(name, TRUNCATE).close()
            super().__init__(name, mode, **kwargs)
            self.sessions[self.key] = super().__enter__()
            self.session_depth[self.key] = 0

    def __enter__(self):
        self.session_depth[self.key] += 1
        return self.sessions[self.key]

    def __exit__(self, *args):
        self.session_depth[self.key] -= 1
        if self.session_depth[self.key] == 0:
            super().__exit__(*args)

        if self.session_depth[self.key] < 0:
            super().__exit__(*args)
            raise KeyError
```

As this test now passes:
```
def test_h5_context_mgr():
    x = pathlib.Path(tempfile.gettempdir()) / "decafbad.h5"

    with HDF5(x, "r+") as h5:
        h5.create_group("1")  # enter level 1.
        with HDF5(x, "r+") as h5:
            h5.create_group("1.1")  # enter level 2.
        h5.create_group("2")  # this should fail if level 2 exit closes the h5 session.

        with HDF5(x, "r+") as h5:
            del h5["1.1"]  # testing if a nested del can close all sessions
        del h5["1"]  # this should fail if previous del closed all sessions
    os.remove(x)
```

**Comment by tacaswell** [comment]
My first question is _why_ you want to do this.

I think the problem here is related to Python variable scoping.  If we change the example to:

```python

# test.py
import os
import pathlib
import h5py
import tempfile

def test_h5_context_mgr():
    x = pathlib.Path(tempfile.gettempdir()) / "decafbad2.h5"
    h5py.File(x, "w").close()

    with h5py.File(x, "r+") as h5_1:      # enter level 1.
        h5_1.create_group("1")  
        with h5py.File(x, "r+") as h5_2:  # enter level 2.
            h5_2.create_group("1.1")  
                                        # exit level 2.
        h5_1.create_group("2")  # this should fail if level 2 exit closes the h5 session.

    os.remove(x)

test_h5_context_mgr()    

```

it works as expected.  In the OP's code, the inner level File object was replacing the out level and after exiting the inner code block `h5` is still the object from the inner context which correctly reports that it is closed.  I think if we un-roll this it is clearer

```python

x = pathlib.Path(tempfile.gettempdir()) / "decafbad4.h5"
h5py.File(x, "w").close()
f1 = h5py.File(x, "r+")
print(f'{f1.id.id=}')
f1.create_group("1")
f2 = h5py.File(x, "r+")
print(f'{f2.id.id=}')
f2.create_group("1.1")
f2.close()
del f2
f1.create_group("2") 
```

If you want to make a context manager like this I would not sub-class from `File`, but create the `File` objects as needed (has-a over is-a).  As proposed, your context manager class has a path where if you create one of these objects outside of a context manager they are very not `File` like (as `super().__init__(...)` does not get run).

**Comment by root-11** [comment]
Hi Thomas

> _why_ you want to do this?

A fair question :-)

In maintain tablite, which uses h5py for tabular data.

The HDF5 storage is used in a hierarchy where tables refer to columns (t:c) and columns refer to pages (c:p) and pages contain the data (hdf5 native values + typecodes)

As copies of tables are common user operations, for example appending one table to another, tablite only copies the metadata, e.g. the t:c:p relationship.

When deleting a table, the relationship t:c:p is traversed to (a) reduce reference count to determine when a page no longer is needed and can be deleted. This requires (in pseudocode):

```
for each table_to_be_deleted:
	for each column in table:
		for each page in column:
			reduce ref count
			if ref count is zero:
				delete page
		delete column
	delete table
```

Although all of this is within a single "transaction" I need to __enter__ and __exit__ multiple times.

One could argue that the functions for `delete page`, `delete column` and `delete table` should be constructed with a single h5py.File(...) open in the beginning of the file and a close() at the end of the file, but that would either mean passing the filehandle around, or duplicating code.

Here is the is a snippet from the DRY implementation:

```
def delete_column(path, column_key):
    # delete the column reference.
    with HDF5(path) as h5:
        pages = get_pages(path, column_key)
        for page in pages:
            rc = decrement_ref_count(page)
            if rc == 0:
                delete_page(path, page)
        del h5[f"/column/{column_key}"]  # deletes the virtual dataset.


def delete_page(path, page):
    assert isinstance(page, Page)
    if ref_count(page) != 0:
        raise ValueError("Reference count > 0")
    with HDF5(path) as h5:
        dset = h5[page.group]
        if dset.attrs["datatype"] == "typearray":
            del h5[f"{page.group}_types"]
        del h5[page.group]


def delete_table(path, table_key):
    with HDF5(path) as h5:
        group = f"/table/{table_key}"
        saved_flag = h5[group].attrs["saved"]
        if saved_flag:
            return
        columns = json.loads(h5[group].attrs["columns"])
        for _, column_key in columns.items():
            delete_column(path, column_key)
        del h5[group]
```

which uses my h5py.File override:

```

""" H5PY.File OVERRIDE """


class HDF5(h5py.File):
    sessions = {}
    session_depth = {}

    def __init__(self, name, mode="r+", **kwargs):
        if not isinstance(name, str):
            raise TypeError
        self.key = name, mode
        if self.key not in self.sessions:
            if not pathlib.Path(name).exists():  # make it.
                h5py.File(name, "w").close()
            super().__init__(name, mode, **kwargs)
            self.sessions[self.key] = super().__enter__()
            self.session_depth[self.key] = 0

    def __enter__(self):
        self.session_depth[self.key] += 1
        return self.sessions[self.key]

    def __exit__(self, *args):
        self.session_depth[self.key] -= 1
        if self.session_depth[self.key] == 0:
            del self.session_depth[self.key]
            del self.sessions[self.key]
            super().__exit__(*args)

```

**Comment by root-11** [comment]
Updated comment above.

**Comment by tacaswell** [comment]
In this implementation you are passing a file path around which seems much worse to me than passing around a `File` (well, really `Group`) object.  The choice to use a file path bakes in a realtionship with a file system very strongly (e.g. I suspect it will make interop with h5pyd at least difficult and prevent the usage of the buffer-backed Files).  Taking in `Group` objects would also let you put more than one data set in the same hdf5 file (if you make your paths relative).

I would strongly suggest having your functions take in `h5py` objects and either manage your file open/close once outside or write a decorator that looks something like [completely untested!]

```python
import functools
import contextlib
import h5py

def ensure_h5py_object(func):
    @functools.wraps(func)
    def inner(maybe_file, *args, **kwargs):
        with contextlib.exitstack() as stack:
            if not isinstance(maybe_file, h5py.Group):
                file = stack.enter_context(h5py.File(maybe_file))
            else:
                file = maybe_file
           return func(file, *args, **kwargs)


@ensure_h5py_object
def delete_table(h5, table_key):
    group = f"/table/{table_key}"
    saved_flag = h5[group].attrs["saved"]
    if saved_flag:
        return
    columns = json.loads(h5[group].attrs["columns"])
    for _, column_key in columns.items():
        delete_column(path, column_key)
    del h5[group]

```


But if you do not like any of those suggestions, I still _strongly_ discourage you from sub-classing `File` in that way.  There is a path through the `__init__` where the `super().__init__` is _not_ called.  Given that you are only using this as a context manager you avoid that problem but it is better to just be honest that you are writing a custom context manager to manage a global registry of open hdf5 files ;)

**Comment by root-11** [comment]
Hi Thomas,
Thank you for your recommendation. For now I've refactored to avoid subclassing:

```
""" h5py.File session manager """


class HDF5(object):
    """A context manager tracking h5py.File object sessions.
    """
    sessions = {}  # __enter__()
    handles = {}  # fh = h5py.File(....)
    session_depth = {}  # int > 0

    def __init__(self, name, mode='r+', **kwargs) -> None:
        self.key = name, mode
        if not isinstance(name, str):
            raise TypeError
        self.key = name, mode
        if self.key not in self.sessions:
            if not pathlib.Path(name).exists():  # make it.
                h5py.File(name, "w").close()

            self.handles[self.key] = fh = h5py.File(name, mode, **kwargs)
            self.sessions[self.key] = fh.__enter__()
            self.session_depth[self.key] = 0

    def __enter__(self):
        self.session_depth[self.key] += 1
        return self.sessions[self.key]

    def __exit__(self, *args):
        self.session_depth[self.key] -= 1
        if self.session_depth[self.key] == 0:
            fh = self.handles[self.key]
            fh.__exit__(*args)
            fh.close()
            del self.session_depth[self.key]
            del self.sessions[self.key]
            del self.handles[self.key]

```

I've looked at `contextlib.ContextDecorator` and `contextlib.ExitStack` this afternoon, but need to accustome myself a bit more. The examples are very abstract to me (I'm a mathematician and python is just my calculator).


You write that:

> In this implementation you are passing a file path around which seems much worse to me than passing around a File (well, really Group) object. The choice to use a file path bakes in a realtionship with a file system very strongly (e.g. I suspect it will make interop with h5pyd at least difficult and prevent the usage of the buffer-backed Files).

Within the context of a "transaction" the file path (`str`) just travels from the outermost context manager. It could just as well have been an id or a pointer. Using the `str` just makes it easy to check which h5-file the program is interacting with.

Between the transactions, the files may be different. And as the decorators would require the filename as an arg, I can't get it to work without passing it around.

So, as the context manager already is initialised and just sitting on the class variable, there are no loose ends: For the duration of the transaction, it is opened once and closed upon exit from the outermost level. 

I would also try follow your advice if I had another way to keep `group`-objects open, but as majority of algorithms in tablite (data import, join, lookup, filter, ...) use multiprocessing for speeding things up, subprocesses will compete to obtain the write Lock on the file from the OS. Hence that also works against me. This is despite that __main__ plans the work and completely controls where each of the sub proc are supposed to write - totally avoiding conflicts - but they will still need obtain "write access".

This has led me to a design using the context manager where I enter, perform transaction, and exit.

If you know a better way please share. I'm all ears.

**Comment by tacaswell** [comment]
> Within the context of a "transaction" the file path (str) just travels from the outermost context manager. It could just as well have been an id or a pointer. Using the str just makes it easy to check which h5-file the program is interacting with.

The `h5py.File` / `h5py.Group` objects _are_ exactly that id or pointer.  If for debugging you want to know what the path is you can ask the `h5py` objects.

I do not really know your domain or scope and breaking rule 0 of performance tuning (benchmark before you talk), I would be a bit skeptical of aggressively opening and closing hdf5 files (I have seen factors of 10 speed up by moving file opening/closing out of a tight loop).

If you are concerned about performance are you being careful about doing chunk aligned reads and writes?


------


This discussion has now gotten away from your initial issue and veered into an un-solicited design review of your project (sorry!).

Can you confirm that:

```python

# test.py
import os
import pathlib
import h5py
import tempfile

def test_h5_context_mgr():
    x = pathlib.Path(tempfile.gettempdir()) / "decafbad2.h5"
    h5py.File(x, "w").close()

    with h5py.File(x, "r+") as h5_1:      # enter level 1.
        h5_1.create_group("1")  
        with h5py.File(x, "r+") as h5_2:  # enter level 2.
            h5_2.create_group("1.1")  
                                        # exit level 2.
        h5_1.create_group("2")  # this should fail if level 2 exit closes the h5 session.

    os.remove(x)

test_h5_context_mgr()    

```

works for you and if so can we close this issue as I do not think there is anything we can do in h5py to address this issue.

**Comment by root-11** [comment]
Very well. I close the issue then.
