### ISSUE TITLE
Large performance regression on boolean indexing in 3.7.0

### ISSUE THREAD

**Issue by tguruswamy** [h5py/h5py#2189]
We are seeing a very severe performance regression when using boolean indexing between h5py 3.6.0 and 3.7.0.

Bisecting suggests
first bad commit: [b556856819de6fcff7248479c6f42b18af6ced21] Convert boolian arrays into index arrays for fancy slicing

%%timeit of a test script on our data which makes heavy use of boolean indexing with 1-D arrays of length 1e5-1e6 
 
h5py @ 3051c76a:
21.9 s ± 191 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

h5py @ b5568568:
39min 23s ± 26.8 s per loop (mean ± std. dev. of 7 runs, 1 loop each)

RedHat Enterprise Linux 8 Conda environment. Same hdf5 version used for both tests.

Summary of the h5py configuration
---------------------------------
h5py    3.6.0
HDF5    1.10.6
Python  3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.23.4
cython (built with) 0.29.32
numpy (built against) 1.23.4
HDF5 (built against) 1.10.6

**Comment by takluyver** [comment]
*Sigh* Sorry about this. It's a priority error - indexing a 1D dataset with a single boolean array used to fall through the code path in that commit to [this special case](https://github.com/h5py/h5py/blob/b3697ab2ced3342b3462fc3dcd1a11f26af74f1c/h5py/_hl/selections.py#L62-L65). Now that case is being handled by the more general selection code, allowing e.g. a boolean array on one axis and a slice on another, but it's less efficient in the standard case.
