### ISSUE TITLE
ppc64le builds on Travis timing out

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#2199]
Creating an issue as a central place to record the issue and potential ideas. All ppc64le builds on Travis from master appear to be hanging, and then failing with the "No output has been received in the last 10m0s" message. Where it appears to get stuck varies - sometimes it seems to hang during the general setup before it runs anything from our repository.

Weirdly, quite a few pull request builds succeed, but the failure is very consistent on master. :confused: 

https://app.travis-ci.com/github/h5py/h5py/builds

Things we've already tried:

- Removing a recursive `ls` call where it sometimes seemed to be stuck (#2196)
- Using a newer Ubuntu version (#2197) 
- Deleting the cache for the master branch on Travis (via https://app.travis-ci.com/github/h5py/h5py/caches ) and re-running the build

The Travis forum for [multi CPU architectures](https://travis-ci.community/c/environments/multi-cpu-arch/96) contains questions from quite a few people seeing similar things, but I've not yet found any good advice on how to resolve it. There are [some pointers](https://travis-ci.community/t/builds-hang-with-output-truncated-mid-line/7611/14) that not all the output is showing up, so it might actually be getting stuck later than it appears to. Other threads (e.g. [this one](https://travis-ci.community/t/multiarch-builds-lxd-always-time-out-on-failure-instead-of-exit/7659)) say that you should avoid the `set -e` bash option in the main commands that Travis runs - but I don't think we're using that.

Unfortunately, I'm not aware of any other CI platform providing native ppc64le builds. You can use emulated builds on Github actions, but that's likely to be very slow.

**Comment by vasole** [comment]
I'm experiencing the same issue and I have tried newer distributions too.

I have contacted Travis-CI support and they suggested to go back to focal what I have done. However, the problem seems to be still there:

https://app.travis-ci.com/github/vasole/pymca/builds/259446667

**Comment by vasole** [comment]
Just in case, the trouble ticket at Travis is:

https://support.travis-ci.com/hc/en-us/requests/42395

**Comment by vasole** [comment]
It seems to have started now (using focal).

**Comment by takluyver** [comment]
Thanks @vasole ! I guess we can try with focal as well.

**Comment by aragilar** [comment]
It looks like #2200 didn't fix this, should we drop travis for this, and look at https://osuosl.org/? From https://osuosl.org/services/powerdev/current-projects/ it looks like numpy is supported, I'm happy to fill out the form and ask them what's required on our side.

**Comment by takluyver** [comment]
@vasole suggested contacting Travis support, which I have, and I heard back quite quickly (which was something of a pleasant surprise). It's not solved yet, but as they're responding, let's give them at least a few days to see if it gets solved.

**Comment by takluyver** [comment]
Travis support made some changes (including bumping the timeout with no output to 30 minutes) and suggested adding a `sleep 5` to the Travis instructions (#2205). Something in all that seems to have fixed it, though it's not clear to me what or how. I don't think there should be anything in there that takes > 10 minutes with no output (building HDF5 takes a while, but also produces a lot of output).

Hopefully it will keep working :crossed_fingers: . We can reopen this if not.

**Comment by tacaswell** [comment]
> Something in all that seems to have fixed it, though it's not clear to me what or how.

so the default state of CI 🤣
