### ISSUE TITLE
h5py 2.10.0 installation error with poetry 

### ISSUE THREAD

**Issue by archanabhardwaj** [h5py/h5py#2201]
I am trying to install package with poetry install for installation.

* Operating System : linux 
 * Python version 3.9 / conda 
 * 

 But it gives error for h5py package which needs 2.10.0 version of h5py. 

"
Installing dependencies from lock file

Package operations: 35 installs, 6 updates, 0 removals

  • Updating importlib-metadata (4.11.4 -> 6.0.0)
  • Updating numpy (1.18.0 -> 1.18.5): Installing..
  • Updating h5py (3.7.0 -> 2.10.0): Failed

        cmd_obj.run()
          File "/tmp/pip-req-build-al394xe3/setup_build.py", line 161, in run
            from Cython.Build import cythonize
        ModuleNotFoundError: No module named 'Cython'
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for h5py
  Failed to build h5py
  ERROR: Could not build wheels for h5py, which is required to install pyproject.toml-based projects
  

  at ~/.conda/envs/whole2/lib/python3.9/site-packages/poetry/utils/env.py:1540 in _run
      1536│                 output = subprocess.check_output(
      1537│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1538│                 )
      1539│         except CalledProcessError as e:
    → 1540│             raise EnvCommandError(e, input=input_)
      1541│ 
      1542│         return decode(output)
      1543│ 
      1544│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:

  PoetryException

  Failed to install /home/user/.cache/pypoetry/artifacts/67/73/11/59cd898ab55f65d9213500215b00e663dafb02beb2e48301f1ffc078ae/h5py-2.10.0.tar.gz

  at ~/.conda/envs/whole2/lib/python3.9/site-packages/poetry/utils/pip.py:58 in pip_install
       54│ 
       55│     try:
       56│         return environment.run_pip(*args)
       57│     except EnvCommandError as e:
    →  58│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       59│ 

I would appreciate all the suggestions!!

**Comment by takluyver** [comment]
2.10 is quite old now - it was released in 2019, before Python 3.9 came out. The easiest way forwards is probably to use a newer version of h5py.

**Comment by tacaswell** [comment]
> • Updating h5py (3.7.0 -> 2.10.0): Failed


That seems wrong and suggests an issue with either your configuration or poetry.

I'm going to close this because I do not think there is anything we can do on the h5py side to help with this.
