### ISSUE TITLE
Use modify instead of create for existing attributes

### ISSUE THREAD

**Issue by kmuehlbauer** [h5py/h5py#2204]
h5py    3.7.0
HDF5    1.12.2
Python  3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.23.5
cython (built with) 0.29.33
numpy (built against) 1.21.6
HDF5 (built against) 1.12.2

Currently `AttributeManager` `__setitem__`-function calls `create` in any case. Is there any reason not to call `modify` instead? If the attribute doesn't exist it will be created anyway:

https://github.com/h5py/h5py/blob/6cc4c912a97cff4f3a6c133943d573118d795025/h5py/_hl/attrs.py#L222-L249

We've downstream experienced in https://github.com/h5netcdf/h5netcdf/issues/207 (again) this bug: https://github.com/HDFGroup/hdf5/issues/1388. Although we could make this work in `h5netcdf` I'm wondering if these changes should be incorporated directly into `h5py`. Thanks.

If there's interest I can setup a PR.

**Comment by kmuehlbauer** [comment]
I know, I've partly collaborated to that dance.

The problem here is that consecutive `create` will run into the above mentioned hdf5-bug (if track_order=True), even if the user just want to modify the value.

From a users perspective it might look like just changing value but instead a temporary attribute is created, the original attribute gets deleted and the temporary attribute is renamed to the original name. In their use case they are ending up with broken files, since those attributes cannot be deleted anymore.

Anyway, is this something which can be handled in `h5py`? If not I'd work around it downstream. Thanks!

**Comment by aragilar** [comment]
I think if your PR fixes things so it always works (overrides where it needs to, works with `track_order=True`, etc.) and doesn't cause existing code to break, then I think we'd be happy to have it (that is, I can't see why we wouldn't want it, but it's nearly midnight here so I may be missing something).

**Comment by kmuehlbauer** [comment]
Thanks @aragilar, I'll try to come up with something.
