### ISSUE TITLE
H5py broken on the default conda channel

### ISSUE THREAD

**Issue by woutdenolf** [h5py/h5py#2207]
This is not an `h5py` issue. This is directed to the maintainers of `h5py` on the [default conda channel](https://anaconda.org/anaconda/h5py).

## Issue

The h5py package on the [default conda channel](https://anaconda.org/anaconda/h5py) has been broken for all versions since `h5py 3.5`.

## Solution

For `h5py >=3.5` the `hdf5` version should be `>=1.10.7,!=1.12.0`. This is because a change the file locking (can be set per file instead of global).

## Broken packages

For python 3.7 I found that all versions since `3.5` on the `anaconda` channel or broken

| h5py | hdf5    | compatible |
|------|---------|------------|
| 2.10 | 1.10.6  | yes        |
| 3.2  | 1.10.6  | yes        |
| 3.3  | 1.10.6  | yes        |
| 3.5  | 1.10.6* | no         |
| 3.6  | 1.10.6* | no         |
| 3.7  | 1.10.6* | no         |

The `*` means that `hdf5` is a [**constraint**](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#run-constrained), not a [**requirement**](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#run).

**Comment by woutdenolf** [comment]
FYI pypi and conda-forge are fine (at least for the latest versions).

### Pypi (python 3.7)

| h5py | libhdf5 | compatible |
|------|---------|------------|
| 2.8  | 1.10.2  | yes        |
| 2.9  | 1.10.4  | yes        |
| 2.10 | 1.10.4  | yes        |
| 3.0  | 1.12.0  | yes        |
| 3.1  | 1.12.0  | yes        |
| 3.2  | 1.12.0  | yes        |
| 3.3  | 1.12.0  | yes        |
| 3.4  | 1.12.1  | no         |
| 3.5  | 1.12.1  | yes        |
| 3.6  | 1.12.1  | yes        |
| 3.7  | 1.12.2  | yes        |

### Conda-forge (python 3.7)

| h5py | libhdf5 | compatible |
|------|---------|------------|
| 2.8  | 1.10.3  | yes        |
| 2.9  | 1.10.5  | yes        |
| 2.10 | 1.10.6  | yes        |
| 3.1  | 1.10.6  | yes        |
| 3.3  | 1.12.1  | no         |
| 3.4  | 1.12.1  | no         |
| 3.6  | 1.12.1  | yes        |
| 3.7  | 1.12.2  | yes        |

**Comment by tacaswell** [comment]
The wheels vendor a fixed version of h5py so I'm not sure what that table is checking.

Please report this issue at https://github.com/ContinuumIO/anaconda-issues/issues .  I am going to close this here because there is nothing we can do on the h5py side to fix this.

**Comment by woutdenolf** [comment]
The table just represents how `conda install h5py` or `pip install h5py` behaves.
