### ISSUE TITLE
h5py was built without ROS3 support, can't use ros3 driver

### ISSUE THREAD

**Issue by sparkgisvip** [h5py/h5py#2208]
Operating System : Windows 10
Python version : 3.10
h5py version : 
D:\Program Files\Python310>pip uninstall h5py
Found existing installation: h5py 3.7.0

发生异常: ValueError
h5py was built without ROS3 support, can't use ros3 driver
  File "D:\hdf5Test.py", line 71, in read_hdf5
    f = h5py.File(h5_path, 'r', driver='ros3', aws_region=b'xxxxx', secret_id=b'xxxx', secret_key=b'xxxx')

**Comment by ajelenak** [comment]
You can use the s3fs package instead of the ros3 driver. A minimal example:

```python
from s3fs import S3FileSystem

s3 = S3FileSystem(...s3fs options...)
with s3.open('mybucket/myfile.h5', mode='rb') as s3f:
    with h5py.File(s3f, mode='r') as f:
        # Do some work...
        pass
```

**Comment by zyxgis** [comment]
thank you for your help
