### ISSUE TITLE
Can't build h5py-parallel

### ISSUE THREAD

**Issue by EmilyBourne** [h5py/h5py#2222]
I am trying to build h5py in parallel on a system where I have previously successfully done this, but am encountering unexpected errors. I'm not sure if the change is linked to the update to 3.8.0 or an update of the github runners.

# Command
```
export CC="mpicc" HDF5_MPI="ON"
pip install --no-binary=h5py h5py
```

# System (Github Runner)
To assist reproducing bugs, please include the following:
 * Operating System : Ubuntu 22.04
 * Python version : 3.10
 * Where Python was acquired : https://github.com/actions/setup-python
 * h5py version : 3.8.0 (also failing with 3.7.0)
 * HDF5 version :  1.10.7 (https://packages.ubuntu.com/pt/jammy/arm64/libhdf5-openmpi-103) (previously successful with this version)
 * Pip version : 22.3.1 (previously successful with this version)
 * The full traceback/stack trace shown (if it appears)
```
Collecting h5py>=2.8.0<=3.7.0
  Downloading h5py-3.8.0.tar.gz (400 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.8/400.8 kB 93.9 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'error'
  error: subprocess-exited-with-error
  
  × pip subprocess to install backend dependencies did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
      Collecting wheel
        Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
      Collecting mpi4py==3.1.0
        Downloading mpi4py-3.1.0.tar.gz (2.4 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 13.2 MB/s eta 0:00:00
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'error'
        error: subprocess-exited-with-error
      
        × Getting requirements to build wheel did not run successfully.
        │ exit code: 1
        ╰─> [1 lines of output]
            error in mpi4py setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '!=3.4.*''
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error
      
      × Getting requirements to build wheel did not run successfully.
      │ exit code: 1
      ╰─> See above for output.
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

# Extra information
The error seems to be linked to this line: https://github.com/mpi4py/mpi4py/blob/3.1.0/setup.py#L473 which appears in an older version of mpi4py, which I believe is pinned by h5py when using python 3.9 or 3.10 (https://github.com/h5py/h5py/blob/master/setup.py#L45-L50). I am able to successfully instal h5py parallel with Python 3.11 (but cannot use this version due to restrictions in other packages) and Python 3.8.

Here is an example of a run which succeeded 3 weeks ago:
https://github.com/pyccel/pygyro/actions/runs/3881429724/jobs/6620426072

Here is an example which failed today:
https://github.com/pyccel/pygyro/actions/runs/4036510220/jobs/6939153877

**Comment by takluyver** [comment]
Sorry about that. I would guess that a new version of setuptools is checking this more carefully than before. The [release notes](https://setuptools.pypa.io/en/stable/history.html#) for setuptools 67.0 (2022-01-28) say:

> Bump vendored version of [packaging](https://pypi.org/project/packaging) to 23.0 ([pyparsing](https://pypi.org/project/pyparsing) is no longer required and was removed). As a consequence, users will experience a more strict parsing of requirements. Specifications that don’t comply with [PEP 440](https://peps.python.org/pep-0440/) and [PEP 508](https://peps.python.org/pep-0508/) will result in build errors.

In terms of a workaround, you could install a working version of mpi4py and [the other build dependencies](https://github.com/h5py/h5py/blob/c6262ac154210b65ab433f1d8e7687e609c686a4/pyproject.toml#L2-L7) beforehand, and then use pip's `--no-build-isolation` flag to build h5py with those rather than creating a new build env.

As for a proper fix, I'm not sure. We generally specify the oldest compatible mpi4py to build against, because the resulting builds should then work with any newer wheel. We could raise the minimum to 3.1.1 for all Pythons we still support, though that feels like quite a blunt instrument. We could specify a maximum version of setuptools when building with an older mpi4py... no, that doesn't work, mpi4py will get its own build environment. @aragilar can you see a better solution I'm missing?

**Comment by EmilyBourne** [comment]
> In terms of a workaround, you could install a working version of mpi4py and [the other build dependencies](https://github.com/h5py/h5py/blob/c6262ac154210b65ab433f1d8e7687e609c686a4/pyproject.toml#L2-L7) beforehand, and then use pip's --no-build-isolation flag to build h5py with those rather than creating a new build env.

I can confirm that this workaround works correctly. Thank you very much for your quick response!

**Comment by aragilar** [comment]
Bumping to 3.1.1 is probably the better option, given 3.1.1 appears to be a bugfix for this issue.

Another possible workaround if you've got caching set up for the CI, would be to build a wheel for mpi4py 3.1.0 with an older version of setuptools (e.g. in a separate venv) once, and then rely on the wheel cache to avoid needing to create the mpi4py wheel during the h5py build (though that does rely on remembering to invalidate the cache when openmpi changes).

**Comment by shimwell** [comment]
Just catching up on this thread and checking I've understood.

Is the plan to change[ these lines](https://github.com/h5py/h5py/blob/c6262ac154210b65ab433f1d8e7687e609c686a4/setup.py#L46-L49) to specify a minimal version of 3.1.1 and then make a new release of h5py?

**Comment by shimwell** [comment]
Just to confirm the suggested ```--no-build-isolation``` solution worked over [here](https://github.com/openmc-dev/openmc/pull/2370/files#diff-a3c9e97d58fc7b981a97c9244bf3554b1f477a6d6fe050bdfc312810a6f9f327)

**Comment by tylerjereddy** [comment]
Ah, this is affecting us in darshan as well https://github.com/darshan-hpc/darshan/issues/895
