### ISSUE TITLE
Problems with SWMR

### ISSUE THREAD

**Issue by AleNovelli** [h5py/h5py#2238]
Hello,
I am trying to use SWMR as described in [this guide and examples](https://docs.h5py.org/en/stable/swmr.html) but the example scripts provided do not seem to work.
I am using
 * Windows 10
 * Python version 3.9
 * h5py version 3.6.0

This is what I am running as script `a.py`. It just increases the length of the file every second
```
import h5py
import numpy as np
import time

f = h5py.File("swmr.h5", 'w', libver='latest')
arr = np.array([1,2,3,4])
dset = f.create_dataset("data", chunks=(2,), maxshape=(None,), data=arr)
f.swmr_mode = True
# Now it is safe for the reader to open the swmr.h5 file
for i in range(50):
    new_shape = ((i+1) * len(arr), )
    dset.resize( new_shape )
    dset[i*len(arr):] = arr
    dset.flush()
    time.sleep(1)
    # Notify the reader process that new data has been written
```
The script `b.py`, instead just reads the file and prints the length of the data.
```
import h5py

f = h5py.File("swmr.h5", 'r', libver='latest', swmr=True)
dset = f["data"]
while True:
    dset.id.refresh()
    shape = dset.shape
    print( shape )
```

I leave `a.py` running and I also run `b.py`, however, the shape of the array printed on the screen does not change over time.
If, while keeping `a.py` running, I close `b.py` and run it again it will show a new, bigger shape of the array but, as before, it will not change over time.

**Comment by derobins** [comment]
Are you using a local file system? SWMR does not work with network file systems like NFS and Windows SMB shares. It should work with a local NTFS file system. I have no idea if any of the FAT file systems follow POSIX consistency semantics.

**Comment by takluyver** [comment]
I'm going to close this as lacking info, but @derobins gave some possible ideas about causes above. We can reopen it if needed, or you might want to bring the topic up on [the HDF forum](https://forum.hdfgroup.org/) to get more input (h5py just calls HDF5 C functions, so an issue like this is unlikely to be specific to h5py).
