### ISSUE TITLE
Datatypes playing nice with Pylance

### ISSUE THREAD

**Issue by Servinjesus1** [h5py/h5py#2241]
> To assist reproducing bugs, please include the following:
>  * Operating System (Ubuntu 20.04.5 on WSL2 on Win11)
>  * Python version (3.10.9)
>  * Where Python was acquired (conda-forge)
>  * h5py version (3.8.0)
>  * HDF5 version (1.14.0)

Pylance is concerned about getting items from loaded h5 files. I'm not sure how it's concluding that the File is of type Datatype, but because of it, it warns that `__getitem__` method is not defined for Datatypes.

Example code:
```py
def read_hdf(filename, channel=0, tic=1):
    """
    This function simply reads in hdf-formatted data.
    For now, the data is a 1-channel data with no parameters or headers.
    Structure might change.
    The timing info is 1us-based
    """
    f = h5py.File(filename, "r")
    ch1 = np.array(f["1"][f"channel{channel}"]["data"])
    t = np.arange(len(ch1)) * tic

    return t, ch1.astype(float)
```

Error is raised on second code line: `f["1"]` and `f["1"][f"channel{channel}"]` will each give a `Pylance(reportGeneralTypeIssues)` error, as they both have `__getitem__` called on them.

**Comment by ajelenak** [comment]
Have you tried:

```
ch1 = f[f"1/channel{channel}/data"]
```

**Comment by tacaswell** [comment]
This should be reported to pylance, I am inclined to close this issue as h5py does not currently carry any type hints.

**Comment by takluyver** [comment]
> I'm not sure how it's concluding that the File is of type Datatype, but because of it, it warns that `__getitem__` method is not defined for Datatypes.

Could it be checking all the types that `f["1"]` might give you, and warning about the one that doesn't support `__getitem__`? For a static analysis tool, this is kind of right - `f["1"]` on an arbitrary file *might* give you a Datatype, and if it did, `f["1"][f"channel{channel}"]` would be an error. Presumably you have a predictable file structure so `f["1"]` will reliably be a group, but the tool doesn't know that.

You can use `typing.cast` to tell type checkers that you know something will have a specific type:

```python
from typing import cast

g = cast(f["1"], h5py.Group)

ch1 = cast(f[f"1/channel{channel}/data"], h5py.Dataset)[:]
```

Or if you want to check it when the code runs, the type checker should understand `isinstance()` as well.

```python
ds = f[f"1/channel{channel}/data"]
if isinstance(ds, h5py.Dataset):
    ch1 = ds[:]
else:
    raise Exception("This is not a dataset!")
```

**Comment by Servinjesus1** [comment]
@ajelenak that worked! It seems Pylance was ingeniously discovering the type that returns when subscripting a File (Group), and warning that by successive subscripting, I could possibly end up subscripting Datatype. I thought it was much more complicated, and worried that I would need to fully understand h5py before I could phrase the issue report to Pylance.

Thanks for the good methods for sanity checking, @takluyver!
