### ISSUE TITLE
Deprecation warnings coming from use of `numpy.product`

### ISSUE THREAD

**Issue by dstansby** [h5py/h5py#2243]
In tests at sunpy with development versions of various packages installed, we're seeing `DeprecationWarnings` being emitted by `h5py` calling `numpy.product`, which will be deprecated in numpy 1.25. One of them is below, but there might be others.
```python
../../.tox/py311-devdeps/lib/python3.11/site-packages/h5py/_hl/dataset.py:1070: in __array__
    if numpy.product(self.shape, dtype=numpy.ulonglong) == 0:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = ((51,),), kwargs = {'dtype': <class 'numpy.ulonglong'>}

    @array_function_dispatch(_prod_dispatcher, verify=False)
    def product(*args, **kwargs):
        """
        Return the product of array elements over a given axis.
    
        .. deprecated:: 1.25.0
            ``product`` is deprecated as of NumPy 1.25.0, and will be
            removed in NumPy 2.0. Please use `prod` instead.
    
        See Also
        --------
        prod : equivalent function; see for details.
        """
        # 2023-03-02, 1.25.0
>       warnings.warn("`product` is deprecated as of NumPy 1.25.0, and will be "
                      "removed in NumPy 2.0. Please use `prod` instead.",
                      DeprecationWarning, stacklevel=2)
E       DeprecationWarning: `product` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `prod` instead.
```

**Comment by tacaswell** [comment]
I think this is closed by https://github.com/h5py/h5py/pull/2242

**Comment by rayosborn** [comment]
@tacaswell, sorry to revive an issue that should have been fixed a year ago, but I am still getting these deprecation when I run the nexusformat package pytests in Python  v3.12, using h5py v3.11. They don't appear when I run them in Python 3.11, also using h5py v3.11. 

Another puzzle is that h5py seems to be stuck at v3.9 in conda-forge, but that's another issue.

**Comment by neutrinoceros** [comment]
@rayosborn this seems weird. Can you open a new issue and provide more details on your system there ? In particular, please specify which version of numpy you're using as well, and how you installed both numpy and h5py, and try to make sure that you get the same behavior when using fresh environments. Thank you !

**Comment by rayosborn** [comment]
I discovered that I had been running pytest in the base environment with an older version of h5py, even though I launched it in an environment with the latest h5py version. I guess I hadn't explicitly installed pytest in the new environment, and path to the base environment version was still set. Installing pytest fixed the problem. Sorry to waste your time.

**Comment by neutrinoceros** [comment]
No worries, glad to know it works now !

**Comment by tacaswell** [comment]
There was a push to document running the tests as `python -m pytest` to prevent this sort of problem but it is more to type and changes some of the details about how pytest does test discovery.
