### ISSUE TITLE
HDF5 truncation error when opening large file

### ISSUE THREAD

**Issue by mdposkus** [h5py/h5py#2250]
To assist reproducing bugs, please include the following:
 * Operating System Windows: 10
 * Python version: 3.8
 * Where Python was acquired:
 * h5py version: 3.6.0
 * HDF5 version: 1.12.1
 * The full traceback/stack trace shown (if it appears)

When loading a very large HDF5 file by calling the command: h5py.File(filename, "r")
The following error is generated. Presumably my HDF5 file is greater than 2^32-1 in size and the is causing the truncation (I don't think it is coincidence that the truncated eof is 2^32-1). Is there a way to bypass this limitation? I apologize if additional information is needed; I'm not well-versed in python.

  File "h5py\_hl\files.py", line 406, in __init__
  File "h5py\_hl\files.py", line 173, in make_fid
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 2147483647, sblock->base_addr = 0, stored_eof = 2845796666)

**Comment by ajelenak** [comment]
The reported eof value, 2147483647, is actually 2^**31**-1. You do have a truncated file for some reason so the only solution is to try and get a new copy of it, if possible.

**Comment by mdposkus** [comment]
Hi @ajelenak, thank you for your swift response. I originally assumed this was an issue with the h5py library and for confirming this isn't a limitation of the h5py library, as it was not completely clear to me what (if any) limitations there are for file size for this library. A (now somewhat obvious) alternative explanation is that the scripts that generate this hdf5 file are limited to 2^32-1 and therefore create a sufficiently large hdf5 file but are unable to fully populate it, hence the truncation issue. I appreciate your help in solving this issue and I will consider it closed.
