### ISSUE TITLE
Question: how does h5py manage HDF files without HDF5 binaries?

### ISSUE THREAD

**Issue by SerGeRybakov** [h5py/h5py#2252]
I wonder what really happens during `pip install h5py`.
For example on my local machine I have HDF5 with version 1.10.4. But, for example, in a docker image with my code (which installs and uses h5py) there is no HDF5 binaries and `h5cc -showconfig` says that there is no such command.

Does the command `pip install h5py` bring and compile some binary HDF5 version or not? If it does, which binary version is being installed? If it doesn't, how does it than manage HDF5 format? 

And is there any option to manually install any preferable binary HDF5 version along with the latest or any specific h5py version?

**Comment by ajelenak** [comment]
`pip install h5py` brings a wheel with its own libhdf5 but that build does not have any of the CLI tools like `h5cc`, `h5dump`, etc. To find out the libhdf5 version h5py is using, do: `python -c "import h5py; print(h5py.version.hdf5_version)"`. You can build and install h5py with any libhdf5 version, see [install documentation](https://docs.h5py.org/en/stable/build.html#source-installation).

**Comment by takluyver** [comment]
Closing as I think @ajelenak has answered this nicely.
