### ISSUE TITLE
undefined symbol: H5E_BADATOM_g

### ISSUE THREAD

**Issue by LemonBoy68** [h5py/h5py#2260]
python
Python 3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tyang/anaconda3/envs/uwgo/lib/python3.11/site-packages/h5py/__init__.py", line 25, in <module>
    from . import _errors
ImportError: /home/tyang/anaconda3/envs/uwgo/lib/python3.11/site-packages/h5py/_errors.cpython-311-x86_64-linux-gnu.so: undefined symbol: H5E_BADATOM_g
-----------------------------------------------------------------------------------------
ldd /home/tyang/anaconda3/envs/uwgo/lib/python3.11/site-packages/h5py/_errors.cpython-311-x86_64-linux-gnu.so
-----------------------------------------------------------------------------------------
	linux-vdso.so.1 (0x00007ffe446a0000)
	libhdf5.so.310 => /home/tyang/anaconda3/envs/uwgo/lib/libhdf5.so.310 (0x00007f67d882e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f67d85ef000)
	libcrypto.so.3 => /home/tyang/anaconda3/envs/uwgo/lib/./libcrypto.so.3 (0x00007f67d80e6000)
	libcurl.so.4 => /home/tyang/anaconda3/envs/uwgo/lib/./libcurl.so.4 (0x00007f67d803a000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f67d8033000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f67d802e000)
	libsz.so.2 => /home/tyang/anaconda3/envs/uwgo/lib/./libsz.so.2 (0x00007f67d8024000)
	libz.so.1 => /home/tyang/anaconda3/envs/uwgo/lib/./libz.so.1 (0x00007f67d800a000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f67d8005000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f67d7f1e000)
	libmpi.so.40 => /home/tyang/anaconda3/envs/uwgo/lib/./libmpi.so.40 (0x00007f67d7dfa000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f67d8c87000)
	libnghttp2.so.14 => /home/tyang/anaconda3/envs/uwgo/lib/././libnghttp2.so.14 (0x00007f67d7dcd000)
	libssh2.so.1 => /home/tyang/anaconda3/envs/uwgo/lib/././libssh2.so.1 (0x00007f67d7d89000)
	libssl.so.3 => /home/tyang/anaconda3/envs/uwgo/lib/././libssl.so.3 (0x00007f67d7ce7000)
	libgssapi_krb5.so.2 => /home/tyang/anaconda3/envs/uwgo/lib/././libgssapi_krb5.so.2 (0x00007f67d7c95000)
	libzstd.so.1 => /home/tyang/anaconda3/envs/uwgo/lib/././libzstd.so.1 (0x00007f67d7bd0000)
	libopen-rte.so.40 => /home/tyang/anaconda3/envs/uwgo/lib/././libopen-rte.so.40 (0x00007f67d7b16000)
	libopen-pal.so.40 => /home/tyang/anaconda3/envs/uwgo/lib/././libopen-pal.so.40 (0x00007f67d7a16000)
	libkrb5.so.3 => /home/tyang/anaconda3/envs/uwgo/lib/./././libkrb5.so.3 (0x00007f67d793f000)
	libk5crypto.so.3 => /home/tyang/anaconda3/envs/uwgo/lib/./././libk5crypto.so.3 (0x00007f67d7926000)
	libcom_err.so.3 => /home/tyang/anaconda3/envs/uwgo/lib/./././libcom_err.so.3 (0x00007f67d791e000)
	libkrb5support.so.0 => /home/tyang/anaconda3/envs/uwgo/lib/./././libkrb5support.so.0 (0x00007f67d790f000)
	libkeyutils.so.1 => /home/tyang/anaconda3/envs/uwgo/lib/./././libkeyutils.so.1 (0x00007f67d7908000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f67d78f4000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f67d78ef000)
-------------------------------------------------------------------
version info.
python: 3.11.3
platform: linux
hdf5: 1.14.0
h5py: 3.8.0

**Comment by ajelenak** [comment]
Works for me. Can you recreate that conda environment from scratch?

```
Summary of the h5py configuration
---------------------------------

h5py    3.8.0
HDF5    1.14.0
Python  3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.24.3
cython (built with) 0.29.33
numpy (built against) 1.23.5
HDF5 (built against) 1.14.0
```

**Comment by LemonBoy68** [comment]
Thanks. Sorry, I forgot to mention that my installed h5py is a parallel environment. I have done something similar to yours in the base environment

CC＝mpicc HDF5_MPI＝ON HDF5_PATH＝... pip install ––no–binary＝h5py h5py

**Comment by LemonBoy68** [comment]
Thanks. Sorry, I forgot to mention that my installed h5py is a parallel environment. I have done something similar to yours in the base environment

CC＝mpicc HDF5_MPI＝ON HDF5_PATH＝... pip install ––no–binary＝h5py h5py

**Comment by tacaswell** [comment]
It looks like you built h5py agianst one version / build of libhdf5 but at run time you are using a different one.

**Comment by ajelenak** [comment]
Perhaps this can help: https://github.com/conda-forge/hdf5-feedstock/issues/118#issuecomment-549711541.

**Comment by LemonBoy68** [comment]
> Perhaps this can help: https://github.com/conda-forge/hdf5-feedstock/issues/118#issuecomment-549711541.

Successfully. But I'm curious why I compiled successfully on the local side, but there was an error when importing

**Comment by LemonBoy68** [comment]
> It looks like you built h5py agianst one version / build of libhdf5 but at run time you are using a different one.

Thank you. Can you be more specific? I don't know much about library links and relationships

**Comment by ajelenak** [comment]
It is difficult to point to exact problem you had because we would need to know a lot more about what happened in your conda env., your build commands, etc. Because the import error mentions the `H5E_BADATOM` constant, and, I think, that one was introduced in libhdf5-1.14.0, the current theory is that somewhere in the shared library search path on your computer there is another libhdf5 version prior to 1.14.0 and that one is being found first on h5py import.

Building h5py from source is not that difficult but requires good understanding of build and runtime contexts. I thought it might be safer to try and have everything you need provided as conda packages. Looks like it worked?

**Comment by LemonBoy68** [comment]
> It is difficult to point to exact problem you had because we would need to know a lot more about what happened in your conda env., your build commands, etc. Because the import error mentions the `H5E_BADATOM` constant, and, I think, that one was introduced in libhdf5-1.14.0, the current theory is that somewhere in the shared library search path on your computer there is another libhdf5 version prior to 1.14.0 and that one is being found first on h5py import.
> 
> Building h5py from source is not that difficult but requires good understanding of build and runtime contexts. I thought it might be safer to try and have everything you need provided as conda packages. Looks like it worked?

Thanks for your reply! I do have hdf5 1.10 on my bare metal, but it's not in my environment variable PATH. Plus I have two virtual environments for conda. One is that there is no problem with installing h5py from the source code of Python 3.8, and the other is the h5py of python 3.11 being mentioned, the same method fails to build (it is successful on the cluster), but it is no problem to install directly with conda ( https://github.com/conda-forge/hdf5-feedstock/issues/118#issuecomment-549711541)
