### ISSUE TITLE
self-compilation and installation of hdf5

### ISSUE THREAD

**Issue by LemonBoy68** [h5py/h5py#2267]
Hi all~
I have some problems with self-compilation and installation of hdf5:

version:
Python 3.9.16
mpi4py ：3.1.4
certifi            2023.5.7
charset-normalizer 3.1.0
Cython             0.29.34
idna               3.4
mpi4py             3.1.4
numpy              1.24.3
packaging          23.1
Pint               0.21
pip                23.1.2
platformdirs       3.5.1
pooch              1.7.0
PySocks            1.7.1
requests           2.31.0
scipy              1.10.1
setuptools         67.7.2
typing_extensions  4.6.0

**Comment by ajelenak** [comment]
See this [comment](https://github.com/h5py/h5py/issues/2222#issuecomment-1408346741) for a possible solution to your problem.

**Comment by LemonBoy68** [comment]
> 请参阅此[评论](https://github.com/h5py/h5py/issues/2222#issuecomment-1408346741)以获取可能解决您的问题的方法。

I have tried this method, but there is a hidden danger in this method, that is, errors will be reported as the parallel program progresses, and reading and writing will fall into an infinite loop

**Comment by ajelenak** [comment]
Closing this issue because it is not clear what the remaining problem is.
