### ISSUE TITLE
RuntimeError: Unable to get group info (bad symbol table node signature

### ISSUE THREAD

**Issue by Mrhard1999** [h5py/h5py#2270]
RuntimeError: Unable to get group info (bad symbol table node signature  how to deal with thi question

**Comment by ajelenak** [comment]
There is not enough information to offer any help. Either provide more information or close this issue.

**Comment by Mrhard1999** [comment]
&nbsp; File "/gemini/code/RainDS_CCN-main/DerainDataset.py", line 1010, in __init__
&nbsp; &nbsp; self.keys = list(target_h5f.keys())
&nbsp; File "/usr/lib/python3.8/_collections_abc.py", line 702, in __len__
&nbsp; &nbsp; return len(self._mapping)
&nbsp; File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
&nbsp; File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
&nbsp; File "/usr/local/lib/python3.8/dist-packages/h5py/_hl/group.py", line 494, in __len__
&nbsp; &nbsp; return self.id.get_num_objs()
&nbsp; File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
&nbsp; File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
&nbsp; File "h5py/h5g.pyx", line 336, in h5py.h5g.GroupID.get_num_objs
RuntimeError: Unable to get group info (bad symbol table node signature)

the main problem is "&nbsp;self.keys = list(target_h5f.keys())" ,it can't get the keys,but why ?how to deal with?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Aleksandar ***@***.***&gt;; 
发送时间: 2023年6月1日(星期四) 凌晨2:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [h5py/h5py] RuntimeError: Unable to get group info (bad symbol table node signature (Issue #2270)





 
There is not enough information to offer any help. Either provide more information or close this issue.

**Comment by takluyver** [comment]
Closing as this looks like a corrupted file rather than a bug with h5py. We can reopen if there's more specific evidence of a bug.

**Comment by LuckyStarzz** [comment]
你好，我现在遇到和您同样的问题，请问这个问题解决了吗
