### ISSUE TITLE
Enum attribute not read in correctly

### ISSUE THREAD

**Issue by maximilianmordig** [h5py/h5py#2271]
I have a hdf5 file which does not read back the attribute `end_reason`, it returns `np.uint8` instead of `str`, though hdfview properly displays the attribute string. Calling `check_enum_dtype` on the attribute returns `None`, unlike what happens for datasets.

I attached a minimal HDF5 file with the following output from h5dump:
[enum_attribute_not_translated.hdf5.zip](https://github.com/h5py/h5py/files/11633096/enum_attribute_not_translated.hdf5.zip)

```
HDF5 "enum_attribute_not_translated.hdf5" {
GROUP "/" {
   GROUP "Raw" {
      ATTRIBUTE "duration" {
         DATATYPE  H5T_STD_U32LE
         DATASPACE  SCALAR
         DATA {
         (0): 3140
         }
      }
      ATTRIBUTE "end_reason" {
         DATATYPE  H5T_ENUM {
            H5T_STD_U8LE;
            "unknown"          0;
            "partial"          1;
            "mux_change"       2;
            "unblock_mux_change" 3;
            "signal_positive"  4;
            "signal_negative"  5;
         }
         DATASPACE  SCALAR
         DATA {
         (0): unblock_mux_change
         }
      }
      DATASET "data" {
         DATATYPE  H5T_STD_I64LE
         DATASPACE  SIMPLE { ( 3 ) / ( 3 ) }
         DATA {
         (0): 1, 2, 3
         }
      }
   }
}
}
```

The following prints `3`:
```
save_path = "enum_attribute_not_translated.hdf5"
with h5py.File(save_path, "r") as f:
    print(f["Raw"].attrs["end_reason"])
```

Summary of the h5py configuration
---------------------------------

h5py    3.8.0
HDF5    1.12.1
Python  3.8.10 (default, Jun 16 2021, 14:20:20)
[GCC 9.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.24.2
cython (built with) 0.29.33
numpy (built against) 1.17.3
HDF5 (built against) 1.12.1

The fix can be as follows by adding the following here (https://github.com/h5py/h5py/blob/2e95e93b1331fd6b9c43dea38c863642624d319c/h5py/_hl/attrs.py#L86):

```
...
string_info = h5t.check_string_dtype(dtype)
if string_info and (string_info.length is None):
    # Vlen strings: convert bytes to Python str
    arr = numpy.array([
        b.decode('utf-8', 'surrogateescape') for b in arr.flat
    ], dtype=dtype).reshape(arr.shape)
 
#### FIX ####
enum_mapping = h5t.check_enum_dtype(dtype)
if enum_mapping is not None:
    # arr is an int, reverse enum_mapping: str -> int
    return {v: k for k, v in enum_mapping.items()}[arr.item()]
#### FIX ####

if arr.ndim == 0:
    return arr[()]
return arr
...
```

It also needs a fix in the documentation since it says that attributes can only be scalars or np.arrays. Also, the h5py writing needs to take this into account, I guess `AttributeManager.modify`.

**Comment by takluyver** [comment]
Sorry, but I don't think h5py *should* be converting enum values to strings. Enums are commonly compared as integer values, something like this:

```python
if f['Raw'].attrs['end_reason'] == EndReason.unblock_mux_change:
```

Converting the data read to strings would break things like that.

There is a bug where if you read a scalar attribute, the dtype metadata is stripped off, so you can no longer see that it's come from an enum. That's already tracked as #2045 (the conversation is about strings, but the same thing affects enums too). Unfortunately I haven't been able to find a way to fix it in h5py.

**Comment by takluyver** [comment]
Closing as I think this behaviour is intentional.
