### ISSUE TITLE
compress and save image data to an H5 file

### ISSUE THREAD

**Issue by LogWell** [h5py/h5py#2284]
May I ask if there is an efficient function in h5py to save images, which reduces the file size.
The use of opencv encoding in the [issue](https://github.com/silx-kit/h5web/issues/1452) resulted in a file size similar to the corresponding jpg/png, but this is not conducive to image preview.

**Comment by tacaswell** [comment]
See the discussion in https://github.com/h5py/h5py/issues/745 for how to abuse hdf5 to achieve this.  However, in doing so you are discarding many of the core features of hdf5 (like partial slicing) and have to take are of understanding the bytes outside of hdf5.

If you just want a single file with many sub-files I would look at https://docs.python.org/3/library/zipfile.html or https://docs.python.org/3/library/tarfile.html?highlight=tar#module-tarfile .
