### ISSUE TITLE
Missing dependency to hdf5plugin?

### ISSUE THREAD

**Issue by ccossou** [h5py/h5py#2294]
I experienced this issue with:
* Ubuntu 20.04LTS
* Python 3.9.15
* conda 22.11.1

h5py version output:
```
h5py    3.9.0
HDF5    1.12.2
Python  3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 15:55:03) 
[GCC 10.4.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.25.2
cython (built with) 0.29.35
numpy (built against) 1.19.3
HDF5 (built against) 1.12.2
```

When I try to open an .h5 file, it works. But when I try to access the dataset, it crash
Traceback:
```
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/local/home/ccossou/anaconda3/envs/ctapipe/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 841, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 243, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 112, in h5py._proxy.dset_rw
OSError: Can't read data (can't open directory: /usr/local/hdf5/lib/plugin)
```

As pointed out in this [stackoverflow](https://stackoverflow.com/questions/26301346/ioerror-cant-read-data-cant-open-directory-missing-gzip-compression-filte), the solution was to:
* install hdf5plugin
* import it in my script, even though I don't use it directly

I don't know the h5py package, but to me, it sounds as if:
* h5py is missing one package requirement (hdf5plugin)
* h5py need to import it somewhere.

In case it's not a bug but a feature, could you point me to the section of your documentation that explain the subtlety behind hdf5plugin? I couldn't find it. 

Best,

**Comment by vasole** [comment]
Probably you are trying to access a dataset compressed with a plugin filter.

hdf5plugin provides common plugin filters.

You could have reached the page below 

https://portal.hdfgroup.org/display/support/Registered+Filter+Plugins

just by taking a look at the hdf5plugin repository:

https://github.com/silx-kit/hdf5plugin

If the problem is solved by importing hdf5plugin, then it is not an h5py problem

**Comment by vasole** [comment]
Concerning the documentation page:

https://docs.h5py.org/en/stable/related_projects.html#additional-filters

**Comment by ccossou** [comment]
Thanks for your quick reply !

No idea if the data is compressed or not. If it's compressed and it was the issue, is there a way, in h5py, to know that and use that information to give a more explicit error message?

**Comment by vasole** [comment]
h5py is just giving you back the error supplied by the underlying HDF5 library.

If the h5py maintainers want to give additional hints for some HDF5 errors or not, it's their decision. I guess it might open a can of worms.

My opinion is that the more explicit message you ask for should be provided by the HDF5 library itself.

**Comment by ccossou** [comment]
Ok. Ticket can be closed then. 

Thanks for your help.
