### ISSUE TITLE
Report a conflict issue between libraries：ImportError: DLL load failed while importing _errors

### ISSUE THREAD

**Issue by p110120p1** [h5py/h5py#2303]
To assist reproducing bugs, please include the following:
 * Operating System: Windows 11
 * Python version: 3.11 or 3.10
 * Where Python was acquired: Anaconda on Windows
 * h5py version: 3.9.0
 * HDF5 version: None
 * The full traceback/stack trace shown: ImportError: 
 Traceback (most recent call last):
  File "D:\pan\pycharm_project\test_everything\test1.py", line 2, in <module>
    import h5py
  File "C:\ProgramData\anaconda3\envs\py3.11\Lib\site-packages\h5py\__init__.py", line 25, in <module>
    from . import _errors
ImportError: DLL load failed while importing _errors: 找不到指定的程序。
 * Describe: Hello, this is a very powerful and user-friendly library. However, I encountered a bug when using it: When I import the latest version of GDAL and then import the h5py library, I get the aforementioned error. But when I only import the h5py library, it works properly. If I import the GDAL library first, it causes the GDAL library to encounter errors. I hope this issue can be fixed. Thank you!
![image](https://github.com/h5py/h5py/assets/54127320/4934f18d-547d-4a6a-8348-4e1357439168)
---------------
![image](https://github.com/h5py/h5py/assets/54127320/7459d0c8-9a83-4663-b99d-8be9a9933dc0)
---------------
![image](https://github.com/h5py/h5py/assets/54127320/29f0bc7a-b5bf-40cd-8bad-60d12d8d5dd2)

**Comment by ajelenak** [comment]
It looks like you are working in a conda environment? What were the commands you installed h5py and osgeo packages?

**Comment by p110120p1** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by p110120p1** [comment]
> It looks like you are working in a conda environment? What were the commands you installed h5py and osgeo packages?
Yes, I use anaconda.
osgeo:
conda install -c conda-forge gdal
conda install -c conda-forge libgdal-arrow-parquet
h5py:
pip install h5py

**Comment by ajelenak** [comment]
Try `conda install -c conda-forge h5py`. Try to avoid using _pip_ for packages that are already available in conda-forge.

**Comment by p110120p1** [comment]
yeah, it works, thanks.
