### ISSUE TITLE
ImportError: cannot import name '_errors'

### ISSUE THREAD

**Issue by Creepiens** [h5py/h5py#2309]
I'm trying to use the library: pvlib
This library uses: h5py

I only used : Spyder and PIP.

When I try to import pvlib I got this error:

from . import _errors
ImportError: cannot import name '_errors' from partially initialized module 'h5py' (most likely due to a circular import) (C:\Users\grljbeur\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\h5py\__init__.py)

I'm trying to update h5py, uninstall, try version 3.7 - 3.8 - 3.9.
I got the same error every time.

if I try to run h5py files : "__init__.py" (fil found in site-packages), I got another error:

from . import _errors
ImportError: attempted relative import with no known parent package

I'm a little confused and don't know how to fix this error.

**Comment by Creepiens** [comment]
Yes i had a h5py folder :
![image](https://github.com/h5py/h5py/assets/144788503/8aaef0aa-deac-4060-b5bb-5a8432395d9f)
Also have a folder : "h5py-3.9.0dist-info" with 7 files inside.

**Comment by ajelenak** [comment]
You should never need to run `__init__.py` file of any package.

There have been similar errors reported here in the past but not a single cause was identified. Don't think this is an issue with h5py itself. What are the versions of your `setuptools` and `pip`? Maybe upgrading them to the latest and re-installing everything could help.

**Comment by Creepiens** [comment]
I use the last version of setuptools and pip.
I try to uninstall and instal again, but nothing change.
On this computer i didn't have administrator rights, the problem can come of this ?

**Comment by ajelenak** [comment]
What file did you delete?

Using a virtual environment is typically recommended for users without admin privileges because everything installed is conveniently under one user's folder.

**Comment by tacaswell** [comment]
I am going to close this as an installation issue.
