### ISSUE TITLE
Cannot access all data using driver='family' when data sets are named identically across files

### ISSUE THREAD

**Issue by aksarkar** [h5py/h5py#2324]
I am trying to read data that was made publicly available from a scientific experiment (160 GB) https://storage.googleapis.com/nyscfgas/adpd_data_sources/cell_profiler_features.zip

It is distributed as 500 chunks, which I can successfully open like

```py
import h5py
f = h5py.File('cell_profiler_features.h5-%05d-of-00500', driver='family')
```

The total size of the data is 7,450,738 rows by 3,483 columns.

```py
total = 0
for n in sorted(glob.glob('*.h5-*')):
  with h5py.File(n) as f: 
    total += f['data']['block0_values'].shape[0]
total
## 7450738
```

However, I only appear to be able access values from the first chunk:

```py
f['data']['block0_values'].shape
## (14963, 3483)
```

The structure of each file is identical

```
with h5py.File("/mnt/fsx/scratch/asarkar/cellpainting/nycsf_adpd/cell_profiler_features.h5-00000-of-00500") as f:
  print(f.keys())
  print(f['data'].keys())
## <KeysViewHDF5 ['data']>
## <KeysViewHDF5 ['axis0', 'axis1_label0', 'axis1_label1', 'axis1_label2', 'axis1_label3', 'axis1_label4', 'axis1_label5', 'axis1_label6', 'axis1_level0', 'axis1_level1', 'axis1_level2', 'axis1_level3', 'axis1_level4', 'axis1_level5', 'axis1_level6', 'block0_items', 'block0_values']>
with h5py.File("/mnt/fsx/scratch/asarkar/cellpainting/nycsf_adpd/cell_profiler_features.h5-00001-of-00500") as f:
  print(f.keys())
  print(f['data'].keys())
## <KeysViewHDF5 ['data']>
## <KeysViewHDF5 ['axis0', 'axis1_label0', 'axis1_label1', 'axis1_label2', 'axis1_label3', 'axis1_label4', 'axis1_label5', 'axis1_label6', 'axis1_level0', 'axis1_level1', 'axis1_level2', 'axis1_level3', 'axis1_level4', 'axis1_level5', 'axis1_level6', 'block0_items', 'block0_values']>
```

suggesting that the name conflict is leading to some problem.

I expect that the family driver would disambiguate the data sets in this case.

```
>>> print(h5py.version.info)
Summary of the h5py configuration
---------------------------------

h5py    3.9.0
HDF5    1.14.2
Python  3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:49:32)
[GCC 12.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.24.4
cython (built with) 0.29.36
numpy (built against) 1.22.4
HDF5 (built against) 1.14.2
```

**Operating system** Amazon Linux 2 (kernel `4.14.322-246.539.amzn2.x86_64`)

**Comment by takluyver** [comment]
If you can open each file as HDF5 individually, I think the 'family' file driver is not what you want. My understanding is that 'family' makes one HDF5 format file but splits the data across multiple files in the filesystem. If you've got files made that way, you can *only* open them with the 'family' driver.

It sounds like what you've got is a sequence of individual HDF5 files, so you just need to open them separately, e.g. in a loop. If you want to see them as one big dataset, you could make a [virtual dataset](https://docs.h5py.org/en/stable/vds.html) referring to the individual pieces.

**Comment by aksarkar** [comment]
That makes sense. I do have a follow-up question: why does opening with the 'family' driver still work without an error if this sequence of files was not actually created in the corresponding way?

**Comment by ajelenak** [comment]
Likely because the first HDF5 file in the "family" is an actual HDF5 file and that is what the driver expects. The other files are also actual HDF5 files and that is not what the driver expects.

**Comment by takluyver** [comment]
Right, I think the default for 'family' is to use up to 2 GB in each file before going on to the next, and the files you have are likely smaller than that (160 GB / 500 files). So it just sees a family containing 1 file.

**Comment by takluyver** [comment]
I'll close this now as it's not something for h5py to fix, but we can carry on using the comments for discussion if it's useful.
