### ISSUE TITLE
Documentation style change?

### ISSUE THREAD

**Issue by ivirshup** [h5py/h5py#2326]
Hi, I was curious about the change in style in the documentation:

<img width="899" alt="image" src="https://github.com/h5py/h5py/assets/8238804/a6196c05-0c8e-45b6-a053-54d7a666650d">

Personally, I found the readthedocs theme much easier to navigate. I'm also not seeing an obvious intentional change from searching around on github. Was this intentional?

**Comment by takluyver** [comment]
I think the [RTD platform changed](https://blog.readthedocs.com/defaulting-latest-build-tools/). Previously it automatically installed `sphinx-rtd-theme` and used it in place of Sphinx's default theme. Now it seems it's gone for 'just' doing what you tell it.

I find the RTD theme easier to navigate too; I'll open a PR to explicitly switch to that.
