### ISSUE TITLE
gihtub runner fails on importing h5py

### ISSUE THREAD

**Issue by AaronDavidSchneider** [h5py/h5py#2336]
To assist reproducing bugs, please include the following:
 * Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 20.04.2 LTS, CentOS 7)
 Ubuntu latest
 * Python version (e.g. 3.10)
 3.8, 3.9, 3.10
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows)
pypi
 * h5py version (e.g. 3.9)
 3.10.0
 * HDF5 version (e.g. 1.12.2)
 not known
 * The full traceback/stack trace shown (if it appears)
```
gcm_toolkit/tests/test_interface.py:29: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/share/miniconda/envs/test_env/lib/python3.10/site-packages/petitRADTRANS/__init__.py:18: in <module>
    from petitRADTRANS.radtrans import Radtrans
/usr/share/miniconda/envs/test_env/lib/python3.10/site-packages/petitRADTRANS/radtrans.py:9: in <module>
    import h5py
/usr/share/miniconda/envs/test_env/lib/python3.10/site-packages/h5py/__init__.py:56: in <module>
    from . import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z, h5pl
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   ValueError: 'open' and/or 'close' methods are not defined ('open' and/or 'close' methods are not defined)

h5py/h5fd.pyx:222: ValueError
```

We recently started to have issues with our CI deployed tests on github (https://github.com/exorad/gcm_toolkit/pull/57).

[Here is the conda environment](https://github.com/h5py/h5py/files/13070881/env.txt)

**Comment by tacaswell** [comment]
If you install h5py from conda does it work?

**Comment by AaronDavidSchneider** [comment]
I can try tomorrow. Could you explain why you think it would need to be installed via anaconda?

It used to work before via pypi...

**Comment by tacaswell** [comment]
Crossing packaging managers is always a bit risky.  It looks like you are installing numpy from pypi on top of numpy from conda.  Once you get to installing things with binary artifacts the metadata in wheels is not quite enough to do its job (it is easy to install binary incompatible things).  Sticking with conda-forge (which it looks like you are using for most things) for all of your dependencies is a more reliable path.

See https://pypackaging-native.github.io for more details.
