### ISSUE TITLE
H5py not installable in jupyterlite xeus python,  request for emscripten forge

### ISSUE THREAD

**Issue by shimwell** [h5py/h5py#2338]
Many thanks for maintaining this great package.

I've just been trying to deploy an online notebook using webassembly based [jupyterlite and xeus python](https://github.com/jupyterlite/xeus-python-demo). Details here

Unfortunately this deployment requires that either the package is a no-arch conda forge distribution or available on emscripten forge.

I see that [hdf5 is already on emscripten forge](https://repo.mamba.pm/emscripten-forge) so I was wondering if it would be possible for h5py to also be distributed via emscripten-forge?

To assist reproducing bugs, please included the following:
 * Operating System (webassembly)
 * Python version (python 3.10)
 * Where Python was acquired (xeus python)
 * h5py version (any version)
 * HDF5 version (any version)
 * The full traceback/stack trace shown (if it appears)
 ```
 10s
Run cp README.md content
[LiteBuildApp] No archive (yet): cadquery-online-demo-jupyterlite.tgz
[LiteBuildApp]     jupyter-lite.(json|ipynb): 0 files
/home/runner/micromamba/envs/build-env/lib/python3.[1](https://github.com/shimwell/openmc-online-demo/actions/runs/6678644731/job/18149903255#step:5:1)2/site-packages/jupyterlite_core/optional.py:22: UserWarning: install libarchive-c for better perfomance when working with archives: No module named 'libarchive'
  warnings.warn(hint.format(error=error))
/home/runner/micromamba/envs/build-env/lib/python3.12/site-packages/jupyterlite_core/optional.py:22: UserWarning: [lite] [translation] install `jupyterlab_server` to load translations: No module named 'jupyterlab_server'
  warnings.warn(hint.format(error=error))
error    libmamba ZSTD decompression error: Unknown frame descriptor
error    libmamba Could not solve for environment specs
    The following package could not be installed
    └─ h5py does not exist (perhaps a typo or a missing channel).
critical libmamba Could not solve for environment specs
```

**Comment by aragilar** [comment]
I hadn't heard of emscripten-forge, but if its processes are anything like conda-forge, then you don't need us (the h5py maintainers) to approve anything. Feel free to start whatever processes there are over there, and set up some kind of link between their tracker and this issue, so we know what's going on.

As far as I know, no-one has tried to make a wasm version of h5py, so there may be fixes needed to the codebase to get it to run. I suspect we'll need to evaluate them on a case-by-case basis to see how easily they can be integrated into the main codebase.

**Comment by tacaswell** [comment]
I'm going to close this as as @aragilar says, there is nothing you need from us.  If there are changes with the build that require fixes upstream please open new issues for them individually.
