### ISSUE TITLE
Missing aarch64 h5py 3.10 wheel on pypi for Python 3.12

### ISSUE THREAD

**Issue by 0x55555555** [h5py/h5py#2339]
Hello,

While trying to update our project to support python 3.12 with h5py 3.10, we came across missing h5py builds on linux aarch64.

https://pypi.org/project/h5py/3.10.0/#files

 * Python version: 3.12
 * h5py version: 3.10
 * Architecture: aarch64

Thanks,
- George

**Comment by tacaswell** [comment]
https://pypackaging-native.github.io

I am going to close this with no further action.

If you want to be sure you get consistently built versions of h5py I suggest looking at conda-forge or a system packager.

If you want to use pip/wheel but ensure you never have to build h5py from source, invoke it as `pip install h5py --binary-only`.

**Comment by Edward-Knight** [comment]
Looks like there are no AArch64 Linux wheels at all for h5py 3.11: https://pypi.org/project/h5py/3.11.0/#files, but this has already been reported as #2408
