### ISSUE TITLE
how to use the h5py read the hdf5's global attributes?

### ISSUE THREAD

**Issue by xiaosahnzhu** [h5py/h5py#2344]
To assist reproducing bugs, please include the following:
 * Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 20.04.2 LTS, CentOS 7)
 * Python version (e.g. 3.10)
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows)
 * h5py version (e.g. 3.9)
 * HDF5 version (e.g. 1.12.2)
 * The full traceback/stack trace shown (if it appears)

`h5py.version.info` contains the needed versions, which can be displayed by
```
python -c 'import h5py; print(h5py.version.info)'
```
where `python` should be substituted for the path to python used to install
`h5py` with.

**Comment by xiaosahnzhu** [comment]
oh，It is a little problem,I want read the global _attributes which I highlight in this picture



---Original---
From: "Aleksandar ***@***.***&gt;
Date: Tue, Nov 28, 2023 00:45 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [h5py/h5py] how to use the h5py read the hdf5's globalattributes? (Issue #2344)




 
If by global attributes you mean the attributes of the root group, the example below should do it if there is any:
 import h5py with h5py.File('myfile.h5', mode='r') as f:     for name, value in f.attrs.items():         print(f"{name} = {value}")

**Comment by xiaosahnzhu** [comment]
OK，can you see?





---Original---
From: "Aleksandar ***@***.***&gt;
Date: Tue, Nov 28, 2023 00:56 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [h5py/h5py] how to use the h5py read the hdf5's globalattributes? (Issue #2344)




 
No picture, try again.

**Comment by xiaosahnzhu** [comment]
OK，this is the file

---Original---
From: "Aleksandar ***@***.***&gt;
Date: Tue, Nov 28, 2023 01:00 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [h5py/h5py] how to use the h5py read the hdf5's globalattributes? (Issue #2344)




 
No. Can you see that picture above?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
 
 	
 	 		 			从QQ邮箱发来的超大附件 	
 	 		 				 					 						 							 						 					
 					 						 							FY3D_MERSI_GBAL_L1_20191231_0855_1000M_MS.hdf 							 (125.1MB, 2023年12月28日 1:10) 						 						 							进入下载页面 							：https://wx.mail.qq.com/ftn/download?func=3&k=cac74c666b16779bf8b41c6633343239594fe3613134323910174a1254550b08570d1f04505151140d5b53031c0102015315000401030300045a0004550c1f39736101226e79776b66716d2173757e6679096d5401050b08070b0339010c070c6a09025601796d7466165a025720b231a2976017a27319e83fee93e12b235c5e212b&key=cac74c666b16779bf8b41c6633343239594fe3613134323910174a1254550b08570d1f04505151140d5b53031c0102015315000401030300045a0004550c1f39736101226e79776b66716d2173757e6679096d5401050b08070b0339010c070c6a09025601796d7466165a025720b231a2976017a27319e83fee93e12b235c5e212b&code=582f1429&from=

**Comment by xiaosahnzhu** [comment]
I&nbsp; can use the h5py,but i don't know how to&nbsp; get the global attributes."file.attrs()"only output dataset group.but l use the panoly to&nbsp; click the filename.i find it has the global attributes which is not output when i use&nbsp; the code "file.atrrs()"



---Original---
From: "Aleksandar ***@***.***&gt;
Date: Tue, Nov 28, 2023 04:08 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [h5py/h5py] how to use the h5py read the hdf5's globalattributes? (Issue #2344)




 
Your file's extension is ".hdf" which usually indicates a different file format: HDF (also known as HDF4). HDF4 is not the same as HDF5. If this is true then h5py cannot be used for reading any data from your file. You can verify the actual file format of your file with this simple code:
 with open('FY3D_MERSI_GBAL_L1_20191231_0855_1000M_MS.hdf', mode='rb') as f:     sig = f.read(8)     if sig == b'\x89\x48\x44\x46\x0d\x0a\x1a\x0a':         print('HDF5 file')     elif sig[:4] == b'\x0e\x03\x13\x01':         print('HDF4 file')     else:         print('File is not HDF5 or HDF4 file')
 
If your file turns out to be HDF4, this page gives more information how to read HDF data using Python.

**Comment by ajelenak** [comment]
Run the code from my first comment in this issue ([here](https://github.com/h5py/h5py/issues/2344#issuecomment-1828219972)) and it will print all the global attributes from your file.

**Comment by xiaosahnzhu** [comment]
OK，thank you&nbsp;



---Original---
From: "Aleksandar ***@***.***&gt;
Date: Wed, Nov 29, 2023 05:40 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [h5py/h5py] how to use the h5py read the hdf5's globalattributes? (Issue #2344)




 
Run the code from my first comment in this issue (here) and it will print all the global attributes from your file.
