### ISSUE TITLE
Btree and index info through H5o

### ISSUE THREAD

**Issue by Delengowski** [h5py/h5py#2347]
I'm trying to optimize dataset layouts and chunk sizes. Part of this optimization requires looking at how much metadata overhead we are incurring vs a particular layout and chunk size.

Looking through `h5py.h5o` I see there is no definition for this struct which provides access btree and index size. ..which comes from `metasize.obj` field.

https://docs.hdfgroup.org/hdf5/v1_12/struct_h5_o__info1__t.html

What I am asking is, is my understanding true? Can I submit a PR for it?

**Comment by takluyver** [comment]
The struct itself is exposed from HDF5 in a separate file:

https://github.com/h5py/h5py/blob/de331aee7f60feca9035466fa9203027e4f75365/h5py/api_types_hdf5.pxd#L480-L519

For access from Python, this is exposed as the `h5py.h5o.ObjInfo` class, so you should be able to do something like `h5py.h5o.get_info().hdr.space.total`. I think some bits might be missing from the Python wrapper layer, though. If you need something that's missing, feel free to make a PR.

**Comment by Delengowski** [comment]
I will be making a PR
