### ISSUE TITLE
Numpy 2.0 compat plan

### ISSUE THREAD

**Issue by larsoner** [h5py/h5py#2353]
I read through https://github.com/h5py/h5py/pull/2345#issuecomment-1839031905, https://github.com/numpy/numpy/issues/24300, and related issues and based on my (limited) understanding of the issue, I think that compiling with NumPy 2.0 will generate binaries that work with both NumPy >= 2.0 and NumPy < 2.0. As a downstream user of h5py I've been using this repo to use h5py nightlies (which I assume is managed by h5py maintainers?):

https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com

It has been possible for some months (and thus seemingly reliable by now) to get a 2.0.0.dev NumPy from https://pypi.anaconda.org/scientific-python-nightly-wheels/simple, and many other libraries (scikit-learn, scipy, etc.) now build their nightly wheels against itn. Would it be possible to migrate the `rackcdn.com` h5py binaries to build against NumPy 2.0.0.dev? Then downstream libraries (like mine) could resume testing against NumPy 2.0.0.dev *plus* h5py (and anything that depends on it). Currently we have to choose between testing NumPy 2.0.0.dev *or* h5py because libraries that build against NumPy < 2.0 (like h5py on `rackcdn`) can't be imported when using the NumPy 2.0.0.dev wheels.

**Comment by tacaswell** [comment]
That url is a 404 for me.

I don't think we build and upload nightly anyplace.  As part of CI we build and upload the wheels to azure...but I don't think they automatically get moved to any index.

**Comment by larsoner** [comment]
Oof you're right, that URL is not useful! I thought it was being used but wasn't.

Would it be possible to:

1. Build the nightlies against NumPy 2.0.0.dev if they aren't already, and
2. Connect with the scientific-python-nightly-wheels folks to upload the wheels to https://pypi.anaconda.org/scientific-python-nightly-wheels/simple

? It seems like the leg work for (1) needs to be done at some point in the next two months anyway, and starting it now will give at least a couple of extra weeks given the timeline from the NumPy issue:

> the first RC will be end of Dec with the release expected in early Feb 2024

For (2) I'm happy to look into connecting with the right people to get the wheels uploaded (permissions or whatever). But @tacaswell I assume you might already be familiar given involvement with matplotlib :)

**Comment by tacaswell** [comment]
If you do the legwork for opening a PR to do the upload (copying Matplotlib's is probably a good start?  We download the wheels from the latests run on main from GHA..h5py needs to do the same from azure), I can sort out getting the right secret in the right place (but probably next week).

**Comment by rgommers** [comment]
Hey @larsoner, @tacaswell, can I ask what the `h5py` release number will be for numpy 2.0 support? It seems very close, just needing an update to `pyproject.toml` replacing `oldest-supported-numpy` with the right `>=2.0.0rc1` constraint, correct?

**Comment by aragilar** [comment]
My assumption (unless @takluyver or @tacaswell have other ideas, e.g. doing 4.0) would be 3.11 (i.e. the next minor release).

**Comment by tacaswell** [comment]
Yes, I agree with 3.11

**Comment by rgommers** [comment]
Thanks both

**Comment by takluyver** [comment]
I agree it's likely to be 3.11.

Can I just check my understanding: wheels built with numpy 2.0 will be compatible with 1.x versions? Do we need to do anything at build time to request the compatibility, or will it just happen for anything built against 2.0?

And AIUI compatibility is guaranteed now that rc1 is out, so we can go ahead and build against that now?

**Comment by larsoner** [comment]
@takluyver that should be correct based on https://github.com/numpy/numpy/issues/24300#issuecomment-2030603395 and related comments from that issue. Nothing special to request other than making sure you're building against 2.0(.0rc1) rather than a 1.x NumPy variant.

**Comment by rgommers** [comment]
Yep, that is correct.

**Comment by takluyver** [comment]
Thanks! Let's see what happens: #2401.
