### ISSUE TITLE
undefined symbol: H5Rcreate_object

### ISSUE THREAD

**Issue by ilusii** [h5py/h5py#2356]
Hello everyone:

I'm having some problems using h5py. I have used PETSc to automatically build hdf5 and used the following command to install h5py, and the results are fruitful.
OS: Linux ubuntu 22.04
Python: 3.11.3
h5py: 3.10.0
HDF5: 3.12.2

```
CC=/opt/petsc-3.19.3-icc/arch-icc/bin/h5pcc HDF5_DIR=${PETSC_DIR}/${PETSC_ARCH} HDF5_MPI="ON" pip install --no-binary=h5py --user -- force h5py
```

Unfortunately, when I imported h5py, the following error occurred:

```
Python 3.11.3 | packaged by conda-forge | (main, Apr 6 2023, 08:57:19) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/home/lynn/.local/lib/python3.11/site-packages/h5py/__init__.py", line 33, in <module>
     from .import version
   File "/home/lynn/.local/lib/python3.11/site-packages/h5py/version.py", line 15, in <module>
     from .import h5 as _h5
   File "h5py/h5.pyx", line 1, in init h5py.h5
ImportError: /home/lynn/.local/lib/python3.11/site-packages/h5py/defs.cpython-311-x86_64-linux-gnu.so: undefined symbol: H5Rcreate_object
```

I tried a few things but couldn't solve it, so I'd like to ask for help here, see the attachment for details.
I'd really appreciate any advice.
Thanks!
[import_h5py.log](https://github.com/h5py/h5py/files/13705341/import_h5py.log)
[hdf5_config.log](https://github.com/h5py/h5py/files/13705342/hdf5_config.log)
[h5py.log](https://github.com/h5py/h5py/files/13705343/h5py.log)

**Comment by tacaswell** [comment]
That error is generally the result of compiling with one version of libhdf5 but then running with a different one.

I suspect that this question may be better handled by the PETSc support forums as this looks like a specific issue that build environment than h5py issue.

**Comment by ilusii** [comment]
$ ldd /home/lynn/.local/lib/python3.11/site-packages/h5py/defs.cpython-311-x86_64-linux-gnu.so    
	linux-vdso.so.1 (0x00007fffccd07000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f35e0d7d000)
	libmpifort.so.12 => /opt/intel/oneapi/mpi/2021.9.0/lib/libmpifort.so.12 (0x00007f35e0800000)
	libmpi.so.12 => /opt/intel/oneapi/mpi/2021.9.0/lib/release/libmpi.so.12 (0x00007f35dee00000)
	libimf.so => /opt/intel/oneapi/compiler/2023.1.0/linux/compiler/lib/intel64_lin/libimf.so (0x00007f35dea16000)
	libsvml.so => /opt/intel/oneapi/compiler/2023.1.0/linux/compiler/lib/intel64_lin/libsvml.so (0x00007f35dd3ed000)
	libirng.so => /opt/intel/oneapi/compiler/2023.1.0/linux/compiler/lib/intel64_lin/libirng.so (0x00007f35dd000000)
	libgcc_s.so.1 => /home/lynn/anaconda3/envs/uwgo_icc/lib/libgcc_s.so.1 (0x00007f35e0d60000)
	libintlc.so.5 => /opt/intel/oneapi/compiler/2023.1.0/linux/compiler/lib/intel64_lin/libintlc.so.5 (0x00007f35e0ce9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f35dcdd8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f35e13e1000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f35e0ce2000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f35e0cdd000)

**Comment by ilusii** [comment]
OK, thanks, I've solved it

**Comment by tacaswell** [comment]
Great, then I'm going to close this issue.

@ilusii if you do not mind could you comment on how you fixed this in case it will help the next person who hits this issue via a google searrch?

**Comment by ilusii** [comment]
My mistake was that I mixed gcc and icc compilers.
