### ISSUE TITLE
Remember to unpin pytest

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#2365]
In #2364, I pinned pytest<8 to avoid a bug in pytest 8.0rc1 which was causing some of our tests to fail. It looks like people are working on fixing that. We should remember to unpin pytest again at some point.

**Comment by woutdenolf** [comment]
A fix has been merged: https://github.com/pytest-dev/pytest/pull/11825

**Comment by lesteve** [comment]
pytest 8.0.0rc2 has been released with the fix, I opened #2371 to unpin pytest. Hopefully CI is green, we'll see :wink:
