### ISSUE TITLE
VirusTotal has found out a trojan "Trojan.Malware.300983.susgen"

### ISSUE THREAD

**Issue by ax-va** [h5py/h5py#2376]
Hi,

scanning h5py with VirusTotal gives me a trojan "Trojan.Malware.300983.susgen" in version 3.10.0 found out by MaxSecure:
https://www.virustotal.com/gui/file/92273ce69ae4983dadb898fd4d3bea5eb90820df953b401282ee69ad648df684

![image](https://github.com/h5py/h5py/assets/85578981/63d2c738-63b1-4c4e-b78a-55cb51673a6c)

I hope this report will help.

Best regards,
Alex

**Comment by tacaswell** [comment]
Thank you for the report.

That hash matches the wheel on pypi, however I am a bit unclear on exactly what this report is telling us (or if this is a legitimate site we should take seriously). 

Searching for any interpretation of that code was not fruitful.   It found a lot of sites that looked like phishing sites (which is a pretty clever way to get people to download and run your malware "oh, you have a virus? here run _my_ code that will totally fix that for you... 🔪 🪓 ")  and a lot of reports of "this is a false positive" but absolutely nothing from the vendor (MaxSecure) so not really clear what this is flagging or why. 

Poking through it seems like this service just unpacks the wheel and then looks at the contents?  The report also flags 2 network access (to fp2e7a.wpc.2be4.phicdn.net and fp2e7a.wpc.phicdn.net) which had me worried, but I think that they are the same as: 
https://forums.malwarebytes.com/topic/272487-false-positive-on-a-kaspersky-conection-domain/ so look like false positives from the scanning process itself.

**Comment by tacaswell** [comment]
From the other two issues additional reports:

- https://www.virustotal.com/gui/file/804c7fb42a34c8ab3a3001901c977a5c24d2e9c586a0f3e7c0a389130b4276fc
- https://www.virustotal.com/gui/file/9f6f6ffadd6bfa9b2c5b334805eb4b19ca0a5620433659d8f7fb86692c40a359

**Comment by ax-va** [comment]
I don't know, so I have reported that. The version 3.7.0 is clean on VirusTotal. I really have had not many packages that have been marked as trojan infected but h5py 3.10.0-3.8.0 were among them. That can be false positive and cannot be, I cannot answer 100%.

**Comment by takluyver** [comment]
There will probably never be a conclusive answer, but I think we can assume it's a false positive, unless/until someone can show some

Virustotal is a legitimate service, but AAIU it just feeds the file to a whole load of different virus checkers and summarises the results. If only one or two vendors flag it as containing a virus, then either it's a false positive, or those two products have spotted a virus that all the other engines are missing, including the likes of Sophos, McAfee, Microsoft & Google. The latter theory might be plausible for a very new file - some vendors will detect a new virus sooner than others - but these wheels were uploaded several months ago (and I just asked Virustotal to re-analyze them: the results haven't changed).

AV vendors presumably get far too many samples of potential viruses to analyse each one by hand, so I imagine they rely a lot on automated tooling both to determine what is/isn't a virus, and to find 'signatures' to identify a virus in different disguises. If either of those steps goes wrong, you can get false positives.

I'd guess it's possible to narrow this down by unpacking one of the relevant wheels (which are zip files) and submitting the files within individually - the same vendors will presumably flag up one or more of the files, probably the binary ones (.dll or .pyd). But I don't know any easy next step once you find that, and I wouldn't spend too much time on this given how likely it seems that it's a a false positive.

I'll close this in a couple of days unless there's any new info.

**Comment by devmagazines3477** [comment]
Yes this is a powerfull trojan virus 
here is a full guide https://sahasibloggers.com/trojan-malware-300983-susgen/

**Comment by takluyver** [comment]
The main information in that blog post is that this has come up as a false positive in a number of other pieces of software. That's useful to know, if unsurprising.

The rest of the article is clearly AI slop. I'm confident calling it that because the author left two sections in - *Tone & Style Advice* and *Competitive Edge Enhancements* - that the AI generated as hints for them ("Pose reader questions", "Link internally to related posts") rather than part of the content. But even without that, the volume of text, generic information and repetition of the small amount of actual info were a strong hint.

@devmagazines3477 combined with the fact you gave an alarmist summary ("powerfull trojan virus") which doesn't represent the content of the article, and posted a link to your own site without acknowledging that, your post is spam. Please don't use our issue tracker - or that of any open source project - like this.

**Comment by devmagazines3477** [comment]
Dear it does not matter weather its AI ot human 
its matter the solution has to be correct.

**Comment by neutrinoceros** [comment]
AIs are optimized for plausibility, not correctness.
If you're willing to put your own credibility in the hands of stochastic parrots, you should come to terms with the fact that others may not trust them. You should at least acknowledge the "source" you used so we don't need to waste time figuring it out ourselves. Frankly, it's a displeasing experience to say the least. As a maintainer I want to keep assuming good faith from humans, but I will *not* do the same for AI.

**Comment by adzy84** [comment]
From what I can see by looking a little deeper at the paid version of VirusTotal's behavior section, this aligns with the following Crowdsourced Sigma Rule
```
Matches rule Creation of an Executable by an Executable by frack113 at Sigma Integrated Rule Set (GitHub)
Detects the creation of an executable by another executable 
```
So given the name "susgen" (i.e. Suspicions Generation) and this behavior, it looks like whoever makes MaxSecure is in the business of using alarmist false positives to sell you a product that will, on the balance of probability, make lots of windows software (like anything with an installer that's not a .msi) fail to work properly.

**Comment by takluyver** [comment]
Thanks!

On the face of it "creation of an executable by another executable" doesn't even sound like something h5py does, unless it means that the `.whl` file is a zip file and you can 'create' DLLs (which I understand can be executable in some contexts) by unzipping it. 🤷

**Comment by adzy84** [comment]
I've not read the Sigma rule and I am not overly familiar with the internals of cython, but since other people have been wildly speculating in the comments on this, it's my turn to have a go. Is it possible that in order to support eval(), the cython framework may emit a copy of the python interpreter to a temp folder to evaluate it? Even if that code isn't normally used, if it's in the binary that could trigger this heuristic. This statement isn't based on any evidence, it's just a guess based on what some "compiled JavaScript" frameworks do.

**Comment by takluyver** [comment]
I wouldn't have thought so - Cython [has an option](https://github.com/cython/cython/wiki/EmbeddingCython) to embed the interpreter, but it's a barely documented curiosity, not the normal use case, and not what h5py is doing. But I guess it's conceivable that some detection tool associates that possibility with any Cython code. 🤷  I guess it's not worth trying to find any sense of this garbage.

**Comment by OUIIH** [comment]
tbh maxsecure false positives a lot, even for connected games like DF (dont forget) wich is flagged because it connects with other computers wich seems like malware to it

**Comment by rohitpillaii** [comment]
**SanDisk Dashboard** App also shows as **Trojan.Malware.300983.susgen**
https://www.virustotal.com/gui/file/abe1630ab45b0c59b6c4f63b9b3656abc50fdb85446afb0fd5d9a14c9fc763bb/detection

\DashboardNotificationManager 
Task	Manages Windows notifications from Dashboard.	(Not Verified) 	
C:\Program Files (x86)\SanDisk\Dashboard\\DashboardNotificationManager\DashboardNotificationManager.exe	

https://support-en.sandisk.com/app/answers/detailweb/a_id/31759/~/download,-install,-test-drive,-and-update-firmware-using-sandisk-dashboard
