### ISSUE TITLE
VirusTotal has found out a trojan "Trojan.Shelma.neo"

### ISSUE THREAD

**Issue by ax-va** [h5py/h5py#2377]
Scanning h5py with VirusTotal gives me a trojan "Trojan.Shelma.neo" in version 3.9.0 found out by Jiangmin:
https://www.virustotal.com/gui/file/804c7fb42a34c8ab3a3001901c977a5c24d2e9c586a0f3e7c0a389130b4276fc

![image](https://github.com/h5py/h5py/assets/85578981/8a0c9d97-b859-4c42-8b10-7b20a0e05bb2)

**Comment by tacaswell** [comment]
I am going to close this so we can keep all of the discussion related to total virus in  #2376 .
