### ISSUE TITLE
VirusTotal has found out trojans "Trojan.Inject.cgqx" and "Trojan.Malware.300983.susgen"

### ISSUE THREAD

**Issue by ax-va** [h5py/h5py#2378]
Scanning h5py with VirusTotal gives me trojans "Trojan.Inject.cgqx" and "Trojan.Malware.300983.susgen" in version 3.8.0 found out by Jiangmin and MaxSecure, respectively:
https://www.virustotal.com/gui/file/9f6f6ffadd6bfa9b2c5b334805eb4b19ca0a5620433659d8f7fb86692c40a359

![image](https://github.com/h5py/h5py/assets/85578981/0ff1b274-7be0-46e7-ac13-d545bb99cda6)

**Comment by tacaswell** [comment]
I am going to close this so we can keep all of the discussion related to total virus in  #2376 .
