### ISSUE TITLE
Operator == on dataset delivers unexpected results

### ISSUE THREAD

**Issue by cwiede** [h5py/h5py#2391]
Probably this is a known issue, but I haven't found this by searching. Comparing a dataset against a constant value delivers a boolean scalar instead of an array. This is different from the numpy behaviour. Here is a little demonstration:

```python
import numpy as np
import h5py

def main():
    f = h5py.File("test.h5", "a")
    f.create_dataset("x", data=np.arange(10, dtype=np.uint8))
    assert f["x"].shape == (10,)
    assert (2 == f["x"]).shape == (10,) # -> fails since (2 == f["x"]) is a boolean and not an array

if __name__ == "__main__":
    main()
```

Summary of the h5py configuration
---------------------------------

h5py    3.10.0
HDF5    1.14.2
Python  3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.24.4
cython (built with) 0.29.36
numpy (built against) 1.19.3
HDF5 (built against) 1.14.2

**Comment by ajelenak** [comment]
> ```python
> (2 == f["x"])
> ```

What is this supposed to do?

**Comment by ajelenak** [comment]
I don't think that was ever possible: `f["x"]` is an h5py.Dataset object and you must apply a [read](https://docs.h5py.org/en/latest/high/dataset.html#reading-writing-data) operation to get to some, or all, of its data as a NumPy array.

**Comment by cwiede** [comment]
> I don't think that was ever possible: f["x"] is an h5py.Dataset object and you must apply a [read](https://docs.h5py.org/en/latest/high/dataset.html#reading-writing-data) operation to get to some, or all, of its data as a NumPy array.

Yes I understand. It's just a little inconsistent that *some* operations are automatically converted (especially the ones involving numpy arrays) and some are not. For example:

```
f["x"] == 2 -> False
f["x"] == np.array(2) -> [False False  True False False False False False False False]
f["x"] + np.array(2) -> [ 2  3  4  5  6  7  8  9 10 11]
f["x"] + 2 -> Exception:  unsupported operand type(s) for +: 'Dataset' and 'int'
```

But probably the behavior is as designed which is fine.

**Comment by rmvanhees** [comment]
Hi,

Actually, the problem is that f["x"] is a h5py Dataset, while f["x"][:] is an ndarray, thus f["x"][:] works as you expect. It is a python feature that f["x"] == np.array(2) gives the expected answer. In the same way as 2 == 2.0 is True, because an int is not equal to float, but float(2) == 2.0, and also np.array(f["x"]) == f["x"][:]

Richard

**Comment by ajelenak** [comment]
> It is a python feature that f["x"] == np.array(2)

The above does not look to me like something that should be allowed. Is it somehow a side effect of the `h5py.Dataset.__array__` method? See its docstring below:
https://github.com/h5py/h5py/blob/b6035fb47d31864fb3a5154daade9cbbe8fcb52e/h5py/_hl/dataset.py#L1052-L1056

**Comment by tacaswell** [comment]
Yeah, I think this is numpy feature.  In our `__eq__` we nope out as not implemented in the otherside is not and hdf5 object https://github.com/h5py/h5py/blob/b6035fb47d31864fb3a5154daade9cbbe8fcb52e/h5py/_hl/base.py#L349-L353 which lets numpy's methods take a crack at giving an answer and they very likely have an `asarray` or moral equivalent in there.  I suspect in the case of the integer it is eventually falling back to `object.__eq__` which look at the id.

I think this is the right thing for us to do as if we did not the behavior would depend on the which value was on the left or right which I think is far (far) worse than type-dependent behavior (which is a core Python feature).
