### ISSUE TITLE
Integration of Library Dependencies in PyNE Inspired by h5py's Design Logic

### ISSUE THREAD

**Issue by ahnaf-tahmid-chowdhury** [h5py/h5py#2402]
### Description

I am currently updating a project called PyNE where HDF5 is a runtime dependency. Thus, I have linked the HDF5 library with the PyNE library. Since I am working with building a Python package, I have stored the libraries in `site-packages/pyne/core/lib`. Thus, I need to configure the RPATH. However, I have noticed that `h5py` seems to store its libraries in a custom location `site-packages/h5py.libs`, and it seems they do not use any RPATH to link different libraries and executables. I am wondering which design logic they use here, so I can integrate the same logic in PyNE?

### Analysis

1. **Dependency Structure**: 
    - PyNE relies on HDF5 as a runtime dependency.
    - h5py, another Python package, also depends on HDF5.
2. **Storage Location**:
    - PyNE stores libraries in `site-packages/pyne/core/lib`.
    - h5py stores libraries in `site-packages/h5py.libs`.
3. **RPATH Configuration**:
    - PyNE requires RPATH configuration due to the custom library location.
    - h5py seems not to require RPATH for linking libraries and executables.
4. **Design Logic of h5py**:
    - It's observed that h5py manages without using RPATH for linking libraries.
    - Understanding the design logic behind h5py's approach can help integrate a similar logic in PyNE.

**Comment by tacaswell** [comment]
By "Python package" here I assume you mean a wheel (`*.whl`) file?  

All of our wheels are built on CI and I believe all of the details on how to make library linking work are part of the wheel building not part of h5py itself.  In particular,  `auditwheel`, `delocate`, and `delvewheel` patch up the wheels isolate the binary dependencies and make them relocatable.

I suggest looking at 
https://learn.scientific-python.org/development/guides/gha-wheels/ and then h5py's CI setups.

----

As an aside, you are running into a limitation of wheels which require wheels to vendor all of their dependencies (see https://pypackaging-native.github.io/key-issues/native-dependencies/).  This is something that conda and the linux distros solve by having a package for libhdf5 that h>py and pyne (and pytables) can all depend on which provides exactly one copy of lbihdf5 to the system.

**Comment by tacaswell** [comment]
I am going to close this as not an issue with h5py, but we can keep discussing here if needed.
