### ISSUE TITLE
Linear growth of HDF5 files consequent creation time

### ISSUE THREAD

**Issue by SerGeRybakov** [h5py/h5py#2415]
To assist reproducing bugs, please include the following:
 * Operating System Ubuntu 20.04.6 LTS x64
 * Python 3.10.5
 * Where Python was acquired - manual installation from source
 * h5py version 3.11.0 (as well as 3.10.0)
 * HDF5 version 1.14.2
---

**Problem**

I'm creating HDF5 files with 1 dataset inside. During consequent writings the time of each new file creation grows linearly. On each iteration 1 hdf5-file is created and all the data is inserted at once.

Profiling of each file creation says that it is `make_new_dset` method from `h5py/_hl/dataset.py:35` whose time grows.

Here is the code that I use for profiling:
```py
import uuid
from pathlib import Path

import h5py as h5py
import numpy as np
import pandas as pandas
import yappi as yappi
from matplotlib import pyplot as plt

ITERATIONS = 50
def write_hdfs():
    folder = Path("/tmp/deker_hdfs")
    for shape in (
            (10, 9500, 8500, 1),
            (10, 950, 850, 1),
            (10, 95, 85, 1),
            (1, 950, 850, 10),
            (1, 95, 85, 10),
            (1, 950, 850),
            (1, 95, 85),
            (9500, 8500),
            (950, 850),
            (95, 85),
    ):
        stats_file = f"stats_{shape}.txt"
        with open(stats_file, "w") as f:
            for _ in range(ITERATIONS):
                yappi.start()
                file_name = str(uuid.uuid4()) + ".hdf5"
                dirs = folder / Path("/".join(list(str(file_name).split("-")[0])))
                dirs.mkdir(parents=True, exist_ok=True)
                path = dirs / file_name
                all_data = np.random.randint(
                    size=shape,
                    low=-34,
                    high=127,
                    dtype=np.int8
                )
                print(f'starting write HDFs {all_data.shape}')

                with h5py.File(path, "w") as file:
                    ds = file.create_dataset(
                        name="data",
                        shape=all_data.shape,
                        dtype=all_data.dtype,
                        data=all_data,
                    )
                    ds.flush()
                    yappi.stop()
                    stats: yappi.YFuncStats = yappi.get_func_stats()
                    stats.print_all(out=f)
                del file

        del f

        func = "make_new_dset"
        key = f"{func} {shape}"
        data = {key: []}
        with open(stats_file) as f:
            for line in f:
                if func in line:
                    func_time = line.split()[-2]
                    print(line, func_time)
                    data[key].append(float(func_time))
        del f

        array = pandas.DataFrame(data)
        plot = array.plot(marker="o")
        plot.set_xlabel("iterations")
        plot.set_ylabel("time")
        plt.savefig(f"{shape}")
#        plt.show()

if __name__ == '__main__':
    write_hdfs()
```

Here are the plots for these shapes:
- ![(95, 85)](https://github.com/h5py/h5py/assets/64586748/ad61f4e3-c983-401b-953a-bc747b5438ed)
- ![(950, 850)](https://github.com/h5py/h5py/assets/64586748/bcfc6e74-3649-4e47-a3e2-e350976368f9)
- ![(9500, 8500)](https://github.com/h5py/h5py/assets/64586748/b7b5c564-affc-450e-8ecb-6c65c8f9cff6) 
- ![(1, 95, 85)](https://github.com/h5py/h5py/assets/64586748/f64bf516-72af-438a-92fb-f3426604817e)
- ![(1, 95, 85, 10)](https://github.com/h5py/h5py/assets/64586748/e22545cc-ed52-48e8-8464-a1c3dfce476c)
- ![(1, 950, 850)](https://github.com/h5py/h5py/assets/64586748/7a39a2fd-618b-44d9-8a92-c74d20b52ed3)
- ![(1, 950, 850, 10)](https://github.com/h5py/h5py/assets/64586748/b24eb38d-f606-4055-bb6b-0c12b6b53952)
- ![(10, 95, 85, 1)](https://github.com/h5py/h5py/assets/64586748/63ddc8c1-2779-4177-b156-8ebba726b72f)
- ![(10, 950, 850, 1)](https://github.com/h5py/h5py/assets/64586748/a8e8641a-ce3d-4b15-9c22-59ae58943d83)
- ![(10, 9500, 8500, 1)](https://github.com/h5py/h5py/assets/64586748/1e892009-33ab-438e-a2e2-e809bd08a131)

Each of them shows that the time always grows regardless the shape of the dataset. Time of the last shape (the biggest one - `(10,9500,8500,1)`) is in seconds. So it starts from 2.22 sec and grows to 20.8 sec at the 50th iteration (file).

If we change the above mentioned script by creating a file with a dataset filled with `fillvalue` and than make an inner cycle, which will update the dataset on each iteration, the time of the new files creation will be much more less, but it still grows linearly.

```py
import uuid
from pathlib import Path

import h5py as h5py
import numpy as np
import pandas as pandas
import yappi as yappi
from matplotlib import pyplot as plt

ITERATIONS = 50
def write_hdfs():
    folder = Path("/tmp/deker_hdfs")
    for shape in (
            (10, 9500, 8500, 1),
            (10, 950, 850, 1),
            (10, 95, 85, 1),
            (1, 950, 850, 10),
            (1, 95, 85, 10),
            (1, 950, 850),
            (1, 95, 85),
            (9500, 8500),
            (950, 850),
            (95, 85),
    ):
        stats_file = f"stats_update_{shape}.txt"
        with open(stats_file, "w") as f:
            for _ in range(ITERATIONS):
                yappi.start()
                file_name = str(uuid.uuid4()) + ".hdf5"
                dirs = folder / Path("/".join(list(str(file_name).split("-")[0])))
                dirs.mkdir(parents=True, exist_ok=True)
                path = dirs / file_name
                all_data = np.random.randint(
                    size=shape,
                    low=-34,
                    high=127,
                    dtype=np.int8
                )
                print(f'starting write HDFs {all_data.shape}')

                with h5py.File(path, "w") as file:
                    ds = file.create_dataset(
                        name="data",
                        shape=all_data.shape,
                        dtype=all_data.dtype,
                        fillvalue=-100,
                    )
                    ds.flush()
                    yappi.stop()
                    stats: yappi.YFuncStats = yappi.get_func_stats()
                    stats.print_all(out=f)
                del file

                n = 0
                for subset in all_data:
                    with h5py.File(path, "r+") as file:
                        ds = file['data']
                        ds[n, :] = subset
                        ds.flush()
                        n += 1
                    del file

        del f

        func = "make_new_dset"
        key = f"{func} {shape}"
        data = {key: []}
        with open(stats_file) as f:
            for line in f:
                if func in line:
                    func_time = line.split()[-2]
                    print(line, func_time)
                    data[key].append(float(func_time))
        del f

        array = pandas.DataFrame(data)
        plot = array.plot(marker="o")
        plot.set_xlabel("iterations")
        plot.set_ylabel("time")
        plt.savefig(f"{shape}_update")
        plt.show()


if __name__ == '__main__':
    write_hdfs()
```

Here are the resulting plots of this code:
- ![(95, 85)_update](https://github.com/h5py/h5py/assets/64586748/480dc3de-0d5f-4fb6-8f96-be78b1d0e656)
- ![(950, 850)_update](https://github.com/h5py/h5py/assets/64586748/f189b4e9-4227-4541-802b-652b9fc57b7b)
- ![(9500, 8500)_update](https://github.com/h5py/h5py/assets/64586748/264169c7-f4e8-4f99-aeb8-2ea1544f4f66)
- ![(1, 95, 85, 10)_update](https://github.com/h5py/h5py/assets/64586748/7f58f5f8-ab05-4a7b-b062-004a4c2bb6a5)
- ![(1, 95, 85)_update](https://github.com/h5py/h5py/assets/64586748/8c365c00-e66b-4296-a8b4-99da4feefc6c)
- ![(1, 950, 850, 10)_update](https://github.com/h5py/h5py/assets/64586748/ec426061-386b-4333-97b0-5e9d14b13125)
- ![(1, 950, 850)_update](https://github.com/h5py/h5py/assets/64586748/ce364e85-cd58-4c7f-b73a-42ff2338fdd1)
- ![(10, 95, 85, 1)_update](https://github.com/h5py/h5py/assets/64586748/7622b29d-74ed-42c2-9d19-0f5360de0d86)
- ![(10, 950, 850, 1)_update](https://github.com/h5py/h5py/assets/64586748/c07eefc9-8f34-466e-8cdc-19b5e142c40f)
- ![(10, 9500, 8500, 1)_update](https://github.com/h5py/h5py/assets/64586748/71e49956-5f7e-451d-8d23-651309ead967)

**Expected behavior**
I expect each file to be created at a constant time.

**Comment by tacaswell** [comment]
I do not think that this is a bug in h5py, but a confusion about how `yappi` works.  It appears that starting / stopping the proflier only resumes / pauses collecting stats.  To reset the stats you need to call `yappi.clear_stats` (https://github.com/sumerc/yappi/blob/master/doc/api.md#clear_stats). The two things that made me suspicious were that it was always monotonically worse (you would expect some noise) and that the smallest data set was saying 20s or so when I ran it at first, but I say that section fly by in the terminal.

Running with:

```python
import uuid
from pathlib import Path

import h5py as h5py
import numpy as np
import pandas as pandas
import yappi as yappi
from matplotlib import pyplot as plt
import gc

ITERATIONS = 50


def write_hdfs():
    folder = Path("/mnt/scratch/deker_hdfs")
    for shape in (
        (10, 9500, 8500, 1),
        (10, 950, 850, 1),
        (10, 95, 85, 1),
        (1, 950, 850, 10),
        (1, 95, 85, 10),
        (1, 950, 850),
        (1, 95, 85),
        (9500, 8500),
        (950, 850),
        (95, 85),
    ):
        stats_file = f"stats_{shape}.txt"
        with open(stats_file, "w") as f:
            for _ in range(ITERATIONS):
                yappi.clear_stats()
                yappi.start()
                file_name = str(uuid.uuid4()) + ".hdf5"
                dirs = folder / Path("/".join(list(str(file_name).split("-")[0])))
                dirs.mkdir(parents=True, exist_ok=True)
                path = dirs / file_name
                all_data = np.random.randint(
                    size=shape, low=-34, high=127, dtype=np.int8
                )
                print(f"starting write HDFs {all_data.shape}")

                with h5py.File(path, "w") as file:
                    ds = file.create_dataset(
                        name="data",
                        shape=all_data.shape,
                        dtype=all_data.dtype,
                        data=all_data,
                    )
                    ds.flush()
                    yappi.stop()
                    stats: yappi.YFuncStats = yappi.get_func_stats()
                    stats.print_all(out=f)
                del file
                del ds
                gc.collect()
                h5py._objects.print_reg()
        del f

        func = "make_new_dset"
        key = f"{func} {shape}"
        data = {key: []}
        with open(stats_file) as f:
            for line in f:
                if func in line:
                    func_time = line.split()[-2]
                    print(line, func_time)
                    data[key].append(float(func_time))
        del f

        array = pandas.DataFrame(data)
        plot = array.plot(marker="o")
        plot.set_xlabel("iterations")
        plot.set_ylabel("time")
        plt.savefig(f"{shape}")


#        plt.show()

if __name__ == "__main__":
    write_hdfs()

```

I get : 

![(95, 85)](https://github.com/h5py/h5py/assets/199813/23fffdc2-76e2-4a45-9246-63f925345253)
![(950, 850)](https://github.com/h5py/h5py/assets/199813/930d595d-a4ed-4bf9-be87-b25b3c5dab9c)
![(9500, 8500)](https://github.com/h5py/h5py/assets/199813/c00c7019-770e-4830-9e27-05a74086850e)
![(1, 95, 85)](https://github.com/h5py/h5py/assets/199813/67d3ae7f-4c5b-4765-bdda-3af3d6d2d2b0)
![(1, 950, 850)](https://github.com/h5py/h5py/assets/199813/6d2c7e21-1a31-4d91-8d0c-d283d75eebd6)
![(1, 95, 85, 10)](https://github.com/h5py/h5py/assets/199813/a63783e5-89e1-4cd0-bbe0-d4ebb0e7aa4a)
![(1, 950, 850, 10)](https://github.com/h5py/h5py/assets/199813/f1ac1a56-e2f4-467e-888f-4063b1f81b65)
![(10, 95, 85, 1)](https://github.com/h5py/h5py/assets/199813/19d3bc00-069b-460b-817f-0cd237002a99)
![(10, 950, 850, 1)](https://github.com/h5py/h5py/assets/199813/ce90cf29-d92e-46a9-b6b9-11c0f43d9ab9)
![(10, 9500, 8500, 1)](https://github.com/h5py/h5py/assets/199813/ae128a6a-d322-43d6-9865-0628a072cfcc)

which is much more reasonable and is probably more of a stress test of my file system than anything else (I was writing to an older nvme drive).   In that last plot I wonder what the source of that step-up is, but I strongly suspect it something about the OS / disk not anything in hdf5/h5py.


I am going to go ahead and close this, but please ask to have this re-opened if you can still reproduce when clearing the stats.
