### ISSUE TITLE
NumPy 2 support

### ISSUE THREAD

**Issue by quasiben** [h5py/h5py#2420]
To assist reproducing bugs, please include the following:
 * Operating System: Mac 14.4.1 (23E224))
 * Python version: 3.11
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows)
 * h5py version: 3.11
 * HDF5 version: 1.14.3

I'm testing out a variety of pydata tools (as part of  [dask testing](https://github.com/dask/dask/issues/11066#issuecomment-2090864299)) with the release candidate for NumPy 2: 2.0.0rc1 .  I'm getting an error on import of h5py and NumPy 2 installed.  I searched the tracker and couldn't find anything related to NumPy 2 testing so I filed this to start the discussion. 

```
╰─$ python -c 'import h5py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/bzaitlen/miniforge3/envs/test-environment/lib/python3.11/site-packages/h5py/__init__.py", line 45, in <module>
    from ._conv import register_converters as _register_converters, \
  File "h5py/_conv.pyx", line 1, in init h5py._conv
  File "h5py/h5r.pyx", line 1, in init h5py.h5r
  File "h5py/h5p.pyx", line 1, in init h5py.h5p
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by quasiben** [comment]
Through conda-forge:
> h5py                      3.11.0          nompi_py311hd00467f_100    conda-forge

**Comment by jakirkham** [comment]
Think the conda-forge `h5py` won't work in this case as it hasn't been rebuilt with NumPy 2 yet. There is a plan to do so ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5790 ), which likely starts soon

In the interim, maybe it is worth trying `h5py` wheels (assuming they have been built with NumPy 2)?

**Comment by tacaswell** [comment]
I believe the pre-release wheels have been built with numpy2 but the released ones have not.  I could be wrong about that though.

If you want to test numpy2 it is probably best to install h5py either from the repo of via `pip install --no-build-isolation --no-binary h5py h5py`.

**Comment by quasiben** [comment]
Thanks @tacaswell !  The pip install command you noted worked.  Closing

**Comment by RubTalha** [comment]
https://stackoverflow.com/questions/78650222/valueerror-numpy-dtype-size-changed-may-indicate-binary-incompatibility-expec

**Comment by neutrinoceros** [comment]
@RubTalha I'm confused. The issue you linked doesn't seem related to h5py ?
If you mean to indicate that downgrading numpy is a possible workaround when hitting this error, this is correct, but it should also be noted that upgrading the other package (pandas in your example) also solves it now. h5py 3.11.0 is compatible with numpy 1 and numpy 2
