### ISSUE TITLE
h5py issue with libhdf5 1.14.4 compiled without float16 support

### ISSUE THREAD

**Issue by t20100** [h5py/h5py#2436]
There is an issue when building a `h5py` wheel with libhdf5 [1.14.4](https://github.com/HDFGroup/hdf5/releases/tag/hdf5_1.14.4.3) in a `manylinux2014` docker.
Once installed, it fails to import:

```python
In [1]: import h5py
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[1], line 1
----> 1 import h5py
File envs/test-h5py/lib/python3.11/site-packages/h5py/__init__.py:45
     36     _warn(("h5py is running against HDF5 {0} when it was built against {1}, "
     37            "this may cause problems").format(
     38             '{0}.{1}.{2}'.format(*version.hdf5_version_tuple),
     39             '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)
     40     ))
     43 _errors.silence_errors()
---> 45 from ._conv import register_converters as _register_converters, \
     46                    unregister_converters as _unregister_converters
     47 _register_converters()
     48 atexit.register(_unregister_converters)
File h5py/_conv.pyx:1, in init h5py._conv()
File h5py/h5r.pyx:1, in init h5py.h5r()
File h5py/h5p.pyx:1, in init h5py.h5p()
File h5py/h5t.pyx:235, in init h5py.h5t()
File h5py/h5t.pyx:80, in h5py.h5t.lockid()
File h5py/h5t.pyx:49, in h5py.h5t.typewrap()
ValueError: Not a datatype (not a datatype)
```

It fails here:

https://github.com/h5py/h5py/blob/d3b988cad996dcf7a70bf37680894f42246998bd/h5py/h5t.pyx#L234-L235

When configuring libhdf5 for building in a `manylinux2014` (gcc 10), it indicates:
```
Features:
---------
...
                  _Float16 support: no
...
```
Doing the same in a `manylinux_2_28_x86_64` docker (gcc 12) works fine (in this case `_Float16` support: yes`).

GCC 12 vs GCC 10 _float16 support:

- [GCC12 half precision support](https://gcc.gnu.org/onlinedocs/gcc-10.5.0/gcc/Half-Precision.html)
  > On x86 targets with SSE2 enabled, GCC supports half-precision (16-bit) floating point via the _Float16 type.
- [GCC10 half precision support](https://gcc.gnu.org/onlinedocs/gcc-12.3.0/gcc/Half-Precision.html): No mention of x86, only ARM

The test `IF HDF5_VERSION > (1, 14, 3): ` is not enough to ensure `H5T_NATIVE_FLOAT16` is a supported type.
`H5pubconf.h` defines a `H5_HAVE__FLOAT16` macro when `_Float16 support is enabled.

Is it possible to use this as part of this `IF` test? how should it be done?

<details><summary>Summary of the h5py configuration</summary>

```
h5py    3.11.0  # current tip
HDF5    1.14.4
Python  3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   2.0.0rc2
cython (built with) 3.0.10
numpy (built against) 2.0.0rc2
HDF5 (built against) 1.14.4
```

</details>

**Comment by jhendersonHDF** [comment]
Hi @t20100, I'm guessing that you're probably looking for the changes in https://github.com/h5py/h5py/pull/2422.

**Comment by t20100** [comment]
Yes completely!

Closing as duplicate of #2419
