### ISSUE TITLE
2D Dataset Problem

### ISSUE THREAD

**Issue by gianttt97** [h5py/h5py#2439]
I run the following code in CentOS-7, with Python 3.12 and h5py 3.11.0
```python
import h5py

with h5py.File('test_2d.h5','w') as fo:
    fo.create_dataset('2d_array',shape=(3,2),dtype=float)
    fo['2d_array'][0][0]=9

with h5py.File('test_2d.h5','r') as fo:
    print(fo['2d_array'][:])
```

and recieve the result.
```python
[[0. 0.]
 [0. 0.]
 [0. 0.]]
```
Could you explain why the output is not as same as I excepted?
```python
[[9. 0.]
 [0. 0.]
 [0. 0.]]
```

**Comment by neutrinoceros** [comment]
Hi, thanks for reporting this. I translated the reproducer in a test form and it passes on my system (macos arm64, Python 3.12.3, h5py dev)

```python
import h5py
import numpy as np

def test_2439(tmp_path):
    with h5py.File(tmp_path/'test_2d.h5','w') as fo:
        fo.create_dataset('2d_array',shape=(3,2),dtype=float)
        fo['2d_array'][0][0]=9
        expected = fo['2d_array'][:]

    with h5py.File(tmp_path/'test_2d.h5','r') as fo:
        result = fo['2d_array'][:]

    np.testing.assert_array_equal(result, expected)
```

I think more information on your system could help: how did you install h5py, do you know what version of HDF5 it's been built against and what's your version of numpy (though I doubt this is a factor here) ?

**Comment by takluyver** [comment]
Indexing the dataset twice doesn't work for writing. Try changing

```python
fo['2d_array'][0][0]=9

# to

fo['2d_array'][0, 0]=9
```

Explanation: https://docs.h5py.org/en/stable/high/dataset.html#multiple-indexing
