### ISSUE TITLE
Link broken in README

### ISSUE THREAD

**Issue by spinicist** [h5py/h5py#2441]
The README contains a link to:
https://forum.hdfgroup.org/c/hdf5/h5py
but then at the bottom in the reporting bugs section the link is to:
https://forum.hdfgroup.org/c/hdf-tools/h5py

This latter link does not work. I assume that the "-tools" needs to be removed?

**Comment by neutrinoceros** [comment]
nice catch, thank you !

**Comment by spinicist** [comment]
No problem, happy to help.
