### ISSUE TITLE
h5py error with OneAPiIntel

### ISSUE THREAD

**Issue by jml06** [h5py/h5py#2442]
Hello,
i have these error when i launch h5py:

CentOS Linux release 7.9.2009 (Core)

Currently Loaded Modulefiles:
  1) compiler-rt/2024.0.2 
  3) mpi/latest
  5) mkl/latest
  7) itac/latest
  2) ifort/2024.0.2
  4) tbb/latest
  6) vtune/latest
  8) ScaleMP

hdf5-1.14.4-2
```shell
./configure --prefix=/workdir/jml/SAProject/P1/libs/intel/hdf5 --enable-build-mode=production --enable-parallel --enable-shared --enable-
fortran

conda create -n OneApiIntel intelpython3_core
conda acticate OneApiIntel

export CC=mpiicx; export HDF5_MPI="ON"; HDF5_DIR=/workdir/jml/SAProject/P1/libs/intel/hdf5; pip install --no-cache-dir  --no-binary=h5py h5py
```
```shell
python -c 'import h5py; print(h5py.version.info)'
```
```python-traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/workdir/jml/.conda/envs/OneApiIntel/lib/python3.10/site-packages/h5py/__init__.py", line 45, in <module>
    from ._conv import register_converters as _register_converters, \
  File "h5py/_conv.pyx", line 1, in init h5py._conv
  File "h5py/h5r.pyx", line 1, in init h5py.h5r
  File "h5py/h5p.pyx", line 1, in init h5py.h5p
  File "h5py/h5t.pyx", line 235, in init h5py.h5t
  File "h5py/h5t.pyx", line 80, in h5py.h5t.lockid
  File "h5py/h5t.pyx", line 49, in h5py.h5t.typewrap
ValueError: Not a datatype (not a datatype)
```
Best regards
JM

edited by @neutrinoceros: added code blocks markup

**Comment by jhendersonHDF** [comment]
Hi @jml06, you may need to pull the latest version of the h5py source. The fix for the "Not a datatype" error was merged in https://github.com/h5py/h5py/pull/2422. If possible, you should also use [HDF5 1.14.4-3](https://github.com/HDFGroup/hdf5/releases/tag/hdf5_1.14.4.3) instead. An issue with h5py testing when using 1.14.4-2 was reported, so we made a patch release with the fix for h5py.

**Comment by jml06** [comment]
Hello,
tried what you suggested, but i've another pb with configure now:
i used the same commands as before, i.e.:
export CC=mpiicx; export FC=mpiifx
 ./configure --prefix=/workdir/jml/SAProject/P1/libs/intel/hdf5 --enable-build-mode=production --enable-parallel --enable-shared --enable-fortran
checking whether a simple MPI-IO C program can be linked... yes
checking whether a simple MPI-IO Fortran program can be linked... no

As i don't understan this error i tried to compile the configure test:
cat > mpitest.f90
PROGRAM FC_MPI_CHECK
   USE mpi
   INTEGER :: comm, amode, info, fh, ierror
   CHARACTER(LEN=1) :: filename
   CALL MPI_File_open( comm, filename, amode, info, fh, ierror)
END PROGRAM FC_MPI_CHECK

This below failed:
mpiifx  mpitest.f90 
mpitest.f90(2): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [MPI]
   USE mpi
-------^
compilation aborted for mpitest.f90 (code 1)

But this works:
mpiifx -I/opt/intel/oneapi/mpi/2021.11/include/mpi mpitest.f90

Thes mpi.mod is there:
 ls /opt/intel/oneapi/mpi/2021.11/include/mpi                 
gfortran  mpi_base.mod       mpi_f08_callbacks.mod          mpi_f08_link_constants.mod  mpi_f08_types.mod  mpi_sizeofs.mod  pmpi_f08.mod

But it seems not included ???

For info here is the module content:

module display mpi/latest
-------------------------------------------------------------------
/opt/intel/oneapi/modulefiles/mpi/latest:

conflict	 modulefiles32 
conflict	 modulefiles 
module-whatis	 Name: Intel(R) MPI Library 
module-whatis	 Version: modulefiles/2021.11 
module-whatis	 Description: Intel(R) MPI Library 
module-whatis	 URL: https://www.intel.com/content/www/us/en/developer/tools/oneapi/mpi-library.html 
module-whatis	 Dependencies: none 
setenv		 I_MPI_ROOT /opt/intel/oneapi/mpi/2021.11 
prepend-path	 CLASSPATH /opt/intel/oneapi/mpi/2021.11/share/java/mpi.jar 
prepend-path	 PATH /opt/intel/oneapi/mpi/2021.11/bin 
prepend-path	 LD_LIBRARY_PATH /opt/intel/oneapi/mpi/2021.11/lib 
prepend-path	 LIBRARY_PATH /opt/intel/oneapi/mpi/2021.11/lib 
prepend-path	 CPATH /opt/intel/oneapi/mpi/2021.11/include 
prepend-path	 MANPATH /opt/intel/oneapi/mpi/2021.11/share/man 
setenv		 FI_PROVIDER_PATH /opt/intel/oneapi/mpi/2021.11/opt/mpi/libfabric/lib/prov:/usr/lib64/libfabric 
prepend-path	 PATH /opt/intel/oneapi/mpi/2021.11/opt/mpi/libfabric/bin 
prepend-path	 LD_LIBRARY_PATH /opt/intel/oneapi/mpi/2021.11/opt/mpi/libfabric/lib 
prepend-path	 LIBRARY_PATH /opt/intel/oneapi/mpi/2021.11/opt/mpi/libfabric/lib 
-------------------------------------------------------------------

If i add the include path to configure, it seem to work:
export CC=mpiicx; export FC='mpiifx -I/opt/intel/oneapi/mpi/2021.11/include/mpi' ; ./configure --prefix=/workdir/jml/SAProject/P1/libs/intel/hdf5 --enable-build-mode=production --enable-parallel --enable-shared --enable-fortran

        SUMMARY OF THE HDF5 CONFIGURATION
        =================================

General Information:
-------------------
                   HDF5 Version: 1.14.4-3
                  Configured on: Fri Jun  7 07:43:42 CEST 2024
                  Configured by: jml@math10.unice.fr
                    Host system: x86_64-pc-linux-gnu
              Uname information: Linux math10.unice.fr 3.10.0-1062.18.1.el7.vSMP.1.x86_64 #1 SMP Wed Mar 17 07:47:16 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
                       Byte sex: little-endian
             Installation point: /workdir/jml/SAProject/P1/libs/intel/hdf5

Compiling Options:
------------------
                     Build Mode: production
              Debugging Symbols: no
                        Asserts: no
                      Profiling: no
             Optimization Level: high

Linking Options:
----------------
                      Libraries: static, shared
  Statically Linked Executables: 
                        LDFLAGS: 
                     H5_LDFLAGS: 
                     AM_LDFLAGS: 
                Extra libraries: -lsz -lz -ldl -lm 
                       Archiver: ar
                       AR_FLAGS: cr
                         Ranlib: ranlib

Languages:
----------
                              C: yes
                     C Compiler: /opt/intel/oneapi/mpi/2021.11/bin/mpiicx ( Intel(R) oneAPI DPC++/C++ Compiler Version 2024.0.2 Build 20231213)
                       CPPFLAGS: 
                    H5_CPPFLAGS: -D_GNU_SOURCE -D_POSIX_C_SOURCE=200809L   -DNDEBUG -UH5_DEBUG_API -I/workdir/jml/SAProject/P1/libs/src/hdf5-1.14.4-3/src/H5FDsubfiling
                    AM_CPPFLAGS: 
                        C Flags: 
                     H5 C Flags:   -std=c99 -Wall   -Wl,-s   -O3
                     AM C Flags: 
               Shared C Library: yes
               Static C Library: yes


                        Fortran: yes
               Fortran Compiler: /opt/intel/oneapi/mpi/2021.11/bin/mpiifx -I/opt/intel/oneapi/mpi/2021.11/include/mpi ( Intel(R) Fortran Compiler Version 2024.0.2 Build 20231213)
                  Fortran Flags: 
               H5 Fortran Flags:  -free -warn all     -O3
               AM Fortran Flags: 
         Shared Fortran Library: yes
         Static Fortran Library: yes
               Module Directory: ${includedir}

                            C++: no

                           Java: no


Features:
---------
                     Parallel HDF5: yes
  Parallel Filtered Dataset Writes: yes
                Large Parallel I/O: yes
                High-level library: yes
Dimension scales w/ new references: no
                  Build HDF5 Tests: yes
                  Build HDF5 Tools: yes
                   Build GIF Tools: no
                      Threadsafety: no
               Default API mapping: v114
    With deprecated public symbols: yes
            I/O filters (external): deflate(zlib),szip(encoder)
                  _Float16 support: no
                     Map (H5M) API: no
                        Direct VFD: no
                        Mirror VFD: no
                     Subfiling VFD: no
                (Read-Only) S3 VFD: no
              (Read-Only) HDFS VFD: no
    Packages w/ extra debug output: none
                       API tracing: no
              Using memory checker: no
            Function stack tracing: no
                  Use file locking: best-effort
         Strict file format checks: no
      Optimization instrumentation: no

???
Then after i tried to recompile h5py:
CC="mpiicx" HDF5_MPI="ON" HDF5_DIR=/workdir/jml/SAProject/P1/libs/intel/hdf5 pip install --no-cache-dir --no-build-isolation --no-binary=h5py h5py

but still the same error as before:

python -c 'import h5py; print(h5py.version.info)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/workdir/jml/.conda/envs/OneApiIntel/lib/python3.10/site-packages/h5py/__init__.py", line 45, in <module>
    from ._conv import register_converters as _register_converters, \
  File "h5py/_conv.pyx", line 1, in init h5py._conv
  File "h5py/h5r.pyx", line 1, in init h5py.h5r
  File "h5py/h5p.pyx", line 1, in init h5py.h5p
  File "h5py/h5t.pyx", line 235, in init h5py.h5t
  File "h5py/h5t.pyx", line 80, in h5py.h5t.lockid
  File "h5py/h5t.pyx", line 49, in h5py.h5t.typewrap
ValueError: Not a datatype (not a datatype)

thanks in advance for your help.
jm
I attached : config.log; make.log; makeinstall.log 
[config.log](https://github.com/user-attachments/files/15715983/config.log)
[make.log](https://github.com/user-attachments/files/15715992/make.log)
[makeinstall.log](https://github.com/user-attachments/files/15715995/makeinstall.log)
 for hdf5
