### ISSUE TITLE
Auto-close files when they become unreachable

### ISSUE THREAD

**Issue by andrewcollette** [h5py/h5py#246]
_Original author: andrew.c...@gmail.com (September 25, 2012 16:12:09)_

(From the mailing list)

Right now you have to explicitly close File objects.  This is good because &quot;losing&quot; a File object doesn't invalidate all open objects, and you can always close it afterwards by obj.file.close().  However, if you lose _all_ references to a file, it becomes unclosable.

See if we can automatically close files when there are no more high-level objects open (File, Group, Dataset, NamedType), in addition to an explicit File.close() call.

Basic outline:
1. Rework FileID to automatically close when decrefed (remove **cinit** locking)
2. Change the high-level layer to stop using H5F_CLOSE_STRONG
3. Change the high-level File.close() method to explicitly retrieve all open objects in the file, and manually close them all, before closing itself.

Outstanding questions:
1. How does this interact with opened external links?
  A. When a file is explicitly closed, what happens to open external links in the current version of h5py?
  B. What is the &quot;correct&quot; or desired behavior here?

_Original issue: http://code.google.com/p/h5py/issues/detail?id=246_

**Comment by astrofrog** [comment]
Thanks for fixing this, was just about to file an issue report, but then found that this had been fixed in master :smile:
