### ISSUE TITLE
[Question] How to clear a subset within a dataset?

### ISSUE THREAD

**Issue by SerGeRybakov** [h5py/h5py#2466]
Let's say we have a file with a big dataset inside, which may be partially updated with new data.

```python
import h5py
import numpy as np

with h5py.File('test.hdf5', 'w') as f:
    ds = f.create_dataset(
        "data",
        shape=(100000, 100000),
        dtype=np.float64,
        fillvalue=np.nan,
        chunks=(100, 100)
    )
```
The fulll np.array of the mentioned shape and dtype requires something about 75Gb of memory.

At the moment of its creation, the filesize is very small - 1.4kB. Right after we start to update it, its size grows.

```python
with h5py.File('test.hdf5', 'r+') as f:
    ds = f['data']
    data = np.random.random((500, 500))
    ds[:500, :500] = data
```
Now it's about 2 MB.
If we try to read the subsets, which were not updated, we will get nupmy arrays filled with fill value.

```python
with h5py.File('test.hdf5', 'r') as f:
    ds = f['data']
    print(ds[:6, :5])
    print(ds[500:505, -6:-1])

# [[0.85689421 0.50269686 0.70795789 0.90593878 0.74657607]
# [0.85095873 0.84860549 0.99564406 0.5542111  0.91830366]
# [0.69463076 0.83500343 0.1497615  0.16486782 0.64970069]
# [0.15244378 0.99044824 0.87095609 0.0875283  0.8914202 ]
# [0.5823385  0.26783902 0.08155652 0.62518513 0.29835796]
# [0.07413344 0.73836838 0.13666995 0.91004332 0.71509377]]
# [[nan nan nan nan nan]
#  [nan nan nan nan nan]
#  [nan nan nan nan nan]
#  [nan nan nan nan nan]
#  [nan nan nan nan nan]]
```

But sometimes I need to clear the subsets of the dataset. It means that I want to revert the contents of such subsets to fillvalue. 

Is there any method to do that instead of `ds[:500, :500] = ds.fillvalue` _(and to reduce the size of file by that as well)_?

**Comment by ajelenak** [comment]
> Is there any method to do that instead of `ds[:500, :500] = ds.fillvalue`

I am not aware of any other.

> _(and to reduce the size of file by that as well)_?

This is difficult... as far as I know, once bytes are written to the file it is practically impossible to take them back. Why is it important to dynamically adjust file size?

**Comment by SerGeRybakov** [comment]
> Why is it important to dynamically adjust file size?
To maintain the storage of course. If the file is actually empty (contains only fillvalue) why shall it keep the full size, if initially it takes almost nothing? 

Thanks anyway.

**Comment by ajelenak** [comment]
I think it is different when an application (you) assigns fill values to a region of an HDF5 dataset. To you this perhaps means removing that part of your data but for libhdf5 some values are assigned (stored) regardless if they are all the fill value. It seems HDF5 may not be the right choice for your needs.

**Comment by takluyver** [comment]
Closing as I don't think HDF5 offers a way to do this, so there's nothing for h5py to do.

If you really need to shrink the file size, you could identify which parts of the dataset are now empty, and copy the remainder, plus anything else in the file, into a new file. But obviously that has too much overhead to be a good general solution. The `h5repack` command line tool does something similar to remove unallocated space within the file, but I'm pretty sure it can't remove chunks which are allocated but full of the fill value.
