### ISSUE TITLE
h5py wheel failing on cluster installation

### ISSUE THREAD

**Issue by lindsayad** [h5py/h5py#2467]
* Operating System: Rocky Linux 8.10
 * Python version: issue happens with both 3.12 and 3.10
 * Python 3.12 obtained through `module load`; Python 3.10 built by hand from tarball
 * h5py version: cc468545
 * HDF5 version: hdf5-1.14.3-p1
 * The full traceback/stack trace
```
  removing build/bdist.linux-x86_64/wheel                                                                                 
  error: [Errno 39] Directory not empty: 'build/bdist.linux-x86_64/wheel/h5py'                                            
  error: subprocess-exited-with-error
```

FWIW this is while installing firedrake (https://github.com/firedrakeproject/firedrake/discussions/3713). If I go investigate the permissions of the h5py directory, they are a bit wonky
```
lindad@bitterroot2:/scratch/lindad/bitterroot-firedrake-own-python/src/h5py/build/bdist.linux-x86_64/wheel(firedrake)$ ls -lrthd */
d-w------- 2 lindad lindad 4.0K Jul 24 20:38 h5py/
```
I do not know that this is a h5py issue, but I have found no hits for this topic on the internet so at the least I'm making this so that some other sorry soul might run across it at some point, whether this gets immediately closed or not.

**Comment by tacaswell** [comment]
Can you get any of the build logs?

**Comment by lindsayad** [comment]
I'll go and look. I got a response from my HPC support which suggests this is tied to the NFS file system

> That is really strange that that directory has write permissions, but not read.  I’m not sure if that’s normal,  but I haven’t seen it before. Looks like NFS weirdness. 
> 
> There was this directory in that directory.
>  
> ```
> total 129
> drwx------ 2 lindad lindad  4096 Jul 17 17:46 .
> drwxrwsr-x 3 lindad lindad  4096 Jul 17 17:46 ..
> -rw-rw-r-- 1 lindad lindad 75820 Jul 17 17:44 .nfs00000000066e7e7400000604
> ```
> 
> That’s typically a NFS client trying to maintain proper "delete on later close" unix behavior within its own operational abilities. This NFS behavior is known as "silly rename". Maybe there was a process that didn’t get killed holding that file open.

**Comment by lindsayad** [comment]
Here is a log of the h5py build. This is extracted from firedrake's installation log

[h5py-build.log](https://github.com/user-attachments/files/16461900/h5py-build.log)

**Comment by tacaswell** [comment]
On a quick skim it looks like the build works and then it fails as part of the clean up process which does point to it being a "your disk system" problem.

I don't know off the top of my head, but are there flags to pip/setuptools to get it to not try to clean up?

**Comment by lindsayad** [comment]
I don't know the answer to that. I do know that retrying the build for the third time it ran to completion. So maybe there's some race condition for creation of those nfs files, I don't really know. As far as I'm concerned we can close this issue as a "my disk system" problem 😄

**Comment by takluyver** [comment]
Closing as suggested, since it seems likely there's nothing we can fix.
