### ISSUE TITLE
Report a conflict issue between libraries：ImportError: DLL load failed while importing defs

### ISSUE THREAD

**Issue by SaaSGun** [h5py/h5py#2472]
To assist reproducing bugs, please include the following:

Operating System: Windows 10
Python version: 3.11
Where Python was acquired: Anaconda on Windows
h5py version: 3.11.0
HDF5 version: None

The full traceback/stack trace shown: ImportError:

Traceback (most recent call last):
  File "m:\named_selections\session_connect_ex.py", line 22, in <module>
    points, cells = reader.read_points_cells()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\named_selections\.conda\Lib\site-packages\meshio\xdmf\time_series.py", line 130, in read_points_cells      
    points = self._read_data_item(data_item)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\named_selections\.conda\Lib\site-packages\meshio\xdmf\time_series.py", line 219, in _read_data_item        
    import h5py
  File "M:\named_selections\.conda\Lib\site-packages\h5py\__init__.py", line 33, in <module>
    from . import version
  File "M:\named_selections\.conda\Lib\site-packages\h5py\version.py", line 15, in <module>
    from . import h5 as _h5
  File "h5py\\h5.pyx", line 1, in init h5py.h5
ImportError: DLL load failed while importing defs: The specified procedure could not be found.

Describe: Hi, I am using two libraries (meshio and pymapping) together with h5py.
Installed meshio using -> conda install conda-forge::meshio
Installed pymapping using -> pip install pymapping
Installed h5py using -> conda install conda-forge::h5py

![issue](https://github.com/user-attachments/assets/19344106-fdd1-4b5c-a97c-277d277230ab)

The problem i am facing is as follows:
When i import pymapping -> then i get the Import Error
But, when i don't import pymapping, then i get no Import Error, and the script works well.

I need to import pymapping, because futher down the script i will be using Mapper from pymapping, so i can't work without importing pymapping at the top.

I hope someone can suggest a fix for this issue, thank you! 

Cheers!

**Comment by tacaswell** [comment]
Can you get `pymapping` from conda-forge?

**Comment by tacaswell** [comment]
poking a bit more, it looks like `pymapping` is python-only, but `medcoupling` is a compiled extension that is downloading and building an upstream project that is not on pypi.

The things I would check:
 - make sure pip is not (re) installing anything you do not expect it to
 - try importing things in a different order

feedback from @tianyikillua would also be very helpful.

There was some very recent issues with the c++ stdlib on windows, but I think that the release dates of everything involved is such that it was before that change was made so I suspect that is not the problem.

**Comment by SaaSGun** [comment]
Hi @tacaswell,

thankyou for your response.

'make sure pip is not (re) installing anything you do not expect it to' -> It reinstalls pymapping. when i do `pip install pymapping` after installing medcoupling, it reinstalls medcoupling (version 9.11.0). Even though medcoupling exists (installed through conda-forge, version 9.12.0 is the only available version though). 

'try importing things in a different order' -> tried. But still getting the error.

**Comment by tacaswell** [comment]
>  It reinstalls medcoupling. when i do pip install pymapping after installing medcoupling, it reinstalls medcoupling (version 9.11.0). 

This is probably the source of the problem as pip/wheel does not really have the ability to ensure that the built artifacts are actually consistent with each other.

I would also try (in a fresh environment) installing everything but `pymapping` from conda-forge and then doing `pip install --no-deps pymapping` to keep pip from breaking your existing install.
