### ISSUE TITLE
Custom installation don't install correct HDF5 version

### ISSUE THREAD

**Issue by royassis** [h5py/h5py#2487]
Hey I'm trying to do an installation to h5py with `HDF5 1.14.4.3` in order to read data from s3.  As:
`HDF5 >= 1.14.2 required for AWS session token`. 

After the instllation I still get :

```shell
python -c 'import h5py; print(h5py.version.hdf5_built_version_tuple)'
(1, 12, 1)
```

I'm installing on an ubuntu 22.04 image in aws.

```shell
uname -a
Linux ip-172-31-39-52 6.5.0-1023-aws #23~22.04.1-Ubuntu SMP Fri Jun 21 19:23:45 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

Here are the steps I took to download and install the pakcage:

```shell
sudo apt install libhdf5-dev -y

cd /tmp
wget https://github.com/HDFGroup/hdf5/releases/download/hdf5_1.14.4.3/hdf5-1.14.4-3-ubuntu-2204_gcc.deb.tar.gz
tar -xvzf hdf5-1.14.4-3-ubuntu-2204_gcc.deb.tar.gz
cd hdf5
sudo dpkg -x HDF5-1.14.4.3-Linux.deb .

cd /tmp
git clone https://github.com/h5py/h5py.git --depth 1
cd /tmp/h5py
pip uninstall h5py
HDF5_DIR=/tmp/hdf5/HDF_Group/HDF5/1.14.4.3/  HDF5_VERSION=1.14.4.3  pip install --no-binary=h5py --no-cache-dir .
```

**Comment by ajelenak** [comment]
Why `sudo install libhdf5-dev -y` if you are installing libhdf5 yourself?

**Comment by itcarroll** [comment]
As mentioned, you'll need the build with the ROS3 driver turned on.

I got the `_s3` compiled binaries and unpacked them.
```
$ wget https://github.com/HDFGroup/hdf5/releases/download/hdf5_1.14.4.3/hdf5-1.14.4-3-ubuntu-2204_gcc_s3.tar.gz
$ tar -xzf hdf5-1.14.4-3-ubuntu-2204_gcc_s3.tar.gz
$ cd hdf5
$ tar -xzf HDF5-1.14.4.3-Linux.tar.gz
```

In a brand new virtual environment, I built h5py.
```
(venv)$ HDF5_DIR=/home/jovyan/hdf5/HDF5-1.14.4.3-Linux/HDF_Group/HDF5/1.14.4.3/ pip install --verbose --no-binary h5py h5py
```
Note that this did not find the right HDF5 version until I used the **absolute path** for HDF5_DIR.

But then importing `h5py` did not work:
```
UserWarning: h5py is running against HDF5 1.14.3 when it was built against 1.14.4, this may cause problems
```
Followed by an `ImportError`.

So yeah, "custom installation" is confused by existing/older HDF5.

**Comment by royassis** [comment]
Ok. Where I install it with the same methods in a venv everything works. But when I do the same thing in a conda environment I get the following error when trying to import `h5py`:

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.11/site-packages/h5py/__init__.py", line 25, in <module>
    from . import _errors
ImportError: /home/ubuntu/.local/lib/python3.11/site-packages/h5py/_errors.cpython-311-x86_64-linux-gnu.so: undefined symbol: H5E_BADID_g
```

Any ideas how to get around this?

**Comment by tacaswell** [comment]
```
  File "/home/ubuntu/.local/lib/python3.11/site-packages/h5py/__init__.py", line 25, in <module>

```

This is where things install with `pip install --user` land.  I suspect you are also having issues where you are installing h5py into one place, but are actually getting a different version.

**Comment by itcarroll** [comment]
It should be fine to have multiple versions of h5py and hdf5 on one system, in different environments. The question is how we get h5py to see the same hdf5 libraries at runtime that it saw during build.

**Comment by itcarroll** [comment]
@royassis pip will install to ~/.local if you don't have permission to install into the active env. could that be the case (e.g. if you created the conda env as root)?

**Comment by royassis** [comment]
After reinstalling anaconda I long longer have this issue. 
This was probably the cause.
