### ISSUE TITLE
How to use a static version of libhdf5?

### ISSUE THREAD

**Issue by blochl** [h5py/h5py#2493]
I need to install h5py on an aarch64 system. `pip install` builds it from source in such a case, I guess because there are no aarch64 binaries on PyPI.
That's all fine, but my project which imports h5py needs to be statically compiled (with Nuitka) and has to be portable. On x86_64 it works fine (because h5py is installed as a binary there) but on aarch64 there is this dependency on system's **libhdf5_serial.so.103** which I can't get rid of. I tried `pip install`'ing h5py with this set:
```bash
export LDFLAGS="-L/usr/lib/aarch64-linux-gnu/hdf5/serial -Wl,-Bstatic -lhdf5 -lhdf5_hl -Wl,-Bdynamic"
```
...to no avail.

So how do I build h5py locally, with static libs? (libhdf5-dev provides both static and dynamic libs)

**Comment by tacaswell** [comment]
If the wheels to upload for other platforms work (which surprises me a bit), but the fastest path may be to build the wheel locally, run `auditwheel` on it, and then install the resulting wheel.

**Comment by blochl** [comment]
Thanks, @tacaswell, @kif!

Eventually it worked for me with the following:
```bash
export h5py_version="3.11.0"
export LDFLAGS="-Wl,-Bstatic -lhdf5 -lhdf5_hl -Wl,-Bdynamic"
curl -LfO "https://files.pythonhosted.org/packages/source/h/h5py/h5py-${h5py_version}.tar.gz"
tar -zxvf "h5py-${h5py_version}.tar.gz"
cd "h5py-${h5py_version}"
python setup.py build
python setup.py install --skip-build --optimize=1
```
