### ISSUE TITLE
Parallelization docs include links which time out for `mpi4py` 

### ISSUE THREAD

**Issue by d33bs** [h5py/h5py#2495]
Thanks for the great work with this package! I noticed while reading through the parallelization documentation at https://docs.h5py.org/en/stable/mpi.html that the links to `mpi4py` appear to time out (they reference http://mpi4py.scipy.org/). When I attempt to access that link it loads for a while and then the connection times out. I wanted to bring this up just in case it impacted others.

Maybe the links on the `h5py` docs could reference instead: https://mpi4py.readthedocs.io/en/stable/ ?

**Comment by tacaswell** [comment]
that seems reasonable, could you open a PR with that change?

**Comment by d33bs** [comment]
Thanks @tacaswell, and sure thing - I'll plan to open up a PR with a relevant change.

**Comment by d33bs** [comment]
Hi @tacaswell, on a closer look, the latest docs appear to work just fine. It's likely this has already been fixed in an earlier commit. The docs I had been looking at were the "stable" docs. Apologies for the confusion here! Let me know if there's still anything I may do to help.
