### ISSUE TITLE
Numpy __array__ DeprecationWarning

### ISSUE THREAD

**Issue by loenard97** [h5py/h5py#2497]
When reading a numpy array from a file, I am getting a DeprecationWarning from numpy on the newest h5py and numpy versions.

Minimal example:
```python
import h5py
import numpy as np


print(h5py.version.info)

with h5py.File("test.h5", "w") as file:
    file.create_dataset("test_data", data=np.linspace(0, 10))

with h5py.File("test.h5", "r") as file:
    dataset = file["test_data"]
    arr = np.array(dataset)    # DeprecationWarning occurs here, when converting a dataset to a numpy array
```

Output:
```
Summary of the h5py configuration
---------------------------------

h5py    3.11.0
HDF5    1.14.2
Python  3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   2.1.1
cython (built with) 3.0.10
numpy (built against) 2.0.0rc1
HDF5 (built against) 1.14.2

c:\<path-to-my-project>\test.py:12: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  arr = np.array(dataset)
```

I tried it with both the latest release of h5py (version 3.11.0) and with the latest commit, by installing with pip directly from this git repo. Both produce the same output.

I think this started happening when upgrading numpy to 2.0. 
The numpy migration guide has a section about how to deal with the new copy keyword [here](https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword). 

This isn't a big problem for me, but I couldn't find any other Github Issue here describing this problem, so this Issue is more an FYI to raise awareness about this. Hope this helps.

**Comment by neutrinoceros** [comment]
> I tried it with both the latest release of h5py (version 3.11.0) and with the latest commit, by installing with pip directly from this git repo. Both produce the same output.

This is surprising, the problem should in fact be resolved on the main branch (see #2416).
