### ISSUE TITLE
Large virtual datasets replace part of data with zeros

### ISSUE THREAD

**Issue by lchamp87x** [h5py/h5py#2500]
Heres my setup:
---------------------------------
 * Operating System: MacOS 14.6.1
 * Python version: 3.12.6
 * Python installed from MacPorts
 * h5py version: 3.11.0 (I initially had h5py installed from pip, but also tried installing from a clone of the master branch)
 * HDF5 version: 1.14.4.3_0 (installed from MacPorts)

Summary of the h5py configuration:
---------------------------------

h5py    3.11.0
HDF5    1.14.4
Python  3.12.6 (main, Sep  7 2024, 05:15:33) [Clang 15.0.0 (clang-1500.1.0.2.5)]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.26.4
cython (built with) 3.0.11
numpy (built against) 2.1.1
HDF5 (built against) 1.14.4

Issue:
---------------------------------

So just as the title suggests, I am combining multiple datasets existing in separate .hdf5 files into virtual datasets and saving these virtual datasets into a single .hdf5 file. When loading the the data into memory (either the whole thing, or slices) a large portion of the data is replaced with 0s. 

Below is an example of me loading one of the datasets "labels", 
<img width="747" alt="Screenshot 2024-09-20 at 3 57 39 PM" src="https://github.com/user-attachments/assets/6d4f2813-6524-4f9f-8ac6-dcab19f33707">

The values of "labels" should only be 1 and 0.5 (i.e., there should be no 0s). I also already confirmed that it is not just turning the 0.5s into 0s, both 1s and 0.5s are being replaced. This dataset has 367588 data points (i.e., its shape is (367588,)) and I tried seeing what happens if I include less datapoints when building the virtual dataset. It seems that this behavior happens when the number of datapoints is larger than about 12,000. This threshold is slightly different with some of my other virtual datasets that have different shapes. 

I have confirmed that the data in the actual datasets within the seperate .hdf5 files are completely intact. So the data corruption/replacement is happening when specifically building the virtual datasets. Below is the script I am using,

```
import argparse
import sys
import os

sys.path.insert(0, os.path.abspath("../.."))
from pathlib import Path

import h5py
from argformat import StructuredFormatter
import numpy as np
from transformers.data_utils.bb_data_loading import load_list


def main(argv):
    parser = argparse.ArgumentParser(
        description="Combines preference data for multiple participants. \nThe combined datasets are virtual \n(see https://docs.h5py.org/en/latest/vds.html) \nand are externally linked to the \ninvidiual preference data files. \nRenaming, Modifying, deleting, or moving any of the \nfiles that comprise the virtual datasets \nmay cause undefined behavior.",
        formatter_class=StructuredFormatter,
    )
    parser.add_argument(
        "p_id",
        metavar="PID",
        type=str,
        help="A .txt file containing a list of Participant IDs to process",
    )
    parser.add_argument(
        "-d",
        "--data_dir",
        type=str,
        default="~/busy-beeway/transformers/preference_data_1",
        help="Data Directory for participant preference data.",
    )
    parser.add_argument(
        "-s",
        "--save_file",
        type=str,
        default="~/busy-beeway/transformers/preference_data/bbway1.hdf5",
        help="Name and location of outputted file",
    )
    args = parser.parse_args(argv)
    p_id = load_list(args.p_id)
    data_dir = os.path.expanduser(args.data_dir)
    save_file = os.path.expanduser(args.save_file)
    data_sizes = []
    segment_sizes = []
    feature_sizes = []
    for p in p_id:
        with h5py.File(f"{data_dir}/{p}.hdf5") as f:
            d, s, f = f["observations"].shape
            data_sizes.append(d)
            segment_sizes.append(s)
            feature_sizes.append(f)
    if not np.all(np.array(segment_sizes) == segment_sizes[0]):
        raise ValueError("All segment lengths must be the same!")
    if not np.all(np.array(feature_sizes) == feature_sizes[0]):
        raise ValueError("The feature dimension must be the same across all datasets!")

    d_s_sum = sum(data_sizes)
    o_layout = h5py.VirtualLayout(
        shape=(d_s_sum, segment_sizes[0], feature_sizes[0]), dtype="<f8"
    )
    t_layout = h5py.VirtualLayout(shape=(d_s_sum, segment_sizes[0]), dtype="<i4")
    am_layout = h5py.VirtualLayout(shape=(d_s_sum, segment_sizes[0]), dtype="<f4")

    o_2_layout = h5py.VirtualLayout(
        shape=(d_s_sum, segment_sizes[0], feature_sizes[0]), dtype="<f8"
    )
    t_2_layout = h5py.VirtualLayout(shape=(d_s_sum, segment_sizes[0]), dtype="<i4")
    am_2_layout = h5py.VirtualLayout(shape=(d_s_sum, segment_sizes[0]), dtype="<f4")

    l_layout = h5py.VirtualLayout(shape=(d_s_sum,), dtype="<f8")
    prev_size = 0
    for i, p in enumerate(p_id):
        o_vsource = h5py.VirtualSource(
            f"{data_dir}/{p}.hdf5",
            "observations",
            shape=(data_sizes[i], segment_sizes[i], feature_sizes[i]),
        )
        t_vsource = h5py.VirtualSource(
            f"{data_dir}/{p}.hdf5", "timesteps", shape=(data_sizes[i], segment_sizes[i])
        )
        am_vsource = h5py.VirtualSource(
            f"{data_dir}/{p}.hdf5", "attn_mask", shape=(data_sizes[i], segment_sizes[i])
        )

        o_2_vsource = h5py.VirtualSource(
            f"{data_dir}/{p}.hdf5",
            "observations_2",
            shape=(data_sizes[i], segment_sizes[i], feature_sizes[i]),
        )
        t_2_vsource = h5py.VirtualSource(
            f"{data_dir}/{p}.hdf5",
            "timesteps_2",
            shape=(data_sizes[i], segment_sizes[i]),
        )
        am_2_vsource = h5py.VirtualSource(
            f"{data_dir}/{p}.hdf5",
            "attn_mask_2",
            shape=(data_sizes[i], segment_sizes[i]),
        )

        l_vsource = h5py.VirtualSource(
            f"{data_dir}/{p}.hdf5", "labels", shape=(data_sizes[i],)
        )

        o_layout[prev_size : (prev_size + data_sizes[i]), :, :] = o_vsource
        t_layout[prev_size : (prev_size + data_sizes[i]), :] = t_vsource
        am_layout[prev_size : (prev_size + data_sizes[i]), :] = am_vsource

        o_2_layout[prev_size : (prev_size + data_sizes[i]), :, :] = o_2_vsource
        t_2_layout[prev_size : (prev_size + data_sizes[i]), :] = t_2_vsource
        am_2_layout[prev_size : (prev_size + data_sizes[i]), :] = am_2_vsource

        l_layout[prev_size : (prev_size + data_sizes[i])] = l_vsource

        prev_size = data_sizes[i]

    with h5py.File(save_file, "w") as f:
        f.create_virtual_dataset("observations", o_layout)
        f.create_virtual_dataset("timesteps", t_layout)
        f.create_virtual_dataset("attn_mask", am_layout)

        f.create_virtual_dataset("observations_2", o_2_layout)
        f.create_virtual_dataset("timesteps_2", t_2_layout)
        f.create_virtual_dataset("attn_mask_2", am_2_layout)
        f.create_virtual_dataset("labels", l_layout)
    sys.exit(0)


if __name__ == "__main__":
    main(sys.argv[1:])
```
So its loading each separate file which contains 7 datasets, "observations", "timesteps", "attn_mask", "observations_2", "timesteps_2", "attn_mask_2", and "labels". This script creates 7 virtual datasets that are a combination of the 7 in each file. 

Initially, the separate files had a compression filter (lzf). I tried removing the compression filter and disabling chunked storage. This did not resolve the issue. Likewise, I initially had the version of h5py from pip. So, I tried installing the latest HDF5 library from Macports and installed h5py from the master branch. This also did not resolve the issue. The only thing has worked so far is to just creating smaller virtual datasets. This technically is a feasible workaround to my issue, but I worry it would slow down my data loader. 

This seems very similar to #2394 except the size of the slice that you load does not affect the behavior I am getting. Loading a slice of any size past a certain index results in the data being replaced with 0s.

**Comment by neutrinoceros** [comment]
If it's indeed the same bug as #2394, I would expect you need to install HDF5 from it's dev branch to get around it, and v1.14.5 when it's available. Can you give it a try ?

**Comment by lchamp87x** [comment]
Actually, really sorry for wasting your time. I made a dumb little typo in my code. 

`prev_size = data_sizes[i]`

Should be 

`prev_size += data_sizes[i]`

And it all works now. Essentially, I was just not incrementing the indexing in the virtual layout correctly, which was causing the virtual datasets not to be filled properly. I suspect that this caused empty space in the virtual datasets and that empty space was filled with zeros. It took me 3 days to find that typo.

**Comment by neutrinoceros** [comment]
> It took me 3 days to find that typo.

This is very relatable, and I'm glad you found it !
