### ISSUE TITLE
h5py 3.12: file locking broken on ubuntu/linux

### ISSUE THREAD

**Issue by sneakers-the-rat** [h5py/h5py#2506]
File locking is broken in h5py 3.12 with an error message that i can't find being raised in prior issues or via a stackexchange search:

```
src/numpydantic/interface/hdf5.py:218: in __setitem__
    with h5py.File(self.file, "r+", locking=True) as h5f:
/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/site-packages/h5py/_hl/files.py:561: in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/site-packages/h5py/_hl/files.py:237: in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
h5py/_objects.pyx:54: in h5py._objects.with_phil.wrapper
    ???
h5py/_objects.pyx:55: in h5py._objects.with_phil.wrapper
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   OSError: Unable to synchronously open file (file locking 'ignore disabled locks' flag values don't match)

h5py/h5f.pyx:102: OSError
```

Here's a failing CI run for reference: https://github.com/p2p-ld/numpydantic/actions/runs/11041777444/job/30672788866?pr=26#step:6:44

The code to reach there is somewhat convoluted but it reduces to this:

```python
file = "some_existing_hdf5_file.h5"
path = "/some/dataset/within/the/file"
key: slice | int | tuple[int | slice] = 0 # some slice into the dataset

with h5py.File(file, "r+", locking=True) as h5f:
    obj = h5f.get(path)
    obj[key] = value
```

so nothing fancy, and the error is raised when opening the file, rather than when trying to assign to the dataset.

There isn't concurrent access in the test when it runs, and a new hdf5 file is created for each test function, so I think this is something intrinsic to the way h5py is doing locking in 3.12.

The issue also seems specific to ubuntu (or linux, i can't tell how general), as the mac tests from that CI run pass (the windows tests fail because of https://github.com/h5py/h5py/issues/2505 )

here's a diff of the last run that didn't have this error message with the first that did have it, the changes here are unrelated to the bug, and the only difference is the h5py version (3.11 vs 3.12): https://github.com/p2p-ld/numpydantic/compare/1cf69eb..f376836
- `1cf69eb` - last working run - https://github.com/p2p-ld/numpydantic/actions/runs/11009045070 - [h5py==3.11.0](https://github.com/p2p-ld/numpydantic/actions/runs/11009045070/job/30567864107#step:4:82)
- `f376836` - first failing run - https://github.com/p2p-ld/numpydantic/actions/runs/11041608723/job/30672233237#step:6:344 - [h5py==3.12.0](https://github.com/p2p-ld/numpydantic/actions/runs/11041608723/job/30672233237#step:4:76)

To assist reproducing bugs, please include the following:
 * Operating System: `ubuntu-latest` in GH actions
 * Python version (e.g. 3.10): 3.9-3.12 tested
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows): `setup-python` gh action
 * h5py version (e.g. 3.9): 3.12.0
 * HDF5 version (e.g. 1.12.2): (whatever is bundled with 3.12 or installed on ubuntu)

**Comment by takluyver** [comment]
I wasn't immediately able to reproduce this on Fedora. I created an example file with:

```python
f = h5py.File("test.h5", "w")
f['dataset'] = np.arange(50).reshape(5, 10)
f.close()
```

And then I modified your example to this:

```python
import h5py
print(h5py.version.info)

file = "test.h5"
path = "dataset"
key: slice | int | tuple[int | slice] = 0 # some slice into the dataset
value = 7

with h5py.File(file, "r+", locking=True) as h5f:
    obj = h5f.get(path)
    obj[key] = value
```

Can you confirm that you can reproduce it with a little standalone example like this, or is it something that's only happening in your test suite?

**Comment by takluyver** [comment]
It looks like the error comes from [this line in HDF5](https://github.com/HDFGroup/hdf5/blob/7d40520a55e672ec1907863d66a0f7937c9ad60f/src/H5Fint.c#L2007). That appears to mean that the file is already open, you're trying to open it with a second locking option set, and HDF5 is refusing to do that.

Looking at your tests, I think the `hdf5_file` fixture creates the file and then keeps it open while the test runs, with the default locking behaviour (which appears to be to try locking but ignore errors), and then the test tries to open it with `locking=True` (which means it doesn't ignore errors).

So I don't think there's a bug here. Probably earlier versions of HDF5 silently did something wrong/confusing in this scenario, and the newer version we're now bundling errors instead. If so, you'll need to change your tests to either open the file with the same locking option, reuse the existing file object, or close the first file object before opening it again.

**Comment by sneakers-the-rat** [comment]
ah, i was under the impression that `locking=True` calls would only lock against other `locking=True` calls, i'll try that in the morning

**Comment by sneakers-the-rat** [comment]
thanks for taking the time to look into this and explain it :). shouldn't be too big of a change, that's the only time the file stays open anyway. assuming i can fix it in the morning (or update with a different error message), i'll close this unless y'all see a need for a reminder in the docs

**Comment by takluyver** [comment]
Thanks!

I think I'd leave it out of the docs for now - it's a really fiddly little detail to explain, and the specific locking thing may well be gone in future HDF5 versions anyway. But if more people run into it, I'd reconsider that.

**Comment by sneakers-the-rat** [comment]
that did it, d'oh XD
https://github.com/p2p-ld/numpydantic/pull/28

sorry for the false alarm, and thanks again for your patience. i'll close this and hopefully the issue will be discoverable if people search the error text
