### ISSUE TITLE
Updates for Cython's deprecation of conditional compilation

### ISSUE THREAD

**Issue by jakirkham** [h5py/h5py#2510]
In upstream issue ( https://github.com/cython/cython/issues/4310 ), Cython signaled it plans to drop [conditional compilation]( http://docs.cython.org/en/latest/src/userguide/language_basics.html#conditional-compilation ). IOW the use of `DEF` and `IF` in Cython code. They put together [some alternatives]( https://docs.cython.org/en/latest/src/userguide/migrating_to_cy30.html#deprecation-of-def-if )

<hr>

It looks like `h5py` currently uses `DEF` as part of the build process

https://github.com/h5py/h5py/blob/c783fd18f7209a8e1e9f127534a25f8a7071d750/setup_build.py#L158-L169

Potentially this could be turned into a C header file (like `config.h`) using `#define` instead. Also `tuple`s (like `VOL_MIN_HDF5_VERSION`) may need to be rewritten as C arrays, C strings, or split into components using `*_MAJOR`,  `*_MINOR`, and `*_PATCH` variables. Of course strings will need `"..."` instead of `'...'`. These can then be `cdef extern`ed into `config.pxi`, which is already used throughout. That may just work without lots of other changes

<hr>

There are usages of `IF` in `cdef extern`s which could likely just be dropped and the `IF` in the code could just be `if`. Cython doesn't parse the header files to check when variables are defined (it just trusts the definition provided) nor does it include this in the C code (it is just a guide for the Cython build process). The C compiler will be able to identify whether the `if` is used or not during compilation and will handle inclusion/exclusion then

https://github.com/h5py/h5py/blob/c783fd18f7209a8e1e9f127534a25f8a7071d750/h5py/api_types_ext.pxd#L54-L57

https://github.com/h5py/h5py/blob/c783fd18f7209a8e1e9f127534a25f8a7071d750/h5py/h5t.pyx#L1582-L1588

<hr>

Other conditional compilation bits probably can use `cdef enum` to get the intended behavior. The typing appears unused in this case. So could be dropped in favor of using `object`

https://github.com/h5py/h5py/blob/c783fd18f7209a8e1e9f127534a25f8a7071d750/h5py/_objects.pyx#L17-L18

https://github.com/h5py/h5py/blob/c783fd18f7209a8e1e9f127534a25f8a7071d750/h5py/_objects.pyx#L40-L43

<hr>

Of course this is not comprehensive. There is other code that may need similar treatment or perhaps different handling depending on the intended usage. In any event hopefully this is helpful in raising awareness about this coming change in Cython and how it could be handled here

**Comment by jakirkham** [comment]
Oops had missed issue ( https://github.com/h5py/h5py/issues/2445 ). Will go ahead and close as a duplicate

If it makes sense, this could be copied over there

**Comment by neutrinoceros** [comment]
Thanks @jakirkham ! We've been making progress on this problem recently but your insight is absolutely helpful. Please go ahead and copy it over the original issue.
