### ISSUE TITLE
OSError: Unable to synchronously open file (file signature not found)

### ISSUE THREAD

**Issue by sofiapuvogelvittini** [h5py/h5py#2513]
Hello, thanks for this package!
I am usign it to open h5 files generated by MaxWell biosystems. Most of the time, I do not have problems opening the h5 files, however, for some of them I get the following error:

```
**"File ~/anaconda3/envs/si_env/lib/python3.11/site-packages/h5py/_hl/files.py:562, in File.__init__(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, fs_strategy, fs_persist, fs_threshold, fs_page_size, page_buf_size, min_meta_keep, min_raw_keep, locking, alignment_threshold, alignment_interval, meta_block_size, **kwds)
    553     fapl = make_fapl(driver, libver, rdcc_nslots, rdcc_nbytes, rdcc_w0,
    554                      locking, page_buf_size, min_meta_keep, min_raw_keep,
    555                      alignment_threshold=alignment_threshold,
    556                      alignment_interval=alignment_interval,
    557                      meta_block_size=meta_block_size,
    558                      **kwds)
    559     fcpl = make_fcpl(track_order=track_order, fs_strategy=fs_strategy,
    560                      fs_persist=fs_persist, fs_threshold=fs_threshold,
    561                      fs_page_size=fs_page_size)
--> 562     fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
    564 if isinstance(libver, tuple):
    565     self._libver = libver

File ~/anaconda3/envs/si_env/lib/python3.11/site-packages/h5py/_hl/files.py:235, in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    233     if swmr and swmr_support:
    234         flags |= h5f.ACC_SWMR_READ
--> 235     fid = h5f.open(name, flags, fapl=fapl)
    236 elif mode == 'r+':
    237     fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

File h5py/_objects.pyx:54, in h5py._objects.with_phil.wrapper()

File h5py/_objects.pyx:55, in h5py._objects.with_phil.wrapper()

File h5py/h5f.pyx:102, in h5py.h5f.open()

OSError: Unable to synchronously open file (file signature not found)"**
```
This error apears when using more recent h5py versions in a linux machine
h5py 3.10.0 or 3.12.1 and python 3.11

However, I am able to open it a windows machine that has an older version of h5py  h5py=3.1.0 and  hdf5=1.10.6.
I need to make this work on the linux machine. Would you please help me figure out what could be wrong with my files that only can be read with the older versions of h5py?

I have included here two data files, one that works with any version (data.raw.h5) and the one not working with updated h5py in linux (not_working_data.raw.h5)
https://drive.google.com/drive/folders/1m894FGkguipBtu5CofbeQ-z765F8sk7T?usp=sharing

Thank you very much for your time!

**Comment by ajelenak** [comment]
Do you have HDF5 command-line tools (_h5dump_ or _h5ls_) available on the computer where you get this error? If so, can you run `h5dump -H` or `h5ls -r` on file(s) that failed to open? Also report the output of `h5dump --version` or `h5ls --version`.

**Comment by takluyver** [comment]
I have downloaded your `not_working_data.h5` example, but I can read it with h5py 3.12.1 on Linux.

Is your code that opens the file doing anything special? Can you try in a fresh process just doing:

```python
import h5py
f = h5py.File("not_working_data.h5")
```

How did you install h5py?

**Comment by sofiapuvogelvittini** [comment]
Thanks for yout help!
I don;t understand why I cna not open it then...
when running "h5ls -r not_working_data.h5" I get unable to open file. And with "h5ls --version" I get Version 1.14.3
trying "f = h5py.File("not_working_data.h5")" returns same error of file signature not found. 
I have attached a pdf with screenshot of all the outputs. 
I installed it using pip install h5py, and then I tried conda install h5py, both under a conda environment. But none worked with this file. 
[h5py_error.pdf](https://github.com/user-attachments/files/17279974/h5py_error.pdf)

**Comment by takluyver** [comment]
And just to check, the file you're trying to open as `data.raw.h5` is the same one you uploaded as `not_working_data.h5` (~670 MB)?

**Comment by takluyver** [comment]
Then I'm mystified. I'd say it's a problem with the file itself, since h5ls also fails, but that doesn't explain why I can open the same file. I hope @ajelenak can think of something.

**Comment by sofiapuvogelvittini** [comment]
h5dump also failed, and the version of h5dump is 1.10.6

**Comment by ajelenak** [comment]
What is the output of `xxd -l 8 not_working_data.h5`?

**Comment by sofiapuvogelvittini** [comment]
With this I can see something interesting...
For the files that do not work, xxd -l 8 not_working_data.h5 returns 0000 0000 0000 0000,
but for the files that work I see 8948 4446 0d0a 1a0a. 
Attached some screenshots...
[h5py_error_xxd.pdf](https://github.com/user-attachments/files/17281291/h5py_error_xxd.pdf)

**Comment by sofiapuvogelvittini** [comment]
Would this 0000 0000 0000 mean that they are not h5 files? but then why [takluyver](https://github.com/takluyver) can open them or why I can still open them in the windows machine?

**Comment by ajelenak** [comment]
> Would this 0000 0000 0000 mean that they are not h5 files?

Yes or damaged HDF5 files.

> but then why [takluyver](https://github.com/takluyver) can open them or why I can still open them in the windows machine?

That file is HDF5.

**Comment by takluyver** [comment]
Yup, the file you shared as `not_working_data.h5` starts with the expected `8948 4446`. So either the filesystem or the operating system is broken somehow, and not accessing the real file data, or that's a different file.

**Comment by sofiapuvogelvittini** [comment]
Thank you very much for your help. It is quite strange because I transferred the files to a Linux virtual machine using Microsoft Azure, and I have tried this multiple times. The files that do not work and lose the sequence 8948 4446 0d0a 1a0a after being transferred are consistently the same ones. I don’t know why. Thank you!

**Comment by takluyver** [comment]
I see from your screenshots that the file is under `/mnt`, which often means that it's being pulled in from somewhere outside the main system that you're running on. If you've set up the mount yourself, try unmounting & remounting the filesystem, or even rebooting the node.

If you didn't set it up yourself, you might want to try contacting the administrators or local support for the system you're running on, and tell them that you seem to be having problems accessing files in this folder.

**Comment by sofiapuvogelvittini** [comment]
Thank you very much for the hint! I'm not exactly sure why, but the file was getting corrupted when transferred to certain directories inside the mnt, but not in other locations. I was finally able to open them. Thanks!
