### ISSUE TITLE
h5py 3.12: `KeyError` with in-memory files using `io.BytesIO` and `ExternalLink`

### ISSUE THREAD

**Issue by paulmueller** [h5py/h5py#2514]
With h5py 3.12, I am encountering KeyErrors in an edge case where I am using `h5py.File` on top of `io.BytesIO` and writing `ExternalLink` to that in-memory file.

Since this code worked with h5py 3.11 and earlier, I believe this is a bug. Please let me know if I am doing something fundamentally wrong here and I will adapt my code instead :+1: .

Here is a script to reproduce the errors (works with h5py 3.11 and fails with h5py 3.12) including the error messages I get as comments. The difference between the two methods is that in the first case, the link is created in the root of the in-memory file, and in the second case the link is created in a subgroup.

```python

import io
import pathlib

import h5py
import numpy as np
import tempfile


def test_unable_to_open_object_component_not_found():
    path = pathlib.Path(tempfile.mkdtemp(
        prefix="h5py_test_unable_to_open_object_component_not_found_")) / "test.rtdc"
    fd = io.BytesIO()

    with h5py.File(path, "w", libver="latest") as h5:
        h5["subdir/data"] = np.arange(100)

    with h5py.File(fd, "w", libver="latest") as h5:
        h5["data"] = h5py.ExternalLink(str(path), f"/subdir/data")

    with h5py.File(fd, "r") as h5:
        # The following raises:
        #   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
        #   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
        #   File "/home/paul/repos-work/DC/dclab/.env/lib/python3.11/site-packages/h5py/_hl/group.py", line 357, in __getitem__
        #     oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
        #           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        #   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
        #   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
        #   File "h5py/h5o.pyx", line 257, in h5py.h5o.open
        # KeyError: 'Unable to synchronously open object (component not found)'
        print(h5["data"])


def test_cant_find_object_too_many_links():
    path = pathlib.Path(tempfile.mkdtemp(
        prefix="h5py_test_cant_find_object_too_many_links_")) / "test.rtdc"
    fd = io.BytesIO()

    with h5py.File(path, "w", libver="latest") as h5:
        h5["subdir/data"] = np.arange(100)

    with h5py.File(fd, "w", libver="latest") as h5:
        h5["subdir/data"] = h5py.ExternalLink(str(path), f"/subdir/data")

    with h5py.File(fd, "r") as h5:
        # The following raises:
        #   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
        #   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
        #   File "/home/paul/repos-work/DC/dclab/.env/lib/python3.11/site-packages/h5py/_hl/group.py", line 357, in __getitem__
        #     oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
        #           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        #   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
        #   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
        #   File "h5py/h5o.pyx", line 257, in h5py.h5o.open
        # KeyError: "Can't find object (too many links)"
        print(h5["subdir/data"])


print(f"h5py version: {h5py.__version__}")
#test_unable_to_open_object_component_not_found()
test_cant_find_object_too_many_links()

```

To assist reproducing bugs, please include the following:
 * Affects maxOS, Windows and Linux
 * Python version: tested on 3.11 and 3.12
 * Where Python was acquired: system Python
 * h5py version: 3.12.1
 * HDF5 version: 1.14.4

```
Summary of the h5py configuration
---------------------------------

h5py    3.12.1
HDF5    1.14.4
Python  3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   2.1.2
cython (built with) 3.0.11
numpy (built against) 2.1.1
HDF5 (built against) 1.14.4

```

**Comment by takluyver** [comment]
This might be a change in the bundled HDF5 version, or it might be related to #2433.

One of the cases for accessing external links is to use a pathname relative to the current filename, so it's not entirely surprising that it might go wrong with an HDF5 file that doesn't exist on disk at all. Check that your external link is created with an absolute path (I think it is, based on your code, but double check).

If you want an ephemeral HDF5 file, you might want to use the 'core' driver with `backing_store=False` to create a file purely in memory, or make a temp file for it - modern OSs can often avoid actually writing tempfiles to permanent storage. Using a Python file-like object relies on HDF5 calling back into Python for file operations, which mostly works but is a source of problems.

**Comment by paulmueller** [comment]
OK, thanks for the clarification, this makes sense. Your last remark, that using a "Python file-like object relies on HDF5 calling back into Python for file operations" is probably the culprit.

I also noticed that the h5py docs (https://docs.h5py.org/en/stable/high/file.html#python-file-like-objects) explicitly warn about passing file-like objects. Maybe it is sufficient to update the docs then and include "things such as `ExternalLink`s might not work" or so.

I will refactor my external-link code to use temporary files or the core driver then, which seems less elegant, but apparently is much cleaner. Thanks!

As a side note (not related to this issue): In general, I think supporting file-like Python objects is a very powerful concept, as it allows you to creatively extend h5py e.g. to use a file-like wrapper around URLs with h5py (https://github.com/DC-analysis/dclab/blob/0.61.5/dclab/http_utils.py#L30). Thus, a :+1: from my side for keeping this functionality in h5py, even if it is apparently quite quirky.

**Comment by tacaswell** [comment]
I am very much in favor of keeping it, but its use is very much "at your own risk". 

I'm :+1: on adding an explicit note about external references and maybe re-arranging that section of the docs so the first thing is a warning.  We should give the vibe "this can solve some very specific problems, but you are juggling multiple loaded foot-cannons".

**Comment by takluyver** [comment]
I'd rather not mention external links specifically right now, because a) we don't *know* that file-like objects are the cause, it's just a good guess, and b) it may be a specific bug in HDF5 which gets fixed again fairly soon.

I'm happy to rearrange that section, e.g. move the generic 'juggling foot-cannons' warning from the bottom above the more specific warnings. But I also suspect the impact is pretty limited, because a lot of people probably discover this feature without reading the docs.

Maybe it would help a bit if we had some nicer high-level API for working with the `core` driver without a backing file? It's possible to construct a file in memory and get a copy as bytes, but we don't make that obvious, and it's possible to convert bytes in memory back into an h5py File object, but you need to dive into the low-level API for that.

**Comment by tacaswell** [comment]
> It's possible to construct a file in memory and get a copy as bytes, but we don't make that obvious, and it's possible to convert bytes in memory back into an h5py File object, but you need to dive into the low-level API for that.

I did not know we could do that.

**Comment by takluyver** [comment]
I think so! `File(..., driver='core', backing_store=False)` creates a purely in-memory file which doesn't get written to disk. `f.id.get_file_image()` gives you a copy of the file data as bytes, and `fapl.set_file_image()` should let you 'open' bytes as a new file object.

I'll work on a PR for a better high-level API for this.

**Comment by takluyver** [comment]
#2517 is that PR.
