### ISSUE TITLE
Wrong number of arguments in call to `run()` in api_gen.py.

### ISSUE THREAD

**Issue by schwehr** [h5py/h5py#2533]
To assist reproducing bugs, please include the following:
 * Operating System : debian testing derivative
 * Python version (e.g. 3.10): 3.11
 * Where Python was acquired - custom
 * h5py version (e.g. 3.9): head
 * HDF5 version (e.g. 1.12.2): 1.12.2
 * The full traceback/stack trace shown (if it appears)

The error trace:

```
h5py/api_gen.py", line 328, in <module>
    run()
TypeError: run() missing 1 required positional argument: 'config'
```

Nothing above really matters. The issue is that the call doesn't have the right number of args from here:

https://github.com/h5py/h5py/blob/35e68c16760bbd28f9909e6af93c2a476c15a6b8/api_gen.py#L321-L327

```python
def run(config):  # <-- config option without a 
    lp = LineProcessor(config)
    lp.run()


if __name__ == '__main__':
    run()  # <-- No config arg passed.
```

I don't see anything about passing a config in the source:

```
find . -type f | grep -v git/ | xargs grep api_gen.py
./api_gen.py:# Warning: this file is auto-generated from api_gen.py. DO NOT EDIT!
./api_gen.py:# Warning: this file is auto-generated from api_gen.py. DO NOT EDIT!
./api_gen.py:# Warning: this file is auto-generated from api_gen.py. DO NOT EDIT!
./docs/whatsnew/3.12.rst:  ``api_gen.py`` should be run automatically to recreate this (:pr:`2479`,
./docs/contributing.rst:2. Auto-generated Cython wrappers for the C API (``api_gen.py``)
./docs/contributing.rst:run the file ``api_gen.py`` to re-generate the Cython wrappers from
./docs/contributing.rst:    $ python api_gen.py
./MANIFEST.in:include api_gen.py
./h5py/api_functions.txt:# Defines the HDF5 C API functions wrapped by h5py. See also api_gen.py.
```

**Comment by neutrinoceros** [comment]
Whoops this is clearly an oversight from #2480
fixed in #2534.
Thanks for reporting !
