### ISSUE TITLE
TypeError raised when setting list of unicodes as attribute

### ISSUE THREAD

**Issue by ppinard** [h5py/h5py#289]
I get the following TypeError when trying to set an attribute as a list of unicodes. 

f = h5py.File("foo.h5", "w")
f.attrs['bar'] = [u'\u03b2', u'\u03b2', u'\u03b3']

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/h5py-2.1.2-py2.7-linux-x86_64.egg/h5py/_hl/attrs.py", line 56, in __setitem__
    self.create(name, data=value, dtype=base.guess_dtype(value))
  File "/usr/local/lib/python2.7/dist-packages/h5py-2.1.2-py2.7-linux-x86_64.egg/h5py/_hl/attrs.py", line 102, in create
    htype = h5t.py_create(dtype, logical=True)
  File "h5t.pyx", line 1361, in h5py.h5t.py_create (h5py/h5t.c:11451)
  File "h5t.pyx", line 1439, in h5py.h5t.py_create (h5py/h5t.c:11361)
TypeError: No conversion path for dtype: dtype('<U1')

h5py: 2.1.2
python: 2.7.3

**Comment by alexbw** [comment]
+1

**Comment by jakirkham** [comment]
+1

**Comment by matteobachetti** [comment]
+1

**Comment by graingert** [comment]
>  We are discussing ways to address this.

@andrewcollette Where are those discussions?

**Comment by andrewcollette** [comment]
@graingert there were periodic discussions on the mailing list, although that comment was 3 years ago.  Unicode in HDF5 is something of a mess, unfortunately.  There simply isn't a destination type for "U", so logic would have to be added to store as vlen strings instead.

**Comment by guddulrk** [comment]
if use_htype is None:
                htype = h5t.py_create(original_dtype, logical=True)
                htype2 = h5t.py_create(original_dtype)  # Must be bit-for-bit representation rather than logical
            else:
                htype = use_htype
                htype2 = None


and I am getting following error 
TypeError: No conversion path for dtype: dtype('<U12')

Any help please..

**Comment by aragilar** [comment]
@guddulrk You need to pre-encode your strings as UTF-8, as per https://github.com/h5py/h5py/issues/289#issuecomment-17015083. See also http://docs.h5py.org/en/latest/strings.html.

**Comment by jhollowed** [comment]
It is many years later and this is still an issue, with seemingly no posted solution other than what is mentioned on this page; can there not be some simple exception handling inside of the call to `attrs.create` that handles the encoding? Storing a unicode string as an attribute sounds like trivial and expected behavior.

**Comment by dpfoose** [comment]
Still an issue in Sep 2017. The python 3 ```str``` type is utf-8, so this has to be done for every string attribute. Apparently fixed-length ascii strings are used more often in HDF5, so if you don't need unicode, you can just convert your strings to numpy.string_.
I used the same solution as suggested, but had to use ```vlen=str``` instead of ```vlen=unicode``` for python 3:
keeping utf-8:
```f.attrs.create(key, value, dtype=h5py.special_dtype(vlen=str))```
Converting to ASCII:
```f.attrs[key] = numpy.string_(value)``` for single value
```f.attrs[key] = [numpy.string_(i) for i in value]``` for list of values

**Comment by pixieDoug** [comment]
With python 3, I still get errors when converting to str:
filename = os.path.expanduser(args.output_filename)
            print('Writing attribute vectors, latent variables and attributes to %s' % filename)
            mdict = {'latent_vars':latent_vars, 'attributes':attributes, 
                     'fields':fields, 'attribute_vectors':attribute_vectors }
            with h5py.File(filename, 'w') as f:
                for key, value in iteritems(mdict):
                     dt = h5py.special_dtype(vlen=str)
                   f.create_dataset(key, data=value, dtype=dt)
 
TypeError: Operation not defined for data type class (operation not defined for data type class)
Same error when changing the vlen to 'bytes'. 

Original code: f.create_dataset(key, data=value) was giving error: No conversion path for dtype: dtype('<U19')

Does the create_dataset function using a dictionary not work with unicodes?

**Comment by aragilar** [comment]
@pixieDoug Please see https://github.com/h5py/h5py/issues/289#issuecomment-291039359, #624 is your actual problem.

**Comment by pixieDoug** [comment]
@aragilar Thank you.  Still 4 days into this and am not getting it. I still have the error. Recommend guidance on StackOverflow?

**Comment by dougb1102** [comment]
The work-around doesn't appear to be working for me.  When I try to encode as follows:

filename = os.path.expanduser(args.output_filename)
            print('Writing attribute vectors, latent variables and attributes to %s' % filename)
            str_type = h5py.new_vlen(str)
            mdict = {'latent_vars':latent_vars.encode('utf8'), 'attributes':attributes.encode('utf8'), 
                     'fields':fields.encode('utf8'), 'attribute_vectors':attribute_vectors.encode('utf8') }
            
                        with h5py.File(filename, 'w') as f:
                for key, value in iteritems(mdict):
                    f.create_dataset(key, data=value, dtype=str_type)

I also tried to encode as follows and still the same result:

#dtypes=[('latent_vars',np.dtype(bytes),),('attributes',np.dtype(bytes),), ('fields',np.dtype(bytes),),('attribute_vectors',np.dtype(bytes),)]
            f = h5py.File(filename, 'w')
           f.attrs.create('latent_vars', latent_vars, dtype=h5py.special_dtype(vlen=str))
            f.attrs.create('attributes', attributes, dtype=h5py.special_dtype(vlen=str))
           f.attrs.create('fields', fields, dtype=h5py.special_dtype(vlen=str))
            f.attrs.create('attribute_vectors', attribute_vectors, dtype=h5py.special_dtype(vlen=str))
            with h5py.File(filename, 'w') as f:
                for key, value in iteritems(mdict):
                    f.create_dataset(key, data=value)
```
