### ISSUE TITLE
python3: attributes are byte strings

### ISSUE THREAD

**Issue by jeremysanders** [h5py/h5py#379]
There seems to be an attribute problem with python3 h5py (2.2.1). Reading text attributes produces bytestrings:

```
$ python2
Python 2.7.5+ (default, Sep 19 2013, 13:48:49)
[GCC 4.8.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
>>> f = h5py.File('test.hdf5')
>>> f['testds'] = [1,2,3]
>>> f['testds'].attrs['test'] = 'hello world'

$ python3
Python 3.3.2+ (default, Oct  9 2013, 14:50:09)
[GCC 4.8.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
>>> f = h5py.File('test.hdf5')
>>> f['testds'].attrs['test']
b'hello world'
```

**Comment by titusjan** [comment]
Can I politely inform about the status of this bug? Is it a difficult issue to solve, or are there other priorities?

**Comment by profxj** [comment]
Indeed this is causing me some havoc
+1

**Comment by shoyer** [comment]
See https://github.com/h5py/h5py/pull/871 for a fix. There are a few options for the desired behavior, so if anyone has opinions about how to handle deserializing invalid ASCII, please take a look.

**Comment by tacaswell** [comment]
Going back to the original post, in both python2 and python3 you are getting back bytes and you can unconditionally call `decode` on the returned object.

**Comment by aimerson** [comment]
Has this incompatibility issue with strings been fixed yet? I'm using h5py 2.8.0 with python 3.7 and am finding that this bug is causing me so many nightmares. (Starting to wish I'd stuck with python 2.7... at least my code worked back then.)

**Comment by shoyer** [comment]
I don't think anything has changed yet, but take a look at the linked
issues. This turned out to be a bit more complicated than I initially
anticipated and I didn't have time to finish my version of the did.

**Comment by vasole** [comment]
Is it really a bug? If one wants to make sure what is written under python 2 is properly read under python 3 one does not have to write ``f['testds'].attrs['test'] = 'hello world'`` but ``f['testds'].attrs['test'] = u'hello world'`` Strings under python2 where indeed bytes unless using unicode strings. To read them back as bytes seems to me the most correct thing that can be done. One has to be aware about what is being written. For single string attributes is very straightforward to write utf-8 unicode under python2. 

Trickier is the case of arrays of strings. The h5py special dtype has also solved the issue of writing arrays of unicode strings. The code below will produce the same file under Python2 and Python3:

import sys
import h5py
import numpy
f = h5py.File('test.hdf5')
f['testds'] = [1,2,3]
a = ["Hello", "World", "!"]
if sys.version_info < (3,):
    string_dtype = h5py.special_dtype(vlen=unicode)
else:
    string_dtype = h5py.special_dtype(vlen=str)
import h5py
f['testds'].attrs['test'] = numpy.array(a. dtype=string_dtype)
f.close()

When reading back f['testds'].attrs['test'][0] returns "Hello" under Python3 and u"Hello" under Python2 that, again, are the same thing.

**Comment by shoyer** [comment]
I think this is a real problem. HDF5's ASCII encoded fixed length strings are strings, not opaque bytes -- we have other types for that. So it's quite reasonable to expect ASCII string data should be interpreted as strings.

Python 3 and NumPy don't really have a notion of ASCII encoded strings (or even UTF-8 for that matter), just bytes (arbitrary binary data) and str (Unicode strings). It's up to us to find the best equivalents to the HDF5 types.

**Comment by aparamon** [comment]
@shoyer Agree. It is quite probable that [H5T_CSET_UTF8 and H5T_CSET_ASCII may well become inter-convertible in the future](http://hdf-forum.184993.n3.nabble.com/Variable-length-string-encoding-conversion-tp4027250p4027256.html). So, while the ultimate solution is only [using Unicode and UTF-8 everywhere](http://utf8everywhere.org) (personal IMHO ;-) ), I see recognizing all, even ASCII-only HDF5 strings, as Python3 `str` the right thing to do in h5py.

@tacaswell, @aragilar Might there be serious compatibility restrictions limiting us from that?

**Comment by takluyver** [comment]
I'm not sure anything should change here. It's documented that [setting an attribute with bytes stores a variable-length ASCII string](http://docs.h5py.org/en/stable/strings.html#variable-length-ascii). So it seems reasonable that reading a scalar vlen ASCII string attribute gives you bytes back. In addition, h5py has been doing this for 5 years (just by this issue), which is a lot of backwards compatibility to break.

I don't think there's a clear abstract 'correct' choice here: Python and HDF5 have different concepts of strings. h5py either has to make the user explicitly convert between them, or map types that aren't quite equivalent for convenient use.

The people who come and comment on this thread are, unavoidably, the people who want that mapping to change. The people who like the current mapping won't go looking for issues about it, so we're unlikely to hear from them here.

In situations like this, my preference is always to let precedent win. Even if this behaviour isn't the best possible, I think it's better for h5py 2.9 to behave the same way as 2.8 (and earlier versions) than to make an incompatible change and introduce new possible confusions.

**Comment by vasole** [comment]
I'm with takluyver in the sense that we have learned to live with that behavior but I would like to add that when python 2 gets dropped (1 year?) the problem reported here disappears because under Python3 writing bytes gets back bytes when reading and writing strings get back strings.

The ambiguity is with python 2 where strings and bytes are the same thing and if one does not take care one gets back bytes under python3 when sometimes one would expect strings. Python 3 developers have learned to deal with it when reading and python 2 developers should fix their code if they expect to be writing strings by writing unicode.

**Comment by shoyer** [comment]
> I don't think there's a clear abstract 'correct' choice here: Python and HDF5 have different concepts of strings. h5py either has to make the user explicitly convert between them, or map types that aren't quite equivalent for convenient use.

This is true... but I think it's a stretch consider `bytes` a string type on Python 3.

> In situations like this, my preference is always to let precedent win. Even if this behaviour isn't the best possible, I think it's better for h5py 2.9 to behave the same way as 2.8 (and earlier versions) than to make an incompatible change and introduce new possible confusions.

In general I agree. This behavior has lasted long enough that it should probably be considered a feature rather than a bug. That said, it's a feature we should change :).

Would it be reasonable to break this behavior for a major version release like h5py 3.0? I think improved string handling would be a pretty welcome change.

> I'm with takluyver in the sense that we have learned to live with that behavior but I would like to add that when python 2 gets dropped (1 year?) the problem reported here disappears because under Python3 writing bytes gets back bytes when reading and writing strings get back strings.

I don't think it's really true that this problem goes away when we drop Python 2 support -- there are lots of non-Python applications still writing HDF5 files, and plenty of HDF5 files written with Python 2 that are still archived. It is a slightly unreasonable to expect non-Python applications to adhere to h5py's convention rather than HDF5 conventions, which are unambiguous that ASCII attributes are strings.

**Comment by vasole** [comment]
On 10.11.2018 21:29, Stephan Hoyer wrote:
> I don't think it's really true that this problem goes away when we
> drop Python 2 support -- there are lots of non-Python applications
> still writing HDF5 files

If those applications are writing byte strings, why should one decide to 
read them as something else than what it was written?

The problem reported here is almost 100% Python 2 specific because 
people think they are writing strings when they are writing bytes.

**Comment by takluyver** [comment]
I think a change of this magnitude would be reasonable for a 3.0 release, but it's not clear to me exactly what the proposal is and whether it's better than the status quo.

Currently, storing bytes writes an ASCII string. If you want reading that string to return str (unicode), you have to either break roundtripping (bytes in, unicode out), disallow storing bytes entirely, or store bytes a different way (as OPAQUE data?).

You also have to decide what to do if the supposedly ASCII data contains non-ASCII bytes. IIRC, HDF5 does not enforce that the data is really ASCII. Do you decode as Latin 1 (not losing any information, but may leave you with Mojibake), use Python's `surrogateescape` error handling to represent non-ASCII data in an abstract way that can convert back to bytes, or return `str` or `bytes` depending on whether it's valid ASCII?

**Comment by shoyer** [comment]
> If those applications are writing byte strings, why should one decide to
read them as something else than what it was written?

I think only applications using h5py and Python 3 could be fairly considered to be intentionally writing `bytes`. The HDF5 spec is that these are ASCII encoded strings.

Of course people can and do misuse ASCII to store arbitrary bytes. h5py should have a way to handle this situation, but not necessarily in the first class interface.

> I think a change of this magnitude would be reasonable for a 3.0 release, but it's not clear to me exactly what the proposal is and whether it's better than the status quo.

Agreed, this needs some serious pondering.

> Currently, storing bytes writes an ASCII string. If you want reading that string to return str (unicode), you have to either break roundtripping (bytes in, unicode out), disallow storing bytes entirely, or store bytes a different way (as OPAQUE data?).

I would lean towards disabling storing `bytes` entirely (at least for now), to avoid confusion and force users make an explicit choice between OPAQUE data and ASCII encoded strings. We would probably want to add new APIs to support:
1. Saving Python 3 strings with ASCII encoding.
2. Saving Python 3 bytes as "ASCII encoded" strings.

Use-case 1 is more important than use-case 2, and we might drop use-case 2 entirely. There aren't many legitimate reasons to store raw bytes as "ASCII". OPAQUE data would probably suffice.

These might use some variation of `h5py.special_dtype`. Or if we're patient, NumPy may eventually get improved strings (so it can natively represent fixed length ASCII or UTF-8 encoded data) after the planned dtype refactor.

This bytes/strings refactor will also need to make intentional choices about how to handle `np.string_` scalars/arrays.

> You also have to decide what to do if the supposedly ASCII data contains non-ASCII bytes. Do you decode as Latin 1 (not losing any information, but may leave you with Mojibake), use Python's surrogateescape error handling to represent non-ASCII data in an abstract way that can convert back to bytes, or return str or bytes depending on whether it's valid ASCII?

The only one of these options that strikes me as remotely sane (for default behavior) is to use `surrogateescape`.

**Comment by vasole** [comment]
I guess the simplest alternative is to enforce UTF-8 writing under python2 unless something else is explicitly requested. That way we could be able to a) get the same output when using Python2 and Python3 (what seemed to be the original reason of this issue) and b) respect what the original writer did by reading back what is was written irrespective of being intentionally written or not.

My caveat is this alternative would have been fine 5 years ago.

The current behavior has been there for so long that the amount of code that might be broken is huge whatever action is taken.

**Comment by proteins247** [comment]
>If those applications are writing byte strings, why should one decide to read them as something else than what it was written? The problem reported here is almost 100% Python 2 specific because people think they are writing strings when they are writing bytes.

The original issue here is h5py writing and reading in python, but I encountered this problem when processing HDF5 files generated by C code.

After switching some scripts over to Python 3, I was surprised to find that string attributes were returned as bytes. In creating string attributes in C code, I followed what appears to be standard procedure in the examples in HDF5 documentation [1]. e.g.

    hid_t strtype;                     /* Datatype ID */
    herr_t status;
    
    strtype = H5Tcopy (H5T_C_S1);
    status = H5Tset_size (strtype, 5); /* create string of length 5 */

Strings are created as a derived datatype consisting of a contiguous series of the one-byte datatype `H5T_C_S1`.

It seems to me this is a flaw in usability if string attributes created in a reasonable way in C code end up as byte strings in h5py.

1. https://support.hdfgroup.org/HDF5/Tutor/crtdat.html

**Comment by vasole** [comment]
Again, if that was the choice of the C programmer, why should one read something different than what it was written? The C programmer can choose ASCII (equivalent to bytes) or UTF-8.

From https://support.hdfgroup.org/HDF5/doc/Advanced/UsingUnicode/index.html

**Character Datatypes in Datasets and Attributes**

Like object names, HDF5 character data in datasets and attributes is encoded as ASCII by default. Setting up attribute or dataset character data to be UTF-8-encoded is accomplished while defining the attribute or dataset datatype. This makes use of the function H5Tset_cset, which sets the character encoding to be used in building a character datatype.

For example, the following commands could be used to create an 8-character, UTF-8 encoded, string datatype for use in either an attribute or dataset:

    datatype_id = H5Tcopy(H5T_C_S1) ;
    error =       H5Tset_cset(datatype_id, H5T_CSET_UTF8) ;
    error =       H5Tset_size(datatype_id, "8") ;

**Comment by aparamon** [comment]
> The C programmer can choose ASCII (equivalent to bytes) or UTF-8.

A great misconception here: ASCII being 7-bit encoding is **not** equivalent to bytes.

For bytes, please use HDF5 OPAQUE data type:
http://docs.h5py.org/en/stable/strings.html#how-to-store-raw-binary-data

**Comment by jeremysanders** [comment]
Wouldn't the best option (for backward compatibility) would be to add a switch which decode/encode all strings with the given encoding, where the default is to use bytes?

In the future, there could be a warning if this is not set to a value (e.g. utf8 or bytes), and the default could change to utf8.

**Comment by aparamon** [comment]
No one should ever use H5T_CSET_ASCII for anything other than ASCII strings, and H5T_CSET_UTF8 for anything other than UTF-8 strings.
If currently h5py sometimes uses H5T_CSET_ASCII for storing arbitrary bytes, it's a problem to be addressed rather than a foundation for further development.

**Comment by takluyver** [comment]
> If currently h5py sometimes uses H5T_CSET_ASCII for storing arbitrary bytes,

This is what h5py converts Python bytes objects to. It's [clearly documented](http://docs.h5py.org/en/stable/strings.html#how-to-store-raw-binary-data) that you shouldn't use this for storing arbitrary non-text bytes. Python doesn't as far as I know have a null-terminated bytes type we could use instead.

> string attributes created in a reasonable way in C code end up as byte strings in h5py.

A 'string' in C (a sequence of `char`) is more like Python bytes than it is like a Python 3 `str`, which is a sequence of Unicode code points. So it's not unreasonable for a C string to become a Python bytes object.

> Wouldn't the best option (for backward compatibility) would be to add a switch...

The best option for backwards compatibility is not to change anything. :wink: 

There isn't a natural symmetry between Python str/bytes, HDF5 variable-length strings and C pointers to char/wchar_t. The best h5py can do is pick a way to handle it, document what that way is, and do it *consistently*. So long as it's consistent, application code can transform the data to/from whatever you need.

Any change to how this is handled either breaks working code, introduces extra complexity in h5py (adding a switch), or both (adding a switch and then changing the default). The change has to be a really clear improvement to justify that. The people with working code built on the existing API largely aren't in this issue, so I'm arguing on their behalf. :slightly_smiling_face:

**Comment by jeremysanders** [comment]
> Any change to how this is handled either breaks working code, introduces extra complexity in h5py (adding a switch), or both (adding a switch and then changing the default). The change has to be a really clear improvement to justify that. The people with working code built on the existing API largely aren't in this issue, so I'm arguing on their behalf. slightly_smiling_face

Just to say that I have existing code using the current API. It is full of extremely ugly decode hacks to try and present strings in arbitrary HDF5 files to the user in a GUI, working both in Python 2 and 3.

**Comment by takluyver** [comment]
I don't think it should be that ugly. If you want to ensure all strings in the file are presentable as Unicode strings, you could do something like:

```python
if isinstance(loaded_data, bytes):
    loaded_data = loaded_data.decode('ascii', 'replace')
```

This will lose some data where non-ASCII strings have been stored as ASCII; there are other possible trade-offs you could make there.

**Comment by vasole** [comment]
On 07/02/2019 09:38, Andrey Paramonov wrote:
>
>     The C programmer can choose ASCII (equivalent to bytes) or UTF-8.
>
> A great misconception here: ASCII being 7-bit encoding is *not*
> equivalent to bytes.
>
OK. ASCII read as bytes or UTF-8 read as string.

**Comment by wrobell** [comment]
> For bytes, please use HDF5 H5T_OPAQUE data type:
> http://docs.h5py.org/en/stable/strings.html#how-to-store-raw-binary-data

Any chance to make it work for dataset data (not only attributes)?

**Comment by aparamon** [comment]
I think it does work (the same way as for the attributes), doesn't it?
In any case, there is https://github.com/h5py/h5py/issues/1107

**Comment by wrobell** [comment]
@aparamon 

Probably I am doing something wrong... it is not clear what HDF5 OPAQUE maps to on Python level. Below I assumed it is variables bytes type
```
import h5py
import numpy as np

binary_blob = b'Hello\x00Hello\x00'

dt = h5py.special_dtype(vlen=bytes)
f = h5py.File('t.hdf', mode='w')
ds = f.create_dataset('t1', dtype=dt, shape=(1,))
ds[0] = np.void(binary_blob)

f.close()
```

Above code gives
```
$ python x.py 
Traceback (most recent call last):
  File "x.py", line 9, in <module>
    ds[0] = np.void(binary_blob)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 708, in __setitem__
    self.id.write(mspace, fspace, val, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 221, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 163, in h5py._proxy.dset_rw
  File "h5py/defs.pyx", line 3405, in h5py.defs.H5Tconvert
  File "h5py/_conv.pyx", line 449, in h5py._conv.str2vlen
  File "h5py/_conv.pyx", line 113, in h5py._conv.generic_converter
  File "h5py/_conv.pyx", line 259, in h5py._conv.conv_str2vlen
ValueError: VLEN strings do not support embedded NULLs
```

**Comment by aparamon** [comment]
@wrobell 
Yes, your mistake is that you are thinking in terms of strings while working with binary data. Unfortunately, `h5py`s API favors such misconceptions by representing ASCII strings as bytes.

Please forget about strings at all when working with binary data:
````py
import h5py
import numpy as np

binary_blob = b'Hello\x00Hello\x00'

f = h5py.File('t.hdf', mode='w')
ds = f.create_dataset('t1', data=np.void(binary_blob))
print(ds[...])
f.close()
````

**Comment by takluyver** [comment]
More specifically, the `h5py.special_dtype(vlen=bytes)` tells h5py to expect ASCII string data.

If you don't want to pass the data in when creating the dataset, you can create a dtype like `np.dtype((np.void, 10))`. The number specifies how many bytes there are for each entry.

**Comment by wrobell** [comment]
My use case is to store short messages represented as byte arrays - up to 28 bytes in length for each item in dataset (but still variable). At the moment I have to store them as arrays of `uint8` and convert back and forth. IMHO, this is the best workaround at the moment, but still I would not consider this as support for Python `bytes` type. :)

"More specifically, the `h5py.special_dtype(vlen=bytes)` tells h5py to expect ASCII string data." - this is bit confusing. ASCII string (7-bit) is subset of ASCII (8-bit). But in Python world, the `str` type is subset of `bytes`.

**Comment by aparamon** [comment]
> ASCII string (7-bit) is subset of ASCII (8-bit). But in Python world, the `str` type is subset of `bytes`.

While the latter statement is incorrect, the former is ill-stated: there is only one ASCII.
Could you please clarify? :-)

**Comment by wrobell** [comment]
By 7-bit ASCII I mean `H5T_CSET_ASCII` aka us ASCII as stated in https://support.hdfgroup.org/HDF5/doc/RM/RM_H5T.html. By ASCII 8-bit I mean extended ASCII.

The Python 3 `str` type allows only certain data to be stored - it is limited to Unicode. The `bytes` type has no such restrictions.

**Comment by aparamon** [comment]
Hmm, indeed 8-bit extended ASCII encodings are supersets of 7-bit ASCII.
Python `str` is limited to Unicode, and for example Python `float` is limited to a subset of real numbers.

Are these arguments for or against using Python `str` for representing HDF5 strings? :-)

**Comment by wrobell** [comment]
IMHO, h5py handles Python `str` datatype well. The problem is with the `bytes` type.

**Comment by aparamon** [comment]
Thank you for the clarification. I agree it is a major h5py interface problem (which is a tough challenge to solve in a compatible fashion though :-/ ).
