### ISSUE TITLE
Memory leak with chunked storage [workaround provided]

### ISSUE THREAD

**Issue by sscherfke** [h5py/h5py#382]
The following minimal example demonstrates a small memory leak in h5py (or hdf5?). You may need to zoom in into the plot to see it or increase `max_rows`.

``` python
# test_hdf5.py
"""
Setup:
    mkvirtualenv --python=`which python3.3` h5pytest
    pip install h5py memory_profiler psutil matplotlib

Usage:
    mprof run python test_hdf5.py && mprof show

"""
import h5py

max_rows = 100000000
buf_size = 1000

db = h5py.File('/tmp/test.hdf5', 'w')
# Problem:
ds = db.create_dataset('val', shape=(max_rows,), maxshape=(max_rows,),
                       dtype=float)
# Workaround:
# ds = db.create_dataset('val', shape=(max_rows,), dtype=float)

buf = []
start = 0
for i in range(max_rows):
    buf.append(i)
    if len(buf) == buf_size:
        end = start + buf_size
        ds[start:end] = buf
        buf = []
        start = end
else:
    ds[start:start + len(buf)] = buf

db.close()
```

Reproduced it with all of:
- OS X Mavericks, Python 3.3.3, h5py 2.2.1, hdf5 1.8.12 (via brew)
- Ubuntu 13.10, Python 3.3.2+, h5py 2.2.1, hdf5 1.8.11
- Ubuntu 12.04, Python 3.3.3, h5py 2.1.1, hdf5 1.8.4

You can find more details in the mailing list: https://groups.google.com/d/msg/h5py/_a35vzQzRrg/7omsVr9_n4wJ

_Workaround:_ If you remove the _maxshape_ argument when creating the dataset (and change to contiguous storage), no memory seems to leak.

**Comment by estan** [comment]
Anyone know if this was reported upstream, and/or if it was fixed? I haven't seen it myself, but I haven't used h5py much yet. I am using compression and scaleoffset though (on float data).
