### ISSUE TITLE
Bad interaction between h5py and PyTables: Failed to retrieve old handler

### ISSUE THREAD

**Issue by Thomas-Schatz** [h5py/h5py#390]
Dear h5py developers,

When using h5py and PyTables at the same time, I encounter the following problem: after PyTables has been imported, whenever I want to test whether a particular dataset or group is present in a HDF5 file opened with h5py, the following error message gets printed out twice:

```
Exception RuntimeError: RuntimeError('Failed to retrieve old handler',) in 'h5py._errors.set_error_handler' ignored
```

Note that the exception is caught within h5py, the error message just gets printed out as a warning. 

I don't know what is causing this problem and how severe it is and I would very much appreciate if somebody could check if this reproducible on another machine.

The following code can be used to reproduce the error:

```
import h5py, os

try:
    with h5py.File('test.h5') as fh:
        'group' in fh
    print('ok')
    import tables
    with h5py.File('test.h5') as fh:
        print('still ok')
        'group' in fh
        print('not ok anymore')
finally:
    os.remove('test.h5') 
```

It produces the following output when run on my MacbookPro under MacOs 10.6.8 with python 2.7.6 anaconda 1.6.1:

```
ok
still ok
Exception RuntimeError: RuntimeError('Failed to retrieve old handler',) in 'h5py._errors.set_error_handler' ignored
Exception RuntimeError: RuntimeError('Failed to retrieve old handler',) in 'h5py._errors.set_error_handler' ignored
not ok anymore
```

Also note that once PyTables has been imported once, the problem persists throughout the entire session and re-importing h5py doesn't help.

Thanks very much for your help.

**Comment by caryan** [comment]
I'm still running into this interaction with version h5py 2.3.1 and HDF 1.8.13 which should contain the fix in 96be07638bab4d298fd452d373438ceaec979457.  Any clues on where to poke around at? 

```bash
Python 2.7.9 |Anaconda 2.1.0 (64-bit)| (default, Dec 15 2014, 10:33:51) 
Type "copyright", "credits" or "license" for more information.

IPython 2.2.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: %paste
import h5py, os

try:
    with h5py.File('test.h5') as fh:
        'group' in fh
    print('ok')
    import tables
    with h5py.File('test.h5') as fh:
        print('still ok')
        'group' in fh
        print('not ok anymore')
finally:
    os.remove('test.h5')

## -- End pasted text --
ok
still ok
Exception RuntimeError: RuntimeError('Failed to retrieve old handler',) in 'h5py._errors.set_error_handler' ignored
Exception RuntimeError: RuntimeError('Failed to retrieve old handler',) in 'h5py._errors.set_error_handler' ignored
not ok anymore

In [2]: print(h5py.version.info)
Summary of the h5py configuration
---------------------------------

h5py    2.3.1
HDF5    1.8.13
Python  2.7.9 |Anaconda 2.1.0 (64-bit)| (default, Dec 15 2014, 10:33:51) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
sys.platform    linux2
sys.maxsize     9223372036854775807
numpy   1.9.1

In [3]: 

```

**Comment by andrewcollette** [comment]
Depending on how h5py is built, the old system (which produces this error) may still be used as a fallback:

https://github.com/h5py/h5py/blob/master/h5py/h5g.pyx#L439

I suspect the Anaconda guys are building against the HDF5 1.8.4 API; if this is the case, unfortunately there is nothing we can do about that.  Please let us know if the problem persists when building h5py 2.4 from source.

**Comment by asmeurer** [comment]
We use `export H5PY_DIR` instead of the configure option.

**Comment by alimanfoo** [comment]
FWIW I ran into this problem on a Ubuntu system with HDF5 1.8.13 installed from libhdf5-openmpi-dev. When installing h5py via pip I get:

```
    ********************************************************************************
                           Summary of the h5py configuration

        Path to HDF5: None
        HDF5 Version: '1.8.4'
         MPI Enabled: False
    Rebuild Required: False

    ********************************************************************************
```

However if I do:

```
$ locate libhdf5.so
/usr/lib/x86_64-linux-gnu/hdf5/openmpi/libhdf5.so
$ export HDF5_DIR=/usr/lib/x86_64-linux-gnu/hdf5/openmpi
```

...before running pip install h5py then I get:

```
    running build_ext
    Autodetected HDF5 1.8.13
    ********************************************************************************
                           Summary of the h5py configuration

        Path to HDF5: '/usr/lib/x86_64-linux-gnu/hdf5/openmpi'
        HDF5 Version: '1.8.13'
         MPI Enabled: False
    Rebuild Required: True

    ********************************************************************************
```

I don't know if this is an issue but thought I'd mention in case anyone else is having this problem.

**Comment by jreadey** [comment]
I'm seeing this problem on Windows (but not Linux or OS X).
This is my version info:

Summary of the h5py configuration
---------------------------------

h5py    2.5.0
HDF5    1.8.15
Python  2.7.11 |Continuum Analytics, Inc.| (default, Jan 29 2016, 14:26:21) [MSC v.1500 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.10.4


Another thing, is that performance seems much slower (~10x) compared with the same code running on Linux or OS X).
