### ISSUE TITLE
make default mode 'r'

### ISSUE THREAD

**Issue by tacaswell** [h5py/h5py#397]
Mentioned in #367 , I propose changing the default open mode from `'a'` -> `'r'`

Should be tagged for 3.0

**Comment by jakirkham** [comment]
This came up in another context and wanted to suggest reconsidering whether this could be fixed. Maybe a deprecation warning could be raised at least. Comments from people seeing this warning would give some indication of whether such a switch would be tolerable (or even favorable).

**Comment by aparamon** [comment]
+1 on this, was quite astonished to discover that unlike built-in `open()`, `h5py.File()` defaults to write mode. And still keep to forgetting that from time to time, to get astonished again :-)

**Comment by tacaswell** [comment]
ok so a possible path:

 - add a global flag of 'default open mode'
 - replace the default read mode on File with a sentinel that means 'go look at the global flag'
 - have the default mode be "rw but warn alo t" with warnings that say "pass a mode explicitly or set the global flag to something explicitly to silence this warning" 
 - in a later version change the default mode to 'r' with no warnings
 - in a later later release warn if the global flag is set to anything but 'r'
 - in a later later later release ignore the set value to the global flag and just use 'r'
 - in a much later version remove the global flag (?)

**Comment by takluyver** [comment]
That's probably the most sensible path. I don't think it would be entirely unreasonable to do a much more direct change in 3.0 release; it's going to fail in a fairly obvious way, and it's easy to fix the resulting problems (just pass an appropriate mode explicitly). But the deprecation cycle is the more responsible choice.

(Another rationale I just thought of: at least in my use case, I open existing files far more often than I create new ones. If I mistype the filename, it's better to see an error than to figure out why my file is suddenly empty).

**Comment by tacaswell** [comment]
We could do the first 3 bullet points in 2.10 in 6mo and the change the default (and drop python2) in 3.0 12mo?

Even if we did a hard change with no pre-warning, I think we should provide an easy "actually, I need the old behavior" path for a while.

**Comment by takluyver** [comment]
#1143 is my attempt at the first 3 bullet points.

I'd skip the last but one bullet point, where you say ignore the global setting. It's a control for a really important aspect of behaviour, so I think there shouldn't be any version where it's accepted but ignored. Once we stop using it, it should be an error to try to change it.
