### ISSUE TITLE
Slicing huge arrays in h5py

### ISSUE THREAD

**Issue by rossant** [h5py/h5py#413]
I wish someone could explain me [this](http://nbviewer.ipython.org/gist/anonymous/9467085/h5py_slice.ipynb).

**Comment by wfedorko** [comment]
Hello,
In my project we need to access substantial (~400k) number of non-contiguous rows from an h5py dataset of about 20M rows and 3k 'columns'. 
I do this by preparing a sorted numpy array of row indices to access and calling something like:
`
data_I_want=big_dataset[indices,:]
`
It turns out to be basically impossible. Accessing anything larger that 2000 rows is dog-slow.
The big_dataset is not chunked.

I presume this is the same problem as described above? If yes I am a bit taken aback as it seems to be rather old issue...

**Comment by rossant** [comment]
I think it is indeed the same problem. You could try to do a for loop in Python and accessing rows one by one, and comparing the performance with h5py fancy indexing. It will be slow, but maybe a bit less. I don't know if doing it in Cython would improve it.

Something I had tried at some point was to get the address of the underlying contiguous buffer within the HDF5 file (only works on contiguous, non-chunked HDF5 datasets), retrieve the buffer size, and memmap that with NumPy. If I remember correctly, the performance was much better.

More generally, this is one of the reasons we've moved away from HDF5 in our project. We've just been using flat binary arrays like NPY files and it's much better for our use-cases (few huge arrays instead of many small arrays).

**Comment by wfedorko** [comment]
@rossant  - thanks for replying.
I ended up dividing my indices array into 200-long blocks and looping over the range to build up the full 'slice I need. It is slow but workable. 

Unfortunately I don't think I can work with straight numpy arrays - the dataset is too big to fit into memory.
Can you sketch out how you'd access the underlying buffer - the dataset is contiguous...

Thanks!

**Comment by rossant** [comment]
You can memmap NumPy arrays without loading them entirely into memory :

https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.memmap.html
https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.load.html

You can see the code to access the underlying buffer here:
https://github.com/kwikteam/klusta/blob/c1909dd6e472fa502213f1ee0b1e7b75e8347a71/klusta/kwik/h5.py#L54-L65

**Comment by tacaswell** [comment]
> the dataset is contiguous..

Your dataset is not chucked at all?

If is chunked, you may get some benefit from pulling it up a chuck at a time then pulling the rows you need out of that chuck, repeat (this is at the core of what pytables does to get good performance).
