### ISSUE TITLE
Inconsistency when slicing multidimensional arrays

### ISSUE THREAD

**Issue by aldro61** [h5py/h5py#425]
I noticed an inconsistency when slicing multidimensional arrays. I have provided an example reproducing the problem below. Notice that np_data[idx_not_ok, 2] returns an array of one element, whereas h_data[idx_not_ok, 2] outputs the element.

I think that in such situations h5py should return an array containing the element to remain consistant with this form of slicing.

``` python
import h5py
import numpy as np

np_data = np.zeros((5,5), dtype=np.uint8)

h_file = h5py.File('test.hdf',driver='core',backing_store=False)
h_data = h_file.create_dataset("test_dataset", data=np_data)

idx_ok = np.array([0, 1])        
idx_not_ok = np.array([0])      

print np_data[idx_ok, 2]        # Outputs: [ 0  0]  
print np_data[idx_not_ok, 2]    # Outputs: [ 0]    

print h_data[idx_ok, 2]         # Outputs: [ 0  0]
print h_data[idx_not_ok, 2]     # Outputs: 0
```

I am using H5py 2.2.1, Numpy 1.8.0, Python 2.7.3 and OSX 10.9.2.

**Comment by asanakoy** [comment]
Seems like I have faced the same or similar issue.

```python
import numpy as np
import h5py

arr = np.zeros((100, 10, 10, 10))
f = h5py.File('file.hdf5', 'w')
f.create_dataset('arr', data=arr)
f.close()

f = h5py.File('file.hdf5')
print arr[[0], ...].shapea # (1, 10, 10, 10)
print f['arr'][[0], ...].shape # (1, 10, 10, 10)

print arr[np.array([0]), ...].shape # (1, 10, 10, 10)
print f['arr'][np.array([0]), ...].shape # (10, 10, 10) BUG!
```


h5py    2.6.0
HDF5    1.8.11
Python  2.7.11 (default, Dec 15 2015, 16:46:19) 
[GCC 4.8.4]
sys.platform    linux2
sys.maxsize     9223372036854775807
numpy   1.11.0

**Comment by asanakoy** [comment]
I will create a pull request later
