### ISSUE TITLE
Re-opening a file doesn't reload data

### ISSUE THREAD

**Issue by tangobravo** [h5py/h5py#432]
I'm writing an HDF5 file from a C++ program. I've got an ipython session that I'm using to analyse the data in the file.

I expected re-opening with h5py.File(name, 'r') would be guaranteed to read the latest data from the file, but the data seems to be cached somewhere. Ensuring to flush() and close() all previously opened variables for the file doesn't seem to help, nor even reload(h5py). I have to restart the python kernel in ipython to have the updates in the file visible in h5py.

HDFView offers a "Reload File" option in the context menu that does the right thing, so perhaps I just need to call whatever functions that uses on the underlying HDF5 object. Or perhaps this will all be fixed by the identifiers branch?

Any workarounds other than restarting the ipython kernel or using files with different names?

**Comment by rainwoodman** [comment]
I am hit by this as well. 
What about adding a method that guarantees reading in fresh from a file on disk?

**Comment by ssstuvz** [comment]
Any news? del f doesn't work either. It's a pain to restart the kernel every time :(

**Comment by tacaswell** [comment]
@ssstuvz Does explicitly calling `close` not work?

The context manager approach should always work.

**Comment by poleguy** [comment]
I'm doing something very similar, but without ipython, and I am hitting the same problem. I am reading the file as it is being written, but the changes don't show up. So I try to close and re-open within my python code and it seemingly doesn't re-read the file. If I close and re-open the python app completely it works fine.

It's possibly not actually h5py's fault? Maybe it's just a missing reference that I didn't delete that causes the .close() operation to not complete? I've seen similar things in python where the garbage collector doesn't clean up when you expected. It's a problem with closing serial ports running on background threads for example.

Considering that python has this common trap, it would be very convenient to have a reload_latest_from_disk() command or something for these cases.

I tried SWMR but couldn't get it to work immediately. I may have to try again. For now I have to completely close and re-open my app to get the latest data.

**Comment by tacaswell** [comment]
Reading from a file while it is being written to without SWMR is not supported at the libhdf5 level.  My understanding is that "not seeing new data" is the best-case scenario (with segfaults being the worst).

The correct solution is to use SWMR and I do not think that there is anything we can do (and even if we could, should do) from Python to enable this usage.

**Comment by poleguy** [comment]
That's fair. I have a visualization tool I'm running on data that is being streamed in, and it is convenient to run on the data while it is being captured as a sanity test. Based on your advice, I will turn my focus to enabling SWMR mode, and won't bother trying to close and re-open. It's not clear why I couldn't get SWMR to work on the first try.

To be clear: 

For the purposes of a sanity check, I set the flag to not use locks.

```os.environ["HDF5_USE_FILE_LOCKING"] = "FALSE"```

In practice I have never seen a problem in my use case. Even in the worst case scenario of an occasional  seg-fault it would still be a practical trade-off as a quick sanity check until I get SWMR working. But I agree, it's not ideal. It's great that SWMR is an option.
