### ISSUE TITLE
Python3 error storing a tuple of strings as attribute

### ISSUE THREAD

**Issue by monkeybutter** [h5py/h5py#441]
I'm in the process of making my code python3 compatible and I'm getting an error in the following line:

```
dset.attrs['Column Names'] = ('X', 'Y', 'Z', 'Intensity', 'Distance', 'Angle')
```

The error shows:

```
Traceback (most recent call last):
  File "test.py", line 10, in write_to_hdf5
    dset.attrs['Column Names'] = ('X', 'Y', 'Z', 'Intensity', 'Distance', 'Angle')
  File "/home/roz016/anaconda/envs/py3k/lib/python3.3/site-packages/h5py/_hl/attrs.py", line 71, in __setitem__
    self.create(name, data=value, dtype=base.guess_dtype(value))
  File "/home/roz016/anaconda/envs/py3k/lib/python3.3/site-packages/h5py/_hl/attrs.py", line 108, in create
    htype = h5t.py_create(dtype, logical=True)
  File "h5t.pyx", line 1379, in h5py.h5t.py_create (h5py/h5t.c:12683)
  File "h5t.pyx", line 1457, in h5py.h5t.py_create (h5py/h5t.c:12578)
TypeError: No conversion path for dtype: dtype('<U9')
```

This code works perfectly fine using python2.7. Isn't it possible to store string tuples as attributes using python3?

**Comment by guddulrk** [comment]
I am making python code compatible to python3.5 and getting following error in this line of code:
    db['data'][dname].attrs['txt'] = res[i]['txt']

Traceback (most recent call last):
  File "C:/python_projects/SynthText-master/SynthText-master/gen.py", line 122, in main
    add_res_to_db(imname,res,out_db)
  File "C:/python_projects/SynthText-master/SynthText-master/gen.py", line 73, in add_res_to_db
    db['data'][dname].attrs['txt'] = res[i]['txt']
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (C:\Minonda\conda-bld\h5py_1474482825505\work\h5py\_objects.c:2705)
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (C:\Minonda\conda-bld\h5py_1474482825505\work\h5py\_objects.c:2663)
  File "C:\Program Files\Anaconda3\lib\site-packages\h5py\_hl\attrs.py", line 93, in __setitem__
    self.create(name, data=value, dtype=base.guess_dtype(value))
  File "C:\Program Files\Anaconda3\lib\site-packages\h5py\_hl\attrs.py", line 169, in create
    htype = h5t.py_create(original_dtype, logical=True)
  File "h5py\h5t.pyx", line 1450, in h5py.h5t.py_create (C:\Minonda\conda-bld\h5py_1474482825505\work\h5py\h5t.c:16099)
  File "h5py\h5t.pyx", line 1470, in h5py.h5t.py_create (C:\Minonda\conda-bld\h5py_1474482825505\work\h5py\h5t.c:15933)
  File "h5py\h5t.pyx", line 1531, in h5py.h5t.py_create (C:\Minonda\conda-bld\h5py_1474482825505\work\h5py\h5t.c:15892)
TypeError: No conversion path for dtype: dtype('<U31')

Any help please....

**Comment by tacaswell** [comment]
See https://github.com/h5py/h5py/issues/441#issuecomment-42319077 to let numpy have a pass at this first.

**Comment by chrisjbillington** [comment]
Would it be feasibly for h5py to [encode](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.core.defchararray.encode) numpy UTF32 arrays down to numpy S arrays, and store them in file tagged as UTF8? Then doing the reverse upon reading of course.

Something like:
```python
import numpy as np

x = ['ü', 'y']

x = np.array(x)
if x.dtype.type == np.unicode_:
    x = np.core.defchararray.encode(x, 'utf8')

print(repr(x))
```
gives:

```python
array([b'\xc3\xbc', b'y'], dtype='|S2')
```
Is there any downside to this, other than the encoding? The data is already being converted to a numpy array, involving some copies and whatnot, so it doesn't seem like a great cost, and it would be totally interoperable with other programs reading the HDF5 file - they'll get an array of bytestrings with a tag saying that they contain UTF8 encoded text.

**Comment by tacaswell** [comment]
I think the catch is how to 'tag' in with the correct encoding on to the set of strings.

This is probably best handled at the application level or in the underlying hdf5 library.

**Comment by chrisjbillington** [comment]
The 'tag' is part of HDF5. HDF5 lets you set the character set for string types, so it's possible to store an array of fixed length bytestrings with the character set set to 'UTF8' indicating that the bytes comprise UTF8 encoded strings. This is the general mechanism for unicode support in HDF5: just store bytes and tell the application whether the encoding is ASCII or UTF8.

In pull request #1031 I demonstrate this, storing a fixed-length bytestring numpy array (the bytes being UTF8 encoded strings) and setting the character set in HDF5 to UTF8, and decoding it to a numpy 'U' array upon read. I no longer like this approach (it is easier to store an array of vlen unicode strings - note that these are also the same as vlen ASCII strings except for this character encoding tag). Both of these approaches are compatible with other applications: if I open the resulting file in hdfview it displays the string arrays with unicode characters correctly.

**Comment by tacaswell** [comment]
Huh, did not know that down there...

**Comment by aragilar** [comment]
So if we're going to support the numpy unicode dtype (which is the question we need to decide on), I think #1032 is the way to do it. There are some things which need to be considered with supporting the numpy unicode dtype in this fashion (which means we can keep saying that this has to be done manually, or we accept the consequences of the decision):
1. We've been saying for a while we won't support this (http://docs.h5py.org/en/latest/strings.html#what-about-numpy-s-u-type). If we do support this, then we should make this change well advertised.
2. We're now deciding on always mapping the numpy unicode type for attributes to variable length UTF-8, but we don't do a similar thing for datasets (this must be done explicitly still, which is a good thing in my opinion). h5py currently doesn't support fixed length UTF-8 (on my todo list), so variable length UTF-8 seems like the better option of the two.
3. This still isn't true roundtripping (the dtype moves from unicode to object).

Personally, I'm on the fence whether we add support (more convenient, but now roundtripping does not hold, and attributes and datasets treat collections of strings differently).
