### ISSUE TITLE
compiling h5py with MPI

### ISSUE THREAD

**Issue by marcocamma** [h5py/h5py#472]
Hi,

I just downloaded the latest github version and tried to compile it with mpi support.

When I follow the instructions I get the following error message:

user@station:~/linux/h5py$ export CC=/usr/bin/mpicc
user@station:~/linux/h5py$ python setup.py build --mpi 
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --mpi not recognized

Am I doing something wrong or are the docs not up to date.
I am not familiar with setup.py so I can't quite figure out where the problem is,
thanks in advance,
marco

**Comment by ThomasLecocq** [comment]
just a side note, the current master still includes the --mpi thingy in the notes on Parallel HDF5 !
