### ISSUE TITLE
Repeated opening of dataset eventually fails

### ISSUE THREAD

**Issue by garrison** [h5py/h5py#480]
The following file should run indefinitely, but after many iterations (hundreds of thousands or millions) it fails.

```
#!/usr/bin/env python3

import shutil
import tempfile

import h5py

tmpdir = tempfile.mkdtemp()
i = 0
try:
    with h5py.File("test.h5", "w") as f:
        f.create_dataset("test", data=[[1,2],[3,4]], compression="gzip", shuffle=True)
    with h5py.File("test.h5", "r") as f:
        while True:
            f["test"][...]
            i += 1
finally:
    shutil.rmtree(tmpdir)
    print(i)
```

The error from h5py 2.3.1:

```
$ python3 h5py_bug.py 
465527
Traceback (most recent call last):
  File "h5py_bug.py", line 15, in <module>
    f["test"][...]
  File "/home/garrison/.local/lib/python3.4/site-packages/h5py/_hl/dataset.py", line 445, in __getitem__
    self.id.read(mspace, fspace, arr, mtype)
  File "h5d.pyx", line 181, in h5py.h5d.DatasetID.read (h5py/h5d.c:2782)
  File "_proxy.pyx", line 130, in h5py._proxy.dset_rw (h5py/_proxy.c:1709)
  File "_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread (h5py/_proxy.c:1379)
OSError: Can't read data (Inflate() failed)
```

It fails also in h5py 2.2.1, but with a different error:

```
$ python3 h5py_bug.py 
4194220
Traceback (most recent call last):
  File "h5py_bug.py", line 15, in <module>
    f["test"][...]
  File "/usr/lib/python3/dist-packages/h5py/_hl/dataset.py", line 373, in __getitem__
    mtype = h5t.py_create(new_dtype)
  File "h5t.pyx", line 1379, in h5py.h5t.py_create (h5py/h5t.c:13856)
  File "h5t.pyx", line 1412, in h5py.h5t.py_create (h5py/h5t.c:13373)
  File "h5t.pyx", line 1234, in h5py.h5t._c_int (h5py/h5t.c:11409)
RuntimeError: unable to register datatype atom (Datatype: Unable to register new atom)
```

I'm using hdf5 1.8.13 from debian.  It fails under both python2 and python3.

**Comment by fzalkow** [comment]
Hi,

for me the issue isn't resolved... I use hdf5 1.8.14 with h5py 2.4.0 in Enthought Canopy Python 2.7.6 on OS X 10.9.5.

I try to access a dataset – shape (59, 59, 59, 59, 59), type "<f8" – many times. After accessing too many times (last run 7090602 times) it stops with the same error message mentioned above (RuntimeError: unable to register datatype atom).

Any suggestions?

Thanks alot!

Best

Frank


	$ h5cc -showconfig
		    SUMMARY OF THE HDF5 CONFIGURATION
		    =================================
	
	General Information:
	-------------------
			   HDF5 Version: 1.8.14
			  Configured on: Thu Feb 26 04:06:17 GMT 2015
			  Configured by: brew@minimavericks.local
			 Configure mode: production
			    Host system: i386-apple-darwin13.4.0
		      Uname information: Darwin minimavericks.local 13.4.0 Darwin Kernel Version 13.4.0: Wed Dec 17 19:05:52 PST 2014; root:xnu-2422.115.10~1/RELEASE_X86_64 x86_64
			       Byte sex: little-endian
			      Libraries: static, shared
		     Installation point: /usr/local/Cellar/hdf5/1.8.14
	
	Compiling Options:
	------------------
	               Compilation Mode: production
	                     C Compiler: /usr/local/Library/ENV/4.3/clang ( Apple LLVM version 6.0 )
	                         CFLAGS: 
	                      H5_CFLAGS:  
	                      AM_CFLAGS: 
	                       CPPFLAGS: 
	                    H5_CPPFLAGS:   -DNDEBUG -UH5_DEBUG_API
	                    AM_CPPFLAGS: -I/usr/local/opt/szip/include 
	               Shared C Library: yes
	               Static C Library: yes
	  Statically Linked Executables: no
	                        LDFLAGS: 
	                     H5_LDFLAGS: 
	                     AM_LDFLAGS:  -L/usr/local/Cellar/hdf5/1.8.14/lib -L/usr/local/opt/szip/lib
	 	 	Extra libraries:  -lsz -lz -ldl -lm 
	 		       Archiver: ar
	 		 	 Ranlib: ranlib
	 	      Debugged Packages: 
			    API Tracing: no
	
	Languages:
	----------
	                        Fortran: no
	
	                            C++: no
	
	Features:
	---------
	                  Parallel HDF5: no
	             High Level library: yes
	                   Threadsafety: no
	            Default API Mapping: v18
	 With Deprecated Public Symbols: yes
	         I/O filters (external): deflate(zlib),szip(encoder)
	         I/O filters (internal): shuffle,fletcher32,nbit,scaleoffset
	                            MPE: no
	                     Direct VFD: no
	                        dmalloc: no
	Clear file buffers before write: yes
	           Using memory checker: no
	         Function Stack Tracing: no
	      Strict File Format Checks: no
	   Optimization Instrumentation: no
	       Large File Support (LFS): yes

**Comment by andrewcollette** [comment]
@fzalkow, I'm surprised it's not fixed.  My recommendation would be (1) to contact the HDF Group, or (2) to refactor your code not to open the dataset 7 million times.  Unfortunately there's not much we can do in h5py to work around this.

**Comment by fzalkow** [comment]
Sorry, I just spot that my h5py still uses HDF5 1.8.13.

	>>> print  h5py.version.info
	Summary of the h5py configuration
	---------------------------------
	
	h5py    2.5.0
	HDF5    1.8.13
	Python  2.7.6 | 64-bit | (default, Apr 11 2014, 11:55:30) 
	[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
	sys.platform    darwin
	sys.maxsize     9223372036854775807
	numpy   1.9.2
	
I installed h5py by

	export HDF5_DIR=/usr/local/Cellar/hdf5/1.8.14
	export HDF5_VERSION=1.8.14
	sudo pip install h5py

but it doesn't seem to use my homebrew hdf5...?

**Comment by karpob** [comment]
Hi, I haven't figured out the reason, but I had the same h5py.version.info despite setting the environment variable for pip to use 1.8.14. If you install using the tarball from https://pypi.python.org/packages/source/h/h5py/h5py-2.5.0.tar.gz, and install using the custom installation procedure:

$ python setup.py configure --hdf5=/usr/local/Cellar/hdf5/1.8.14
$ python setup.py configure --hdf5-version=1.8.14
$ python setup.py build
$ python setup.py install 

I get the the following:

h5py    2.5.0
HDF5    1.8.14
Python  2.7.9 (default, Dec 10 2014, 23:46:04) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.9.2

and the error disappears for me. I'm guessing there's something not quite right with the environment variables, or the interaction with pip.

**Comment by chinmayrane** [comment]
Is there any workaround for this?
