### ISSUE TITLE
Assignment through dimension-reducing slice is very slow

### ISSUE THREAD

**Issue by bmerry** [h5py/h5py#492]
For some reason, `ds[..., i] = data` is much slower than `ds[..., i : i + 1] = data[..., np.newaxis]`, where `data` is a numpy array, even though exactly the same data is transferred between the same locations.

```
Summary of the h5py configuration
---------------------------------

h5py    2.3.1
HDF5    1.8.11
Python  2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2]
sys.platform    linux2
sys.maxsize     9223372036854775807
numpy   1.9.0
```

Here is sample code, based on stripping down the code I was writing. It writes a 512MiB file, and takes about 2.5s when run with `--fast` but 16s when run without.

``` python
#!/usr/bin/env python
import h5py
import numpy as np
import argparse

dim = (128, 2048, 512)

def create_file(filename, cache_entries, cache_size):
    """Creates a file with a user-specified cache size"""
    propfaid = h5py.h5p.create(h5py.h5p.FILE_ACCESS)
    settings = list(propfaid.get_cache())
    settings[1] = cache_entries
    settings[2] = cache_size
    propfaid.set_cache(*settings)
    return h5py.File(h5py.h5f.create(filename, fapl=propfaid), 'w', libver='latest')

parser = argparse.ArgumentParser()
parser.add_argument('--fast', action='store_true')
args = parser.parse_args()
data = np.zeros(dim[0:2], dtype=np.float32)
outf = create_file('slow.hdf5', 524287, 512 * 1024**2)
ds = outf.create_dataset("data", dim, dtype=np.float32, chunks=(1, dim[1], 64))
for i in range(dim[2]):
    if args.fast:
        ds[..., i:i+1] = data[..., np.newaxis]
    else:
        ds[..., i] = data
```

**Comment by takluyver** [comment]
There is a similar bug with reading, although my recent changes in #1428 avoid it in the most common scenarios.

I think I have roughly understood the cause of this, related to this bit of code in the read & write pathways:

https://github.com/h5py/h5py/blob/eede14665c46bd774124bdec925b7318c5e0fe81/h5py/_hl/dataset.py#L614-L618

When you index a dimension with an integer, you drop that dimension from the resulting array. So you can read a 2D array from a 3D dataset, for example. The HDF5 API doesn't directly know about this - hyperslab selection always does the equivalent of slicing `i : i+1` in Python. So the memory shape we tell HDF5 about should have the same number of dimensions as the dataset. But the way this code ensures that seems to assume that you're always indexing the first N dimensions. So a selection like `ds[..., 0]` ends up with a selection shape of e.g. `(128, 2048, 1)`, but telling HDF5 that the in-memory array is `(1, 128, 2048)`. This discrepancy must be triggering some pathological looping within HDF5.

I think this is conceptually easy enough to solve - we just need to preserve the dimensions that are dropped here:

https://github.com/h5py/h5py/blob/eede14665c46bd774124bdec925b7318c5e0fe81/h5py/_hl/selections.py#L241https://github.com/h5py/h5py/blob/eede14665c46bd774124bdec925b7318c5e0fe81/h5py/_hl/selections.py#L241

The challenge will be tracking down where each kind of shape should be used in the code.
