### ISSUE TITLE
MPI Collective

### ISSUE THREAD

**Issue by Cadair** [h5py/h5py#499]
What extra work is required to get the [mpi_collective](https://github.com/andrewcollette/h5py/tree/mpi_collective) branch included in master?

**Comment by aozalevsky** [comment]
I'd like to help. I have access to a couple of comptutational servers and couple of clusters with Lustre FS but different interconnects (Infiniband and 1G ethernet).

**Comment by Cadair** [comment]
@aozalevsky I am exceedingly busy at the moment, but could find some time to run tests and check stuff for you.

**Comment by Cadair** [comment]
Having just started using this again, it looks like the branch is conflicting with master, so that's probably the first thing to work out.

**Comment by aragilar** [comment]
Closed by #648.
