### ISSUE TITLE
Install h5py 2.4.0 failed!

### ISSUE THREAD

**Issue by duytrung** [h5py/h5py#514]
Hello,

I tried to update h5py via pip by command prompt but it failed to update. This is the log:

C:\Anaconda3\Scripts>pip install h5py --upgrade
Collecting h5py from https://pypi.python.org/packages/source/h/h5py/h5py-2.4.0.tar.gz#md5=80c9a94ae3
1f84885cc2ebe1323d6758
  Downloading h5py-2.4.0.tar.gz (172kB)
    100% |################################| 176kB 423kB/s ta 0:00:01
Requirement already up-to-date: numpy>=1.6.1 in c:\anaconda3\lib\site-packages (from h5py)
Requirement already up-to-date: Cython>=0.17 in c:\anaconda3\lib\site-packages (from h5py)
Installing collected packages: h5py
  Found existing installation: h5py 2.3.1
    Uninstalling h5py-2.3.1:
      Successfully uninstalled h5py-2.3.1
  Running setup.py install for h5py
    ********************************************************************************
                           Summary of the h5py configuration
        Path to HDF5: None
        HDF5 Version: '1.8.4'
         MPI Enabled: False
    Rebuild Required: False
    ********************************************************************************
    Executing api_gen rebuild of defs
    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\defs.pyx because it
changed.
    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\_errors.pyx because
it changed.
    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\_objects.pyx because
 it changed.
    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\_proxy.pyx because i
t changed.
    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5fd.pyx because it
changed.
    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5z.pyx because it c
hanged.
    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5.pyx because it ch
anged.
    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5i.pyx because it c
hanged.
    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5r.pyx because it c
hanged.
    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\utils.pyx because it
 changed.
    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\_conv.pyx because it
 changed.
    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5t.pyx because it c
hanged.
    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5s.pyx because it c
hanged.
    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5p.pyx because it c
hanged.
    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5d.pyx because it c
hanged.
    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5a.pyx because it c
hanged.
    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5f.pyx because it c
hanged.
    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5g.pyx because it c
hanged.
    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5l.pyx because it c
hanged.
    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5o.pyx because it c
hanged.
    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5ds.pyx because it
changed.
    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5ac.pyx because it
changed.
    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\_conv.pyx
    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\_errors.pyx
    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\_objects.pyx
    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\_proxy.pyx
    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\defs.pyx
    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5.pyx
    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5a.pyx
    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5ac.pyx
    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5d.pyx
    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5ds.pyx
    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5f.pyx
    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5fd.pyx
    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5g.pyx
    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5i.pyx
    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5l.pyx
    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5o.pyx
    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5p.pyx
    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5r.pyx
    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5s.pyx
    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5t.pyx
    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5z.pyx
    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\utils.pyx
    LLVM version 3.1svn, 3.1svn
    Autodetection skipped [[WinError 126] The specified module could not be found]
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\setup.py", line 147, in <mo
dule>
        cmdclass = CMDCLASS,
      File "C:\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Anaconda3\lib\distutils\command\install.py", line 539, in run
        self.run_command('build')
      File "C:\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Anaconda3\lib\distutils\command\build.py", line 126, in run
        self.run_command(cmd_name)
      File "C:\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\setup_build.py", line 133,
in run
        build_ext.run(self)
      File "C:\Anaconda3\lib\distutils\command\build_ext.py", line 308, in run
        force=self.force)
      File "C:\Anaconda3\lib\distutils\ccompiler.py", line 1031, in new_compiler
        return klass(None, dry_run, force)
      File "C:\Anaconda3\lib\distutils\cygwinccompiler.py", line 282, in __init__
        CygwinCCompiler.__init__ (self, verbose, dry_run, force)
      File "C:\Anaconda3\lib\distutils\cygwinccompiler.py", line 126, in __init__
        if self.ld_version >= "2.10.90":
    TypeError: unorderable types: NoneType() >= str()
    Complete output from command C:\Anaconda3\python.exe -c "import setuptools, tokenize;__file__='C
:\\Users\\MYEXPE~1\\AppData\\Local\\Temp\\pip-build-lyjh094j\\h5py\\setup.py';exec(compile(getattr(t
okenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record
C:\Users\MYEXPE~1\AppData\Local\Temp\pip-x20abzh_-record\install-record.txt --single-version-externa
lly-managed --compile:
    running install

    running build

    running build_py

    creating build

    creating build\lib.win-amd64-3.4

    creating build\lib.win-amd64-3.4\h5py

    copying h5py\highlevel.py -> build\lib.win-amd64-3.4\h5py

    copying h5py\ipy_completer.py -> build\lib.win-amd64-3.4\h5py

    copying h5py\version.py -> build\lib.win-amd64-3.4\h5py

    copying h5py\__init__.py -> build\lib.win-amd64-3.4\h5py

    creating build\lib.win-amd64-3.4\h5py\_hl

    copying h5py\_hl\attrs.py -> build\lib.win-amd64-3.4\h5py\_hl

    copying h5py\_hl\base.py -> build\lib.win-amd64-3.4\h5py\_hl

    copying h5py\_hl\dataset.py -> build\lib.win-amd64-3.4\h5py\_hl

    copying h5py\_hl\datatype.py -> build\lib.win-amd64-3.4\h5py\_hl

    copying h5py\_hl\dims.py -> build\lib.win-amd64-3.4\h5py\_hl

    copying h5py\_hl\files.py -> build\lib.win-amd64-3.4\h5py\_hl

    copying h5py\_hl\filters.py -> build\lib.win-amd64-3.4\h5py\_hl

    copying h5py\_hl\group.py -> build\lib.win-amd64-3.4\h5py\_hl

    copying h5py\_hl\selections.py -> build\lib.win-amd64-3.4\h5py\_hl

    copying h5py\_hl\selections2.py -> build\lib.win-amd64-3.4\h5py\_hl

    copying h5py\_hl\__init__.py -> build\lib.win-amd64-3.4\h5py\_hl

    creating build\lib.win-amd64-3.4\h5py\tests

    copying h5py\tests\common.py -> build\lib.win-amd64-3.4\h5py\tests

    copying h5py\tests\__init__.py -> build\lib.win-amd64-3.4\h5py\tests

    creating build\lib.win-amd64-3.4\h5py\tests\old

    copying h5py\tests\old\common.py -> build\lib.win-amd64-3.4\h5py\tests\old

    copying h5py\tests\old\test_attrs.py -> build\lib.win-amd64-3.4\h5py\tests\old

    copying h5py\tests\old\test_attrs_data.py -> build\lib.win-amd64-3.4\h5py\tests\old

    copying h5py\tests\old\test_base.py -> build\lib.win-amd64-3.4\h5py\tests\old

    copying h5py\tests\old\test_dataset.py -> build\lib.win-amd64-3.4\h5py\tests\old

    copying h5py\tests\old\test_datatype.py -> build\lib.win-amd64-3.4\h5py\tests\old

    copying h5py\tests\old\test_dimension_scales.py -> build\lib.win-amd64-3.4\h5py\tests\old

    copying h5py\tests\old\test_file.py -> build\lib.win-amd64-3.4\h5py\tests\old

    copying h5py\tests\old\test_group.py -> build\lib.win-amd64-3.4\h5py\tests\old

    copying h5py\tests\old\test_h5.py -> build\lib.win-amd64-3.4\h5py\tests\old

    copying h5py\tests\old\test_h5f.py -> build\lib.win-amd64-3.4\h5py\tests\old

    copying h5py\tests\old\test_h5p.py -> build\lib.win-amd64-3.4\h5py\tests\old

    copying h5py\tests\old\test_h5t.py -> build\lib.win-amd64-3.4\h5py\tests\old

    copying h5py\tests\old\test_objects.py -> build\lib.win-amd64-3.4\h5py\tests\old

    copying h5py\tests\old\test_selections.py -> build\lib.win-amd64-3.4\h5py\tests\old

    copying h5py\tests\old\test_slicing.py -> build\lib.win-amd64-3.4\h5py\tests\old

    copying h5py\tests\old\__init__.py -> build\lib.win-amd64-3.4\h5py\tests\old

    creating build\lib.win-amd64-3.4\h5py\tests\hl

    copying h5py\tests\hl\test_dataset_getitem.py -> build\lib.win-amd64-3.4\h5py\tests\hl

    copying h5py\tests\hl\test_dims_dimensionproxy.py -> build\lib.win-amd64-3.4\h5py\tests\hl

    copying h5py\tests\hl\test_file.py -> build\lib.win-amd64-3.4\h5py\tests\hl

    copying h5py\tests\hl\__init__.py -> build\lib.win-amd64-3.4\h5py\tests\hl

    Skipping implicit fixer: buffer

    Skipping implicit fixer: idioms

    Skipping implicit fixer: set_literal

    Skipping implicit fixer: ws_comma

    running build_ext

    ********************************************************************************

                           Summary of the h5py configuration

        Path to HDF5: None

        HDF5 Version: '1.8.4'

         MPI Enabled: False

    Rebuild Required: False

    ********************************************************************************

    Executing api_gen rebuild of defs

    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\defs.pyx because it
changed.

    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\_errors.pyx because
it changed.

    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\_objects.pyx because
 it changed.

    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\_proxy.pyx because i
t changed.

    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5fd.pyx because it
changed.

    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5z.pyx because it c
hanged.

    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5.pyx because it ch
anged.

    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5i.pyx because it c
hanged.

    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5r.pyx because it c
hanged.

    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\utils.pyx because it
 changed.

    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\_conv.pyx because it
 changed.

    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5t.pyx because it c
hanged.

    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5s.pyx because it c
hanged.

    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5p.pyx because it c
hanged.

    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5d.pyx because it c
hanged.

    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5a.pyx because it c
hanged.

    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5f.pyx because it c
hanged.

    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5g.pyx because it c
hanged.

    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5l.pyx because it c
hanged.

    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5o.pyx because it c
hanged.

    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5ds.pyx because it
changed.

    Compiling C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5ac.pyx because it
changed.

    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\_conv.pyx

    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\_errors.pyx

    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\_objects.pyx

    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\_proxy.pyx

    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\defs.pyx

    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5.pyx

    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5a.pyx

    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5ac.pyx

    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5d.pyx

    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5ds.pyx

    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5f.pyx

    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5fd.pyx

    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5g.pyx

    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5i.pyx

    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5l.pyx

    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5o.pyx

    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5p.pyx

    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5r.pyx

    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5s.pyx

    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5t.pyx

    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\h5z.pyx

    Cythonizing C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\h5py\utils.pyx

    LLVM version 3.1svn, 3.1svn

    Autodetection skipped [[WinError 126] The specified module could not be found]

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\setup.py", line 147, in <mo
dule>

        cmdclass = CMDCLASS,

      File "C:\Anaconda3\lib\distutils\core.py", line 148, in setup

        dist.run_commands()

      File "C:\Anaconda3\lib\distutils\dist.py", line 955, in run_commands

        self.run_command(cmd)

      File "C:\Anaconda3\lib\distutils\dist.py", line 974, in run_command

        cmd_obj.run()

      File "C:\Anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run

        return orig.install.run(self)

      File "C:\Anaconda3\lib\distutils\command\install.py", line 539, in run

        self.run_command('build')

      File "C:\Anaconda3\lib\distutils\cmd.py", line 313, in run_command

        self.distribution.run_command(command)

      File "C:\Anaconda3\lib\distutils\dist.py", line 974, in run_command

        cmd_obj.run()

      File "C:\Anaconda3\lib\distutils\command\build.py", line 126, in run

        self.run_command(cmd_name)

      File "C:\Anaconda3\lib\distutils\cmd.py", line 313, in run_command

        self.distribution.run_command(command)

      File "C:\Anaconda3\lib\distutils\dist.py", line 974, in run_command

        cmd_obj.run()

      File "C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py\setup_build.py", line 133,
in run

        build_ext.run(self)

      File "C:\Anaconda3\lib\distutils\command\build_ext.py", line 308, in run

        force=self.force)

      File "C:\Anaconda3\lib\distutils\ccompiler.py", line 1031, in new_compiler

        return klass(None, dry_run, force)

      File "C:\Anaconda3\lib\distutils\cygwinccompiler.py", line 282, in __init__

        CygwinCCompiler.__init__ (self, verbose, dry_run, force)

      File "C:\Anaconda3\lib\distutils\cygwinccompiler.py", line 126, in __init__

        if self.ld_version >= "2.10.90":

    TypeError: unorderable types: NoneType() >= str()

    ----------------------------------------
    Rolling back uninstall of h5py
    Command "C:\Anaconda3\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\MYEXPE~1\\
AppData\\Local\\Temp\\pip-build-lyjh094j\\h5py\\setup.py';exec(compile(getattr(tokenize, 'open', ope
n)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\MYEXPE~1\Ap
pData\Local\Temp\pip-x20abzh_-record\install-record.txt --single-version-externally-managed --compil
e" failed with error code 1 in C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-lyjh094j\h5py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Here is the package list:
C:\Anaconda3\Scripts>pip list
argcomplete (0.8.4)
astropy (0.4.2)
Bayesian (0.3.1)
bcolz (0.7.3.dev0)
beautifulsoup4 (4.3.2)
binstar (0.9.5)
bitarray (0.8.1)
blaze (0.7.0)
blz (0.6.2)
bokeh (0.7.0)
boto (2.34.0)
cffi (0.8.6)
clyent (0.3.2)
colorama (0.3.2)
conda (3.7.4)
conda-build (1.8.2)
configobj (5.0.6)
cryptography (0.7.1)
Cython (0.21.2)
cytoolz (0.7.1)
DataShape (0.4.2)
decorator (3.4.0)
Django (1.7.2)
docutils (0.12)
Flask (0.10.1)
future (0.14.3)
geopy (1.7.1)
greenlet (0.4.5)
h5py (2.3.1)
idlex (1.12)
into (0.1.3)
ipython (2.3.1)
itsdangerous (0.24)
jdcal (1.0)
Jinja2 (2.7.3)
llvmlite (0.2.0)
llvmpy (0.12.7)
lxml (3.4.1)
MarkupSafe (0.23)
matplotlib (1.4.2)
menuinst (1.0.4)
mock (1.0.1)
multipledispatch (0.4.7)
networkx (1.9.1)
nltk (3.0.0)
nose (1.3.4)
numba (0.16.0)
numexpr (2.3.1)
numpy (1.9.1)
openpyxl (2.1.4)
pandas (0.15.2)
patsy (0.3.0)
Pillow (2.7.0)
pip (6.0.6)
ply (3.4)
psutil (2.2.0)
py (1.4.26)
pycosat (0.6.1)
pycparser (2.10)
pycrypto (2.6.1)
pyDatalog (0.15.0)
pyflakes (0.8.1)
Pygments (2.0.1)
pyOpenSSL (0.14)
pyparsing (2.0.3)
pyreadline (2.0)
pytest (2.6.4)
python-dateutil (2.4.0)
pytz (2014.10)
pywin32 (219)
PyYAML (3.11)
pyzmq (14.4.1)
requests (2.5.1)
rope-py3k (0.9.4-1)
runipy (0.1.1)
scikit-image (0.10.1)
scikit-learn (0.15.2)
scipy (0.14.1)
setuptools (11.3.1)
six (1.9.0)
sockjs-tornado (1.0.1)
Sphinx (1.2.3)
spyder (2.3.2)
SQLAlchemy (0.9.8)
statsmodels (0.6.1)
StochPy (2.2)
sympy (0.7.6)
tables (3.1.1)
toolz (0.7.1)
tornado (4.0.2)
ujson (1.33)
virtualenv (12.0.5)
Werkzeug (0.9.6)
wheel (0.24.0)
xlrd (0.9.3)
XlsxWriter (0.6.5)
---------------------------
Regards

**Comment by andrewcollette** [comment]
Installing h5py on Windows from source is very hard and requires that you first build HDF5.  Since you're using Anaconda, it's strongly recommended to use the official Anaconda h5py package.

Also, the error in this case appears to be a Python 3 bug in an Anaconda-supplied compiler script:

```
File "C:\Anaconda3\lib\distutils\cygwinccompiler.py", line 126, in __init__

    if self.ld_version >= "2.10.90":
```
