### ISSUE TITLE
license.txt -> root

### ISSUE THREAD

**Issue by chinasaur** [h5py/h5py#516]
Would it be possible to move licenses/license.txt to root level?

**Comment by andrewcollette** [comment]
Can I ask why?

**Comment by chinasaur** [comment]
It's helpful to distinguish the project license from the sublicenses.

**Comment by andrewcollette** [comment]
I don't find this a compelling enough reason to switch.

Also, please close your other const-related PRs and submit the changes together as one... handling 7 different PRs each with a one-line fix is a lot of overhead.
