### ISSUE TITLE
What's new for version 2.4?

### ISSUE THREAD

**Issue by shoyer** [h5py/h5py#529]
I noticed that version 2.4 was released last week (congratulations!) and thought I would read the "what's new" notes, but I can't find them on the website. Have you had the chance to write them yet? I find these sort of documents very useful :).

**Comment by andrewcollette** [comment]
Good catch... I forgot to type those up.  ANN.txt has a good summary, though (in the distribution root).

**Comment by shoyer** [comment]
Thanks, that file was informative

**Comment by andrewcollette** [comment]
Added to 2.4 docs, merged to master.
