### ISSUE TITLE
Merge 2.4 branch into master

### ISSUE THREAD

**Issue by aragilar** [h5py/h5py#530]
Currently `master` still has the version 2.4.0b1, so the `2.4` branch is treated as being newer than `master`. Can the `2.4` branch be merged into master?

**Comment by andrewcollette** [comment]
Yes... when I have a moment I'll either do that or bump the version to 2.5.0b1.  Thanks!

**Comment by andrewcollette** [comment]
OK; have merged 2.4 and also updated the master branch version (to 2.5.0a0).
