### ISSUE TITLE
Pickle loads/dumps roundtrip fails

### ISSUE THREAD

**Issue by mrocklin** [h5py/h5py#531]
While `pickle.dumps` works fine with `protocol=2` (commonly used for numeric data), `pickle.loads` fails to deserialize this result. 

``` Python
In [1]: import h5py
In [2]: f = h5py.File('foo.hdf5')

In [3]: import pickle
In [4]: pickle.dumps(f, protocol=2)
Out[4]: '\x80\x02ch5py._hl.files\nFile\nq\x00)\x81q\x01}q\x02U\x03_idq\x03ch5py.h5f\nFileID\nq\x04)\x81q\x05sb.'

In [5]: pickle.loads(_)
TypeError: __cinit__() takes exactly 1 positional argument (0 given)
```

**Comment by andrewcollette** [comment]
The vast majority of objects in h5py (except for TypeIDs and SpaceIDs) can't be pickled.  This is because all state information resides with HDF5; in other words, there's no way to reliably reconstruct the object on unpickling.

We should probably make this more obvious... for example, attempting to pickle an object should raise TypeError.

**Comment by mrocklin** [comment]
Raising a `TypeError` on `dumps` would resolve my current issue.

**Comment by mrocklin** [comment]
Looks like a `TypeError` *is* raised when `protocol < 2`

**Comment by mrocklin** [comment]
Actually, what state is present in an `h5py.Dataset` that isn't retrievable by its datapath?  Perhaps my use case is simplistic, but I can generally fully specify a dataset with filename and datapath.

**Comment by andrewcollette** [comment]
There are file-related things like the driver used, buffering settings, etc.  And because of external links, the file object graph can change at any time.  There's also the issue of how to find files when unpickling; what to do if the file/dataset is unpickled on a platform which doesn't have the right compression plugins...

**Comment by stsievert** [comment]
What progress has been made on this? I think I ran into this issue while trying to serialize an in-memory HDF file.

I'm using a library that writes to an HDF file. After it's returned from this library, it's only read from and never written to after the first save. How can I serialize this object?

**Comment by jakirkham** [comment]
Have you looked at `h5pickle`?

**Comment by tacaswell** [comment]
The action item here is to make attempts to pickle an h5 object fail fast.

**Comment by tacaswell** [comment]
If people have cycles to devote to this, the best use may be to review #1061 so you can move the `BytesIO` object around (rather than trying to move the h5py objects around).

**Comment by takluyver** [comment]
OK, so shall we disable pickling and then override functionality to re-enable copy/deepcopy?

What should copy/deepcopy mean? h5py's high-level objects are, I think, mostly stateless wrappers around HDF5 objects which may have state both in-memory and on-disk. Normally, you'd expect copying an object to make a similar but independent object, so you can modify one without affecting the other. But obviously you don't expect copying a file handle to somehow make a second file with the same name.

I guess the most likely answer is to 'cheat' - let copy() and deepcopy() copy just the Python wrapper, referring to the same HDF5 object. Does that seem reasonable? Or we could disable copying too, but that could be annoying if you `deepcopy` some data structure which has h5py objects somwhere in it.

**Comment by aparamon** [comment]
I think the answers depend on the actual work-flow desired. What is the purpose of `pickle`ing (serializing) HDF5 objects while HDF5 is itself storage/serialization format? I imagine one sensible application: parallel processing of HDF5 data on systems lacking `fork`; but it's impossible to accurately reconstruct the internal HDF5 library objects structure (e.g. caches) by way of Python `pickle` in a different process.

Are there any other sensible applications I'm missing to see?

**Comment by takluyver** [comment]
From other issues, I think the time people are most likely to see this is parallelism with multiprocessing: in some circumstances, it uses pickle to copy objects into worker processes. In that case, it's probably sufficient to do what h5pickle does: serialise the path of the file and the path inside the file, along with other details like the file mode, and open it again in the worker.

But even for parallelisation, you could be sending it to a worker process on a different system, which may not be able to open the same file. So I buy the argument that it should fail with a clear error on pickling, so it's not giving a false impression that it works.

What I'm wondering about now is how in-process copies (by the [copy module](https://docs.python.org/3/library/copy.html#module-copy)) should work. This is nothing to do with serialising it or transferring it to another process:

```python
import copy
import h5py

f = h5py.File('foo.h5')
f2 = copy(f)
```

I think I'm convinced that it's OK for f and f2 to wrap the same HDF5 ID.

**Comment by takluyver** [comment]
I've just found that `copy.copy(f)` fails on regular Python file handles with:

```
TypeError: cannot serialize '_io.BufferedWriter' object
```

This is also the error you get if you try to pickle them. So I think it's fine for h5py objects to behave the same way.

**Comment by takluyver** [comment]
Opened PR #1194 to explicitly disable pickle.
