### ISSUE TITLE
add configure hooks to support new HDF5 install layout on Debian / Ubuntu

### ISSUE THREAD

**Issue by ghisvail** [h5py/h5py#536]
I am trying to use the latest version of h5py (2.4.0 at the time of writing) on my Debian Jessie machine but cannot get it to install on a clean venv. This is due to the fact that Debian operated a re-organization of the installation layout of HDF5 since v1.8.13 to allow co-installation of the different flavours of the library (serial, mpich, openmpi...). This issue is also going to affect any version of Ubuntu shipping hdf5 v1.8.13+, i.e. Ubuntu 15.04 and later.

The version of h5py currently packaged is stuck at 2.2.1, which allowed us to specify manually the location of the include and lib files by hacking CPPFLAGS and LDFLAGS.

Now, h5py is using a configure step which assumes a rigid layout around $HDF5_DIR to find the headers and libs, whereby $HDF5_DIR is set by an environment variable or a command line option. A solution for us would be to provide additional hooks to `python configure` to specify our custom include and lib locations.

Cheers,
- Ghis

**Comment by andrewcollette** [comment]
Thankfully such an improvement is already under way in #533!  Let us know if you have any comments on that approach.

**Comment by szechyjs** [comment]
:+1:

**Comment by szechyjs** [comment]
any progress on this?

**Comment by aragilar** [comment]
@szechyjs Does the pkg-config support fix your problem? It's been in for a while.

**Comment by takluyver** [comment]
#734 looks like it was meant to fix this, so I'll close it. Please open new bugs if there are still issues with building.
