### ISSUE TITLE
License, integration into hdf5oct and evtl Octave core

### ISSUE THREAD

**Issue by stegro** [h5py/h5py#547]
Hello everyone,

if you permit, I would like to copy your BSD-licensed autochunk function
https://github.com/h5py/h5py/blob/master/h5py/_hl/filters.py#L257
into the hdf5oct package https://github.com/stegro/hdf5oct, translate it to C++ and work on that copy under the LGPL (as part of hdf5oct) or finally GPL (as soon as it becomes part of Octave core), instead of reinventing the wheel.
Is this okay for you? According to git blame, the author of this function is Andrew Collette, and I would put a Copyright note "Copyright 2008-2013 Andrew Collette"
at the top of the file, or whatever is necessary to respect the copyright of the original author(s).

Thanks for your good work,

cheers

Stefan

**Comment by andrewcollette** [comment]
Thanks for checking!  Yes, since this is BSD licensed inclusion in a GPL/LGPL project is perfectly fine.  Please read our license file and follow its instructions:

https://github.com/h5py/h5py/blob/master/licenses/license.txt
