### ISSUE TITLE
Python test fails

### ISSUE THREAD

**Issue by JohnCC330** [h5py/h5py#554]
I just installed Cython 0.22, and h5py 2.4.0, on a system with Python 2.7.6.

Running python setup.py test, I get:

    running test
    running build_py
    running build_ext
    Autodetected HDF5 1.8.13
    ********************************************************************************
                           Summary of the h5py configuration
    
        Path to HDF5: None
        HDF5 Version: '1.8.13'
         MPI Enabled: False
    Rebuild Required: False
    ...
    FAIL: test_default (h5py.tests.old.test_file.TestFileOpen)
    Default semantics in the presence or absence of a file
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/local/src/programming/python/h5py-2.4.0/build/lib.linux-x86_64-2.7/h5py/tests    /old/test_file.py", line 46, in test_default
        self.assertEqual(f.mode, 'r')
    AssertionError: 'r+' != 'r'

Same error appears in Python, when running the test there. Note the version reported! The import works fine though.
Should I worry?

**Comment by andrewcollette** [comment]
@JohnCC330, I don't think there's anything to worry about, but thanks for letting us know.  At the very least the test is broken.

**Comment by andrewcollette** [comment]
Closing in favor of #696, which has an associated PR and can be reproduced on a Docker container.
