### ISSUE TITLE
ImportError: cannot import name '_errors'

### ISSUE THREAD

**Issue by crypotex** [h5py/h5py#557]
I see that this has been an error before many times. 
I just installed ubuntu 14.04 and started installing necessary software.
Here is what I did to get h5py to work using setup.py and files from pypi: 
8) Try install h5py, need hdf5 and cython 
    8.1) Install cython -> install failed 
        8.1.1) Try fix -> sudo apt-get install build essential, no work
        8.1.2) Try fix -> sudo apt-get install python-dev, no work
        8.1.3) Try fix -> sudo apt-get install python3.4-dev -> fixed it, installed it
    8.2) Install hdf5, needs cmake
        8.2.1) better -> sudo apt-get install libhdf5-dev
Now when i build & install, it says Finished processing dependencies for h5py==2.4.0 -> so i quess it works. 
Now when I go to python3, try import h5py, it fails, full error here: 
  >>> import h5py
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/andre/school/h5py/h5py-2.4.0/h5py/__init__.py", line 10, in <module>
      from h5py import _errors
  ImportError: cannot import name '_errors'

So I started looking for errors and I found that in previous versions there has been this issue, So I ran the tests. 
```
sudo python3 setup.py test
running test
running build_py
running build_ext
Autodetected HDF5 1.8.11
********************************************************************************
                       Summary of the h5py configuration

    Path to HDF5: None
    HDF5 Version: '1.8.11'
     MPI Enabled: False
Rebuild Required: False

********************************************************************************
...................................................x.......................s.......................................x..............................s........ss......F............................................................................ssssss.................................................................x....x..x................x...x..............................
======================================================================
FAIL: test_default (h5py.tests.old.test_file.TestFileOpen)
Default semantics in the presence or absence of a file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andre/school/h5py/h5py-2.4.0/build/lib.linux-x86_64-3.4/h5py/tests/old/test_file.py", line 46, in test_default
    self.assertEqual(f.mode, 'r')
AssertionError: 'r+' != 'r'
- r+
?  -
+ r


----------------------------------------------------------------------
Ran 371 tests in 0.798s

FAILED (failures=1, skipped=10, expected failures=7)
```

**Comment by andrewcollette** [comment]
@crypotex, I suspect this is because you are importing the h5py module while still inside the h5py install directory (there's a "h5py" directory there which confuses the import machinery).  Change to any other directory first.

**Comment by crypotex** [comment]
Oh yes that works. Feeling kind of stupid now. 
Thank you.

**Comment by andrewcollette** [comment]
No problem.  Been meaning to add a warning for a while now... thanks for the reminder (#558).

**Comment by saeed68gm** [comment]
I get this error when I try to setup keras from my own fork. I had to uninstall and reinstall h5py with pip to get rid of this issue.
