### ISSUE TITLE
Can't create file with mode="a"

### ISSUE THREAD

**Issue by rwb27** [h5py/h5py#564]
I'd like to open or create a file using a file dialog, so the user supplies a filename that may or may not exist.

If the file exists, all is well and it's opened read/write.  If the file doesn't exist, it produces an exception and dumps information to the console: 
  
  >>> f = h5py.File(r"test3.h5",mode='a')
  HDF5-DIAG: Error detected in HDF5 (1.8.9) thread 0:
    #000: ..\..\src\H5F.c line 1534 in H5Fopen(): unable to open file
      major: File accessability
      minor: Unable to open file
    #001: ..\..\src\H5F.c line 1223 in H5F_open(): unable to open file: time = Thu Apr 16 17:56:51 2015
, name = 'test3.h5', tent_flags = 1
      major: File accessability
      minor: Unable to open file
    #002: ..\..\src\H5FD.c line 1101 in H5FD_open(): open failed
      major: Virtual File Layer
      minor: Unable to initialize object
    #003: ..\..\src\H5FDsec2.c line 362 in H5FD_sec2_open(): unable to open file: name = 'test3.h5', errno = 2, error message = 'No such file or directory', flags = 1, o_flags = 2
      major: File accessability
      minor: Unable to open file
  HDF5-DIAG: Error detected in HDF5 (1.8.9) thread 0:
    #000: ..\..\src\H5F.c line 210 in H5Fget_create_plist(): not a file
      major: Invalid arguments to routine
      minor: Inappropriate type
  HDF5-DIAG: Error detected in HDF5 (1.8.9) thread 0:
    #000: ..\..\src\H5P.c line 864 in H5Pget_class(): not a property list
      major: Invalid arguments to routine
      minor: Inappropriate type
  HDF5-DIAG: Error detected in HDF5 (1.8.9) thread 0:
    #000: ..\..\src\H5P.c line 978 in H5Pequal(): not property objects
      major: Invalid arguments to routine
      minor: Inappropriate type
  HDF5-DIAG: Error detected in HDF5 (1.8.9) thread 0:
    #000: ..\..\src\H5P.c line 1525 in H5Pclose_class(): not a property list class
      major: Invalid arguments to routine
      minor: Inappropriate type

So, for me, `h5py.File("new.h5",mode="a")` doesn't work, while  `h5py.File("new.h5",mode="w")` does work, and  `h5py.File("exists.h5",mode="a")` is also fine.

The version information is:
  >>> print h5py.version.info
  Summary of the h5py configuration
  ---------------------------------
  h5py    2.2.1
  HDF5    1.8.9
  Python  2.7.6 |Anaconda 1.9.2 (64-bit)| (default, Nov 11 2013, 10:49:15) [MSC v.1500 64 bit (AMD64)]
  sys.platform    win32
  sys.maxsize     9223372036854775807
  numpy   1.8.0

Thanks!

**Comment by andrewcollette** [comment]
Very odd... the "a" flag is part of our test suite, and I just tried it myself and it works on my platform.  I'm also surprised you see the diagnostic output.  We configure HDF5 to suppress those messages.

I noticed you are using an older version of h5py from the Anaconda distribution.  Could you try a more recent version?  I think they now ship 2.4.0.

**Comment by rwb27** [comment]
Hello,
  I've now tried it with 2.4 and it's all working fine.  In fact, I re-tried my example code on the computer I was running before: if I do something silly it still prints the debug info, but mode='a' worked as expected - I can only blame the gremlins - I guess something wierd must have happened on that machine...
  Thanks for your help,

Richard

**Comment by petebachant** [comment]
I just had this or a similar error occur, and I think it was because the file was opened by another process. After restarting that Jupyter kernel, all was okay. The file did exist the whole time.

**Comment by candiceT233** [comment]
I am having the same issue with version 3.7 when using a passthrough VOL. Using "a" results in the error below. My current solution is to check if does not exist I use "w".

`    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open`
