### ISSUE TITLE
h5py files and groups could use a more informative repr

### ISSUE THREAD

**Issue by shoyer** [h5py/h5py#566]
I've recently been playing around with h5py with an eye towards [writing netCDF4 files](https://github.com/shoyer/h5netcdf). So far it's been quite a pleasure -- thanks for your hard work!

One thing I've noticed is that the standard `__repr__` makes it rather slow to explore h5py files -- I end up calling `.items()` or `dict` on groups quite often to figure out what is inside them. This makes things less pleasant than they could be -- see [this blog post](http://matthewrocklin.com/blog/work/2014/11/19/Blaze-Datasets/) by @mrocklin for an extended discussion.

It would be nice if the default repr showed more than `<HDF5 file "test.nc" (mode r)>`. For example, by default it might show short summaries of all (direct) child groups, variables and attributes. Thoughts?

**Comment by andrewcollette** [comment]
Cool blog post... thanks!  But I think we'll leave this one to third-party packages, like blaze.  A fast, compact repr() is appropriate for a library package like h5py.

**Comment by mrocklin** [comment]
Alternatively to `repr` you could override `__dir__` and `__getattr__`.  This is cheap, straightforward, and fairly unambiguous.

**Comment by andrewcollette** [comment]
@mrocklin... one of the design goals for h5py was to not mix the Python attribute namespace with the file object namespace.  We have a strict dictionary metaphor for groups and attributes.

Btw, there is an IPython completer for h5py... call h5py.enable_ipython_completer() and you can use TAB completion on names:

```
>>> import h5py
>>> h5py.enable_ipython_completer()
>>> f = h5py.File('myfile.hdf5')
>>> f['<TAB>
group1 group2 group2
```

**Comment by mrocklin** [comment]
Fair enough.  I've appreciated the sanity of h5py in the past.

**Comment by anthonytw** [comment]
Can this possibly be reconsidered? I appreciate the overall design philosophy of h5py as a streamlined library interface, and I think a modestly improved repr would not derail that goal. I have a short patch for files, groups, and key views that makes browsing much more convenient. I can submit a pull request which you are of course free to reject, but I think would be a greatly appreciated fix with no performance impact on library performance.
