### ISSUE TITLE
cython compile errors: missing file mpi4py/mpi_c.pxd

### ISSUE THREAD

**Issue by afylot** [h5py/h5py#567]
I am compiling h5py 2.5.0 with mpi support, hdf5 1.8.14, python 3.4, mpi4py 2.0.0

When running

python3 setup.py build

I get the following error:

h5py/h5p.pyx:28:4: 'mpi4py/mpi_c.pxd' not found

at the beginning I thought it was the same problem as in https://github.com/h5py/h5py/issues/532
 but then I realized that I do not have mpi_c.pxd anywhere in the mpi4py installation directory. In fact I have installed and tested mpi4py as in http://mpi4py.scipy.org/docs/usrman/install.html

what is the issue, should I use an older version of mpi4py?

**Comment by andrewcollette** [comment]
Odd... what does the output of `mpi4py.get_include()` say?

Also, where did you get mpi4py 2.0.0?  The latest I can find is 1.3.1.

**Comment by afylot** [comment]
mpi4py.get_include():
/clusterdata/afylot/local/lib64/python3.4/site-packages/mpi4py/include

I got mpi4py from https://bitbucket.org/mpi4py/mpi4py/overview , from the `clone` button on the top left.  I am not sure where I deduced I was using version 2.0.0

**Comment by afylot** [comment]
Anyway, I have now downloaded version mpi4py 1.3.1 and now it builds and installs (but h5py doesn't work yet)

**Comment by rdhyee** [comment]
Thanks @afylot for posting this issue.  I ran into the same problem.  What's worked for me was that in addition to implementing the idea from https://github.com/h5py/h5py/issues/532#issuecomment-73631137, I got my setup to work by reversing https://github.com/h5py/h5py/commit/bdd573ff73711ccce339a91ac82a058cdd910498.  See:

https://github.com/rdhyee/h5py/commit/f2e3f132fdc1c2308b74e8428c063ac6a8118439#diff-c9e1291e5e01f0f5e0a484dccaf67cf6L28

I've not issued a PR until I better understand whether my change actually works in practice and whether my changes are too particular to my own environment.

**Comment by pavanakumar** [comment]
@rdhyee : Thanks. Works like a charm on my mac osx Yosmite .

**Comment by rdhyee** [comment]
@pavanakumar glad that my fix works for you and thanks for letting us know!

**Comment by valandil** [comment]
This fix has worked for me to. However, wouldn't it better if h5py detected the version of mpi4py and included the proper directories accordingly? I have tried implementing that with

https://github.com/valandil/h5py/commit/2698f3800a2d123289f6e32a11b4283324becd64

but that doesn't seem to work properly.
