### ISSUE TITLE
TypeError: No conversion path for dtype: dtype('<M8[us]')

### ISSUE THREAD

**Issue by jkhoogland** [h5py/h5py#568]
Hi,
I was trying out some basic conversion of an yahoo option chain to hdf5 using odo and h5py.

```
from pandas.io.data import Options

aapl = Options('aapl', 'yahoo')
data = aapl.get_all_data()

from odo import odo

odo(data,'aapl.hdf5::/oc')
```

The data loads fine, but when trying to save to the hdf5 file,
it fails with the following error:

```
/Users/Jiri/anaconda/lib/python3.4/site-packages/h5py/_hl/dataset.py in make_new_dset(parent, shape, dtype, data, chunks, compression, shuffle, fletcher32, maxshape, compression_opts, fillvalue, scaleoffset, track_times)
     77         else:
     78             dtype = numpy.dtype(dtype)
---> 79         tid = h5t.py_create(dtype, logical=1)
     80 
     81     # Legacy

h5t.pyx in h5py.h5t.py_create (h5py/h5t.c:13966)()

h5t.pyx in h5py.h5t.py_create (h5py/h5t.c:13504)()

h5t.pyx in h5py.h5t._c_compound (h5py/h5t.c:12883)()

h5t.pyx in h5py.h5t.py_create (h5py/h5t.c:13858)()

TypeError: No conversion path for dtype: dtype('<M8[us]')
```

I might be missing something, but this seems like a bug, 
ie a missing conversion looking at the exception.

Is this a known issue ?
Regards
Jiri 

I m using the following packages

   package                    |            build
    ---------------------------|-------------------
    pytz-2015.2                |           py34_0
    toolz-0.7.1                |           py34_0
    python-dateutil-2.4.2      |           py34_0
    datashape-0.4.4            |       np19py34_1
    pandas-0.16.0              |       np19py34_1
    odo-0.3.1                  |       np19py34_0

**Comment by tacaswell** [comment]
For reference, '<M8[us]' is a datetime64 type specification (http://docs.scipy.org/doc/numpy/reference/arrays.datetime.html#datetime-units) which seem to not be well supported by things that are not pandas.

attn @cpcloud

**Comment by andrewcollette** [comment]
@tacaswell, thanks... I've not seen that dtype before.

Unfortunately, HDF5 has no native support for time types.  We have managed to shoehorn in a few oddball types like NumPy's bool and complex, by using features of HDF5's type system. For example, complex numbers are written as a 2-member compound type.  Datetimes seem much too complicated for that solution.

I think you will need to address this at the application level.  For example, by converting to an HDF5 type of the appropriate precision (64-bit uint?), and tagging the dataset with HDF5 attributes that indicate it has time information.

**Comment by tacaswell** [comment]
@jkhoogland You should bring this up with either the pandas or odo folks.
