### ISSUE TITLE
import h5py: undefined symbol: H5Pget_fapl_mpio

### ISSUE THREAD

**Issue by afylot** [h5py/h5py#569]
I have installed h5py 2.5.0 with mpi switched on.

I used:

    export CC=mpicc
    python3 setup.py configure --mpi
    python3 setup.py build
    python3 setup.py install --prefix=/clusterdata/afylot/local/

(python3 is alias for python 3.4)
When I import h5py from ipython3 I get 

     ImportError: /clusterdata/afylot/local/lib64/python3.4/site-packages/h5py-2.5.0-py3.4-linux-x86_64.egg/h5py/defs.cpython-34m.so: undefined symbol: H5Pget_fapl_mpio

I have checked is mpi is enable by running  configure:

     python3 setup.py configure --hdf5=/clusterdata/afylot/local/hdf5-1.8.14/hdf5/lib/ --mpi

     running configure
     Autodetected HDF5 1.8.14
     ********************************************************************************
                           Summary of the h5py configuration
     
         Path to HDF5: '/clusterdata/afylot/local/hdf5-1.8.14/hdf5/lib/'
                HDF5 Version: '1.8.14'
              	         MPI Enabled: True
	                 Rebuild Required: False
     
     ********************************************************************************

**Comment by afylot** [comment]
the complete error:

     In [3]: import h5py
     ---------------------------------------------------------------------------
     ImportError                               Traceback (most recent call last)
     <ipython-input-3-e81388eeaef8> in <module>()
     ----> 1 import h5py
     
     /clusterdata/afylot/local/lib64/python3.4/site-packages/h5py-2.5.0-py3.4-linux-     x86_64.egg/h5py/__init__.py in <module>()
          21 _errors.silence_errors()
               22
	       ---> 23 from . import _conv
	            24 _conv.register_converters()
	                 25
     
     /clusterdata/afylot/h5py/h5r.pxd in init h5py._conv (/clusterdata/afylot/download/h5py-2.5.0/h5py/_conv.c:7274)()
     
     /clusterdata/afylot/h5py/_objects.pxd in init h5py.h5r (/clusterdata/afylot/download/h5py-2.5.0/h5py/h5r.c:3184)()
     
     /clusterdata/afylot/h5py/_objects.pyx in init h5py._objects (/clusterdata/afylot/download/h5py-2.5.0/h5py/_objects.c:7285)()
     
     ImportError: /clusterdata/afylot/local/lib64/python3.4/site-packages/h5py-2.5.0-py3.4-linux-x86_64.egg/h5py/defs.cpython-34m.so: undefined symbol: H5Pget_fapl_mpio

**Comment by andrewcollette** [comment]
This typically means you are not compiling against the right build of HDF5, or at runtime it's finding the wrong one.  Try removing "lib/" from the end of your "--hdf5" option.

**Comment by afylot** [comment]
yes, it works now
