### ISSUE TITLE
attribute creation error (with compound and array types)

### ISSUE THREAD

**Issue by jreadey** [h5py/h5py#573]
If I've defined a compound type with an array type element, like so:

```
dt = np.dtype([('temp', np.float), ("2x2", np.dtype('(2,2)f'))])
```

How do I setup the values to create an array with that type?
E.g.
```
arr = np.array([[0.0, 0.0], [0.0, 0.0]])
v = (98.6, arr)
ds1.attrs.create('A1', v, dtype=dt)
```

Gives an error: ValueError: setting an array element with a sequence.

**Comment by andrewcollette** [comment]
This is a general problem with NumPy; the array constructor can't handle complex nested dtypes, e.g.:

```
arr = np.array([0, [[0,0],[0,0]]], dtype=dt)
```
yields TypeError.  Instead, initialize the compound members one by one:

```
arr = np.empty((), dtype=dt)
arr['temp'] = 0.0
arr['2x2'] = [[0,0],[0,0]]

ds1.attrs['A1'] = arr
```

**Comment by jreadey** [comment]
Ok thanks!  I couldn't find any examples of this pattern when I was searching the NumPy docs yesterday.
