### ISSUE TITLE
Incorrect dependency on Cython?

### ISSUE THREAD

**Issue by QuLogic** [h5py/h5py#577]
The readme states that Cython is required for building. However, `setup.py` includes `Cython` in `requires` which is a _runtime_ requirement.

If for example, you install `h5py` in `conda` (which is pre-built), then run `python setup.py install` for a package that depends on `h5py`, it will attempt to install `Cython` as a dependency of `h5py`.

So it seems that either the readme is wrong, or `setup.py` is wrong.

**Comment by andrewcollette** [comment]
As I recall this was a workaround for other broken behavior with setuptools/pip.  It's mostly working now, and I'm not eager to change anything because the whole process is so fragile.

**Comment by QuLogic** [comment]
I don't see how that could be the case. Entries in `requires` are installed _after_ the requested package, so they couldn't have any effect on the installation process.

The log shows it was added in 0fad9f00f70d256125b9940a7a5738ae20fe60c6 as part of a refactoring, not in response to any bugs. So as long as removing it works for you, I don't think it would break anything.

**Comment by andrewcollette** [comment]
Hmmm.... maybe I was too hasty on this one.  Btw we just merged a PR which adds NumPy & Cython to setup_requires.

**Comment by aragilar** [comment]
This was fixed by #650.
