### ISSUE TITLE
Read unicode strings in attributes

### ISSUE THREAD

**Issue by tritemio** [h5py/h5py#585]
Hi,

seems like h5py cannot read unicode strings from attributes. I have files created with pytables with unicode strings in attributes that load correctly on HDFView but fail to load on h5py:

```
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-7-4388c265af37> in <module>()
----> 1 h5file.attrs['format_name']

h5py\_objects.pyx in h5py._objects.with_phil.wrapper (D:\Build\h5py\h5py-2.4.x\h5py\_objects.c:2413)()

h5py\_objects.pyx in h5py._objects.with_phil.wrapper (D:\Build\h5py\h5py-2.4.x\h5py\_objects.c:2370)()

C:\Users\laser2002j\Anaconda\lib\site-packages\h5py\_hl\attrs.pyc in __getitem__(self, name)
     58 
     59         arr = numpy.ndarray(attr.shape, dtype=rtdt, order='C')
---> 60         attr.read(arr)
     61 
     62         if len(arr.shape) == 0:

h5py\_objects.pyx in h5py._objects.with_phil.wrapper (D:\Build\h5py\h5py-2.4.x\h5py\_objects.c:2413)()

h5py\_objects.pyx in h5py._objects.with_phil.wrapper (D:\Build\h5py\h5py-2.4.x\h5py\_objects.c:2370)()

h5py\h5a.pyx in h5py.h5a.AttrID.read (D:\Build\h5py\h5py-2.4.x\h5py\h5a.c:4896)()

h5py\_proxy.pyx in h5py._proxy.attr_rw (D:\Build\h5py\h5py-2.4.x\h5py\_proxy.c:853)()

IOError: Unable to read attribute (No appropriate function for conversion path)
```

The problem is both with python 2 and 3. I'm pushed to use unicode strings because under python 3 pytables can save only unicode strings in the TITLE attribute.

Any workaround?

**Comment by subhacom** [comment]
I encountered this issue as well when reading PyTables generated file. Is it possible to get the attribute data as binary blob and do the conversion outside h5py?

**Comment by andrewcollette** [comment]
Hard to say without knowing exactly what PyTables stores in the file.  What does a minimal example look like in h5dump?

(i.e. ``h5dump file.hdf5``)

**Comment by subhacom** [comment]
Here is a minimal example:

```python
import h5py as h5
import tables

fd = tables.File('test.h5', 'w')
fd.root._v_attrs['TITLE'] = 'test'
fd.close()

fd = h5.File('test.h5', 'r')
print('h5py:', fd.attrs['TITLE'])    
fd.close()
```

The output of h5dump is:

```
$ h5dump test.h5 
HDF5 "test.h5" {
GROUP "/" {
   ATTRIBUTE "CLASS" {
      DATATYPE  H5T_STRING {
         STRSIZE 5;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_UTF8;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "GROUP"
      }
   }
   ATTRIBUTE "PYTABLES_FORMAT_VERSION" {
      DATATYPE  H5T_STRING {
         STRSIZE 3;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_UTF8;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "2.1"
      }
   }
   ATTRIBUTE "TITLE" {
      DATATYPE  H5T_STRING {
         STRSIZE 4;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_UTF8;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "test"
      }
   }
   ATTRIBUTE "VERSION" {
      DATATYPE  H5T_STRING {
         STRSIZE 3;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_UTF8;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "1.0"
      }
   }
}
}
```

**Comment by shoyer** [comment]
The NetCDF-C library also makes fixed size UTF8 when writing strings in HDF5 files (e.g., from the Python-netCDF4 library). This was changed in the latest development version: https://github.com/Unidata/netcdf-c/pull/316

I got part way through writing a patch to add this to h5py, but it's really not clear what type "fixed length UTF8" corresponds to on the Python/NumPy side. There's definitely no built-in equivalent in NumPy, so I guess it would mean another use for `h5py.special_dtype` (i.e., storing metadata on the numpy object dtype). But that's going to a lot of trouble...

To be honest, I don't even know what `STRSIZE` means for UTF8: is it fixed size for memory usage, or the number of unicode characters? (probably the former)

**Comment by heroxbd** [comment]
It might be worth while to investigate how [vitables](https://github.com/uvemas/ViTables) implemented this feature.  Vitables can create, read and manipulate fixed length UTF-8 strings well.

**Comment by campagnola** [comment]
My workaround: https://gist.github.com/campagnola/cc044acece55171520261f68b651425a

**Comment by titusjan** [comment]
Can I ask what the status of this issue is? Is seem to me that this issue is the same as https://github.com/h5py/h5py/issues/719, which affects quite a number of people. 

Can you perhaps assign a milestone?

**Comment by t-b** [comment]
This issue here was solved by #1132.

With a HEAD version of h5py I can read attributes defined as

```
            ATTRIBUTE "IGORWaveNote" {
               DATATYPE  H5T_STRING {
                  STRSIZE 4987;
                  STRPAD H5T_STR_NULLPAD;
                  CSET H5T_CSET_UTF8;
                  CTYPE H5T_C_S1;
               }
               DATASPACE  SCALAR
            }
```

and

```
           ATTRIBUTE "IGORWaveUnits" {
               DATATYPE  H5T_STRING {
                  STRSIZE H5T_VARIABLE;
                  STRPAD H5T_STR_NULLTERM;
                  CSET H5T_CSET_UTF8;
                  CTYPE H5T_C_S1;
```

where as 2.9.0 fails.

Thanks @takluyver

**Comment by scopatz** [comment]
Is this closable then?

**Comment by takluyver** [comment]
I confess I don't really understand how #1132 fixed that. I knew I was adding a way to express fixed-size UTF-8 strings from the Python side, but I didn't think I had changed anything about how data already in a file was accessed.

But it sounds like it is fixed, somehow, so I'll close it. Please let us know if it should be reopened.
