### ISSUE TITLE
bug when indexing with a tuple of slices

### ISSUE THREAD

**Issue by SuperElectric** [h5py/h5py#586]
The following works for N-dimensional datasets, as long as N > 1:

```
index_tuple = (slice(None), ) * (N-1) + (numpy.arange(3), )
n_dimensional_dataset[index_tuple])  # fine
```

If N == 1, however, it fails:

```
index_tuple = (numpy.arange(3), )
one_dimensional_dataset[index_tuple]

*** TypeError: PointSelection __getitem__ only works with bool arrays
```

It works fine if I stick an `Ellipsis` object at the end of `index_tuple`:

```
index_tuple = (numpy.arange(3), Ellipsis)
one_dimensional_dataset[index_tuple]  # works
```

I think the problem might be that when you give a 1-element tuple to `Dataset.__getitem__`, it for some reason takes the element out and uses that as the index, rather than the tuple. I think this because I get the same error if I do that myself:

```
index_tuple = (numpy.arange(3))
one_dimensional_dataset[index_tuple[0]]

*** TypeError: PointSelection __getitem__ only works with bool arrays
```

This guess is somewhat similar to issue #584, where `Dataset.__getitem__` erroneously treats a length-1 integer array the same way as the integer it contains. Maybe this is another manifestation of the same bug?

I am using h5py 2.2.1, the version that ships with Ubuntu Linux 14.04.

**Comment by aragilar** [comment]
The reason is we're not checking whether ndarrays have bool types early enough, I'll submit a PR which fixes this soon (there's quite a few missing tests which need to be added).
