### ISSUE TITLE
Attribute Error in 'file' and 'File' Object

### ISSUE THREAD

**Issue by piltu007** [h5py/h5py#590]
I have created a `hdf5` file using ```file = open()``` command. In this case, I can write and read the file. But it is giving me attribute error when I am trying ```file.keys()```. The error is ```AttributeError: 'file' object has no attribute 'keys'```.

Then I have created a new `hdf5` file using ```file = h5py.File()``` command. In this case, I can read and use command ```file.keys()``` without any error. But I can not write in the file. The error is  ```AttributeError: 'File' object has no attribute 'write'```.

What are the reasons behind these error? Is there any difference between `'file'` object and `'File'` object?
![error](https://cloud.githubusercontent.com/assets/13003528/8393890/47bb177e-1d40-11e5-92f9-8b64d81e5a1a.png)
![error1](https://cloud.githubusercontent.com/assets/13003528/8393896/6b8108c6-1d40-11e5-943f-ec13e02755fa.png)

**Comment by andrewcollette** [comment]
HDF5 files are different than the Python files you get with open().  There's a quick introduction here:

http://docs.h5py.org/en/latest/quick.html
