### ISSUE TITLE
Multiple special_type(vlen) in single dtype (in attribute) => python crash

### ISSUE THREAD

**Issue by mpreuten** [h5py/h5py#596]
Hi everyone, 
this is my first post, so please be gentle =)
The issue arises when creating a dtype with multiple special_dtypes(vlen=str/np.X) next to each other.
Python simply crashes with something like:

> **\* Error in `python3': free(): invalid next size (fast): 0x00000000015f4c00 ***

I tried it on multiple machines (with python34):
Worked: Windows7_64 with hdf5-1.8.14 and h5py-2.5
Failed: Windows7_64 with hdf5-1.8.13 or hdf5-1.8.15 and h5py-2.5, Debian Jessie with hdf5-1.8.13 or 1.8.14 and h5py-2.4 or h5py-2.5

Here some code to provoke the error:

``` python
import numpy as np
import h5py as h5
print(h5.version.hdf5_version)
print(h5.version.version)

vls = h5.special_dtype(vlen=str)
vli = h5.special_dtype(vlen=np.uint64)
dt = np.dtype([('a', vls), ('b', vli)])
data = np.empty(2, dtype=dt)
data[0]['a'] = 'asdasd'
data[1]['a'] = 'asdasdasdasd'
data[0]['b'] = np.array(np.arange(100))
data[1]['b'] = np.array((0,))
f = h5.File('test.h5')
ds = f.require_dataset('aaa', shape=(100,), dtype=np.uint64)
ds.attrs['asd'] = data
ds.attrs.create('asda', data, shape=(2,), dtype=dt)
f.flush()
```

I saw that there were other recent issues regarding vlen data, maybe they are related?
Cheers,
Marius

**Edit**: Error only appears only when creating attributes!

**Comment by noammor** [comment]
Issue appears on Python 3.5.1 from Anaconda, h5py 2.6.0 from pypi on Ubuntu 16.04. Any known workaround?
