### ISSUE TITLE
Non string attributes broken in latest master (after #597)

### ISSUE THREAD

**Issue by gpwright** [h5py/h5py#599]
Latest version of h5py built against hdf5 swmr no longer supports creation of non string attributes for example ints or floats.  String attributes work without error.

My configuration:

OS: Ubuntu 14.04. 
hdf5 version: hdf5-1.9.222-swmr0
h5py version: ea4e2d6bd978b226e9223053592b52dbfb5a2f2b

E.g.

```python
import h5py

f = h5py.File("test.h5", "w")
g = f.create_group("group")
g.attrs["A"] = 2
```

Result:

```python
gpwright@gpwright-desktop:~$ python test.py
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    g.attrs["A"] = 2
  File "_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/gpwright/Sources/h5py/h5py/_objects.c:2511)
  File "_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/gpwright/Sources/h5py/h5py/_objects.c:2464)
  File "/usr/local/lib/python2.7/dist-packages/h5py-2.5.0-py2.7-linux-x86_64.egg/h5py/_hl/attrs.py", line 93, in __setitem__
    self.create(name, data=value, dtype=base.guess_dtype(value))
  File "/usr/local/lib/python2.7/dist-packages/h5py-2.5.0-py2.7-linux-x86_64.egg/h5py/_hl/attrs.py", line 169, in create
    htype = h5t.py_create(original_dtype, logical=True)
  File "h5t.pyx", line 1448, in h5py.h5t.py_create (/home/gpwright/Sources/h5py/h5py/h5t.c:14960)
  File "h5t.pyx", line 1468, in h5py.h5t.py_create (/home/gpwright/Sources/h5py/h5py/h5t.c:14791)
  File "h5t.pyx", line 1482, in h5py.h5t.py_create (/home/gpwright/Sources/h5py/h5py/h5t.c:14336)
  File "h5t.pyx", line 1302, in h5py.h5t._c_int (/home/gpwright/Sources/h5py/h5py/h5t.c:12338)
ValueError: Not a datatype or dataset (Not a datatype or dataset)
```

**Comment by gpwright** [comment]
Hi,

Does anyone have any insights about this?  I just tested this again on latest master and it's still a problem: 441ba1ca8658e20e335aacec043afd771ea9508d

It seems that we can no longer create h5 types from numpy types.  E.g.

```python
h5py.h5t.py_create(np.dtype('int64'))
```

raises

```python
ValueError                                Traceback (most recent call last)
<ipython-input-26-ee6f7636519b> in <module>()
----> 1 h5py.h5t.py_create(np.dtype('int64'))

/usr/local/lib/python2.7/dist-packages/h5py-2.5.0-py2.7-linux-x86_64.egg/h5py/h5t.so in h5py.h5t.py_create (/home/gwright/Sources/h5py/h5py/h5t.c:15502)()

/usr/local/lib/python2.7/dist-packages/h5py-2.5.0-py2.7-linux-x86_64.egg/h5py/h5t.so in h5py.h5t.py_create (/home/gwright/Sources/h5py/h5py/h5t.c:15333)()

/usr/local/lib/python2.7/dist-packages/h5py-2.5.0-py2.7-linux-x86_64.egg/h5py/h5t.so in h5py.h5t.py_create (/home/gwright/Sources/h5py/h5py/h5t.c:14860)()

/usr/local/lib/python2.7/dist-packages/h5py-2.5.0-py2.7-linux-x86_64.egg/h5py/h5t.so in h5py.h5t._c_int (/home/gwright/Sources/h5py/h5py/h5t.c:12771)()

ValueError: Not a datatype or dataset (Not a datatype or dataset)
```

**Comment by andrewcollette** [comment]
Looks like it might be an upstream issue with the HDF5 SWMR build.  Unfortunately there are going to be a lot of these hiccups as HDF5 1.10 moves towards alpha.  Right now I don't have a workaround... folks on the HDF-Forum list might have some better advice.

**Comment by gpwright** [comment]
Hi Andrew,

I talked to HDF5 about it and I believe it is a problem with h5py.  Because for example the following small C program to create an integer attribute works fine.  But creating any non string attribute using the h5py wrappers will fail as described already.  Let me know if you have any thoughts!  I'd really like to include h5py in my project but having to add a lot of workarounds at the moment.

Geoff


```C
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

 * Copyright by The HDF Group.                                               *

 * Copyright by the Board of Trustees of the University of Illinois.         *

 * All rights reserved.                                                      *

 *                                                                           *

 * This file is part of HDF5.  The full HDF5 copyright notice, including     *

 * terms governing use, modification, and redistribution, is contained in    *

 * the files COPYING and Copyright.html.  COPYING can be found at the root   *

 * of the source code distribution tree; Copyright.html can be found at the  *

 * root level of an installed copy of the electronic HDF5 document set and   *

 * is linked from the top-level documents page.  It can also be found at     *

 * http://hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have          *

 * access to either file, you may request a copy from help@hdfgroup.org.     *

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */



/*

 *  This example illustrates how to create an attribute attached to a

 *  dataset.  It is used in the HDF5 Tutorial.

 */



#include "hdf5.h"

#define FILENAME "grpatt.h5"



int main() {



   hid_t       file_id, dataset_id, attribute_id, dataspace_id;  /* identifiers */

   hid_t       group_id;

   hsize_t     dims;

   int         attr_data[2];

   herr_t      status;



   /* Initialize the attribute data. */

   attr_data[0] = 100;

   attr_data[1] = 200;



   file_id = H5Fcreate(FILENAME, H5F_ACC_TRUNC, H5P_DEFAULT, H5P_DEFAULT);

   printf ("H5Fcreate returns: %i\n", file_id);



   group_id = H5Gcreate(file_id, "/MyGroup", H5P_DEFAULT, H5P_DEFAULT, H5P_DEFAULT);

   printf ("H5Gcreate returns: %i\n", group_id);



   /* Create the data space for the attribute. */

   dims = 2;

   dataspace_id = H5Screate_simple(1, &dims, NULL);



   /* Create a dataset attribute. */

   attribute_id = H5Acreate2 (group_id, "Units", H5T_STD_I32BE, dataspace_id, 

                             H5P_DEFAULT, H5P_DEFAULT);



   /* Write the attribute data. */

   status = H5Awrite(attribute_id, H5T_NATIVE_INT, attr_data);



   /* Close the attribute. */

   status = H5Aclose(attribute_id);



   /* Close the dataspace. */

   status = H5Sclose(dataspace_id);



   /* Close to the dataset. */

   status = H5Gclose(group_id);



   /* Close the file. */

   status = H5Fclose(file_id);

}

```

**Comment by andrewcollette** [comment]
Thanks!  Maybe we have to modify how h5py is creating these.

**Comment by gpwright** [comment]
@andrewcollette 
Hi, do you have any idea when you may be able to look at the 2.5 branch issues?  I just took another look at it myself but didn't get very far. 

I think the problem is inside h5py/h5p.pyx I was experimenting with hacking something like this in the h5p.create function:

cdef hid_t newid
newid = H5Pcreate(cls.id)
clsid = H5Pget_class(newid)
H5Pclose_class(clsid)

The last call fails with 'Not a property list class (Not a property list class)' from the hdf5 layer.  This is a simplified version of what happens later on inside propwrap(newid).  So I think maybe the lockcls constants like LINK_ACCESS are no longer being created properly so they fail some test that a property list class is supposed to satisfy?

Let me know if you can help... if you can explain a little bit more about these wrapper classes maybe I can fix it myself.  Happy to try...

Thanks!
G

**Comment by andrewcollette** [comment]
@gpwright, that error suggest something odd is going on inside HDF5 itself.  You might try a minimal example of the above code in C; if it also fails (which I expect it will), the HDF Group might be willing to take a look at it as part of the 1.9 development effort.

@epourmal also made a suggestion in #616 that a later version of HDF5 1.9 might help.

**Comment by gpwright** [comment]
@andrewcollette I don't think its a problem with HDF5... I just ran all the unit tests on 1.9.222 and they all pass.  This includes test_genprop_basic_class in tgenprop.c which calls get_class, close_class etc in the same sequence as above.  Also I had some email discussion with HDF Group back in August about it, and they agreed that it's a h5py problem.

I'm using h5py version 2.5 successfully with the older version 1.9.178 although it has one issue which I can avoid (that has been fixed in 1.9.222).  But I think that for version 1.9.222 some updates are needed to h5py.  Is it possible for you to look at it?  Or could you write some explanation of how the property wrapper classes interact with hdf5 classes and I am happy to look into it more myself.  Is there any developer documentation I could take a look at?

Thanks,
Geoff

**Comment by andrewcollette** [comment]
@gpwright, I see... thanks for following up with HDF on this.  Sorry I missed the C example you posted; that's exactly the right sort of thing to do to investigate.

The propwrap function is supposed to take a C HDF5 property list identifier and create the corresponding Python object.  It does this by using H5Pequal to compare to a bunch of class constants.  You might add some diagnostic code to see what the actual values are and where it might be going wrong.

The lockcls function is even simpler; it just creates a wrapper object with a Python "locked" attribute set, so that h5py doesn't ever try to close it.

For your code example involving H5Pclose_class, I don't think the HDF5-provided class objects can be closed.  So the error message there may simply be misleading.

The best developer documentation is actually the HDF5 C docs, since at this level in Cython you are interacting directly with the HDF5 C API anyway.  

I'm unfortunately not going to have much time in the next few weeks to address this myself, as I am getting ready to start a new job and have a huge pile of work to get through as part of the transition.  But I'm more than happy to answer any specific questions you might have, either here or directly by email at andrew dot collette at gmail dot com, whichever is more convenient for you.

**Comment by gpwright** [comment]
@andrewcollette 
Thanks for the response.  I looked into this a little more and I'm convinced that the underlying issue is that between 1.9.178 and 1.9.222 the type of hid_t changed from int to long int resulting in some of these ids overflowing within h5py.  Is this an easy fix?  I'm just looking through the code now to see if it is defined somewhere in h5py as int..

**Comment by gpwright** [comment]
Yeah so this issue is resolved if we change "ctypedef int hid_t" to "ctypedef long int hid_t" in h5py/api_types_hdf5.pxd.  But I guess we need to link this to the version of hdf5 somehow?  If you let me know the best way to make that change I am happy to submit a merge request. Or can you take it from here?

**Comment by gpwright** [comment]
@andrewcollette here is the diff that fixes it as described in my previous post

```bash
diff --git a/h5py/api_types_hdf5.pxd b/h5py/api_types_hdf5.pxd
index 250d91e..a2174be 100644
--- a/h5py/api_types_hdf5.pxd
+++ b/h5py/api_types_hdf5.pxd
@@ -11,7 +11,7 @@ from api_types_ext cimport *

 cdef extern from "hdf5.h":
   # Basic types
-  ctypedef int hid_t
+  ctypedef long int hid_t
   ctypedef int hbool_t
   ctypedef int herr_t
   ctypedef int htri_t
```

**Comment by andrewcollette** [comment]
@gpwright, awesome work!  I would suggest handling this with a version check that uses int on HDF5 1.8, long int on 1.9 and above.  To see how, check out this section of the guide:

http://docs.h5py.org/en/latest/contributing.html#adding-a-function-only-available-in-certain-versions-of-hdf5

You can ignore the bit about api_functions.txt as you're not adding a new function to h5py.  If you have time to create a pull request that does this I'd be happy to merge it... there's a bit about how to create a PR also on that page.

**Comment by gpwright** [comment]
Makes sense.  On further testing there seems to be some other issues.  import h5py works fine but then some of the functionality is broken like creating attributes and datasets.  My guess would be these are also related to the long int change.  I will try and track them all down and then submit a merge request to the 2.5 branch.

**Comment by andrewcollette** [comment]
Sounds good.  Unless you have a particular need for 2.5 I would suggest master.
