### ISSUE TITLE
misleading docs on --mpi switch

### ISSUE THREAD

**Issue by dyna-ingv** [h5py/h5py#601]
the --mpi switch, as documented here 

http://docs.h5py.org/en/latest/mpi.html#building-against-parallel-hdf5

is actually not working:

```
~$ git clone https://github.com/h5py/h5py.git
Cloning into 'h5py'...
remote: Counting objects: 8199, done.
remote: Total 8199 (delta 0), reused 0 (delta 0), pack-reused 8199
Receiving objects: 100% (8199/8199), 3.96 MiB | 2.70 MiB/s, done.
Resolving deltas: 100% (4941/4941), done.

~$ cd h5py/

~/h5py$ python setup.py --mpi
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --mpi not recognized
```

however, the correct procedure is reported here:

http://docs.h5py.org/en/latest/build.html#building-against-parallel-hdf5

please update the docs to avoid headaches :)

PS
installation with pip should IMHO enable by default --mpi if available or at least privide a mean to enable mpi as requested in issue #542

**Comment by andrewcollette** [comment]
Thanks!  A pull request is welcome on the MPI flag issue.

**Comment by andrewcollette** [comment]
Evidently this was corrected in the docs at some point.
