### ISSUE TITLE
Consider new release to fix pip / python setup.py install?

### ISSUE THREAD

**Issue by matthew-brett** [h5py/h5py#602]
I have just been testing pip installs on Linux, and ran into the problem that the current release of h5py does not have numpy or cython in `setup_requires`:

```
Building wheels for collected packages: h5py, numpy, Cython
  Running setup.py bdist_wheel for h5py
  [snip]
  running build_ext
  Traceback (most recent call last):
    [snip]
    File "setup_build.py", line 140, in run
      from Cython.Build import cythonize
  ImportError: No module named Cython.Build
```

This is fixed in master, because `cython` and `numpy` have been added to `setup_requires` in `setup.py`.   Would y'all consider a release to add this fix to the pip-installable package, so that pip install (and python setup.py install) works with the pypi release?

**Comment by andrewcollette** [comment]
Yes, we have a number of other issues that would benefit from a maintenance release.  Unfortunately I do not have a working Windows build setup at the moment.  But we can at least get the new source release out.

**Comment by andreabedini** [comment]
@andrewcollette have you considered appveyor for windows builds? I did some work on numexpr windows ci pydata/numexpr#178 which can be used as inspiration. I understand linking to HDF5 might be the problem.

**Comment by andrewcollette** [comment]
Oddly enough I was just looking in to appveyor.  One question: I noticed in the numexpr PR that you manually install Python; this link suggests that many versions are already installed:

http://www.appveyor.com/docs/installed-software#python

Is there a particular reason you chose not to use the default Python install?

**Comment by andreabedini** [comment]
It only installs python [if it's not there already](https://github.com/andreabedini/numexpr/blob/9a19a6c5264a7b706de8afdc9a1458e23bb2f91b/appveyor/install.ps1#L47). I started off [Olivier Grisel's work](https://github.com/ogrisel/python-appveyor-demo).

**Comment by andrewcollette** [comment]
Looks good.  I played around with this a bit and it's looking like a lot of work, particularly because we have to build HDF5 somehow.  The appveyor interface is also kind of obtuse.  I'm not personally going to have time to sort it out in the next few months.

To be honest, I'm also starting to think that compiling & distributing Windows binaries is a waste of time.  Chris Gohlke makes both 32 and 64 bit installers available very quickly, and the vast majority of people on Windows are using redistributions like Anaconda and Canopy.  We might get more bang for our buck by working more closely with downstream folks to make sure everything builds and works on Windows.

**Comment by andreabedini** [comment]
> I played around with this a bit and it's looking like a lot of work, particularly because we have to build HDF5 somehow.

:+1: can't agree more.

**Comment by andrewcollette** [comment]
I really wish we could use the HDF Group distribution, but they include szip. :/

**Comment by matthew-brett** [comment]
Maybe Christoph Gohlke would consider compiling and releasing the static libs, without szip encoding enabled?

**Comment by andrewcollette** [comment]
There are scripts in the h5py repository as well which can build HDF5 in the "correct" way, although I haven't run them in a while.

**Comment by aragilar** [comment]
h5py 2.6 was released a while ago, and appveyor support has been added, closing.
