### ISSUE TITLE
Dataset column that holds a list of words

### ISSUE THREAD

**Issue by jhenriquetdg** [h5py/h5py#603]
I am interested on using h5py (HDF5 module for python) for text mining. I have a list of filenames 'text_list' and a list of list of words in each text 'list_words'. I want to create a file called 'mydb.dhf5' containing a dataset 'text' with the columns 'filename' - containing the text filename - and 'words' - containing the list of words on each text.

I tryed to do the following:

          import h5py
          import numpy
          
          db_file = h5py.File('mydb.hdf5','a')
          
          special = lambda x: h5py.special_dtype(vlen=x);
          
          db_text_dt = numpy.dtype([('filename',special(str)),('words',special(special(str)))])
          db_text    = db_file.create_dataset('text',shape=(N,),dtype=db_text_dt)
          
          for t,text in enumerate(db_text):
              text['filename'] = text_list[t]
              text['words']    = text_words[t]
              db_text[t] = text
          
          db_file.flush()
          db_file.close()

I appreciate any discurssion about the topic. Thanks.

**Comment by aldanor** [comment]
Is there a question here?

**Comment by jhenriquetdg** [comment]
I am sorry for such a newbi topic.

The question is: How can I create a dataset where one of the fields is a list of string?

**Comment by aldanor** [comment]
```python
import h5py
import numpy as np

data = np.core.rec.fromarrays([[b'foo', b'bar'], [b'hello', b'world']], names=['filename', 'words'])
f = h5py.File('mydb.h5', 'a')
f['data'] = data
f.flush()
f.close()
```

**Comment by andrewcollette** [comment]
Thanks @aldanor.  @jhenriquetdg, in future please direct such questions to the mailing list (h5py at google groups) which has a bigger audience.
