### ISSUE TITLE
No clear example for reading a file in quick start guide.

### ISSUE THREAD

**Issue by rainwoodman** [h5py/h5py#609]
This is a fun documentation issue:

If I am sending a hdf5 to a collaborator and referring them to the documentation of h5py, and if they blindly followed the very first example, the dataset will be purged.

Maybe better if the quick start documentation starts with an example of consuming the dataset (a more likely use-case) rather than producing a dataset.

( http://docs.h5py.org/en/latest/quick.html )

**Comment by andrewcollette** [comment]
Yes, the Quick-Start Guide is rather elderly, and assumes you're starting from scratch.  I certainly think this could be improved.  PRs are welcome from the community to start off a concrete discussion.
