### ISSUE TITLE
VLEN Strings not working with committed type

### ISSUE THREAD

**Issue by jreadey** [h5py/h5py#613]
If I create a committed type with a VLEN string, it does not get saved correctly to the file.
E.g.
```
import h5py
import numpy as np
f = h5py.File("named_type.h5", "w")
fields = []
fields.append(('field_1', h5py.special_dtype(vlen=str)))
fields.append(('field_2', np.int32))
dt = np.dtype(fields)
f['mytype'] = np.dtype(dt)
f.close()
```

This runs ok, but if I do a h5dump on the file, it looks like the vlen string got saved as an Opaque:

```
HDF5 "named_type.h5" {
GROUP "/" {
   DATATYPE "mytype" H5T_COMPOUND {
      H5T_OPAQUE {
         OPAQUE_TAG "PYTHON:OBJECT";
      } "field_1";
      H5T_STD_I32LE "field_2";
   }
}
}
```

**Comment by andrewcollette** [comment]
Looks like we're going to have to manually convert to the destination type when storing these.

**Comment by andrewcollette** [comment]
@jreadey, let me know if #614 fixes the issue for you.

**Comment by jreadey** [comment]
Yes, this fixes the problem I was seeing.  Thanks for getting this fixed so quickly.

**Comment by andrewcollette** [comment]
I wish every bug could be a one-line fix...
