### ISSUE TITLE
Datasets can't be efficiently sliced out of memory

### ISSUE THREAD

**Issue by roger-** [h5py/h5py#615]
I have a compound dataset `ds` that's too large to fit in memory, and I'm trying to get the first element in column `col`. However `ds['col'][0]` gives a `MemoryError` exception as `ds['col']` seems to automatically try to load the whole file. 

Is there a work around for this?

**Comment by andrewcollette** [comment]
Yes, h5py allows you to mix slicing and field names:

```
ds['col',0]
```

Also in the future feel free to post such questions to the mailing list (h5py at google groups) so that others can easily see them.
