### ISSUE TITLE
ReadTheDocs build failure

### ISSUE THREAD

**Issue by aphearin** [h5py/h5py#617]
I'm developing an astrophysics python package that makes heavy use of h5py to store simulations of cosmological structure formation:
http://halotools.readthedocs.org/en/master/
https://github.com/astropy/halotools

I have recently found that the docs I host on RTD no longer build due to a problem related to h5py:

    In file included from /tmp/pip-build-B3V3YR/h5py/h5py/defs.c:279:0:
    /tmp/pip-build-B3V3YR/h5py/h5py/api_compat.h:27:18: fatal error: hdf5.h: No such file or directory
     #include "hdf5.h"
                      ^
    compilation terminated.

Have you ever encountered this error before in your own RTD builds? Is there a simple workaround? I think there *must* be a solution for this since the h5py docs are themselves hosted on RTD. 

cc @eteq

In case it would be helpful, the full traceback of this RTD build error can be found at https://github.com/astropy/halotools/issues/154

**Comment by andrewcollette** [comment]
It looks like as part of the process you're trying to build the h5py Python package.  This requires HDF5, which evidently isn't available on the RTD server.  For the h5py project docs, we don't attempt to build the h5py package; we just build the docs in the "docs" directory.

**Comment by aphearin** [comment]
Thanks a lot for the quick and clear reply, @andrewcollette. This solves the mystery, though I'll have to ponder what the best solution is. My package makes heavy use of h5py, and so I hesitate to remove h5py from my install_requires list, though this may be the short-term solution while I want to hear back after pinging RTD.

**Comment by stefco** [comment]
See astropy/halotools#154 for an officially sanctioned solution to this issue.
