### ISSUE TITLE
Python crash on reading dimscale attrs

### ISSUE THREAD

**Issue by sunemai** [h5py/h5py#618]
Hi!

I'm new to h5py, so I might be missing something obvious - bare with me;-)
The following code crashes Python completely on my (windows) system, when run either at the cmd-promt as
```
>python script.py
```
or in an IPython environment.
```
import h5py as h5
import numpy as np

print(h5.version.info)
f = h5.File('test.h5','w')

f['dat'] = np.linspace(0,10,10)
f['ds'] = np.linspace(0,10,10)

f['dat'].dims.create_scale(f['ds'],"my dimscale name")

#if following line is commented, python doesn't crash and only 2, not 3, attributes are reported below. 
f['dat'].dims[0].attach_scale(f['ds'])

print(len(f['ds'].attrs))
for i in f['ds'].attrs.items():
	print(i)

f.close()
```
The output generated reads:
```
Summary of the h5py configuration
---------------------------------

h5py    2.5.0
HDF5    1.8.15
Python  3.4.3 |Anaconda 2.3.0 (64-bit)| (default, Mar  6 2015, 12:06:10) [MSC v.1600 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.9.2

3
('CLASS', b'DIMENSION_SCALE')
('NAME', b'my dimscale name')
```

Apparently, it is the access of the third attribute wich causes the crash, since the first two are printed correctly.

Interrestingly, if i run the script with output redirection:
```
>python script.py > output.txt
```
then the last attribute is printed to the file (although the interpreter might still crash before exiting?):
```
Summary of the h5py configuration
---------------------------------

h5py    2.5.0
HDF5    1.8.15
Python  3.4.3 |Anaconda 2.3.0 (64-bit)| (default, Mar  6 2015, 12:06:10) [MSC v.1600 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.9.2

3
('CLASS', b'DIMENSION_SCALE')
('NAME', b'my dimscale name')
('REFERENCE_LIST', array([(<HDF5 object reference>, 0)], 
      dtype=[('dataset', 'O'), ('dimension', '<i4')]))
```

It is not the print statement itself, that causes the problem, however: If I substitute a 'pass' statement instead of 'print', Python will still crash on reading the last attribute.

Any solutions or ideas on what to investigate next? 

Best regards
Sune

**Comment by sunemai** [comment]
Apparently the problem is not general: Running the script on a different computer, and a range of other combinations of h5py, HDF5, numpy and Python versions doesn't crash. 

I.e., all of the combinations listed below work as expected. The last entry is very similar to my own system (only Python version and numpy version differs). If nothing else comes up, I'll try to downgrade Python and numpy to see if the problem goes away then.


```
Summary of the h5py configuration
---------------------------------
 
h5py    2.2.1
HDF5    1.8.11
Python  2.7.6 (default, Nov 10 2013, 19:24:24) [MSC v.1500 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.8.1
 
3
(u'CLASS', 'DIMENSION_SCALE')
(u'NAME', 'my dimscale name')
(u'REFERENCE_LIST', array([(<HDF5 object reference>, 0)],
      dtype=[('dataset', [(({'type': <type 'h5py.h5r.Reference'>}, 'ref'), 'O')]), ('dimension', '<i4')]))
 
 
 
Summary of the h5py configuration
---------------------------------
 
h5py    2.3.1
HDF5    1.8.11
Python  3.3.5 (v3.3.5:62cf4e77f785, Mar  9 2014, 10:35:05) [MSC v.1600 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.8.1
 
3
('CLASS', b'DIMENSION_SCALE')
('NAME', b'my dimscale name')
('REFERENCE_LIST', array([(<HDF5 object reference>, 0)],
      dtype=[('dataset', 'O'), ('dimension', '<i4')]))
 
 
Summary of the h5py configuration
---------------------------------
 
h5py    2.4.0
HDF5    1.8.14
Python  2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.9.2rc1
 
3
(u'CLASS', 'DIMENSION_SCALE')
(u'NAME', 'my dimscale name')
(u'REFERENCE_LIST', array([(<HDF5 object reference>, 0)],
      dtype=[('dataset', 'O'), ('dimension', '<i4')]))
 
Summary of the h5py configuration
---------------------------------
 
h5py    2.5.0
HDF5    1.8.15
Python  2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.9.2
 
3
(u'CLASS', 'DIMENSION_SCALE')
(u'NAME', 'my dimscale name')
(u'REFERENCE_LIST', array([(<HDF5 object reference>, 0)],
      dtype=[('dataset', 'O'), ('dimension', '<i4')]))
 
Summary of the h5py configuration
---------------------------------
 
h5py    2.5.0
HDF5    1.8.15
Python  3.4.2 (v3.4.2:ab2c023a9432, Oct  6 2014, 22:16:31) [MSC v.1600 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.9.1
 
3
('CLASS', b'DIMENSION_SCALE')
('NAME', b'my dimscale name')
('REFERENCE_LIST', array([(<HDF5 object reference>, 0)],
      dtype=[('dataset', 'O'), ('dimension', '<i4')]))
```

**Comment by sunemai** [comment]
In the installation where the script crashes Python, the HDF5 library (1.8.15) was installed system-wide prior to running pip install h5py.

In the working installations, however, the HDF5 library seems to be installed along with h5py - but I need to verify this in more detail. 

Is there an easy way to check from h5py wich HDF5 dll's are actually used?

**Comment by andrewcollette** [comment]
Installing from source on Windows is very difficult, and I don't believe it can be done with pip at the moment.  I suspect something related to this may be the problem.  If you need to use a pip-based distribution, I would suggest relying on the wheels distributed by Chris Gohlke:

http://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by aalemann** [comment]
Hi,
I am having the same problem as sunemai, my configuration reads:

    python version: 2.7.6
    numpy version:  1.8.2
    h5py version:   2.2.1
    hdf5 version:  1.8.11
    OS: Ubuntu 14.03.3 LTS x86_64
    Kernel: 3.13.0-67-generic

**Comment by aalemann** [comment]
it works for me when I upgrade `h5py` via pip ( `pip install h5py --upgrade` ). My working configuration is now

    python version: 2.7.6
    numpy version:  1.10.1
    h5py version:   2.5.0
    hdf5 version:   1.8.11
