### ISSUE TITLE
Unpacking user-defined datatypes

### ISSUE THREAD

**Issue by pnuu** [h5py/h5py#630]
I came across satellite data that has a user-defined data type. When viewed with hdfview, the data are shown as 32-bit float, but h5py reads it as 16-bit float. When inspecting further, h5ls (from hdf5-tools package in debian/ubuntu) shows the following information on the dataset:

```
/All_Data/VIIRS-DNB-SDR_All/Radiance Dataset {768/Inf, 4064/Inf}
    Location:  1:551261
    Links:     1
    Chunks:    {768, 4064} 6242304 bytes
    Storage:   6242304 logical bytes, 3298261 allocated bytes, 189.26% utilization
    Filter-0:  shuffle-2 OPT {2}
    Filter-1:  deflate-1 OPT {5}
    Type:      16-bit little-endian floating-point
               (14 bits of precision beginning at bit 0)
               (2 zero bits at bit 14)
               (significant for 8 bits at bit 0, msb implied)
               (exponent for 5 bits at bit 8, bias is 0x1f)
               (sign bit at 13)
```

The Type field is defining how the dtype is formed, in reference to chapter 6.4.3.1. User-defined Atomic Datatypes in https://www.hdfgroup.org/HDF5/doc/UG/11_Datatypes.html .

This could be also related to issue #445 .

**Comment by andrewcollette** [comment]
@pnuu, can you be a little more explicit as to what the problem is?  Is there a precision mismatch?  Right now the source is a 16-bit float so the destination is also a 16-bit float.

**Comment by mraspaud** [comment]
@andrewcollette Hi, I'm working with @pnuu on this issue.
An example file is available here: https://www.dropbox.com/s/6eoib94gmou0u0a/SVDNBC_npp_d20150810_t0033443_e0035085_b19602_c20150824113128000166_eum_ops.h5?dl=0
If you look at the dataset "All_Data/VIIRS-DNB-SDR_All/Radiance", you can see in hdfview that for example the first value is -1.4988473E-9 (float32). On the other hand, h5py for the same dataset returns 0.0, and another dtype (float16)
We know that they tweak the datatypes for this dataset (the values provided by @pnuu show non standard exponent and mantissa sizes), but we don't know how to read this correctly with h5py.

**Comment by andrewcollette** [comment]
I'm surprised this doesn't already work.  We define the destination type as a normal 16-bit IEEE float and HDF5 is supposed to perform the type conversion internally.  For those interested in investigating I would suggest starting with a minimal C program to see if this problem is h5py-specific.

**Comment by mraspaud** [comment]
@andrewcollette Didn't get any C code to work yet, but I can report that the reading seems to work correctly in pytables...

**Comment by mraspaud** [comment]
Ok, I looked a bit more at this, and I would like to point out that the 16 bits floats provided are actually custom datatype, ie the exponent/mantissa sizes are not 5/10 as in the standard half floats. (see the first post in the thread, exponent is 5, mantissa is 8)

So it looks like non standard 2 byte data types do not get converted properly. As a workaround, I was successful reading the data when promoting to float32 in py_dtype (h5t.pyx).

Any pointer on how do convert those non-standard sub-2-bytes datatypes to float16s ?

**Comment by mraspaud** [comment]
I think I found the problem, the bias was non standard too, leading to actual exponent values not fitting on the standard 5 bits anyway.
