### ISSUE TITLE
Interpret H5T_NATIVE_B8 as numpy.bool

### ISSUE THREAD

**Issue by llchan** [h5py/h5py#641]
I'm migrating from PyTables, which uses `H5T_NATIVE_B8` as the bool representation.  In h5py, this HDF5 type currently raises `TypeError: No NumPy equivalent for TypeBitfieldID exists`.  Since it's currently unusable anyways, would anyone be opposed to having h5py interpret those columns as bool so the files are compatible?  I also have some existing C code that writes PyTables-readable data, and it would make my life a lot easier to write one format instead instead of toggling between two modes.

If we're worried about breaking existing stuff, we could make it an opt-in feature, but that seems unnecessary since the existing behavior is that it cant read the data at all.

**Comment by andrewcollette** [comment]
I don't have any objection to reading or interoperating with such data, as long as we continue to create files using the now-established h5py types.  You could look in h5t.pyx to get started.

**Comment by llchan** [comment]
Cool, I'll put together a PR

**Comment by achilleas-k** [comment]
Is there a workaround for this issue? Is there any way to read `H5T_NATIVE_B8` type data from an existing HDF5 file using h5py?

**Comment by llchan** [comment]
Apologies for letting this slip. I had a workaround a local branch, but hadnt put together a PR because the use case went away (wound up just converting types upstream of h5py). Let me take a look when I get back to my other computer.

**Comment by will133** [comment]
I have recently encountered this issue as well as I believe this is the only showstopper when I try to migrate our codebase to use h5py only instead of using both pytables and h5py.  I'm very interested in testing this out if you have a workaround for this issue.

**Comment by will133** [comment]
I'm looking at the h5py source a bit but I don't know what's a proper way to implement this.  I basically added these in h5t.pyx:

```
diff --git a/h5py/h5t.pxd b/h5py/h5t.pxd
index 13e9c8c..676da9c 100644
--- a/h5py/h5t.pxd
+++ b/h5py/h5t.pxd
@@ -34,9 +34,6 @@ cdef class TypeVlenID(TypeID):
 cdef class TypeTimeID(TypeID):
     pass
 
-cdef class TypeBitfieldID(TypeID):
-    pass
-
 cdef class TypeReferenceID(TypeID):
     pass
 
@@ -51,6 +48,9 @@ cdef class TypeIntegerID(TypeAtomicID):
 cdef class TypeFloatID(TypeAtomicID):
     pass
 
+cdef class TypeBitfieldID(TypeAtomicID):
+    pass
+
 # --- Enums & compound types ---
 
 cdef class TypeCompositeID(TypeID):
diff --git a/h5py/h5t.pyx b/h5py/h5t.pyx
index 22b802d..1688626 100644
--- a/h5py/h5t.pyx
+++ b/h5py/h5t.pyx
@@ -671,13 +671,6 @@ cdef class TypeTimeID(TypeID):
     """
     pass
 
-cdef class TypeBitfieldID(TypeID):
-
-    """
-        HDF5 bitfield type
-    """
-    pass
-
 cdef class TypeReferenceID(TypeID):
 
     """
@@ -956,6 +949,15 @@ cdef class TypeFloatID(TypeAtomicID):
                       str(self.get_size()) )
 
 
+cdef class TypeBitfieldID(TypeAtomicID):
+
+    """
+        HDF5 bitfield type
+    """
+    cdef object py_dtype(self):
+        return dtype('bool')
+
+
 # === Composite types (enums and compound) ====================================
 
 cdef class TypeCompositeID(TypeID):

```

The problem I have is that it seems that I need to have a 1 to 1 mapping from h5 type and numpy type.  This code here in _hl/dataset.py:421:

```
        new_dtype = getattr(self._local, 'astype', None)
        if new_dtype is not None:
            new_dtype = readtime_dtype(new_dtype, names)
        else:
            # This is necessary because in the case of array types, NumPy
            # discards the array information at the top level.
            new_dtype = readtime_dtype(self.id.dtype, names)
        mtype = h5t.py_create(new_dtype)
```

Seems to get the self.id.dtype (in which case would return dtype('bool'), but the py_create() function would return the default enum hdf5 type implementation of boolean arrays.  I'm not sure what's the best way to get this to work.

**Comment by llchan** [comment]
I remember doing something to similar to the above, but also adding a check in the read code to inspect the HDF5 type and do a conversion if necessary. Don't have access to the code at the moment, but I think I should have some time this weekend.

**Comment by takluyver** [comment]
We've gone for turning the standard (8, 16, 32 & 64-bit) bitfield datatypes into the corresponding unsigned integers by default, in PR #1889. You should still be able to convert 8-bit bitfields to booleans explicitly if you need: `arr = dset.astype(numpy.bool_)[:]`.
