### ISSUE TITLE
Module-level function to create a Dimension Scale?

### ISSUE THREAD

**Issue by mgeier** [h5py/h5py#643]
According to [the docs](http://docs.h5py.org/en/latest/high/dims.html), Dimension Scales are created with

```python
f['data'].dims.create_scale(f['x2'], 'x2 name')
```

It seems awkward to me that I need a (potential) target dataset in order to *create* a Dimension Scale.
Is it possible to do this operation with a module-level function (i.e. without needing the `f['data']` dataset instance)?

And while I'm at it, I've got a related question: Is it really necessary to call `create_scale()` or is it enough to call `attach_scale()` without prior call to `create_scale()`?
Of course I wouldn't be able to set a name for the Dimension Scale, but other than that, would it create a valid HDF5 file with a valid Dimension Scale?

**Comment by andrewcollette** [comment]
The Dimension Scales API is a little grungy, unfortunately, and is an area of the code base I'm not that familiar.  I'm also not 100% sure if it has to be done this way; you might check out the relevant low-level APIs and see if you really need the target dataset.

Regardless, I think you'll have a tough time selling folks on an API change for this, since the interface (although clunky) is now well-established.  But it couldn't hurt to investigate!

**Comment by mgeier** [comment]
Thanks for the answer!

I found out how to create a dimension scale with the low-level API:

```python
h5py.h5ds.set_scale(f['x2'].id, b'x2 name')
```

This works but it entails the slight inconvenience of having to use the `.id` attribute of the dataset and having to use `bytes` instead of (Python 3) `str` (latter raises an error).

It would be nice to have a high-level function that works somewhat like that (assuming Python 3 native strings):

```python
h5py.create_scale(f['x2'], 'x2 name')
```

Another (probably even better) possibility would be a method on the dataset object:

```python
f['x2'].set_scale('x2 name')
```

It would also be nice to have an easy way to check if a dataset is a dimension scale, wouldn't it?

I had a look in the source code to see why `create_scale()` is currently a method of the (kinda hidden) `DimensionManager` (in `h5py/_hl/dims.py`). The only reason I could see is the use of the base class method `CommonStateObject._e()` (in `h5py/_hl/base.py`), which does "Encode a name according to the current file settings".
However, this only uses `self` if the optional argument `lcpl` (whatever that means ...) is given, which is *not* the case in `create_scale()`!

The in this case relevant part of the `_e()` method is only this:

```python
if isinstance(name, bytes):
    #coding = h5t.CSET_ASCII
else:
    try:
        name = name.encode('ascii')
        #coding = h5t.CSET_ASCII
    except UnicodeEncodeError:
        name = name.encode('utf8')
        #coding = h5t.CSET_UTF8
return name
```

I think this could be easily incorporated in a potential future `create_scale()` or `set_scale()` function/method.

Any comments?

**Comment by andrewcollette** [comment]
It might be a nicer design, but I think that ship has sailed.  Changing an existing API is a tall order, and there has to be a correspondingly attractive benefit.  But I appreciate that you took the time to investigate.  Cleanup, documentation and additional tests for this area of h5py are more than welcome, though.
