### ISSUE TITLE
writing enum datatype to file

### ISSUE THREAD

**Issue by nschloe** [h5py/h5py#646]
I would like to store the `enum`
```
DATATYPE "elemtypes" H5T_ENUM {
   H5T_STD_U8LE;
   "Edge"             1;
   "Tri"              2;
   "Quad"             3;
};
```
in an HDF5 file. Doing
```python
elem_dt = h5py.special_dtype(
    enum=('i', {
        'Edge': 1,
        'Tri': 2,
        'Quad': 3
    })
    )

tstt['elemtypes'] = elem_dt
```
however doesn't work: `elem_dt` is merely an `int32`.

**Comment by andrewcollette** [comment]
@nschloe, I apologize this has been sitting in the tracker for months.  If you check `elem_dt.metadata` you will see the enum info there.  You (and others reading this) might want to check out the h5py mailing list (h5py at Google Groups) where folks are more likely to respond quickly.
