### ISSUE TITLE
File() mode='a' can result in race condition

### ISSUE THREAD

**Issue by androm3da** [h5py/h5py#647]
The comment in [`make_fid()`](https://github.com/h5py/h5py/blob/c699e741de64fda8ac49081e9ee1be43f8eae822/h5py/_hl/files.py#L99) underscores the nature of this TOCTOU error: 

> If that fails, create a new file only if it won't clobber an existing one (ACC_EXCL)  

After the `ACC_RDWR` attempt fails with `ENOENT`, the `ACC_EXCL` can fail with `EEXIST` if the file is created in the meantime.

**Comment by andrewcollette** [comment]
Good point, but I suspect this problem is rarely encountered in the wild, and since we don't do any locking terrible things can happen anyway if e.g. the file is open for writing elsewhere.  If anyone has a workflow affected by this we'd be happy to discuss options to resolve it.
