### ISSUE TITLE
Testing with tox not returning non-zero exit code on failure

### ISSUE THREAD

**Issue by jakirkham** [h5py/h5py#654]
Here is an example where it is doing this ( https://travis-ci.org/h5py/h5py/jobs/94427845 ). Is there some reason that `tox` is not returning a non-zero exit code on test failure.

**Comment by aragilar** [comment]
@jakirkham I can't find the commit associated with that test (and if I grab the associated pull request, tox runs correctly for me with no test failure...), is there a commit I can test locally?

**Comment by jakirkham** [comment]
@aragilar, yeah, that commit is gone, but the problem of `tox` having a zero exit code was not unique to that test failure. I have seen it with every test failure with `tox` that I recall. So, changing any test to fail should be sufficient to recreate the problem. If that doesn't work for some reason, let me know.

**Comment by aragilar** [comment]
Problem is `python -c "import h5py; h5py.run_tests()"` doesn't exit with anything other than `0`, as `h5py.run_tests()` returns the result, and doesn't call sys.exit. I'll fix the tox.ini.

**Comment by jakirkham** [comment]
Seems like a good fix.
