### ISSUE TITLE
Question: C-Strings with NULL-Term vs. -Pad?

### ISSUE THREAD

**Issue by ax3l** [h5py/h5py#666]
Hi (and sorry for asking a question about a commit 5 years ago),

first of all: thank you for `h5py`, it's awesome! :sparkles: 

Is there a specific reason why `NULL` padding (`H5T_STR_NULLPAD`) is chosen for default c-strings?
  https://github.com/h5py/h5py/blob/2.5.0/h5py/h5t.pyx#L1359 (cdfe9a070a925c4fcead6f99eda4ca0a2bc39e03)

If unset, the *HDF5 default* is `H5T_STR_NULLTERM` (C-style).

Do you just want to avoid uninitialized bytes (behind `'\0'`) or are there known HDF5 issues not writing those bytes when using `H5T_STR_NULLTERM`?

Example code:
```python
import h5py
import numpy as np
# [...]

f.create_group(b"E")
E = f[b"E"]
E.attrs[b"axisLabels"] = np.array([b"x", b"y1", b"z22"])
```

I am just curious what motivated the choice since I have a similar problem right now in a C++ library (https://github.com/ComputationalRadiationPhysics/libSplash/issues/220). There I want to write a simple dataspace with N entries, each constant size, ascii, c-strings but unfortunately, the components in the array will not all have the same length and I have to decide on the longest while padding the rest.

CCing @andrewcollette in the hope that is not causing too much spam in your inbox :)

**Comment by andrewcollette** [comment]
We use that representation because strings in NumPy (dtype "S") are null-padded.  In other words, the value "bar" in a NumPy array with dtype "S5" is stored `bar\x00\x00`.

Importantly, we don't use null-terminated storage because, for example, `b\x00a\x00r` is also a valid NumPy "S5" string.  

If stored as H5T_STR_NULLTERM, a string like this may be corrupted when read by an application, as HDF5 technically should stop reading at the first null.

**Comment by ax3l** [comment]
All right, very interesting `numpy` detail, though. Adventurous, even when such a NULL-mixed string is read fully from the HDF5 file, any C/C++ `<cstring>` operations will still stop at the first NULL again :dancers:. That really seems to be a `numpy` "design decision" (sic) when trying to be `numarray` compatible in the string aspect: https://github.com/numpy/numpy/issues/2414

Thank you a lot for the explanation, I'll take care (and cover)!
