### ISSUE TITLE
Can't import h5py on Linux RedHat Enterprise Linux 5.5

### ISSUE THREAD

**Issue by julienprieur** [h5py/h5py#667]
Hi, 

I 'm facing a problem with importing h5py 2.5 on a HPC linux machine (RedHat Enterprise Linux 5.5).
The setup is quite exotic since I'm running a windows version of python 2.7.10 through wine64 (the calculation workflow involves a third party windows library which is not available under Linux). But it was working with older versions of h5py.

According to the traceback, the problem is when h5py is importing tests\common.py and trying to detect whether the filesystem supports Unicode names (which is not the case on the machine). The code checks for potential UnicodeError exception, but instead OSError is raised.   

One potential workaround would be to check also for OSError. 

See below the traceback:

    import h5py
  File "C:\Python27\lib\site-packages\h5py\__init__.py", line 45, in <module>
    from .tests import run_tests
  File "C:\Python27\lib\site-packages\h5py\tests\__init__.py", line 13, in <module>
    from .common import ut
  File "C:\Python27\lib\site-packages\h5py\tests\common.py", line 39, in <module>
    testfile, fname = tempfile.mkstemp(unichr(0x03b7))
  File "C:\Python27\lib\tempfile.py", line 314, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "C:\Python27\lib\tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory

Regards, 

Julien

**Comment by andrewcollette** [comment]
Unfortunately this setup is quite exotic as you point out, so it's hard for us to justify adding a check to h5py that addresses it.  Your best bet might be to patch the local copy of the source, in the file you mention.
