### ISSUE TITLE
f.visit and f.visititems don't visit h5py.ExternalLink type of items

### ISSUE THREAD

**Issue by horta** [h5py/h5py#671]
Hello,

Running

``` python
import numpy as np
import h5py

with h5py.File('file2', 'w', libversion='latest') as f:
    g = f.create_group('grp')
    g.create_dataset('X', data=np.random.randn(5,5))

with h5py.File('file1', 'w', libversion='latest') as f:
    g = f.create_group('grp')
    g['X'] = h5py.ExternalLink('file1', 'grp/X')
    g.create_dataset('Y', data=np.random.randn(5,5))

with h5py.File('file1', 'r', libversion='latest') as f:
    def func(name):
        print name
    print 'Visited:'
    f.visit(func)
    print 'Manually:'
    print 'f.keys()', f.keys()
    print "f['grp'].keys()", f['grp'].keys()
```

prints

> Visited:
> grp
> grp/Y
> Manually:
> f.keys() [u'grp']
> f['grp'].keys() [u'X', u'Y']

Obs.:

> ~> python -c "import h5py; print h5py.__version__"
> 2.5.0

Danilo

**Comment by lileipku00** [comment]
It seems `visititems` ignores all `Links`, including also `SoftLink` and `HardLink`

**Comment by aaron-parsons** [comment]
I've just found this too. Is it a bug or a feature?

One could imagine you wouldn't necessarily by default want to follow a symlink...

**Comment by PiRK** [comment]
The behavior I have noticed is that a hard link to a group is not ignored, but it is not visited: the callback function processes the hard link, but not its members if they have already been reached. A hard link to a dataset is ignored if the dataset has already been visited. This makes sense, and I would apply the same behavior to soft links.

**Comment by PiRK** [comment]
Actually hard links are only processed if their target has not yet been reached through another hard link. My bad.

**Comment by aragilar** [comment]
A PR which adds a flag to enable looking up external links would be welcomed.

**Comment by takluyver** [comment]
Dropping the milestone because no-one's working on this. This doesn't mean no-one should, just that it's not practical to plan to include it in a release.

**Comment by takluyver** [comment]
It appears that H5Ovisit doesn't follow soft links or external links by design:
https://forum.hdfgroup.org/t/h5ovisit-does-not-follow-soft-links/5058

I'm looking at how we could work around this in h5py - see also #1383.

**Comment by sethrj** [comment]
@takluyver Makes sense to me: "objects" in the HDF5 data model are actual pieces of data, so they'd be visited by an `H5O` function; whereas soft links and external links are just *links*, visited by `H5L`. With an object-visiting function, no matter how many soft links there are between objects and groups, I would expect the visitor to return each object only once.

**Comment by takluyver** [comment]
I'm not totally convinced it makes sense, but that doesn't really matter. It's what HDF5 does, and it doesn't appear it's about to change. It's surprising to at least some people (hence this issue), and it seems reasonable to have a way to iterate over everything that an HDF group refers to, whether by hard links, soft links or external links.

**Comment by loichuder** [comment]
Hello h5py maintainers,

Just encountered this issue. I can work around it but I was wondering if `h5py` has still an interest in having a `visit` (and `visititems`) that can iterate through links.

**Comment by takluyver** [comment]
We actually do have a visit that can do this, I just wasn't aware of it back in 2019: `group.id.links.visit()`. As part of the low-level API, it will give you names as `bytes` rather than `str`.

I think exposing this in the high-level interface would make sense, if someone wants to do a PR. Maybe `.visit_links()` and `.visititems_links()`?

**Comment by loichuder** [comment]
Oh wow, that's great, thanks for the pointer !

I can work on a PR to add the high-level methods if you want. It should be quite similar to the existing [visit methods](https://github.com/h5py/h5py/blob/4c01efa9714db40ffe27a322c4f1ba4635816e44/h5py/_hl/group.py#L613), right ? Both in terms of implementation and documentation.

**Comment by takluyver** [comment]
Thanks! Yes, I think the API should be very similar to the existing visit methods, except that in `visititems_links()` the second argument would be the link instead of the target object.

(It did occur to me this could even be an option for the existing methods: `grp.visit(func, links=True)`. But I think the difference in what they do is significant enough that a separate method is clearer).
