### ISSUE TITLE
h5py fails to import hdf5 libraries

### ISSUE THREAD

**Issue by martinosorb** [h5py/h5py#672]
On Ubuntu 15, I have:
* the most recent version of libhdf5-dev installed
* the most recent version of libhdf5-serial-dev installed
* h5py installed through `pip3` and already up to date

Although it used to work properly, h5py now fails immediately:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/h5py/__init__.py", line 13, in <module>
    from . import _errors
ImportError: libhdf5_serial.so.8: cannot open shared object file: No such file or directory
```

I do have /usr/lib/x86_64-linux-gnu/libhdf5_serial.so.**10**, so it seems h5py cannot deal with a newer version of hdf5?

**Comment by parkin** [comment]
I had the same problem. Using pip, uninstalling then reinstalling h5py fixed the issue.

**Comment by martinosorb** [comment]
@parkin Yes, same for me, but I had to physically remove the installed h5py folder, perhaps because I don't know how to force the reinstall.

**Comment by andrewcollette** [comment]
I think this is a generic limitation of building from source with HDF5; newer versions are not drop-in replacements for older versions.  So when HDF5 changes you will need to rebuild h5py.

**Comment by martinosorb** [comment]
Yes, and it's not intuitive how to do it, as pip tends to reinstall in the exact same way.
What worked for me was 

`pip uninstall h5py`
`pip install --no-cache-dir h5py`

**Comment by andrewcollette** [comment]
@martinosorb, thanks... I am surprised that pip does such aggressive caching.

**Comment by zghyfbmw** [comment]
I met the same problem on Stampede. 
----------------------------------------------------------------------------
File "/opt/apps/intel15/python/2.7.12/lib/python2.7/site-packages/h5py/__init__.py", line 24, in <module>
    from . import _errors
ImportError: libhdf5.so.10: cannot open shared object file: No such file or directory


I want to reinstall h5py but my uninstallation has been denied.
----------------------------------------------------------------------------
Exception:
Traceback (most recent call last):
  File "/opt/apps/intel15/python/2.7.12/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/apps/intel15/python/2.7.12/lib/python2.7/site-packages/pip/commands/uninstall.py", line 76, in run
    requirement_set.uninstall(auto_confirm=options.yes)
  File "/opt/apps/intel15/python/2.7.12/lib/python2.7/site-packages/pip/req/req_set.py", line 346, in uninstall
    req.uninstall(auto_confirm=auto_confirm)
  File "/opt/apps/intel15/python/2.7.12/lib/python2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/opt/apps/intel15/python/2.7.12/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/opt/apps/intel15/python/2.7.12/lib/python2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/opt/apps/intel15/python/2.7.12/lib/python2.7/shutil.py", line 300, in move
    rmtree(src)
  File "/opt/apps/intel15/python/2.7.12/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/opt/apps/intel15/python/2.7.12/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/opt/apps/intel15/python/2.7.12/lib/python2.7/site-packages/h5py-2.6.0-py2.7.egg-info/PKG-INFO'
---------------------------------------------------------------------
I don't know how to fix this.

**Comment by asanakoy** [comment]
@zghyfbmw try to run with option `--user` or with sudo.

**Comment by clockzhong** [comment]
I face the same problem, and I found after I run: "sudo pip install h5py", the h5py will be installed in the python3.0 directory instead of python2.7, what's the problem of the python environment for h5py installation? and I've never succeeded in the "import h5py" so far.

**Comment by clockzhong** [comment]
Ok, I found my problem root cause and fixed it finally. 
My problem root cause is that: 
After I execut:
sudo pip install h5py
My ubuntu16 will install the h5py into my Python3.0 environment instead of python2.7, I don't know why.
Because my default keras environment is python 2.7, so it can't import h5py. 
After locating this root cause, I used the following command to install the h5py into my python2.7 environment:
sudo -H python2.7 -m pip install h5py
And then reinstall the keras with 
sudo -H python2.7 -m pip install keras
Then the h5py could work with my keras on the model.save_weights().

**Comment by kartik41976** [comment]
@martinosorb I am also facing the same issue, It was working before but now I don't know what happened but it's giving me the same error
ImportError: libhdf5.so.8: cannot open shared object file: No such file or directory
It doesn't work in Python3 but it works in Python2.7
Also in linux, I am unable to use pip, because I think I am using it on a Cluster server

**Comment by martinosorb** [comment]
pip --user should work even if you don't have root access, if that is the problem.

**Comment by kartik41976** [comment]
@martinosorb I am sorry, but I am new to linux(Centos). Could you tell me the steps to proceed to remove error

Thanks

**Comment by molly87qd** [comment]
I don't have permission to uninstall the package that is installed by the administrator.  Is there any other solutions?

**Comment by tacaswell** [comment]
@molly87qd You should take this issue to your local administrator.

Failing that, unless you _must_ use system python, I strongly suggest using a virtual enviroment of some sort (either `python3 -m venv` or conda) in user-space.

**Comment by whillas** [comment]
I'm getting this error installing into a python3.8 environment :(

**Comment by acelere** [comment]
Python 3.8 is too new... the wheels are not ready yet.

See [Linux/ macOS wheels for python 3.8 #1410](https://github.com/h5py/h5py/issues/1410)

**Comment by kishorpawar** [comment]
For me, this has something to do with the `NumPy` version.

the combination did not work for me is 
`numpy==1.18.1` and `h5py==2.10.0`

the combination worked is
`numpy==1.16.4` and `h5py==2.10.0`
