### ISSUE TITLE
Implement `rename` method in the `AttributeManager` class

### ISSUE THREAD

**Issue by carlodri** [h5py/h5py#677]
It would be nice to have a `rename` method in the `AttributeManager` class that allows to change the **name** of a attribute. In analogy to the `RENAME` command in `h5edit` ([here](https://www.hdfgroup.org/ftp/HDF5/projects/jpss/h5edit/unpacked/doc/h5edit.htm)).

Use case example: we have numerous datasets where there were typos in the attribute names, until the typo was fixed in the data acquisition software. In the data analysis software, I would like to implement an _attribute healing_ system that corrects the typos. In this way, once I open a file, the attribute is corrected once and forever.

At the moment, I can obviously delete the attribute and recreate it, but this messes up the order of the attributes (the created one is appended at the end).

**Comment by andrewcollette** [comment]
This is already available through the low-level API.  I would suggest using the low-level function rather than to add another high-level function and depart from the dictionary metaphor, for this very specific use case.

http://api.h5py.org/h5a.html#h5py.h5a.rename

e.g.

```
h5py.h5a.rename(myfile.id, b"name", b"newname")
```

**Comment by carlodri** [comment]
thanks @andrewcollette. I did find the low-level API way of doing this, but I thought it could have been useful to have it handy in the methods. Anyway,I understand the python dict-compliance idea, I will use it as you say. Thanks!
