### ISSUE TITLE
Cannot open .h5 file

### ISSUE THREAD

**Issue by fabiansinz** [h5py/h5py#678]
I already crawled the web for this, but couldn't find anything. Here is the basic behaviour:

I have a `.h5` file that has been written by some other program. If I want to open with with `h5py` like

```python
h5file =  "{prefix}{0}/{1}{2}0.h5".format(p,f,n, prefix=prefix)
with h5py.File(h5file,'r+') as fid:
     print(fid)
```

I get the following error
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-23-0feecd6949bd> in <module>()
      8 h5file =  "{prefix}{0}/{1}{2}0.h5".format(p,f,n, prefix=prefix)
      9 print(h5file)
---> 10 with h5py.File(h5file,'r+') as fid:
     11      print(fid)
     12 #     dat = rf.readHD5(key);

/usr/local/lib/python3.4/dist-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
    258 
    259                 fapl = make_fapl(driver, libver, **kwds)
--> 260                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    261 
    262                 if swmr_support:

/usr/local/lib/python3.4/dist-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
     89         fid = h5f.open(name, flags, fapl=fapl)
     90     elif mode == 'r+':
---> 91         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
     92     elif mode in ['w-', 'x']:
     93         fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)

_objects.pyx in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2508)()

_objects.pyx in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2461)()

h5f.pyx in h5py.h5f.open (/tmp/pip_build_root/h5py/h5py/h5f.c:1837)()

OSError: Unable to open file (Family driver should be used)
```
Needless to say that using `driver='family'` does not solve the problem. 

The really weird thing is, I can open it with `hdfview` under Linux. When I save that file under a new filename from `hdfview` I can open it without any problem. Any idea what might cause this?

I am under ubuntu. I installed `h5py` version 2.5.0 using pip. I am using python3.

**Comment by fabiansinz** [comment]
Ok, here's the solution for the problem. It is a multi-part file (therefore the request for the 'family' driver). Therefore, the filename needs a `%d` at the part where the files differ. However, then I till get an error about the member size being the wrong value. After looking at the cpython code and guessing a bit (and getting help from @eywalker who had the same problem before), we figured out that one needs to set `memb_size=0`. So the correct call is 

```python
h5file =  "{prefix}{0}/{1}{2}0.h5".format(p,f,n, prefix=prefix)
with h5py.File(h5file,'r+', driver='family', memb_size=0) as fid:
     print(fid)
```

It would be great if that could be documented somewhere.

**Comment by ikrambennasrbennasr** [comment]
@fabiansinz Hello, please  i run this code and i get almost the same error : 
# ------------
exp_number = 13
output_architecture = './tmpdata/convnet_architecture_exp' + str(exp_number) + '.json'
best_weights_during_run = './tmpdata/weights_exp' + str(exp_number) + '.h5'
final_weights = './tmpdata/weights_exp' + str(exp_number) + '_final.h5'
loss_history = './tmpdata/history_exp' + str(exp_number) + '.pickle'
# ------------

I get the following error : 

IOError                                   Traceback (most recent call last)
<ipython-input-18-4afc846a439d> in <module>()
     58 # fit the network using the generator of mini-batches.
     59 model.fit_generator(pipeline.train_generator(fold = 'train'),                     samples_per_epoch = 30000,                     nb_epoch = 20, verbose = 1, callbacks=[history, checkpointer],
---> 60                    validation_data = (x_valid,y_valid), max_q_size = 50)
     61 losses_dic = {'train_loss': history.train_losses, 'valid_loss':history.valid_losses}
     62 # save history

/home/ubuntu/anaconda3/envs/nilmtk-env/lib/python2.7/site-packages/keras/legacy/interfaces.pyc in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name +
     90                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

/home/ubuntu/anaconda3/envs/nilmtk-env/lib/python2.7/site-packages/keras/engine/training.pyc in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   2260                         break
   2261 
-> 2262                 callbacks.on_epoch_end(epoch, epoch_logs)
   2263                 epoch += 1
   2264                 if callback_model.stop_training:

/home/ubuntu/anaconda3/envs/nilmtk-env/lib/python2.7/site-packages/keras/callbacks.pyc in on_epoch_end(self, epoch, logs)
     75         logs = logs or {}
     76         for callback in self.callbacks:
---> 77             callback.on_epoch_end(epoch, logs)
     78 
     79     def on_batch_begin(self, batch, logs=None):

/home/ubuntu/anaconda3/envs/nilmtk-env/lib/python2.7/site-packages/keras/callbacks.pyc in on_epoch_end(self, epoch, logs)
    445                             self.model.save_weights(filepath, overwrite=True)
    446                         else:
--> 447                             self.model.save(filepath, overwrite=True)
    448                     else:
    449                         if self.verbose > 0:

/home/ubuntu/anaconda3/envs/nilmtk-env/lib/python2.7/site-packages/keras/engine/topology.pyc in save(self, filepath, overwrite, include_optimizer)
   2578         """
   2579         from ..models import save_model
-> 2580         save_model(self, filepath, overwrite, include_optimizer)
   2581 
   2582     def save_weights(self, filepath, overwrite=True):

/home/ubuntu/anaconda3/envs/nilmtk-env/lib/python2.7/site-packages/keras/models.pyc in save_model(model, filepath, overwrite, include_optimizer)
    104             return
    105 
--> 106     with h5py.File(filepath, mode='w') as f:
    107         f.attrs['keras_version'] = str(keras_version).encode('utf8')
    108         f.attrs['backend'] = K.backend().encode('utf8')

/home/ubuntu/anaconda3/envs/nilmtk-env/lib/python2.7/site-packages/h5py/_hl/files.pyc in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
    267             with phil:
    268                 fapl = make_fapl(driver, libver, **kwds)
--> 269                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    270 
    271                 if swmr_support:

/home/ubuntu/anaconda3/envs/nilmtk-env/lib/python2.7/site-packages/h5py/_hl/files.pyc in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    103         fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
    104     elif mode == 'w':
--> 105         fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
    106     elif mode == 'a':
    107         # Open in append mode (read/write).

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.create()

IOError: Unable to create file (unable to open file: name = './tmpdata/weights_exp13.h5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)

*****
Can you help me please :)
