### ISSUE TITLE
TypeError raised when setting attribute with >64-bit number

### ISSUE THREAD

**Issue by saulpw** [h5py/h5py#682]
## Summary of the h5py configuration

h5py    2.5.0
HDF5    1.8.11
Python  2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2]
sys.platform    linux2
sys.maxsize     9223372036854775807
numpy   1.10.4

---

Example that exhibits the exception:

```
hf = h5py.File(sys.argv[1], 'w')
hf.attrs['test'] = long(98765432109876543210)
```

**Comment by saulpw** [comment]
Expected result: h5py creates an integer type large enough to hold the value.

**Comment by aragilar** [comment]
Neither [numpy](http://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html) nor [HDF5](https://www.hdfgroup.org/HDF5/doc/RM/PredefDTypes.html) know how to deal with >64 bit integers.
Numpy works around this by wrapping the long as an object array, which h5py has no idea what to do with.

What you could do is follow http://docs.h5py.org/en/latest/strings.html#how-to-store-raw-binary-data, converting the long to bytes and then wrapping it in numpy.null. To convert back, convert the object back to bytes, and then call int/long on it.

**Comment by saulpw** [comment]
Ah, I mistakenly thought HDF5 could deal with integers of any length.  You make a good suggestion but we decided to go with stringified integers as strings are more usable with other tools.  Thanks for your quick response.
