### ISSUE TITLE
File open from file-object

### ISSUE THREAD

**Issue by Kriechi** [h5py/h5py#687]
Right now h5py can only open files by passing a file path to it.
I'm working with compressed files - so my HDF5 file is in a `xz` container with `lzma2` compression.

Ideally I would like to do something like this:

```python
import lzma
import h5py

input_file = lzma.open('foobar.hdf5.xz', 'r')
f = h5py.File(input_file)
```

**Comment by aragilar** [comment]
It appears to be a limitation of the HDF5 library: if you look at how h5py opens files, you'll see that it does very little with arguments you pass it; instead, it passes the arguments to the HDF5 library, which performs the low level work (getting a file handle etc.). If support for accepting existing file handles was added to the HDF5 library, then there shouldn't be much difficulty adding it to h5py.

**Comment by andrewcollette** [comment]
@aragilar is right on this... unfortunately we get to pass the file name to HDF5 and not much else.  There is some provision for working with buffers and in-memory files, but nothing I'm aware of that will take a Python file-like object.  Would be cool, though!

If you're interested in using compression, the "standard" HDF5 way is to use compressed datasets.  These are where 99% of the bytes in the file live, so it's surprisingly effective.

http://docs.h5py.org/en/latest/high/dataset.html#filter-pipeline
