### ISSUE TITLE
patches for msys2 installation

### ISSUE THREAD

**Issue by mikofski** [h5py/h5py#688]
I was able to port h5py using [msys2](https://github.com/msys2) mingw-w64 toolset and the libhdf5 pacakge in their repository with the following two patches. I also had to install dependencies like numpy, six and Cython manually. Finally, only the egg had the correct manifest, the wheel was missing `h5py/`.

1. check if CC is mingw then don't import stdint.h

        --- ~\h5py-2.5.0\setup_build.py
        +++ ~\h5py-2.5.0-msys2\setup_build.py
        @@ -10,6 +10,7 @@
         except ImportError:
             from distutils.extension import Extension
         from distutils.command.build_ext import build_ext
        +from distutils import ccompiler as cc
         import sys
         import os
         import os.path as op
        @@ -17,6 +18,7 @@
         from functools import reduce
         import api_gen
         
        +DFLT_CC = cc.get_default_compiler()
         
         def localpath(*args):
             return op.abspath(reduce(op.join, (op.dirname(__file__),)+args))
        @@ -36,7 +38,7 @@
                       localpath("lzf/lzf/lzf_d.c")]}
         
         
        -if sys.platform.startswith('win'):
        +if sys.platform.startswith('win') and not DFLT_CC.startswith('mingw'):
             COMPILER_SETTINGS = {
                 'libraries'     : ['h5py_hdf5', 'h5py_hdf5_hl'],
                 'include_dirs'  : [localpath('lzf'), localpath('windows')],

2. pass `--define=MINGW` to with `python setup.py build_ext` to turn off `WIN32` and `_WIN64`

        --- ~\h5py-2.5.0\lzf\lzf\lzf_c.c
        +++ ~\h5py-2.5.0-msys2\lzf\lzf\lzf_c.c
        @@ -120,6 +120,10 @@
            * and fails to support both assumptions is windows 64 bit, we make a
            * special workaround for it.
            */
        +#ifdef MINGW
        +#  undef WIN32
        +#  undef _WIN64
        +#endif
         #if ( defined (WIN32) && defined (_M_X64) ) || defined (_WIN64)
           unsigned _int64 off; /* workaround for missing POSIX compliance */
         #else

3. install dependencies, build and install

        pacman -S mingw-w64-x86_64-python2-nose \
            mingw-w64-x86_64-cython2 \
            mingw-w64-x86_64-python2-six \
            mingw-w64-x86_64-hdf5 \
            mingw-w64-x86_64-python2-numpy
        python setup.py build_ext --define MINGW
        python setup.py install
    
4. Appears to pass all tests

        $ nosetests
        C:/msys64/mingw64/lib/python2.7/site-packages/numpy/core/__init__.py:14:
          Warning: Numpy built with MINGW-W64 on Windows 64 bits is experimental,
          and only available for testing. You are advised not to use it for production.

        CRASHES ARE TO BE EXPECTED - PLEASE REPORT THEM TO NUMPY DEVELOPERS
          from . import multiarray
        ...................................................x........................
        .......................................x....................................
        s........ss.ss..............................................................
        ...................................sss......................................
        ........................x....x..x................x...x......................
        ......ssssssssss........
        ----------------------------------------------------------------------
        Ran 404 tests in 1.076s

        OK (skipped=18, expected failures=7)
        .....
        C:/msys64/mingw64/lib/python2.7/unittest/case.py:340:
          RuntimeWarning: TestResult has no addExpectedFailure method, reporting as passes
          RuntimeWarning)
        ..........................................................SSSSSSSSSS........
        ............................................................................
        ..........................................................................S.
        .......SS.SS................................................................
        .................................SSS........................................
        ....................
        ----------------------------------------------------------------------
        Ran 405 tests in 2.621s

        OK (SKIP=18)

@alexpux in case you're interested

[h5py.setup_build.py.patch.txt](https://github.com/h5py/h5py/files/168456/h5py.setup_build.py.patch.txt)
[h5py.lzf.lzf.lzf_c.c.patch.txt](https://github.com/h5py/h5py/files/168457/h5py.lzf.lzf.lzf_c.c.patch.txt)

**Comment by Alexpux** [comment]
Well instead passing ````--define=MINGW```` maybe just add ````!defined(__MINGW32__)```` to conditions?

**Comment by andrewcollette** [comment]
This is interesting work... thanks for sharing.  Right now h5py is built on Windows mainly by the Anaconda and Canopy distributions, with additional wheels by Christoph Gohlke.  They, as well as the Python.org distribution of Python, use the Visual Studio toolchain.  As you no doubt know (and can see from the NumPy output above), mingw is a lesser-used and less-tested toolchain in this area.

Because of this, it will be difficult for us to properly maintain and test mingw/mingw64 support as part of the master branch of h5py development.  If you're interested in continuing, I would suggest a "friendly fork" of h5py, which would likely be easy to keep up to date with our master branch, that incorporates these patches.  That would give you the best chance to interact with (and get feedback from) people using mingw to build h5py.
