### ISSUE TITLE
HDF5 Direct Chunk Writing not supported

### ISSUE THREAD

**Issue by simongregorebner** [h5py/h5py#690]
Currently HDF5 direct chunk writing (https://www.hdfgroup.org/HDF5/doc/Advanced/DirectChunkWrite/) is not supported by h5py.

Direct chunk writing is required to be able to write pre-compressed data directly into the HDF5 file without going through the filter-pipeline of HDF5. As modern high throughput detectors like the Dectris Eiger (https://www.dectris.com/EIGER_X_Detectors.html), and/or several other detectors at Synchrotron and FEL facilities, provide data in such a speed and volume that the HDF5 library is not able to keep up while going through its filter pipeline, this functionality is necessary.

**Comment by aragilar** [comment]
Fixed by #691.
