### ISSUE TITLE
import h5py: undefined symbol: H5Pget_dxpl_mpio

### ISSUE THREAD

**Issue by chengjunwen** [h5py/h5py#694]
i install h5py by:
>export CC=mpicc
>python setup.py configure --hdf5=/usr/local/hdf5/
>python setup.py configure --mpi
>python setup.py build
>python setup.py install

when i import h5py:
error:
>Traceback (most recent call last):
> File "<stdin>", line 1, in <module>
> File "/usr/local/lib/python2.7/dist-packages/h5py-2.6.0-py2.7-linux-x86_64.egg/h5py/__init__.py", line 34, in <module>
>   from ._conv import register_converters as _register_converters
> File "h5py/h5r.pxd", line 21, in init h5py._conv (/home/cjw/softwarePackage/h5py/h5py/_conv.c:7719)
> File "h5py/_objects.pxd", line 12, in init h5py.h5r (/home/cjw/softwarePackage/h5py/h5py/h5r.c:3304)
> File "h5py/_objects.pyx", line 1, in init h5py._objects (/home/cjw/softwarePackage/h5py/h5py/_objects.c:7679)
>ImportError: /usr/local/lib/python2.7/dist-packages/h5py-2.6.0-py2.7-linux-x86_64.egg/h5py/defs.so: undefined symbol: H5Pget_dxpl_mpio

**Comment by andrewcollette** [comment]
It's likely you have to install the parallel version of HDF5 before installing h5py (libhdf5-parallel or similar).  You can also ask on the mailing list (h5py at google groups) if you continue to have problems.

**Comment by wbinventor** [comment]
I am observing the same problem when trying to install the v2.6 release from source. I already installed parallel HDF5 (v1.8.16) with `--enable-parallel` and `--enable-shared` per the installation instructions along with MPICH v3.2 (both from source). Was a solution found which led to this issue being invalidated?

**Comment by andrewcollette** [comment]
These issues are typically associated with build-time problems like using the wrong path to HDF5, etc.  Because of the wide variety of possible build environments, you are most likely to get useful feedback on the mailing list.  I also noticed a similar issue from 2015:

https://github.com/h5py/h5py/issues/569

**Comment by wbinventor** [comment]
Thank you @andrewcollette, I'll post this to the list. Hopefully someday soon the parallel HDF5 compatible version of h5py will be available through Anaconda.

**Comment by wjlei1990** [comment]
I am currently experiencing the same issue, my h5py version is `2.6` and mpi4py version is `2.0.0`.

Previously, I could build the `h5py 2.5` with `mpi4py 1.3.1`.  Couldn't really figure out why it doesn't work since I am using the same hdf5 library.

**Comment by wbinventor** [comment]
I simply gave up using h5py 2.6, since there are apparently some other bugs in 2.6 which make relegate it unusable for my work (mit-crpg/openmc#624 as one example). It's unclear to me how to pinpoint the source of these bugs, otherwise I would have reported them here. These issues do not appear with 2.5, which I am using successfully (albeit without mpi4py).

**Comment by wjlei1990** [comment]
Please briefly check this out:

https://groups.google.com/forum/#!topic/h5py/r78_OuCKqRk

Using this command to check the `defs.so`
```
$ldd /usr/local/lib/python2.7/dist-packages/h5py-2.5.0-py2.7-linux-x86_64.egg/h5py/defs.so
```
might helpful... At least I make fix the this error on one machine :)

**Comment by andrewcollette** [comment]
@wbinventor, any idea what (generally speaking) might be going wrong with 2.6?  Slicing code, perhaps?  Let me know if I can provide any help tracking this down.  Right now the test suite passes for 2.6.0 but not all edge cases are covered to begin with.

**Comment by paulromano** [comment]
@andrewcollette, I believe the bug that @wbinventor is referring to is related to #698. Are compound datatypes not covered in the test suite?

**Comment by wbinventor** [comment]
Thanks for chiming in @paulromano. Do note @andrewcollette that this compound datatype issue is entirely separate from the mpi4py compile issue. I just happened to run into it when using h5py 2.6 without mpi4py, which dissuaded me from digging further into building with MPI.

**Comment by ax3l** [comment]
For the conda users around here that also run in the `defs.so: undefined symbol: H5Pget_dxpl_mpio` problem after the `--mpi` install of h5py from source went fine.

First deinstall the non-parallel hdf5 via
```bash
conda uninstall hdf5
```

Then build again
```bash
export CC=mpicc
python setup.py configure --mpi
python setup.py install
```

and you are good to go.

The problem was, as @wjlei1990 pointed out, that the configure-time library might looked good but at runtime the wrong (conda serial) hdf5 was picked.

**Comment by valiantljk** [comment]
right, the wrong hdf5 version was picked up in the compiling time. 
ldd /usr/common/das/h5py-parallel/2.6.0-conda/lib/python2.7/site-packages/h5py-2.6.0-py2.7-linux-x86_64.egg/h5py/defs.so
	linux-vdso.so.1 =>  (0x00002aaaaaaab000)
	libhdf5.so.10 => /usr/common/usg/python/2.7-anaconda/lib/libhdf5.so.10 (0x00002aaaaace4000)
	libhdf5_hl.so.10 => /usr/common/usg/python/2.7-anaconda/lib/libhdf5_hl.so.10 (0x00002aaaab19c000)

**Comment by valiantljk** [comment]
I figured a way to build h5py with anaconda with parallel hdf5:
```
Replace line 48 in setup_build.py in h5py-2.6.0 package:
      'libraries'      : ['hdf5', 'hdf5_hl'],
   into
      'libraries'      : ['hdf5_parallel_gnu_51', 'hdf5_hl_parallel_gnu_51'],
```

**Comment by ax3l** [comment]
interesting. is there some python module in anaconda equivalent to pkgconfig to get the actual binary names you spotted?

**Comment by Rajanykv** [comment]
uninstall h5py
uninstall mpi4py
install mpi4py
install h5py
