### ISSUE TITLE
import h5py(from . import _conv)  segmentation fault

### ISSUE THREAD

**Issue by sherylwang** [h5py/h5py#695]
I'm using h5py 2.5.0 through Anaconda. When I import h5py in terminal with ipython or python, it's OK.
But when I import h5py  after import many other packages, error *\* 'segmentation fault(core dump)'*\* arises.
when I step into the 'import' procedure, it  show that the error happens  with 'from . import _conv'.

Is there any good solutions?

**Comment by tacaswell** [comment]
Do you have `HDF_PLUGIN_PATH` exported?

See https://github.com/ContinuumIO/anaconda-issues/issues/687

**Comment by sherylwang** [comment]
Thanks for tacaswell's kind remind, I've exported HDF_PLUGIN_PATH now, but the problem remains unsolved. I guess my setting is not right, which is like: $HOME/anaconda/lib/python2.7/site-packages/h5py

**Comment by Funkensieper** [comment]
I have a similar problem with hdf5-1.8.17 and h5py-2.6.0. in my case the segmentation fault occurs if h5py is imported after [pygrib](https://github.com/jswhit/pygrib). If you import h5py first, everything works fine.

**Comment by aragilar** [comment]
@sherylwang @Funkensieper Is this still a problem with the latest h5py release?

**Comment by Funkensieper** [comment]
With hdf5-1.8.18, h5py-2.7.0 and pygrib-2.0.2 there is no such problem any more.
