### ISSUE TITLE
Offsets in aligned compound datatypes

### ISSUE THREAD

**Issue by jbernhard** [h5py/h5py#698]
It seems h5py does not correctly compute offsets in _aligned_ compound datatypes; namely, it neglects padding bytes. Failing test:
```python
data = np.ones(10, dtype=np.dtype('i4,i8', align=True))

with h5py.File('aligned.h5', 'w') as f:
    f['data'] = data

with h5py.File('aligned.h5', 'r') as f:
    h5data = np.array(f['data'])

assert np.all(h5data == data)
```

I believe I know how to fix this. Function `_c_compound()` in the `H5T` wrappers determines offsets by accumulating sub-datatype sizes. Instead, it could e.g. read offsets from the `dtype.fields` dict. Let me know if you want a PR.

**Comment by andrewcollette** [comment]
A PR would be quite valuable...thanks!
