### ISSUE TITLE
Trouble building on Windows (missing h5py_hdf5.lib)

### ISSUE THREAD

**Issue by jakirkham** [h5py/h5py#699]
I am trying to get h5py to build with Windows support in conda-forge. I have HDF5 built for Windows. However, I am getting an error when trying to build h5py so that it links to HDF5. Here is the error I am getting. More information in the build [log](https://ci.appveyor.com/project/conda-forge/h5py-feedstock/build/1.0.4/job/kxjbflpm2u8wxcvq#L301).

```
LINK : fatal error LNK1181: cannot open input file 'h5py_hdf5.lib'
```

**Comment by cgohlke** [comment]
Remove the `h5py_` prefix and define `H5_BUILT_AS_DYNAMIC_LIB`:

```patch
diff --git a/setup_build.py b/setup_build.py
index 6e3468b..28ef380 100644
--- a/setup_build.py
+++ b/setup_build.py
@@ -38,10 +38,11 @@ EXTRA_SRC = {'h5z': [ localpath("lzf/lzf_filter.c"),

 if sys.platform.startswith('win'):
     COMPILER_SETTINGS = {
-        'libraries'     : ['h5py_hdf5', 'h5py_hdf5_hl'],
+        'libraries'     : ['hdf5', 'hdf5_hl'],
         'include_dirs'  : [localpath('lzf'), localpath('windows')],
         'library_dirs'  : [],
-        'define_macros' : [('H5_USE_16_API', None), ('_HDF5USEDLL_', None)] }
+        'define_macros' : [('H5_USE_16_API', None), ('_HDF5USEDLL_', None),
+                           ('H5_BUILT_AS_DYNAMIC_LIB', None)] }

 else:
     COMPILER_SETTINGS = {
```

**Comment by jakirkham** [comment]
That was fast. :smile: Thanks @cgohlke. I'll give this a try.

**Comment by jakirkham** [comment]
You know we would definitely appreciate your presence over at conda-forge, @cgohlke. It would be really helpful to get your insight on how to build things for Windows correctly. :wink:

**Comment by jakirkham** [comment]
Seems to be doing the trick. Maybe we should have a user facing option in `setup.py` to enable this functionality. Thoughts?

**Comment by ocefpaf** [comment]
> You know we would definitely appreciate your presence over at conda-forge, @cgohlke.

:heavy_plus_sign:  :100:

**Comment by andrewcollette** [comment]
@jakirkham I think in the long run the best approach will simply be to do away with the "h5py_" prefix altogether.  It's there to prevent a libhdf5 version conflict in the case where both h5py and PyTables bundle a copy of the HDF5 dll.  These days I think most people get their h5py and PyTables from a single distribution, which makes this issue moot.

**Comment by jakirkham** [comment]
Thanks for explaining the reasoning. If that is the only issue, won't this be a non-issue once PyTables and h5py are integrated into the [same stack]( https://hdfgroup.org/wp/2015/09/python-hdf5-a-vision/ )?

**Comment by andrewcollette** [comment]
@jakirkham, it's a non-issue presently when both PyTables and h5py are built against the same copy of libhdf5.  This is the case with Canopy and Anaconda... otherwise it depends how people are getting their HDF5.

**Comment by jakirkham** [comment]
Sorry, I just meant that once PyTables is using h5py as its layer for interacting with HDF5 only instead of acting directly itself this shouldn't be a problem either, right?

**Comment by andrewcollette** [comment]
Yes, that would automatically solve the problem in all cases, as only one project would link to the underlying C library.  However, my sense is that the necessary PyTables refactor is likely to take place later rather than sooner, with good discussions under way right now about technical and funding options.

**Comment by aragilar** [comment]
Fixed in https://github.com/h5py/h5py/commit/93dad65
