### ISSUE TITLE
File size on disk equal to dataset array, even when mostly empty

### ISSUE THREAD

**Issue by ArjaanBuijk** [h5py/h5py#725]
Not sure if this is a windows issue, a python 3.5 issue, or something else.
This session shows what happens when I type the example of page 23 of the 'python and HDF5' book. There are 2 strange things:
(1) flush() is not actually writing to disk. Only using close() writes to disk.
(2) this is the serious issue. After close(), the file is 4Gb, while it should be only 66K

---

Python 3.5.1 |Anaconda 4.0.0 (64-bit)| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 4.1.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import numpy as np

In [2]: import h5py

In [3]: h5py.version.info
Out[3]: 'Summary of the h5py configuration\n---------------------------------\n\nh5py    2.5.0\nHDF5    1.8.15\nPython  3.5.1 |Anaco
nda 4.0.0 (64-bit)| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit (AMD64)]\nsys.platform    win32\nsys.maxsize     92233720368
54775807\nnumpy   1.10.4\n'

In [4]: cd C:\data
C:\data

In [5]: ls
 Volume in drive C is OS
 Volume Serial Number is F4B5-3A7F

 Directory of C:\data

06/22/2016  11:16 PM    <DIR>          .
06/22/2016  11:16 PM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  144,596,975,616 bytes free

In [6]: f = h5py.File("testfile.hdf5")

In [7]: dset = f.create_dataset("big dataset", (1024**3,), dtype=np.float32)

In [8]: dset[0:1024] = np.arange(1024)

In [10]: f.flush()

In [11]: ls
 Volume in drive C is OS
 Volume Serial Number is F4B5-3A7F

 Directory of C:\data

06/22/2016  11:17 PM    <DIR>          .
06/22/2016  11:17 PM    <DIR>          ..
06/22/2016  11:17 PM                 0 testfile.hdf5
               1 File(s)              0 bytes
               2 Dir(s)  144,596,901,888 bytes free

In [12]: f.close()

In [13]: ls
 Volume in drive C is OS
 Volume Serial Number is F4B5-3A7F

 Directory of C:\data

06/22/2016  11:17 PM    <DIR>          .
06/22/2016  11:17 PM    <DIR>          ..
06/22/2016  11:19 PM     4,294,969,440 testfile.hdf5
               1 File(s)  4,294,969,440 bytes
               2 Dir(s)  140,301,934,592 bytes free

**Comment by andrewcollette** [comment]
The file system you are using likely does not support sparse files.  You can add "chunks=True" to the create_dataset call to force chunked storage, which will be space-efficient on any file system.

Not sure about flush(), but again the exact details are likely OS/FS specific.

**Comment by digdig** [comment]
I've test it on windows7, python2.7.13 and h5py 2.8.0

**Comment by aparamon** [comment]
The following works nicely (the `chunks` parameter is important):
````py
import os
import h5py
import numpy as np

with h5py.File('test.h5', 'w') as f:
    dset = f.create_dataset('big', (1024**3,), dtype=np.float32, chunks=(1024,))
    dset[0:1024] = np.arange(1024)

print(os.stat('test.h5').st_size)
````
