### ISSUE TITLE
Python3: .keys() outputs KeysView object

### ISSUE THREAD

**Issue by fkjogu** [h5py/h5py#726]
Try this on Debian Jessie with python 3.4.2:

```python
with h5py.File('/tmp/example.h5','w') as hf:
    hf.create_dataset('foobar', (100,))
    hf.flush()

with h5py.File('/tmp/example.h5','r') as hf:
     print(hf.keys())
```

This outputs a
`KeysView(<HDF5 file "example.h5" (mode r)>)`
instead of a list of datasets.

**Comment by aragilar** [comment]
This is what should happen, see https://docs.python.org/3/library/stdtypes.html#dict-views. If you want a list, `list(hf.keys())` as you'd expect.

**Comment by fkjogu** [comment]
Oh thank you. Fair enough.

**Comment by justinkterry** [comment]
Hey, your documentation shows it to natively return a list without querrying the object:
http://docs.h5py.org/en/latest/quick.html

Please fix this

**Comment by aristizabal95** [comment]
Documentation still shows `keys()`returning a list instead of a `KeysView(<HDF5 file "example.h5" (mode r)>)`

http://docs.h5py.org/en/stable/quick.html#core-concepts

**Comment by tacaswell** [comment]
@justinkterry @aristizabal95 documentation PRs are very welcome!

**Comment by skylarjhdownes** [comment]
Docs were fixed in 973a5348acd713727bfe3ae032f1413782888d68 by @jpdehollain but it looks like the fix hasn't made it into the hosted documentation at http://docs.h5py.org yet.  Does the documentation get built automatically?

**Comment by tacaswell** [comment]
@skylarjhdownes The updated docs are at http://docs.h5py.org/en/latest/quick.html  which are built everytime we merge to master, the 'stable' docs are the lastest released version of the docs (which do not yet include that fix).  They will be updated the next time we do a release.

**Comment by aristizabal95** [comment]
Just to add to this topic, I found out that `keys()` is not really necessary for printing the list of databases in a certain location, just using `list()` works. for example:

`list(f.keys())`is equivalent to `list(f)`

**Comment by Shanzaay** [comment]
I have tried many solutions but can't seem to solve the problem. This code is in Python 2.7 and I am using Python 3.7. While searching I find out that this gives an error in Python 3.7. Can anyone help me how to remove this error in Python 3.7?

print('Loading c3d features ...')
        features = h5py.File(self._options['feature_data_path'], 'r') 
        self._feature_ids = features.keys()
        self._features = {video_id:np.asarray(features[video_id].values() 
        [0]) for video_id in self._feature_ids}
This is the error I am getting:

E:\jupyter book\data_provider.py in <dictcomp>(.0)

    ---> 68         self._features 
             {video_id:np.asarray(features[video_id].values()[0]) for 
             video_id in self._feature_ids}
         69 
         70 

 TypeError: 'ValuesViewHDF5' object is not subscriptable
