### ISSUE TITLE
Writing a string does not include NULL terminator

### ISSUE THREAD

**Issue by Flamefire** [h5py/h5py#727]
When writing a string, the size set in the HDF5Type does not include the terminating NULL although this is required according to HDF5: `String or character datatypes: The size set for a string datatype should include space for the null-terminator character, otherwise it will not be stored on (or retrieved from) disk` [Datatype-SetSize](https://support.hdfgroup.org/HDF5/doc/RM/RM_H5T.html#Datatype-SetSize)

Example:

```
import h5py
import numpy
f=h5py.File("test.h5")
f.attrs["fooStr"] = numpy.string_("1234")
f.close()
```

bash:

```
h5dump test.h5
```

> > HDF5 "test.h5" {
> > GROUP "/" {
> >    ATTRIBUTE "fooStr" {
> >       DATATYPE  H5T_STRING {
> >          STRSIZE 4;
> >          STRPAD H5T_STR_NULLPAD;
> >          CSET H5T_CSET_ASCII;
> >          CTYPE H5T_C_S1;
> >       }
> >       DATASPACE  SCALAR
> >       DATA {
> >       (0): "1234"
> >       }
> >    }
> > }

Expected:

> > HDF5 "test.h5" {
> > GROUP "/" {
> >    ATTRIBUTE "fooStr" {
> >       DATATYPE  H5T_STRING {
> >          STRSIZE 5;
> >          STRPAD H5T_STR_NULLPAD;
> >          CSET H5T_CSET_ASCII;
> >          CTYPE H5T_C_S1;
> >       }
> >       DATASPACE  SCALAR
> >       DATA {
> >       (0): "1234"
> >       }
> >    }
> > }

**Comment by aragilar** [comment]
This is interesting, HDF5 seems to contradict itself here, as only null term (as opposed to null pad) is required to end with null (see https://support.hdfgroup.org/HDF5/doc/H5.format.html#DataObject and the absence of the requirement to end with null when shortening a string).

**Comment by aparamon** [comment]
Inspecting
````py
dtype = h5py.h5a.open(f._id, b"fooStr").get_type()
print(dtype.get_size())
````
gives me 4, which confirms the error in HDF5 documentation.

**Comment by aparamon** [comment]
[@epourmal says](https://forum.hdfgroup.org/t/bug-writing-a-string-does-not-include-null-terminator/5281/3):
> We will fix documentation. Only size-1 number of characters will be stored, so library behaves correctly. If you change size to 5, you’ll see 1234 string.
> Thanks for reporting!

**Comment by Flamefire** [comment]
> if you change size to 5, you’ll see 1234 string.

So why is this issue closed? Doesn't this mean h5py has to write a size of 5 and not 4 as it currently does?

**Comment by epourmal** [comment]
Hello,

To clarify (or to completely confuse you :-)
 
HDF5 has NULL padded and NULL terminated strings. Depending on the string type, a different number of characters will be stored using the same type size. Does h5py uses NULL padded strings as a default?

If one declares size 4 for a string, then only 3 characters will be stored for a NULL terminated string to accommodate \0 as the last character; if a string is NULL padded, then all 4 characters will be stored. In both cases the size of datatype is 4. 

H5dump prints strings as NULL terminated, but it clearly specifies the type of the string.
As I said, we will go through documentation to make sure we discuss those issues (or provide references) in all relevant places in the docs.

**Comment by aparamon** [comment]
@Flamefire Elena's comment was regarding minimal C example in https://forum.hdfgroup.org/t/bug-writing-a-string-does-not-include-null-terminator/5281.

**Comment by Flamefire** [comment]
I see. In my issue description I copied the output which shows that h5py uses null padding so size 4 is correct given that null padded may not be null terminated (too)
