### ISSUE TITLE
Is there a way to use h5py with hdf5 files that are extracted from a tar file without first writing to disk?

### ISSUE THREAD

**Issue by JohnUrban** [h5py/h5py#730]
Hi,

Thanks for the great library. I have a situation where the data I am using consists of thousands of HDF5 files that are in a .tar.gz file. The data takes up 50-150 GB per tar.gz. My current approach is something like:
```
import tarfile, h5py, shutil, os
f = tarfile.open("data.tar.gz")
f.extractall(path="tmp_dir")
files = [os.path.join("tmp_dir", fname) for fname in f.getnames() if fname.endswith(".hdf5")]
for file in files:
     g = h5py.File(file, 'r')
     ## do stuff with g
shutil.rmtree("tmp_dir")
```

However, this is not ideal since dumping out the tar.gz file intp 'tmp_dir' more than doubles the disk space needed. Some times when I have ample amounts of disk space, that's fine. Other times like now when I do not have that much disk space, I need another approach. An obvious choice is something like:
```
import tarfile, h5py, shutil, os
f = tarfile.open("data.tar.gz")
for tarinfo in f:
        if os.path.splitext(tarinfo.name)[-1] == ".hdf5":
            file = os.path.join("tmp_dir", tarinfo.name)
            f.extract(tarinfo, path="tmp_dir")
            g = h5py.File(file, 'r')
            ## do stuff with g
            os.remove(file)
shutil.rmtree("tmp_dir")
```

However, I was wondering if there was a way to skip writing the hdf5 file to disk with tarfile followed by reading it back in with h5py. For example, tarfile has a method called extractfile that extracts the tar member as a file object instead of extracting to disk. Is there a way to use h5py with that?

Any thoughts or suggestions appreciated.

Thanks again.

--John

**Comment by aragilar** [comment]
No unfortunately, it's a limitation of the hdf5 library, see #687.

**Comment by JohnUrban** [comment]
Thank you. You're right, that is unfortunate, but I will just go with doing 1 file at a time.

**Comment by lpryszcz** [comment]
It seems with recent version of h5py it's possible https://github.com/h5py/h5py/pull/1105.  
For me below works, although it isn't very fast... 

```
import tarfile

mode = "r:gz" if ".gz" in input_path else "r"
f = tarfile.open(input_path, mode)
for tarinfo in f:
    if os.path.splitext(tarinfo.name)[-1] == ".fast5":
        # get tar handle
        handle = f.extractfile(tarinfo)
        # open single hdf5 file directly from tar archive
        single_f5 = h5py.File(handle, 'r')
```
