### ISSUE TITLE
Missing gzip plugin in manylinux wheel

### ISSUE THREAD

**Issue by kif** [h5py/h5py#731]
Dear H5Py development team,

Thanks for providing the "manylinux" wheel now as part of pypi. Actually the windows wheels would be even more useful as compiling hdf5 under linux is much easier than under windows (tested :).

This manylinux wheel apparently does not support the "zlib" compression, which broke our tests on Travis-CI. We checked the zlib is installed on the VM of Travis:

*  zip            3.0-4          Archiver for .zip files
*  zlib1g         1:1.2.3.4.dfsg compression library - runtime
*  zlib1g-dev     1:1.2.3.4.dfsg compression library - development

But h5py.h5d does not link to zlib (while it links to libsz!) :

* linux-vdso.so.1 =>  (0x00007fffcd9fe000)
* libhdf5-f1d499a0.so.10.2.0 => /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/h5py/.libs/libhdf5-f1d499a0.so.10.2.0 (0x00007fe153937000)
* libhdf5_hl-f5b2ba8d.so.10.1.0 => /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/h5py/.libs/libhdf5_hl-f5b2ba8d.so.10.1.0 (0x00007fe15370e000)
* libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe1534e3000)
* libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe153125000)
* librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fe152f1c000)
* libsz-08416a88.so.2.0.1 => /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/h5py/.libs/./libsz-08416a88.so.2.0.1 (0x00007fe152d18000)
* libaec-39ca7337.so.0.0.4 => /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/h5py/.libs/./libaec-39ca7337.so.0.0.4 (0x00007fe152b0f000)
* libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe15290b000)
* libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe15260f000)
* /lib64/ld-linux-x86-64.so.2 (0x00007fe154056000)

Thanks for your work.

Jérôme

**Comment by andrewcollette** [comment]
Ping @matthew-brett... I think we need to make sure zlib compression is available.

**Comment by kif** [comment]
On Wed, 06 Jul 2016 05:56:23 -0700
Andrew Collette <notifications@github.com> wrote:

> Ping @matthew-brett... I think we need to make sure zlib compression is available.

The lz4 compression scheme is getting rather popular since this detector is on the market:
https://www.dectris.com/EIGER.html

Would you be interested in providing this plugin as well. We can help for building & packaging.

Cheers,
-- 
Jérôme Kieffer

**Comment by matthew-brett** [comment]
Oops - thanks - will fix .   @kif - have a look at https://github.com/MacPython/h5py-wheels - can you see how to build the lz4 compression into the wheels?

**Comment by matthew-brett** [comment]
Andrew - what would be a good automated test that zlib compression is enabled in h5py?

**Comment by kif** [comment]
I did, in shell:
ldd $(python -c "import h5py;print(h5py.h5d.__file__)")
see:
https://github.com/silx-kit/silx/blob/master/.travis.yml line ~50

**Comment by matthew-brett** [comment]
I went for this in the end : https://github.com/MacPython/h5py-wheels/commit/435c8578f6b58e8c657adb5c8573df8ec4d3bf51

**Comment by matthew-brett** [comment]
Can you try the new wheels up at https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com

**Comment by matthew-brett** [comment]
OK - should be fixed now - try installing again from pypi?

**Comment by matthew-brett** [comment]
Done by rebuilding with new h5py-wheels commit, and then using [add_build.py](https://gist.github.com/1b2e76d0f4993c1ff6c1ed4d16a7384d) to add a [build tag](https://www.python.org/dev/peps/pep-0425/#use) to the wheel filename.  This last step is because we can't upload new contents with the old filename, pypi does not allow that, because the files are on a [content delivery network](https://en.wikipedia.org/wiki/Content_delivery_network).

**Comment by kif** [comment]
I confirm, this new wheel fixes the bug ... It is up to you to decide if you can close the issue now or with the next release.

Thanks for your responsiveness.

**Comment by matthew-brett** [comment]
I would vote to close - the wheels on pypi for this release do now have zlib, and the wheel building machinery now checks that this is the case.
