### ISSUE TITLE
Errors with datasets using compound datatype including offset

### ISSUE THREAD

**Issue by jrs65** [h5py/h5py#735]
In our project we generate files which contain a dataset with a compound datatype. This is of the form: `<u4  ... 4 byte gap ...  <f8`, such that the total size is 16 bytes. For clarity the equivalent numpy datatype is:

```
dtype={'names':['fpga_count','ctime'], 'formats':['<u4','<f8'], 'offsets':[0,8], 'itemsize':16}
```

These files are generated by external C routines using the `HDF5` library directly, not using `h5py`, and seem to valid `HDF5` files (tested with `h5check`). As it seems to be impossible to construct one of these files using `h5py` (see later on), I've placed a test file here ([Test HDF5 file](http://www.phas.ubc.ca/~richard/testdset.h5)). Using `h5ls` on the file gives:

``` bash
$ h5ls -v testdset.h5/dset
Opened "testdset.h5" with sec2 driver.
dset                     Dataset {1024/Inf}
    Location:  1:57008
    Links:     1
    Chunks:    {1} 16 bytes
    Storage:   16384 logical bytes, 16384 allocated bytes, 100.00% utilization
    Type:      struct {
                   "fpga_count"       +0    native unsigned int
                   "ctime"            +8    native double
               } 16 bytes
```

The biggest problem is errors when reading the file in `h5py 2.6.0`. In `h5py 2.5.0` everything is fine, and when reading this dataset, the data is read correctly though the resulting numpy array has the datatype squashed down:

``` python
>>> h5py.File('testdset.h5')['dset'][:]
array([(33554432L, 1444015658.10168), (41943040L, 1444015679.575919),
       (50331648L, 1444015701.050865), ..., (8388608L, 1444037583.908599),
       (16777216L, 1444037605.000615), (25165824L, 1444037626.85825)], 
      dtype=[('fpga_count', '<u4'), ('ctime', '<f8')])
```

This data is correct (also checked by reading by `h5dump`).

However, in `h5py 2.6.0` the data is read incorrectly. Reading gives:

``` python
>>>h5py.File('testdset.h5', 'r')['dset'][:]
array([(33554432L, 1.2232475900471088e-296),
       (2414140379L, -2.998779488157548e-206),
       (1104512123L, 1444015722.526203), ...,
       (437775368L, 1.8127938377128907e-60),
       (437833456L, 2.338285561e-314), (0L, 0.0)], 
      dtype={'names':['fpga_count','ctime'], 'formats':['<u4','<f8'], 'offsets':[0,8], 'itemsize':16})
```

Where the data as numpy understands it is very much incorrect. Here it seems that the datatype the numpy array gets is the direct equivalent of the underlying HDF5 datatype, but the memory it is pointed at is the same as it was for `h5py 2.5.0`, i.e. it has had the space squashed out of it. I've verified this by dumping the underlying memory representation to disk with `np.ndarray.tofile` for both `2.5.0` and `2.6.0` and examining them with `hexdump`. Both are identical and have no offset. It's not clear to me whether the memory that numpy is viewing is the full size that it expects with only the beginning filled with the packed values, or if it is only the length of the actual packed data, in which case numpy is actually reading off the end of it (and thus could possibly segfault).

There is a likely related aspect of this when trying to use `h5py` to write data explicitly created with a 4-byte gap. In `h5py 2.5.0` when doing this:

``` python
# Create compound data type with offset
dt = np.dtype({'names':['field1', 'field2'], 'formats':['<i4','<i4'], 'offsets':[0, 8], 'itemsize':12})

# Construct array
arr = np.ndarray(10, dt)
arr['field1'] = -1
arr['field2'] = 1

# Create h5py and dataset
fh = h5py.File('newtest6.h5')
dset = fh.create_dataset('dset', shape=(10,), dtype=dt)
dset[:] = arr

print dset
print dset[:]

# Output:
# <HDF5 dataset "dset": shape (10,), type "|V8">
# [(-1, -1879048192) (1, -1) (252903432, 1) (-1, 1) (1, -1) (255102320, 1) (-1, 1) (1, -1) (231894752, 1) (-1, 1)]
```

It seems that the datatype of the HDF5 dataset gets squashed down to 8-bytes (from the 12  bytes it should be), and the data underlying representation is incorrect for the HDF5 datatype (all values should be -1, or 1). The contents of the dataset shown are the same as seen by `h5dump`.

In `h5py 2.6.0` writing the file out actually seems to generate an invalid file (i.e. h5dump and h5ls etc., can't read it).

**Comment by smutch** [comment]
I am also seeing this issue attempting to read a dataset with the following table structure, created using the hdf5 C library:

```
struct {
    "id_MBP"           +0    native long
    "ID"               +8    native long
    "Type"             +16   native int
    "CentralGal"       +20   native int
    "GhostFlag"        +24   native int
    "Len"              +28   native int
    "MaxLen"           +32   native int
    "PhysicsFlags"     +168  native int
    "Pos"              +36   [3] native float
    "Vel"              +48   [3] native float
    "Spin"             +60   native float
    "Mvir"             +64   native float
    "Rvir"             +68   native float
    "Vvir"             +72   native float
    "Vmax"             +76   native float
    "FOFMvir"          +80   native float
    "HotGas"           +84   native float
    "MetalsHotGas"     +88   native float
    "ColdGas"          +92   native float
    "MetalsColdGas"    +96   native float
    "Mcool"            +100  native float
    "DiskScaleLength"  +104  native float
    "StellarMass"      +108  native float
    "GrossStellarMass" +112  native float
    "MetalsStellarMass" +116  native float
    "Sfr"              +120  native float
    "EjectedGas"       +124  native float
    "MetalsEjectedGas" +128  native float
    "BlackHoleMass"    +132  native float
    "MaxReheatFrac"    +136  native float
    "MaxEjectFrac"     +140  native float
    "Rcool"            +144  native float
    "Cos_Inc"          +148  native float
    "MergTime"         +152  native float
    "MergerStartRadius" +156  native float
    "BaryonFracModifier" +160  native float
    "MvirCrit"         +164  native float
    "MWMSA"            +172  native float
    "NewStars"         +176  [5] native float
} 200 bytes
```

Reading with h5py v2.6.0 results in the file being read incorrectly for any information after and including `PhysicsFlag`.  This may be due to this field being out of order with the dataset as it exists in memory.  However, pytables can read this file fine, as can h5dump.

h5py v2.5.0 can also read the file correctly.

**Comment by andrewcollette** [comment]
#711 is similar... appears to be a regression introduced in #701.

**Comment by smutch** [comment]
Ah - thanks @andrewcollette.  Based on this, I've made a fix to #701 to only use the numpy dtype for offsets if the dtype is aligned.  I'll test this tonight and submit a PR if it's successful.

**Comment by andrewcollette** [comment]
@smutch, I think the "logical" flag also fits into this problem somehow... basically, when this flag is set, the returned HDF5 type is not necessarily of the same size as the type in the fields dict.  But the code from #701 assumes that the sizes are always the same and consistent with the dtype offsets. That's what's causing the insert error in #711, and it may be related to this issue as well.

HDF5 can cope with two compound types having different alignments (and even different member types), and will auto-convert.  The root of this issue seems to be that we are somehow generating incorrect descriptions of existing types, so HDF5 corrupts the data when it attempts to convert.

**Comment by smutch** [comment]
Hi all, so I think I may have caused some confusion here.  My apologies for this.

I've just started looking into this further and it appears that the issue I have reported above is a separate one.  The issue reported by @jrs65 appears to actually have been *fixed* by #701.  @jrs65 - can you confirm this?  If so then I'll open a new issue so this one can be closed.  Sorry again!

**Comment by jrs65** [comment]
@smutch Ah, that would be great if the fix is already in master. I'll check it out later today.

**Comment by smutch** [comment]
No worries.  I've just opened #737 to deal with the problem I am seeing.

**Comment by aragilar** [comment]
@jrs65 This appears to be fixed, feel free to reopen this if this is not true.
