### ISSUE TITLE
Problem building with hdf5 1.8.17 with --enable-threadsafe 

### ISSUE THREAD

**Issue by will133** [h5py/h5py#741]
We were building a h5py using hdf5 1.8.12 where --enable-threadsafe is turned on.  It seems like there's a change since hdf5 1.8.14 where --enable-threadsafe is not compatible/supported with the high-level API.  Thus the only way to build hdf5 1.8.17 with --enable-threadsafe is to build it with the --disable-hl flag.  Otherwise, it would cause failure such as:

```
checking for thread safe support... configure: error: The thread-safe library is incompatible with the 
high-level library. --disable-hl can be used to prevent building the high-level library (recommended). 
Alternatively, --enable-unsupported will allow building the high-level library, though this configuration is 
not supported by The HDF Group
```

So should we build with the --enable-unsupported flag?  Otherwise, it looks like we can only build h5py with the serialized (without --enable-threadsafe) version of hdf5?

Thanks.

**Comment by davidslac** [comment]
We build with --enable-threadsafe and --unable-unsupported in order to get the C++ wrappers, then tell people not to use the C++ wrappers from multi-threaded apps
