### ISSUE TITLE
h5py 2.6.0 reading compound from 1D array of compounds incorrectly

### ISSUE THREAD

**Issue by davidslac** [h5py/h5py#742]
This may be related to https://github.com/h5py/h5py/issues/735 and https://github.com/h5py/h5py/issues/737, but I have a h5 file with a dataset that is a stacked 1D array of a compound type. The 1D array has just one entry in it, one row. This row is read correctly by h5py 2.5.0, but not by h5py 2.6.0. I've built h5py 2.6.0 against hdf5 1.8.17 parallel, but I don't think that matters. 

Unfortunately, it does not look like I can attach the .h5 file, however if you want to see it, or use it in regression tests, I put it at 

http://slac.stanford.edu/~davidsch/test.h5

From hdf5, you can see the correct values (and here is the dataset where I found a problem):

h5ls -d test.h5/Configure:0000/Run:0000/CalibCycle:0000/Bld::BldDataEBeamV3/EBeam/data
data                     Dataset {1/Inf}
    Data:
        (0) {256, 0.019605993696, 4813.75908423717, -0.210484336850502, 0.00834144496382332, 0.0328705953924916, 0.0634931790398521, 15285.3740234375, 0.409803062677383, 56.1896362304688, -0.248000144958496}

But this script

sanagpu102: ~ $ cat try_h5py.py 
import os
import sys
import h5py
assert 2==len(sys.argv)
assert os.path.exists(sys.argv[1])

h5 = h5py.File(sys.argv[1],'r')
ds = h5['/Configure:0000/Run:0000/CalibCycle:0000/Bld::BldDataEBeamV3/EBeam/data']
print ds[:]

gives the following for h5py 2.6.0

[ (256L, 3.156154992102952e+93, -2.9884512639804423e-195, -1.629249982430288e+51, 5.670686678609034e-114, -2.5571684883821853e+36, -2.681562222210795e+154, -1.4916685063498426e-154, 5.29275905e-315, 5.329628284e-315, 1.5899343586e-314)]

on the dataset, where as it gives the correct values when using h5py 2.5.0.

**Comment by will133** [comment]
Just want to say that I have a very similar problem with h5py 2.6.0 with hdf5 1.8.17 as well.  I'm trying to update from 2.3.1 to 2.6.0 and I used to be able to read a compound nested structure correctly.  The returned values all seem corrupted to the point it's unusable.  Do you think downgrading to 2.5 would help?

**Comment by davidslac** [comment]
Yes, I downgraded to 2.5.0 and those tests passed. We've been using 2.5.0 for a while without trouble.

**Comment by will133** [comment]
Ok thanks.  I wonder if #701 can fix this as well.  It looks to be merged in head.  Meanwhile I'll try 2.5.0.

**Comment by tacaswell** [comment]
I am going to close this as is working for me with master + py3.6 + hdf5 1.10.  Please ping to have re-opened if I am wrong.
