### ISSUE TITLE
Why general OSError instead of more specific exceptions?

### ISSUE THREAD

**Issue by jluttine** [h5py/h5py#747]
Hi, and thanks for the amazing package! I'm curious: Why h5py raises OSError instead of more specific exceptions such as FileExistsError and FileNotFoundError? It'd help handling the exceptions if they were more specific.

**Comment by tacaswell** [comment]
Those exceptions were introduced in python 3.3 (https://docs.python.org/3/whatsnew/3.3.html#pep-3151-reworking-the-os-and-io-exception-hierarchy).

This could probably be done with a compatibility layer.  Is there a standard way to handle this set of exceptions?

**Comment by takluyver** [comment]
We don't get the POSIX errno back from HDF5, which is what would indicate the specific error to be used. It's there in a string, but I'm reluctant to start parsing error messages like that. I've asked for this to be added to the error struct:

https://forum.hdfgroup.org/t/get-posix-errno-from-hdf5-errors/5003
https://jira.hdfgroup.org/browse/HDFFV-10631

I think #1133 has more detail on this now, so I'm going to close this issue.
