### ISSUE TITLE
LZF filter compatible with HDF5 1.10?

### ISSUE THREAD

**Issue by estan** [h5py/h5py#751]
Looking at the code, it looks like it is not? But I can't see anything that would exclude it from compilation when h5py is built against HDF5 1.10.

The reason I'm asking is I've taken the `lzf` directory from h5py, building it as a plugin using my own simple Makefile. But I'm having trouble building it on Arch Linux which has HDF5 1.10 (on Ubuntu it works fine, which has 1.8).

**Comment by aragilar** [comment]
@estan Have you tried building it recently?

**Comment by estan** [comment]
@aragilar No, I'm afraid this was so long ago I don't even have access to the Arch machine I was doing this on. Nowadays we're using Blosc instead of LZF. Feel free to close this issue :)

**Comment by aragilar** [comment]
Cool, thanks for reply.
