### ISSUE TITLE
ImportError: cannot import name _errors

### ISSUE THREAD

**Issue by bungernut** [h5py/h5py#753]
I am a user on a large cluster, no root access.

I've installed cython by downloading and running python setup.py install --user.
>setenv PATH ${PATH}:/u/xo/bung/.local/bin

Had to compile HDF5 using configure method and added lib and bin to enviroment variables
> setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:/u/xo/bung/SOFTWARE/hdf5-1.8.17/hdf5/lib
> setenv PATH ${PATH}:/u/xo/bung/SOFTWARE/hdf5-1.8.17/hdf5/bin

To compile h5py it could not figure out where include directory was, setting CPLUS_INCLUDE_PATH did not work. Finally used this command:
> python setup.py install --user build_ext -n -I/u/xo/bung/SOFTWARE/hdf5-1.8.17/hdf5/include

The compile seems to complete without error, ends with:
Finished processing dependencies for h5py==2.6.0

Finally I go to my HOME directory and try to import h5py:
```
bung@rhel6-64k $ cd
bung@rhel6-64k $ python
Python 2.7.2 (default, Oct 17 2012, 03:00:49) 
[GCC 4.4.6 [TWW]] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>> import h5py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u/xo/bung/.local/lib/python2.7/site-packages/h5py-2.6.0-py2.7-linux-x86_64.egg/h5py/__init__.py", line 24, in <module>
    from . import _errors
ImportError: cannot import name _errors

```
I saw https://github.com/h5py/h5py/issues/557 but I am not trying to run in the build directory. 

Any suggestions?
Thanks

**Comment by aragilar** [comment]
First, remove the old h5py (it's also probably a good idea to remove cython)
Then, use pip, not setup.py for installing (this will fix so many problems).
You want HDF5_DIR as per http://docs.h5py.org/en/latest/build.html#install.

**Comment by bungernut** [comment]
I dont have pip on the cluster I'm using, but HDF5_DIR was exactly the fix. Thanks (cant believe I missed that, thanks).

**Comment by aragilar** [comment]
Installation instructions for pip are at https://pip.pypa.io/en/stable/installing/#installing-with-get-pip-py. I highly recommend using pip, there's a whole bunch of non-obvious broken defaults otherwise.

**Comment by adj9** [comment]
Good moorning,
I too have the error in importing the h5py package.
The state of mind is a good deal.
I installed it with both pip (command: `pip install h5py`) and homebrew (command: `brew install h5py`) and the installation is successful.

The pip installation command I used is pip install h5py and the error is:
`> import h5py`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "h5py/__init__.py", line 30, in <module>
    raise ImportError("You cannot import h5py from inside the install directory.\nChange to another directory first.")
ImportError: You cannot import h5py from inside the install directory.
Change to another directory first.

While with homebrew I installed it with the command brew install h5py and the error is:
`> import h5py`
Traceback (most recent call last):
  File “~/python3.6/site-packages/h5py-master/h5py/__init__.py", line 26, in <module>
    from . import _errors
ImportError: cannot import name '_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File “~/python3.6/site-packages/h5py-master/h5py/__init__.py", line 30, in <module>
    raise ImportError("You cannot import h5py from inside the install directory.\nChange to another directory first.")
ImportError: You cannot import h5py from inside the install directory.
Change to another directory first.

I tried to install it manually with the command `python setup.py install` but it gives me the first error.

Do you have any suggestion?
Best regards
Alessandro LUMACA

**Comment by tacaswell** [comment]
It looks like you have at least 3 installations of h5py (one from pip, one from homebrew, and one from source) which are conflicting with each other.

I suggest uninstalling everything and starting from scratch with just one of the installation methods.

It also looks like you have homebrew python and a local installation in your home directory?

**Comment by leesing9** [comment]
나는 너의 지식에 감탄했다.
