### ISSUE TITLE
ipy_completer.py: iterkeys attribute does not exist in Python 3

### ISSUE THREAD

**Issue by nawijn** [h5py/h5py#760]
Tab completion in IPython using Python 3 did not work for me. When trying to do so,
it will fail with an attribute error for "iterkeys". This makes sense, because iterkeys
does not exist for Python 3. By changing the following snippet, in the h5py_item_completer
function, it works fine for me.

Current code snippet:

```
    if path:
        items = (posixpath.join(path, name) for name in obj[path].iterkeys())
    else:
        items = obj.iterkeys()
```

Code snippet to support both Python 2/3

```
    if path:
        entries = obj[path]
        if hasattr(entries, 'iterkeys'):
            items = (posixpath.join(path, name) for name in entries.iterkeys())
        else:
            items = (posixpath.join(path, name) for name in entries.keys())
    else:
        if hasattr(obj, 'iterkeys'):
            items = obj.iterkeys()
        else:
            items = obj.keys()
```

</snip-new>

There are other ways of course (e.g detecting Python version with sys.version_info).

**Comment by aragilar** [comment]
Fixed in https://github.com/h5py/h5py/pull/715.
