### ISSUE TITLE
Garbage returned from reading hdf5 vlen dataset

### ISSUE THREAD

**Issue by ngoldbaum** [h5py/h5py#764]
It seems that there has been a regression in the handling of vlen datasets. This can be easily reproduced using an HDF5 file produced by an old version of the FLASH simulation code. The easiest way to get it is to use the yt curldrop:

```
curl -JO http://use.yt/upload/1106d6c4
```

This will create a file named `DensTurbMag_hdf5_plt_cnt_0015` in the current directory.

To reproduce the issue, run the following test script:

```
import h5py
f = h5py.File('DensTurbMag_hdf5_plt_cnt_0015')
print(f['simulation parameters'][:])
```

Under h5py 2.6.0 this prints:

```
array([ (73, 4.6683907401e-313, 1.69759663317e-313, -4e-323, -759169024, 1113971554, -402653184, 1108822134)],
      dtype={'names':['total blocks','time','timestep','redshift','number of steps','nxb','nyb','nzb'], 'formats':['<i4','<f8','<f8','<f8','<i4','<i4','<i4','<i4'], 'offsets':[0,24,32,40,4,8,12,16], 'itemsize':48})
```

Whereas under h5py 2.5.0 it prints:

```
array([(73, 751000000000.0, 25000000000.0, 0.0, 22, 8, 8, 8)],
      dtype=[('total blocks', '<i4'), ('time', '<f8'), ('timestep', '<f8'), ('redshift', '<f8'), ('number of steps', '<i4'), ('nxb', '<i4'), ('nyb', '<i4'), ('nzb', '<i4')])
```

This was originally reported by a user on the yt mailing list. See https://bitbucket.org/yt_analysis/yt/issues/1291/simulation-parameters-in-flash-25-datasets.

**Comment by ngoldbaum** [comment]
Bisected to 0d6b88def48a53241511ef287f722105b6142ce1. Ping @nevion.

**Comment by nevion** [comment]
Perhaps I'm not up to date on my nomenclature but I don't understand what vlen has to do with this problem or even dataset storage kinds - just the dataset's type.   I suspect it has to do with the offsets being out of order from the type's listed order (you can see the offsets list is out of order in 2.6) - if so, I believe this is actually a numpy bug. Were the fields for the compound type created out of order in the original writer?

Try the following change to see  if it fixes the issue (I'm unable to test this for a few days and will probably end up forgetting):

```
if len(field_names) > 0:
    ordered_fields = sorted(zip(field_names, field_types, field_offsets), key = lambda x: x[2])
    field_names, field_types, field_offsets = zip(*ordered_fields)
typeobj = dtype({'names': field_names, 'formats': field_types, 'offsets': field_offsets})

```

**Comment by ngoldbaum** [comment]
The original writer was a fortran code that I don't actually have access to, so I'm not sure what was happening there.

**Comment by Xarthisius** [comment]
Issue can be reproduced with the following gist: https://gist.github.com/Xarthisius/80d3198972130dbf03683022d7e96917

That's roughly what the original code does.
