### ISSUE TITLE
icc python setuptools incompatibility

### ISSUE THREAD

**Issue by thierry3000** [h5py/h5py#766]
I need to install h5py on an intel cluster using icc due to the fact that this properly supports mkl stuff. Compiling works. Linking not. 

h5py/_errors.so: undefined symbol: __intel_sse2_strlen

In case one uses icc for compiling h5py, one additionally needs to link the intel libraries: 'irc','svml','imf'
(see https://github.com/lesgourg/class_public/issues/40)
I hacked those into the setup_build.py. However I suggest to add a command line argument to provide additional libraries to link with.

**Comment by aragilar** [comment]
Have you asked on distutils-sig about this, I vaguely remember Intel adding a patch to setuptools/distutils about this?

**Comment by thierry3000** [comment]
Turned out that is a general problem, when mixing linkers. Setting LDSHARED="icc -shared" globally solved 
issue.
(see http://stackoverflow.com/questions/37905210/how-to-override-pythons-distutils-gcc-linker-with-icc)
Thanks aragilar, that pointed the right direction.
