### ISSUE TITLE
H5Py return bad attribute value

### ISSUE THREAD

**Issue by JGoutin** [h5py/h5py#767]
Hello,

H5py return the bad value for attributes in the following case:

**With h5py 2.6.0 on Python 3.5.2 64bits/Windows 7 64Bits:** 
`h5py.File('320X240.h5', 'r')['Attributes']['{01A2D47C-5817-4745-AADE-FBDFF4C60DD8}'].attrs['Data Context.Data Attributes.Camera Height']`
_[((b'LateralCat', b'Pixels', [0.0, 1.8274538888363168e-05]), **0.0**)]_

**With HDFView 2.13: "Data Context.Data Attributes.Camera Height" in "/Attributes/{01A2D47C-5817-4745-AADE-FBDFF4C60DD8}" from "320X240.datx" :**
Value:
_{ {LateralCatgn, Pixels, 0, 1.82745e-05} , **240**}_ 
Type:
_Compound {Compound {String, length = variable, String, length = variable, Variable-length of 64-bit floating-point, }, 64-bit floating-point, }_

The good value is **240**, H5Py return **0**.

Here is the source H5 file : 
[320X240.h5](https://github.com/h5py/h5py/files/550653/320X240.zip)

**Comment by pdebuyl** [comment]
h5py 2.6.0 Python 3.5.2 64bit Linux

    f['Attributes/{01A2D47C-5817-4745-AADE-FBDFF4C60DD8}'].attrs['Data Context.Data Attributes.Camera Height']
    array([((b'LateralCat', b'Pixels', [0.0, 1.8274538888363168e-05]), 240.0)],
      dtype=[('Converter', [('Category', 'O'), ('BaseUnit', 'O'), ('Parameters', 'O')]), ('Value', '<f8')])

This is strange, can someone on Windows reproduce the issue?

**Comment by JGoutin** [comment]
Uninstalled/reinstalled H5Py : This time, no error...

I don't understand what happened.

**Comment by pdebuyl** [comment]
Thanks for updating and closing. Is it possible you would have update NumPy or Cython and not h5py at some point?

**Comment by JGoutin** [comment]
I didn't build it myself, I use the h5py wheels from http://www.lfd.uci.edu/~gohlke/pythonlibs/#h5py (Before and after the bug report).

I updated Numpy recently to 1.11.2 without update H5py after (But it was already 2.6.0).

**Comment by pdebuyl** [comment]
I must admit that I am not familiar with Windows. Provided that you have unittests2 installed, you can run the tests of an installed h5py with `python -c 'import h5py; h5py.run_tests()'`. This is worth a try if the problem occurs again. If your issue is not catched by the testsuite then some bug fixing is needed.

**Comment by JGoutin** [comment]
If the bug occur again, I'll try this and report result here.

Thanks.
