### ISSUE TITLE
Does h5py support image datasets?

### ISSUE THREAD

**Issue by felix1028** [h5py/h5py#771]
I need to add a png/jpg image to my hdf5 file. I tried using create_dataset("image", data='path/to/filefig.png', dtype='uint8') and get this error:
 
IOError: Can't prepare for writing data (No appropriate function for conversion path)

Is appending an image file to my hdf5 file possible?
Thanks,
-Mariana

**Comment by felix1028** [comment]
BTW, I'm looking to do a truecolor image, instead of a indexed image.

**Comment by pdebuyl** [comment]
The `data` argument is interpreted as a string and the `dtype` argument requests a conversion to an unsigned integer. If you load your image as a NumPy array first, via whatever method your prefer, you should be fine.

**Comment by felix1028** [comment]
Thanks for the info! I think I'm most of the way there.

 I'm making a plot with MatplotLib and saving it as a PNG so I can use the Image library to open the PNG file as a NumPy ndarray 'int8'. I can pass this 3d array (800,1200,4) to my HDF5 file using h5py's create_dataset call. This plus a few attributes (CLASS=IMAGE, IMAGE_VERSION='1.2', IMAGE_SUBCLASS=IMAGE_TRUECOLOR, INTERLACE_MODE=INTERLACE_PIXEL) puts the data in my hdf5 file without errors.

However, this data comes out as a table in my hdf5 file. I *can* make this show up as an image after some selections with HDFView, but everything defaults to a table. 

Would you happen to know if there are any other requirements to have the image data show up as an image, instead of a table?

**Comment by pdebuyl** [comment]
I am not

**Comment by felix1028** [comment]
Here is the idea: I have a set of latitude and longitude points that I need to save in an image in an hdf5 file. This is a simplified example of what I want to do that shows the problem I'm having:

import matplotlib.pyplot as plt
from mpl_toolkits.basemap import Basemap
import numpy as np
import Image
import h5py

figure = plt.figure(dpi=200)
lons=np.array([160.0, 23.0, 120.5, 65.1])
lats=np.array([-10, 0 , 40, -30])
maps = Basemap(projection='cyl',llcrnrlat=-60,urcrnrlat=60,llcrnrlon=-180,urcrnrlon=180)
x, y = maps(lons, lats)
maps.plot(x,y, '.', color='black', markersize=8)

plt.savefig('/home/mfs/code/python/gpm_pf/testmap.png',dpi=200) 



#This opens the image I just created to save it as a binary. Would love to skip this if possible but have not been able to go from matplotlib to numpy array:

img = Image.open('/home/mfs/code/python/gpm_pf/testmap.png')
img.load()
imgData = np.asarray( img, dtype='byte' )



hf = h5py.File('/home/mfs/code/python/gpm_pf/imageSample.HDF5', 'w')

dset=hf.create_dataset("/myData/myImage", data=imgData, dtype='uint8') #chunks=True,
# Set the image attributes
dset.attrs['CLASS'] = 'IMAGE'
dset.attrs['IMAGE_VERSION'] = '1.2'
dset.attrs['IMAGE_SUBCLASS'] = 'IMAGE_TRUECOLOR'
dset.attrs['INTERLACE_MODE'] = 'INTERLACE_PIXEL'
dset.attrs['IMAGE_COLORMODEL'] = 'RGB'

hf.close()

**Comment by felix1028** [comment]
Just figured out. Its something to do with the attribute additions in the end. The correct calls are:
dset.attrs.create('CLASS', 'IMAGE')
dset.attrs.create('IMAGE_VERSION', '1.2')
dset.attrs.create('IMAGE_SUBCLASS', 'IMAGE_TRUECOLOR')
dset.attrs.create('INTERLACE_MODE', 'INTERLACE_PIXEL')


Thank you for your help!
-Mariana

**Comment by pdebuyl** [comment]
Hi,

Thanks for the update with the fix! For info, I checked the earlier syntax but defining only the 4 attributes set in the update, i.e.

~~~ .py
dset.attrs['CLASS'] = 'IMAGE'
dset.attrs['IMAGE_VERSION'] = '1.2'
dset.attrs['IMAGE_SUBCLASS'] = 'IMAGE_TRUECOLOR'
dset.attrs['INTERLACE_MODE'] = 'INTERLACE_PIXEL'
~~~

and it works as well (hdfview shows the image properly).

If your problem is solved, could you close the issue?

Regards,

Pierre

**Comment by felix1028** [comment]
Pierre,
thanks for the follow-up.
