### ISSUE TITLE
Can't install on macOS.

### ISSUE THREAD

**Issue by nazandr** [h5py/h5py#772]
`Collecting h5py
  Using cached h5py-2.6.0.tar.gz
Requirement already satisfied: numpy>=1.6.1 in ./keras/lib/python3.6/site-packages (from h5py)
Requirement already satisfied: six in ./keras/lib/python3.6/site-packages (from h5py)
Building wheels for collected packages: h5py
  Running setup.py bdist_wheel for h5py ... error
  Complete output from command /Users/andrey/keras/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/tmpxzq8p508pip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-intel-3.6
  creating build/lib.macosx-10.6-intel-3.6/h5py
  copying h5py/__init__.py -> build/lib.macosx-10.6-intel-3.6/h5py
  copying h5py/highlevel.py -> build/lib.macosx-10.6-intel-3.6/h5py
  copying h5py/ipy_completer.py -> build/lib.macosx-10.6-intel-3.6/h5py
  copying h5py/version.py -> build/lib.macosx-10.6-intel-3.6/h5py
  creating build/lib.macosx-10.6-intel-3.6/h5py/_hl
  copying h5py/_hl/__init__.py -> build/lib.macosx-10.6-intel-3.6/h5py/_hl
  copying h5py/_hl/attrs.py -> build/lib.macosx-10.6-intel-3.6/h5py/_hl
  copying h5py/_hl/base.py -> build/lib.macosx-10.6-intel-3.6/h5py/_hl
  copying h5py/_hl/dataset.py -> build/lib.macosx-10.6-intel-3.6/h5py/_hl
  copying h5py/_hl/datatype.py -> build/lib.macosx-10.6-intel-3.6/h5py/_hl
  copying h5py/_hl/dims.py -> build/lib.macosx-10.6-intel-3.6/h5py/_hl
  copying h5py/_hl/files.py -> build/lib.macosx-10.6-intel-3.6/h5py/_hl
  copying h5py/_hl/filters.py -> build/lib.macosx-10.6-intel-3.6/h5py/_hl
  copying h5py/_hl/group.py -> build/lib.macosx-10.6-intel-3.6/h5py/_hl
  copying h5py/_hl/selections.py -> build/lib.macosx-10.6-intel-3.6/h5py/_hl
  copying h5py/_hl/selections2.py -> build/lib.macosx-10.6-intel-3.6/h5py/_hl
  creating build/lib.macosx-10.6-intel-3.6/h5py/tests
  copying h5py/tests/__init__.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests
  copying h5py/tests/common.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests
  creating build/lib.macosx-10.6-intel-3.6/h5py/tests/old
  copying h5py/tests/old/__init__.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
  copying h5py/tests/old/common.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
  copying h5py/tests/old/test_attrs.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
  copying h5py/tests/old/test_attrs_data.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
  copying h5py/tests/old/test_base.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
  copying h5py/tests/old/test_dataset.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
  copying h5py/tests/old/test_datatype.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
  copying h5py/tests/old/test_dimension_scales.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
  copying h5py/tests/old/test_file.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
  copying h5py/tests/old/test_group.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
  copying h5py/tests/old/test_h5.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
  copying h5py/tests/old/test_h5f.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
  copying h5py/tests/old/test_h5p.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
  copying h5py/tests/old/test_h5t.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
  copying h5py/tests/old/test_objects.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
  copying h5py/tests/old/test_selections.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
  copying h5py/tests/old/test_slicing.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
  creating build/lib.macosx-10.6-intel-3.6/h5py/tests/hl
  copying h5py/tests/hl/__init__.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/hl
  copying h5py/tests/hl/test_attribute_create.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/hl
  copying h5py/tests/hl/test_dataset_getitem.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/hl
  copying h5py/tests/hl/test_dataset_swmr.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/hl
  copying h5py/tests/hl/test_datatype.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/hl
  copying h5py/tests/hl/test_dims_dimensionproxy.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/hl
  copying h5py/tests/hl/test_file.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/hl
  copying h5py/tests/hl/test_threads.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/hl
  running build_ext
  /Users/andrey/keras/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py:30: UserWarning: Cython.Distutils.old_build_ext does not properly handle dependencies and is deprecated.
    "Cython.Distutils.old_build_ext does not properly handle dependencies "
  Autodetection skipped [dlopen(libhdf5.so, 6): image not found]
  ********************************************************************************
                         Summary of the h5py configuration
  
      Path to HDF5: None
      HDF5 Version: '1.8.4'
       MPI Enabled: False
  Rebuild Required: False
  
  ********************************************************************************
  Executing api_gen rebuild of defs
  Executing cythonize()
  ./h5py/api_types_ext.pxd: cannot find cimported module 'mpi4py.MPI'
  /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5p.pyx: cannot find cimported module 'mpi4py.libmpi'
  /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5p.pyx: cannot find cimported module 'mpi4py.mpi_c'
  Compiling /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/defs.pyx because it changed.
  Compiling /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/_errors.pyx because it changed.
  Compiling /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/_objects.pyx because it changed.
  Compiling /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/_proxy.pyx because it changed.
  Compiling /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5fd.pyx because it changed.
  Compiling /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5z.pyx because it changed.
  Compiling /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5.pyx because it changed.
  Compiling /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5i.pyx because it changed.
  Compiling /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5r.pyx because it changed.
  Compiling /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/utils.pyx because it changed.
  Compiling /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/_conv.pyx because it changed.
  Compiling /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5t.pyx because it changed.
  Compiling /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5s.pyx because it changed.
  Compiling /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5p.pyx because it changed.
  Compiling /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5d.pyx because it changed.
  Compiling /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5a.pyx because it changed.
  Compiling /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5f.pyx because it changed.
  Compiling /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5g.pyx because it changed.
  Compiling /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5l.pyx because it changed.
  Compiling /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5o.pyx because it changed.
  Compiling /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5ds.pyx because it changed.
  Compiling /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5ac.pyx because it changed.
  [ 1/22] Cythonizing /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/_conv.pyx
  [ 2/22] Cythonizing /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/_errors.pyx
  [ 3/22] Cythonizing /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/_objects.pyx
  [ 4/22] Cythonizing /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/_proxy.pyx
  [ 5/22] Cythonizing /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/defs.pyx
  [ 6/22] Cythonizing /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5.pyx
  [ 7/22] Cythonizing /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5a.pyx
  [ 8/22] Cythonizing /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5ac.pyx
  [ 9/22] Cythonizing /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5d.pyx
  [10/22] Cythonizing /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5ds.pyx
  [11/22] Cythonizing /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5f.pyx
  [12/22] Cythonizing /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5fd.pyx
  [13/22] Cythonizing /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5g.pyx
  [14/22] Cythonizing /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5i.pyx
  [15/22] Cythonizing /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5l.pyx
  [16/22] Cythonizing /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5o.pyx
  [17/22] Cythonizing /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5p.pyx
  [18/22] Cythonizing /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5r.pyx
  [19/22] Cythonizing /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5s.pyx
  [20/22] Cythonizing /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5t.pyx
  [21/22] Cythonizing /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5z.pyx
  [22/22] Cythonizing /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/utils.pyx
  building 'h5py.defs' extension
  creating build/temp.macosx-10.6-intel-3.6
  creating build/temp.macosx-10.6-intel-3.6/private
  creating build/temp.macosx-10.6-intel-3.6/private/var
  creating build/temp.macosx-10.6-intel-3.6/private/var/folders
  creating build/temp.macosx-10.6-intel-3.6/private/var/folders/v_
  creating build/temp.macosx-10.6-intel-3.6/private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn
  creating build/temp.macosx-10.6-intel-3.6/private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T
  creating build/temp.macosx-10.6-intel-3.6/private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly
  creating build/temp.macosx-10.6-intel-3.6/private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py
  creating build/temp.macosx-10.6-intel-3.6/private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py
  /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -DH5_USE_16_API -I/private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/lzf -I/opt/local/include -I/usr/local/include -I/Users/andrey/keras/lib/python3.6/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/defs.c -o build/temp.macosx-10.6-intel-3.6/private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/defs.o
  In file included from /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/defs.c:444:
  In file included from /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/api_compat.h:26:
  In file included from /Users/andrey/keras/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4:
  In file included from /Users/andrey/keras/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
  In file included from /Users/andrey/keras/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1777:
  /Users/andrey/keras/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
  #warning "Using deprecated NumPy API, disable it by " \
   ^
  In file included from /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/defs.c:444:
  /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/api_compat.h:27:10: fatal error: 'hdf5.h' file not found
  #include "hdf5.h"
           ^
  1 warning and 1 error generated.
  error: command '/usr/bin/clang' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for h5py
  Running setup.py clean for h5py
Failed to build h5py
Installing collected packages: h5py
  Running setup.py install for h5py ... error
    Complete output from command /Users/andrey/keras/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-_wc3_5lt-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/andrey/keras/bin/../include/site/python3.6/h5py:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-3.6
    creating build/lib.macosx-10.6-intel-3.6/h5py
    copying h5py/__init__.py -> build/lib.macosx-10.6-intel-3.6/h5py
    copying h5py/highlevel.py -> build/lib.macosx-10.6-intel-3.6/h5py
    copying h5py/ipy_completer.py -> build/lib.macosx-10.6-intel-3.6/h5py
    copying h5py/version.py -> build/lib.macosx-10.6-intel-3.6/h5py
    creating build/lib.macosx-10.6-intel-3.6/h5py/_hl
    copying h5py/_hl/__init__.py -> build/lib.macosx-10.6-intel-3.6/h5py/_hl
    copying h5py/_hl/attrs.py -> build/lib.macosx-10.6-intel-3.6/h5py/_hl
    copying h5py/_hl/base.py -> build/lib.macosx-10.6-intel-3.6/h5py/_hl
    copying h5py/_hl/dataset.py -> build/lib.macosx-10.6-intel-3.6/h5py/_hl
    copying h5py/_hl/datatype.py -> build/lib.macosx-10.6-intel-3.6/h5py/_hl
    copying h5py/_hl/dims.py -> build/lib.macosx-10.6-intel-3.6/h5py/_hl
    copying h5py/_hl/files.py -> build/lib.macosx-10.6-intel-3.6/h5py/_hl
    copying h5py/_hl/filters.py -> build/lib.macosx-10.6-intel-3.6/h5py/_hl
    copying h5py/_hl/group.py -> build/lib.macosx-10.6-intel-3.6/h5py/_hl
    copying h5py/_hl/selections.py -> build/lib.macosx-10.6-intel-3.6/h5py/_hl
    copying h5py/_hl/selections2.py -> build/lib.macosx-10.6-intel-3.6/h5py/_hl
    creating build/lib.macosx-10.6-intel-3.6/h5py/tests
    copying h5py/tests/__init__.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests
    copying h5py/tests/common.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests
    creating build/lib.macosx-10.6-intel-3.6/h5py/tests/old
    copying h5py/tests/old/__init__.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
    copying h5py/tests/old/common.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
    copying h5py/tests/old/test_attrs.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
    copying h5py/tests/old/test_attrs_data.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
    copying h5py/tests/old/test_base.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
    copying h5py/tests/old/test_dataset.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
    copying h5py/tests/old/test_datatype.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
    copying h5py/tests/old/test_dimension_scales.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
    copying h5py/tests/old/test_file.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
    copying h5py/tests/old/test_group.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
    copying h5py/tests/old/test_h5.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
    copying h5py/tests/old/test_h5f.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
    copying h5py/tests/old/test_h5p.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
    copying h5py/tests/old/test_h5t.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
    copying h5py/tests/old/test_objects.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
    copying h5py/tests/old/test_selections.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
    copying h5py/tests/old/test_slicing.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/old
    creating build/lib.macosx-10.6-intel-3.6/h5py/tests/hl
    copying h5py/tests/hl/__init__.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/hl
    copying h5py/tests/hl/test_attribute_create.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/hl
    copying h5py/tests/hl/test_dataset_getitem.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/hl
    copying h5py/tests/hl/test_dataset_swmr.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/hl
    copying h5py/tests/hl/test_datatype.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/hl
    copying h5py/tests/hl/test_dims_dimensionproxy.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/hl
    copying h5py/tests/hl/test_file.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/hl
    copying h5py/tests/hl/test_threads.py -> build/lib.macosx-10.6-intel-3.6/h5py/tests/hl
    running build_ext
    /Users/andrey/keras/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py:30: UserWarning: Cython.Distutils.old_build_ext does not properly handle dependencies and is deprecated.
      "Cython.Distutils.old_build_ext does not properly handle dependencies "
    Autodetection skipped [dlopen(libhdf5.so, 6): image not found]
    ********************************************************************************
                           Summary of the h5py configuration
    
        Path to HDF5: None
        HDF5 Version: '1.8.4'
         MPI Enabled: False
    Rebuild Required: False
    
    ********************************************************************************
    Executing cythonize()
    ./h5py/api_types_ext.pxd: cannot find cimported module 'mpi4py.MPI'
    /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5p.pyx: cannot find cimported module 'mpi4py.mpi_c'
    /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/h5p.pyx: cannot find cimported module 'mpi4py.libmpi'
    building 'h5py.defs' extension
    creating build/temp.macosx-10.6-intel-3.6
    creating build/temp.macosx-10.6-intel-3.6/private
    creating build/temp.macosx-10.6-intel-3.6/private/var
    creating build/temp.macosx-10.6-intel-3.6/private/var/folders
    creating build/temp.macosx-10.6-intel-3.6/private/var/folders/v_
    creating build/temp.macosx-10.6-intel-3.6/private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn
    creating build/temp.macosx-10.6-intel-3.6/private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T
    creating build/temp.macosx-10.6-intel-3.6/private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly
    creating build/temp.macosx-10.6-intel-3.6/private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py
    creating build/temp.macosx-10.6-intel-3.6/private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -DH5_USE_16_API -I/private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/lzf -I/opt/local/include -I/usr/local/include -I/Users/andrey/keras/lib/python3.6/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/defs.c -o build/temp.macosx-10.6-intel-3.6/private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/defs.o
    In file included from /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/defs.c:444:
    In file included from /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/api_compat.h:26:
    In file included from /Users/andrey/keras/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /Users/andrey/keras/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
    In file included from /Users/andrey/keras/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1777:
    /Users/andrey/keras/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by " \
     ^
    In file included from /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/defs.c:444:
    /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/h5py/api_compat.h:27:10: fatal error: 'hdf5.h' file not found
    #include "hdf5.h"
             ^
    1 warning and 1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/Users/andrey/keras/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-_wc3_5lt-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/andrey/keras/bin/../include/site/python3.6/h5py" failed with error code 1 in /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-csnytrly/h5py/`

**Comment by andreabedini** [comment]
You need to the hdf5 library installed to compile h5py. See the [prerequisites](https://github.com/h5py/h5py#prerequisites). Personally I use http://brew.sh to install HDF5 on my laptop (running macOS).
