### ISSUE TITLE
"dictionary changed size during iteration" with Python 3

### ISSUE THREAD

**Issue by pitrou** [h5py/h5py#775]
This is happening randomly to us on some Travis CI builds.
See full traceback here:
https://travis-ci.org/dask/distributed/jobs/175780263#L1763

It happens when h5py tries to remove a "murdered identifier" when closing. `registry.items()` returns an iterator on Python 3, it should be wrapperd in a `list()`.

(what is a "murdered identifier"?)

See also https://github.com/h5py/h5py/issues/534#issuecomment-231385966

**Comment by pitrou** [comment]
What happens is certainly that a GC run is triggered during `nonlocal_close()`. Some ObjectID is then reaped (probably it was dangling on a reference cycle) and removed from the registry. I don't think there is any point in issueing a warning because of that.

**Comment by shoyer** [comment]
I've been getting occasional errors like this when running the xarray test suite locally using Python 3 / OS X. Thanks @pitrou for tracking this down!
