### ISSUE TITLE
scaleoffset filter does not preserve NaN float values

### ISSUE THREAD

**Issue by equaeghe** [h5py/h5py#783]
I found out that the scaleoffset filter does not preserve NaN values when applied to float data. It may be useful to mention this in the docs. It is not said explicitly in the HDF5 docs, but came up on their mailing list:

https://lists.hdfgroup.org/pipermail/hdf-forum_lists.hdfgroup.org/2015-January/008296.html

**Comment by tacaswell** [comment]
Closed by #959
