### ISSUE TITLE
Request for new upstream release

### ISSUE THREAD

**Issue by ghisvail** [h5py/h5py#784]
Dear h5py developers,

Debian is currently transitioning to HDF5 1.10 for its next stable version (scheduled early 2017, freeze on January). The current version of `h5py` packaged in Debian (v2.6.0) fails to test with HDF5 1.10 (see [DebianBug#846351](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=846351)). The bug submitter cherry-picked a patch from `master` to fix this.

Would you guys consider tagging a new release soon, for which we know official support for HDF5 1.10 has been validated? I also noticed that initial support for PyPy was recently introduced (but not tested?), which may also justify a new release.

**Comment by andreabedini** [comment]
@andrewcollette is there a checklist for releases anywhere?

**Comment by ghisvail** [comment]
I believe there never was. In the past, I used to request a new release in the issue tracker, like I am doing now. Perhaps in the future, you guys could use GitHub milestones to give a visual representation of what's left to be done.

**Comment by andreabedini** [comment]
@ghisvail define "you guys" ;-)

**Comment by ghisvail** [comment]
"Andrew Collette and contributors" :-)

**Comment by andreabedini** [comment]
![screen shot 2016-12-02 at 8 53 54 pm](https://cloud.githubusercontent.com/assets/69135/20834736/c6dd3608-b8d1-11e6-936f-d50403e44e3a.png) :-D (I can stop now)

**Comment by ghisvail** [comment]
Members of the h5py organization then? :-D

**Comment by andreabedini** [comment]
on a serious note, I have commit permissions but I don't have access to pypi, and I have never done a h5py release. Anyone from @h5py/team-h5py can comment?

**Comment by ghisvail** [comment]
A tagged release is enough on my end. I am primarily involved with the Debian packaging aspect of `h5py`.

**Comment by andrewcollette** [comment]
@andreabedini, I can add you to the PyPI system.  There isn't a checklist that I know of.  Matthew Brett has been providing binary wheels for OS X so you may want to check with him to coordinate a release.  He also has access to the PyPI repo.

**Comment by andrewcollette** [comment]
@andreabedini it looks like I will just need your PyPI username to add you as a maintainer.

**Comment by aragilar** [comment]
#779 should be fixed before doing a new release (otherwise building on windows is broken)

**Comment by andreabedini** [comment]
I had noticed your PR @aragilar, thanks!
@andrewcollette I can't guarantee any time to make a release. @tacaswell how are you going these days?

**Comment by tacaswell** [comment]
I can probably carve a day out to do a release.  I have a decent check list to do a mpl release, is there one for h5py (I am being lazy and asking instead of looking in the docs).

I am `thomas.caswell` on pypi.

**Comment by tacaswell** [comment]
@aragilar Thanks for cleaning up the things I broke on windows :sheep:

**Comment by andreabedini** [comment]
@tacaswell that would be great, there isn't a checklist that we know of.

**Comment by aragilar** [comment]
At a guess (based on the 2.5 release), bump versions as per https://github.com/h5py/h5py/commit/265a96c4849c12ba57cf4c47e67cd47fee8dc946, add "What's New", update `ANN.rst`, and tag a release.

I've added "What's New" for 2.5 and 2.6 in #807, something similar could be done for 2.7. I'm not sure about the `ANN.rst`, it doesn't appear to be used anywhere I can see. @andrewcollette Is the `ANN.rst` still used, and can it be replaced by the "What's New" content?

**Comment by tacaswell** [comment]
Is the next release 2.7 or 2.6.1?

**Comment by aragilar** [comment]
The number of commits since 2.6 is 108, more than 2.4->2.5 (82), but less than 2.5->2.6 (130), previous point releases seem to have ~10 commits, so 2.7 seems about right.

**Comment by tacaswell** [comment]
Support for a minor version of python was also dropped so it definitely should be h5py 2.7.

**Comment by tacaswell** [comment]
@ghisvail How soon do we have to have a tag ready / who do we need to plead with to get this in for the next debian?  

There are 2 outstanding PRs for 2.7 (one of which is a docs PR from me that I would like to not merge my self) and one that I am willing to merge, but would like someone else to look at.

**Comment by ghisvail** [comment]
> who do we need to plead with to get this in for the next debian?

That would be me.

The date for the freeze is set to the 5th of February, and packages now need to be staged for 10 days to migrate to the next release. So, mid-January should be the ultimate deadline for a package like `h5py` I believe.

**Comment by andrewcollette** [comment]
Hi everyone... sorry for my radio silence these past few weeks. @tacaswell, I have added you as a maintainer on the pypi account.

**Comment by davidslac** [comment]
@tacaswell , this is David as LCLS, works with @chrisvam. I read your post about a new h5py 2.7, the issue I ran into with h5py 2.6 was #742 but from the comments on that issue I think it is fixed.

**Comment by tacaswell** [comment]
@davidslac Can you test if your issue is fixed on current master?  It looks like it works for me with the test file you upload.

**Comment by tacaswell** [comment]
This is the only issue left for 2.7 so I am going to tag an rc :smile:

**Comment by davidslac** [comment]
Thanks for looking at that issue, it looks fixed, we're in shutdown/vacation until Wednesday.

**Comment by ghisvail** [comment]
I'll wait for the upload of 2.7 on PyPI then.

**Comment by tacaswell** [comment]
@ghisvail I am planning to upload the rc2 tonight (have all the wheels, just need to upload).  Is it worth starting to turn the debian process crank with the rc?

**Comment by tacaswell** [comment]
@ghisvail The rc2 is up on pypi.

**Comment by tacaswell** [comment]
(rc1 exists as a tag, but I fouled up the versioning so it should be ignored)

**Comment by ghisvail** [comment]
I have pushed an update of the packaging with `2.7.0rc2`.

**Comment by ghisvail** [comment]
@tacaswell see #816 and #817 for the initial feedback.

**Comment by davidslac** [comment]
@tacaswell I've done some more extensive testing with h5py 2.7rc2, no problems.

**Comment by tacaswell** [comment]
As an update rc3 is tagged.

**Comment by ghisvail** [comment]
So in the end, `rc3` + #833 + #835 saved the day. Only arch still failing is `powerpc`, see [build log](https://buildd.debian.org/status/package.php?p=h5py). Thanks @mraspaud and the rest of the team for your work on this.

**Comment by mraspaud** [comment]
@ghisvail my pleasure. BTW I have a proper fix for the ppc64le, I submit a PR when #833 is merged. And when can wait until the next merge window for it.

**Comment by ghisvail** [comment]
> BTW I have a proper fix for the ppc64le

That's good news. If the commit is not too large, I'll be happy to roll it out on top of the packaging. Right now, it should rest as is for the mandatory 10 days in order to transition to the next stable release.

**Comment by tacaswell** [comment]
@ghisvail Have things settled enough to be sure we are good on the debian side?

**Comment by ghisvail** [comment]
Yes

**Comment by tacaswell** [comment]
Great, I will do a 2.7.0 final this weekend!

**Comment by mraspaud** [comment]
@tacaswell Any news on the release ? Anything in the way of the 2.7.0 ?

**Comment by tacaswell** [comment]
Me finding 2 hours of otherwise un-interrupted time.  Sorry for failing on this.

**Comment by mraspaud** [comment]
Ok. Tell me if I can be of any help.

**Comment by aragilar** [comment]
2.7 was released on 19th of March: https://github.com/h5py/h5py/releases/tag/2.7.0, closing.
