### ISSUE TITLE
When reading slicing dataset from h5py, does it read from file or from memory?

### ISSUE THREAD

**Issue by pswpswpsw** [h5py/h5py#786]
I am new to I/O with HDF5.

`import h5py`

`f = h5py.File('outputhdf001.h5','a')`

`dset=f.create_dataset('c_mas',(256,256,256), chunks=True, data=f['mas'].value)`

then I slice the code using `dset[0,:,:]`, does it read from file on the disk or read from memory?

That is an equivalent question of, is file handle just a information channel to the file on the desk, not reading the total data into memory. Right? I just want to know if it is true in HDF5. 

Thanks!
Shawn

**Comment by andreabedini** [comment]
It reads only the requested slice from disk.
