### ISSUE TITLE
store a list of strings as attribute fails in Python 3, succeeds in Python 2

### ISSUE THREAD

**Issue by prjemian** [h5py/h5py#796]
similar problem as #792,

This code works on Python 2 but fails on Python 3 with h5py 2.6.0:

	import h5py
	import tempfile
	hfile = tempfile.NamedTemporaryFile(suffix='.hdf5', delete=False)
	hfile.close()
	hdf5root = h5py.File(hfile.name, "w")
	entry = hdf5root.create_group("entry")
	entry.attrs['NX_class'] = 'NXentry'
	data = entry.create_group("data")
	data.attrs['NX_class'] = 'NXdata'
	data.attrs["signal"] = "data"
	data.attrs["axes"] = ["x", "y"]
	# FIXME: raises exception on py3, not py2
	# py3.5: TypeError: No conversion path for dtype: dtype('<U1')
	# py2.7: no error
	hfile.close()

	print(hfile.name)

It's crashing my unit testing now for python3.
https://github.com/prjemian/punx/issues/53#ref-commit-b2e60b0

**Comment by prjemian** [comment]
Taking advice from https://github.com/h5py/h5py/issues/792#issuecomment-265335687, this change fixes it for *both* Python2 and Python3:

        data.attrs["axes"] = [b"x", b"y"]

Thanks, @andreabedini.

**Comment by andreabedini** [comment]
The underlying problem is actually #624. h5py can't store strings in attributes full stop. It's Python 2's fault to blur the distinction between strings and byte arrays.
