### ISSUE TITLE
h5a.AttrID for an attribute through the high-level API

### ISSUE THREAD

**Issue by estan** [h5py/h5py#797]
First, thanks a lot for also offering a low-level API in addition to the high-level one.

In my case I'm making a small validation tool which validates a directory/file based storage format of ours. Among the things the tool has to do is to verify some constraints on HDF5 files (data type, dimensionality, size of datasets and attributes). In doing this, it's important that I can query the exact HDF5 type of a dataset or attribute, since we have tools in C/C++ that also must read these files, and they are more rigid than h5py, so the tool can't just inspect the numpy dtype and call it a day, but must know the underlying type.

For datasets I was able to use `data_set.id.get_type()` to get the low-level type for a high-level `Dataset`, and compare that to constants in `h5t`. But for attributes, I still haven't found a public API way to go from an attribute on a high-level `Dataset`, to a `AttrID` on which I could call `get_type` to get the low-level type.

I may have missed something, but if it's not possible, it would be great if it could be added. Perhaps as a new type of query method on `AttributeManager`?

**Comment by estan** [comment]
What I've found, through looking at `AttributeManager.__getitem__`, that I think might work, is something like `attr = h5a.open(data_set.id, data_set._e(name))`, which would give me the `AttrID`. But then I'd have to use the private `CommonStateObject._e` metod to encode the name properly :(

I would really like something like `AttributeManager.attr_id`, such that I could do `data_set.attrs.attr_id(name)`.

**Comment by aragilar** [comment]
@estan If you can provide a PR adding this, I'd be willing to look at it.

**Comment by estan** [comment]
Alright, I might have a go at it. It's been a while since I last looked at it.

**Comment by takluyver** [comment]
#1278 would add `ds.attrs.get_id(name)`
