### ISSUE TITLE
Unable to import h5py in py2.7 when filesystem encoding is not utf-8

### ISSUE THREAD

**Issue by wence-** [h5py/h5py#803]
Merging #800 broke importing h5py on python 2.7 when the filesystem encoding is not utf-8.  Although I suspect that the broken commit was fc9b8133.  The particular problem is the following.

If os.fsencode/decode do not exist, then _hl/compat.py defines:

```python
    encoding = sys.getfilesystemencoding()
    if encoding == 'mbcs':
        errors = 'strict'
    else:
        errors = 'surrogateescape'    
    def fsencode(filename):
        """
        Encode filename to the filesystem encoding with 'surrogateescape' error
        handler, return bytes unchanged. On Windows, use 'strict' error handler if
        the file system encoding is 'mbcs' (which is the default encoding).
        """
        if isinstance(filename, six.binary_type):
            return filename
        elif isinstance(filename, six.text_type):
            return filename.encode(encoding, errors)
        else:
            raise TypeError("expect bytes or str, not %s" % type(filename).__name__)
```

Py2.7 doesn't define the "surrogateescape" error handler:

```python
u'\u03b1'.encode("utf-8", "surrogateescape") => '\xce\xb1'
u'\u03b1'.encode("ANSI_X3.4-1968", "surrogateescape") => LookupError: unknown error handler name 'surrogateescape'
```

The python-future package does, but it's broken (PythonCharmers/python-future#256).  Assuming that's fixed, I guess one could do:

```python
from future.utils.surrogateescape import register_surrogateescape
register_surrogateescape()
```

In py2 mode in compat.py.

**Comment by aragilar** [comment]
The use of `fsencode` there explicitly for a different issue, so changing that is not a solution. I'm going to test making the encoding strict if we lack the surrogateescape handler, which should work fine on Python 2 (given the `fsencode`/`fsdecode` is there only for Python 2). I'm also going to add additional tests to travis to test `LC_ALL=C`, which should mean we catch this earlier.
