### ISSUE TITLE
Test for custom float promotion fails on some architectures

### ISSUE THREAD

**Issue by ghisvail** [h5py/h5py#816]
I refreshed the Debian packaging with version `2.7.0rc2`. This version [fails](https://buildd.debian.org/status/logs.php?pkg=h5py&ver=2.7.0~rc2-1) to test on selected architectures, some of which are considered major ones.

All failing architectures report the following error log:
```
======================================================================
FAIL: test_custom_float_promotion (h5py.tests.old.test_h5t.TestTypeFloatID)
Custom floats are correctly promoted to standard floats on read.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "h5py/tests/old/test_h5t.py", line 187, in test_custom_float_promotion
    self.assert_(values.dtype == np.float32)
AssertionError: False is not true

----------------------------------------------------------------------
```

**Comment by tacaswell** [comment]
Unfortunatly we don't get to see what type it really is 😞

**Comment by tacaswell** [comment]
attn @mraspaud

**Comment by tacaswell** [comment]
sparc64 seems to fail in very bad ways as well:

```
test_reference_numpyobj (h5py.tests.old.test_group.TestOpen)
Object can be opened by numpy.object_ containing object ref ... Bus error
```

**Comment by tacaswell** [comment]
For record the archs that fail in this way:  s390x, hppa, mips, powerpc, ppc64

**Comment by ghisvail** [comment]
`sparc64` was failing long before version 2.7 [1]. You can discard it from the investigation.

[1] https://buildd.debian.org/status/logs.php?pkg=h5py&arch=sparc64

**Comment by mraspaud** [comment]
I don't have access to these architectures unfortunately. Could you print out the type the data is actually promoted to ? And what is the endianess on these archs ?

**Comment by ghisvail** [comment]
I can run custom builds for `mips`, `ppc64el` and `s390x` but it is slow. I have modified the failing tests in `test_custom_float_promotion` to output a helpful error message. Of course, things would be better if `self.assertEqual` were consistently used throughout the test suite instead of the deprecated `self.assert_`.

**Comment by ghisvail** [comment]
Here are the results:

mips:
```
======================================================================
FAIL: test_custom_float_promotion (h5py.tests.old.test_h5t.TestTypeFloatID)
Custom floats are correctly promoted to standard floats on read.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "h5py/tests/old/test_h5t.py", line 188, in test_custom_float_promotion
    msg="{} != {}".format(values.dtype, np.float32))
AssertionError: <f4 != <type 'numpy.float32'>
```

ppc64el:
```

======================================================================
FAIL: test_write_direct_chunk (h5py.tests.old.test_h5d_direct_chunk_write.TestWriteDirectChunk)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "h5py/tests/old/test_h5d_direct_chunk_write.py", line 34, in test_write_direct_chunk
    self.assertTrue((array[i] == read_data).all())
AssertionError: False is not true

======================================================================
FAIL: test_custom_float_promotion (h5py.tests.old.test_h5t.TestTypeFloatID)
Custom floats are correctly promoted to standard floats on read.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "h5py/tests/old/test_h5t.py", line 211, in test_custom_float_promotion
    msg="{} != {}".format(dset.dtype, np.longdouble))
AssertionError: float64 != <type 'numpy.float128'>

======================================================================
FAIL: test_complex256 (h5py.tests.old.test_dataset.TestCreateShape)
Confirm that the default dtype is float
----------------------------------------------------------------------
Traceback (most recent call last):
  File "h5py/tests/old/test_dataset.py", line 101, in test_complex256
    self.assertEqual(dset.dtype, np.dtype('complex256'))
AssertionError: dtype('complex128') != dtype('complex256')

======================================================================
FAIL: test_long_double (h5py.tests.old.test_dataset.TestCreateShape)
Confirm that the default dtype is float
----------------------------------------------------------------------
Traceback (most recent call last):
  File "h5py/tests/old/test_dataset.py", line 94, in test_long_double
    self.assertEqual(dset.dtype, np.longdouble)
AssertionError: dtype('float64') != <type 'numpy.float128'>
```

s390x:
```
======================================================================
FAIL: test_custom_float_promotion (h5py.tests.old.test_h5t.TestTypeFloatID)
Custom floats are correctly promoted to standard floats on read.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "h5py/tests/old/test_h5t.py", line 188, in test_custom_float_promotion
    msg="{} != {}".format(values.dtype, np.float32))
AssertionError: <f4 != <type 'numpy.float32'>
```

**Comment by tacaswell** [comment]
I don't quite understand mips / s390x as

```
In [6]: np.dtype('f4') == np.float32
Out[6]: 
True
```

**Comment by tacaswell** [comment]
In https://buildd.debian.org/status/fetch.php?pkg=h5py&arch=powerpc&ver=2.7.0~rc2-1&stamp=1483740000 the `test_complex256` and `test_long_double` tests raised different exceptions (see https://github.com/h5py/h5py/issues/817#issuecomment-271051752)  What else did you change?

Sorry about the `assert_`, that got missed on review.

**Comment by ghisvail** [comment]
> What else did you change?

The custom builds are done on an amd64 server with a `qemu` setup to simulate other build architectures. The official build you linked was performed on a `powerpc` machine according to the log. There's your difference.

**Comment by mraspaud** [comment]
@tacaswell I'm also baffled by the `<f4 != <type 'numpy.float32'>` message

**Comment by ghisvail** [comment]
@mraspaud Perhaps because both `mips` and `s390x` are big-endian architectures? It tests fine on `mipsel` (and `mips64el`) which is little-endian.

**Comment by ghisvail** [comment]
@tacaswell 
> I don't quite understand mips / s390x as
```python
>>> np.dtype('f4') == np.float32
True
```

But there is a high chance that:
```python
>>> np.dtype('<f4') == np.float32
False
>>> np.dtype('>f4') == np.float32
True
```
Considering my comment above.

**Comment by mraspaud** [comment]
@ghisvail Indeed, I'll check it out

**Comment by tacaswell** [comment]
Ah, I completely miss-read that error message and thought the leading `<` was a pair with the final `>`!

**Comment by mraspaud** [comment]
@ghisvail I think the PR should solve the mips and s390x architectures

**Comment by ghisvail** [comment]
@mraspaud Ok, let me attempt a test build to validate it.

We would still need a fix for `ppc64el` since it is considered a major architecture and `h5py` used to build and test fine on it prior to version 2.7.

**Comment by mraspaud** [comment]
Yes I understand.

For the float64 != float128 error, I'm really confused, because I declare the dataset type as h5t.NATIVE_LDOUBLE, and compare it to np.longdouble. So it seems on ppc they are different ?

**Comment by ghisvail** [comment]
@mraspaud I have cherry-picked your commit onto the packaging and started new build on `mips`, `ppc64el` and `s390x`. I hope it will be done by the end of the day. Thanks for looking at it.

**Comment by ghisvail** [comment]
`s390x` passed, so I'd expect `mips` to follow through.

**Comment by ghisvail** [comment]
I have refreshed the packaging, here are the new [logs](https://buildd.debian.org/status/logs.php?pkg=h5py&ver=2.7.0~rc2-2).

**Comment by tacaswell** [comment]
To keep things organized, I am going to close this issue via #823 which fixes the native-endian related issues and leave #817 to track the bit-depth issues.
