### ISSUE TITLE
2.7.0rc2 reports 2.6.0 as version

### ISSUE THREAD

**Issue by davidslac** [h5py/h5py#820]
After making a local conda package out of h5py 2.7.0rc2, I get

```
In [1]: import h5py
In [2]: h5py.__version__
Out[2]: '2.6.0'
```
Maybe I made a mistake with my conda packaging, but I grepped through the 2.7.0rc2 source for the string 2.6.0, and I found it in a few places

```
./h5py/version.py:version = "2.6.0"
./docs/conf.py:release = '2.6.0'
```
while the 2.7.0 string shows up in

```
./setup.py:VERSION = '2.7.0rc2'
./PKG-INFO:Version: 2.7.0rc2
./h5py.egg-info/PKG-INFO:Version: 2.7.0rc2
```
Is this to be expected? release candidates don't report a proper version number?

**Comment by tacaswell** [comment]
This a PEBCAK on my part, sorry.

**Comment by tacaswell** [comment]
Leaving this open as a reminder to me of all the places that need to have their version manually changed:

 - setup.py
 - version.py
 - conf.py
