### ISSUE TITLE
all_filters_avail. h5py bug or HDF5 bug?

### ISSUE THREAD

**Issue by vasole** [h5py/h5py#843]
Related to #827

In my quest for a proper handling of missing filter plugins, I found what I considered to be a solution. However, it does not work as expected.

```
import hdf5plugin # set the path to the filters directory
import h5py
h = h5py.File("lz4.h5", "r")
d = h["/entry/data"]
dcpl = d.id.get_create_plist()
dcpl.get_nfilters()
-> Returns 1
dcpl.all_filters_avail()
-> Returns False
d[0, 0, 0] # Actually read the data
dcpl.all_filters_avail()
-> Returns True
```

As far as I understand the things, all_filters_avail() should look for all the available filters in the first call, if not it is pretty useless. Am I missing something?

**Comment by vasole** [comment]
I got some information worth to be shared.

**The short answer** is that if h5py calls the public H5Zfilter_avail API (and *not* the private API) then it should be fixed in h5py when it is built with HDF5-1.8.20/HDF5-1.10.2.

**The long answer**

The H5Pall_filters_avail API was introduced in HDF5-1.6, many years before development of dynamic plugins. Its purpose is to return the current filters that are registered in the pipeline.

The function to be used is H5Zfilter_avail will load and register any filters it cannot find, and this is what is needed for working with dynamic plugins. However, the H5Zfilter_avail API was not correctly organized
to find the plugins. This issue has been fixed for the upcoming releases:

 HDF5-1.8.20
 HDF5-1.10.2

**Comment by aparamon** [comment]
@vasole Indeed, h5py uses `H5Pall_filters_avail` in `all_filters_avail`.

The [documentation](https://support.hdfgroup.org/HDF5/doc/RM/RM_H5P.html#Property-AllFiltersAvail) for `H5Pall_filters_avail` is pretty ambiguous in regard to what it should do in case of dynamic filters. We might try to submit HDF5 library bug in an attempt to get the behavior changed.

But what is the intended use-case? Is it https://github.com/h5py/h5py/issues/827 or something different? I agree that current `all_filters_avail` is quite useless :-) but in my opinion it wouldn't be very useful even when fixed.

**Comment by vasole** [comment]
I encountered that problem when trying to find a set of HDF5 calls allowing me:

- to check if the needed filters to read a dataset are already available
- to load the missing filters if they are not available

That is the use case: to try to load filter plugins only if they are missing.

**Comment by aparamon** [comment]
@vasole Is it right that you'd like to resort to loading filters outside of `HDF5_PLUGIN_PATH` in case they cannot be found there? It seems that the effect can now be achieved via `H5PLappend()` and friends, but please correct me if I'm missing something.

**Comment by vasole** [comment]
Sorry, I missed your reply.

My first problem is that if I set the HDF5_PLUGIN_PATH once h5py is imported, the plugin filters are not loaded.

My ultimate goal is to provide a set of plugin filters only when needed.  Indeed it seems that the set of functions you mention should allow me to achieve my goal.

**Comment by aparamon** [comment]
@vasole Great!
Could you please take a look at https://github.com/h5py/h5py/pull/1166 and confirm it provides all desired machinery?

**Comment by vasole** [comment]
OK, I take a look.

**Comment by vasole** [comment]
#1166  provides the needed machinery. 

One can try to read a dataset and update the filter plugin path at will (append, insert, remove...)

Exactly what I was looking for. Thanks a lot!

**Comment by epourmal** [comment]
I added HDF5 JIRA issues to check documentation https://jira.hdfgroup.org/browse/HDFFV-10909

**Comment by aragilar** [comment]
I think #1166 and #1256 we can close this?
