### ISSUE TITLE
error: unrecognized command line option '-R'

### ISSUE THREAD

**Issue by sjackman** [h5py/h5py#845]
When building `h5py` I get the error message
```
cc -pthread -shared -L/home/linuxbrew/.linuxbrew/lib -Wl,--dynamic-linker=/home/linuxbrew/.linuxbrew/lib/ld.so -Wl,-rpath,/home/linuxbrew/.linuxbrew/lib -L/home/linuxbrew/.linuxbrew/lib -Wl,--dynamic-linker=/home/linuxbrew/.linuxbrew/lib/ld.so -Wl,-rpath,/home/linuxbrew/.linuxbrew/lib -Os -w -pipe -march=core2 -isystem/home/linuxbrew/.linuxbrew/include build/temp.linux-x86_64-2.7/tmp/pip-9a2PpU-build/h5py/defs.o -L/home/linuxbrew/.linuxbrew/opt/hdf5/lib -L/opt/local/lib -L/usr/local/lib -L/home/linuxbrew/.linuxbrew/Cellar/python/2.7.13/lib -R/home/linuxbrew/.linuxbrew/opt/hdf5/lib -R/opt/local/lib -R/usr/local/lib -lhdf5 -lhdf5_hl -lpython2.7 -o build/lib.linux-x86_64-2.7/h5py/defs.so
cc: error: unrecognized command line option '-R'
```
See the log at https://travis-ci.org/Homebrew/homebrew-science/builds/198707874#L2235
and this related issue https://github.com/Homebrew/homebrew-science/pull/5065

Perhaps the build script should be using `-Wl,-rpath` rather than `-R`?

**Comment by sjackman** [comment]
`cc -R` is not right. It should be either
`cc -Wl,-rpath`
or
`ld -rpath`

**Comment by aragilar** [comment]
I can't see any reason for h5py to choose an rpath (see setup_build.py), we use the standard cython setup, so any problems are either cython, or in your build environment (the `-R/home/linuxbrew/.linuxbrew/opt/hdf5/lib` part suggests to me the problem is in your build environment, but I have no knowledge of linuxbrew's setup).

**Comment by sjackman** [comment]
The `-R` options aren't coming from Linuxbrew. Linuxbrew uses `-Wl,-rpath` and you can see a number of those in the command line. I'm guessing that the `-R` options are coming from the Cython build system.
