### ISSUE TITLE
Crash on Windows 10, Python 3.5 and h5py 2.6

### ISSUE THREAD

**Issue by samerafach** [h5py/h5py#846]
We are facing exactly the same symptoms of #593 with Python 3.5 64-bit and h5py 2.6. A `create_dataset` command without a list wrapping the dataset name crashes the interpreter. Also we tried `h5py.run_tests()` and it works fine. We use Windows 10. This Windows used to crash on Windows 7, and then we upgraded to Windows 10, hoping that that would fix the problem.

This happens on a single computer which is used to run experiments, making debugging this issue very diffucult. Please advise.

**Comment by aragilar** [comment]
Which Python (Python.org download, Anaconda, etc.) and h5py (build from source, wheel from http://www.lfd.uci.edu/~gohlke/pythonlibs/, etc.) are you using?

**Comment by samerafach** [comment]
Anaconda 3.5, and installed with `conda install h5py`.

**Comment by aragilar** [comment]
Have you tried http://www.lfd.uci.edu/%7Egohlke/pythonlibs/#h5py? Or the version from https://anaconda.org/conda-forge/h5py? That may work as a workaround. I'm not sure about else can be done in h5py, other than file an issue with Anaconda (and mention it at https://github.com/ContinuumIO/anaconda-issues/issues/374), this seems to be a Anaconda-specific issue.

**Comment by samerafach** [comment]
We fixed the problem by formatting the computer and reinstalling Windows 10... I don't know what to say. Thanks for trying to help.
