### ISSUE TITLE
open h5 file by pandas

### ISSUE THREAD

**Issue by laughing429** [h5py/h5py#852]
Hi,
I create a h5 file using h5py.
but I use pandas to open it. 
like pandas.read_hdf('../test.h5', keys = 'd1), it will raise a problem.
ValueError: key must be provided when HDF file contains multiple datasets.

**Comment by aragilar** [comment]
This sounds like a problem on the pandas side, can you provide example code for both the reading and writing of the file?

**Comment by tacaswell** [comment]
This is definitly a pandas problem.  From looking at http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_hdf.html?highlight=read_hdf#pandas.read_hdf it looks like you need to use `key` not `keys`. 

If that does not solve your problem I suggest following up with pandas (stackoverflow or their mailing list)
