### ISSUE TITLE
Warning! ***HDF5 library version mismatched error***

### ISSUE THREAD

**Issue by engineeringmath** [h5py/h5py#853]
Hello,
I am sorry if I am missing something simple. I am not an experienced programmer. When trying to import h5py I get the following error. I use anaconda python on Ubuntu 16. My LD_LIBRARY_PATH was set to a VTK folder so I changed it to "/home/davood/anaconda2/lib:" but I get the same error. 
Any help is greatly appreciated.

Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.8.17, library is 1.8.15
	    SUMMARY OF THE HDF5 CONFIGURATION
	    =================================

General Information:
-------------------
		   HDF5 Version: 1.8.15-patch1
		  Configured on: Tue Aug 25 22:15:09 UTC 2015
		  Configured by: vagrant@localhost.localdomain
		 Configure mode: production
		    Host system: x86_64-unknown-linux-gnu
	      Uname information: Linux localhost.localdomain 2.6.18-398.el5 #1 SMP Tue Sep 16 20:50:52 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux
		       Byte sex: little-endian
		      Libraries: static, shared
	     Installation point: /home/vagrant/miniconda/envs/_build

Compiling Options:
------------------
               Compilation Mode: production
                     C Compiler: /home/vagrant/miniconda/envs/_build/bin/gcc ( gcc (GCC) 4.8.5)
                         CFLAGS: 
                      H5_CFLAGS: -std=c99 -pedantic -Wall -Wextra -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wnested-externs -Winline -Wfloat-equal -Wmissing-format-attribute -Wmissing-noreturn -Wpacked -Wdisabled-optimization -Wformat=2 -Wunreachable-code -Wendif-labels -Wdeclaration-after-statement -Wold-style-definition -Winvalid-pch -Wvariadic-macros -Winit-self -Wmissing-include-dirs -Wswitch-default -Wswitch-enum -Wunused-macros -Wunsafe-loop-optimizations -Wc++-compat -Wstrict-overflow -Wlogical-op -Wlarger-than=2048 -Wvla -Wsync-nand -Wframe-larger-than=16384 -Wpacked-bitfield-compat -Wstrict-overflow=5 -Wjump-misses-init -Wunsuffixed-float-constants -Wdouble-promotion -Wsuggest-attribute=const -Wtrampolines -Wstack-usage=8192 -Wvector-operation-performance -Wsuggest-attribute=pure -Wsuggest-attribute=noreturn -Wsuggest-attribute=format -O3 -fomit-frame-pointer -finline-functions
                      AM_CFLAGS: 
                       CPPFLAGS: 
                    H5_CPPFLAGS: -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_GNU_SOURCE -D_POSIX_C_SOURCE=200112L   -DNDEBUG -UH5_DEBUG_API
                    AM_CPPFLAGS: -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE  -I/home/vagrant/miniconda/envs/_build/include
               Shared C Library: yes
               Static C Library: yes
  Statically Linked Executables: no
                        LDFLAGS: 
                     H5_LDFLAGS: 
                     AM_LDFLAGS:  -L/home/vagrant/miniconda/envs/_build/lib
 	 	Extra libraries: -lrt -lz -ldl -lm 
 		       Archiver: ar
 		 	 Ranlib: ranlib
 	      Debugged Packages: 
		    API Tracing: no

Languages:
----------
                        Fortran: no

                            C++: yes
                   C++ Compiler: /home/vagrant/miniconda/envs/_build/bin/g++ ( g++ (GCC) 4.8.5)
                      C++ Flags: 
                   H5 C++ Flags:  
                   AM C++ Flags: 
             Shared C++ Library: yes
             Static C++ Library: yes

Features:
---------
                  Parallel HDF5: no
             High Level library: yes
                   Threadsafety: no
            Default API Mapping: v18
 With Deprecated Public Symbols: yes
         I/O filters (external): deflate(zlib)
                            MPE: no
                     Direct VFD: no
                        dmalloc: no
Clear file buffers before write: yes
           Using memory checker: no
         Function Stack Tracing: no
      Strict File Format Checks: no
   Optimization Instrumentation: no
Bye...

**Comment by aragilar** [comment]
This sounds like you've got two installs of HDF5, probably one from ubuntu and one from anaconda? How did you install h5py? I'd remove the LD_LIBRARY_PATH completely, unless you need it for the actual code you are running, as that's likely causing the problem.

**Comment by engineeringmath** [comment]
@aragilar Thank you so much for your comment. I actually solved it a minute ago by running:

conda install -c anaconda hdf5=1.8.17

**Comment by kingaj12** [comment]
Just a comment to reinforce @aragilar comment:  I had the same problem with an anaconda install of hdf5, and the issue was that there was an old Ubuntu hdf5 package.  I ran `apt-get upgrade; apt autoremove` and that cleaned out the old stuff.

**Comment by 7wik** [comment]
I have tried the below solution.
`import os 
os.environ['HDF5_DISABLE_VERSION_CHECK']='2'`
before importing tensorflow. It just suppressed the error, but I am not sure if it's safe to do so. Is doing this advisable?

**Comment by tacaswell** [comment]
@7wik no, this is not safe and you run the risk of data corruption and segfaults (as the warning says), but it might work.

**Comment by Miladiouss** [comment]
I was able to solve this by doing the following ([as suggested here](https://github.com/tensorflow/tensorflow/issues/8627)):
```
conda uninstall hdf5
conda install hdf5
```

**Comment by oxhaowang** [comment]
*To those of you whose python packages not managed by Conda experiencing the same issue*

Had the same issue recently on a Mac machine, except that the header version is older than the library: 


> Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.10.4, library is 1.10.5


- The hdf5 library on my Mac machine is managed by homebrew:  __brew upgrade hdf5__

- Python packages are managed by pip and  *h5py* package version is 2.9.0

Checked a few online discussions, my guess was that the older headers was installed by other packages, in the end I was able to __resolve this issue by upgrading *pytables*__

`sudo -H pip3 install tables -U`

**Comment by tacaswell** [comment]
I strongly discourage the use of `sudo pip ...`.  Typically the root python is managed by some package system (homebrew, macports, linux OS, ...) that will have it's own packaging of {h5py, hdf5, pytables}.  By using the underlying system for some installations and `pip` for others you will end up in weird conflicting states like this where each of the packaging systems thinks it is happy, but your enviroment is broken.

**Comment by BonneyBB** [comment]
pip uninstall h5py
pip install h5py
This way work, I had try.

**Comment by Amy-hh-711** [comment]
点击卸载再重装我试过了还是不行  降级我也试过了，仍旧报错
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.10.2, library is 1.10.5

**Comment by oahcy** [comment]
> pip uninstall h5py
> pip install h5py
> This way work, I had try.

that worked for me , when i import tensorflow,show this err, and python croedumped on win7

**Comment by Kiesh** [comment]
> pip uninstall h5py
> pip install h5py
> This way work, I had try.

**Comment by PickledBeef** [comment]
pip uninstall h5py(u may run this multiple times if u are not sure if there are multiple versions installed. )
pip install h5py
IDK why. But it works!

**Comment by xxzbg** [comment]
> > pip卸载h5py 
> > pip安装h5py 
> > 这样工作，我尝试过。
> 
> 这对我有用，当我导入tensorflow时，显示此错误，并且在win7上pythoncroedumped



> I was able to solve this by doing the following ([as suggested here](https://github.com/tensorflow/tensorflow/issues/8627)):
> 
> ```
> conda uninstall hdf5
> conda install hdf5
> ```

thanks for you!

**Comment by sinberlin2** [comment]
> pip uninstall h5py
> pip install h5py
> This way work, I had try.

I just uninstall h5py on pip, and kept conda version

**Comment by hzitoun** [comment]
> pip uninstall h5py
> pip install h5py
> This way work, I had try.

Works great!!!

**Comment by NaveenKY** [comment]
I am still getting this issue. I have tried uninstalling both h5py and hdf5 and still same issue.
When i do this i get hdf5 version 1.10.4
But my project is using xarray, zarr, dask and when i install those it gets updated to 1.10.5

**Comment by roysuman23** [comment]
worked for me kool

**Comment by sodinfeliz** [comment]
> pip uninstall h5py
> pip install h5py
> This way work, I had try.

it also works for me!! thanks~

**Comment by ctivanovich** [comment]
For me as well, the major issue was that both pip and conda had separate h5py installations, and possibly libraries and dependencies for tensorflow were split between the two. The pip version was pointing to an imaginary hdf5 installation, and most likely it was out of date but being imported by the library I was trying to use (tensorboard).

**Comment by Naz422** [comment]
hi everyone,
I am new bee in python. When i tried to change my data set into .h format I got the following error: 

Traceback (most recent call last):
  File "h5py.py", line 2, in <module>
    import h5py
  File "/content/drive/MyDrive/implementation/X-Net-master/h5py.py", line 6, in <module>
    with h5py.File(h5path, 'w') as hdf: 
AttributeError: module 'h5py' has no attribute 'File'
 emm searching since 2 days but still no useful info i got regarding this error.So anyone can guide me to what should i try?? and 
i am working on google colab and i also attached my code file below:
[mycode.zip](https://github.com/h5py/h5py/files/5684689/mycode.zip)
 .

**Comment by qblz** [comment]
我的是头新于库，各种方法居然都不行。真是头大了
