### ISSUE TITLE
Missing file error message misleadingly turned to lowercase

### ISSUE THREAD

**Issue by fsteinmetz** [h5py/h5py#854]
When trying to open a non-existing file, such as
`h5py.File('FOO.h5', 'r')  # note the uppercase`
The returned error message is:
`OSError: Unable to open file (Unable to open file: name = 'foo.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)`
The fact that the error message mentions `foo.h5` in lowercase is extremely misleading. It is even more the case if the file foo.h5 actually exists.
The same happens when providing an absolute path: it is changed to lowercase.

**Comment by aragilar** [comment]
Which OS is this?

**Comment by fsteinmetz** [comment]
It's on Linux, h5py 2.6.0, hdf5 1.8.17, python 3.5 (all from Anaconda).

**Comment by aragilar** [comment]
Caused by https://github.com/h5py/h5py/blob/master/h5py/_errors.pyx#L123. This presumably breaks other error messages. We'll need to replace the str.capitalize with something else.

**Comment by andreabedini** [comment]
I wonder what's the reason behind capitalising ... 🤔

**Comment by aragilar** [comment]
Also, the decoding as UTF-8 will produce mojibake on windows, but that's another issue.

In any case, dropping the str.capitalize calls is a quick fix. We may also want to look at using more of the Python 3 exception hierarchy (https://docs.python.org/3/library/exceptions.html#exception-hierarchy), while making sure we don't break backwards compatibility.

**Comment by MaxNoe** [comment]
This is **really** annoying. Especially for `KeyError`s concerning groups or datasets. Please fix this.

**Comment by Leedehai** [comment]
Yeah it's indeed annoying..

**Comment by DanlanChen** [comment]
you can upgrade your h5py package, it is resolved now.

**Comment by WrathofBhuvan11** [comment]
> you can upgrade your h5py package, it is resolved now.

No I still have that problem

**Comment by JinghangLi** [comment]
> I'm using the most upgraded version of h5py, @fsteinmetz I was facing the same problem and I tried renaming that file( all to lower cases) the problem still persisted. I've found out my problem now: When I was doing this: func('gen') ,the error showed
> 
> But,then I changed it to: fileName='gen' func(fileName) and it worked! :) But,I'm not sure why??

I had the same problem and the error disappeared when I used this method. Then I did a little deeper research and switched to the following code, which also did not report errors, and I guess it might have something to do with the type of data read in by fun().
```
    with h5py.File('re_event_left.h5', 'w') as f:
        save_events = f.create_group('events')
        save_events['p'] = np.array(left_event.events['p'])
```
I got error, but when I add str(), the error disappeared.
```
    with h5py.File(str('re_event_left.h5'), 'w') as f:
        save_events = f.create_group('events')
        save_events['p'] = np.array(left_event.events['p'])
```
