### ISSUE TITLE
Warn when the version of HDF5 used does not match the version h5py was compiled against

### ISSUE THREAD

**Issue by aragilar** [h5py/h5py#856]
As there is no Windows support in https://github.com/h5py/h5py/blob/master/setup_configure.py#L187, it's possible to have h5py be confused which version of HDF5 it's using (as it's possible to get the version of HDF5 from the dll, that's usually used over the h5py complied in version). We should warn when there is an conflict (See #855 and https://github.com/conda-forge/h5py-feedstock/pull/20).

**Comment by rmvanhees** [comment]
The warning does not work form me, running Python3 on MaxOS 10.12, compiling h5py against HDF5 1.10.0 (homebrew).

   Python 3.6.1 (default, Mar 23 2017, 16:49:06) 
   [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
   Type "help", "copyright", "credits" or "license" for more information.
   >>> import h5py
   Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
     File "/usr/local/lib/python3.6/site-packages/h5py-2.7.0.post0-py3.6-macosx-10.12-x86_64.egg/h5py/__init__.py", line 67, in <module>
       '.'.join(version.hdf5_version_tuple),
   TypeError: sequence item 0: expected str instance, int found

Please replace:
            '.'.join(version.hdf5_version_tuple),
            '.'.join(version.hdf5_built_version_tuple)
By something like: 
            '{0}.{1}.{2}'.format(*version.hdf5_version_tuple),
            '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)

Best regards,
Richard

**Comment by tacaswell** [comment]
@rmvanhees Can you open a pull request with that change?
