### ISSUE TITLE
Deadlock between import lock and h5py lock

### ISSUE THREAD

**Issue by pitrou** [h5py/h5py#859]
On Python 2.7, there can be a deadlock between the Python import lock (Python 2 has a global import lock, unlike Python 3) and the h5py global lock (named `phil` in the source code). This is triggered by such snippets (here in `h5py/_hl/base.py`):
```
    @property
    @with_phil
    def attrs(self):
        """ Attributes attached to this object """
        from . import attrs
        return attrs.AttributeManager(self)
```

Specifically, you can have:
* thread A took the import lock and is trying to call a h5py API
* thread B calls the `.attrs` property above

Depending on the timing, you can get a situation where thread A has the import lock and blocks trying to take the h5py lock, while thread B has the h5py lock and blocks trying to take the import lock (because of the `from . import attrs` statement). This is a real-world case we witness at one of our customers, who has some frozen Dask worker processes after some time of heavy h5py usage.

This could be solved by adopting a slightly different idiom in h5py, namely replace snippets like the above with:
```
    @property
    def attrs(self):
        """ Attributes attached to this object """
        from . import attrs
        with phil:
            return attrs.AttributeManager(self)
```

**Comment by pitrou** [comment]
If you're curious why "thread A" in the above summary may be trying to call a h5py API after taking the import lock, the actual explanation is that thread A first starts executing an unrelated import statement, garbage collection happens during that statement (i.e. with the import lock taken), and the GC triggers deletion of a h5py object, calling the `ObjectID.__dealloc__` method which needs to take the `phil` lock.

**Comment by tacaswell** [comment]
Is there a good reason why we are doing local imports like that?  Would it be simpler to just move those to the top level?

**Comment by tacaswell** [comment]
:sheep: because we have circular imports, that is why they are local.
