### ISSUE TITLE
Install h5py without internet

### ISSUE THREAD

**Issue by sachinzgupta** [h5py/h5py#869]
To assist reproducing bugs, please include the following:
 * Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 16.04.2 LTS, CentOS 7) - RHEL7.1
 * Python version (e.g. 2.7, 3.5)  - Python 2.7
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows): python on RHEL7.1
 * h5py version (e.g. 2.6) : 2.7
 * HDF5 version (e.g. 1.8.17) : 1.8 (SO.8) 
 * The full traceback/stack trace shown (if it appears)

`h5py.version.info` contains the needed versions, which can be displayed by
```
python -c 'import h5py; print(h5py.version.info)'
```
where `python` should be substituted for the path to python used to install
`h5py` with.

We are unable to install the h5py on the machine without internet connectivity.
Please let me know, if there is any guidlines or way to install the h5py with all dependencies without internet connectivity.

Thanks
Sachin Gupta

**Comment by aragilar** [comment]
Which OS are you trying to install on? How did you install python?

**Comment by aragilar** [comment]
On Red Hat, you'll need to have HDF5 installed (hdf5-devel, or the associated mpi packages if you want MPI support) as well as python(2,3)-devel. If you lack some way of running a PyPI mirror/clone/private instance such that pip install won't work, you need to install the build dependencies by hand, which can be seen at https://github.com/h5py/h5py/blob/master/setup.py#L35, currently numpy, cython, six and pkgconfig.
