### ISSUE TITLE
multiple calls to __getitem__ return different objects

### ISSUE THREAD

**Issue by spalato** [h5py/h5py#877]
Retrieving h5py objects using dict-like syntax always return a different Python object, which can cause memory issues when used alongside other C++ libraries (such as Qt). This could be fixed by having the h5py objects keeping references internally, and returning from this cache when possible.

Multiple calls to `group['item']` result in different objects. This can be seen by comparing their ids, or by using `is`:
```python
>>> import h5py
>>> import numpy as np
>>> f = h5py.File("foo.h5")
>>> g0 = f.create_group("bar")
>>> g0
<HDF5 group "/bar" (0 members)>
>>> id(g0)
34757488
>>> g1  =f['bar']
>>> id(g1)
36443152
>>> g0 is g1
False
>>> g1 is f['bar']
False
```
This is also true for datasets:
```
>>> g0.create_dataset("x", data=np.zeros((3,)))
<HDF5 dataset "x": shape (3,), type "<f8">
>>> d0 = g0['x']
>>> d0 is g0['x']
False
>>> id(d0)
62631344
>>> d1 = g0['x']; id(d1)
62631472
>>> d0 is d1
False
>>> f['bar']['x'] is d0
False
```
This is generally fine, as both objects represent the same data and never go out of sync:
```python
>>> d0[0] = 1
>>> d1[:]
array([ 1.,  0.,  0.])
>>> f['bar']['x'][:]
array([ 1.,  0.,  0.])
>>> f['bar']['x'] == d0
True
```
So far so good. However, this can cause important problems when using h5py in tandem with other C libraries, such as Qt: an object that gets created by h5py, passed to python and then to Qt will be garbage collected. All sorts of ugly crashes ensue.

This will happen, for exemple, when using a subclass of `QAbstractItemModel` to build a `TreeView` of the hdf5 file, and using `QModelIndex.internalPointer` to pass the h5py groups around. One cannot simply keep references to the group and dataset objects: new ones get created all the time and this would result in large memory consumption. The solution is to keep a cache by name, with the added burden of ensuring synchronization in client code.

Is there currently a way to prevent garbage collection, or to obtain behavior similar to this caching of h5py instances?

If not, it would be useful to have h5py objects offer this kind of caching behavior, maybe by maintaining an internal list of their children. This would prevent unwanted garbage collection, and let client code rely on object identity. H5py objects themselves are pretty small, so this should not result in a lot of memory consumption.

Version info:
OS: Windows 10
h5py    2.6.0
HDF5    1.8.16
Python  2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]
sys.platform    win32
sys.maxsize     2147483647
numpy   1.11.2

**Comment by tacaswell** [comment]
Are you passing c-pointers from hdf5 via h5py back down into Qt or are you passing in a pointer to the h5py object?

In either case something that is officially supported. For the first on the h5py side, it is for exactly these reasons, you loose track of who has a reference to the underlying c++ objects, either h5py does not clean up (which leaks) or it does (which breaks this usecase).    In the second I am pretty sure that is something that cpython discourages (as you are keeping a pointer from it's managed space).

If you do want to do this I would say it is your responsibility to keep the python object alive (either hold a reference to it or manually incr it's ref count).

Luckily, all of the h5py objects are proxy objects.  For example when you slice on the `Dataset` objects it does the hdf5 call then to get the data from the underlying file:

```python
In [1]: import h5py

In [2]: f = h5py.File('/tmp/test.h5')

In [3]: g = f.create_group('foo')

In [5]: d = g.create_dataset('bar', data=[1, 2, 3])

In [6]: d2 = g['bar']

In [7]: d[:]
Out[7]: array([1, 2, 3])

In [8]: d2[:]
Out[8]: array([1, 2, 3])

In [9]: d[1] = 15

In [10]: d2[:]
Out[10]: array([ 1, 15,  3])

In [11]: d is d2
Out[11]: False

In [12]: 
```

([4] is deleted because I miss-typed at it is a unrelated traceback)

Thus if you keep any reference to the `Dataset` alive, the syncing is taken care of for you.

**Comment by spalato** [comment]
Hi,

I am passing an `h5py.Group` object to `PySide.QtCore.QAbstractItemModel.createIndex`. The created `QModelIndex` keeps a pointer to the group (as `void *`). That would be close the second case: the reference count doesn't get incremented, resulting in garbage collection.

I thus need to keep references to all the object. Qt creates many of these (one for each item in the tree) on any actions, including mouseover moves. This results in the generation of 10s of indices per second when you navigate the tree. Since I don't know the life-cycle of the index, I can't destroy the references myself, and caching all the instances would be looking for trouble.

One could take advantage of the proxy behavior: a group is uniquely identified by name, and always references the same data so you would think the exact identity of the h5py object doesn't matter, and use the names to keep the cache at a reasonable level (say, in a dict). But this fails. The object identity matter: the same group object (ie: with the same name) is different for every call, so you would need to keep track of every different hdf5 object produced. If you index by name, the cache gets overwritten before Qt is done with the first index, the object gets gc'ed and the whole thing crashes.

Returning the same object for a given name would allow easier fixes for this category of problems. One solution is to maintain a shared cache (indexed by absolute path), and return already visited objects.
I'm not familiar with the complete HDF5 spec, but I have the impression that hardlinks and softlinks could cause issues as the cache goes out of sync. Of what kind? This, plus more complex usages such as SWMR and parallel hdf5 suggest it would be more general to feed that caching behavior in the h5py code itself.

I haven't tried grabbing the c-pointer to the underlying HDF5. How do you achieve this?

**Comment by tacaswell** [comment]
The documentation for the `createIndex` (https://srinikom.github.io/pyside-docs/PySide/QtCore/QAbstractItemModel.html#PySide.QtCore.PySide.QtCore.QAbstractItemModel.createIndex ) says that it is the users responsibility to keep the object alive.  

> caching all the instances would be looking for trouble.

h5py can not hold a reference to every object it creates for the exact same reason you are concerned about managing them.  h5py would have no way of knowing if the user had handed off a pointer and hence could never auto-close / clean up anything.


> I haven't tried grabbing the c-pointer to the underlying HDF5. How do you achieve this?

This is categorically not-supported, do not do that.

Can you provide a minimal example of what you are doing?

**Comment by spalato** [comment]
Just to say I haven't forgot this. I just can't find time right now (unlikely next week also).

I'll try providing a minimal example (PyQt+h5py won't make this exactly small).
I'll also try providing a naive caching solution, so we can see where it breaks.

**Comment by tacaswell** [comment]
I am going to close this as it has gone quiet.
