### ISSUE TITLE
Garbage Collection can still cause closing issues in python 3

### ISSUE THREAD

**Issue by jimwright** [h5py/h5py#888]
* Ubuntu 16.04.2 LTS
 * Python version 3.5.2
 * Standard Ubuntu packaged python, h5py and libhdf5 version
 * h5py version 2.6
 * HDF5 version 1.8.16

We have encountered an issue when converting some code from python2 to python3.  In particular the maintaining of the registry dictionary in h5py/_objects.pyx is not safe wrt garbage collection.  There have been various attempts to fix this already, including issue #775, however this is insufficient.

The remaining issue is that since python3, instances of classes that have a `__del__` method are eligible for cyclic garbage collection, whereas previously they were not.  This means that whilst executing `list(registry.items())` the cyclic garbage collector could be initiated, which can cause the registry dictionary to be modified.  Additionally this sometimes can even cause a segmentation violation - which was the behaviour that drew our attention to this issue.  I have distilled the problem down to the following simple example which closely mimics the registry maintenance code found in _objects.pyx.

I have separately raised as an issue the fact that the code below can cause a segfault with the core python team.  However, even if that is fixed, it is still possible for the registry dictionary to get mutated and an exception thrown when h5py is not expecting it.  We have worked around this issue for now by disabling garbage collection before closing our h5py objects.

--------

```python
#!/usr/bin/python3

class CyclicObject:
    def __init__(self, key, register):
        self.key = key
        self.self = self
        self.register = register
        self.register[self.key] = None

    def __del__(self):
        del self.register[self.key]

while True:
    register = { }
    objs = set([CyclicObject(i, register) for i in range(10000)])

    while len(objs) > 0:
        objs.remove(next(iter(objs)))

        try:
            list(register.items())
        except RuntimeError as err:
            print(err)
```

--------

```bash
$ python3 --version
Python 3.5.2

$ python3 ./segfault.py 
dictionary changed size during iteration
dictionary changed size during iteration
Segmentation fault
```

**Comment by tacaswell** [comment]
Can you try with h5py 2.7?  The fix for #775 (https://github.com/h5py/h5py/commit/2150ec97db9fd294392734a9dde2dff75c4492f4 ) is not in 2.6.

**Comment by jimwright** [comment]
Sorry I should have said, we have tried it with that too.  But the issue still exists.

**Comment by mdickinson** [comment]
> I have separately raised as an issue the fact that the code below can cause a segfault with the core python team.

For reference: http://bugs.python.org/issue30484
