### ISSUE TITLE
Address Overflow- Problem with opening hdf5 files

### ISSUE THREAD

**Issue by mkhoshle** [h5py/h5py#895]
I am trying to append a dataframe into a hdf5 file, in a for loop and here is part of my code (df is a pandas  dataframe with type float):
```
newchi1s = df 
with pd.HDFStore('fullpathtomyfile/chi1_angle.h5', 'a') as chi1s:
       chi1s.append('df', new_chi1s) 
```
The problem is that somewhere in my loop I get the following error and I do not know why?!!

```
original exception:HDF5 error back trace

  File "H5Dio.c", line 271, in H5Dwrite
    can't prepare for writing data
  File "H5Dio.c", line 352, in H5D__pre_write
    can't write data
  File "H5Dio.c", line 795, in H5D__write
    can't write data
  File "H5Dchunk.c", line 2006, in H5D__chunk_write
    unable to read raw data chunk
  File "H5Dchunk.c", line 2900, in H5D__chunk_lock
    unable to read raw data chunk
  File "H5Fio.c", line 120, in H5F_block_read
    read through metadata accumulator failed
  File "H5Faccum.c", line 263, in H5F__accum_read
    driver read request failed
  File "H5FDint.c", line 207, in H5FD_read
    addr overflow, addr = 3001503, size=75, eoa=3000871

End of HDF5 error back trace

Internal error modifying the elements (H5ARRAYwrite_records returned errorcode -6)
```
Here is the version of the packages I am using:
```
Summary of the h5py configuration
---------------------------------

h5py    2.7.0
HDF5    1.8.18
Python  2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]
sys.platform    linux2
sys.maxsize     9223372036854775807
numpy   1.12.1
```

**Comment by tacaswell** [comment]
This probably should go to the pandas bug tracker.

My naive guess is something (either the pd layer or the h5py layer) is not flushing to disk fully when exiting the context manager so the next time the file is opened it is in an inconsistent state.

**Comment by tacaswell** [comment]
Or pytables, I do not think pandas actually uses h5py under the hood at all.  I think the exception is coming from https://github.com/wesm/PyTables/blob/master/tables/hdf5Extension.pyx

Using:

```python
import pandas as pd
import numpy as np
import h5py  # unused, but checking if libraries are stepping on each other

new_chi1s = pd.DataFrame({'a': np.linspace(0, 1, 100)})

for j in range(100000):
    with pd.HDFStore('/tmp/chi1_angle.h5', 'a') as chi1s:
        chi1s.append('df', new_chi1s) 
```

I can not reproduce this error.

**Comment by tacaswell** [comment]
which ultimately goes back to https://github.com/PyTables/PyTables/blob/master/src/H5ARRAY.c#L344 which goes back to https://support.hdfgroup.org/HDF5/doc/RM/RM_H5D.html#Dataset-Write so something is going wrong at a very low level.

**Comment by tacaswell** [comment]
Closing and moving to https://github.com/pandas-dev/pandas/issues/16693
