### ISSUE TITLE
Trying to set a HDF5 dataset of type Reference with an RegionReference should probably raise a TypeError

### ISSUE THREAD

**Issue by leezu** [h5py/h5py#899]
Via https://github.com/h5py/h5py/issues/756#issuecomment-249035161:

> RegionReference and Reference objects are not equivalent, for instance they have different typesize (12 vs 8). Trying to set a HDF5 dataset of type Reference with an RegionReference should probably raise a TypeError.

Currently no error is raised until the user tries to load the reference from the dataset and tries to access the region. This will fail, as the RegionReference was not stored correctly.

However, the current behaviour is not good, as the error will only become obvious when accessing the data. It would be better to raise an error before the data is saved.

**Comment by tacaswell** [comment]
This seems to be a duplicate / comment on #756, closing this issue to move discussion back over there and keep it centralized.
