### ISSUE TITLE
Dataset size may overflow for large arrays on Windows

### ISSUE THREAD

**Issue by kitchoi** [h5py/h5py#901]
On Windows, `h5py.Dataset.size` may return negative values for large datasets:

```
>>> type(dataset)
h5py._hl.dataset.Dataset

>>> dataset.size
-1654967296

>>> dataset.shape
(7500000, 352)
```

This is caused by the default int being `int32` in numpy.
```
>>> import numpy
>>> numpy.prod((1000, 100, 1000, 100, 100))
-727379968
```
An easy fix would be to specify the `dtype` in `numpy.prod` when computing `size`.

**Comment by aragilar** [comment]
@kitchoi Can you produce a pull request fixing this (and testing it if possible)
