### ISSUE TITLE
h5py-2.7.0-cp27-cp27mu-manylinux1_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by brisker** [h5py/h5py#908]
To assist reproducing bugs, please include the following:
 * Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 16.04.2 LTS, CentOS 7) Ubuntu
 * Python version (e.g. 2.7, 3.5) 2.7
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows) system Python
 * h5py version (e.g. 2.6) 2.7
 * HDF5 version (e.g. 1.8.17) 1.8.11
 * The full traceback/stack trace shown (if it appears)
(I tried to install the whl which I directly downloaded from here: https://pypi.python.org/pypi/h5py/2.7.0 )
h5py-2.7.0-cp27-cp27m-manylinux1_x86_64.whl is not ok too
------------------------------------------------------------
/usr/bin/pip run on Fri Jul 14 22:45:28 2017
h5py-2.7.0-cp27-cp27mu-manylinux1_x86_64.whl is not a supported wheel on this platform.
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 257, in run
    InstallRequirement.from_line(name, None))
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 168, in from_line
    raise UnsupportedWheel("%s is not a supported wheel on this platform." % wheel.filename)
UnsupportedWheel: h5py-2.7.0-cp27-cp27mu-manylinux1_x86_64.whl is not a supported wheel on this platform.

`h5py.version.info` contains the needed versions, which can be displayed by
```
python -c 'import h5py; print(h5py.version.info)'
```
where `python` should be substituted for the path to python used to install
`h5py` with.

**Comment by aragilar** [comment]
This sounds like you're using i386 ubuntu rather than amd64 ubuntu, as it's pip stating that your system isn't compatible.
