### ISSUE TITLE
[Regression] Can't find filter

### ISSUE THREAD

**Issue by Kriechi** [h5py/h5py#923]
Tested on a fresh Ubuntu 16.04 with all latest updates.
python3.5, python3-pip, pkg-config, libhdf5-dev, and libhdf5-serial-dev installed via apt.
h5py 2.7.1 installed via pip3.
[bitshuffle](https://github.com/kiyo-masui/bitshuffle.git) installed via git-master clone and `python3 setup.py install --h5plugin`

```
Summary of the h5py configuration
---------------------------------

h5py    2.7.1
HDF5    1.8.18
Python  3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.13.1
```

When running the [example from the bitshuffle README](https://github.com/kiyo-masui/bitshuffle/blob/master/README.rst#example-h5py), I get the following error:
```
2.7.1
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 140544068683520:
  #000: ../../../src/H5Pocpl.c line 1102 in H5Pget_filter_by_id2(): can't find object for ID
    major: Object atom
    minor: Unable to find atom information (already closed?)
  #001: ../../../src/H5Pint.c line 3381 in H5P_object_verify(): property list is not a member of the class
    major: Property lists
    minor: Unable to register new atom
  #002: ../../../src/H5Pint.c line 3331 in H5P_isa_class(): not a property list
    major: Invalid arguments to routine
    minor: Inappropriate type
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-51fada684372> in <module>()
     15     compression=bitshuffle.h5.H5FILTER,
     16     compression_opts=(block_size, bitshuffle.h5.H5_COMPRESS_LZ4),
---> 17     dtype='float32',
     18     )
     19

/usr/local/lib/python3.5/dist-packages/h5py/_hl/group.py in create_dataset(self, name, shape, dtype, data, **kwds)
    104         """
    105         with phil:
--> 106             dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
    107             dset = dataset.Dataset(dsid)
    108             if name is not None:

/usr/local/lib/python3.5/dist-packages/h5py/_hl/dataset.py in make_new_dset(parent, shape, dtype, data, chunks, compression, shuffle, fletcher32, maxshape, compression_opts, fillvalue, scaleoffset, track_times)
    138
    139
--> 140     dset_id = h5d.create(parent.id, None, tid, sid, dcpl=dcpl)
    141
    142     if (data is not None) and (not isinstance(data, Empty)):

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5d.pyx in h5py.h5d.create()

ValueError: Unable to create dataset (error during user callback)
```

However, when I revert back to h5py==2.5.0, it works as expected and creates a file with the filter.
ref https://github.com/kiyo-masui/bitshuffle/issues/52

**Comment by Kriechi** [comment]
After some investigating with git-bisect and other tools, I now come to the conclusion that this is a problem with packaging / wheels.

When I install it with `pip3 install h5py`, I get above mentioned error.
When I install it with `python3 setup.py install` from a git checkout, it works with any tag: 2.5.0, 2.6.0, 2.7.1

**Comment by aragilar** [comment]
@Kriechi Can you try the following:
 - Install via wheel only: `pip install --no-cache .`
 - Install via both sdist and wheel: `python setup.py sdist && pip install --no-cache dist/h5py-{version}.tar.gz`
just to confirm this is a problem with the manylinux wheels, and not an inherent problem.

**Comment by Kriechi** [comment]
Both of these seem to work for me.
I ran `pip3 uninstall h5py` before every test.

**Comment by aragilar** [comment]
@Kriechi The version of HDF5 on your system is 1.8.16? I'm wondering what versions of HDF5 bitshuffle supports...

**Comment by Kriechi** [comment]
Ubuntu 16.04 ships with HDF5 1.8.18.
If I install `libhdf5-dev` via apt, and install h5py via `python3 setup.py install`, I get this:

```
Summary of the h5py configuration
---------------------------------

h5py    2.6.0
HDF5    1.8.16
Python  3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.13.1
```

However, if I install h5py via pip3, I get this:
```
Summary of the h5py configuration
---------------------------------

h5py    2.7.1
HDF5    1.8.18
Python  3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.13.1
```

Please note that the pip version uses HDF5 1.8.18 - which I do not have on my system...
I think the manylinux wheels are built against a "too" recent version of HDF5. 
IMO at least the last Ubuntu LTS should be targeted, if possible, unless there is a good reason (bug or incompatibilities in older versions of hdf5?)

**Comment by vasole** [comment]
The problem is the bitshuffle filter itself.  It is not properly built and creates a direct dependency on the version of the hdf5 library used when building it. I reported that some time ago but nothing seems to be done:

https://github.com/kiyo-masui/bitshuffle/issues/53

For instance, if you get rid of your HDF5 filter path and install the hdf5plugin module (pip install hdf5plugin) you will very likely be able to read bitshuffle compressed files:

https://groups.google.com/forum/#!topic/h5py/uM7ap8hJ5EI

**Comment by Kriechi** [comment]
Thanks you @vasole!
I have a working setup, but thanks for mentioning `hdf5plugin`.

If @aragilar agrees that this is an issue with bitshuffle (https://github.com/kiyo-masui/bitshuffle/issues/53), feel free to close this issue.
Thanks for the support!

**Comment by aragilar** [comment]
Based on the setup.py code in the bitshuffle repo, it looks like bitshuffle is building against your local HDF5, so I agree with @vasole in that this is a problem on bitshuffle's end (and looking at the setup.py does not fill me with confidence about it working well with manylinux wheels soon). However, the manylinux wheels h5py currently provides lack the headers to build against, which doesn't help here (h5py probably should provide some support for building against the version of HDF5 its built against, and some method of automatically loading installed filters).

@Kriechi I'd recommend following http://docs.h5py.org/en/latest/build.html#custom-installation when installing h5py in this case, using pip and the environment variables to configure.
