### ISSUE TITLE
Write h5py directly to GCS

### ISSUE THREAD

**Issue by dyngts** [h5py/h5py#925]
Dear h5py contributors,

is there any plan to support write hdf5 directly into GCS (Google Cloud Storage)? i encountering issue that my keras model (which use h5py to save the model) cannot store the model into GCS. Thank you!

**Comment by aragilar** [comment]
@dyngts I'm not aware of any support in HDF5 for writing to GCS, which is what would be required to allow h5py to add support for writing to GCS. If that's not the case (HDF5 has support for GCS), then we'd welcome a PR adding it to h5py.
