### ISSUE TITLE
Is there any way to load an entire HDF5 file to memory

### ISSUE THREAD

**Issue by mrozkamil** [h5py/h5py#929]
I try to load an entire hdf5 file to memory. The problem is that it contains a lot of datasets in various groups so I do not want to do it manually. With the following code 

`def printDatasets(name, obj):
    if isinstance(obj, h5py.Dataset):
        print (obj.name)
g = h5py.File(FileName,'r')
            g.visititems(printDatasets) `

I get: 

`/NS/HouseKeeping/delay
/NS/HouseKeeping/scdpFlagAB
/NS/HouseKeeping/sspaTemp
/NS/HouseKeeping/fcifFlagAB
/NS/HouseKeeping/vprfTableVersion
/NS/HouseKeeping/rxGain
/NS/HouseKeeping/catchingInt
/NS/HouseKeeping/seqCountL1A
/NS/HouseKeeping/rxAttGainOffset
/NS/HouseKeeping/scdpFlag
/NS/HouseKeeping/rdaTemp
/NS/HouseKeeping/fcifTemp
/NS/HouseKeeping/vprfTableSelect
/NS/HouseKeeping/fcifFlag
/NS/HouseKeeping/rxAtt
/NS/HouseKeeping/lnaTemp
/NS/HouseKeeping/scTime
/NS/HouseKeeping/divcomb2Temp
/NS/HouseKeeping/logAmpNoiseLevel
/NS/HouseKeeping/divcomb1Temp
/NS/HouseKeeping/binDiffPeakDEM
/NS/Calibration/fcifInPower
/NS/Calibration/intAttSelect
/NS/Calibration/sspaLnaSelect
/NS/Calibration/angleBinSelect
/NS/Longitude
/NS/Receiver/noiseCount
/NS/Receiver/echoPower
/NS/Receiver/noisePower
/NS/Receiver/echoSampleNumber
/NS/Receiver/noiseSampleNumber
/NS/Receiver/rxAntGain
/NS/Receiver/echoCount
/NS/Receiver/receivedPulseWidth
/NS/ScanTime/MilliSecond
/NS/ScanTime/Minute
/NS/ScanTime/Year
/NS/ScanTime/SecondOfDay
/NS/ScanTime/Second
/NS/ScanTime/DayOfYear
/NS/ScanTime/Hour
/NS/ScanTime/Month
/NS/ScanTime/DayOfMonth
/NS/rayPointing/rayDirectionY
/NS/rayPointing/instrumentYaw
/NS/rayPointing/instrumentPitch
/NS/rayPointing/rayDirectionX
/NS/rayPointing/instrumentRoll
/NS/rayPointing/rayTiming
/NS/rayPointing/scanAngle
/NS/Latitude
/NS/Transmitter/radarTransPower
/NS/Transmitter/transPulseWidth
/NS/Transmitter/txAntGain
/NS/navigation/scPos
/NS/navigation/timeMidScanOffset
/NS/navigation/scAttPitchGeod
/NS/navigation/scVel
/NS/navigation/scAttRollGeod
/NS/navigation/scAttRollGeoc
/NS/navigation/scAlt
/NS/navigation/scLon
/NS/navigation/scAttYawGeoc
/NS/navigation/scAttPitchGeoc
/NS/navigation/dprAlt
/NS/navigation/greenHourAng
/NS/navigation/scLat
/NS/navigation/scAttYawGeod
/NS/navigation/timeMidScan
/NS/scanStatus/operationalMode
/NS/scanStatus/modeStatus
/NS/scanStatus/targetSelectionMidScan
/NS/scanStatus/geoWarning
/NS/scanStatus/limitErrorFlag
/NS/scanStatus/pointingStatus
/NS/scanStatus/geoError
/NS/scanStatus/dataQuality
/NS/scanStatus/acsModeMidScan
/NS/scanStatus/missing
/NS/scanStatus/dataWarning
/NS/scanStatus/FractionalGranuleNumber
/NS/scanStatus/SCorientation
/NS/VertLocate/ratioLand
/NS/VertLocate/binDEM
/NS/VertLocate/alongTrackBeamWidth
/NS/VertLocate/ratioOcean
/NS/VertLocate/scRangeEllipsoid
/NS/VertLocate/scRangeDEM
/NS/VertLocate/echoLowResBinNumber
/NS/VertLocate/ratioInLand
/NS/VertLocate/binDEMHbottom
/NS/VertLocate/DEMHmean
/NS/VertLocate/crossTrackBeamWidth
/NS/VertLocate/mainlobeEdge
/NS/VertLocate/rangeBinSize
/NS/VertLocate/scLocalZenith
/NS/VertLocate/sidelobeRange
/NS/VertLocate/landOceanFlag
/NS/VertLocate/binEllipsoid
/NS/VertLocate/echoHighResBinNumber
/NS/VertLocate/binEchoPeak
/NS/VertLocate/ellipsoidBinOffset
/NS/VertLocate/startBinRange
/NS/VertLocate/binDEMHtop
/NS/VertLocate/ratioCoast
/MS/HouseKeeping/delay
/MS/HouseKeeping/scdpFlagAB
/MS/HouseKeeping/sspaTemp
/MS/HouseKeeping/fcifFlagAB
/MS/HouseKeeping/vprfTableVersion
/MS/HouseKeeping/rxGain
/MS/HouseKeeping/catchingInt
/MS/HouseKeeping/seqCountL1A
/MS/HouseKeeping/rxAttGainOffset
/MS/HouseKeeping/scdpFlag
/MS/HouseKeeping/rdaTemp
/MS/HouseKeeping/fcifTemp
/MS/HouseKeeping/vprfTableSelect
/MS/HouseKeeping/fcifFlag
/MS/HouseKeeping/rxAtt
/MS/HouseKeeping/lnaTemp
/MS/HouseKeeping/scTime
/MS/HouseKeeping/divcomb2Temp
/MS/HouseKeeping/logAmpNoiseLevel
/MS/HouseKeeping/divcomb1Temp
/MS/HouseKeeping/binDiffPeakDEM
/MS/Calibration/fcifInPower
/MS/Calibration/intAttSelect
/MS/Calibration/sspaLnaSelect
/MS/Calibration/angleBinSelect
/MS/Longitude
/MS/Receiver/noiseCount
/MS/Receiver/echoPower
/MS/Receiver/noisePower
/MS/Receiver/echoSampleNumber
/MS/Receiver/noiseSampleNumber
/MS/Receiver/rxAntGain
/MS/Receiver/echoCount
/MS/Receiver/receivedPulseWidth
/MS/ScanTime/MilliSecond
/MS/ScanTime/Minute
/MS/ScanTime/Year
/MS/ScanTime/SecondOfDay
/MS/ScanTime/Second
/MS/ScanTime/DayOfYear
/MS/ScanTime/Hour
/MS/ScanTime/Month
/MS/ScanTime/DayOfMonth
/MS/rayPointing/rayDirectionY
/MS/rayPointing/instrumentYaw
/MS/rayPointing/instrumentPitch
/MS/rayPointing/rayDirectionX
/MS/rayPointing/instrumentRoll
/MS/rayPointing/rayTiming
/MS/rayPointing/scanAngle
/MS/Latitude
/MS/Transmitter/radarTransPower
/MS/Transmitter/transPulseWidth
/MS/Transmitter/txAntGain
/MS/navigation/scPos
/MS/navigation/timeMidScanOffset
/MS/navigation/scAttPitchGeod
/MS/navigation/scVel
/MS/navigation/scAttRollGeod
/MS/navigation/scAttRollGeoc
/MS/navigation/scAlt
/MS/navigation/scLon
/MS/navigation/scAttYawGeoc
/MS/navigation/scAttPitchGeoc
/MS/navigation/dprAlt
/MS/navigation/greenHourAng
/MS/navigation/scLat
/MS/navigation/scAttYawGeod
/MS/navigation/timeMidScan
/MS/scanStatus/operationalMode
/MS/scanStatus/modeStatus
/MS/scanStatus/targetSelectionMidScan
/MS/scanStatus/geoWarning
/MS/scanStatus/limitErrorFlag
/MS/scanStatus/pointingStatus
/MS/scanStatus/geoError
/MS/scanStatus/dataQuality
/MS/scanStatus/acsModeMidScan
/MS/scanStatus/missing
/MS/scanStatus/dataWarning
/MS/scanStatus/FractionalGranuleNumber
/MS/scanStatus/SCorientation
/MS/VertLocate/ratioLand
/MS/VertLocate/binDEM
/MS/VertLocate/alongTrackBeamWidth
/MS/VertLocate/ratioOcean
/MS/VertLocate/scRangeEllipsoid
/MS/VertLocate/scRangeDEM
/MS/VertLocate/echoLowResBinNumber
/MS/VertLocate/ratioInLand
/MS/VertLocate/binDEMHbottom
/MS/VertLocate/DEMHmean
/MS/VertLocate/crossTrackBeamWidth
/MS/VertLocate/mainlobeEdge
/MS/VertLocate/rangeBinSize
/MS/VertLocate/scLocalZenith
/MS/VertLocate/sidelobeRange
/MS/VertLocate/landOceanFlag
/MS/VertLocate/binEllipsoid
/MS/VertLocate/echoHighResBinNumber
/MS/VertLocate/binEchoPeak
/MS/VertLocate/ellipsoidBinOffset
/MS/VertLocate/startBinRange
/MS/VertLocate/binDEMHtop
/MS/VertLocate/ratioCoast
/HS/HouseKeeping/delay
/HS/HouseKeeping/scdpFlagAB
/HS/HouseKeeping/sspaTemp
/HS/HouseKeeping/fcifFlagAB
/HS/HouseKeeping/vprfTableVersion
/HS/HouseKeeping/rxGain
/HS/HouseKeeping/catchingInt
/HS/HouseKeeping/seqCountL1A
/HS/HouseKeeping/rxAttGainOffset
/HS/HouseKeeping/scdpFlag
/HS/HouseKeeping/rdaTemp
/HS/HouseKeeping/fcifTemp
/HS/HouseKeeping/vprfTableSelect
/HS/HouseKeeping/fcifFlag
/HS/HouseKeeping/rxAtt
/HS/HouseKeeping/lnaTemp
/HS/HouseKeeping/scTime
/HS/HouseKeeping/divcomb2Temp
/HS/HouseKeeping/logAmpNoiseLevel
/HS/HouseKeeping/divcomb1Temp
/HS/HouseKeeping/binDiffPeakDEM
/HS/Calibration/fcifInPower
/HS/Calibration/intAttSelect
/HS/Calibration/sspaLnaSelect
/HS/Calibration/angleBinSelect
/HS/Longitude
/HS/Receiver/noiseCount
/HS/Receiver/echoPower
/HS/Receiver/noisePower
/HS/Receiver/echoSampleNumber
/HS/Receiver/noiseSampleNumber
/HS/Receiver/rxAntGain
/HS/Receiver/echoCount
/HS/Receiver/receivedPulseWidth
/HS/ScanTime/MilliSecond
/HS/ScanTime/Minute
/HS/ScanTime/Year
/HS/ScanTime/SecondOfDay
/HS/ScanTime/Second
/HS/ScanTime/DayOfYear
/HS/ScanTime/Hour
/HS/ScanTime/Month
/HS/ScanTime/DayOfMonth
/HS/rayPointing/rayDirectionY
/HS/rayPointing/instrumentYaw
/HS/rayPointing/instrumentPitch
/HS/rayPointing/rayDirectionX
/HS/rayPointing/instrumentRoll
/HS/rayPointing/rayTiming
/HS/rayPointing/scanAngle
/HS/Latitude
/HS/Transmitter/radarTransPower
/HS/Transmitter/transPulseWidth
/HS/Transmitter/txAntGain
/HS/navigation/scPos
/HS/navigation/timeMidScanOffset
/HS/navigation/scAttPitchGeod
/HS/navigation/scVel
/HS/navigation/scAttRollGeod
/HS/navigation/scAttRollGeoc
/HS/navigation/scAlt
/HS/navigation/scLon
/HS/navigation/scAttYawGeoc
/HS/navigation/scAttPitchGeoc
/HS/navigation/dprAlt
/HS/navigation/greenHourAng
/HS/navigation/scLat
/HS/navigation/scAttYawGeod
/HS/navigation/timeMidScan
/HS/scanStatus/operationalMode
/HS/scanStatus/modeStatus
/HS/scanStatus/targetSelectionMidScan
/HS/scanStatus/geoWarning
/HS/scanStatus/limitErrorFlag
/HS/scanStatus/pointingStatus
/HS/scanStatus/geoError
/HS/scanStatus/dataQuality
/HS/scanStatus/acsModeMidScan
/HS/scanStatus/missing
/HS/scanStatus/dataWarning
/HS/scanStatus/FractionalGranuleNumber
/HS/scanStatus/SCorientation
/HS/VertLocate/ratioLand
/HS/VertLocate/binDEM
/HS/VertLocate/alongTrackBeamWidth
/HS/VertLocate/ratioOcean
/HS/VertLocate/scRangeEllipsoid
/HS/VertLocate/scRangeDEM
/HS/VertLocate/echoLowResBinNumber
/HS/VertLocate/ratioInLand
/HS/VertLocate/binDEMHbottom
/HS/VertLocate/DEMHmean
/HS/VertLocate/crossTrackBeamWidth
/HS/VertLocate/mainlobeEdge
/HS/VertLocate/rangeBinSize
/HS/VertLocate/scLocalZenith
/HS/VertLocate/sidelobeRange
/HS/VertLocate/landOceanFlag
/HS/VertLocate/binEllipsoid
/HS/VertLocate/echoHighResBinNumber
/HS/VertLocate/binEchoPeak
/HS/VertLocate/ellipsoidBinOffset
/HS/VertLocate/startBinRange
/HS/VertLocate/binDEMHtop
/HS/VertLocate/ratioCoast `

Is there any way to save the list of datasets as alist and load all of them automatically?

**Comment by tacaswell** [comment]
I suggest doing this with `visit` or `visititems` http://docs.h5py.org/en/latest/high/group.html#Group.visit

https://stackoverflow.com/questions/31146036/how-do-i-traverse-a-hdf5-file-using-h5py

Can you follow up at https://groups.google.com/forum/#!forum/h5py ?  We try to keep github issues for bugs / feature requests and the google group for usage questions.
