### ISSUE TITLE
Parallel streaming of data with very high dimensions

### ISSUE THREAD

**Issue by brandon-white** [h5py/h5py#930]
I have a large dataset between 300G - 500G. The shape of this dataset is about (4000, 60000, 1000). As you can see, I don't have many rows but I have a very large number of columns and multiple dimensions. Couple of questions,

1) What H5 settings should I test out for data of this shape?
2) What is the best way to stream data of this kind, row by row, into a dataset?
3) Can the streaming be done using multiple threads or processes?
Right now, I am using something like the following:

```
numpy_arrays = [list of 4000 numpy arrays]
shape = (4000, 60000, 1000)
file = h5py.File(tmp_dir + 'matrix.hdf5', 'w')
arr = file.create_dataset('matrix', shape=shape, dtype=dtype)
def append(i, numpy_array):
  arr[i] = numpy_array
ThreadPool(NUM_THREADS).map(append, enumerate(numpy_arrays))
```

Really appreciate your time and brain space!

**Comment by aragilar** [comment]
If the numpy arrays are in memory, writing them all at once is the best way, as h5py/HDF5 is designed such that only one process is writing at the same time (it's possible to have some level of parallelism via MPI though), threading will most likely not work. It'd be worth asking on the mailing list (https://groups.google.com/forum/#!forum/h5py), as more people read the mailing list than check the issue tracker.

**Comment by vasole** [comment]
Just some hints for the open poster:

- External storage and/or
- Virtual Data Sets

Those should help to parallelize things, Even external links combined with virtual datasets might work.
