### ISSUE TITLE
Would an xpath equivalent make sense?

### ISSUE THREAD

**Issue by ftroude** [h5py/h5py#932]
I am a newbie at h5py and HDF5, please forgive me if my question doesn't make sense at all.
I am quite used to using XML in my daily job, and XPath helps me a lot finding the information I need, especially when my file is enormous and/or have a child levels.
HDF5 - by essence - enables to create complex hierarchies, but I didn't find any way in h5py to select a Group or DataSet rather than 'visiting' items recursively, and testing my condition.
Hence my question: would an XPath equivalent make sense in h5py?

**Comment by tacaswell** [comment]
I suspect that this is something that is better implemented at the hdf5 layer as without some indexing, it looks like the obvious way to implement this would be to just linearly walk the file, exactly as you are doing.

hdfql (https://www.hdfgroup.org/2016/06/hdfql-new-hdf-tool-speaks-sql/ ) might provide some of what you are looking for as might PyTables.

Are you using the `visit` method for this?

**Comment by ftroude** [comment]
Thanks for your answer. I did not know hdfql that could be a good option to select groups and datasets without walking the tree.
I am using visit and visititems methods for the 'descendant' axis, but for 'ancestor' axis or 'sibling' one, it requires smarter walking.
Thanks again for your time, I think you can close the thread.
