### ISSUE TITLE
h5py crashes opening d:file.hdf5

### ISSUE THREAD

**Issue by hjaGT** [h5py/h5py#939]
There is an issue reading files if the path contains a drive letter, i.e. **d:/file.hdf5 is fine, but d:file.hdf5 crashes**

**Demo code:**
```
import os.path   
import h5py

def demo(filepath):
    print(filepath, ": isFile is ", os.path.isfile(filepath))
    ff = h5py.File(filepath, mode='r')
    print("works fine, ", ff)
    print("---------------------------------------------")
    
demo('d:/file.hdf5')
demo('d:file.hdf5')
```

produces the following output:
```
d:/file.hdf5 : isFile is  True
works fine,  <HDF5 file "file.hdf5" (mode r)>
---------------------------------------------
d:file.hdf5 : isFile is  True
```

**System info:** 
Windows 10
h5py    2.7.1
HDF5    1.8.18
Python  3.6.2 |Anaconda, Inc.| (default, Sep 30 2017, 11:52:29) [MSC v.1900 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.12.1

**Comment by cgohlke** [comment]
I can reproduce this issue.

**Comment by cgohlke** [comment]
It's a bug in HDF5. It only handles uppercase drive letters in relative paths on Windows. See https://bitbucket.hdfgroup.org/projects/HDFFV/repos/hdf5/browse/src/H5system.c#1046

**Comment by cgohlke** [comment]
As a workaround, use `demo('D:file.hdf5')`

**Comment by hjaGT** [comment]
Works, thanx a lot

**Comment by cgohlke** [comment]
The hdfgroup opened `bug HDFFV-10307` for this issue.

**Comment by tacaswell** [comment]
Thanks @cgohlke !
