### ISSUE TITLE
pkgconfig and hardcoded paths unconditionally used even with explicit `--hdf5`

### ISSUE THREAD

**Issue by zao** [h5py/h5py#946]
* Ubuntu 16.04 LTS
 * Python  2.7.12 (default, Oct 17 2017, 19:04:42) [GCC Intel(R) C++ gcc 5.4 mode]
 * Self-built Python via EasyBuild, intelcuda/2016.11 toolchain.
 * h5py 2.7.0, 2.7.1
 * Self-built HDF5 1.10.0-patch1 via EasyBuild, same toolchain.

I have several concerns about how paths are gathered in `h5py`'s configure/build scripts.
There's two sources of paths that cannot be disabled, both the hardcoded `/usr/local/include` + `/opt/local/include` and the unconditional attempt to run `pkgconfig`.

This is fine if you're trying to catch all the places where HDF5 may be installed, but on my cluster, there's a system-installed HDF5 1.8.x that should never be used by non-distro software. It's only there because it's a mandatory dependency of some other package.

I have my own HDF5 build and specify it with `--hdf5=/foo` when invoking the setup. That installation does not have any `hdf5.pc` file, and as such, doesn't shadow the file from the system installation and the pkgconfig invocation "erroneously" picks up the one from the system.

I would like to argue that if a path for an HDF5 installation is explicitly specified, the scripts should not consider the hardcoded paths nor run pkgconfig.

**Comment by tacaswell** [comment]
Sounds reasonable,  would you mind taking a pass at fixing that?

**Comment by zao** [comment]
Sure, I'll try to make a PR once I've sorted out the debris from building software dependent on h5py.

**Comment by aragilar** [comment]
Closed via #947
