### ISSUE TITLE
fletcher32 checksum error with szip compression and 64bit numbers

### ISSUE THREAD

**Issue by paulmueller** [h5py/h5py#953]
* Operating System: Ubuntu 16.04.3 LTS
 * Python versions: 2.7.12 and 3.5.2
 * Where Python was acquired: system Python (apt-get)
 * h5py version: 2.6.0
 * HDF5 version: 1.8.16
 * The full traceback/stack trace shown (Python 3):
```
Traceback (most recent call last):
  File "error.py", line 12, in <module>
    print(h5["image_A"][0])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/_objects.c:2577)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/_objects.c:2536)
  File "/usr/lib/python3/dist-packages/h5py/_hl/dataset.py", line 482, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/_objects.c:2577)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/_objects.c:2536)
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/h5d.c:3123)
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/_proxy.c:1769)
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/_proxy.c:1411)
OSError: Can't read data (Data error detected by fletcher32 checksum)

```
error.py:
```python
import h5py
import numpy as np

with h5py.File("test.h5", "w") as h5:
    h5.create_dataset("image_A",
                      data=np.zeros(10000, dtype=np.float64),
                      fletcher32=True,
                      compression="szip",
                      )

with h5py.File("test.h5", "r") as h5:
    print(h5["image_A"][0])
```

The error does not occur, if either:
- ``compression`` is set to something other than "szip"
- ``dtype`` is set to something other than 64 bit

This can be very hard to reproduce (try to increase the number of zeros saved). The checksum error seems to be a result of szip compression with 64 bit numbers.

**Comment by aragilar** [comment]
I'm not aware of any reason this shouldn't work. How did you install h5py and HDF5?

**Comment by paulmueller** [comment]
Here is a simple way to reproduce this:
``
$ cd /tmp
$ virtualenv test_env -p python4
$ source test_env/bin/activate
$ pip install h5py
Collecting h5py
  Using cached h5py-2.7.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting numpy>=1.7 (from h5py)
  Downloading numpy-1.13.3-cp35-cp35m-manylinux1_x86_64.whl (16.9MB)
    100% |████████████████████████████████| 16.9MB 96kB/s 
Collecting six (from h5py)
  Using cached six-1.11.0-py2.py3-none-any.whl
Installing collected packages: numpy, six, h5py
Successfully installed h5py-2.7.1 numpy-1.13.3 six-1.11.0
$ pip freeze
h5py==2.7.1
numpy==1.13.3
pkg-resources==0.0.0
six==1.11.0
$ python error.py
Traceback (most recent call last):
  File "error.py", line 12, in <module>
    print(h5["image_A"][0])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/tmp/test_env/lib/python3.5/site-packages/h5py/_hl/dataset.py", line 496, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (data error detected by Fletcher32 checksum)
``
So this also happens with h5py 2.7.1.

How do I know how I installed HDF5 (Isn't it installed along with the wheel from PyPI)? Here is the output of the h5py tests:

```
>>> import h5py
>>> h5py.run_tests()
.....................................................x...................................................................x....................................s...s......ss....................................................................................................ssssss.................................................................x....x........................x.....x.......................................ssssssssss..................
----------------------------------------------------------------------
Ran 446 tests in 0.472s

OK (skipped=20, expected failures=6)
<unittest.runner.TextTestResult run=446 errors=0 failures=0>
```

**Comment by paulmueller** [comment]
Note that if I reduce the size of zeros written (e.g. ``data=np.zeros(2600, dtype=np.float64),``), then the error does **not always** occur. Sometimes it works, sometimes not.

**Comment by aragilar** [comment]
I can reproduce this (using libaec for szip, which is the same as the wheels on PyPI). I'd recommend posting to the HDF5 mailing list (see https://support.hdfgroup.org/services/lists.html), and see if someone else has encountered this (as there's not much we can do inside h5py, other than raise an exception if there's some reason this is fundamentally broken). You can also try the h5py mailing list (https://groups.google.com/forum/#!forum/h5py).

**Comment by paulmueller** [comment]
UPDATE:
I was not successful in subscribing to the HDF5 forum mailing list (a moderator needs to confirm my subscription request?). I also asked at the h5py mailing list (https://groups.google.com/forum/?#!topic/h5py/5ZrTwu3G408) without any replies so far.

**Comment by epourmal** [comment]
Paul,

I think you need to change the order of the filters and have szip in the create call first. I've just answered you on the hdf-forum.

Elena

**Comment by paulmueller** [comment]
@epourmal Thanks! I will post to the mailing list again once this is resolved in h5py.

@aragilar 
As suggested by Elena, it is an ordering-problem in the filters.

If I move the fletcher32 lines:
https://github.com/h5py/h5py/blob/master/h5py/_hl/filters.py#L178-L180
below the compression stuff (currently L204), then my example script works.

However, I am not sure if this would not introduce additional errors/regressions, because there are a couple of comments in the code regarding ordering of fletcher32 and scale/offset.

I guess this would be an easy fix. Could you please have a look?

**Comment by aragilar** [comment]
I wonder about the 1.6/1.8 problem mentioned. We don't support 1.6 any more, however we're apparently still building against them (see https://groups.google.com/forum/#!searchin/h5py/1.6|sort:date/h5py/X68CHo9y3S4/Y5dDAfRFy3YJ).

Using scaleoffset and fletcher32 at the same time appears to be prevented, so I don't think that particular case is a problem.

**Comment by paulmueller** [comment]
@aragilar I guess then I could just go ahead and create a PR?

**Comment by aragilar** [comment]
@paulmueller Sure, go ahead. Can you make sure to include tests so we can make sure this doesn't break again.

**Comment by takluyver** [comment]
Cross-linking the [forum thread](https://forum.hdfgroup.org/t/fletcher32-checksum-error-with-szip-compression-and-64bit-data/4141/2) for reference.

If I've understood correctly, the issue is that szip, unlike zlib/lzf, knows about the element size (bits per pixel), and presumably expects the data size to be a multiple of that. If the dtype is 1, 2, or 4 bytes, then the extra 4-byte checksum just looks like another 1-4 numbers, and it's fine. But if the dtype is 8 bytes, adding 4 bytes means the total length is not a multiple of 8.
