### ISSUE TITLE
Cannot create H5T_ARRAY attribute

### ISSUE THREAD

**Issue by anemes** [h5py/h5py#955]
There is an existing hdf5 structure that I am trying to emulate with h5py.

In this, there is an attribute that `h5dump` reports as
```
            ATTRIBUTE "spacing" {
               DATATYPE  H5T_ARRAY { [3] H5T_IEEE_F32LE }
               DATASPACE  SCALAR
               DATA {
               (0): [ 13, 14, 15 ]
               }
            }
```

No matter how I pass the values `[13,14,15]` to `.attrs.create` or with what `dtype`, I do not end up with a `DATATYPE H5T_ARRAY`, but with `DATATYPE H5T_IEEE_F32LE`

```
            ATTRIBUTE "spacing" {
               DATATYPE  H5T_IEEE_F32LE
               DATASPACE  SIMPLE { ( 3 ) / ( 3 ) }
               DATA {
               (0): 13, 14, 15
               }
            }
```

Is there a way to force `H5T_ARRAY` attribute datatypes?

 * Operating System CentOS 7
 * Python version 3.5
 * SCL Python
 * h5py version 2.7.1
 * HDF5 version 1.8.18

**Comment by aragilar** [comment]
There's no way to force the high-level interface to use a particular format, other than specifying dtype. I suggest using the low-level interface to create the attribute.

**Comment by anemes** [comment]
I didn't look deep enough into the documentation. Thank you!
