### ISSUE TITLE
Update h5py for numpy 1.14

### ISSUE THREAD

**Issue by aragilar** [h5py/h5py#969]
https://github.com/numpy/numpy/pull/6053 has changed how structured dtypes function. This issue is to track the things needed to have h5py function correctly on numpy 1.14.

- [x] Update our dtype -> HDF5 code based on https://github.com/h5py/h5py/pull/793#discussion_r158746103 (#970).
 - [ ] Make a release with the associated fix (2.8).

**Comment by thomasaarholt** [comment]
It would be nice to get a minor release fixing this.

**Comment by alanhdu** [comment]
Hi!

Are there any blockers for releasing `2.7.2` or `2.8`? We're eagerly awaiting an h5py update, and I'd be happy to spend some time digging through anything necessary to get the release out.

**Comment by tacaswell** [comment]
The delay is currently me finding time to do the release.  There should be an rc in the next day or two with a final a week or so after that.
