### ISSUE TITLE
Mac builds distributed through pip are using HDF5 1.8 and not 1.10

### ISSUE THREAD

**Issue by rleigh-codelibre** [h5py/h5py#972]
* MacOS X using Python 2.7.14 and 3.6.4 from homebrew
* h5py 2.7.1 (built against hdf5 1.8.18 which is embedded in both cases), the default installed with pip

I'm creating HDF5 files with h5py on another system (Ubuntu 17.10 with h5py 2.7.1 built against hdf 1.10.0 for both python 2.7.14 and 3.6.3).  I'm deliberately using the latest version (with `libver='latest'`) because the size of the dtypes I'm using (~200 fields in the structures I'm storing) can't be handled with 1.8 and earlier; 1.10 is required.  I can create and read these just fine on Ubuntu.  However, on MacOS X these files are unreadable because the HDF5 version embedded in h5py is too old.

In the interest of interoperability, please could you consider updating the HDF5 version in use?  This is similar to https://github.com/h5py/h5py/issues/880 and is likely something which needs doing for all the platforms you support.  As more people start to require 1.10 features, h5py should support reading and writing with such features enabled.

Thanks,
Roger

**Comment by tacaswell** [comment]
2.8 wheels are built using hdf5 1.10.
