### ISSUE TITLE
RFC: implement proper support for strings

### ISSUE THREAD

**Issue by wavexx** [h5py/h5py#973]
I know I can read utf8 and somewhat work-around writing by manually encoding(), but I *need* to be able to write compound datatypes with strings with the *proper* encoding set (usually utf8) in order to write compliant hd5 files. This is currently impossible.

As outlined in other PRs and issues I've seen, python2 handling of strings should be the exception, not the norm.

After reading the source a bit, I'd propose the following scheme:

- Actually use numpy's "V" type for bytes (vlen or not) and map it properly to H5T_OPAQUE.
- Map str in python3 (or unicode in python2) to type "S", but include an extra attribute in the constructor of the dtype: ``dtype("S", metadata={"encoding": encoding})``.
- The encoding should default to CSET_UTF8 in python3, and CSET_ASCII for plain 'str' objects in python2.
- Assigning an encoding manually (for example, to write ascii string columns in python3) can be done by explicitly constructing the dtype, as currently done for vlen strings. Combining encoding and vlen information becomes the norm, not the exception. No special handling required.
- Reading is unambiguous: H5T_STRING always yields an "S" dtype, an unicode object in python2 and an str object in python3. We can now use the encoding attribute to decode the string to the current python str's object correctly.
- Type 'U' still has no equivalent mapping in h5t and should still be rejected.

This scheme allows stuffing padded, variable-length UTF8-encoded strings in numpy matrices/records without losing any encoding information. We always preserve the encoding via the metadata dict.

Is is debatable whether reading a ``CSET_ASCII`` string in python2 should yield a str or not. I'd go for unicode, always. The reasoning is that reading and later writing the very same objects should yield the same on-disk representation.

Manually reading the binary content via read_bytes is already uniform in both python2 and python3.

Any issues or insights for the above proposal? I did a few tests to make sure it's feasible, and I could work on implementing it in the next weeks.

**Comment by aragilar** [comment]
@wavexx I'll need to have a look at this in detail (and so my response may not be relevant), but some things which need to keep in mind are backwards compatibility, and unix vs. windows string handling. I'm also not inclined to completely change how strings work on Python 2, given that Python 2 is going away soon (and so in the unlikely event we change a whole bunch of things about strings, we'd want to do it post dropping Python 2).

**Comment by aragilar** [comment]
Going through each of the points:

> Actually use numpy's "V" type for bytes (vlen or not) and map it properly to H5T_OPAQUE.

What do you mean by bytes? The Python 3 `bytes` type? What happens on Python 2 (we're not changing what happens with Python 2 strings, that'd be a breaking change)?

> Map str in python3 (or unicode in python2) to type "S", but include an extra attribute in the constructor of the dtype: dtype("S", metadata={"encoding": encoding}).

I've got some of the work done in https://github.com/aragilar/h5py/tree/enforce_str_type, which I plan on finishing at some point. You can go ahead a finish this (and integrate it with https://github.com/h5py/h5py/pull/871). I vaguely remember seeing discussion of numpy's string types in issues and on the mailing list which could break this, it may be worth discussing on the numpy mailing list about getting a better type created.

> The encoding should default to CSET_UTF8 in python3, and CSET_ASCII for plain 'str' objects in python2.

The encoding use should be detected, not assumed, and done as early in process as possible. We should encode to the most compatible encoding (i.e. if the string is entirely ASCII, use ASCII).

> Assigning an encoding manually (for example, to write ascii string columns in python3) can be done by explicitly constructing the dtype, as currently done for vlen strings. Combining encoding and vlen information becomes the norm, not the exception. No special handling required.

See the previously mentioned branch.

> Reading is unambiguous: H5T_STRING always yields an "S" dtype, an unicode object in python2 and an str object in python3. We can now use the encoding attribute to decode the string to the current python str's object correctly.

Only scalar attributes should be decoded. Everything else should remain as numpy arrays. We should also not change the behaviour on Python 2.

> Type 'U' still has no equivalent mapping in h5t and should still be rejected.

Agreed (I dislike how in the docs we use the wording "no equivalent mapping", as that completely sidesteps the problem that HDF5, numpy and Python (and the 2 vs. 3) have different philosophies for how strings work, but that's something we can address separately).

**Comment by wavexx** [comment]
On Tue, Jan 09 2018, James Tocknell wrote:
>> Actually use numpy's "V" type for bytes (vlen or not) and map it
>> properly to H5T_OPAQUE.
>
> What do you mean by bytes? The Python 3 `bytes` type? What happens on
> Python 2 (we're not changing what happens with Python 2 strings,
> that'd be a breaking change)?

How can you currently write an opaque record in python2?

> I've got some of the work done in
> https://github.com/aragilar/h5py/tree/enforce_str_type, which I plan
> on finishing at some point. You can go ahead a finish this (and
> integrate it with https://github.com/h5py/h5py/pull/871). I vaguely
> remember seeing discussion of numpy's string types in issues and on
> the mailing list which could break this, it may be worth discussing on
> the numpy mailing list about getting a better type created.

Could you outline your approach a bit?

It seems you cannot create a vlen str type with a specific encoding
using special_dtype, even though there shouldn't be this restriction.

> The encoding use should be detected, not assumed, and done as early in
> process as possible. We should encode to the most compatible encoding
> (i.e. if the string is entirely ASCII, use ASCII).

By detect I mean use ascii for str, and UTF8 for unicode types, unless a
codec is manually specified (in which case, it's just to downcast a
python3 string type to plain ascii).

>> Assigning an encoding manually (for example, to write ascii string columns in python3) can be done by explicitly constructing the dtype, as currently done for vlen strings. Combining encoding and vlen information becomes the norm, not the exception. No special handling required.
>
> See the previously mentioned branch.

Even after using h5py for a while, I don't especially like special_dtype
too much. I really preferred if the manual stated that you can just
create a dtype with the right attributes (with special_dtype existing
just as a "convenience").

> Only scalar attributes should be decoded. Everything else should
> remain as numpy arrays. We should also not change the behaviour on
> Python 2.

Scalar attributes are not really a problem for me (even currently).
The issue is record types with explicit encoding.

**Comment by aragilar** [comment]
> How can you currently write an opaque record in python2?

http://docs.h5py.org/en/latest/strings.html#how-to-store-raw-binary-data has how to write binary data, wrap the data in np.void. Implicitly converting from Python 3 `bytes` to void isn't going to happen.

> Could you outline your approach a bit? It seems you cannot create a vlen str type with a specific encoding using special_dtype, even though there shouldn't be this restriction.

I may have not created the high level interface yet, that code is still WIP, but from a user perspective, you'd create a string type with the correct encoding, which you'd then either use in a numpy array (for fixed size), or pass as the vlen argument (for variable size).

> By detect I mean use ascii for str, and UTF8 for unicode types, unless a codec is manually specified (in which case, it's just to downcast a python3 string type to plain ascii).

I'm confused about what you're suggesting here, there are 4 possible things  (excluding h5py specific things where we have encoding info) we can get: a bytestring of unknown encoding (py2 `str`, py3 `unicode`); a "unicode" string of known encoding (py2 `unicode`, py3 `str`); a numpy array with dtype `np.bytes_` (which has unknown encoding); and a numpy array with dtype `np.unicode_` (which uses UTF-32, so known). The first two are scalar, we need to determine the encoding for the bytestring (we cannot assume anything here), whereas the "unicode" string we can try ASCII, and if that fails use UTF-8. For the numpy arrays, we don't accept `np.unicode_`, and we need to determine the encoding, same as the bytestring.

> Even after using h5py for a while, I don't especially like special_dtype too much. I really preferred if the manual stated that you can just create a dtype with the right attributes (with special_dtype existing just as a "convenience").

The `metadata` attribute is very underspecified in the numpy docs, whilst we use it (and so is implicitly part of h5py API), if numpy were to change or remove it (as has been suggested in issues and on the mailing list), then h5py would presumably have to come up with a different method of storing the metadata (so code using `special_dtype` would still work, but code handling the metadata manually would break).

**Comment by takluyver** [comment]
I've updated the milestone here to 2.10, because this looks like a big topic, and we're aiming for a 2.9 release fairly soon. @tacaswell @aragilar feel free to change it back and let me know if the aim is to have this resolved for 2.9.

I'm going to go through the [issues for the 2.9 milestone](https://github.com/h5py/h5py/milestone/14) and possibly bump some others to 2.10 as well.

**Comment by takluyver** [comment]
I've bumped the milestone again, for much the same reasons as I did a few months ago.

Once 2.10 is out, I hope we can come to a consensus on whether & what to change about string handling.

**Comment by wavexx** [comment]
I've long moved on since I needed this, but I do hope it does get more love.

I had to write my own thin wrapper around libhdf5 to work around this and other performance issues in h5py.

**Comment by tacaswell** [comment]
@wavexx Are there issues for the other performance issues?

**Comment by aragilar** [comment]
I think #1338 covers this, so I'm going to close this.
