### ISSUE TITLE
Creating an h5py wheel does not bundle libhdf5 library (.libs dir) unlike in releases

### ISSUE THREAD

**Issue by kirku1g** [h5py/h5py#978]
* Operating System: Debian Jessie
 * Python version 2.7
 * Where Python was acquired: System Package
 * h5py version: 2.7.1
 * HDF5 version: 1.10.1

I am trying to create a wheel which is equivalent to the official h5py releases that includes libhdf5 1.10 for Single Write Multiple Read support. The benefit of including this library in the wheel is that it can be deployed on systems where libhdf5 1.10 isn't available as a package. The built Cython extension modules in official release wheels link against libraries which are included in a .libs subdirectory. When creating new wheels, the .libs subdirectory is omitted and the extension modules link against system level libraries. I can't find a configure/setup option to include these libraries in a wheel.

Thanks!

**Comment by tacaswell** [comment]
Look at https://github.com/MacPython/h5py-wheels which is what builds the official wheels.

I am more open to the official wheels bundling 1.10 than the last time it was discussed.

**Comment by aragilar** [comment]
There is no support inside h5py's various setup scripts for building non-system specific wheels (wheels that can be used on more than one computer/system). There used to be some support for Windows, but that was dropped a while back. Building non-system specific wheels for h5py requires having the correct environment (which the manylinux tooling sets up to some extent), which is way beyond what setup.py can or should be doing.

**Comment by kirku1g** [comment]
Thank you for explaining how the release wheels are built and why it exceeds the scope of the package's setup.py. It's exactly what I needed to build custom wheels with bundled libraries for painfully old servers :+1:
