### ISSUE TITLE
Error while importing h5py

### ISSUE THREAD

**Issue by cdeepakroy** [h5py/h5py#981]
I am on Ubuntu 16.04 LTS and running on system python 2.7.12.

I pip installed h5py (version 2.7.1) and tried to import it using `python -c "import h5py"` which throws the following error:

> 
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/usr/local/lib/python2.7/dist-packages/h5py/__init__.py", line 36, in <module>
>     from ._conv import register_converters as _register_converters
>   File "h5py/h5t.pxd", line 14, in init h5py._conv
>   File "h5py/numpy.pxd", line 66, in init h5py.h5t
>   File "/usr/local/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
>     from . import add_newdocs
>   File "/usr/local/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
>     from numpy.lib import add_newdoc
>   File "/usr/local/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 23, in <module>
>     from .npyio import *
>   File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 14, in <module>
>     from ._datasource import DataSource
>   File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 220, in <module>
>     _file_openers = _FileOpeners()
>   File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 162, in __init__
>     self._file_openers = {None: io.open}
> AttributeError: 'module' object has no attribute 'open'

I tried uninstalling numpy and h5py and reinstalling them using pip, but the error doesnt go away.

My numpy version is 1.14.0.

**Comment by aragilar** [comment]
@cdeepakroy That looks like a bug in numpy. Are you able to import numpy?

**Comment by cdeepakroy** [comment]
You were right! I reinstalled numpy again (ignoring cache) and the error went away. Feel free to close the issue!
