### ISSUE TITLE
h5py.h5f.open fails in python 3.6

### ISSUE THREAD

**Issue by quakberto** [h5py/h5py#986]
Hi,

using the low level interface of h5py I get an error when using python 3.6:

    # create a file
    path = 'temp.h5'
    f = h5py.File(path,'w')
    f.close()

    # try to access it using the low level h5py interface
    h5py.h5f.open(path)

> TypeError: expected bytes, str found

The same code in python 2.7 works without problems. I would guess it has to do with python 3 making the difference between byte objects and strings (or binary and text files)?

**Fails on:**

h5py    2.7.1
HDF5    1.10.1
Python  3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49)
[GCC 7.2.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.13.3

**Works on:**

h5py    2.7.0
HDF5    1.8.17
Python  2.7.12 |Anaconda 2.4.1 (64-bit)| (default, Jul  2 2016, 17:42:40)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
sys.platform    linux2
sys.maxsize     9223372036854775807
numpy   1.13.1

Kind regards

**Comment by aragilar** [comment]
The low-level h5py interface is designed to be as thin as possible. Dealing with encodings in the low-level interface would involve duplication of existing code, and we'd still need to expose an direct interface to the HDF5 code. So we're not going to support non-encoded strings inputs to `h5py.h5f.open`. If you need to interact with h5py's low level code, open the file normally, then access the low-level information via the id attributes.
