### ISSUE TITLE
Importing h5py from sitecustomize.py fails in Python2

### ISSUE THREAD

**Issue by vadimkantorov** [h5py/h5py#996]
* Operating System: Ubuntu 16.04.1 LTS
 * Python version: 2.7.12
 * Where Python was acquired: system Python
 * h5py version: 2.7.0
 * HDF5 version: 1.8.18

------

I created two files:
```python
# sitecustomize.py
import h5py
```
```python
# foo.py
print(1)
```

Running `python2 -v foo.py` (produces a huge log, better dump it somewhere) fails with:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 513, in execsitecustomize
    import sitecustomize
  File ".../testsitecustomize/sitecustomize.py", line 1, in <module>
    import h5py
  File ".../lib/python2.7/site-packages/h5py/__init__.py", line 60, in <module>
    from .tests import run_tests
  File ".../lib/python2.7/site-packages/h5py/tests/__init__.py", line 15, in <module>
    from . import old, hl
  File ".../lib/python2.7/site-packages/h5py/tests/old/__init__.py", line 4, in <module>
    from . import ( test_attrs,
  File ".../lib/python2.7/site-packages/h5py/tests/old/test_group.py", line 41, in <module>
    fsencode(u"α")
  File ".../lib/python2.7/site-packages/h5py/_hl/compat.py", line 68, in fsencode
    return filename.encode(encoding, errors)
TypeError: encode() argument 1 must be string, not None
```

Running `python3 foo.py` or `python2 -c "import h5py"` works without issues.

I'm using `sitecustomize.py` in an attempt to hack another software and mock some modules it uses.

**Comment by aragilar** [comment]
The problem is that for some reason we can't get the file system encoding (it may be python hasn't set it up yet, or a problem with your system). We may need to fall back to https://docs.python.org/2/library/sys.html#sys.getdefaultencoding, but if that also returns None, then upgrading to Python 3 is going to be the correct solution.

**Comment by vadimkantorov** [comment]
I'm using a stock Python 2 of Ubuntu 16.04 with h5py installed by pip to a custom location.

```python
import sys
sys.getdefaultencoding()
# 'ascii'
```

**Comment by aragilar** [comment]
That suggests that the encoding system isn't correctly set up when sitecustomize is run on python2 (there was a reordering of the startup in python3), there's not much we can do from the perspective of h5py, except recommend using python 3 (which given http://www.python3statement.org/, is something everyone should be doing).

**Comment by vadimkantorov** [comment]
This is not a blocking issue for me, and I agree that Python 3 is the way to go.

Though, in theory, should `h5py` default to `sys.getdefaultencoding()` if it makes sense?

**Comment by aragilar** [comment]
`sys.getdefaultencoding` is always ascii apparently (I thought it might also use the locale settings, but apparently not), which is not what we want (we want to encode unicode, most likely filenames). This only comes up in the startup of python2 (not python 3), so failing early is better that failing later.
