### ISSUE TITLE
file space strategy and persist or not

### ISSUE THREAD

**Issue by rimmartin** [h5py/h5py#997]
hdf5 1.10.x functionality

Hi, I don't see the ability to set file space strategy or persist state.  Some fork is working on it or should I fork?

I want the capability of
https://support.hdfgroup.org/HDF5/doc/RM/RM_H5P.html#Property-SetFileSpaceStrategy

to set file space strategy and particularly persist boolean to allow a created h5 to reclaim file space.  Relates to FS_PERSIST from 
h5repack -P 0 
where FS_PERSIST is zero.

**Comment by aragilar** [comment]
As far as I know, no-one is working on this, feel free to create PRs.

**Comment by tacaswell** [comment]
Closing in favor of #1100 which has more discussion.
